### ISSUE TITLE
1k issue

### ISSUE THREAD

**Issue by sam01101** [Mrs4s/go-cqhttp#1000]
好耶！

**Comment by noahzark** [comment]
好耶！

**Comment by ishkong** [comment]
这个issue为啥没有被bot close？

**Comment by timi137137** [comment]
> > 这个issue为啥没有被bot close？
> 
> 这个是一个以特殊的方式开的issue，所以不适用于被bot检测

因为你没添加bug label xd（别问我为什么知道）

**Comment by sam01101** [comment]
你猜下怎么样才可以不加label（

**Comment by timi137137** [comment]
> 你猜下怎么样才可以不加label（

我试过了，只要不走模板就行了x
