### ISSUE TITLE
/send_msg 发送群消息字符超100后报错

### ISSUE THREAD

**Issue by eggnice** [Mrs4s/go-cqhttp#1001]
**环境信息**

go-cqhttp版本:  当前版本:v1.0.0-beta5
运行环境:  centos 7
连接方式:  http
使用协议: ipad

**bug内容**

send_msg 发送群消息当message超过100个字符无法发送

log：
[2021-08-12 10:06:50] [DEBUG]: HTTPServer接收到API调用: send_msg 
2021/08/12 10:06:50 http: panic serving 10.1.177.73:51199: runtime error: invalid memory address or nil pointer dereference
goroutine 105 [running]:
net/http.(*conn).serve.func1(0xc0001620a0)
	net/http/server.go:1824 +0x153
panic(0xd67ce0, 0x1547be0)
	runtime/panic.go:971 +0x499
github.com/Mrs4s/MiraiGo/message.(*ServiceElement).Pack(0x0, 0xfad140, 0x0, 0x7fa986e60750)
	github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/message/pack.go:84 +0x37
github.com/Mrs4s/MiraiGo/message.ToProtoElems(0xc00051f280, 0x1, 0x1, 0xc00038d101, 0x47a5bf, 0xd57660, 0xc0005a08d0)
	github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/message/message.go:285 +0x59a
github.com/Mrs4s/MiraiGo/client.(*QQClient).buildGroupSendingPacket(0xc00029c480, 0x2153fc25, 0x1fd90f551, 0x0, 0x0, 0xc00051f280, 0x1, 0x1, 0xc00059c228, 0xedcc98, ...)
	github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/group_msg.go:255 +0x17b
github.com/Mrs4s/MiraiGo/client.(*QQClient).sendGroupMessage(0xc00029c480, 0x2153fc25, 0xc00038d300, 0xc00038d3d0, 0x0)
	github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/group_msg.go:129 +0x86c
github.com/Mrs4s/MiraiGo/client.(*QQClient).SendGroupMessage(0xc00029c480, 0x2153fc25, 0xc00038d6b8, 0xc00066d45f, 0x1, 0x1, 0xc00066d4c8)
	github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/group_msg.go:53 +0x359
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).SendGroupMessage(0xc0000fe300, 0x2153fc25, 0xc00066d6b8, 0x0)
	github.com/Mrs4s/go-cqhttp/coolq/bot.go:292 +0x2d7
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSendGroupMessage(0xc0000fe300, 0x2153fc25, 0x3, 0xc00039603a, 0x68, 0xc00039603b, 0x66, 0x0, 0x3a, 0x1, ...)
	github.com/Mrs4s/go-cqhttp/coolq/api.go:391 +0xa59
github.com/Mrs4s/go-cqhttp/server.sendMSG(0xc0000fe300, 0xfad360, 0xc00052c910, 0x8)
	github.com/Mrs4s/go-cqhttp/server/api.go:63 +0x88e
github.com/Mrs4s/go-cqhttp/server.(*apiCaller).callAPI(0xc00007e040, 0xc00052a036, 0x8, 0xfad360, 0xc00052c910, 0x1)
	github.com/Mrs4s/go-cqhttp/server/api.go:425 +0x409
github.com/Mrs4s/go-cqhttp/server.(*httpServer).ServeHTTP(0xc00007e000, 0xfba9c0, 0xc0001fc9a0, 0xc000142100)
	github.com/Mrs4s/go-cqhttp/server/http.go:113 +0x265
net/http.serverHandler.ServeHTTP(0xc0004080e0, 0xfba9c0, 0xc0001fc9a0, 0xc000142100)
	net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0001620a0, 0xfbc7f0, 0xc000368040)
	net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	net/http/server.go:3013 +0x39b

**复现方法**

100字符正常发送：
curl -vvv -H "Content-Type:application/json" -d '{"message_type":"group","group_id":"559152165", "message":"1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111","auto_escape":true}' http://10.2.145.233:5700/send_msg
*   Trying 10.2.145.233...
* TCP_NODELAY set
* Connected to 10.2.145.233 (10.2.145.233) port 5700 (#0)
> POST /send_msg HTTP/1.1
> Host: 10.2.145.233:5700
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Type:application/json
> Content-Length: 180
> 
* upload completely sent off: 180 out of 180 bytes
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Date: Thu, 12 Aug 2021 02:06:40 GMT
< Content-Length: 60
< 
{"data":{"message_id":538214748},"retcode":0,"status":"ok"}
* Connection #0 to host 10.2.145.233 left intact
* Closing connection 0

102字符发送失败：
curl -vvv -H "Content-Type:application/json" -d '{"message_type":"group","group_id":"559152165", "message":"111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111","auto_escape":true}' http://10.2.145.233:5700/send_msg
*   Trying 10.2.145.233...
* TCP_NODELAY set
* Connected to 10.2.145.233 (10.2.145.233) port 5700 (#0)
> POST /send_msg HTTP/1.1
> Host: 10.2.145.233:5700
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Type:application/json
> Content-Length: 182
> 
* upload completely sent off: 182 out of 182 bytes
* Empty reply from server
* Connection #0 to host 10.2.145.233 left intact
curl: (52) Empty reply from server
* Closing connection 0

**Comment by wdvxdr1123** [comment]
看上去是长消息上传失败， 可能和 #983 有关
