### ISSUE TITLE
环境变量增加数据库是否启用的配置参数

### ISSUE THREAD

**Issue by 502647092** [Mrs4s/go-cqhttp#1002]
环境变量增加数据库是否启用的配置参数

**Comment by timi137137** [comment]
感觉其实并没有必要，在环境变量添加这个设置的意义在哪里。目前有yml配置文件控制就够了，并且不一定人人一台服务器只放一个gocq。

**Comment by 502647092** [comment]
@timi137137 因为我是用Docker容器批量启动的 不依赖config文件 只持久化了Session文件
而且环境变量启动的情况下 好像不会生成配置文件啊

**Comment by timi137137** [comment]
@502647092 建议标题改成 建议Docker下使用环境变量控制数据库配置 或 建议Docker下移除yml文件采用环境变量配置
