### ISSUE TITLE
调用event.json（）报错

### ISSUE THREAD

**Issue by chrisyang2003** [Mrs4s/go-cqhttp#1004]
**描述问题：**
调用event.json()报错

**如何复现？**
在handle中调用event.json

**环境信息：**

 - OS: linux
 - Python Version: python3.9.0
 - Nonebot Version: 2

**协议端信息：**

 - 协议端: cqhttp
 - 协议端版本: 1.0.0.beta4

**截图或日志**
调用event.json()报错
![image](https://user-images.githubusercontent.com/63803385/129255709-09a6f728-f863-4081-a87c-5b335bf89587.png)

**Comment by AkiraXie** [comment]
首先这是nonebot2的问题，这里是go-cqhttp，请注意repo。
其次，这个问题在今日凌晨nb2升级2.00a15后已解决，请留意。
