### ISSUE TITLE
运行时错误：无效内存地址或零指针解引用

### ISSUE THREAD

**Issue by kaliisra** [Mrs4s/go-cqhttp#1006]
**环境信息**

go-cqhttp版本: 
运行环境: 
连接方式: 
使用协议: 

**在最新的release版本中能否复现**

**bug内容**
2021/08/14 11:34:00 http: panic serving 127.0.0.1:57254: runtime error: invalid memory address or nil pointer dereference
goroutine 203703 [running]:
net/http.(*conn).serve.func1(0xc0002a5e00)
	net/http/server.go:1824 +0x153
panic(0xd67ce0, 0x1547be0)
	runtime/panic.go:971 +0x499
github.com/Mrs4s/MiraiGo/message.(*ServiceElement).Pack(0x0, 0xfad140, 0x0, 0x7fafdbf31890)
	github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/message/pack.go:84 +0x37
github.com/Mrs4s/MiraiGo/message.ToProtoElems(0xc00087d540, 0x1, 0x1, 0xc0004ff101, 0x47a5bf, 0xd57660, 0xc00061f080)
	github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/message/message.go:285 +0x59a
github.com/Mrs4s/MiraiGo/client.(*QQClient).buildGroupSendingPacket(0xc0001fc480, 0x23564913, 0x17fe7396c, 0x0, 0x0, 0xc00087d540, 0x1, 0x1, 0xc0006f8268, 0xc000415440, ...)
	github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/group_msg.go:255 +0x17b
github.com/Mrs4s/MiraiGo/client.(*QQClient).sendGroupMessage(0xc0001fc480, 0x23564913, 0xc0004ff300, 0xc0004ff3d0, 0x0)
	github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/group_msg.go:129 +0x86c
github.com/Mrs4s/MiraiGo/client.(*QQClient).SendGroupMessage(0xc0001fc480, 0x23564913, 0xc0004ff6b8, 0xc0004ff45f, 0x1, 0x1, 0x1)
	github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/group_msg.go:53 +0x359
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).SendGroupMessage(0xc00034e000, 0x23564913, 0xc0004ff6b8, 0xc000174201)
	github.com/Mrs4s/go-cqhttp/coolq/bot.go:292 +0x2d7
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSendGroupMessage(0xc00034e000, 0x23564913, 0x3, 0x0, 0x0, 0xc0001742d0, 0x8e, 0x0, 0x0, 0x0, ...)
	github.com/Mrs4s/go-cqhttp/coolq/api.go:391 +0xa59
github.com/Mrs4s/go-cqhttp/server.sendMSG(0xc00034e000, 0xfad360, 0xc00088df40, 0x8)
	github.com/Mrs4s/go-cqhttp/server/api.go:69 +0x4ce
github.com/Mrs4s/go-cqhttp/server.(*apiCaller).callAPI(0xc000221620, 0xc00040a1e6, 0x8, 0xfad360, 0xc00088df40, 0x1)
	github.com/Mrs4s/go-cqhttp/server/api.go:425 +0x409
github.com/Mrs4s/go-cqhttp/server.(*httpServer).ServeHTTP(0xc0002215e0, 0xfba9c0, 0xc00016d420, 0xc000532200)
	github.com/Mrs4s/go-cqhttp/server/http.go:113 +0x265
net/http.serverHandler.ServeHTTP(0xc000458460, 0xfba9c0, 0xc00016d420, 0xc000532200)
	net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0002a5e00, 0xfbc7f0, 0xc00067b380)
	net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	net/http/server.go:3013 +0x39b

![7OSQ@R0VVAS3O{~TZ)()3E3](https://user-images.githubusercontent.com/66672984/129433047-843d4f61-badc-4933-aeea-c4a6c27ec98e.png)

**复现方法**
发消息时突然出现的错误，内容不长

**Comment by kaliisra** [comment]
> **环境信息**
> 
> go-cqhttp版本:v1.0.0-beta5
> 运行环境:linux amd64
> 连接方式:http
> 使用协议:http
> 
> **在最新的release版本中能否复现**
> 
> **bug内容**
> 2021/08/14 11:34:00 http: panic serving 127.0.0.1:57254: runtime error: invalid memory address or nil pointer dereference
> goroutine 203703 [running]:
> net/http.(*conn).serve.func1(0xc0002a5e00)
> net/http/server.go:1824 +0x153
> panic(0xd67ce0, 0x1547be0)
> runtime/panic.go:971 +0x499
> github.com/Mrs4s/MiraiGo/message.(*ServiceElement).Pack(0x0, 0xfad140, 0x0, 0x7fafdbf31890)
> github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/message/pack.go:84 +0x37
> github.com/Mrs4s/MiraiGo/message.ToProtoElems(0xc00087d540, 0x1, 0x1, 0xc0004ff101, 0x47a5bf, 0xd57660, 0xc00061f080)
> github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/message/message.go:285 +0x59a
> github.com/Mrs4s/MiraiGo/client.(*QQClient).buildGroupSendingPacket(0xc0001fc480, 0x23564913, 0x17fe7396c, 0x0, 0x0, 0xc00087d540, 0x1, 0x1, 0xc0006f8268, 0xc000415440, ...)
> github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/group_msg.go:255 +0x17b
> github.com/Mrs4s/MiraiGo/client.(*QQClient).sendGroupMessage(0xc0001fc480, 0x23564913, 0xc0004ff300, 0xc0004ff3d0, 0x0)
> github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/group_msg.go:129 +0x86c
> github.com/Mrs4s/MiraiGo/client.(*QQClient).SendGroupMessage(0xc0001fc480, 0x23564913, 0xc0004ff6b8, 0xc0004ff45f, 0x1, 0x1, 0x1)
> github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/group_msg.go:53 +0x359
> github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).SendGroupMessage(0xc00034e000, 0x23564913, 0xc0004ff6b8, 0xc000174201)
> github.com/Mrs4s/go-cqhttp/coolq/bot.go:292 +0x2d7
> github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSendGroupMessage(0xc00034e000, 0x23564913, 0x3, 0x0, 0x0, 0xc0001742d0, 0x8e, 0x0, 0x0, 0x0, ...)
> github.com/Mrs4s/go-cqhttp/coolq/api.go:391 +0xa59
> github.com/Mrs4s/go-cqhttp/server.sendMSG(0xc00034e000, 0xfad360, 0xc00088df40, 0x8)
> github.com/Mrs4s/go-cqhttp/server/api.go:69 +0x4ce
> github.com/Mrs4s/go-cqhttp/server.(*apiCaller).callAPI(0xc000221620, 0xc00040a1e6, 0x8, 0xfad360, 0xc00088df40, 0x1)
> github.com/Mrs4s/go-cqhttp/server/api.go:425 +0x409
> github.com/Mrs4s/go-cqhttp/server.(*httpServer).ServeHTTP(0xc0002215e0, 0xfba9c0, 0xc00016d420, 0xc000532200)
> github.com/Mrs4s/go-cqhttp/server/http.go:113 +0x265
> net/http.serverHandler.ServeHTTP(0xc000458460, 0xfba9c0, 0xc00016d420, 0xc000532200)
> net/http/server.go:2887 +0xa3
> net/http.(*conn).serve(0xc0002a5e00, 0xfbc7f0, 0xc00067b380)
> net/http/server.go:1952 +0x8cd
> created by net/http.(*Server).Serve
> net/http/server.go:3013 +0x39b
> 
> ![7OSQ@R0VVAS3O{~TZ)()3E3](https://user-images.githubusercontent.com/66672984/129433047-843d4f61-badc-4933-aeea-c4a6c27ec98e.png)
> 
> **复现方法**
> 发消息时突然出现的错误，内容不长

**Comment by wdvxdr1123** [comment]
duplicate of #1001
