### ISSUE TITLE
私聊音乐分享收不到，显示消息id为0

### ISSUE THREAD

**Issue by FYWinds** [Mrs4s/go-cqhttp#1011]
**环境信息**

go-cqhttp版本: 1.0.0beta6
运行环境: Windows 10 x86_64
连接方式: 反向ws
使用协议: MacOS协议

**在最新的release版本中能否复现**
能

**bug内容**

调用api发送消息，如下图所示，消息内容未报错，但是显示的消息id为0，且接收不到消息
仅在私聊中出现，群聊发送正常
![U22{NC98}Z _$L`MU)I9KFB](https://user-images.githubusercontent.com/74457127/129832871-8abdea91-cd7a-4d91-b6f3-f34bed2cc792.png)

**复现方法**

nonebot内正常使用MessageSegment构造网易云音乐的分享消息
调用API发送私聊消息
gocq正常解析
无法收到消息

**Comment by GMYXDS** [comment]
请问这个解决了吗
