### ISSUE TITLE
无法处理加群请求，FLAG不存在

### ISSUE THREAD

**Issue by FYWinds** [Mrs4s/go-cqhttp#1016]
**环境信息**

go-cqhttp版本: 1.0.0beta4 &1.0.0.beta6
运行环境: Ubuntu 20.04 / windows 10
连接方式: 反向ws & 正向HTTP
使用协议: IPAD & MacOS

**在最新的release版本中能否复现**
能

**bug内容**

调用set_group_add_request的API返回FLAG不存在

**复现方法**

使用从/get_group_system_msg中返回值的["invited_requests"][x]["request_id"]处理加群请求
调用方式为/set_group_add_request?flag=[request_id]&approve=true

![image](https://user-images.githubusercontent.com/74457127/130247641-806ac93d-7157-4a34-9618-2bb5d1921f74.png)
![image](https://user-images.githubusercontent.com/74457127/130249039-e62a45e7-7417-48b8-946c-d309914b6b6b.png)

**Comment by Mrs4s** [comment]
`curl` 请求时请带上 `""` 以转义参数

**Comment by FYWinds** [comment]
> `curl` 请求时请带上 `""` 以转义参数

![image](https://user-images.githubusercontent.com/74457127/130250202-96e3e5c9-cb6c-45f0-8780-3bdf988aac3f.png)
还是不行

**Comment by Mrs4s** [comment]
`go-cqhttp` 侧打开 `debug` 看看日志？

**Comment by FYWinds** [comment]
> `go-cqhttp` 侧打开 `debug` 看看日志？

![@C8ICWB8EXE_(93M$3__{)B](https://user-images.githubusercontent.com/74457127/130250893-8c608881-6aec-4e77-9845-e03e04000822.png)

这是通过nonebot2内 bot.call_api调用后的结果
nonebot端收到的返回也是FLAG不存在

**Comment by Mrs4s** [comment]
`flag` 暂时只支持传入字符串, 算是bug

**Comment by 77409** [comment]
获取flag参数的类型是string，单匹配的时候，用的是int，两者绝不会相等吧！

```
case "set_group_add_request":
  p0 := p.Get("flag").String()
  p1 := p.Get("[sub_type,type].0").String()
  p2 := p.Get("reason").String()
  p3 := true
  if pt := p.Get("approve"); pt.Exists() {
	  p3 = pt.Bool()
  }
  return c.bot.CQProcessGroupRequest(p0, p1, p2, p3)
```

```
func (bot *CQBot) CQProcessGroupRequest(flag, subType, reason string, approve bool) global.MSG {
	msgs, err := bot.Client.GetGroupSystemMessages()
	if err != nil {
		log.Errorf("获取群系统消息失败: %v", err)
		return Failed(100, "SYSTEM_MSG_API_ERROR", err.Error())
	}
	if subType == "add" {
		for _, req := range msgs.JoinRequests {
			if strconv.FormatInt(req.RequestId, 10) == flag {
				if req.Checked {
					log.Errorf("处理群系统消息失败: 无法操作已处理的消息.")
					return Failed(100, "FLAG_HAS_BEEN_CHECKED", "消息已被处理")
				}
				if approve {
					req.Accept()
				} else {
					req.Reject(false, reason)
				}
				return OK(nil)
			}
		}
	} else {
		for _, req := range msgs.InvitedRequests {
			if strconv.FormatInt(req.RequestId, 10) == flag {
				if req.Checked {
					log.Errorf("处理群系统消息失败: 无法操作已处理的消息.")
					return Failed(100, "FLAG_HAS_BEEN_CHECKED", "消息已被处理")
				}
				if approve {
					req.Accept()
				} else {
					req.Reject(false, reason)
				}
				return OK(nil)
			}
		}
	}
	log.Errorf("处理群系统消息失败: 消息 %v 不存在.", flag)
	return Failed(100, "FLAG_NOT_FOUND", "FLAG不存在")
}
```
