### ISSUE TITLE
无法通过滑块验证

### ISSUE THREAD

**Issue by clacknya** [Mrs4s/go-cqhttp#1018]
**环境信息**

go-cqhttp版本: go-cqhttp-v0.9.40-fix4
运行环境: Linux 64bit
连接方式: 反向 ws
使用协议: ipad / android phone

**在最新的release版本中能否复现**
能

**bug内容**
滑块验证无法通过，报：当前上网环境异常，将更换服务器并重试

**复现方法**
号被封了，新买了个无绑定的直登号，新设备登录需要滑块验证
使用抓包方式，获取到 ticket 后填入无效，报：当前上网环境异常，将更换服务器并重试
![](https://i.loli.net/2021/08/21/nMjKh7IksFGgNES.png)
使用 Cef，同样无效，填入号码后无法进行下一步，报 404，怀疑这个服务已经 down 了。

**Comment by Ink-33** [comment]
请更新

**Comment by clacknya** [comment]
> 
> 
> 请更新

这不是 0.9.40 最新的吗

**Comment by Mrs4s** [comment]
请使用最新版本
