### ISSUE TITLE
关于新增qq电话接口

### ISSUE THREAD

**Issue by nyako233** [Mrs4s/go-cqhttp#1020]
是否考虑过添加拨打qq电话的接口呢？

**Comment by sam01101** [comment]
可以說明一下加入的原因嗎？

在 2021年8月22日週日 下午6:45，siliconwafer ***@***.***> 寫道：

**Comment by nyako233** [comment]
想要做一些定时拨打电话，播放提醒语音的功能不知道是否有可能在后续更新中提供接口呢。谢谢！

**Comment by Mrs4s** [comment]
挺难的, 而且可能被滥用

**Comment by nyako233** [comment]
好的！谢谢耐心解答！十分感谢您的项目！
