### ISSUE TITLE
发送网络图片BUG，出现到MiraiGo Element时出现错误。

### ISSUE THREAD

**Issue by Warrior-li** [Mrs4s/go-cqhttp#1021]
**环境信息**

go-cqhttp版本: v1.0.0-beta6
运行环境: Linux version 3.10.0-1160.11.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Fri Dec 18 16:34:56 UTC 2020
连接方式: 反向ws
使用协议: http

**在最新的release版本中能否复现**
有几率复现，因为BUG是随机出现的。

**bug内容**

1.BUG描述：使用机器人发送网络图片，刚开始可以发送，运行一段时间之后发送不了出现报错，发送的是同一张图片，并且在服务器上用curl命令可以获取图片信息。
有时候重启之后又可以发送，有的时候又要过一会。
目前处于不能发送的阶段。只限于网络图片，本地图片都可以。
2.BUB截图如下：
![image](https://user-images.githubusercontent.com/58515952/130362007-812d0fe1-aea7-42b9-acd6-2798ea3793dc.png)

**复现方法**

使用网络图片一段时间之后

**Comment by Mrs4s** [comment]
![image](https://user-images.githubusercontent.com/12137562/130362113-6e8ddf11-2d5a-486f-a988-9a227356ed65.png)
获取网络突破出现了 `EOF` 错误, 请检查应用

**Comment by Warrior-li** [comment]
> ![image](https://user-images.githubusercontent.com/12137562/130362113-6e8ddf11-2d5a-486f-a988-9a227356ed65.png)
> 获取网络图片出现了 `EOF` 错误, 请检查应用

用其他方式访问该图片都可以正常访问，如curl,使用python程序重新写一个get方法。
而这个EOF错误是使用了一段时间后才会产生。就是说可以正常发一段时间图片，然后开始对后续图片都报错

**Comment by Ink-33** [comment]
我感觉像是服务端因为流控什么的原因关闭了连接
你是一直发这个域名的图片会出问题，还是发不同域名的图片也会出这个问题？
另外我留意到这个域名由Cloudflare提供CDN服务，近期有收到gocq被当做爬虫的报告，如果您有域名控制权不妨检查一下防火墙设置

**Comment by Warrior-li** [comment]
> 我感觉像是服务端因为流控什么的原因关闭了连接
> 你是一直发这个域名的图片会出问题，还是发不同域名的图片也会出这个问题？
> 另外我留意到这个域名由Cloudflare提供CDN服务，近期有收到gocq被当做爬虫的报告，如果您有域名控制权不妨检查一下防火墙设置

不同域名的图片都会出现错误，现在发送三个站点和一个图片api请求到的图片链接都会发生错误。
因为是别人的站点所以我并没有域名控制权

**Comment by Warrior-li** [comment]
> 我感觉像是服务端因为流控什么的原因关闭了连接
> 你是一直发这个域名的图片会出问题，还是发不同域名的图片也会出这个问题？
> 另外我留意到这个域名由Cloudflare提供CDN服务，近期有收到gocq被当做爬虫的报告，如果您有域名控制权不妨检查一下防火墙设置

之前这个问题在重启若然次或者等待几个小时之后会好，这次故障由bug上报持续到现在还未恢复。

**Comment by Mrs4s** [comment]
换个服务器试试？

**Comment by Warrior-li** [comment]
> 换个服务器试试？

目前有三台服务器三运行三个不同的号，都在不同时期出现了该情况。情况：先是一段时间可以发送图片，在一段时间后所有网络图片全部出现EOF的情况。

**Comment by Warrior-li** [comment]
> 我感觉像是服务端因为流控什么的原因关闭了连接
> 你是一直发这个域名的图片会出问题，还是发不同域名的图片也会出这个问题？
> 另外我留意到这个域名由Cloudflare提供CDN服务，近期有收到gocq被当做爬虫的报告，如果您有域名控制权不妨检查一下防火墙设置

至今未恢复

**Comment by Mrs4s** [comment]
运营商问题,  gocq无法解决
