### ISSUE TITLE
log-aging设为0之后仍会删除旧的日志

### ISSUE THREAD

**Issue by Miuzarte** [Mrs4s/go-cqhttp#1023]
**环境信息**

go-cqhttp版本: v1.0.0-beta6
运行环境: ubuntu 20.04 x86
连接方式: 正向ws
使用协议: iPad

**在最新的release版本中能否复现**
能

**bug内容**

`log-aging`设为0之后仍会删除旧的日志

**复现方法**

**Comment by Mrs4s** [comment]
请问设置为0之后会删除多久的日志, 七天吗?

**Comment by Miuzarte** [comment]
> 请问设置为0之后会删除多久的日志, 七天吗?

对  前七天+今天
