### ISSUE TITLE
无法删除好友

### ISSUE THREAD

**Issue by Kandow** [Mrs4s/go-cqhttp#1029]
**环境信息**

go-cqhttp版本: v1.0.0-beta6
运行环境: windows
连接方式: python
使用协议: http

**在最新的release版本中能否复现**
可以
**bug内容**
用删除好友api删除不了好友
**复现方法**
   //获取好友列表
    response=requests.get('http://127.0.0.1:5701/get_friend_list')
    
    response=response.content.decode()
    response=json.loads(response)
    for i in response['data']:
        //遍历删除列表
        print(requests.get('http://127.0.0.1:5701/delete_friend?friend_id={}'.format(i['user_id'])).content.decode())

    返回{"data":null,"msg":"FRIEND_NOT_FOUND","retcode":100,"status":"failed","wording":"好友不存在"}

**Comment by JustUndertaker** [comment]
在这里发现问题：
https://github.com/Mrs4s/go-cqhttp/blob/bf77951f8d389e71ac2bcca43a2820722fafcd9f/server/api.go#L36
在目前条件下，应该将参数"friend_id"修改为"id"。

**Comment by Mrs4s** [comment]
目前参数支持 `user_id` 或者 `id` 了
