### ISSUE TITLE
关于新增群聊全体禁言状态的接口

### ISSUE THREAD

**Issue by IMSUVEN** [Mrs4s/go-cqhttp#1031]
**环境信息**

go-cqhttp版本: v1.0.0

**需要添加的功能内容**

希望新增查询接口，查询所在群聊群号，获取当前群全体禁言状态。
用途：由于服务型bot经常会被拉入“送赞群”、“广告群”。此类群聊显著特点为全体禁言。希望通过增加查询接口，可以查询到这类群聊以退出。

**Comment by IMSUVEN** [comment]
同时也希望增加接口，查询bot在某个群是否被禁言。

**Comment by Ink-33** [comment]
duplicated #565
我依稀记得这个功能好像在miraigo层做了，也好像没做，大家都忘了

**Comment by IMSUVEN** [comment]
> duplicated #565
> 我依稀记得这个功能好像在miraigo层做了，也好像没做，大家都忘了

看了一下miraigo的说明，好像没有实现相关的。mirai那边好像也没有

**Comment by Mrs4s** [comment]
应该有, 回头我加到群信息里面吧

**Comment by IMSUVEN** [comment]
> 应该有, 回头我加到群信息里面吧

感谢，顺便查询单独禁言的接口也希望可以加上

**Comment by Ink-33** [comment]
> > 应该有, 回头我加到群信息里面吧
> 
> 感谢，顺便查询单独禁言的接口也希望可以加上

这个已经有了，在群成员信息里面

**Comment by wdvxdr1123** [comment]
> 感谢，顺便查询单独禁言的接口也希望可以加上
这个已经有了

**Comment by nmMmnmMmn** [comment]
> 应该有, 回头我加到群信息里面吧

那么，现在这个有了吗，文档里似乎没有呢
