### ISSUE TITLE
能添加发送非好友的临时会话吗?就是没有任何联系,也没有qq群的只知道一个qq号的那种

### ISSUE THREAD

**Issue by fei1025** [Mrs4s/go-cqhttp#1032]
能添加发送非好友的临时会话吗?就是没有任何联系,也没有qq群的只知道一个qq号的那种,
现在我想做一个消息推送功能,推送的时候应该只有对方qq号,所以这个是已有到功能,我没找到,还是现阶段没有开发?

**Comment by synodriver** [comment]
恐怕不行

**Comment by Ink-33** [comment]
现在不开发，以后也不会开发，有能力你可以自己开发偷偷用
