### ISSUE TITLE
使用反向ws后，在bot端重启后无法连接

### ISSUE THREAD

**Issue by laazy** [Mrs4s/go-cqhttp#1034]
**环境信息**

go-cqhttp版本: v1.0.0-beta6
运行环境:  windows10 21h1 AMD Ryzen 5 3600 
连接方式: 反向ws
使用协议: ipad

**在最新的release版本中能否复现**
可以

**bug内容**

cq配置反向ws，启动。bot端使用nonebot2
在正常运行时，重启bot，cq无法重连。

**复现方法**

1. 启动nonebot2.
2. 启动cqhttp
3. 重启nonebot2.
4. cqhttp无法重连。

**部分日志信息**
[2021-08-29 17:06:46] [INFO]: 正在检查更新.
[2021-08-29 17:06:46] [INFO]: 检查更新完成. 当前已运行最新版本.
[2021-08-29 17:15:39] [WARNING]: 监听反向WS API时出现错误: websocket: close 1006 (abnormal closure): unexpected EOF
[2021-08-29 17:15:41] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: write tcp 127.0.0.1:1460->127.0.0.1:8080: use of closed network connection
[2021-08-29 17:15:46] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: write tcp 127.0.0.1:1460->127.0.0.1:8080: use of closed network connection
[2021-08-29 17:15:51] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: write tcp 127.0.0.1:1460->127.0.0.1:8080: use of closed network connection

**Comment by ishkong** [comment]
centos7上无法复现

**Comment by laazy** [comment]
**nonebot2**：
版本：2.0.0a15 （包含driver）

log：
PS D:\bot> python bot.py
08-29 17:15:40 [SUCCESS] nonebot | NoneBot is initializing...
08-29 17:15:40 [INFO] nonebot | Current Env: prod
08-29 17:15:40 [SUCCESS] nonebot | Succeeded to import "nonebot.plugins.echo"
08-29 17:15:40 [SUCCESS] nonebot | Succeeded to import "bot"
08-29 17:15:40 [SUCCESS] nonebot | Running NoneBot...
08-29 17:15:40 [INFO] uvicorn | Started server process [19704]
08-29 17:15:40 [INFO] uvicorn | Waiting for application startup.
08-29 17:15:40 [INFO] uvicorn | Application startup complete.
08-29 17:15:40 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
08-29 17:25:27 [INFO] uvicorn | Shutting down
08-29 17:25:27 [INFO] uvicorn | Waiting for application shutdown.
08-29 17:25:27 [INFO] uvicorn | Application shutdown complete.
08-29 17:25:27 [INFO] uvicorn | Finished server process [19704]
PS D:\bot> python bot.py
08-29 17:25:28 [SUCCESS] nonebot | NoneBot is initializing...
08-29 17:25:28 [INFO] nonebot | Current Env: prod
08-29 17:25:29 [SUCCESS] nonebot | Succeeded to import "nonebot.plugins.echo"
08-29 17:25:29 [SUCCESS] nonebot | Succeeded to import "bot"
08-29 17:25:29 [SUCCESS] nonebot | Running NoneBot...
08-29 17:25:29 [INFO] uvicorn | Started server process [23812]
08-29 17:25:29 [INFO] uvicorn | Waiting for application startup.
08-29 17:25:29 [INFO] uvicorn | Application startup complete.
08-29 17:25:29 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
08-29 17:26:01 [INFO] uvicorn | ('127.0.0.1', 5690) - "WebSocket /cqhttp/ws" [accepted]
08-29 17:26:01 [INFO] nonebot | WebSocket Connection from CQHTTP Bot 123456 Accepted!

**Comment by ishkong** [comment]
@wdvxdr1123

**Comment by Ink-33** [comment]
麻烦脱敏发一下配置文件

**Comment by laazy** [comment]
account: # 账号相关
  uin: 123456# QQ账号
  password: '123456' # 密码为空时使用扫码登录
  encrypt: false  # 是否开启密码加密
  status: 0      # 在线状态 请参考 https://docs.go-cqhttp.org/guide/config.html#在线状态
  relogin: # 重连设置
    delay: 3   # 首次重连延迟, 单位秒
    interval: 3   # 重连间隔
    max-times: 0  # 最大重连次数, 0为无限制

  # 是否使用服务器下发的新地址进行重连
  # 注意, 此设置可能导致在海外服务器上连接情况更差
  use-sso-address: true

heartbeat:
  # 心跳频率, 单位秒
  # -1 为关闭心跳
  interval: 5

message:
  # 上报数据类型
  # 可选: string,array
  post-format: array
  # 是否忽略无效的CQ码, 如果为假将原样发送
  ignore-invalid-cqcode: false
  # 是否强制分片发送消息
  # 分片发送将会带来更快的速度
  # 但是兼容性会有些问题
  force-fragment: false
  # 是否将url分片发送
  fix-url: false
  # 下载图片等请求网络代理
  proxy-rewrite: ''
  # 是否上报自身消息
  report-self-message: false
  # 移除服务端的Reply附带的At
  remove-reply-at: false
  # 为Reply附加更多信息
  extra-reply-data: false
  # 跳过 Mime 扫描, 忽略错误数据
  skip-mime-scan: false

output:
  # 日志等级 trace,debug,info,warn,error
  log-level: warn
  # 日志时效 单位天. 超过这个时间之前的日志将会被自动删除. 设置为 0 表示永久保留.
  log-aging: 15
  # 是否在每次启动时强制创建全新的文件储存日志. 为 false 的情况下将会在上次启动时创建的日志文件续写
  log-force-new: true
  # 是否启用 DEBUG
  debug: false # 开启调试模式

# 默认中间件锚点
default-middlewares: &default
  # 访问密钥, 强烈推荐在公网的服务器设置
  access-token: ''
  # 事件过滤器文件目录
  filter: ''
  # API限速设置
  # 该设置为全局生效
  # 原 cqhttp 虽然启用了 rate_limit 后缀, 但是基本没插件适配
  # 目前该限速设置为令牌桶算法, 请参考:
  # https://baike.baidu.com/item/%E4%BB%A4%E7%89%8C%E6%A1%B6%E7%AE%97%E6%B3%95/6597000?fr=aladdin
  rate-limit:
    enabled: false # 是否启用限速
    frequency: 1  # 令牌回复频率, 单位秒
    bucket: 1     # 令牌桶大小

database: # 数据库相关设置
  leveldb:
    # 是否启用内置leveldb数据库
    # 启用将会增加10-20MB的内存占用和一定的磁盘空间
    # 关闭将无法使用 撤回 回复 get_msg 等上下文相关功能
    enable: true

# 连接服务列表
servers:
  - ws-reverse:
      universal: ws://127.0.0.1:8080/cqhttp/ws
  # 添加方式，同一连接方式可添加多个，具体配置说明请查看文档
  #- http: # http 通信
  #- ws:   # 正向 Websocket
  #- ws-reverse: # 反向 Websocket
  #- pprof: #性能分析服务器

**Comment by laazy** [comment]
对应fundbot 代码
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import nonebot
from nonebot.adapters.cqhttp import Bot as CQHTTPBot


# Custom your logger
# 
# from nonebot.log import logger, default_format
# logger.add("error.log",
#            rotation="00:00",
#            diagnose=False,
#            level="ERROR",
#            format=default_format)

# You can pass some keyword args config to init function
nonebot.init(_env_file=".env")
driver = nonebot.get_driver()
config = driver.config
config.command_start = set("!！/#")

nonebot.load_builtin_plugins()
app = nonebot.get_asgi()

driver.register_adapter("cqhttp", CQHTTPBot)


# nonebot.load_plugins("src/plugins")
nonebot.load_plugins("bot/plugins")

# Modify some config / config depends on loaded configs


if __name__ == "__main__":
    nonebot.run(app="bot:app")
```

**Comment by wdvxdr1123** [comment]
```yaml
  - ws-reverse:
      # 反向WS Universal 地址
      # 注意 设置了此项地址后下面两项将会被忽略
      universal: ws://your_websocket_universal.server
      # 反向WS API 地址
      api: ws://your_websocket_api.server
      # 反向WS Event 地址
      event: ws://your_websocket_event.server
      # 重连间隔 单位毫秒
      reconnect-interval: 3000
      middlewares:
        <<: *default # 引用默认中间件
```
请设置重连间隔 (reconnect-interval)
