### ISSUE TITLE
加载群列表超时

### ISSUE THREAD

**Issue by xiaokaizhi** [Mrs4s/go-cqhttp#104]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.10
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
请在这里详细描述bug的内容

每次运行都卡在：加载群列表哪里。然后等了很长时间提示packet time out

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by Mrs4s** [comment]
请使用最新版本
