### ISSUE TITLE
空间不足引发的记录聊天数据错误在腾出空间后仍然出错的问题

### ISSUE THREAD

**Issue by Aixzk** [Mrs4s/go-cqhttp#1045]
**环境信息**

go-cqhttp版本: v1.0.0-beta6
运行环境: linux amd64
连接方式: http
使用协议: android_phone

**在最新的release版本中能否复现**
能

**bug内容**

在运行着 go-cqhttp 时如果磁盘空间满了会提示 “记录聊天数据时出现错误”，即使这时删除服务器上的其他文件腾出空间也仍然提示出错，只有重启 go-cqhttp 的话才能解决这个问题。（出错的话，发送消息时不会返回数据，这在我的程序上持续报错了好几天……）

**复现方法**

运行着 go-cqhttp 的时候填满磁盘空间。

**Comment by Ink-33** [comment]
这谁想得到磁盘满了啊（
目前给出的建议是重启解决，或者换个写不满的硬盘（x

**Comment by 2938137849** [comment]
建议在使用需求里面写上: 硬盘可用空间小于 1G 的不推荐使用  (不是
