### ISSUE TITLE
登录扫描二维码时显示识别二维码失败且程序自动退出

### ISSUE THREAD

**Issue by eric2788** [Mrs4s/go-cqhttp#1046]
**环境信息**

go-cqhttp版本: v1.0.0-beta-6
运行环境: windows10
连接方式: 反向ws + http
使用协议: IPad / Android Phone

**在最新的release版本中能否复现**

**bug内容**

之前因为风控问题，所以打算删掉session.token文件重新扫码登录
config.json 有填写密码，因此扫码为验证登录
为了测试风控，我打开了安全保护(设备锁)
![image](https://user-images.githubusercontent.com/6276840/132288112-1bb07c48-ab3a-45ac-a979-7ffb03d79a79.png)
然而就在扫码登录的时候，出现了无法识别二维码:
![image](https://user-images.githubusercontent.com/6276840/132288160-a06e9768-288b-4cd1-b11d-8709ecc0f17f.png)
而同一时间，go-cqhttp的程序也消失了(我是使用 start.bat 执行 exe)
翻查LOG发现显示为 
```log
[2021-09-07 12:46:54] [INFO]: 请使用手机QQ扫描二维码 (qrcode.png) :  
[2021-09-07 12:47:29] [FATAL]: 扫码被用户取消.
```
但事实是扫码之后go-cqhttp程序自动退出，且显示无法识别的结果
然后我切换了协议(从 IPad 切换到 Android Phone)，结果还是一样
删掉了 device.json 重试，结果还是一样 
config.json 删掉密码重试，结果还是一样
最后我尝试关闭安全保护(设备锁)后重试，发现结果居然还是一样，所以推定跟我打开设备锁无关
最后关闭安全保护之下更换协议(从 Android Phone 到 IPad)重试，结果还是一样

**复现方法**

1. 删掉 session.token 登出
2. 打开安全设备锁
3. 扫码登录 (失败)

4. 更换协议，结果一样
5. 删 device.json，结果一样
6. 关闭安全设备锁，结果一样
7. 关闭安全设备锁后更换协议，结果一样

**Comment by Mrs4s** [comment]
测试了下没有复现, 尝试扫描输出的 `qrcode.png` 文件？

**Comment by Ink-33** [comment]
请尝试将`start.bat`中的内容改为

``` bat
start cmd /K go-cqhttp.exe
```

再次双击`start.bat`，确认gocq是否正常输出崩溃信息

**Comment by eric2788** [comment]
> 
> 
> 请尝试将`start.bat`中的内容改为
> 
> ```batchfile
> start cmd /K go-cqhttp.exe
> ```
> 
> 再次双击`start.bat`，确认gocq是否正常输出崩溃信息

使用此 start.bat 内后，出现的讯息为
![image](https://user-images.githubusercontent.com/6276840/132332200-b446db79-2563-4759-9c31-9fed32231dc1.png)

**Comment by eric2788** [comment]
> 
> 
> 测试了下没有复现, 尝试扫描输出的 `qrcode.png` 文件？

扫那个png的话，会显示已过期

**Comment by Mrs4s** [comment]
> > 测试了下没有复现, 尝试扫描输出的 `qrcode.png` 文件？
> 
> 扫那个png的话，会显示已过期

奇怪了, 能否换个环境测试.
我这边测试了几个号都能正常登录

**Comment by eric2788** [comment]
> 
> 
> > > 测试了下没有复现, 尝试扫描输出的 `qrcode.png` 文件？
> > 
> > 
> > 扫那个png的话，会显示已过期
> 
> 奇怪了, 能否换个环境测试.
> 我这边测试了几个号都能正常登录

好，我试试别的人开看看

**Comment by eric2788** [comment]
我找了号持有者(都是他帮登录的人)去使用exe打开验证，结果是成功
然后我自己再尝试启动，结果发现不用扫码了...直接登录 和 生成 seesion.token....

**Comment by Mrs4s** [comment]
> 我找了号持有者(都是他帮登录的人)去使用exe打开验证，结果是成功
> 然后我自己再尝试启动，结果发现不用扫码了...直接登录 和 生成 seesion.token....

emmm 谜之问题

**Comment by HMScygnet** [comment]
@Mrs4s 经过我的测试后，似乎是与手机QQ版本有关，当使用手机QQ V8.8.33.6300扫码登录时会出现该issues内的问题，而用V8.8.17.5770时可以正常扫码登录，其他版本尚未测试，不知道是在哪个版本开始无法扫码

**Comment by AkagiYui** [comment]
不能选择相册中的图片来扫描，必须直接扫描

**Comment by jiesou** [comment]
我也这样

**Comment by jiesou** [comment]
找了个 8.2.11 的 Play 版本 QQ 也不行
![Screenshot_2022-06-11-22-33-22-336-edit_com miui gallery](https://user-images.githubusercontent.com/84175239/173192250-86b0a43c-ef90-495a-939b-12b187b36bad.jpg)

**Comment by luxunL** [comment]
我也出现这个问题
go-cqhttp版本: v1.0.0-rc2
运行环境: Ubuntu 20.04.3 LTS
TIM V3.3.8.2988（Android）
TIM提示“扫码失败，已失效或存在异常。”
QQ V8.8.88.662 （ios）
QQ提示"**登录环境非常用或存在危险,请保持登陆地一致后再尝试**"

然而我用的阿里云的服务器，怎么保证登陆地一致 = =!

**Comment by jiesou** [comment]
我用 Android Phone 协议也不行

**Comment by luxunL** [comment]
https://github.com/Mrs4s/go-cqhttp/issues/1469#issuecomment-1111987138

我用这个方法解决了这个问题

**Comment by SEANPNEX** [comment]
在本地(ubuntu 21.10)登陆后将session.token,device.json,config.yml上传到云端go-cqhttp目录下后解决了这个问题
