### ISSUE TITLE
关于群聊发生失败（风控）后自动用正常流程进行登录并重新生成device.json

### ISSUE THREAD

**Issue by A2Sumie** [Mrs4s/go-cqhttp#1047]
**环境信息**
<win7，本地机器>
go-cqhttp版本: beta6

**需要添加的功能内容**

在群聊消息发送失败（风控）后自动进行一次正常流程的重新登陆，放弃现有会话token，（并/或）重新生成随机device.json 

一个号被风控后病急投医把device.json改了（所有信息拷贝的自己手机），proc改成安卓手机然后用自己手机登录以无效化会话token，程序登录时自动转了正常流程，风控解决。
同时进行的所以究竟哪边起了作用我不知道，但前面试着让程序随机生成device.json或者手动瞎搞（替换掉所有mirai字段）并没有解开所以我猜是token那边吧。

**Comment by happymario8** [comment]
确实是token

**Comment by Mrs4s** [comment]
这样的话会导致重走设备锁验证流程, 无法自动化

**Comment by AndoKaguya** [comment]
最近好像风控比较频繁，每次删token之后重登又能苟一段时间

**Comment by wangjiahui1126** [comment]
最近好像风控比较频繁，每次删token之后重登又能苟一段时间←（我又遇到这个问题了，怎么办）

**Comment by gitsang** [comment]
> 最近好像风控比较频繁，每次删token之后重登又能苟一段时间←（我又遇到这个问题了，怎么办）

用了一个比较蛋疼的方法，cqhttp 仅用于收消息，然后发消息走 qqhook

**Comment by takoyakiccc** [comment]
https://github.com/takoyakiccc/cqhttp_reboot  自动重启
