### ISSUE TITLE
被群成员邀请加群，需要管理员审核的时候

### ISSUE THREAD

**Issue by takayama-lily** [Mrs4s/go-cqhttp#105]
审核通过入群后，对该群聊无反应，好像并不知道自己已经入群了。
![F$X`51_QR{BMT6KUE4E`N)6](https://user-images.githubusercontent.com/12014361/90242543-37104680-de68-11ea-8b8c-e1d335c5b079.png)

**Comment by Mrs4s** [comment]
已修复
