### ISSUE TITLE
掉线后不尝试重连?

### ISSUE THREAD

**Issue by lancer-wang** [Mrs4s/go-cqhttp#1053]
**环境信息**
go-cqhttp版本: v1.0.0-beta6
运行环境: linux ubuntu20
连接方式: ws
使用协议: ipad

**在最新的release版本中能否复现**
能
**bug内容**
掉线后不尝试重连,设置中有设置自动重连
![image](https://user-images.githubusercontent.com/69783837/133402696-7bd86215-1a6d-4415-8065-6c6846bbbc90.png)

**复现方法**
不知

**Comment by lancer-wang** [comment]
顺便,我是海外服务器

**Comment by lancer-wang** [comment]
又掉了一次...
![image](https://user-images.githubusercontent.com/69783837/133407782-efc6d13d-4128-4c57-b329-67a825fef7fb.png)

**Comment by BestRailgun** [comment]
同样的情况，试过删除session重新登录还是会掉。晚上回去试试重新扫码登录一下。
我现在套了个进程守护，掉了会自动重启。

**Comment by GirlKiller512** [comment]
我也出现这个问题了，上面的方法我也试过了，还是没解决
我可能需要降版本再试了

**Comment by Mrs4s** [comment]
#1015

**Comment by clacknya** [comment]
同海外服务器，这两天疯狂掉线，💔已经菠萝菠萝哒了

**Comment by zsuroy** [comment]
@Mrs4s 
问题依旧存在
环境信息
go-cqhttp版本：v1.0.0-rc1 / v1.0.0-beta8-fix2
运行环境：linux ubuntu21
连接方式：ws
使用协议：ipad

最新的发布内容版本中可以复现
能
bug
掉线不试重连，设置有自动重连

![S20221-09361380](https://user-images.githubusercontent.com/77138019/154875412-e45b2a23-0cdf-4b99-8d2a-33a76f3507ea.png)
