### ISSUE TITLE
最新版本的GO部分图片无法发送，提示消息图片上传失败

### ISSUE THREAD

**Issue by shadow7755** [Mrs4s/go-cqhttp#1063]
环境信息

go-cqhttp版本: v1.0.0-beta7-fix1
运行环境: windows_amd64
连接方式: ws
使用协议: Android Pad

在最新的release版本中能否复现
能
bug内容
hoshino使用 https://github.com/pcrbot/gacha 的自动更新抽卡插件
使用 来一井 抽卡命令，最后得到的抽卡结果图片，无法正常显示
提示消息图片上传失败

比如执行抽卡命令
![image](https://user-images.githubusercontent.com/1725949/133616947-a319b248-d03d-4542-9d07-6624606f9b9f.png)

go报错日志如下
![image](https://user-images.githubusercontent.com/1725949/133616779-104a83d6-3b29-4ad4-ad2e-4a3a216f2006.png)

后来我拿v1.0.0-beta6的go实验了一下，图片是能正常发送的，说明不是QQ号被风控的问题
这个问题在beta6版没有，而在beta7版出现
![image](https://user-images.githubusercontent.com/1725949/133616924-60da595c-a821-4df4-a046-5e7b6182ad79.png)

复现方法
hoshino使用 https://github.com/pcrbot/gacha 的自动更新抽卡插件
使用 来一井 抽卡命令，最后得到的抽卡结果图片，无法正常显示

**Comment by Ink-33** [comment]
请提供您的业务代码

**Comment by shadow7755** [comment]
> 请提供您的业务代码

业务代码是哪个？

**Comment by Ink-33** [comment]
> > 请提供您的业务代码
> 
> 业务代码是哪个？

就是你是如何通过gocq发送图片的

**Comment by shadow7755** [comment]
> > > 请提供您的业务代码
> > 
> > 
> > 业务代码是哪个？
> 
> 就是你是如何通过gocq发送图片的

机器人口令是 来一井
用的自动抽卡的插件 https://github.com/pcrbot/gacha

**Comment by Ink-33** [comment]
请您打开gocq的debug模式，分别截取调用抽卡时，b6和b7的**接收到xxxapi调用**两张截图

**Comment by ishkong** [comment]
已确定最新版base64发送图片存在问题，请等待核心开发者排查

**Comment by Mrs4s** [comment]
初步判断是由于硬件指令集加速导致的兼容性问题, 还在排查

**Comment by Mrs4s** [comment]
确实是硬件加速导致的随机解码错误, 明天修...

**Comment by NepPure** [comment]
相同问题 大佬加油

**Comment by wdvxdr1123** [comment]
可以尝试使用 https://github.com/Mrs4s/go-cqhttp/actions/runs/1244610158 ，如果依旧遇到问题，请及时反馈

**Comment by NepPure** [comment]
> 可以尝试使用 https://github.com/Mrs4s/go-cqhttp/actions/runs/1244610158 ，如果依旧遇到问题，请及时反馈

目前看来问题解决了

**Comment by Mrs4s** [comment]
已修复
