### ISSUE TITLE
【1.0.0beta7】go-cqhttp.exe 与你运行的 Windows 版本不兼容。请查看计算机的系统信息，然后联系软件发布者。

### ISSUE THREAD

**Issue by Seth2333** [Mrs4s/go-cqhttp#1064]
**环境信息**

go-cqhttp版本: 1.0.0 beta7 fix1
运行环境: windows server 2019
连接方式: 
使用协议: 

**在最新的release版本中能否复现**

**bug内容**

go-cqhttp.exe 与你运行的 Windows 版本不兼容。请查看计算机的系统信息，然后联系软件发布者。

**复现方法**

不管是双击打开还是通过cmd均出现此提示 之前beta4不会出现此情况

**Comment by Ink-33** [comment]
截图一下你下载的是哪个`go-cqhttp.exe`

**Comment by Mrs4s** [comment]
请检查下你下载的版本, 一般情况下请下载 `windows_amd64` 而不是 `windows_arm64`

**Comment by Seth2333** [comment]
抱歉 是本人没有看清楚，刚才两个issue以为close就没法再发了，鄙人不太常用GitHub，并非有意刷issue，经核对确实是自己下错了版本，很抱歉给开发者添麻烦了
