### ISSUE TITLE
go-cqhttp.exe 与你运行的 Windows 版本不兼容。请查看计算机的系统信息，然后联系软件发布者。

### ISSUE THREAD

**Issue by Seth2333** [Mrs4s/go-cqhttp#1066]
**环境信息**

go-cqhttp版本: v1.0.0-beta7-fix1
运行环境: windows server 2019
连接方式: ws
使用协议: iPad

**在最新的release版本中能否复现**
能
**bug内容**

go-cqhttp.exe 与你运行的 Windows 版本不兼容。请查看计算机的系统信息，然后联系软件发布者。

**复现方法**

无论是通过cmd指令还是双击打开均会出现此提示，beta4时不会出现此情况且可以正常使用

**Comment by Ink-33** [comment]
**请不要刷issue**
#1065 #1064
