### ISSUE TITLE
重要问题

### ISSUE THREAD

**Issue by TN-110** [Mrs4s/go-cqhttp#1072]
如果腾讯对作者打压得话软件还能不能使用,现在是单机的还是在作者服务器上跳板请求发送,建议作者将软件能做成一个全本地运行的软件,且在更新的那一步请求到了就下请求不到就跳过,防止应为请求不到导致请求不到数据,虽然我不是go语言开发者但是您的程序对web的扩展是真的完美,请您继续加油

**Comment by ishkong** [comment]
现在不就是单机吗？？

**Comment by sam01101** [comment]
> 现在不就是单机吗？？

现在就是单机，但是他可能因为经常被风控以为现在是用某个跳板代发请求的吧

**Comment by Mrs4s** [comment]
现在就是单机解析的, 所有功能的代码都保持开源
