### ISSUE TITLE
图片信息存储问题

### ISSUE THREAD

**Issue by cc004** [Mrs4s/go-cqhttp#1075]
**环境信息**

go-cqhttp版本: 

**需要添加的功能内容**
现在好像是类似coolq的每个图片存一个小文件，一个月就几十万个文件了，无论是迁移还是删除都很慢，可不可以合并成一个db

**Comment by sam01101** [comment]
#749

**Comment by Mrs4s** [comment]
会加入图片储存点选择的功能

**Comment by wdvxdr1123** [comment]
我觉得可以这样，逐步去除缓存文件支持:
1.  v1.0.0 正式版发布前， 可以选择存储在文件夹还是专用db中。
2.  v1.0.0 中接受到的图片只能存入db中，但保留原缓存文件的支持。
3.  v1.1.0 中只支持db缓存。
