### ISSUE TITLE
关于支持docker部署的建议

### ISSUE THREAD

**Issue by youmu1** [Mrs4s/go-cqhttp#1083]
go-cqhttp版本: 
latest

使用docker部署有许多好处，如果go-cqhttp能够支持docker那真是太好了！

**Comment by synodriver** [comment]
怎么能把老婆关容器里面（

**Comment by sam01101** [comment]
👀原来你喜欢放置play

**Comment by youmu1** [comment]
> 怎么能把老婆关的容器里面
r

**Comment by Mrs4s** [comment]
目前是支持docker部署的, 不过没有提供官方的docker镜像而已

**Comment by youmu1** [comment]
> 目前是支持docker部署的, 不过没有提供官方的docker镜像而已

是的，我指的是官方的镜像

**Comment by j1g5awi** [comment]
go-cqhttp 的配置这么简便了，没必要提供官方镜像吧，即便有了官方镜像不还是得填差不多的配置文件。

**Comment by youmu1** [comment]
> go-cqhttp 的配置这么简便了，没必要提供官方镜像吧，即便有了官方镜像不还是得填差不多的配置文件。

![](https://pic1.zhimg.com/80/v2-f920f18fee27b35c342890c3911ad698_720w.jpg)

**Comment by sam01101** [comment]
> go-cqhttp 的配置这么简便了，没必要提供官方镜像吧，即便有了官方镜像不还是得填差不多的配置文件。

否定。
官方镜像除了更新和支援以外还有安全保障

**Comment by jianmj** [comment]
支持官方镜像（又可以省一步打包

**Comment by klarkxy** [comment]
官方可以提供docker-compose一键部署么？

**Comment by zx900930** [comment]
![image](https://user-images.githubusercontent.com/734749/141614764-55b03d91-143e-45ac-a98b-b1ef21f1155d.png)
部署到docker挺简单, 但是每次更新只能自己手动去build image吗?

**Comment by Putarku** [comment]
我用的是pcrbot的gocqhttp的镜像，内含了ffmpeg,用起来还是比较方便的，更新的话换一下容器里的gocq文件就行了

**Comment by Putarku** [comment]
> 我用的是pcrbot的gocqhttp的镜像，内含了ffmpeg,用起来还是比较方便的，更新的话换一下容器里的gocq文件就行了

![image](https://user-images.githubusercontent.com/66679443/156107442-f00f520a-b96b-452a-8af6-b21fc5f74011.png)

**Comment by qianjunakasumi** [comment]
这是过期的 Issue。 https://github.com/Mrs4s/go-cqhttp/pkgs/container/go-cqhttp

cc @Mrs4s

**Comment by VergilGao** [comment]
我提交了一个pr来完善目前docker的功能，更加适配家用nas尤其是unraid
https://github.com/Mrs4s/go-cqhttp/pull/1753
pr的内容还没有测试，我会在本地电脑测试通过了之后再请大家review
