### ISSUE TITLE
Question: How to compile FFmpeg from source for `go-cqhttp`?

### ISSUE THREAD

**Issue by purerosefallen** [Mrs4s/go-cqhttp#1086]
For some reasons, in some uncommon Linux distros, FFmpeg cannot installed from package manager, but should be compiled from source.
According to the FFmpeg documentation of FFmpeg https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu , there are many libraries possible to compile with FFmpeg. But I have no idea which libraries should be used to compile FFmpeg for `go-cqhttp`. In addition, the `go-cqhttp` documentation said nothing about that.
Could you tell me which of the libraries should I compile FFmpeg with? Thanks.

**Comment by mnixry** [comment]
`go-cqhttp` uses ffmpeg from command line, you just need to ensure the ffmpeg executable file could be found and executed successfully.

**Comment by Ink-33** [comment]
If you are using Ubuntu, Debian, you can simply execute `apt install ffmpeg` to install.
If you are using RHEL, Fedora, CentOS, etc, I recommand installing `ffmpeg` form [rpmfusion](https://rpmfusion.org/Configuration).
![image](https://user-images.githubusercontent.com/51873347/134759950-16e2ee8c-dc7f-41e2-ad37-10f3d33d6340.png)

**Comment by purerosefallen** [comment]
What about other distros, such as Archlinux, Gentoo which may be impossible to install `ffmpeg` from package manager, but required to compile it from source? There are many libraries to be compiled with, such as `nasm`, `libx264`. But I'm not sure which of them are required by `go-cqhttp`.

**Comment by sam01101** [comment]
> What about other distros, such as Archlinux, Gentoo which may be impossible to install `ffmpeg` from package manager, but required to compile it from source? There are many libraries to be compiled with, such as `nasm`, `libx264`. But I'm not sure which of them are required by `go-cqhttp`.

You can do alias to bind the binary

**Comment by purerosefallen** [comment]
~~Why aren't you answering the question~~

**Comment by synodriver** [comment]
You should ask under ffmpeg's repo.

**Comment by sam01101** [comment]
> What about other distros, such as Archlinux, Gentoo which may be impossible to install `ffmpeg` from package manager, but required to compile it from source? There are many libraries to be compiled with, such as `nasm`, `libx264`. But I'm not sure which of them are required by `go-cqhttp`.

Maybe I understand you question be wrong, did you mean that you’re not sure about which `ffmpeg` is `go-cqhttp` supported?
Well usually there aren’t any minor version requiring, you can be all versions of `ffmpeg`.

**Comment by YumeMichi** [comment]
Download static build from https://johnvansickle.com/ffmpeg/

**Comment by purerosefallen** [comment]
@synodriver I believe this could be a `go-cqhttp` documentation issue, for not pointing out the minimum library requirement of `ffmpeg`.

@sam01101 Not about ffmpeg version, but **which library**, or which optional dependency of `ffmpeg`. `ffmpeg` contains a bunch of `--with-somelibrary` options, but wondering which of them are required by `go-cqhttp`.

@YumeMichi Not every condition is static build suitable. eg. on Alpine Linux where `glibc` is missing, it should be compiled from source.

**Comment by sam01101** [comment]
> @synodriver I believe this could be a `go-cqhttp` documentation issue, for not pointing out the minimum library requirement of `ffmpeg`.
> 
> @sam01101 Not about ffmpeg version, but **which library**, or which optional dependency of `ffmpeg`. `ffmpeg` contains a bunch of `--with-somelibrary` options, but wondering which of them are required by `go-cqhttp`.
> 
> @YumeMichi Not every condition is static build suitable. eg. on Alpine Linux where `glibc` is missing, it should be compiled from source.

So `go-cqhttp` needs to implement a tutorial documents for building`ffmpeg`, right?

**Comment by Raka-loah** [comment]
For audio part, ffmpeg is solely used to decode your audio file to PCM, so that depends on you.
For video part, x264 and LAME are required I guess.

**Comment by purerosefallen** [comment]
Thanks
