### ISSUE TITLE
闪照CQ码中的`url`字段为空导致`aiocqhttp`解析失败

### ISSUE THREAD

**Issue by mnixry** [Mrs4s/go-cqhttp#1088]
**环境信息**

go-cqhttp版本: 1.0.0-beta7
运行环境: windows
连接方式: 反向WebSocket
使用协议: 手机

**在最新的release版本中能否复现**
是

**bug内容**
上游Issue: https://github.com/nonebot/aiocqhttp/issues/60
根据[OneBot标准](https://github.com/botuniverse/onebot/blob/master/v11/specs/message/string.md)，CQ码的param不应该有空值，这将会导致部分SDK的解析失败

由于闪照无法提供永久链接，所以gocq这边并没有提供闪照的url
我个人建议直接从上报的CQ码中移除该字段

**复现方法**
使用aiocqhttp 1.4.2, 采用string方式上报闪照消息

**Comment by Akitora-R** [comment]
主要是Mirai core是有提供一个闪照链接的…虽然过会儿就会失效，可以的话希望这边也能给一下就好了…
