### ISSUE TITLE
base64上传图片报错 image type error:text/plain charset=utf-8

### ISSUE THREAD

**Issue by DongGua-Jun** [Mrs4s/go-cqhttp#1091]
**环境信息**

go-cqhttp版本: v1.0.0-beta7-fix2
运行环境: Windows Server 2012 R2 DataCenter 64bitCN
连接方式: ws
使用协议: ipad

**在最新的release版本中能否复现**
是
**bug内容**

[https://i.postimg.cc/zfHkyrGV/8.png]
base64上传图片报错 image type error:text/plain charset=utf-8
**复现方法**

使用[https://github.com/Tsuk1ko/cq-picsearcher-bot]发r18setu。

PS.使用上述bot搜图时能正常发送图片无报错。

**Comment by Ink-33** [comment]
#633

**Comment by Ink-33** [comment]
`error:text/plain`代表传入的是一段文本而不是图片，当然发不出去

**Comment by Mrs4s** [comment]
这个问题是应用给的图片数据格式不对，实际解码出来是text，请检查应用
