### ISSUE TITLE
[Not-Bug] 程序进程阻塞

### ISSUE THREAD

**Issue by remiliacn** [Mrs4s/go-cqhttp#11]
在使用的时候有些图片接受后会卡住整个程序（表现形式为不在接受并处理新的群/好友消息），之后必须在控制台中进行键盘操作才能继续接收新的信息（比如ctrl+z）。

使用config：
```
{
  "uin": 123123,
  "password": "",
  "enable_db": true,
  "access_token": "",
  "relogin": false,
  "relogin_delay": 0,
  "http_config": {
    "enabled": true,
    "host": "[::]",
    "port": 5700,
    "post_urls": {}
  },
  "ws_config": {
    "enabled": false,
    "host": "127.0.0.1",
    "port": 6700
  },
  "ws_reverse_servers": [
    {
      "enabled": true,
      "reverse_url": "",
      "reverse_api_url": "ws://127.0.0.1:5700/ws/api/",
      "reverse_event_url": "ws://127.0.0.1:5700/ws/event/",
      "reverse_reconnect_interval": 3000
    }
  ],
  "debug": false
}
```

**Comment by Mrs4s** [comment]
这个问题比较奇怪，所有消息的处理应该都是异步的，不会阻塞。得仔细研究下

**Comment by remiliacn** [comment]
的确奇怪，我也觉得不应该发生啊。我的机器人现在在10几个群里面，沙雕群友发沙雕图一发发一堆，我也不知道是哪一张出的问题。所以重现bug有些难（

**Comment by Mrs4s** [comment]
我这边100多个群的qq挂了一周了还没遇到过这个问题...

**Comment by remiliacn** [comment]
我发现这个问题怎么出现的了。。
如果我at一个人，同时在同一个信息中发送一个本地图片。程序就会阻塞。
试了5次，每一次都出现了阻塞。

**Comment by Mrs4s** [comment]
我晚点写个mock测试下. 比较奇怪emmm

**Comment by remiliacn** [comment]
恩？奇怪啊，现在又不阻塞了……会不会是我本地网络的问题……我再盯一会儿看看

**Comment by Shigma** [comment]
我觉得跟图片没关系。windows 上开的控制台窗口可能会因为鼠标点击而阻塞掉进程，在按下其他按键之后恢复，与你描述的情况比较像，你看看是不是因为你误触导致的这个问题？

**Comment by remiliacn** [comment]
应该没有吧……我印象中启动了进程没有碰过控制台窗口啊
这个一会儿一会儿的……我没看出来是什么原因草

**Comment by remiliacn** [comment]
不过Shigma@ 说的也有可能
可能不是程序的bug，是我这边的操作问题

**Comment by remiliacn** [comment]
正在尝试解决方式中：

- [x] 右键程序窗口

- [x] 将“快速编辑(QuickEdit mode)”前面的勾关掉

- [ ] 观察是否问题解决

**Comment by remiliacn** [comment]
看起来的确是Windows系统下误触控制台窗口产生的阻塞。

感谢Shigma@ 给的debug思路
> 我觉得跟图片没关系。windows 上开的控制台窗口可能会因为鼠标点击而阻塞掉进程，在按下其他按键之后恢复，与你描述的情况比较像，你看看是不是因为你误触导致的这个问题？

目前发现的解决方法：
* 右键程序进程
* 将`快速编辑模式(QuickEdit mode)`前面的勾去除
