### ISSUE TITLE
Centosx下get_message 以及get_forward_message无法使用，报id不存在错误。

### ISSUE THREAD

**Issue by Mechorca** [Mrs4s/go-cqhttp#1105]
**环境信息**

go-cqhttp版本: v1.0.0-beta7-fix2
运行环境: centos7.6
连接方式: http
使用协议: ipad

**在最新的release版本中能否复现**
是
**bug内容**

get_message 以及get_forward_message无法使用，报id不存在错误。
在Windows环境下测试正常
**复现方法**

我的test是把CQ码原样发回
![image](https://user-images.githubusercontent.com/87187802/137354746-20809148-8b1b-4926-ae4e-3c6030a271a9.png)
![image](https://user-images.githubusercontent.com/87187802/137354768-2a0dd482-2dc5-40cf-82f0-2efb5fe53f23.png)

**Comment by sam01101** [comment]
forward的CQ碼不能直接返回，請參考文檔的用法
