### ISSUE TITLE
图片缓存文件中的 url 存储有误，导致无法下载图片

### ISSUE THREAD

**Issue by Tamce** [Mrs4s/go-cqhttp#1106]
**环境信息**

go-cqhttp版本: v1.0.0-beta7-fix2
运行环境: linux (CentOS 7)
连接方式: websocket / http
使用协议: android

**在最新的release版本中能否复现**
能

**bug内容**
某些转发的消息（不确定是否跟转发消息有关，怀疑可能跟发送者的终端有关）中获取到的图片信息与 gocqhttp 缓存下来的 .image 元信息存储不符，导致无法获取对应图片，进一步导致 get_image 下载空文件
![image](https://user-images.githubusercontent.com/12567959/137371068-7ce2a86a-4852-48b1-ae6c-e44d9164f463.png)
![image](https://user-images.githubusercontent.com/12567959/137371224-66279c26-0777-439f-b0b5-81f618cfbbb6.png)

**复现方法**
1. 从转发消息中获取到图片相关的信息
![image](https://user-images.githubusercontent.com/12567959/137371607-28e0b841-b273-41ca-8a78-570958b17c7b.png)
可以看到 api 返回的结果是
```
{"file":"4408adf654dae70c71fa935a42a2d8f8.image","subType":"0","url":"https://gchat.qpic.cn/gchatpic_new/0/0-0-4408ADF654DAE70C71FA935A42A2D8F8/0?term=2"},"type":"image"}
```
2. 确定 gocqhttp 在缓存文件夹下存储的文件：
![image](https://user-images.githubusercontent.com/12567959/137372234-9fd1f8c3-7fd5-4e69-aed2-17171a81a41d.png)
发现 url 有误
3. 无论从什么协议，调用 get_image 获取图片，接口返回成功，并且对应的图片文件是空
![image](https://user-images.githubusercontent.com/12567959/137372335-6c4beb70-9916-462b-92c9-21730166383c.png)
期望接口应该返回失败，而不是成功，毕竟访问图片的真实 url 返回 404 了，而导致 404 的原因是因为 `data/image` 下文件记录的 url 就错了

**Comment by sam01101** [comment]
神奇了，為什麼我沒有404

在 2021年10月15日週五 上午2:09，Tamce ***@***.***> 寫道：

**Comment by Mrs4s** [comment]
这个是特殊情况下图片链接编码错误，下个版本修复

**Comment by Mrs4s** [comment]
已修复
