### ISSUE TITLE
使用C#开发, Http Post上报的内容已经被接收,,,但go-cqhttp端一直循环提示上报错误,,,具体看图

### ISSUE THREAD

**Issue by ChinaPhusun** [Mrs4s/go-cqhttp#1108]
**环境信息**

go-cqhttp版本: 
运行环境: Win10 Win11
连接方式: Http
使用协议: Ipad

**在最新的release版本中能否复现**

**bug内容**

![0](https://user-images.githubusercontent.com/38497378/137446323-fc0dac7c-7233-4b8a-8339-3eb5909cc7bc.jpg)
![1](https://user-images.githubusercontent.com/38497378/137446353-c0f317db-c9f8-4a97-b8e0-5ccd1eb88567.jpg)
![2](https://user-images.githubusercontent.com/38497378/137446372-f503aa5c-40c4-4dc8-9022-424e04a07ed1.jpg)

**复现方法**

**Comment by sam01101** [comment]
> **环境信息**
> 
> go-cqhttp版本: 运行环境: Win10 Win11 连接方式: Http 使用协议: Ipad
> 
> **在最新的release版本中能否复现**
> 
> **bug内容**
> 
> ![0](https://user-images.githubusercontent.com/38497378/137446323-fc0dac7c-7233-4b8a-8339-3eb5909cc7bc.jpg) ![1](https://user-images.githubusercontent.com/38497378/137446353-c0f317db-c9f8-4a97-b8e0-5ccd1eb88567.jpg) ![2](https://user-images.githubusercontent.com/38497378/137446372-f503aa5c-40c4-4dc8-9022-424e04a07ed1.jpg)
> 
> **复现方法**

你C#的代码写错了

**Comment by ChinaPhusun** [comment]
C#的代码写错了 为什么还能正常接收到上报的数据?
