### ISSUE TITLE
加载群列表速度过慢，是否有优化空间

### ISSUE THREAD

**Issue by takayama-lily** [Mrs4s/go-cqhttp#111]
![}MHU~{K5AYK049%6MOGZ8AH](https://user-images.githubusercontent.com/12014361/90316300-348f1900-df5c-11ea-8ef2-e3db49fb175a.png)
每次都差不多，加载了快1分钟。
貌似mirai和原来的CQ都很快。

**Comment by Mrs4s** [comment]
感谢提出，后续版本会考虑异步化加载群列表
