### ISSUE TITLE
经测试，机器人不会收到自己的操作触发的事件

### ISSUE THREAD

**Issue by takayama-lily** [Mrs4s/go-cqhttp#112]
比如机器人禁言了别人，或者踢了人，不会收到群禁言和踢人事件（消息撤回事件除外）。
这个是有意过滤掉了，还是本来就不会收到包呢？

**Comment by Mrs4s** [comment]
感谢提出，这部分后续版本会优化

**Comment by takayama-lily** [comment]
看了下代码，似乎只有群禁言主动过滤了。
其他地方没找到过滤代码，估计是本来就没有收到事件。
```go
case 0x0c: // 群内禁言
	operator := int64(uint32(r.ReadInt32()))
	if operator == c.Uin {
		continue
	}
```

**Comment by Mrs4s** [comment]
> 看了下代码，似乎只有群禁言主动过滤了。
> 其他地方没找到过滤代码，估计是本来就没有收到事件。
> 
> ```go
> case 0x0c: // 群内禁言
> 	operator := int64(uint32(r.ReadInt32()))
> 	if operator == c.Uin {
> 		continue
> 	}
> ```

因为不清楚CQ原本会怎么处理这部分，会处理的话我会考虑手动发一个事件

**Comment by takayama-lily** [comment]
CQ应该是没有做过什么额外的处理的，收到什么包就推什么事件（除了过滤掉了群里自己的发言）。
缺失的事件如果能手动构造触发是一个好主意。

**Comment by Arnie97** [comment]
记得 CQ 没做处理，能直接收到由 QQ 号 1000000（系统消息）发来的消息
以前 CQHTTP 还不能主动上报群头衔的时候踩过坑，去取这个用户头衔取不到
