### ISSUE TITLE
QQ扫码登录，显示请求超时

### ISSUE THREAD

**Issue by drsxyih** [Mrs4s/go-cqhttp#1132]
**环境信息**

go-cqhttp版本: v1.0.0-beta7-fix2
运行环境: CentOS 8.2
连接方式: 反向WS
使用协议: iPad

**在最新的release版本中能否复现**
可以

**bug内容**

使用QQ扫码登录go-cqhttp，允许登录后，显示请求超时，请稍后再试

**复现方法**

1.使用QQ扫码登录go-cqhttp
2.允许登录
3.显示请求超时，请稍后再试

**Comment by drsxyh** [comment]
开发者大大，看到请回下信息，谢谢

**Comment by sam01101** [comment]
#633

**Comment by Mrs4s** [comment]
可以尝试换台服务器登

**Comment by drsxyh** [comment]
> 可以尝试换台服务器登

目前手里没有多余的服务器，尝试过更换系统，发现情况一致

**Comment by asjdf** [comment]
遇到了相同情况

**Comment by shangdev** [comment]
同样问题 +1

**Comment by shangdev** [comment]
我发现是风控影响的，还有就是新申请的号、

**Comment by xiguasamall** [comment]
风控问题，tx不会直接告诉你的，修改密码，更新其他账号即可
