### ISSUE TITLE
希望新增红包类型字段

### ISSUE THREAD

**Issue by NepPure** [Mrs4s/go-cqhttp#1142]
**环境信息**

go-cqhttp版本: v1.0.0-beta7-fix2

**需要添加的功能内容**

想识别口令红包然后开启全员禁言，或者bot自动静默一段时间之类，当前测试了一下所有红包都是一个类型，信息量不足

感谢大佬

**Comment by sam01101** [comment]
#530 #633

**Comment by NepPure** [comment]
看了眼12草案也没提这个
