### ISSUE TITLE
无法上报事件

### ISSUE THREAD

**Issue by A2577467404** [Mrs4s/go-cqhttp#1144]
**环境信息**

go-cqhttp版本: v1.0.0-beta7-fix2
运行环境: Windows11 x64
连接方式: HTTP
使用协议: HTTP

**在最新的release版本中能否复现**

**bug内容**
[WARNING]: 上报Event数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":486678426,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":34,"packet_sent":26,"packet_lost":0,"message_received":3,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1636624547}},"time":1636624552}
 到 127.0.0.1:5701 失败: Post "http://127.0.0.1:5701": net/http: HTTP/1.x transport connection broken: unexpected EOF

一直这样，收发正常，无法实现自动回复

**复现方法**
直接启动

**Comment by wdvxdr1123** [comment]
请检查系统代理

**Comment by ChurchillDu** [comment]
@A2577467404  你好，请问你解决了嘛？我在 azure 上也发现了这个问题

**Comment by ChurchillDu** [comment]
> @A2577467404 你好，请问你解决了嘛？我在 azure 上也发现了这个问题

原来启动efb-qq-slave ，端口有进程监听就好了
