### ISSUE TITLE
建议提供工具将miraiandroid导出的config.json迁移到go-cqhttp

### ISSUE THREAD

**Issue by icerxkx** [Mrs4s/go-cqhttp#1145]
**环境信息**
go-cqhttp版本: 所有版本

**需要添加的功能内容**
miraiandroid可以在手机上导出config.json，真实度比较高，但格式与go-cqhttp不一致。能否提供接口或者工具将其转换成go-cqhttp的config.json格式？确实被风控搞得没脾气了

**Comment by sam01101** [comment]
我们当然非常乐意, 只要你愿意帮助我们贡献这个工具, 我们会非常感激的

**Comment by icerxkx** [comment]
是说miraiandroid？这个在 https://github.com/mzdluo123/MiraiAndroid
下载地址是在 https://install.appcenter.ms/users/mzdluo123/apps/miraiandroid/distribution_groups/release
在手机上安装，登录，然后导出config.json即可

**Comment by Mrs4s** [comment]
暂时应该不会有相关工具的开发计划.
这个其实可以自己写的, 就是json字段转换

**Comment by sam01101** [comment]
@icerxkx 我的意思是你可以自己写一个然后提交 PR (Pull Request)

> 这个其实可以自己写的, 就是json字段转换

**Comment by icerxkx** [comment]
了解了。刚才研究了一下miraiandroid导出的config.json，发现就是把字母换成了ascii码，换回去之后除了多了个imei，别的区别不大，看来是我高兴得太早。。。

**Comment by Ink-33** [comment]
![-54b6650dc369f137.jpg](https://user-images.githubusercontent.com/51873347/141308852-b723a718-77fe-4eec-a390-440ffbe3783d.jpg)
miraiandroid的device并没有读取手机信息，也是随机生成的，并不能有效防止风控

**Comment by icerxkx** [comment]
嗯，是我想当然了，抱歉。不过还是希望能解决风控的问题，我删token也不好使。。。
