### ISSUE TITLE
希望支持安卓平板协议

### ISSUE THREAD

**Issue by gclm** [Mrs4s/go-cqhttp#1146]
**环境信息**
go-cqhttp版本:  v1.0.0-beta7-fix2
linux: centos8

**需要添加的功能内容**
希望新增安卓平板协议，原因是安卓平板的device.json好伪造，甚至可以找个安卓平板把信息勾出来，现在ipad协议太难伪造了。mirai 是支持安卓平板协议的。
![image](https://user-images.githubusercontent.com/27618687/141400702-ceafdaf6-b817-4f13-ac03-053441e6ec26.png)

**Comment by Mrs4s** [comment]
安卓平板协议由于限制太多, 并不适合拿来当BOT
