### ISSUE TITLE
unsupported protocol scheme

### ISSUE THREAD

**Issue by hanximeng** [Mrs4s/go-cqhttp#1148]
在配置文件未改变的情况下，更新至beta8运行后使用http通信的方法会提示unsupported protocol scheme

>  [2021-11-13 09:59:54] [WARNING]: 上报 Event 数据到 127.0.0.1 失败: Post "127.0.0.1": unsupported protocol scheme "" 将进行第 1 次重试

> [2021-11-13 09:59:55] [WARNING]: 上报 Event 数据到 127.0.0.1 失败: Post "127.0.0.1": unsupported protocol scheme "" 将进行第 2 次重试

> [2021-11-13 09:59:56] [WARNING]: 上报 Event 数据到 127.0.0.1 失败: Post "127.0.0.1": unsupported protocol scheme "" 将进行第 3 次重试

> [2021-11-13 09:59:58] [WARNING]: 上报 Event 数据到 127.0.0.1 失败: Post "127.0.0.1": unsupported protocol scheme "" 将进行第 4 次重试

**Comment by wdvxdr1123** [comment]
请使用 `http://127.0.0.1/` 之类的

**Comment by hanximeng** [comment]
使用 http://127.0.0.1/ 发现无法使用PHP的 php://input 方法获取到go-cqhttp传入POST的数据

**Comment by sam01101** [comment]
#633
