### ISSUE TITLE
关于新加入的QQ频道的多个Bug

### ISSUE THREAD

**Issue by mnixry** [Mrs4s/go-cqhttp#1149]
**环境信息**

go-cqhttp版本: v1.0.0-beta8
运行环境: Linux5.10.78-1-MANJARO
连接方式: 反向WebSocket
使用协议: Android Phone

**在最新的release版本中能否复现**
是

**bug内容**

1. 在启动时出现错误
```
[2021-11-13 11:05:09] [ERROR]: Protocol -> panic on decoder trpc.group_pro.synclogic.SyncLogic.PushFirstView : runtime error: invalid memory address or nil pointer dereference
goroutine 76 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20211112183036-d3a21e577b02/client/network.go:323 +0x5d
panic({0xbc5020, 0x13e8d50})
        runtime/panic.go:1038 +0x215
github.com/Mrs4s/MiraiGo/client.(*GuildService).GetGuildMembers(0xc0004942d0, 0x1)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211112183036-d3a21e577b02/client/guild.go:226 +0xab3
github.com/Mrs4s/MiraiGo/client.decodeGuildPushFirstView(0xc000032900, 0x2bc, {0xc000394dc0, 0x2bc, 0x2bc})
        github.com/Mrs4s/MiraiGo@v0.0.0-20211112183036-d3a21e577b02/client/guild.go:458 +0x46b
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc00091b040)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211112183036-d3a21e577b02/client/network.go:333 +0x1cb
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20211112183036-d3a21e577b02/client/network.go:320 +0x652
```
2. 无法获取到全部已加入频道的消息
    - `get_guild_list`不返回获取不到消息的频道
    - 在接受到来自无法获取消息的频道消息时, 有日志`Protocol -> rev pkt: MsgPush.PushGroupProMsg seq: 17451`
3. 当设置消息以数组形式上报时, 所有频道发出的除了`text`之外类型的消息都不会被添加入数组, 即会上报一个值为`[]`的`message`字段

**复现方法**
使用Android Phone协议登录具有频道内测权限的QQ账号

**Comment by NWYLZW** [comment]
+1

**Comment by yujincheng08** [comment]
我这里也有一个
```
[2021-11-13 09:54:34] [INFO]: 处置WS命令时发生无法恢复的异常：runtime error: invalid memory address or nil pointer dereference
goroutine 12027 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/go-cqhttp/server.(*wsConn).handleRequest.func1()
        /build/server/websocket.go:340 +0x46
panic({0xbc5100, 0x13ecd50})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/Mrs4s/MiraiGo/client.(*GuildService).SendGuildChannelMessage(0xc00006d1d0, 0xde54843548767b, 0x1255da, 0xc0006e2ca0)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211112183036-d3a21e577b02/client/guild_msg.go:87 +0x5ea
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).SendGuildChannelMessage(0xc0003c5950, 0xc0007972a9, 0x271, 0xc0006e2ca0)
        /build/coolq/bot.go:368 +0x11f
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSendGuildChannelMessage(0xc0003c5950, 0x0, 0x0, {0x5, {0xc0007972a9, 0x271}, {0x0, 0x0}, 0x0, 0xa9, ...}, ...)
        /build/coolq/api.go:597 +0x245
github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).call(0xc000287de0, {0xc00079720c, 0x16}, {0xde2900, 0xc0008fb5e0})
        /build/modules/api/api.go:185 +0x71ad
github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).Call(0xc000287de0, {0xc00079720c, 0x16}, {0xde2900, 0xc0008fb5e0})
        /build/modules/api/caller.go:34 +0xaa
github.com/Mrs4s/go-cqhttp/server.(*wsConn).handleRequest(0xc000798fd0, 0x8fe740, {0xc000797200, 0xc0008fb310, 0xc0000773e0})
        /build/server/websocket.go:347 +0x525
github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenAPI.func2(0xc00044da30)
        /build/server/websocket.go:185 +0x95
created by github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenAPI
        /build/server/websocket.go:183 +0x1b7
```

**Comment by Mrs4s** [comment]
> 我这里也有一个
> 
> ```
> [2021-11-13 09:54:34] [INFO]: 处置WS命令时发生无法恢复的异常：runtime error: invalid memory address or nil pointer dereference
> goroutine 12027 [running]:
> runtime/debug.Stack()
>         /usr/local/go/src/runtime/debug/stack.go:24 +0x65
> github.com/Mrs4s/go-cqhttp/server.(*wsConn).handleRequest.func1()
>         /build/server/websocket.go:340 +0x46
> panic({0xbc5100, 0x13ecd50})
>         /usr/local/go/src/runtime/panic.go:1038 +0x215
> github.com/Mrs4s/MiraiGo/client.(*GuildService).SendGuildChannelMessage(0xc00006d1d0, 0xde54843548767b, 0x1255da, 0xc0006e2ca0)
>         /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211112183036-d3a21e577b02/client/guild_msg.go:87 +0x5ea
> github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).SendGuildChannelMessage(0xc0003c5950, 0xc0007972a9, 0x271, 0xc0006e2ca0)
>         /build/coolq/bot.go:368 +0x11f
> github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSendGuildChannelMessage(0xc0003c5950, 0x0, 0x0, {0x5, {0xc0007972a9, 0x271}, {0x0, 0x0}, 0x0, 0xa9, ...}, ...)
>         /build/coolq/api.go:597 +0x245
> github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).call(0xc000287de0, {0xc00079720c, 0x16}, {0xde2900, 0xc0008fb5e0})
>         /build/modules/api/api.go:185 +0x71ad
> github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).Call(0xc000287de0, {0xc00079720c, 0x16}, {0xde2900, 0xc0008fb5e0})
>         /build/modules/api/caller.go:34 +0xaa
> github.com/Mrs4s/go-cqhttp/server.(*wsConn).handleRequest(0xc000798fd0, 0x8fe740, {0xc000797200, 0xc0008fb310, 0xc0000773e0})
>         /build/server/websocket.go:347 +0x525
> github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenAPI.func2(0xc00044da30)
>         /build/server/websocket.go:185 +0x95
> created by github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenAPI
>         /build/server/websocket.go:183 +0x1b7
> ```

请问是具体发送了什么信息 能否多次复现

**Comment by yujincheng08** [comment]
> > 我这里也有一个
> > ```
> > [2021-11-13 09:54:34] [INFO]: 处置WS命令时发生无法恢复的异常：runtime error: invalid memory address or nil pointer dereference
> > goroutine 12027 [running]:
> > runtime/debug.Stack()
> >         /usr/local/go/src/runtime/debug/stack.go:24 +0x65
> > github.com/Mrs4s/go-cqhttp/server.(*wsConn).handleRequest.func1()
> >         /build/server/websocket.go:340 +0x46
> > panic({0xbc5100, 0x13ecd50})
> >         /usr/local/go/src/runtime/panic.go:1038 +0x215
> > github.com/Mrs4s/MiraiGo/client.(*GuildService).SendGuildChannelMessage(0xc00006d1d0, 0xde54843548767b, 0x1255da, 0xc0006e2ca0)
> >         /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211112183036-d3a21e577b02/client/guild_msg.go:87 +0x5ea
> > github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).SendGuildChannelMessage(0xc0003c5950, 0xc0007972a9, 0x271, 0xc0006e2ca0)
> >         /build/coolq/bot.go:368 +0x11f
> > github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSendGuildChannelMessage(0xc0003c5950, 0x0, 0x0, {0x5, {0xc0007972a9, 0x271}, {0x0, 0x0}, 0x0, 0xa9, ...}, ...)
> >         /build/coolq/api.go:597 +0x245
> > github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).call(0xc000287de0, {0xc00079720c, 0x16}, {0xde2900, 0xc0008fb5e0})
> >         /build/modules/api/api.go:185 +0x71ad
> > github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).Call(0xc000287de0, {0xc00079720c, 0x16}, {0xde2900, 0xc0008fb5e0})
> >         /build/modules/api/caller.go:34 +0xaa
> > github.com/Mrs4s/go-cqhttp/server.(*wsConn).handleRequest(0xc000798fd0, 0x8fe740, {0xc000797200, 0xc0008fb310, 0xc0000773e0})
> >         /build/server/websocket.go:347 +0x525
> > github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenAPI.func2(0xc00044da30)
> >         /build/server/websocket.go:185 +0x95
> > created by github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenAPI
> >         /build/server/websocket.go:183 +0x1b7
> > ```
> 
> 请问是具体发送了什么信息 能否多次复现

[2021-11-13 09:54:32] [DEBUG]: WS接收到API调用: send_guild_channel_msg 参数: {"channel_id": 1201626, "guild_id": 62580371636123259, "message_type": "guild", "user_id": 144115218677268830, "message": [{"type": "text", "data": {"text": "\u300c\u30b9\u30ab\u30fc\u30c8\u306e\u4e2d\u300d"}}, {"type": "image", "data": {"file": "http://pixiv.lovesykun.cn/img-master/img/2021/03/16/23/11/47/88499488_p0_master1200.jpg"}}, {"type": "text", "data": {"text": "\npid: 88499488\ntag: \u5973\u306e\u5b50, \u5973\u5b69\u5b50, \u30aa\u30ea\u30b8\u30ca\u30eb, \u539f\u521b, \u5275\u4f5c, \u4e0b\u7740, \u5185\u8863, \u30b1\u30e2\u30df\u30df, \u517d\u8033, \u732b, cat, \u30e1\u30a4\u30c9, \u5973\u4ec6, \u9ad8\u54c1\u8cea\u30d1\u30f3\u30c4, \u9ad8\u54c1\u8d28\u5185\u88e4, \u30ac\u30fc\u30bf\u30fc\u30d9\u30eb\u30c8, \u540a\u889c\u5e26"}}]}

**Comment by Dragon-Fish** [comment]
程序启动后，新加入的频道或新创建的子频道收到消息时可能会导致以下报错：

```
runtime error: invalid memory address or nil pointer dereference
```

重启程序后正常

**Comment by KimigaiiWuyi** [comment]
`event error: runtime error: invalid memory address or nil pointer dereference
goroutine 178 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.cover.func1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20211112183036-d3a21e577b02/client/events.go:533 +0x39
panic({0xbc5020, 0x13e8d50})
        runtime/panic.go:1038 +0x215
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).guildChannelMessageEvent(0xc0004e05a0, 0xc0001fd200, 0xc0006a0820)
        github.com/Mrs4s/go-cqhttp/coolq/event.go:163 +0x162
github.com/Mrs4s/MiraiGo/client.(*QQClient).dispatchGuildChannelMessage.func1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20211112183036-d3a21e577b02/client/events.go:254 +0x28
github.com/Mrs4s/MiraiGo/client.cover(0x83a9b177ff6109)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211112183036-d3a21e577b02/client/events.go:536 +0x3e
github.com/Mrs4s/MiraiGo/client.(*QQClient).dispatchGuildChannelMessage(0xc0001fd200, 0xc0006a0820)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211112183036-d3a21e577b02/client/events.go:253 +0x95
github.com/Mrs4s/MiraiGo/client.decodeGuildEventFlowPacket(0xc0000c28c0, 0xd1, {0xc0000c28c0, 0xd1, 0xd1})
        github.com/Mrs4s/MiraiGo@v0.0.0-20211112183036-d3a21e577b02/client/guild_eventflow.go:73 +0x168
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc000871f40)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211112183036-d3a21e577b02/client/network.go:333 +0x1cb
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20211112183036-d3a21e577b02/client/network.go:320 +0x652
event error: runtime error: invalid memory address or nil pointer dereference
`

新添加管理员频道，并把机器人设为管理员，在频道内发送任何消息即可复现。
重启后正常

**Comment by CodeZWT** [comment]
````
[2021-11-12 17:21:57] [ERROR]: Protocol -> panic on decoder MultiMsg.ApplyDown : runtime error: invalid memory address or nil pointer dereference goroutine 2055 [running]:
runtime/debug.Stack(0xc000281b00, 0xda5c20, 0x15a5a30)
	runtime/debug/stack.go:24 +0xa5
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1(0xc0002ec000, 0xc0002a7f40)
	github.com/Mrs4s/MiraiGo@v0.0.0-20210810070836-6614d2383adb/client/network.go:204 +0x78
panic(0xda5c20, 0x15a5a30)
	runtime/panic.go:965 +0x1c7
github.com/Mrs4s/MiraiGo/utils.HttpGetBytes.func1(0x0, 0x0)
	github.com/Mrs4s/MiraiGo@v0.0.0-20210810070836-6614d2383adb/utils/http.go:23 +0x29
github.com/Mrs4s/MiraiGo/utils.HttpGetBytes(0xc000127080, 0x17c, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff6ec0, 0xc000329a40)
	github.com/Mrs4s/MiraiGo@v0.0.0-20210810070836-6614d2383adb/utils/http.go:25 +0x106
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse(0xc0002ec000, 0xc00024b8c0, 0xc00029a900, 0x228, 0x228, 0xc3be01, 0xc0003a8400, 0xc000328990, 0x15c4e20)
	github.com/Mrs4s/MiraiGo@v0.0.0-20210810070836-6614d2383adb/client/multimsg.go:103 +0x271
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0002ec000, 0xc0002a7f40)
	github.com/Mrs4s/MiraiGo@v0.0.0-20210810070836-6614d2383adb/client/network.go:211 +0x198
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
	github.com/Mrs4s/MiraiGo@v0.0.0-20210810070836-6614d2383adb/client/network.go:201 +0x3d7
 ````
该报错在beta7版本存在，在未更新gocphttp的情况下于10月15号开始产生，之前只要发长文本就会出现，但我更新beta8之后反而不复现了

**Comment by Mrs4s** [comment]
应该都处理好了
