### ISSUE TITLE
采用修复版还是会出现裂图的问题

### ISSUE THREAD

**Issue by jdgjxxchy** [Mrs4s/go-cqhttp#115]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: https://github.com/Mrs4s/go-cqhttp/actions/runs/207861506 
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
#65 
原来不能用的群 现在有时可以发有时裂图
原来能用的群现在裂图...

**复现方法**
找到一个裂图的群

**Comment by takayama-lily** [comment]
我这出现过图裂，但是双击能打开的情况（也就是其实没裂）。

**Comment by shitianshiwa** [comment]
> 我这出现过图裂，但是双击能打开的情况（也就是其实没裂）。

但有些图片是怎么点都点不开，而部分图移动端可以显示，但电脑端无法显示。总之，机器人发的图片像薛定谔的猫。

**Comment by Mrs4s** [comment]
挺迷惑的
