### ISSUE TITLE
发送图片报错并断开反向ws连接

### ISSUE THREAD

**Issue by SlightDust** [Mrs4s/go-cqhttp#1156]
**环境信息**

go-cqhttp版本: v1.0.0-beta8  
运行环境: Linux x86  
连接方式: 反向ws  
使用协议: ipad  

**在最新的release版本中能否复现**
能  
**bug内容**

发送图片时会报错
![image](https://user-images.githubusercontent.com/53001305/141644591-1b3cfabd-e27c-4ecc-8a20-8b51786a1551.png)  
回退到1.0.0-beta7-fix2可以正常发送
**复现方法**

直接发送图片，100%复现

**Comment by Dragon-Fish** [comment]
Meet the same issue

**Comment by Dragon-Fish** [comment]
发送 base64 图片时稳定触发

本地图片与远程图片暂时没有影响

**Comment by zhanbao2000** [comment]
一模一样的问题
go-cqhttp这边输出：
```
[2021-11-14 13:33:18] [WARNING]: 监听反向WS API时出现错误: failed to read: read limited at 32769 bytes
[2021-11-14 13:33:21] [WARNING]: 向WS服务器推送 Event 时出现错误: failed to write msg: WebSocket closed: read limited at 32769 bytes
```
nonebot2那边输出：
```
websockets.exceptions.ConnectionClosedError: code = 1009 (message too big), reason = read limited at 32769 bytes
```

**Comment by Ink-33** [comment]
bug，修了，等发版，或者下载最新action

**Comment by Mrs4s** [comment]
已修复
