### ISSUE TITLE
反向WS不重连

### ISSUE THREAD

**Issue by chenxuxin188** [Mrs4s/go-cqhttp#116]
**环境信息**
go-cqhttp版本: v0.9.19
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
反向WS断开之后没反应

**复现方法**
开着go-cqhttp，连上了反向WS。服务端那边关掉之后，go这边啥反应也没有。再打开反向WS服务器也不会重连。

**Comment by Mrs4s** [comment]
请问连接的是哪个接口 api event 还是 universal?

**Comment by chenxuxin188** [comment]
> 请问连接的是哪个接口 api event 还是 universal?

更正一下描述，是在配置了access token了之后，连反向WS的话会能连上，但是一点反应也没有。我就只配置了universal

**Comment by Mrs4s** [comment]
> > 请问连接的是哪个接口 api event 还是 universal?
> 
> 更正一下描述，是在配置了access token了之后，连反向WS的话会能连上，但是一点反应也没有。我就只配置了universal

请问使用的什么框架，不配置access token的话就能正常上报吗？

**Comment by chenxuxin188** [comment]
> > > 请问连接的是哪个接口 api event 还是 universal?
> > 
> > 
> > 更正一下描述，是在配置了access token了之后，连反向WS的话会能连上，但是一点反应也没有。我就只配置了universal
> 
> 请问使用的什么框架，不配置access token的话就能正常上报吗？

用的aiocqhttp...  我重开了几次之后突然就能用了  懵逼

**Comment by Mrs4s** [comment]
> > > > 请问连接的是哪个接口 api event 还是 universal?
> > > 
> > > 
> > > 更正一下描述，是在配置了access token了之后，连反向WS的话会能连上，但是一点反应也没有。我就只配置了universal
> > 
> > 
> > 请问使用的什么框架，不配置access token的话就能正常上报吗？
> 
> 用的aiocqhttp... 我重开了几次之后突然就能用了 懵逼

感谢反馈 我有空会检查下这个问题

**Comment by chenxuxin188** [comment]
> > > > > 请问连接的是哪个接口 api event 还是 universal?
> > > > 
> > > > 
> > > > 更正一下描述，是在配置了access token了之后，连反向WS的话会能连上，但是一点反应也没有。我就只配置了universal
> > > 
> > > 
> > > 请问使用的什么框架，不配置access token的话就能正常上报吗？
> > 
> > 
> > 用的aiocqhttp... 我重开了几次之后突然就能用了 懵逼
> 
> 感谢反馈 我有空会检查下这个问题

问题又复现了……大概是这样，似乎并不是每次后台关掉之后go这边就能马上检测到。

**Comment by Mrs4s** [comment]
> > > > > > 请问连接的是哪个接口 api event 还是 universal?
> > > > > 
> > > > > 
> > > > > 更正一下描述，是在配置了access token了之后，连反向WS的话会能连上，但是一点反应也没有。我就只配置了universal
> > > > 
> > > > 
> > > > 请问使用的什么框架，不配置access token的话就能正常上报吗？
> > > 
> > > 
> > > 用的aiocqhttp... 我重开了几次之后突然就能用了 懵逼
> > 
> > 
> > 感谢反馈 我有空会检查下这个问题
> 
> 问题又复现了……大概是这样，似乎并不是每次后台关掉之后go这边就能马上检测到。

目前理论上是每次推送event的时候会检查ws连接是否存活

**Comment by chenxuxin188** [comment]
这个我关闭了。。经过一晚上的折腾确认了是我电脑的问题，裂开。。
