### ISSUE TITLE
[ERROR]: Protocol -> test long message server latency error: failed to connect to server during quality test: dial tcp 0.0.0.1:443: i/o timeout

### ISSUE THREAD

**Issue by infinityedge01** [Mrs4s/go-cqhttp#1161]
**环境信息**

环境信息 go-cqhttp版本: v1.0.0-beta8
运行环境: ubuntu server 20.04
连接方式: ws-reverse
使用协议: ws-reverse

**在最新的release版本中能否复现**
是最新release
**bug内容**

发送json消息会出现

`[2021-11-14 16:18:51] [ERROR]: Protocol -> test long message server latency error: failed to connect to server during quality test: dial tcp 0.0.0.1:443: i/o timeout`
**复现方法**

使用nonebot发送json消息

**Comment by Akegarasu** [comment]
检查一下你的DNS 使用nslookup指令看一下或者`curl https://ssl.htdata.qq.com`

**Comment by infinityedge01** [comment]
> 检查一下你的DNS 使用nslookup指令看一下或者`curl https://ssl.htdata.qq.com` 另外，不要刷issue。

我这里dns解析的结果是正常的：
```
Non-authoritative answer:
Name:   ssl.htdata.qq.com
Address: 175.27.12.145
```
curl的结果也是正常的（502 bad gateway），但不知为何上面是0.0.0.1……

**Comment by Akityo** [comment]
一样的问题，我dns是这样

root@qinglong:/ql/scripts/QQ $ nslookup ssl.htdata.qq.com
Server:		183.60.83.19
Address:	183.60.83.19:53

Non-authoritative answer:
Name:	ssl.htdata.qq.com
Address: 0.0.0.1

Non-authoritative answer:

**Comment by zzm88** [comment]
我在腾讯云docker部署遇到同样的问题，修改dns服务器也没用（本地同样的docker容器运行正常），cqhttp里还是会解析成0.0.0.1

```
解决办法：
/etc/hosts 里添加一条183.2.143.60 ssl.htdata.qq.com
```
这个办法不太好，如果ip地址变了就不好使了，等一个更好的办法。

**Comment by fallenleavesguy** [comment]
我的腾讯云也是这样。。。dns是0.0.0.1

**Comment by Ink-33** [comment]
> 我的腾讯云也是这样。。。dns是0.0.0.1

~~小心tx下毒~~

**Comment by CercisSuoh** [comment]
腾讯云: 简单粗暴就直接修改/etc/resolv.conf 里的 nameserver

**Comment by qycss** [comment]
蹲蹲解决方案

**Comment by qycss** [comment]
关于腾讯云`0.0.0.1:443`的情况，尝试着增加指定服务器地点对应的nameserver成功了，仅供参考
> https://blog.csdn.net/yeshennet/article/details/82287105

**Comment by ChanningWang2018** [comment]
`Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   ssl.htdata.qq.com
Address: 0.0.0.1
`
