### ISSUE TITLE
README.md存在无效链接

### ISSUE THREAD

**Issue by xiaozuo7** [Mrs4s/go-cqhttp#1165]
**环境信息**

go-cqhttp版本: 
运行环境: 
连接方式: 
使用协议: 

**在最新的release版本中能否复现**

**bug内容**
`README`.md存在无效链接哦
![BH~MR`Y@)S~5%S0D(C)7 _E](https://user-images.githubusercontent.com/49382984/141742396-2ce59f74-5890-4eda-ba5a-6653b916ba43.png)

**复现方法**
README.md --> 已实现功能--> 点击任意链接 --> 404

**Comment by sam01101** [comment]
因为repo改了，因为导致链接404
