### ISSUE TITLE
CQHTTP功能实现请求

### ISSUE THREAD

**Issue by Mrs4s** [Mrs4s/go-cqhttp#117]
目前go-cqhttp暂未实现原CQHTTP的某些功能，故开此ISSUE收集，在工作基本完成后 CQHTTP4.5 协议实现将在单独的分支仅做bug修复，开发重心将调整到新的CQHTTP10.0

**如发现 go-cqhttp 与原 CQHTTP 功能上有差异/缺失功能, 请在此issue回复**

**Comment by Shigma** [comment]
解析请求响应并以 retcode 形式返回（目前的 retcode 似乎只有 100）

**Comment by Shigma** [comment]
send_like（尽管 mirai 宣称不会实现此功能，但此接口确实是 cqhttp 的一部分）

**Comment by Mrs4s** [comment]
> send_like（尽管 mirai 宣称不会实现此功能，但此接口确实是 cqhttp 的一部分）

`send_like` 确实不会支持，正经bot应该用不上...

**Comment by Shigma** [comment]
[CQ:music] 实现 #57

**Comment by takayama-lily** [comment]
cqhttp执行快速回复的时候，如果是群聊，默认会at对方，除非传入at_sender:false
现在好像没有at对方

**Comment by chenxuxin188** [comment]
return code吧。。发送图片失败的时候后端都不知道失败了。

**Comment by shitianshiwa** [comment]
> send_like（尽管 mirai 宣称不会实现此功能，但此接口确实是 cqhttp 的一部分）

这个其实原酷Q官方也不推荐使用，因为存在封号风险，而且即使酷Q不关闭，点赞功能也将在未来停用。

**Comment by Officeyutong** [comment]
CQ:record 完整支持
现在似乎只支持amr

**Comment by takayama-lily** [comment]
尚未支持的cq码：
[CQ:emoji,id=123456] id是emoji字符的10进制整数，虽然感觉deprecated了，但有一些应用可能还在使用，然后cqhttp有个配置是：是否自动转换该cq码为emoji字符。
[CQ:bface,id=FC879AE51FCF5498462B0B4FD7F0665D,p=203385]，原创表情cq码，目前收到的是"[耶]"、"[太棒了]"之类的
[CQ:location]地点类

**Comment by Shigma** [comment]
[CQ:image] 希望能补上 url 字段

**Comment by masnn** [comment]
> [CQ:image] 希望能补上 url 字段

我记得有的吧   不会是你加的（？

**Comment by takayama-lily** [comment]
一些原来的cqhttp配置：
* `post_timeout` 上报超时，单位秒
* `enable_cors` 跨域允许
* `event_filter` 事件过滤器，有人提了#110 正则匹配，貌似有些复杂
* `enable_heartbeat` `heartbeat_interval` ws心跳
* `enable_rate_limited_actions` `rate_limit_interval` 限速调用的api #101 (还有异步调用的，后缀 _async)

还有一些平台相关的、日志配置、线程池配置等 [旧文档](https://richardchien.gitee.io/coolq-http-api/docs/4.15/#/Configuration)

**Comment by Mrs4s** [comment]
> [CQ:image] 希望能补上 url 字段

url字段目前是有的

**Comment by Shigma** [comment]
啊只是 log 中没有显示吗……抱歉抱歉

**Comment by jdgjxxchy** [comment]
#50 
连上ws之后希望加一个推送事件. 方便ws后端进行连接处理. 连接ws后端的除了bot外还有浏览器的websocket服务, 因此需要鉴别.
原CQHTTP元事件
https://richardchien.gitee.io/coolq-http-api/docs/4.15/#/Post?id=%E5%85%83%E4%BA%8B%E4%BB%B6%E5%88%97%E8%A1%A8
meta_event_type. lifecycle.connect

**Comment by takayama-lily** [comment]
> #50
> 连上ws之后希望加一个推送事件. 方便ws后端进行连接处理. 连接ws后端的除了bot外还有浏览器的websocket服务, 因此需要鉴别.
> 原CQHTTP元事件
> https://richardchien.gitee.io/coolq-http-api/docs/4.15/#/Post?id=%E5%85%83%E4%BA%8B%E4%BB%B6%E5%88%97%E8%A1%A8
> meta_event_type. lifecycle.connect

这个应该可以在连接的头部中判断出来是哪个

**Comment by xiaokaizhi** [comment]
原先CQHTTP是没有发生群临时会话API的。希望楼主能增加这个扩展功能。之前发的问题楼主说是支持回复群临时会话。只能回复不能主动发起群临时会话吗。这里说的群临时会话指的是：在一个群里主动和群里某个非好友的人单独私聊。

**Comment by zhzRedstone** [comment]
> 原先CQHTTP是没有发生群临时会话API的。希望楼主能增加这个扩展功能。之前发的问题楼主说是支持回复群临时会话。只能回复不能主动发起群临时会话吗。这里说的群临时会话指的是：在一个群里主动和群里某个非好友的人单独私聊。

主要是怕被滥用。还是整个聊天机制。
比如用户主动给bot发送任意消息，bot就打开这个api，开始推送消息，
用户无操作五分钟后关闭该api。

之类的。。

**Comment by xiaokaizhi** [comment]
> > 原先CQHTTP是没有发生群临时会话API的。希望楼主能增加这个扩展功能。之前发的问题楼主说是支持回复群临时会话。只能回复不能主动发起群临时会话吗。这里说的群临时会话指的是：在一个群里主动和群里某个非好友的人单独私聊。
> 
> 主要是怕被滥用。还是整个聊天机制。
> 比如用户主动给bot发送任意消息，bot就打开这个api，开始推送消息，
> 用户无操作五分钟后关闭该api。
> 
> 之类的。。

嗯。之前酷Q是最近有在群里发过言的人是可以主动私聊的。酷Q这么良心控制的这么严格也G了。滥用的问题是不是交给使用者本身去承担。毕竟群是他自己的。

**Comment by zhzRedstone** [comment]
> > > 原先CQHTTP是没有发生群临时会话API的。希望楼主能增加这个扩展功能。之前发的问题楼主说是支持回复群临时会话。只能回复不能主动发起群临时会话吗。这里说的群临时会话指的是：在一个群里主动和群里某个非好友的人单独私聊。
> > 
> > 
> > 主要是怕被滥用。还是整个聊天机制。
> > 比如用户主动给bot发送任意消息，bot就打开这个api，开始推送消息，
> > 用户无操作五分钟后关闭该api。
> > 之类的。。
> 
> 嗯。之前酷Q是最近有在群里发过言的人是可以主动私聊的。酷Q这么良心控制的这么严格也G了。滥用的问题是不是交给使用者本身去承担。毕竟群是他自己的。

比如，，封号？ 
到时候还会查水表的（）

**Comment by xiaokaizhi** [comment]
> > > > 原先CQHTTP是没有发生群临时会话API的。希望楼主能增加这个扩展功能。之前发的问题楼主说是支持回复群临时会话。只能回复不能主动发起群临时会话吗。这里说的群临时会话指的是：在一个群里主动和群里某个非好友的人单独私聊。
> > > 
> > > 
> > > 主要是怕被滥用。还是整个聊天机制。
> > > 比如用户主动给bot发送任意消息，bot就打开这个api，开始推送消息，
> > > 用户无操作五分钟后关闭该api。
> > > 之类的。。
> > 
> > 
> > 嗯。之前酷Q是最近有在群里发过言的人是可以主动私聊的。酷Q这么良心控制的这么严格也G了。滥用的问题是不是交给使用者本身去承担。毕竟群是他自己的。
> 
> 比如，，封号？
> 到时候还会查水表的（）

查水表？
别吓我啊：（）

**Comment by zxc7895531** [comment]
希望早日支持除了amr格式以外音频文件的发送。以及加入发送图片以及语音时对相对路径的支持，这样可以稍微简化代码。

**Comment by Mrs4s** [comment]
> 希望早日支持除了amr格式以外音频文件的发送。以及加入发送图片以及语音时对相对路径的支持，这样可以稍微简化代码。

支持其他格式语音发送需要集成ffmpeg, 目前计划在 `V0.9.22` 支持.

**Comment by pokebox** [comment]
可以增加一个命令行参数--version或者在启动时显示版本号，便于区分和调试

**Comment by remiliacn** [comment]
希望加入图片的闪照发送支持 #56

**Comment by xiaokaizhi** [comment]
cqhttp原先的api接口都是兼容GET和POST的。go-cqhttp的api接口能否也兼容一下

**Comment by masnn** [comment]
好像有吧
________________________________

**Comment by xiaokaizhi** [comment]
> 好像有吧
> […](#)
> ________________________________ From: xiaokaizhi <notifications@github.com> Sent: Friday, August 21, 2020 10:11:34 AM To: Mrs4s/go-cqhttp <go-cqhttp@noreply.github.com> Cc: undefined <masnn0@outlook.com>; Comment <comment@noreply.github.com> Subject: Re: [Mrs4s/go-cqhttp] CQHTTP功能实现请求 (#117) cqhttp原先的api接口都是兼容GET和POST的。go-cqhttp的api接口能否也兼容一下 ― You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMrs4s%2Fgo-cqhttp%2Fissues%2F117%23issuecomment-677998327&data=02%7C01%7C%7Cb442e59ea68c446ccdad08d8457787c2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637335726957561581&sdata=Fg%2Bwpa6LsBX9SKepa%2BQfQU4f7S%2FVr234aE9nz%2B1D9uM%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHE2KDNEFNGIEPPIPNB62HDSBXJVNANCNFSM4QA3TZVQ&data=02%7C01%7C%7Cb442e59ea68c446ccdad08d8457787c2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637335726957571575&sdata=qt2VPHLIETiSDe1IPtSbW14lDs6SXcyPVtrqv3FrQvc%3D&reserved=0>.

我试过了是支持GET。好像不支持POST。我原先是POST。比如获取群成员列表接口。

**Comment by masnn** [comment]
post传参记得加content-type标头
________________________________

**Comment by xiaokaizhi** [comment]
> post传参记得加content-type标头
> […](#)
> ________________________________ From: xiaokaizhi <notifications@github.com> Sent: Friday, August 21, 2020 10:26:44 AM To: Mrs4s/go-cqhttp <go-cqhttp@noreply.github.com> Cc: undefined <masnn0@outlook.com>; Comment <comment@noreply.github.com> Subject: Re: [Mrs4s/go-cqhttp] CQHTTP功能实现请求 (#117) 好像有吧 …
> ________________________________ From: xiaokaizhi notifications@github.com<mailto:notifications@github.com> Sent: Friday, August 21, 2020 10:11:34 AM To: Mrs4s/go-cqhttp go-cqhttp@noreply.github.com<mailto:go-cqhttp@noreply.github.com> Cc: undefined masnn0@outlook.com<mailto:masnn0@outlook.com>; Comment comment@noreply.github.com<mailto:comment@noreply.github.com> Subject: Re: [Mrs4s/go-cqhttp] CQHTTP功能实现请求 (#117<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMrs4s%2Fgo-cqhttp%2Fissues%2F117&data=02%7C01%7C%7Cf25131ca03c142e666b608d84579a623%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637335736058615341&sdata=O4BGamUuzNQi1VR0kQhZAsHRJPR4RRyRAf%2FMLB3QNrQ%3D&reserved=0>) cqhttp原先的api接口都是兼容GET和POST的。go-cqhttp的api接口能否也兼容一下 D You are receiving this because you commented. Reply to this email directly, view it on GitHubhttps://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMrs4s%2Fgo-cqhttp%2Fissues%2F117%23issuecomment-677998327&data=02%7C01%7C%7Cb442e59ea68c446ccdad08d8457787c2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637335726957561581&sdata=Fg%2Bwpa6LsBX9SKepa%2BQfQU4f7S%2FVr234aE9nz%2B1D9uM%3D&reserved=0<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMrs4s%2Fgo-cqhttp%2Fissues%2F117%23issuecomment-677998327&data=02%7C01%7C%7Cf25131ca03c142e666b608d84579a623%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637335736058615341&sdata=oqFHouBxG32cioQGpvD3%2BEAMvVvYJvFhMEsSsh9k0vY%3D&reserved=0>, or unsubscribehttps://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHE2KDNEFNGIEPPIPNB62HDSBXJVNANCNFSM4QA3TZVQ&data=02%7C01%7C%7Cb442e59ea68c446ccdad08d8457787c2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637335726957571575&sdata=qt2VPHLIETiSDe1IPtSbW14lDs6SXcyPVtrqv3FrQvc%3D&reserved=0<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHE2KDNEFNGIEPPIPNB62HDSBXJVNANCNFSM4QA3TZVQ&data=02%7C01%7C%7Cf25131ca03c142e666b608d84579a623%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637335736058625336&sdata=RVxQ5sddxzazxVnTioBytDeAHYbiDqU0LUhl0x7P8R0%3D&reserved=0>. 我试过了是支持GET。好像不支持POST。我原先是POST。比如获取群成员列表接口。 ― You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMrs4s%2Fgo-cqhttp%2Fissues%2F117%23issuecomment-678002331&data=02%7C01%7C%7Cf25131ca03c142e666b608d84579a623%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637335736058635332&sdata=vNWyFfzj8bsofWyWRULmtyFxh0AL%2FVsJNMHp5qQQIB0%3D&reserved=0>, or unsubscribe<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHE2KDKOEHHR6Q4B6IDRSQLSBXLOJANCNFSM4QA3TZVQ&data=02%7C01%7C%7Cf25131ca03c142e666b608d84579a623%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637335736058635332&sdata=H7D3vDhhZmXnmNtevOLWXUeu2%2BGlr2%2BDUKqjLUZsaiY%3D&reserved=0>.


好像不行。你加的什么标记

**Comment by Mrs4s** [comment]
> > 好像有吧
> > […](#)
> > ________________________________ From: xiaokaizhi [notifications@github.com](mailto:notifications@github.com) Sent: Friday, August 21, 2020 10:11:34 AM To: Mrs4s/go-cqhttp [go-cqhttp@noreply.github.com](mailto:go-cqhttp@noreply.github.com) Cc: undefined [masnn0@outlook.com](mailto:masnn0@outlook.com); Comment [comment@noreply.github.com](mailto:comment@noreply.github.com) Subject: Re: [Mrs4s/go-cqhttp] CQHTTP功能实现请求 (#117) cqhttp原先的api接口都是兼容GET和POST的。go-cqhttp的api接口能否也兼容一下 ― You are receiving this because you commented. Reply to this email directly, view it on GitHubhttps://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMrs4s%2Fgo-cqhttp%2Fissues%2F117%23issuecomment-677998327&data=02%7C01%7C%7Cb442e59ea68c446ccdad08d8457787c2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637335726957561581&sdata=Fg%2Bwpa6LsBX9SKepa%2BQfQU4f7S%2FVr234aE9nz%2B1D9uM%3D&reserved=0, or unsubscribehttps://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHE2KDNEFNGIEPPIPNB62HDSBXJVNANCNFSM4QA3TZVQ&data=02%7C01%7C%7Cb442e59ea68c446ccdad08d8457787c2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637335726957571575&sdata=qt2VPHLIETiSDe1IPtSbW14lDs6SXcyPVtrqv3FrQvc%3D&reserved=0.
> 
> 我试过了是支持GET。好像不支持POST。我原先是POST。比如获取群成员列表接口。可能POST的方式不同。post有两种from表单格式和json格式

都支持

**Comment by masnn** [comment]
0925啥时候出啊

**Comment by Mrs4s** [comment]
> 0925啥时候出啊

最近有点忙，更新频率会下降emmmm

**Comment by scjtqs** [comment]
尝试塞入 [CQ:json] 消息遇到问题。
![image](https://user-images.githubusercontent.com/24914774/91661113-77c8ba80-eb0c-11ea-8336-cd67f06ef799.png)
这是走到了 长消息去了么。。

**Comment by scjtqs** [comment]
最近看别人玩的一种xml的特大号图片消息，有点意思。不过得不过得通过0x6d6之类的上传文件，拿到fileid以及md5反塞回xml。。这种玩法的估计要么新增cq码，要么增加api了。

**Comment by Mrs4s** [comment]
> 最近看别人玩的一种xml的特大号图片消息，有点意思。不过得通过0x6d6之类的上传文件，拿到fileid以及md5反塞回xml。。这种玩法的估计要么新增cq码，要么增加api了。

暂时不是特别想做群文件的管理, 有可能被滥用成网盘.

**Comment by masnn** [comment]
网盘草

**Comment by AntaresQAQ** [comment]
希望支持`get_stranger_info`

**Comment by wdvxdr1123** [comment]
> 希望支持`get_stranger_info`
> 
> [相关CQHTTP文档](https://richardchien.gitee.io/coolq-http-api/docs/4.15/#/API?id=get_stranger_info-%E8%8E%B7%E5%8F%96%E9%99%8C%E7%94%9F%E4%BA%BA%E4%BF%A1%E6%81%AF)

最新版新增加的实验性api `_get_vip_info`可以获取陌生人的昵称等级，可以参考旧的cqhttp文档，返回的数据格式有一点点不同

**Comment by ChateauXiao** [comment]
希望能够增加通过api 去设置 入群验证方式具体包括如下几个方面:

1 选择加群方式 （如下图的6中方式）
2 支持部分加群方式的参数的读取和设置（如入群验证问题， 以及收费群当前的金额，以及重新设置该金额）
3 读取当前加群方式的配置（格式可为 json）
4 可设定部分管理员不收入群验证的白名单.

![image](https://user-images.githubusercontent.com/5915901/92425989-58d8c100-f1bb-11ea-9326-cc7c8e253680.png)

**Comment by wdvxdr1123** [comment]
> 希望能够增加通过api 去设置 入群验证方式具体包括如下几个方面:
> 
> 1 选择加群方式 （如下图的6中方式）
> 2 支持部分加群方式的参数的读取和设置（如入群验证问题， 以及收费群当前的金额，以及重新设置该金额）
> 3 读取当前加群方式的配置（格式可为 json）
> 4 可设定部分管理员不收入群验证的白名单.
> 
> ![image](https://user-images.githubusercontent.com/5915901/92425989-58d8c100-f1bb-11ea-9326-cc7c8e253680.png)

作者有提到过涉及金钱的功能不会支持

**Comment by ShuYuMo2003** [comment]
希望增加：
 - 群视频通话，QQ群电话相关功能QAQ（转成推流之类的QAQ）

是不是有点困难啊QAQ…

**Comment by masnn** [comment]
> > 希望早日支持除了amr格式以外音频文件的发送。以及加入发送图片以及语音时对相对路径的支持，这样可以稍微简化代码。
> 
> 支持其他格式语音发送需要集成ffmpeg, 目前计划在 ~`v0.9.22`~ `v0.9.25` 支持.

嘤

**Comment by Mrs4s** [comment]
> > > 希望早日支持除了amr格式以外音频文件的发送。以及加入发送图片以及语音时对相对路径的支持，这样可以稍微简化代码。
> 
> > 
> 
> > 支持其他格式语音发送需要集成ffmpeg, 目前计划在 ~`v0.9.22`~ `v0.9.25` 支持.
> 
> 
> 
> 嘤

咕

**Comment by 1523789353** [comment]
CQhttp相关文档,请
https://github.com/howmanybots/onebot/tree/master/legacy

**Comment by lz1998** [comment]
现在go-cqhttp和其他cqhttp实现消息格式不同，并且都有一部分扩展。

希望可以通过proto定义保证**QQ客户端**和**消息处理器**类型完全一致，使用proto定义格式加上json_tag，并生成定义的代码，序列化成json/protobuf，http可以根据请求头`application/json`和`application/x-protobuf`来进行判断，websocket用户可以自行配置是json还是protobuf。

定义了一部分Api和Event可以参考：https://github.com/ProtobufBot/onebot_idl

**Comment by lietxia** [comment]
感谢作者的辛勤劳动，如果有空的话，希望增加[CQ:location]地点功能的支持

**Comment by Mmxp** [comment]
+ http接口无法直接得知机器人是否为管理员
+ 当群员回复某信息时，无法直接或根据id获取被回复信息内容

**Comment by biuuu** [comment]
#123 已知 video 不支持发送。
是否可能在不支持本地上传的情况下，支持转发已上传的短视频。

**Comment by Arnie97** [comment]
> ※[CQ码文库](https://docs.cqp.im/manual/cqcode/)已经无法访问，仅凭记忆

目前在 https://docs.coolq.zone/cqcode 复活了
