### ISSUE TITLE
账号风控

### ISSUE THREAD

**Issue by 18844626311** [Mrs4s/go-cqhttp#1175]
可否加个忽略风控警告开关

**Comment by Ink-33** [comment]
不能，因为这样会有人问为什么发不出消息，控制台又没有反应

**Comment by 18844626311** [comment]
长消息风控发不出来

**Comment by sam01101** [comment]
#633

**Comment by takoyakiccc** [comment]
[https://github.com/takoyakiccc/cqhttp_reboot](url)

**Comment by takoyakiccc** [comment]
https://github.com/takoyakiccc/cqhttp_reboot
