### ISSUE TITLE
设置群头衔功能失效

### ISSUE THREAD

**Issue by nikissXI** [Mrs4s/go-cqhttp#1178]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix1

### 运行环境

Ubuntu

### 运行架构

AMD

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 在最新的 Release 版本中能否复现

- [ ] 能

### 重现步骤

beta6上是可以正常设置群头衔的，更新beta8-fix1后就不行了，手动发送http过去给api接口也不行，原来没头衔的还是没头衔，原来有头衔的会被摘下来，gocq后台没任何报错，正常返回200，有其他人也遇到这个问题，没啥图好给的，就不留图了，自己搓个http试试就知道了

### 期望的结果是什么？

头衔能用

### 实际的结果是什么？

现在不能用

**Comment by Ink-33** [comment]
已知bug，近期修复

**Comment by nikissXI** [comment]
> 已知bug，近期修复

加油加油加油！！！

**Comment by guaxiu8888** [comment]
请问现在可以了吗

**Comment by nikissXI** [comment]
> 

可以了
