### ISSUE TITLE
无法收到QQ好友信息

### ISSUE THREAD

**Issue by admintony** [Mrs4s/go-cqhttp#118]
**环境信息**
go-cqhttp版本: v0.9.19
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
无法收到qq好友信息，也无法给QQ好友发送信息。

**复现方法**
1、QQ好友给自己发信息，面板中无显示
2、给QQ好友发信息，提示如下：
```json
{"data":null,"retcode":100,"status":"failed"}
```

**附言**

不知是程序bug还是什么情况？ 配置文件均为默认。

**Comment by Mrs4s** [comment]
请提供更多信息，初步怀疑是风控

**Comment by dzcpy** [comment]
我也收不到个人消息，只能收到群消息。需要提供什么？

**Comment by dzcpy** [comment]
@admintony 您这个QQ好友数量是多少？看别人的反馈和自己尝试，好像超过1000好友的都无法发送接收私了消息？好友数量少的QQ我这都没有问题
