### ISSUE TITLE
频道里的at功能异常

### ISSUE THREAD

**Issue by nikissXI** [Mrs4s/go-cqhttp#1181]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix1

### 运行环境

Ubuntu

### 运行架构

AMD

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 在最新的 Release 版本中能否复现

- [ ] 能

### 重现步骤

![image](https://user-images.githubusercontent.com/31379266/142553385-05e931e7-60ca-4bf1-ae2b-5fb9fd1674db.png)
![image](https://user-images.githubusercontent.com/31379266/142553404-7b3ffda4-222a-4067-b3ee-39e26babf839.png)
![image](https://user-images.githubusercontent.com/31379266/142553428-b3bbd7a8-2dc4-453f-b192-e3cb036b9240.png)
如果at的目标昵称含有特殊字符，就会直接at 用户id，手动长按at是正常的，只有机器人发的at有这个问题

### 期望的结果是什么？

at能正常显示昵称

### 实际的结果是什么？

现在at特殊字符昵称显示的是id

**Comment by sam01101** [comment]
at 没适配频道的用户名导致的

**Comment by nikissXI** [comment]
> at 没适配频道的用户名导致的

噢噢，好的

**Comment by sam01101** [comment]
> > at 没适配频道的用户名导致的
> 
> 噢噢，好的

不是“噢噢，好的”就完事了，这个真的是gocq没加

**Comment by nikissXI** [comment]
> > > at 没适配频道的用户名导致的
> > 
> > 
> > 噢噢，好的
> 
> 不是“噢噢，好的”就完事了，这个真的是gocq没加

好的，谢谢（补上）

**Comment by nikissXI** [comment]
> > > at 没适配频道的用户名导致的
> > 
> > 
> > 噢噢，好的
> 
> 不是“噢噢，好的”就完事了，这个真的是gocq没加

以后会加的就行，预览版没有可以理解的

**Comment by Ink-33** [comment]
疑似是bug

**Comment by sam01101** [comment]
> 疑似是bug

疑似lookup失败

**Comment by Mrs4s** [comment]
这个是因为还没完全适配导致的，下个版本应该会修复
