### ISSUE TITLE
[feat] 请求修改频道id的类型为字符串

### ISSUE THREAD

**Issue by Dragon-Fish** [Mrs4s/go-cqhttp#1189]
**环境信息**

go-cqhttp版本: v1.0.0-beta8-fix1

**需要添加的功能内容**

希望以字符串表示频道id，而不是整型，频道id可能超过某些编程语言的数字最大安全值（例如js）

_Originally posted by @Dragon-Fish in https://github.com/Mrs4s/go-cqhttp/issues/1124#issuecomment-971719489_

**Comment by Mrs4s** [comment]
下个版本应该就会修改为字符串了

**Comment by Dragon-Fish** [comment]
close via v1.0.0-beta8-fix2
