### ISSUE TITLE
go-cqhttp版本: v0.9.10 go-cqhttp程序开放 api http 5700服务 运行一段时间 服务失效

### ISSUE THREAD

**Issue by yangguangwuwu** [Mrs4s/go-cqhttp#120]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.19
运行环境:linux_amd64 centos
连接方式: http

**bug内容**
程序在运行一段时间 后 发送群消息的  5700 端口（go-cqhttp）程序开放 api服务  失效  ，导致对接程序（业务端）请求go-cqhttp服务api 超时

**复现方法**
程序在运行一段时间, 业务端,请求go-cqhttp服务api 
重启go-cqhttp 一切恢复正常 程序在运行一段时间（2小时以上）

**Comment by yangguangwuwu** [comment]
补充：运行环境 linux核心 版本 3.10.0-1127.8.2.el7.x86_64

**Comment by shitianshiwa** [comment]
你的go-cqhttp版本应该没有填错？最新版是go-cqhttp-v0.9.19

**Comment by yangguangwuwu** [comment]
> 你的go-cqhttp版本应该没有填错？最新版是go-cqhttp-v0.9.19

我以为 issue模板 给的是最新版     我是从主干 master 编译的

**Comment by Morn-zh** [comment]
这是mirai的通病好像，写个定时重启的脚本就解决了

**Comment by StarHeartHunt** [comment]
有同样问题，运行两到三小时后只能收消息不能发消息，nonebot能收到下发事件并处理，但是直接手动调用api和nonebot调用api都无法发送消息。

**Comment by Mrs4s** [comment]
> 有遇到同样问题，运行两到三小时后只能收消息不能发消息，nonebot能收到下发事件并处理，但是直接手动调用api和nonebot调用api都无法发送消息，且此时返回的message_id固定不变。

这个是QQ号被风控了，新设备可能要挂机一周才能解除风控

**Comment by yangguangwuwu** [comment]
不是 是 进程 挂掉了 
我使用 Supervisor 做了进程守护 之后 
一点问题都没

**Comment by Mrs4s** [comment]
此问题应该也是TX的风控导致发送信息超时，新设备请挂机一周再试

**Comment by Mrs4s** [comment]
> 不是 是 进程 挂掉了
> 我使用 Supervisor 做了进程守护 之后
> 一点问题都没

进程挂了有没有报错

**Comment by yangguangwuwu** [comment]
没开debug 只是 5700 不通 ，然后我就  使用 Supervisor 做了进程守护 然后当天就好了

**Comment by yangguangwuwu** [comment]
设备号 也是当天生成的

**Comment by Mrs4s** [comment]
panic应该有报错信息，应该也是风控因素导致的，请等待_async api的完整支持
