### ISSUE TITLE
v0.9.19 go-cqhttp 启动后首次接收到某人的私聊信息仍会包含数条历史消息

### ISSUE THREAD

**Issue by Tsuk1ko** [Mrs4s/go-cqhttp#121]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.19
运行环境: windows_amd64
连接方式: any

**bug内容**
RT

**复现方法**
1. 启动 go-cqhttp，假设私聊发送五条消息`1`,`2`,`3`,`4`,`5`
2. 重新启动 go-cqhttp，私聊发送`6`，日志会一瞬显示收到了`1`,`2`,`3`,`4`,`5`,`6`

**Comment by takayama-lily** [comment]
恩，之前的版本好像也一直有这个现象
