### ISSUE TITLE
是否可以加入qq空间发送动态的功能

### ISSUE THREAD

**Issue by S0DX** [Mrs4s/go-cqhttp#1211]
**环境信息**

go-cqhttp版本: 

**需要添加的功能内容**

希望可以加入qq空间发送动态的功能
https://github.com/asjdf/GoQzone

**Comment by sam01101** [comment]
谢谢你的建议，但重复造轮子的行为实在不太适合

**Comment by Mrs4s** [comment]
暂时不会做QQ空间相关功能
