### ISSUE TITLE
[Bug]: 不知道为什么报错:打开数据库失败

### ISSUE THREAD

**Issue by Eternity-luo** [Mrs4s/go-cqhttp#1216]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix1

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 在最新的 Release 版本中能否复现

- [ ] 能

### 重现步骤

可能是重启

### 期望的结果是什么？

不会无故报错
![7ecfb2020952496](https://user-images.githubusercontent.com/72162184/144743568-c5e3bbc1-b16a-455c-aa9c-ad99a885b761.png)

### 实际的结果是什么？

只能重装😂

**Comment by sam01101** [comment]
呜呜呜呜呜求求你了 `issue` 的格式不是乱写的求你对着位置填信息吧呜呜呜

**Comment by sam01101** [comment]
https://stackoverflow.com/a/54515590

**Comment by OVOU4** [comment]
程序还在运行，你先使用ps -ef | grep go-cqhttp查看程序ID然后kill掉再重新启动就好了

**Comment by wdvxdr1123** [comment]
请检查系统最大进程数设置
