### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ID114514** [Mrs4s/go-cqhttp#1227]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix1

### 运行环境

Windows (64)

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 在最新的 Release 版本中能否复现

- [ ] 能

### 重现步骤

未知原因重连失败，再次启动就这样了

### 期望的结果是什么？

![22](https://user-images.githubusercontent.com/92457693/145183454-e2bff40b-cdb4-4477-8c6b-a9adbc91e23a.png)
如何解决这个问题

### 实际的结果是什么？

Protocol -> decrypt payload error: unknown flag
[ERROR]: Protocol -> decrypt payload error: unknown flag
[FATAL]: 登录时发生致命错误: Packet timed out

**Comment by xiaoshengbaiyi** [comment]
我的是如此 

![image](https://user-images.githubusercontent.com/44537257/145184388-36c61c0d-9d71-49fc-afca-1467b48401af.png)

**Comment by lgyzero** [comment]
遇到相同的问题
这两天登陆大概20次有19次是这样，剩下一次能成功~

**Comment by Mrs4s** [comment]
最新版已修复
