### ISSUE TITLE
[CQ:video]似乎还不能正常运行

### ISSUE THREAD

**Issue by shitianshiwa** [Mrs4s/go-cqhttp#123]
**环境信息**
go-cqhttp版本: v0.9.19
运行环境: docker-wine-coolq/Ubuntu 18.04.4 LTS
连接方式: HTTP POST多点上报
使用 https://github.com/howmanybots/cqhttp-node-sdk v1.2.0

**bug内容**
 [WARNING]: 转换CQ码到MiraiGo Element时出现错误: unsupported cq code: video 将原样发送

**复现方法**
[CQ:video,file=file:////home/user/coolq/httpnodejs/src/rsshub2qq/tmp/test.mp4]

**Comment by Mrs4s** [comment]
video仅支持接收, 暂没计划支持发送
