### ISSUE TITLE
[Bug]: 重启go-cqhttp的API（/set_restart）提示无此接口

### ISSUE THREAD

**Issue by xsclyf** [Mrs4s/go-cqhttp#1230]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix2

### 运行环境

CentOS

### 连接方式

HTTP

### 使用协议

0 | iPad

### 在最新的 Release 版本中能否复现

- [X] 能

### 重现步骤

直接访问重启API

### 期望的结果是什么？

重启go-cqhttp

### 实际的结果是什么？

{
    "data": null,
    "msg": "API_NOT_FOUND",
    "retcode": 404,
    "status": "failed",
    "wording": "API不存在"
}

**Comment by Mrs4s** [comment]
这个api由于问题比较多, 在很早的版本就移除了, 暂时还没有再加入的计划.

**Comment by Ink-33** [comment]
重启api由于技术原因已于1.0.0移除

**Comment by xsclyf** [comment]
> 这个api因为问题比较多，在很早的版本就移除了，暂时还没有再加入的计划。

好的～了解了～之前没注意到
