### ISSUE TITLE
translate api

### ISSUE THREAD

**Issue by Weltolk** [Mrs4s/go-cqhttp#1238]
**环境信息**

go-cqhttp版本: latest

**需要添加的功能内容**

已经有ocr api了,请问可以再做个translate api吗?

**Comment by Mrs4s** [comment]
可以做个, 主要是百度之类的接口也是免费的, 没必要从ＱＱ挖

**Comment by Weltolk** [comment]
> 可以做个, 主要是百度之类的接口也是免费的, 没必要从ＱＱ挖

正好最近用到了ocr的api,所以顺手提了个翻译的request,各家云服务的免费额度基本就够用了,所以做不做其实都可以

**Comment by Weltolk** [comment]
> 可以做个, 主要是百度之类的接口也是免费的, 没必要从ＱＱ挖

感谢回复,关了关了
