### ISSUE TITLE
get_group_info及get_group_list无法获取最新状态

### ISSUE THREAD

**Issue by qinpersevere** [Mrs4s/go-cqhttp#124]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.18
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
每天定时通过nonebot的get_group_info及get_group_list获取机器人入群情况，发现get_group_list可以获取到最新的入群状态，但member_count的值在之后并不会更新，如今天获取的人数和昨天相同

**复现方法**
总是出现，邀请机器人入群，当群成员发生变动，再请求get_group_info，结果中member_count依旧是群成员变动前的人数

**Comment by Mrs4s** [comment]
请问是新入的群不会自动获取群成员信息？

**Comment by qinpersevere** [comment]
> 请问是新入的群不会自动获取群成员信息？

不是，问题是可以通过get_group_list获取到当前机器人在哪些群，但获取的群人数字段(member_count)不准确，不会更新，所以对于已经入了一段时间的群无法获取当前实际群人数。

**Comment by qinpersevere** [comment]
@Mrs4s 更新一些验证结果：
1.确认get_group_info和get_group_list中member_count不会随着群成员变动而更新，no_cache设为true或false都试过了
2.get_group_member_list结果是准确的

**Comment by chenxuxin188** [comment]
> 请问是新入的群不会自动获取群成员信息？

今天我试着在挂着mirai go的情况下用电脑的QQ加了新群。加群之后，新群的消息全都收不到。应该和这个有关吧。

**Comment by Mrs4s** [comment]
`/get_group_list` 已支持 `no_cache` 需要时请自己刷新. 群信息自动同步的问题将在后续版本优化
