### ISSUE TITLE
加群消息上报的时候发送了多条。一个加群消息发送了7到8次

### ISSUE THREAD

**Issue by witpark** [Mrs4s/go-cqhttp#125]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.10
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
加群消息上报的时候发送了多条。一个加群消息发送了7到8次

**复现方法**

**Comment by takayama-lily** [comment]
用最新版试试吧。如果还有问题再说

**Comment by xiaokaizhi** [comment]
刚试了最新版本。一个加群消息发送了三十几天请求：（）

**Comment by xiaokaizhi** [comment]
我关掉后再次打开登录后直接闪退
