### ISSUE TITLE
[Bug]: 测试 TEST

### ISSUE THREAD

**Issue by sam01101** [Mrs4s/go-cqhttp#1254]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix1

### 运行环境

CentOS

### 运行架构

ARM [32] (别名：AArch32 / ARMv7）

### 连接方式

WebSocket (反向)

### 使用协议

4 | 企点

### 重现步骤

1. 进去腾讯QQ部
2. 获取内部文件
3. 复制一个QQ协议出来
4. 发涩图

### 期望的结果是什么？

面试通过

### 实际的结果是什么？

被骂到怀疑人生，质问到哭

### 简单的复现代码/链接（可选）

```golang
没有
```

### 日志记录（可选）

```golang
Your life is a failure
```

### 补充说明（可选）

草

**Comment by coder-tq** [comment]
草

**Comment by synodriver** [comment]
焯
