### ISSUE TITLE
为"获取群列表/get_group_list"api添加"no_cache 不使用缓存"参数

### ISSUE THREAD

**Issue by Weltolk** [Mrs4s/go-cqhttp#1259]
**环境信息**

go-cqhttp版本: 
latest v1.0.0-beta8-fix2

**需要添加的功能内容**

为"获取群列表/get_group_list"api添加"no_cache 不使用缓存"参数
"获取群列表/get_group_list"这个api获取的群信息不是最新的,目前我的解决方法是对"获取群列表/get_group_list"返回的json数组遍历调用"获取群信息/get_group_info"这个api并添加"no_cache 不使用缓存"参数

**Comment by Mrs4s** [comment]
你好 `get_group_list` 接口是支持 `no_cache` 的

**Comment by Weltolk** [comment]
> 你好 `get_group_list` 接口是支持 `no_cache` 的

好的,文档上没有,可以更新一下文档,谢谢
