### ISSUE TITLE
程序启动的时候卡在"开始加载群列表“很长时间不动。之后提示PACKET TIME OUT

### ISSUE THREAD

**Issue by witpark** [Mrs4s/go-cqhttp#126]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.10
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
程序启动的时候卡在"开始加载群列表“很长时间不动。之后提示PACKET TIME OUT

**Comment by Mrs4s** [comment]
请使用最新版, 老版本网络部分存在问题
