### ISSUE TITLE
[Bug]: Python使用flask无法与端口建立通信

### ISSUE THREAD

**Issue by BlingCc233** [Mrs4s/go-cqhttp#1269]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，我的 Issue 可能会被无条件自动关闭或/并锁定。
- [x] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix1

### 运行环境

CentOS

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

1. 正常配置好config.yml，连接方式走的是http，在早先运行时查看日志，不运行机器人只开启go-cqhttp时日志如下：`[2021-12-16 00:04:27] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:12334 时出现错误: Post "http://127.0.0.1:12334": context deadline exceeded 将重试. `。此时运行flask+Python可以正常运行通信，flask正常回报200状态码。
2. 最近重启go-cqhttp后，不运行机器人只开启go-cqhttp会出现如下日志：`[2021-12-17 00:00:13] [WARNING]: 上报 Event 数据到 127.0.0.1:12334 时创建请求失败: parse "127.0.0.1:12334": first path segment in URL cannot contain colon `。此时运行flask+Python则机器人不能运行，长期在12334端口无响应事件。

### 期望的结果是什么？

正常运行。
日志应为：`[2021-12-16 00:04:27] [WARNING]: 上报Event到 HTTP 服务器 127.0.0.1:22334 时出现错误: Post "http://127.0.0.1:12334": context deadline exceeded 将重试. `

### 实际的结果是什么？

无法正常通信，日志为：`[2021-12-17 00:00:13] [WARNING]: 上报 Event 数据到 127.0.0.1:12334 时创建请求失败: parse "127.0.0.1:12334": first path segment in URL cannot contain colon `

### 简单的复现代码/链接（可选）

```golang
from flask import Flask, request
app = Flask(__name__)

'''监听端口获取QQ信息'''
@app.route('/', methods=["POST"])

if __name__ == '__main__':
	app.run(debug=True, host='127.0.0.1', port=12334)
```

### 补充说明（可选）

不在服务器操作，而是换成自己的openwrt也会出现一样的结果

**Comment by sam01101** [comment]
标题缺少，请进行添加。

**Comment by wdvxdr1123** [comment]
see #1169
