### ISSUE TITLE
[Bug]: 私聊语音的音质明显比群聊语音的低

### ISSUE THREAD

**Issue by anydream** [Mrs4s/go-cqhttp#1276]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix1

### 运行环境

Ubuntu

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

准备一段语音wav文件, 通过CQ:record码分别发送到QQ群和任意好友私聊

### 期望的结果是什么？

QQ群和私聊的语音音质应该相同

### 实际的结果是什么？

QQ群和私聊的语音音质差别巨大. 私聊语音的音质可能在4k甚至更低的码率
怀疑可能是私聊语音触发了QQ服务器的压缩机制

**Comment by wdvxdr1123** [comment]
请尝试使用 https://github.com/Mrs4s/go-cqhttp/actions/runs/1597995764

**Comment by anydream** [comment]
> 请尝试使用 https://github.com/Mrs4s/go-cqhttp/actions/runs/1597995764

已解决!
