### ISSUE TITLE
反向ws event服务器不会重连

### ISSUE THREAD

**Issue by Akegarasu** [Mrs4s/go-cqhttp#128]
**环境信息**
go-cqhttp版本: v0.9.19
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
反向ws event服务器不会重连，只会自动重连反向ws的api服务器

**复现方法**
反向ws连接nonebot，重新启动nonebot
![反向ws](https://user-images.githubusercontent.com/36563862/90365077-dbc49b00-e097-11ea-9fbc-db167e2f6c05.png)

**Comment by Mrs4s** [comment]
已修复
