### ISSUE TITLE
[Bug]: 当CQ解析时若参数中含有“&amp;”符号(url常有)会返回空信息

### ISSUE THREAD

**Issue by Eric-Joker** [Mrs4s/go-cqhttp#1281]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix1

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

发送参数含有"\&amp;"的CQ码

### 期望的结果是什么？

使其能正常被解析

### 实际的结果是什么？

返回空结果，并报错：
URL query contains semicolon, which is no longer a supported separator; parts of the query may be stripped when parsed
若一条信息只有该CQ码则命令行返回：
`[WARNING]: 群消息发送失败: 消息为空.`

### 简单的复现代码/链接（可选）

```golang
[CQ:image,file=https://api.uomg.com/api/rand.avatar?sort=男&amp;format=images,c=3,cache=0]
```

**Comment by sam01101** [comment]
请进行符号转义。

**Comment by Yiwen-Chan** [comment]
建议使用数组消息链

**Comment by Eric-Joker** [comment]
> 

尝试过\转义，不好使

**Comment by Yiwen-Chan** [comment]
> > 
> 
> 尝试过\转义，不好使

[onebot-11](https://github.com/botuniverse/onebot-11/blob/master/message/string.md)

**Comment by Eric-Joker** [comment]
> > > 
> > 
> > 
> > 尝试过\转义，不好使
> 
> [onebot-11](https://github.com/botuniverse/onebot-11/blob/master/message/string.md)

谢

**Comment by Eric-Joker** [comment]
> > > 
> > 
> > 
> > 尝试过\转义，不好使
> 
> [onebot-11](https://github.com/botuniverse/onebot-11/blob/master/message/string.md)
改成[CQ:image,file=https://api.uomg.com/api/rand.avatar?sort=男&amp;format=images]后报错：
URL query contains semicolon, which is no longer a supported separator; parts of the query may be stripped when parsed

**Comment by Yiwen-Chan** [comment]
经测试无法复现，请提交详细的代码以及报错

**Comment by sam01101** [comment]
转义错误，建议参考 `nb2` 源码里的转义。

**Comment by Eric-Joker** [comment]
> 经测试无法复现，请提交详细的代码以及报错

`import requests
def 群聊发送():
    requests.get(url='http://127.0.0.1:3483/send_group_msg?group_id={0}&message={1}&auto_escape='.format(0, [CQ:image,file=https://api.uomg.com/api/rand.avatar?sort=男&amp;format=images]))
`
报错：
[2021-12-22 10:18:38] [INFO]: 收到群 TEST(0) 内 じ☆Ericぴ(0) 的消息: 男头像 (-1986470788)
[2021-12-22 10:18:38] [WARNING]: 群消息发送失败: 消息为空.
2021/12/22 10:18:38 http: URL query contains semicolon, which is no longer a supported separator; parts of the query may be stripped when parsed; see golang.org/issue/25192

**Comment by Eric-Joker** [comment]
> 转义错误，建议参考 `nb2` 源码里的转义。

给个链接？

**Comment by Yiwen-Chan** [comment]
> ` requests.get(url='http://127.0.0.1:3483/send_group_msg?group_id={0}&message={1}&auto_escape='.format(0,`

低级错误，没有进行 urlencode

**Comment by Eric-Joker** [comment]
> > ` requests.get(url='http://127.0.0.1:3483/send_group_msg?group_id={0}&message={1}&auto_escape='.format(0,`
> 
> 低级错误，没有进行 urlencode

转码后也还是提示URL query contains semicolon, which is no longer a supported separator; parts of the query may be stripped when parsed; see golang.org/issue/25192

**Comment by wdvxdr1123** [comment]
[RFC3986](https://datatracker.ietf.org/doc/rfc3986/)

**Comment by chrysoljq** [comment]
图片链接解码 &amp; => &
[CQ:image,file=https://api.uomg.com/api/rand.avatar?sort=男&format=images]

**Comment by Eric-Joker** [comment]
> 图片链接解码 `&amp; => &` [CQ:image,file=https://api.uomg.com/api/rand.avatar?sort=男&format=images]

这样虽然不会提示不支持“;”，但是也会返回空信息

**Comment by Yiwen-Chan** [comment]
> [RFC3986](https://datatracker.ietf.org/doc/rfc3986/)

请仔细阅读文档，这是你个人问题，没有其他的就 close 了吧

**Comment by chrysoljq** [comment]
> 

因为是302，链接跳转了

**Comment by Eric-Joker** [comment]
这应该不是我个人问题，无论我按任何方式进行转义，若CQ码的url包含;就会返回空信息，而url中的&需要转移成带有;的&amp;
[https://github.com/botuniverse/onebot-11/blob/master/message/string.md](url)中的例子url中包含;却是可以的，为什么啊巴

**Comment by Yiwen-Chan** [comment]
> > `requests.get(url='http://127.0.0.1:3483/send_group_msg?group_id={0}&message={1}&auto_escape='.format(0,`
> 
> 低级错误，没有进行 urlencode

这里已经告诉你为什么会报错了

**Comment by Yiwen-Chan** [comment]
自行设计后端的时候请先提升自己基础，多阅读文档以及类似项目的源码

**Comment by Eric-Joker** [comment]
> > > `requests.get(url='http://127.0.0.1:3483/send_group_msg?group_id={0}&message={1}&auto_escape='.format(0,`
> > 
> > 
> > 低级错误，没有进行 urlencode
> 
> 这里已经告诉你为什么会报错了

转码同样报错。跟汉字是否为urlencode没关系吧

**Comment by Yiwen-Chan** [comment]
那你将完整代码发出来

**Comment by sam01101** [comment]
> 这应该不是我个人问题，无论我按任何方式进行转义，若CQ码的url包含;就会返回空信息，而url中的&需要转移成带有;的& [https://github.com/botuniverse/onebot-11/blob/master/message/string.md](url)中的例子： `[CQ:share,title=震惊&#44;小伙睡觉前居然...,url=http://baidu.com/?a=1&amp;b=2]` 正常执行也报错 ![image](https://user-images.githubusercontent.com/60310368/147105714-451803df-1da9-481b-930e-53a6c7f5db3f.png)

https://github.com/golang/go/issues/25192
https://github.com/golang/go/issues/25192
https://github.com/golang/go/issues/25192
https://github.com/golang/go/issues/25192
https://github.com/golang/go/issues/25192

**Comment by Eric-Joker** [comment]
> > 这应该不是我个人问题，无论我按任何方式进行转义，若CQ码的url包含;就会返回空信息，而url中的&需要转移成带有;的& [https://github.com/botuniverse/onebot-11/blob/master/message/string.md](url)中的例子： `[CQ:share,title=震惊&#44;小伙睡觉前居然...,url=http://baidu.com/?a=1&amp;b=2]` 正常执行也报错 ![image](https://user-images.githubusercontent.com/60310368/147105714-451803df-1da9-481b-930e-53a6c7f5db3f.png)
> 
> [golang/go#25192](https://github.com/golang/go/issues/25192) [golang/go#25192](https://github.com/golang/go/issues/25192) [golang/go#25192](https://github.com/golang/go/issues/25192) [golang/go#25192](https://github.com/golang/go/issues/25192) [golang/go#25192](https://github.com/golang/go/issues/25192)
我瞎了？我没在这里看到解决办法

**Comment by Eric-Joker** [comment]
> 那你将完整代码发出来

http://127.0.0.1:3483/send_group_msg?group_id=838138237&message=[CQ:image,file=https://api.uomg.com/api/rand.avatar?sort=%E5%A5%B3&amp;]

**Comment by Yiwen-Chan** [comment]
> > 那你将完整代码发出来
> 
> [http://127.0.0.1:3483/send_group_msg?group_id=838138237&message=[CQ:image,file=https://api.uomg.com/api/rand.avatar?sort=%E5%A5%B3&amp;]](http://127.0.0.1:3483/send_group_msg?group_id=838138237&message=%5BCQ:image,file=https://api.uomg.com/api/rand.avatar?sort=%E5%A5%B3&amp;%5D) 得发三次了XD

分号不转义吗

**Comment by Yiwen-Chan** [comment]
> > > 这应该不是我个人问题，无论我按任何方式进行转义，若CQ码的url包含;就会返回空信息，而url中的&需要转移成带有;的& [https://github.com/botuniverse/onebot-11/blob/master/message/string.md](url)中的例子： `[CQ:share,title=震惊&#44;小伙睡觉前居然...,url=http://baidu.com/?a=1&amp;b=2]` 正常执行也报错 ![image](https://user-images.githubusercontent.com/60310368/147105714-451803df-1da9-481b-930e-53a6c7f5db3f.png)
> > 
> > 
> > [golang/go#25192](https://github.com/golang/go/issues/25192) [golang/go#25192](https://github.com/golang/go/issues/25192) [golang/go#25192](https://github.com/golang/go/issues/25192) [golang/go#25192](https://github.com/golang/go/issues/25192) [golang/go#25192](https://github.com/golang/go/issues/25192)
> 
> 我瞎了？我没在这里看到有效的解决办法 把;转移成urlencode那CQcode就不会将&amp%26识别成&符号

里面确实有提及

**Comment by Eric-Joker** [comment]
> 把;转移成urlencode那CQcode就不会将&amp%26识别成&符号

把;转移成urlencode那CQcode就不会将&amp%26识别成&符号

**Comment by Eric-Joker** [comment]
> 里面确实有提及

把;转移成urlencode那CQcode就不会将&amp%26识别成&符号

**Comment by Yiwen-Chan** [comment]
> 

%26是&的urlencode

**Comment by Eric-Joker** [comment]
> > 
> 
> %26是&的urlencode

..我是憨批，我去试试

**Comment by Yiwen-Chan** [comment]
> > > 
> > 
> > 
> > %26是&的urlencode
> 
> %3B不行，不会提示不支持;，但是提示群消息发送失败，消息为空

你分号都urlencode了，为什么不想想&也要urlencode呢

**Comment by Yiwen-Chan** [comment]
昨天就告诉你怎么解决了，问问题多找找是不是自己的问题，close了吧

**Comment by Eric-Joker** [comment]
> > > > 
> > > 
> > > 
> > > %26是&的urlencode
> > 
> > 
> > %3B不行，不会提示不支持;，但是提示群消息发送失败，消息为空
> 
> 你分号都urlencode了，为什么不想想&也要urlencode呢

。。。成功了，，谢
