### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by YIXUANXUAN19** [Mrs4s/go-cqhttp#1291]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix2

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

发送图片  [CQ:image,file=https://i.pixiv.cat/img-original/img/2020/12/13/12/24/07/86271080_p0.jpg]

### 期望的结果是什么？

请求成功    浏览器不使用代理可以直接访问

### 实际的结果是什么？

Get "https://i.pixiv.cat/img-original/img/2020/12/13/12/24/07/86271080_p0.jpg": dial tcp 31.13.97.248:443: connect: connection timed out 将原样发送.

### 日志记录（可选）

```golang
[2021-12-24 19:25:43] [WARNING]: 转换CQ码 [CQ:image,file=https://i.pixiv.cat/img-original/img/2016/02/19/20/37/49/55374168_p0.png] 时出现错误: Get "https://i.pixiv.cat/img-original/img/2016/02/19/20/37/49/55374168_p0.png": dial tcp 31.13.97.248:443: connect: connection timed out 将原样发送.
```

**Comment by wdvxdr1123** [comment]
`pixiv.cat` 受到数据跨境安全网关影响，这不是bug

**Comment by qianjunakasumi** [comment]
![image](https://user-images.githubusercontent.com/53565118/147358971-126c3698-e4c5-4f93-b955-336e95c3569f.png)
