### ISSUE TITLE
如何判断后端是否使用go-cqhttp

### ISSUE THREAD

**Issue by mnixry** [Mrs4s/go-cqhttp#13]
因为go-cqhttp具有自己的一些增强API，下游开发者可能需要通过判断后端类型来自动选择是否启用一些功能
请问目前有办法实现嘛

**Comment by Shigma** [comment]
@mnixry 

get_version 这个接口会额外返回 go_cqhttp: true

**Comment by mnixry** [comment]
> @mnixry
> 
> get_version 这个接口会额外返回 go_cqhttp: true

感谢解答
