### ISSUE TITLE
机器人在某个人下面发送消息发不出，其他人下文发送正常，没报错[Bug]: 

### ISSUE THREAD

**Issue by wencheng90** [Mrs4s/go-cqhttp#1307]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix2

### 运行环境

Windows (64)

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

  如题：机器人在某个qq下面发送消息发不出，其他QQ下文发送正常，没报错

### 期望的结果是什么？

正常发出消息内容

### 实际的结果是什么？

在某个qq消息下面无法发出内容

**Comment by sam01101** [comment]
啥也没有，很难排查。。。

**Comment by xia0ji233** [comment]
没错我也遇到了这个问题，cq和nonebot两边的日志都没有报错，但是就是发不出来，很神奇的是，换个号就可以，这个只针对了特定的人特定的消息发不出，而且是一直存在。。。

**Comment by Asudy** [comment]
是不是这个人的ID中含有特殊字符什么的啊

**Comment by Alkaidcc** [comment]
同样遇到了这个问题，cq和nonebot日志均正常 无报错，但是私聊长消息无法发出，群消息一切正常。

**Comment by wdvxdr1123** [comment]
可能与protobuf库bug有关，请更新最新版本.
