### ISSUE TITLE
[Bug]: 向Q群转发频道接收到的含图片的消息时会返回100风控

### ISSUE THREAD

**Issue by DDEle** [Mrs4s/go-cqhttp#1308]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix2

### 运行环境

Ubuntu

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

向某个q群发送 `【频道】DDEle (144115218677475422)：\n[CQ:image,file=bd521bcbff1dadabd4b3ade0d1569b27.image,url=https://gchat.qpic.cn/qmeetpic/10163911639023428/1740492-2588018268-BD521BCBFF1DADABD4B3ADE0D1569B27/0?term=255]带文字的图片`

### 期望的结果是什么？

发送一条带图消息

### 实际的结果是什么？

返回代码 100 显示可能被风控

### 补充说明（可选）

我搞了一个discord - Q群 - 一个QQ频道子频道的互联。现在DC能往群和频道里发图，频道能往dc发图，群能往dc和频道发图，就是频道往群发图的时候会报错100。

应该不是风控的问题，因为从dc往群转发的时候是没问题的。

我最近没有动过代码，这个现象是最近一两天（或者是几个小时前？）开始出现的。

另外，非动图 and/or 消息仅一张图片而非文字图片混合的情况下也会产生上述现象，而只要是纯文字消息就能成功转发

**Comment by Ink-33** [comment]
指不定真的是风控

**Comment by DDEle** [comment]
> 指不定真的是风控

刚尝试重新生成了device.json也没啥区别。很神秘，discord转发以及别的使用场景下（同一个群）发自己生成的图片（puppeteer）都没有问题

**Comment by SlieFamily** [comment]
我也有类似的问题。怀疑是QQ官方那边做的检测啥的，以后只能发自己生成的图片，不能复制已有的 CQ 图片了

**Comment by wdvxdr1123** [comment]
已知问题， dev 已修复

**Comment by furleywolf** [comment]
> 已知问题， dev 已修复

噫？好像还没有新的build欸，这个问题挺麻烦的，对我这边影响有点大

**Comment by KagamiMiro** [comment]
我这边纯文字超过3条也会被风控 请问你们那边也是一样么

**Comment by xia0ti** [comment]
遇到同样的问题了，大佬可以解决吗

**Comment by MistEO** [comment]
> 已知问题， dev 已修复

看了下 CI 里最新的还是上个月底的。这个问题对我们影响比较大，打算手动编个先用着，请问下是哪个分支修的？_(:з」∠)_

**Comment by Mrs4s** [comment]
> > 已知问题， dev 已修复
> 
> 看了下 CI 里最新的还是上个月底的。这个问题对我们影响比较大，打算手动编个先用着，请问下是哪个分支修的？_(:з」∠)_

试试dev分支

**Comment by furleywolf** [comment]
> > > 已知问题， dev 已修复
> > 
> > 
> > 看了下 CI 里最新的还是上个月底的。这个问题对我们影响比较大，打算手动编个先用着，请问下是哪个分支修的？_(:з」∠)_
> 
> 试试dev分支

用dev自行构建了一个版本，还是存在这个问题。(:з」∠)
