### ISSUE TITLE
[Bug]: 消息图片上传失败: file size over max

### ISSUE THREAD

**Issue by BohanRen** [Mrs4s/go-cqhttp#1313]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix2

### 运行环境

Windows (64)

### 运行架构

x86

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

相同的问题在：[https://github.com/Mrs4s/go-cqhttp/issues/712](#712)
发现已经解决，但是发送图片`http://gchat.qpic.cn/gchatpic_new/2144671869/1038707947-2847980560-E739CAD1F84741E3DE326BD718FE3B9A/0`时依然出现错误，控制台：
```
[WARNING]: 警告: 私聊 xxx 消息图片上传失败: file size over max
[2022-01-02 20:03:09] [INFO]: 发送好友 xxx(xxx)  的消息: [CQ:face,i ... (-1052346311)
[2022-01-02 20:03:23] [INFO]: 接受 WebSocket 连接: 127.0.0.1:2245 (/)
[2022-01-02 20:03:23] [WARNING]: 警告: 私聊 xxx消息图片上传失败: file size over max
[2022-01-02 20:03:23] [INFO]: 发送好友 xxx(xxx)  的消息: [CQ:face,i ... (-1237235537)
```
CQ代码如下:

```
[CQ:face,id=0][CQ:image,cache=0,url=https://gchat.qpic.cn/gchatpic_new/2144671869/1038707947-2847980560-E739CAD1F84741E3DE326BD718FE3B9A/0]
```
之前的问题说是url改成file，然后改成file后依然是相同的问题
更换其他照片的链接后,有的照片成功上传，有的问题依然存在

### 期望的结果是什么？

期望结果是发送成功照片
另外想问问到底应该用url还是用file来填写外部图片链接？

### 实际的结果是什么？

```
[WARNING]: 警告: 私聊 xxx 消息图片上传失败: file size over max
[2022-01-02 20:03:09] [INFO]: 发送好友 xxx(xxx)  的消息: [CQ:face,i ... (-1052346311)
[2022-01-02 20:03:23] [INFO]: 接受 WebSocket 连接: 127.0.0.1:2245 (/)
[2022-01-02 20:03:23] [WARNING]: 警告: 私聊 xxx消息图片上传失败: file size over max
[2022-01-02 20:03:23] [INFO]: 发送好友 xxx(xxx)  的消息: [CQ:face,i ... (-1237235537)
```

### 简单的复现代码/链接（可选）

```golang
function send(action, params) {
    console.log(JSON.stringify({ action, params }));
    ws.send(JSON.stringify({ action, params }))
}
ws.on('open',function(){
    console.log("OK!");
    send('send_private_msg',{
        user_id: "qq",
        message: "[CQ:face,id=0][CQ:image,cache=0,file=https://gchat.qpic.cn/gchatpic_new/2144671869/1038707947-2847980560-E739CAD1F84741E3DE326BD718FE3B9A/0]"
    });
})
```

**Comment by Mrs4s** [comment]
![image](https://user-images.githubusercontent.com/12137562/147876669-5cd74462-617f-496b-93b2-b832e05531b3.png)
我们这边没办法复现emmm

**Comment by BohanRen** [comment]
emmm，好吧，谢谢了，这个问题概率性出现，估计也和我本地缓存有关系。

另外想问一问，听说有自己的oss可以加速图片发送速度，是这样么，原理是什么？

**Comment by Mrs4s** [comment]
图片发送速度一般只和bot服务器网速&链接的下载速度有关. 因为发送图片是要将链接上的图片下载到本机, 然后上传到TX服务器

**Comment by BohanRen** [comment]
谢谢您的解答

**Comment by NanakoOfficial** [comment]
我也遇到了这个问题，有时候图发不出来

[2022-09-18 17:10:57] [WARNING]: 警告: 群 ******** 图片上传失败: over file size max

请问怎么解决qwq

**Comment by cqzaiercn** [comment]
之前有发发送成功  现在不能发了  @Mrs4s
