### ISSUE TITLE
[Bug]: 调用合并转发接口发送消息失败

### ISSUE THREAD

**Issue by Viking602** [Mrs4s/go-cqhttp#1316]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix2

### 运行环境

MacOS

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

WebSocket (反向)

### 使用协议

1 | Android Phone

### 重现步骤

使用反向WS发送合并转发消息失败
调用参数：
`{"action":"send_group_forward_msg","params":{"group_id":7253*****"message":[{"type":"node","data":{"name":"测试消息","uin":"10086","content":"123"}}]}}`

### 期望的结果是什么？

![image](https://user-images.githubusercontent.com/27732503/148187010-aed80c97-92ae-421d-b723-e0c1ad038a8e.png)

这个是通过HTTP调用接口发送的

### 实际的结果是什么？

返回结果
不知道是哪里问题？DEBUG日志也仅仅记录了调用记录 并没有详细的错误返回
`{"data":null,"msg":"","retcode":100,"status":"failed","wording":""}`

### 日志记录（可选）

```golang
[2022-01-05 16:38:38] [DEBUG]: WS接收到API调用: send_group_forward_msg 参数: {"group_id":72531****,"message":[{"type":"node","data":{"name":"测试消息","uin":"10086","content":"123"}}]}
```

**Comment by wdvxdr1123** [comment]
参数名为 `messages` 而非 `message`
[文档](https://docs.go-cqhttp.org/api/#%E5%8F%91%E9%80%81%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91-%E7%BE%A4)
