### ISSUE TITLE
[Bug]: 处置WS命令时发生无法恢复的异常

### ISSUE THREAD

**Issue by daizihan233** [Mrs4s/go-cqhttp#1328]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix2

### 运行环境

Windows (64)

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

使用正向WebSocket与机器人链接，调用API时报错

### 期望的结果是什么？

正常发送一条消息给用户

### 实际的结果是什么？

go-cqhttp报错：
![image](https://user-images.githubusercontent.com/72146468/149436709-3f02c9f9-4085-495f-b564-36cba16c4d53.png)
go-cqhttp返回：
![image](https://user-images.githubusercontent.com/72146468/149436805-e871486d-47fc-4c52-b55d-d7de760d9d9f.png)

### 简单的复现代码/链接（可选）

```golang
import json
import time

from websocket import create_connection

# 这个函数是抄百度的，稍微改了一下，返回API不存在
def websockets(url, headers_dict=None, params_dict=None, result: list = None):
    """
    websocket请求
    :param url:
    :param headers_dict:
    :param params_dict:
    :param result: 请求结果列表
    """
    print('websocket请求url：{}'.format(url))
    # step1 创建连接
    while True:
        try:
            if headers_dict is not None:
                ws = create_connection(url, headers=headers_dict)
            else:
                ws = create_connection(url)
            break
        except Exception as e:
            print('连接错误:{}'.format(e))
            time.sleep(5)
    print('请求是否成功：{}'.format('成功' if ws.status == 101 else '失败'))

    # step2：请求/获取 响应
    for _ in range(2):  # 发送了两次请求，因为第一次返回的信息不像是gocq的
        """
        第一次返回的信息：
        {'_post_method': 2, 'meta_event_type': 'lifecycle', 'post_type': 'meta_event', 'self_id': 748029973, 'sub_type': 'connect', 'time': 1642123760}
        """
        if params_dict is not None:
            params = params_dict
            ws.send(str(params))
        response = ws.recv()
        if result is not None:
            result.append(response)

    try:
        response = json.loads(response)
        print(response)
    except Exception:
        print('无法转为Dict')
    print('Type:', type(response))
    ws.close()
    return response

websockets(url='ws://127.0.0.1:6700/send_private_msg',
           params_dict={
               'user_id': 183713750,  # 给这个人发条消息
               'message': '2333'      #消息内容
           }
           )
```

### 补充说明（可选）

程序发送了两次请求，第一次请求gocq的日志显示：
![image](https://user-images.githubusercontent.com/72146468/149437169-4f6baf50-d3fd-40fd-b227-df036eee458f.png)
不知道为啥参数后面没有任何东西

**Comment by xiangxiangxiong9** [comment]
试试把最后面的
```
websockets(url='ws://127.0.0.1:6700/send_private_msg',
           params_dict={
               'user_id': 183713750,  # 给这个人发条消息
               'message': '2333'      #消息内容
           }
           )
```
改成
```
websockets(url='ws://127.0.0.1:6700/',
           params_dict={'action': 'send_private_msg', 'params':{
               'user_id': 183713750,  # 给这个人发条消息
               'message': '2333'      #消息内容
           }}
           )
```
?

**Comment by daizihan233** [comment]
还是不行
![image](https://user-images.githubusercontent.com/72146468/149646501-75c35512-40c4-48cf-8435-f7da96380e96.png)

**Comment by xiangxiangxiong9** [comment]
尝试下这个

**Comment by daizihan233** [comment]
（补充）有时候gocq也会输出这个
![image](https://user-images.githubusercontent.com/72146468/149646630-376077bc-e2c7-4e55-94c2-4bbc279eca1f.png)

**Comment by daizihan233** [comment]
> （补充）有时候gocq也会输出这个 ![image](https://user-images.githubusercontent.com/72146468/149646630-376077bc-e2c7-4e55-94c2-4bbc279eca1f.png)

也就是“实际的结果是什么？”那一处的报错，有时候会有，有时候没有，但都提示找不到API

**Comment by xiangxiangxiong9** [comment]
```python3
import aiohttp
import asyncio
async def func():
    async with aiohttp.ClientSession() as session:
        async with session.ws_connect('ws://127.0.0.1:6700/api') as ws:
            await ws.send_json({'action': 'send_private_msg', 'params':{
                   'user_id': 183713750,  # 给这个人发条消息
                   'message': '2333'      #消息内容
               }})
            data = await ws.receive_json()
    return data
asyncio.run(func())
```
这个呢？？

**Comment by daizihan233** [comment]
可以了，谢谢

**Comment by shadlc** [comment]
这里再提供一种不需要换aiohttp模块继续使用websocket模块的改法，之前的错误原因是因为单引号不是规范的json格式，cqhttp不识别，所以把
`
           params_dict={'action': 'send_private_msg', 'params':{
               'user_id': 183713750,  # 给这个人发条消息
               'message': '2333'      #消息内容
           }}
`
改为
`
           params_dict={"action": "send_private_msg", "params":{
               "user_id": 183713750,  # 给这个人发条消息
               "message": "2333"      #消息内容
           }}
`
这也是一种改法，websockets模块同理

**Comment by xiangxiangxiong9** [comment]
> 这里再提供一种不需要换aiohttp模块继续使用websocket模块的改法，之前的错误原因是因为单引号不是规范的json格式，cqhttp不识别，所以把
> 
> ```
>        params_dict={'action': 'send_private_msg', 'params':{
>            'user_id': 183713750,  # 给这个人发条消息
>            'message': '2333'      #消息内容
>        }}
> ```
> 
> 改为
> 
> ```
>        params_dict={"action": "send_private_msg", "params":{
>            "user_id": 183713750,  # 给这个人发条消息
>            "message": "2333"      #消息内容
>        }}
> ```
> 
> 这也是一种改法，websockets模块同理

应该是 把 ws.send(str(params)) 改为 ws.send(json.dumps(params, ensure_ascii=false)) 就行
