### ISSUE TITLE
[Bug]: 部分图片通过image文件无法向QQ群正常发送

### ISSUE THREAD

**Issue by KagamiMiro** [Mrs4s/go-cqhttp#1330]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix2

### 运行环境

Windows (64)

### 运行架构

x86

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

部分图片通过image文件无法向QQ群正常发送

通过image文件向QQ群发送图片
[CQ:image,file=4f6f9fd1c9643f1b5878aa2140aba710.image]
被风控

通过image文件内的URL向QQ群发送图片
[CQ:image,file=https://gchat.qpic.cn/gchatpic_new/1871033678/869666963-2909258401-4F6F9FD1C9643F1B5878AA2140ABA710/0?term=3]
可以正常发送

但两者均可以正常发送私聊消息

image文件位于.\data\images 已上传OneDrive：
https://1drv.ms/u/s!AoFpr0aB2FA6vVbrk8ipWlCaVZOT?e=1fDVNH

### 期望的结果是什么？

通过image文件向QQ群发送图片

### 实际的结果是什么？

风控警告

### 简单的复现代码/链接（可选）

```golang
nonebot
session.send('[CQ:image,file=4f6f9fd1c9643f1b5878aa2140aba710.image]')
```

**Comment by chshzhe** [comment]
遇到了同样的问题

**Comment by iwxyi** [comment]
我也是，私聊能发，群消息就发不出去

**Comment by 250king** [comment]
有一些图片可以发，但有一些提示风控（

**Comment by wdvxdr1123** [comment]
请使用新版
