### ISSUE TITLE
[Bug]: 连续使用约48h后报错退出 panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by arrio464** [Mrs4s/go-cqhttp#1336]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已经使用 dev 分支版本测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix2 Latest on 8 Dec 2021

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

将go-cqhttp作为EFB客户端，挂机一段时间后程序报错退出。复现时间在1-3天内不等。冷重启客户端后正常。
尚未找到有效稳定复现方法，如需要可提供更多信息。

最近一次日志如下

> [2022-01-22 20:33:04] [INFO]: 收到群 ***(***) 内 ***(***) 的消息: ***  (***)
[2022-01-22 20:33:04] [DEBUG]: 上报Event http://127.0.0.1:5701 到 HTTP 服务器 {"anonymous":null,"font":0,"group_id":***,"message":[{"data":{"text":"***"},"type":"text"}],"message_id":***,"message_seq":1200963,"message_type":"group","post_type":"message","raw_message":"***","self_id":***,"sender":{"age":0,"area":"","card":"***","level":"","nickname":"***","role":"member","sex":"unknown","title":"","user_id":***},"sub_type":"normal","time":1642901581,"user_id":***}
 时被过滤.
[2022-01-22 20:33:06] [DEBUG]: 上报Event http://127.0.0.1:5701 到 HTTP 服务器 {"interval":20000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":***!,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":28470,"packet_sent":9098,"packet_lost":0,"message_received":19257,"message_sent":198,"disconnect_times":1,"lost_times":0,"last_message_time":1642901584}},"time":1642901586}
 时被过滤.
[2022-01-22 20:33:08] [DEBUG]: Protocol -> rev pkt: Heartbeat.Alive seq: 20086
[2022-01-22 20:33:26] [DEBUG]: 上报Event http://127.0.0.1:5701 到 HTTP 服务器 {"interval":20000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":***,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":28471,"packet_sent":9099,"packet_lost":0,"message_received":19257,"message_sent":198,"disconnect_times":1,"lost_times":0,"last_message_time":1642901584}},"time":1642901606}
 时被过滤.
panic: runtime error: makeslice: len out of range
goroutine 51 [running]:
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadBytes(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/binary/reader.go:40
github.com/Mrs4s/MiraiGo/internal/packets.parseSsoFrame({0xc0002a2385, 0xc00000e0c0, 0xc000264f70}, 0x1)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/internal/packets/global.go:145 +0x1a7
github.com/Mrs4s/MiraiGo/internal/packets.ParseIncomingPacket({0xc0003fcc00, 0xc000426720, 0xc79a00}, {0xc000264f70, 0x10, 0x10})
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/internal/packets/global.go:136 +0x38f
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0xc000268480)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/network.go:296 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).connect.func1
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/network.go:121 +0x307
root@***:/usr/cqhttp#

前两次日志如下

>  panic: runtime error: makeslice: len out of range
goroutine 51 [running]:
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadBytes(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/binary/reader.go:40
github.com/Mrs4s/MiraiGo/internal/packets.parseSsoFrame({0xc0000a5a25, 0xc00000e0c0, 0xc0002a5530}, 0x1)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/internal/packets/global.go:145 +0x1a7
github.com/Mrs4s/MiraiGo/internal/packets.ParseIncomingPacket({0xc0001f4480, 0xc00083d350, 0x10}, {0xc0002a5530, 0x10, 0x10})
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/internal/packets/global.go:136 +0x38f
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0xc00025e000)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/network.go:296 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).connect.func1
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/network.go:121 +0x307

> panic: runtime error: makeslice: len out of range
goroutine 78 [running]:                                                                                   
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadBytes(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/binary/reader.go:40
github.com/Mrs4s/MiraiGo/internal/packets.parseSsoFrame({0xc0002d7687, 0xc00000e6f0, 0xc000311830}, 0x1)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/internal/packets/global.go:145 +0x1a7
github.com/Mrs4s/MiraiGo/internal/packets.ParseIncomingPacket({0xc000194400, 0xc00041dfb0, 0x0}, {0xc000311830, 0x10, 0x10})
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/internal/packets/global.go:136 +0x38f
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0xc00023a000)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/network.go:296 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).connect.func1
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/network.go:121 +0x307      

在EFB主端中，显示如下

> 🐧💻 CoolQ Alert, System:
We're unable to communicate with CoolQ Client.
Please check the connection and credentials provided.
Unable to connect to CoolQ Client!Error Message:
HTTPConnectionPool(host='127.0.0.1', port=5700): Max retries exceeded with url: /get_status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4fc75a340>: Failed to establish a new connection: [Errno 111] Connection refused'))

### 期望的结果是什么？

稳定运行

### 实际的结果是什么？

运行1-3天后报错退出

**Comment by zhanbao2000** [comment]
同样的问题
v1.0.0-beta8-fix2
Linux amd64
反向ws
协议：iPad

**Comment by molehzy** [comment]
windows server 2012
v1.0.0-rc1 amd64
正向ws
AndroidWatch

```
panic: runtime error: makeslice: len out of range

goroutine 59 [running]:
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadBytes(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/reader.go:40
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).readSSOFrame(0x507d5f24586a5359, 0xc00043e960, {0xc000028b65, 0x1a0, 0x1a0})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/internal/network/response.go:62 +0x185
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).ReadResponse(0xc000188560, {0xc0001388c0, 0x1b4, 0x1b4})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/internal/network/response.go:51 +0x2a9
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0xc000193080)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:295 +0x1b2
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).connect.func1
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:120 +0x307
```

**Comment by txtxj** [comment]
windows server 2012
v1.0.0-rc1 amd64
反向ws
协议：iPad

在 bot 被封禁、解禁后遇到同样的问题，删除文件夹 `data/` 和 `logs/` 后问题解决

**Comment by KisAaki** [comment]
> 

windos
v1.0.0-rc1 amd64
反向ws
协议iPad
尝试了几次后还是不行。（

**Comment by chaosChildrens** [comment]
> windows server 2012 v1.0.0-rc1 amd64 反向ws 协议：iPad
> 
> 在 bot 被封禁、解禁后遇到同样的问题，删除文件夹 `data/` 和 `logs/` 后问题解决

试了下，有用，可以登录

**Comment by KisAaki** [comment]
> > windows server 2012 v1.0.0-rc1 amd64 反向ws 协议：iPad
> > 在 bot 被封禁、解禁后遇到同样的问题，删除文件夹 `data/` 和 `logs/` 后问题解决
> 
> 试了下，有用，可以登录

我这边试过删除data/ 和 logs，但是还是会报如题的错；也去官网上试过下一个新的go-cqhttp，还是不行；最后解决方法是换了一个新的QQ号（
