### ISSUE TITLE
[Bug]: 无法撤回消息

### ISSUE THREAD

**Issue by guimc233** [Mrs4s/go-cqhttp#1339]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已经使用 dev 分支版本测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix2

### 运行环境

UNIX (Android)  Termux

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

HTTP

### 使用协议

2 | Android Watch

### 重现步骤

使用http让机器人撤回消息时 出现无法撤回的情况
在配置文件内有打开数据库

### 期望的结果是什么？

能撤回消息

### 实际的结果是什么？

并没有撤回

### 简单的复现代码/链接（可选）

```golang
# part1 接受到正向websocket的消息时间 处理消息:
ad = json.loads(message)
# 省略几行无关紧要的
message_id = ad["message_id"]

# part2 撤回消息:
recall(message_id)

# part3 recall实现函数:
def recall(msgid):
    data1 = {
        "message_id": int(msgid)
    }
    print(requests.get("http://localhost:5700/delete_msg", data=data1).text)
```

### 日志记录（可选）

```golang
[2022-01-24 18:37:34] [WARNING]:撤回消息时出现错误 : get value error: leveldb: not found
```

**Comment by xiangxiangxiong9** [comment]
试试把
```python3
print(requests.get("http://localhost:5700/delete_msg", data=data1).text)
```
换成
```python3
print(requests.post("http://localhost:5700/delete_msg", json=data1).text)
```

**Comment by guimc233** [comment]
> 试试把
> ```python3
> print(requests.get("http://localhost:5700/delete_msg", data=data1).text)
> ```
> 换成
> ```python3
> print(requests.post("http://localhost:5700/delete_msg", json=data1).text)
> ```

ok
