### ISSUE TITLE
功能建议：原先CQHTTP是没有发生群临时会话API的。希望楼主能增加这个扩展功能

### ISSUE THREAD

**Issue by xiaokaizhi** [Mrs4s/go-cqhttp#134]
原先CQHTTP是没有发生群临时会话API的。希望楼主能增加这个扩展功能。之前发的问题楼主说是支持回复群临时会话。只能回复不能主动发起群临时会话吗。这里说的群临时会话指的是：在一个群里主动和群里某个非好友的人单独私聊。打扰了：）

**Comment by zhzRedstone** [comment]
#117

**Comment by Mrs4s** [comment]
不会支持主动的, 会被滥用
