### ISSUE TITLE
自动切换QQ账号

### ISSUE THREAD

**Issue by daizihan233** [Mrs4s/go-cqhttp#1340]
**环境信息**

go-cqhttp版本: v1.0.0-beta4

**需要添加的功能内容**

像这样：
![image](https://user-images.githubusercontent.com/72146468/151158133-412c57a7-36d6-4f28-a340-dbbf29b9a66f.png)
如果在一个QQ账号被封、被冻结的情况下自动切到另一个账号尝试登录，这样会更方便一些

**Comment by Ink-33** [comment]
不考虑。

**Comment by Mrs4s** [comment]
没太大作用 暂时不会支持
