### ISSUE TITLE
[Bug]: bot收到的图片缓存[CQ:image,file=图片id.image]无法发送到群

### ISSUE THREAD

**Issue by zanjie1999** [Mrs4s/go-cqhttp#1344]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已经使用 dev 分支版本测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix2

### 运行环境

Ubuntu

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

举个例子
[CQ:image,file=81b3255468b4d11601c68a083ffcf434.image,url=https://c2cpicdw.qpic.cn/offpic_new/625797728//625797728-1638485669-81B3255468B4D11601C68A083FFCF434/0?term=3]
这是bot收到用户发送图片的样子
如果把这一段内容用私聊发送，用户会收到一个图片
如果把这段发到群里，会发送失败
但是，如果把段cq码的file=图片id删掉，就可以发送到群聊了，就像这样
[CQ:image,file=https://c2cpicdw.qpic.cn/offpic_new/625797728//625797728-1638485669-81B3255468B4D11601C68A083FFCF434/0?term=3]
如果key是url，不行，报错消息为空
[CQ:image,url=https://c2cpicdw.qpic.cn/offpic_new/625797728//625797728-1638485669-81B3255468B4D11601C68A083FFCF434/0?term=3]

### 期望的结果是什么？

图片发送成功

### 实际的结果是什么？

图片发送失败

### 日志记录（可选）

```golang
发送同时带有file和url的CQ:image
[2022-01-28 10:35:51] [WARNING]: 群消息发送失败: 账号可能被风控.
发送只有url的CQ:image
[2022-01-28 10:55:54] [WARNING]: 警告: 群 **** 消息图片上传失败: para error 
[2022-01-28 10:55:54] [WARNING]: 群消息发送失败: 消息为空.
```

**Comment by zanjie1999** [comment]
咩咩觉得是发图从file=图片id.image的时候

**Comment by zanjie1999** [comment]
经过测试，像CQ:image,file=图片id.image的缓存图均不能发到群，无论是从群里收到的还是私聊收到的，可以使用下面这条正则把url换到file的位置让图片可以发出去，但这样明显不是最优解，还是希望你们能修好这个bug
re.sub('\[CQ:image,file=[a-z0-9]+.image,url=(.*)\]',r'[CQ:image,file=\1]',msg)

**Comment by Mrs4s** [comment]
最新的 `dev` 分支已经修复
