### ISSUE TITLE
反向代理模式中 发过去的数据还得自己判断事件名称 有点麻烦

### ISSUE THREAD

**Issue by isBoom** [Mrs4s/go-cqhttp#1347]
**环境信息**
go-cqhttp设置模式的反向代理 另一边是我自己从零搭建的机器人用来处理go-cqhttp发过来的数据
go-cqhttp版本: v1.0.0-beta8-fix2

**需要添加的功能内容**
我自己的bot接受到的json数据直接就是实打实的数据，但我必须自己写很多逻辑来判断这是什么事件，能不能再json外面包一层数据，类似这种形式struct{”eventName“:"事件名（新增字段）","data":"原本发过来的数据"}，这样我就可以根据事件名直接解析到对应的struct中了。

**Comment by Ink-33** [comment]
很遗憾，修改上报格式并非一件易事。现版本`go-cqhttp`的上报格式基于`Onebot v11`标准，而下一代标准`Onebot v12`也基本定型，一段时间之内有大型改动的可能性较低。

我本人认为这是一个非常好的提案，因为静态语言对`Onebot RPC`的解析确实存在痛点。如果有可能的话，gocq v2设计时会进一步考虑此需求。

**Comment by isBoom** [comment]
好的谢谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月30日(星期天) 晚上9:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Mrs4s/go-cqhttp] 反向代理模式中 发过去的数据还得自己判断事件名称 有点麻烦 (Issue #1347)





 
很遗憾，修改上报格式并非一件易事。现版本go-cqhttp的上报格式基于Onebot v11标准，而下一代标准Onebot v12也基本定型，一段时间之内有大型改动的可能性较低。
 
我本人认为这是一个非常好的提案，因为静态语言对Onebot RPC的解析确实存在痛点。如果有可能的话，gocq v2设计时会进一步考虑此需求。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by isBoom** [comment]
感谢
