### ISSUE TITLE
支持修改机器人自身头像和昵称信息

### ISSUE THREAD

**Issue by shigma** [Mrs4s/go-cqhttp#1348]
**环境信息**
go-cqhttp版本: 1.0.0-b8f2

**需要添加的功能内容**
添加 API 支持修改机器人自身头像和昵称信息。

方案 1：`set_login_info` 根据传入的参数决定设置的内容，可以有 username 和 avatar 两个字段
方案 2：对不同的信息提供不同的接口，例如 `set_login_username` 和 `set_login_avatar`

**参考**
- #1138 之前这个被误关闭了
- https://github.com/Mrs4s/go-cqhttp/issues/1124#issuecomment-991882781

**Comment by allofee** [comment]
+1

**Comment by ThePureCC** [comment]
+1 尤其希望可以做到像discord bot那种, 将来QQ频道正式放出之后, 可以让bot把自己名字改成某些信息供用户查看

**Comment by shigma** [comment]
@ThePureCC 这个好像已经合并了，等一个新版本就应该有了

**Comment by ThePureCC** [comment]
> 

看到标题太激动了, 没看到merged...

**Comment by shigma** [comment]
头像好像没做 🤣 有希望做的话我另开一个 issue？
