### ISSUE TITLE
发送websocket指令能够附加一个Request ID，返回时原样带上

### ISSUE THREAD

**Issue by fy0** [Mrs4s/go-cqhttp#1352]
**环境信息**
go-cqhttp版本: v1.0.0-beta8-fix2

**需要添加的功能内容**
举例，ws连接获取个人信息时，发送指令
```js
{ action: "get_login_info", params: { requestId: 12345 } }
```

返回指令：
{"data":{"nickname":"<昵称>","user_id":<QQ>},"retcode":0,"status":"ok", "requestId": 12345}

**Comment by Ink-33** [comment]
你可能在找：`echo`

**Comment by Ink-33** [comment]
req：
``` json
{
    "action": "send_private_msg",
    "params": {
        "user_id": 10001000,
        "message": "你好"
    },
    "echo": "123"
}
```

**Comment by wdvxdr1123** [comment]
see https://github.com/botuniverse/onebot-11/blob/master/communication/ws.md#api-%E6%8E%A5%E5%8F%A3

**Comment by fy0** [comment]
十分感谢！正是我需要的。
