### ISSUE TITLE
go1.16版本兼容

### ISSUE THREAD

**Issue by youngbin1213** [Mrs4s/go-cqhttp#1353]
**环境信息**

go-cqhttp版本: [v1.0.0-beta8-fix2]

**需要添加的功能内容**

希望添加对go1.16的兼容

**Comment by Ink-33** [comment]
请您自行适配

**Comment by wdvxdr1123** [comment]
`internal/btree` 中使用了大量 `unsafe.Add()` 不太好适配

**Comment by Mrs4s** [comment]
考虑到今后还要使用泛型, 应该不会适配 `go1.16` 了

**Comment by youngbin1213** [comment]
> 考虑到今后还要使用泛型, 应该不会适配 `go1.16` 了

原来如此，谢谢大佬了！我该去升级1.17了
