### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by zxc7895531** [Mrs4s/go-cqhttp#1360]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix2

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

收到加群请求后分次向/get_group_member_info终点发送含有不同group_id以及同样user_id的请求，当retcode:0 时延迟五秒后向/set_group_add_request终点发送包含同样flags和sub_type的approve: false处理请求
（简称：检测同一个人是否加入了多个群）

### 期望的结果是什么？

拒绝加群请求

### 实际的结果是什么？

go-cqhttp提示flags不存在

### 简单的复现代码/链接（可选）

```python
flag = req_data["flag"]
user_id = req_data["user_id"]
sub_type = req_data["sub_type"]
group_id = req_data["group_id"]
for group in group_list:
    req = requests.get("http://127.0.0.1:XXXX/get_group_member_info",params={"group_id":group,"user_id":user_id})
    returndata = req.json()
    if returndata["retcode"] == 0:
        time.sleep(5)
        requests.post("http://127.0.0.1:XXXX/set_group_add_request",data={"flag":flag,"sub_type":sub_type,"approve":False,"reason":"您已经在XXX群中了，请勿重复加群"})
        return {}
return {}
```

### 日志记录（可选）

```golang
https://paste.ubuntu.com/p/W6q4Qc4rZR/
```

### 补充说明（可选）

在今天之前本来是正常使用的，但是今天突然就不行了

**Comment by wdvxdr1123** [comment]
已修
