### ISSUE TITLE
[Bug]: 配置文件中 max-retries 和 retries-interval 不合法

### ISSUE THREAD

**Issue by YidaozhanYa** [Mrs4s/go-cqhttp#1362]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

54dbccf

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

使用默认的配置文件并取消“反向HTTP POST地址列表"相关几行注释后出现。

### 期望的结果是什么？

max-retries 和 retries-interval 能被机器人程序正常读取并且使用。

### 实际的结果是什么？

机器人报错“配置文件不合法”并且退出。

### 日志记录（可选）

```golang
❯ ./go-cqhttp
FATA[0000] 配置文件不合法!yaml: line 107: found character that cannot start any token
```

### 补充说明（可选）

之前看到过一个pr添加了在两个选项，并且在当时的几个dev版本中可以使用，但是最近就不行了。

**Comment by YidaozhanYa** [comment]
是默认的配置文件中有无效字符，自己删掉之后重新写上就好了，但还是希望改进。

**Comment by lineorte** [comment]
> 是默认的配置文件中有无效字符，自己删掉之后重新写上就好了，但还是希望改进。

请问具体是config.yml哪个地方
