### ISSUE TITLE
[Bug]: 无法发送频道消息

### ISSUE THREAD

**Issue by zxc7895531** [Mrs4s/go-cqhttp#1369]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

[ba808f](https://github.com/Mrs4s/go-cqhttp/commit/ba808fff1d35258ce49f3bb4b2b0ef0a522d7ba4)

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

1 | Android Phone

### 重现步骤

向子频道发送消息

### 期望的结果是什么？

成功发送

### 实际的结果是什么？

无法发送

### 简单的复现代码/链接（可选）

```python
requests.post("http://127.0.0.1:5700/send_guild_channel_msg", json={"guild_id": XXXX, "channel_id": XXXX, "message": "test"}).json()

# {'data': None, 'msg': 'SEND_MSG_API_ERROR', 'retcode': 100, 'status': 'failed', 'wording': '请参考 go-cqhttp 端输出'}
```

### 日志记录（可选）

```golang
[2022-02-12 19:04:41] [DEBUG]: HTTPServer接收到API调用: send_guild_channel_msg
[2022-02-12 19:04:41] [DEBUG]: Protocol -> rev pkt: MsgProxy.SendMsg seq: 13916
[2022-02-12 19:04:41] [WARNING]: 频道消息发送失败: send channel message error: server response 100499
```

**Comment by zxc7895531** [comment]
已解决，是子频道权限问题，希望可以加一个提示

**Comment by 2mf8** [comment]
怎么解决的，我也遇到了，给机器人管理也发不出消息
