### ISSUE TITLE
机器人发送[CQ:at]，手机端艾特的是QQ号码

### ISSUE THREAD

**Issue by lizkes** [Mrs4s/go-cqhttp#138]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.19
运行环境: docker debian container
连接方式: 反向WS

**bug内容**
机器人发送[CQ:at]，手机端艾特的是QQ号码，但是在电脑端正常，艾特的是昵称

电脑端截图
![M 43(YB7`CALC@)}RGXIG{7](https://user-images.githubusercontent.com/20457790/90584700-cb323300-e205-11ea-9d1a-6e3ca71bbf25.png)

安卓端截图
![snipaste_20200819_102237](https://user-images.githubusercontent.com/20457790/90584775-f2890000-e205-11ea-9138-c16eeed38850.png)

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by Mrs4s** [comment]
已修复 请等待Release
