### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 1ndeed** [Mrs4s/go-cqhttp#1380]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc1

### 运行环境

Linux

### 连接方式

HTTP

### 使用协议

2 | Android Watch

### 重现步骤

新版本v1.0.0-rc1中：
> xx.image文件缓存被弃用，以前的文件缓存可以继续使用, 并且消息上报任采用xx.image形式,但是缓存会被写入一个db文件中，计划在正式版中删除文件缓存的支持

尝试使用`DB Browser for SQLite`打开image.db和video.db，都要求输入密码，密码是什么？

我的目的是获取一个被撤回的图片，打开image.db能解决问题吗？

### 期望的结果是什么？

得到image.db和video.db的打开方式
得到获取被撤回图片的方法

### 实际的结果是什么？

无密码

### 日志记录（可选）

```golang
[2022-02-16 11:11:44] [INFO]: 收到群 *** 内 *** 的消息: [CQ:image,file=f5ea23674c38128e70adbfbb4bd73ab0.image,subType=0] (***)
[2022-02-16 11:14:12] [INFO]: 群 *** 内 *** 撤回了 *** 的消息: ***.
```

**Comment by Akegarasu** [comment]
首先，这两个 db 文件并不是 sqlite ，你用 sqlite 的工具自然打不开
其次，gocq 并不会缓存图片文件本身，无论是 `.image` 文件还是数据库都只存了这个图片的一些必要信息，打开 `image.db` 并不能解决你的问题
要获取这个图片你只需要再把上面的 cq码 发出来即可

**Comment by 1ndeed** [comment]
> 首先，这两个 db 文件并不是 sqlite ，你用 sqlite 的工具自然打不开
> 其次，gocq 并不会缓存图片文件本身，无论是 `.image` 文件还是数据库都只存了这个图片的一些必要信息，打开 `image.db` 并不能解决你的问题
> 要获取这个图片你只需要再把上面的 cq码 发出来即可

cq码是这个吗？
```
-2037514746
```
具体获取方法是什么呢？

**Comment by xiangxiangxiong9** [comment]
> > 首先，这两个 db 文件并不是 sqlite ，你用 sqlite 的工具自然打不开
> > 其次，gocq 并不会缓存图片文件本身，无论是 `.image` 文件还是数据库都只存了这个图片的一些必要信息，打开 `image.db` 并不能解决你的问题
> > 要获取这个图片你只需要再把上面的 cq码 发出来即可
> 
> cq码是这个吗？
> 
> ```
> [CQ:image,file=f5ea23674c38128e70adbfbb4bd63ab0.image,subType=0] (-2037514746)
> ```
> 
> 具体获取方法是什么呢？

API: get_image
参数: file [字符串] 传入那个*******.image
返回 file 保存的图片文件 filename 图片名..? size 图片大小[单位可能是字节] url 远程连接
