### ISSUE TITLE
发送本地GIF图片时，电脑端显示正常，手机端显示静态图片。发送网络GIF图片时都正常。

### ISSUE THREAD

**Issue by lizkes** [Mrs4s/go-cqhttp#139]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.19
运行环境: docker debian container
连接方式: 反向WS

**bug内容**
发送本地GIF图片时，电脑端显示正常，手机端显示静态图片。发送网络GIF图片时都正常。

本地GIF图片，电脑端：
![1](https://user-images.githubusercontent.com/20457790/90593368-4c93c080-e21a-11ea-8936-4c667fa5a2b4.png)

本地GIF图片，手机端：
变成了静态图片了，且右下角有一个GIF标志
![3](https://user-images.githubusercontent.com/20457790/90593386-587f8280-e21a-11ea-9a6a-3eb73e6501cb.png)

网络GIF图片，电脑端手机端都正常，且手机端图片右下角无GIF标志：
![2](https://user-images.githubusercontent.com/20457790/90593433-78af4180-e21a-11ea-8354-20ffbfc30f6a.png)
![4](https://user-images.githubusercontent.com/20457790/90593435-7947d800-e21a-11ea-823e-3521fbd434ca.png)

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by lizkes** [comment]
更新，我将那张本地图片上传到图床，再使用网络地址格式，依然是电脑端正常，手机端显示静态文件。所以应该是那个图片的问题

**Comment by Mrs4s** [comment]
这应该是QQ服务器直接转发的问题，目前还有几个其他功能在优先处理，这个bug暂且推后

**Comment by Mrs4s** [comment]
我这边暂时无法复现...
