### ISSUE TITLE
[Bug]: 取不到当前龙王信息，talkative，之前的版本能取到，更新以后就取不到了，这个很好测试复现，你们试一下就知道了

### ISSUE THREAD

**Issue by Thanatuz** [Mrs4s/go-cqhttp#1390]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc1

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

取不到当前龙王信息，talkative，之前的版本能取到，更新以后就取不到了，这个很好测试复现，你们试一下就知道了

### 期望的结果是什么？

龙王信息

### 实际的结果是什么？

null

### 简单的复现代码/链接（可选）

```golang
func IsDragonKing(ctx *zero.Ctx) bool {
	QQ := int64(ctx.GetGroupHonorInfo( 
		ctx.Event.GroupID,
		"talkative",
	).Get("current_talkative").Get("user_id").Num)

	log.Infoln( "IsDragonKing:", ctx.MessageString(), QQ	, ctx.Event.SelfID	 )

	return QQ == ctx.Event.SelfID
}
```

**Comment by wdvxdr1123** [comment]
某些群可能没有龙王，经测试在有龙王的群能正常获取
