### ISSUE TITLE
运行时崩溃

### ISSUE THREAD

**Issue by Shigma** [Mrs4s/go-cqhttp#14]
![image](https://user-images.githubusercontent.com/33423008/89165053-90e05900-d5aa-11ea-925f-27d077067c1d.png)

**Comment by Shigma** [comment]
有点频繁……

![image](https://user-images.githubusercontent.com/33423008/89166624-e6b60080-d5ac-11ea-90ff-0542792c80a4.png)

**Comment by Mrs4s** [comment]
奇怪了 理论上是修好了来着，我再研究下

**Comment by Mrs4s** [comment]
已修复
