### ISSUE TITLE
音频格式建议

### ISSUE THREAD

**Issue by zxc7895531** [Mrs4s/go-cqhttp#140]
本人花了一点的时间研究了一下音频文件的格式，得出的结论大约是这样的：
.amr文件生成最方便，使用ffmpeg自带的编码器即可生成，音质较为清楚（.amr文件上传至服务器之后不会对文件进行任何操作，源文件md5与从服务器上获取的amr文件的md5完全一致）
.silk文件生成麻烦，无法直接使用ffmpeg生成，音质比较差（.silk文件上传后，服务器会对文件进行很严重的二压，上传时48Kbps的码率下载时变成了4.5Kbps）

另外，本人还看见有的机器人通过上传MPEG格式的音频至服务器以实现128Kbps甚至320Kbps的高清音频，但是本人试验了很久发现上传MPEG格式后客户端无法解析并且播放，望知道办法的dalao回复。

**Comment by Mrs4s** [comment]
这部分可能还需要更多测试，目前我观察到的话CQ是转码成silk上传的

**Comment by zxc7895531** [comment]
花了些许时间仔细研究了一下，发现手机QQ客户端可以发送22.1Khz采样率32Kbps音质的slk文件，而且服务器不会进行二次压缩，原理暂时未知，请问owner能否实现这一操作呢？
关于MPEG格式的发送我也找到了相关信息，原理是通过替换手机QQ的录音文件来实现上传mpeg格式文件的功能，但是PC端无法正常解析并播放，手机端则可以。使用go-cqhttp发送mpeg格式文件时则不管是哪种客户端都是无法解析。

**Comment by Mrs4s** [comment]
我这边也研究了一下 直接发送通过 [这个项目](https://github.com/kn007/silk-v3-decoder) 转换出来的语音会被QQ二压，暂时还没找到解决方案. 比较迷
