### ISSUE TITLE
[Bug]: 图片无法单独发送

### ISSUE THREAD

**Issue by MTmin** [Mrs4s/go-cqhttp#1406]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc1/包括以上版本

### 运行环境

CentOS

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

全部协议已经都测试了一边,都无法发送图片,提示账号风控;
尝试操作包括:更换服务器,更换设备信息等

但是不单独发送图片可以发出,例如在图片后面加上一个空格,或者文字之类的就可以发出来

### 期望的结果是什么？

正常发出单独图片信息

### 实际的结果是什么？

无法发出图片

**Comment by MTmin** [comment]
图片是base64的

**Comment by qianjunakasumi** [comment]
您已知晓是由账号风控引起的，`这个 Issue 是关于其他非程序本身问题，这些问题应当在 Discussion 板块提出。`

请您再次认真阅读注意事项

**Comment by wdvxdr1123** [comment]
无法复现
