### ISSUE TITLE
[Bug]: 源码编译时出现包循环引用了，拉的是master分支

### ISSUE THREAD

**Issue by anyanfei** [Mrs4s/go-cqhttp#1412]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

master

### 运行环境

Windows (64)

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

package github.com/Mrs4s/go-cqhttp
	imports github.com/Mrs4s/go-cqhttp/cmd/gocq
	imports github.com/Mrs4s/go-cqhttp/coolq
	imports github.com/Mrs4s/go-cqhttp/db
	imports github.com/Mrs4s/go-cqhttp/global
	imports github.com/Mrs4s/go-cqhttp/internal/base
	imports github.com/Mrs4s/go-cqhttp/global: import cycle not allowed

### 期望的结果是什么？

成功编译

### 实际的结果是什么？

成功编译

**Comment by anyanfei** [comment]
global/codec.go中使用了base.EncodeSilk
而internal/base/flag.go中又使用了global.PathExists  这两个包互相引用了
请作者进行修复。

**Comment by wdvxdr1123** [comment]
你可以拉取dev分支

**Comment by anyanfei** [comment]
> 你可以拉取dev分支

好的大佬~
