### ISSUE TITLE
send_group_message 不支持向多个群发同一个消息吗

### ISSUE THREAD

**Issue by Harris-H** [Mrs4s/go-cqhttp#1419]
只能一个一个群发，是这样嘛qwq

**Comment by qianjunakasumi** [comment]
Onebot 标准中定义了本接口[（链接🔗）](https://github.com/botuniverse/onebot-11/blob/master/api/public.md#%E5%8F%82%E6%95%B0-1)

group_id 中定义数据类型是 number

## 结论

不支持
