### ISSUE TITLE
[Bug]: 视频有时发不起来

### ISSUE THREAD

**Issue by Huangtingdt** [Mrs4s/go-cqhttp#1422]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0

### 运行环境

Ubuntu

### 运行架构

x86

### 连接方式

WebSocket (反向)

### 使用协议

2 | Android Watch

### 发送视频有时会报错
![image](https://user-images.githubusercontent.com/45315146/158054871-df1f8f8a-82cc-422f-9443-63285fd68981.png)

### 期望的结果是什么？

能够正常发送

### 实际的结果是什么？

抛出异常

**Comment by qianjunakasumi** [comment]
Invalid

请提供 go-cqhttp 控制台输出日志，以便我们确定问题，敏感信息请自行删除

**Comment by Huangtingdt** [comment]
cqhttp日志信息
![image](https://user-images.githubusercontent.com/45315146/158142988-74a9c020-2198-4d37-b7ea-f3c4f94187f3.png)
