### ISSUE TITLE
[Bug]: 请问如何正确的关闭go-cqhttp进程(windows)，以免产生“打开数据库失败”错误

### ISSUE THREAD

**Issue by fy0** [Mrs4s/go-cqhttp#1424]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0rc1

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (正向)

### 使用协议

1 | Android Phone

### 重现步骤

两个办法均可以触发：

流程A：使用引导进程启动go-cqhttp，等待登录完成后，结束进程，并稍后再次启动（引导进程不退出）。

流程B：使用引导进程启动go-cqhttp，等待登录完成后，结束进程。此时再关闭引导进程重开，走登录环节前此问题复现。

### 期望的结果是什么？

正常完成进程被关闭 -> 重启的过程。

### 实际的结果是什么？

1.0rc1版本:
[2022-03-16 01:26:35] [FATAL]: 打开数据库失败: open backend error: open leveldb error: The process cannot access the file because it is being used by another process. 

dev版本:
[2022-03-16 01:30:09] [FATAL]: open image cache failed: 文件被其他进程占用 

补充:
我的判断是leveldb打开失败，直接原因就是上次进程没有能够正常退出。因此我设想的修补方案是给gocqhttp发中断的指令。
但是，golang的process模块明确说明“Sending Interrupt on Windows is not implemented.”
gocqhttp手册中也没有找到如何命令gocqhttp退出的说明。

### 简单的复现代码/链接（可选）

```golang
代码大致如此:
	"github.com/fy0/procs"  // 引用这个包，原版包缺依赖


func run() {
	p := procs.NewProcess(gocqhttpExePath + " faststart")
	p.Dir = workDir
	p.Run()
	return p
}

p := run()
p.Stop()

run()


// stop内部使用golang内置的process包的Kill

// Stop tries to stop the process.
func (p *Process) Stop() error {
	for _, cmd := range p.Cmds {
		// ProcessState means it is already exited.
		if cmd.ProcessState != nil {
			continue
		}

		err := cmd.Process.Kill()
		if err != nil {
			return err
		}
	}

	return nil
}

```
```


### 日志记录（可选）

_No response_

### 补充说明（可选）

_No response_

**Comment by fy0** [comment]
我寻思了一下并不能排除引导程序写错的可能   我再去检查一下 先搁置

**Comment by fy0** [comment]
我人傻了，发现有个地方多调用了一次，代码其实能work。我去写个标记值

**Comment by stick-i** [comment]
兄弟，你这个open image cache failed 的报错，最后是怎么解决的啊，我这也报了这个问题

![image](https://user-images.githubusercontent.com/67500171/201468965-925182d3-bec0-4152-8882-a8d28c13211a.png)


我的版本是 go-cqhttp_windows_amd64(v1.0.0-rc3)

**Comment by fy0** [comment]
> 兄弟，你这个open image cache failed 的报错，最后是怎么解决的啊，我这也报了这个问题
> 
> ![image](https://user-images.githubusercontent.com/67500171/201468965-925182d3-bec0-4152-8882-a8d28c13211a.png)
> 
> 我的版本是 go-cqhttp_windows_amd64(v1.0.0-rc3)

我忘了 好像是kill不彻底之类

**Comment by stick-i** [comment]
好的，收到了

**Comment by lmx4727** [comment]
请问一下应该怎么解决啊
