### ISSUE TITLE
视频上传失败

### ISSUE THREAD

**Issue by Huangtingdt** [Mrs4s/go-cqhttp#1426]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0

### 运行环境

Ubuntu

### 运行架构

x86

### 连接方式

WebSocket (反向)

### 使用协议

1 | Android Phone

### 重现步骤

发送视频时出现上传视频错误这个报错
![image](https://user-images.githubusercontent.com/45315146/158573428-b90c26a7-73ea-4bd6-9ff8-d2f47c7cb146.png)

### 期望的结果是什么？

能够不出现报错

### 实际的结果是什么？

提示上传视频失败

**Comment by Huangtingdt** [comment]
版本是v1.0.0-rc1

**Comment by wdvxdr1123** [comment]
参考 #577 ,视频多大， 是否安装ffmpeg

**Comment by Huangtingdt** [comment]
已经安装ffmpeg

**Comment by Gingmzmzx** [comment]
同样，已安装ffmpeg，文件只有几百kb

**Comment by wdvxdr1123** [comment]
可以尝试使用dev中的版本
https://github.com/Mrs4s/go-cqhttp/actions/runs/2096571890

**Comment by Huangtingdt** [comment]
你这个是action地址啊

**Comment by 675535** [comment]
经测试，小于3M的视频经常发送失败，95%~100%，大于3M视频100%发送成功。原因未知。

**Comment by 675535** [comment]
> 可以尝试使用dev中的版本 https://github.com/Mrs4s/go-cqhttp/actions/runs/2096571890

经测试，此版本不存在视频发送失败问题，所有视频100%发送成功。

**Comment by tomorrorning** [comment]
> 可以尝试使用dev中的版本 https://github.com/Mrs4s/go-cqhttp/actions/runs/2096571890

更换此版本后bot发图片会群风控是什么原因？挂bot好几天了也没有解风控，怎么解决呢？
