### ISSUE TITLE
[Bug]: 扫码登陆机器人失败

### ISSUE THREAD

**Issue by zixuan2020** [Mrs4s/go-cqhttp#1428]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc1

### 运行环境

Ubuntu

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

2 | Android Watch

### 重现步骤

扫码登陆机器人失败
![Uploading image.png…]()

### 期望的结果是什么？

扫码登陆机器人成功

### 实际的结果是什么？

扫码登陆机器人成功

**Comment by zixuan2020** [comment]
<img width="757" alt="image" src="https://user-images.githubusercontent.com/20490066/158815923-3830ce5e-24fb-42e0-928c-7016f6c47dcb.png">

**Comment by zixuan2020** [comment]
> 扫码登录链接现在失效了，目前会302跳转到手机QQ下载页面，应该是这个原因
> 
> https://txz.qq.com
> 
> https://im.qq.com/mobileqq/

确实，已发现问题

**Comment by SEANPNEX** [comment]
在本地(ubuntu 21.10)登陆后将`session.token`,`device.json`,`config.yml`上传到云端go-cqhttp目录下后解决了这个问题

**Comment by copurxia** [comment]
> 在本地(ubuntu 21.10)登陆后将`session.token`,`device.json`,`config.yml`上传到云端go-cqhttp目录下后解决了这个问题

还有其他的解决办法吗，我现在在本地都无法登录

**Comment by copurxia** [comment]
目前是暂时用密码登录替代了
