### ISSUE TITLE
[Bug]: 安卓协议下 get_group_member_info 中 shut_up_timestamp 始终为0

### ISSUE THREAD

**Issue by ishkong** [Mrs4s/go-cqhttp#1429]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

8d26e3a

### 运行环境

CentOS

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

1 | Android Phone

### 重现步骤

get_group_member_info获取该id在该群的信息（no_cache=True）

### 期望的结果是什么？

{'age': 0, 'area': '', 'card': '417 Expectation Failed', 'card_changeable': False, 'group_id': *****, 'join_time': ****, 'last_sent_time': 1647529201, 'level': '3', 'nickname': '南 ことり', 'role': 'member', 'sex': 'female', 'shut_up_timestamp': 禁言事件发生+600s具体没算, 'title': '', 'title_expire_time': 0, 'unfriendly': False, 'user_id': *****}

### 实际的结果是什么？

{'age': 0, 'area': '', 'card': '417 Expectation Failed', 'card_changeable': False, 'group_id': *****, 'join_time': ****, 'last_sent_time': 1647529201, 'level': '3', 'nickname': '南 ことり', 'role': 'member', 'sex': 'female', 'shut_up_timestamp': 0, 'title': '', 'title_expire_time': 0, 'unfriendly': False, 'user_id': *****}

**Comment by wdvxdr1123** [comment]
请更新并使用 `no_cache=false`
