### ISSUE TITLE
收到很多meta_event消息是什么原因

### ISSUE THREAD

**Issue by xiaokaizhi** [Mrs4s/go-cqhttp#143]
收到很多meta_event消息是什么原因

**Comment by xiaokaizhi** [comment]
是心跳事件吗。为什么把这种消息也上报了

**Comment by Mrs4s** [comment]
[文档](https://github.com/howmanybots/onebot/blob/master/v11/specs/event/meta.md#%E5%BF%83%E8%B7%B3)

**Comment by xiaokaizhi** [comment]
> [文档](https://github.com/howmanybots/onebot/blob/master/v11/specs/event/meta.md#%E5%BF%83%E8%B7%B3)

是在config.json配置文件里配置吗
