### ISSUE TITLE
[Bug]: 使用[CQ:image]时，路径中包含‘#’符号会导致无法发送

### ISSUE THREAD

**Issue by Caleeen** [Mrs4s/go-cqhttp#1435]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc1

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

发送消息
[CQ:image,file=file:///F:\a#\a.jpg,cache=1]

### 期望的结果是什么？

成功发送图片，尝试过将'#'符号替换成实体字符发送
[CQ:image,file=file:///F:\a&#35;\a.jpg,cache=1]
得到的也是转换错误
转换CQ码 [CQ:image,file=file:///F:\a&#35;\a.jpg,cache=1] 时出现错误: file not found 将原样发送. 

### 实际的结果是什么？

转换CQ码 [CQ:image,file=file:///F:\a#\a.jpg,cache=1] 时出现错误: file not found 将原样发送.

**Comment by Caleeen** [comment]
[期望的结果是什么？](#期望的结果是什么？)中的实体字符被转义了,,,,,我上传图片吧
![QQ截图20220321154801](https://s1.ax1x.com/2022/03/21/qnD8VU.png)

**Comment by qianjunakasumi** [comment]
成功复现

**Comment by wdvxdr1123** [comment]
根据 #1436 的讨论和 [onebot标准](https://github.com/botuniverse/onebot-11/blob/master/message/segment.md#%E5%9B%BE%E7%89%87), 需要对#进行转义(URL转义):
# -> %23
