### ISSUE TITLE
考虑 RESTful 风格 API

### ISSUE THREAD

**Issue by qianjunakasumi** [Mrs4s/go-cqhttp#1437]
随着 API 的增多，更多的 API 聚集在 api.go 文件中，缺乏层级，也不便于查找

## 考虑 RESTful 风格的 API

- 便于更多的功能可以通过 API 暴露
- 避免单一层级中聚合过多的 API
- 和某个实体相关的 API （例如 Group）可以内聚

## 例

- 发送群消息
```
POST https://foo.go-cqhttp/Group/1145141919/message?payload=今晚吃什么
```

- 获取群公告
```
GET https://foo.go-cqhttp/Group/Notice
```

- 发布群公告
```
POST https://foo.go-cqhttp/Group/Notice?content=晚上吃盐焗鸡翅
```

- 群公告删除
```
DELETE https://foo.go-cqhttp/Group/Notice?id=A1B1C4D5E1F4G
```

## 向下兼容

OneBot 11 定义的 API 仍可以保留，除此之外定义的 API 可以通过 RESTful 风格实现

---

##### GRPC？另起 issue

**Comment by DarckRM** [comment]
好
