### ISSUE TITLE
Go-cqhttp程序崩溃

### ISSUE THREAD

**Issue by Watanabe-Asa** [Mrs4s/go-cqhttp#144]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.20
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
启动cqhttp时出现崩溃。控制台报错：
[root@VM-0-9-centos go]# ./go-cqhttp
[2020-08-20 13:57:37] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2020-08-20 13:57:37] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2020-08-20 13:57:42] [INFO]: 开始尝试登录并同步消息... 
[2020-08-20 13:57:44] [INFO]: 登录成功 欢迎使用: Misaki 
[2020-08-20 13:57:45] [INFO]: 开始加载好友列表... 
[2020-08-20 13:57:45] [INFO]: 共加载 12 个好友. 
[2020-08-20 13:57:45] [INFO]: 开始加载群列表... 
[2020-08-20 13:57:47] [INFO]: 共加载 10 个群. 
[2020-08-20 13:57:47] [INFO]: 信息数据库初始化完成. 
[2020-08-20 13:57:47] [INFO]: 开始尝试连接到反向Websocket Universal服务器: ws://0.0.0.0:9222/ws/ 
[2020-08-20 13:57:47] [INFO]: 资源初始化完成, 开始处理信息. 
[2020-08-20 13:57:47] [INFO]: アトリは、高性能ですから! 
runtime: failed to create new OS thread (have 6 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc

runtime stack:
runtime.throw(0xc870ff, 0x9)
        /usr/local/go/src/runtime/panic.go:1112 +0x72
runtime.newosproc(0xc000389180)
        /usr/local/go/src/runtime/os_linux.go:160 +0x1ba
runtime.newm1(0xc000389180)
        /usr/local/go/src/runtime/proc.go:1753 +0xdc
runtime.newm(0x0, 0xc000042000)
        /usr/local/go/src/runtime/proc.go:1732 +0x8f
runtime.startm(0x0, 0xc000042000)
        /usr/local/go/src/runtime/proc.go:1869 +0x12a
runtime.sysmon()
        /usr/local/go/src/runtime/proc.go:4533 +0x2a4
runtime.mstart1()
        /usr/local/go/src/runtime/proc.go:1097 +0xc3
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1062 +0x6e

goroutine 1 [chan receive]:
main.main()
        /github/workspace/main.go:251 +0xfdf

goroutine 7 [chan receive]:
github.com/Mrs4s/MiraiGo/utils.NewCache.func1(0xc00035ec80)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200819185537-8d1e5fb04c17/utils/ttl.go:39 +0x15d
created by github.com/Mrs4s/MiraiGo/utils.NewCache
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200819185537-8d1e5fb04c17/utils/ttl.go:35 +0xb6

goroutine 8 [chan receive]:
github.com/Mrs4s/MiraiGo/utils.NewCache.func1(0xc00035eca0)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200819185537-8d1e5fb04c17/utils/ttl.go:39 +0x15d
created by github.com/Mrs4s/MiraiGo/utils.NewCache
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200819185537-8d1e5fb04c17/utils/ttl.go:35 +0xb6

goroutine 12 [IO wait]:
internal/poll.runtime_pollWait(0x7f5fbbc35e38, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc00039e598, 0x72, 0x0, 0x1, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00039e580, 0xc00038c294, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc00039e580, 0xc00038c294, 0x1, 0x1, 0xc000085e30, 0x449eec, 0x1)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e888, 0xc00038c294, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x8e
github.com/Mrs4s/MiraiGo/binary.(*NetworkReader).ReadByte(0xc000085fa8, 0x4, 0x4, 0xc00038c290)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200819185537-8d1e5fb04c17/binary/reader.go:128 +0x7a
github.com/Mrs4s/MiraiGo/binary.(*NetworkReader).ReadBytes(0xc000085fa8, 0x4, 0xc000085f20, 0xc000085f28, 0x28, 0xc0003aa000, 0x85a867)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200819185537-8d1e5fb04c17/binary/reader.go:141 +0x7f
github.com/Mrs4s/MiraiGo/binary.(*NetworkReader).ReadInt32(0xc000085fa8, 0xcb20d8, 0xc0003a6000, 0xc00012edc0)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200819185537-8d1e5fb04c17/binary/reader.go:151 +0x38
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0xc0003a6000)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200819185537-8d1e5fb04c17/client/client.go:928 +0x9c
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).Login
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200819185537-8d1e5fb04c17/client/client.go:165 +0x9e

goroutine 36 [sleep]:
time.Sleep(0x12a05f200)
        /usr/local/go/src/runtime/time.go:198 +0xba
github.com/Mrs4s/go-cqhttp/coolq.NewQQBot.func1(0xc0000784e0)
        /github/workspace/coolq/bot.go:69 +0x4e
created by github.com/Mrs4s/go-cqhttp/coolq.NewQQBot
        /github/workspace/coolq/bot.go:67 +0xaca

goroutine 38 [IO wait]:
internal/poll.runtime_pollWait(0x7f5fbbc35f18, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc00012d498, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00012d480, 0xc0002e7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc00012d480, 0xc0002e7000, 0x1000, 0x1000, 0xc000393e20, 0xc000393e20, 0xc000083eb0)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e8f8, 0xc0002e7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x8e
bufio.(*Reader).fill(0xc000231e00)
        /usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc000231e00, 0x2, 0xbc9b40, 0x0, 0xc00004d400, 0x5b80b1, 0xc00004d3b8)
        /usr/local/go/src/bufio/bufio.go:138 +0x4f
github.com/gorilla/websocket.(*Conn).read(0xc000367340, 0x2, 0x0, 0xffffffffffffffff, 0xc00004d450, 0x5b8eb6, 0xc0003b7e80)
        /go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:370 +0x40
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc000367340, 0xb3d960, 0xc000230810, 0xb217c0)
        /go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:798 +0x5c
github.com/gorilla/websocket.(*Conn).NextReader(0xc000367340, 0xc00004d5a0, 0x5bc1dd, 0xc0003b7e80, 0xb217c0, 0xc000230810)
        /go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:980 +0x8f
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc000367340, 0x44407c, 0xc000074358, 0x1, 0x0, 0xc00004d6f8, 0xc00004d610)
        /go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:1064 +0x2f
github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenApi(0xc0002822c0, 0xc000367340, 0xc000367301)
        /github/workspace/server/websocket.go:151 +0x7f
created by github.com/Mrs4s/go-cqhttp/server.(*websocketClient).connectUniversal
        /github/workspace/server/websocket.go:144 +0x4a2

goroutine 39 [syscall]:
os/signal.signal_recv(0xc00012e4b0)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.Notify.func1
        /usr/local/go/src/os/signal/signal.go:127 +0x44
[root@VM-0-9-centos go]# 

**复现方法**
启动go-cqhttp时即崩溃。
另外若在bot未运行时启动go-cqhttp，虽然不会报错，但在bot启动后依然会崩溃。应该是bot执行线程过多的缘故，但前一个版本似乎未出现过此问题。

**Comment by Mrs4s** [comment]
请尝试通过ulimit调大限制 6个线程就给系统杀了比较难受
