### ISSUE TITLE
[Bug]: 修改device.json里协议为安卓协议，登录时依然提示ipad协议

### ISSUE THREAD

**Issue by shangdev** [Mrs4s/go-cqhttp#1440]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc1

### 运行环境

CentOS

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

HTTP

### 使用协议

1 | Android Phone

### 重现步骤

如图

![image](https://user-images.githubusercontent.com/15621520/159884023-5486dcc8-fe5c-441a-9dee-33bbd5aa53ed.png)

### 期望的结果是什么？

使用安卓协议登录

### 实际的结果是什么？

ipad协议登录

**Comment by zhaodice** [comment]
你可能需要

sudo rm ./session.token

**Comment by zhaodice** [comment]
登录成功后，会生成`session.token`文件（登录凭据），而里面已经绑定了设备信息，所以你改device.json是木大的

**Comment by wdvxdr1123** [comment]
json中请不要使用重复键

**Comment by shangdev** [comment]
@zhaodice 那该如何修改协议？
