### ISSUE TITLE
Windows跳过启动延时文档好像写错了

### ISSUE THREAD

**Issue by mcdoeswhat** [Mrs4s/go-cqhttp#1446]
Windows跳过启动延时文档好像写错了
试了下win10 bat后面加faststart没用,改成-faststart就可以了
https://docs.go-cqhttp.org/guide/quick_start.html#%E8%B7%B3%E8%BF%87%E5%90%AF%E5%8A%A8%E7%9A%84%E4%BA%94%E7%A7%92%E5%BB%B6%E6%97%B6

**Comment by qianjunakasumi** [comment]
cc @ishkong

**Comment by ishkong** [comment]
已修正 感谢提醒 [ishkong/go-cqhttp-docs#2792e71](https://github.com/ishkong/go-cqhttp-docs/commit/2792e718c80d478b4da4175d6277fed29ca724ef)
