### ISSUE TITLE
希望可以增加频道开关

### ISSUE THREAD

**Issue by rhwong** [Mrs4s/go-cqhttp#1449]
**环境信息**
go-cqhttp版本: 1.0.0-rc1

**需要添加的功能内容**
希望可以添加一个开关，用于关闭接收和回复频道信息
我bot反复被拉到官方频道，一不留神就被触发回复，呜呜救救

**Comment by Wind2009-Louse** [comment]
事件过滤器把``"message_type": "guild"``的过滤掉试试

**Comment by wdvxdr1123** [comment]
简单的方法，配置事件过滤器
```json
{
    "guild_id": null
}
```
这样只会收到不含guild_id的事件
