### ISSUE TITLE
怎么配置不上报心跳消息

### ISSUE THREAD

**Issue by xiaokaizhi** [Mrs4s/go-cqhttp#145]
我在config.json里配置了如下不起作用：
	"heartbeat":{
		"enable":false
	},

**Comment by Mrs4s** [comment]
为了解决断线问题 目前是强制上报心跳的

**Comment by xiaokaizhi** [comment]
> 为了解决断线问题 目前是强制上报心跳的

能不能不要上报到我填的接口地址里去

**Comment by xiaokaizhi** [comment]
我理解心跳是检测是否掉线应该和我接口没有关系才对

**Comment by xiaokaizhi** [comment]
掉线应该是指的qq是否掉线把。不是我接口服务掉线把

**Comment by xiaokaizhi** [comment]
好的。我明白了

**Comment by Mrs4s** [comment]
请仔细阅读文档

**Comment by xiaokaizhi** [comment]
好的

**Comment by xiaokaizhi** [comment]
> 请仔细阅读文档

我之前检测是否掉线是通过调用机器人的某个接口来检测的。

**Comment by Mrs4s** [comment]
服了 我说的是WS掉线, 机器人的心跳怎么可能发到你那里去

**Comment by Mrs4s** [comment]
心跳本身就是个CQHTTP的元事件，请仔细阅读文档再来这里提问

**Comment by shitianshiwa** [comment]
https://github.com/Mrs4s/go-cqhttp/issues/131
