### ISSUE TITLE
希望添加【语音转文字】API

### ISSUE THREAD

**Issue by funnygeeker** [Mrs4s/go-cqhttp#1454]
**环境信息**

go-cqhttp版本: 1.0.0rc1

**需要添加的功能内容**

我是一名老群主，群太多了嘛，然后管的累，然后嘛自己拿python对接go-cqhttp写群管机器人咯～

但是实际情况下，群中互骂的情况下一半都是语音聊天(然后别家的语音转文本API大多数付费)，然后QQ本身是提供了语音转文字的功能的，不知道**go-cqhttp能否支持一下语音转文字？**
感激不尽(鄙人小白一个，如有不当言论，请指正)

**Comment by zxz0415** [comment]
我想做这个issue，然后调用ffmpeg的时候也报了错，提示是 Invalid data found when processing input。大概是说我用brew安装的ffmpeg不支持amr格式编码的意思，经过尝试还没有找到解决办法。我想问下有没有同学知道怎么解决这个问题的。
**环境信息**
go-cqhttp版本：dev
ffmpeg版本：5.0.1
环境：mac 10.15.7

**Comment by wdvxdr1123** [comment]
@zxz0415 虽然接受到的语音文件后缀为 .amr ，但实际文件格式为 silk

**Comment by 1130600015** [comment]
> 

github有个repo解决了 amr转mp3的  实际amr是silk
