### ISSUE TITLE
[Bug]: 反向 Websocket,当对方重启后,websocket连接不上

### ISSUE THREAD

**Issue by dezhishen** [Mrs4s/go-cqhttp#1461]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc1

### 运行环境

Linux

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 使用docker运行
```
docker run --name -d --network=bridge silicer/go-cqhttp
```
```
docker run --name haruka-bot -d --network=bridge --network-alias=haruka-bot dezhishen/haruka-bot
```
###  配置反向websocket
```
  - ws-reverse:
      universal: ws://haruka-bot:8080/onebot/v11/ws
```
### 重启反向websocket的应用
```
docker restart haruka-bot 
```
### 日志
- go-cqhttp
```
....
[2022-04-09 07:59:26] [WARNING]: 向反向WS Universal服务器推送 Event 时出现错误: write tcp 172.21.0.23:47178->172.21.0.24:8080: use of closed network connection
[2022-04-09 07:59:26] [WARNING]: 向反向WS Universal服务器推送 Event 时出现错误: write tcp 172.21.0.23:47178->172.21.0.24:8080: use of closed network connection
....
```
-  haruka-bot 
```
...
04-09 15:59:28 [INFO] nonebot_plugin_apscheduler | Scheduler Started
04-09 15:59:37 [INFO] uvicorn | Application startup complete.
04-09 15:59:37 [INFO] uvicorn | Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
...
```

**可以看到haruka-bot已经启动**

### 期望的结果是什么？

websocket能够自动重连

### 实际的结果是什么？

websocket无法自动重连

#### 固定haruka-bot的ip
```
docker run .... --ip 172.21.0.24
```
- 结果**错误依然存在**
#### 使用ip连接haruka-bot
```
  - ws-reverse:
      universal: ws://172.21.0.24:8080/onebot/v11/ws
```
- 结果**错误依然存在**
#### 直接宿主机net网络模式
```
docker run --network host ... haruka-bot
docker run --network host ... go-cqhttp
```
```
  - ws-reverse:
      universal: ws://127.0.0.1:8080/onebot/v11/ws
```
- 结果**错误依旧存在**

**Comment by yangshiling** [comment]
原来不是我一个人啊，我还以为就我一个人，不过我是window的nb1

**Comment by dezhishen** [comment]
经过追查源码发现
https://github.com/Mrs4s/go-cqhttp/blob/a75f412b828ac26cb17a1e6d7522df7b6bb480a5/server/websocket.go#L282-L303
需要在配置文件中追加
```
  - ws-reverse:
      universal: ws://haruka-bot:8080/onebot/v11/ws
      reconnect-interval: 3000 # 单位毫秒
```
@yangshiling
