### ISSUE TITLE
[Bug]: termux，编译时出现ld.lld: error: unable to find library -lc错误

### ISSUE THREAD

**Issue by brokenpoems** [Mrs4s/go-cqhttp#1463]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

无

### 运行环境

UNIX (Android)

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

无

### 使用协议

无

### 重现步骤

在termux编译时出现了ld.lld: error: unable to find library -lc错误

### 期望的结果是什么？

编译成功

### 实际的结果是什么？

编译失败,报错

### 简单的复现代码/链接（可选）

```golang
使用termux
pkg install golang
git clone -b dev https://github.com/Mrs4s/go-cqhttp.git
cd go-cqhttp/
go build -ldflags "-s -w -extldflags '-static'"
```

### 日志记录（可选）

```golang
/data/data/com.termux/files/usr/lib/go/pkg/tool/android_arm64/link: running aarch64-linux-android-clang failed: exit status 1
ld.lld: error: unable to find library -lc
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by wdvxdr1123** [comment]
请使用CGO_ENABLED=0编译
