### ISSUE TITLE
[Bug]: 私聊戳一戳的时候target_id是0

### ISSUE THREAD

**Issue by dobilibili** [Mrs4s/go-cqhttp#1465]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [ ] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc1

### 运行环境

Ubuntu

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

3 | MacOS

### 重现步骤

使用MacOS协议登录机器人，然后打开和机器人的私聊界面，双击机器人头像，发现notify.Receiver 是0,但是我使用Ipad协议登录的时候，不会出现这个问题.
![image](https://user-images.githubusercontent.com/64294553/162617002-beaac087-4684-42f9-a249-3e7c4458b709.png)

### 期望的结果是什么？

notify.Receiver应该是机器人的QQ号

### 实际的结果是什么？

notify.Receiver是0

**Comment by MingxuanGame** [comment]
`MacOS`的私聊戳一戳数据包中不存在`uin_str2`，默认为0
可能的解决办法：
```go
if receiver == 0{
    receiver = c.Uin
}
```

**Comment by dobilibili** [comment]
好的，非常感谢您的建议！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月10日(星期天) 晚上8:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Mrs4s/go-cqhttp] [Bug]: 私聊戳一戳的时候target_id是0 (Issue #1465)





 
MacOS的私聊戳一戳数据包中不存在uin_str2，默认为0
 可能的解决办法：
 if receiver == 0{     receiver = c.Uin }
