### ISSUE TITLE
希望未来加入对emoji表情的CQ码解析

### ISSUE THREAD

**Issue by NumberSir** [Mrs4s/go-cqhttp#1467]
**环境信息**
Windows
go-cqhttp版本: v1.0.0-rc1

**需要添加的功能内容**
希望可以添加对emoji表情的CQ码解析，现在接收到信息中的emoji表情，在命令行显示出来的是方块乱码，也无法把这种乱码信息写入到数据库/本地文件等地方

**Comment by assassingyk** [comment]
emoji本身就是Unicode的吧，这有什么解析可言吗）

换一个支持unicode的terminal应该就行吧

**Comment by assassingyk** [comment]
![image](https://user-images.githubusercontent.com/55473115/171566509-e968c20c-de7f-4ae3-bc8a-d850c6b1cc63.png)

**Comment by wdvxdr1123** [comment]
emoji无需特殊处理
