### ISSUE TITLE
[Bug]: import cycle not allowed

### ISSUE THREAD

**Issue by issueye** [Mrs4s/go-cqhttp#1468]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

master

### 运行环境

Windows (64)

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

出现互相引用

base 模块
![image](https://user-images.githubusercontent.com/28434476/163119451-5161b352-8e24-4b80-9ff7-a0b2d55e6354.png)

global 模块
![image](https://user-images.githubusercontent.com/28434476/163119535-df90e93e-1b4e-4819-9327-a1a1413e0e0d.png)

### 期望的结果是什么？

master 版本编译就会出现

### 实际的结果是什么？

问题解决

**Comment by wdvxdr1123** [comment]
duplicate of #1412
