### ISSUE TITLE
[Bug]: 登录协议崩了

### ISSUE THREAD

**Issue by Qicloudgit** [Mrs4s/go-cqhttp#1469]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc1

### 运行环境

CentOS

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

登录协议崩了

### 期望的结果是什么？

期待尽快修复

### 实际的结果是什么？

现在新设备登录不上

### 简单的复现代码/链接（可选）

```golang
./go-cqhttp
提示二维码失效或登录环境非常用或存在危险，请保持登录地一致后再尝试
```

**Comment by corvo007** [comment]
可以稳定复现

**Comment by Yz1688** [comment]
![QQ截图20220415230824](https://user-images.githubusercontent.com/92705940/163665902-cbb350a0-3661-4b4e-b63b-92942beb7d79.jpg)
我也是这样

**Comment by discodyer** [comment]
自己电脑上可以正常登陆，在hk服务器上就不行，同样是ipad扫码登陆，device.json自动生成

**Comment by soy-saber** [comment]
我也是自己win10电脑上可以登录，在上海的centos7服务器不行

**Comment by ZnWillbur** [comment]
我自己的电脑能登陆，在上海的windows服务器不行

**Comment by Ink-33** [comment]
疑似风控加强

**Comment by Fader282** [comment]
我是在自己电脑和服务器上都能登录，但是两边一旦同时上线，bot就会被风控，很奇怪...

**Comment by HBcao233** [comment]
我也是自己电脑可以登，CentOS登不上

**Comment by pino889** [comment]
> 

这个怎么操作的

**Comment by synodriver** [comment]
一定是tx搞的鬼

**Comment by pino889** [comment]
您好，您的邮件我已经收到，我会尽快给您回复！祝工作顺利，心情愉快，谢谢！

**Comment by HBcao233** [comment]
自己电脑也登不了了，扫完码会报错
[2022-04-17 14:49:25] [ERROR]: Protocol -> parse incoming packet error: packet dropped
[2022-04-17 14:49:54] [ERROR]: Protocol -> sync channel error: Packet failed to sendPacket: connection closed
[2022-04-17 14:49:54] [INFO]: 登录成功 欢迎使用: 0 ω 0
[2022-04-17 14:49:54] [INFO]: 开始加载好友列表...
[2022-04-17 14:49:54] [FATAL]: 遇到错误: Packet failed to sendPacket: connection closed

CentOS上是扫码提示登录环境异常

**Comment by HBcao233** [comment]
可以在自己电脑上登上以后，把session.token复制到Centos上，这样就可以登了

**Comment by allofee** [comment]
> 可以在自己电脑上登上以后，把session.token复制到Centos上，这样就可以登了

复制了也不一定行，它会说恢复会话失败，继续走扫码登录流程

**Comment by AnsonSkywalker** [comment]
气死个人。在自己的电脑上可以登，一放到服务器上面登录就警告风控。扫码也照常警告拒绝登录。

**Comment by qiaokelidou** [comment]
有人尝试通过代理到服务器上再手机QQ扫码登录吗

**Comment by zangguojun** [comment]
这个我解决了 我也遇到这个问题 你只要在本地登录 然后把go-cqhttp生成的文件，原封不动的上传到服务器就行

**Comment by lowking** [comment]
我也是这样，今天没注意，在ipad上登录了qq，就把服务器上的顶掉了，之后扫码就登录不上了，提示“登录环境非常用或存在危险，请保持登录地一致后再尝试”😂

**Comment by freecodecampcdder** [comment]
我本地登录也登录不上。

**Comment by HMScygnet** [comment]
我通过在服务器上建立ss节点，然后在手机上开代理扫码解决了

**Comment by NepPure** [comment]
有没有办法强制用短信登陆绕过去，我安全中心把绑定的设备都删了，用协议1还是让我扫码

**Comment by freecodecampcdder** [comment]
> 没有办法强制用短信登陆绕过去，我安全中心把密码绑定的设备都删了，协议1还是让我扫

我是使用之自己的电脑使用go-cqhttp 登录上获取到一个token  （只要登录上就会生成）文件。拉到服务器即可登录了 你可以试试

**Comment by FYWinds** [comment]
疑似风控加强
目前验证成功的解决方案：服务器搭建代理，手机通过代理扫码

**Comment by xgbt** [comment]
本地登录成功后的 device 和 session 文件都复制到服务器上可解决。

**Comment by JHeyzo** [comment]
曲线救国方针：
手机挂爱加速代理扫码，跟服务器同一个区域就行。
我上海的华为云扫码成功了

**Comment by huang122124** [comment]
要是go-http在服务器上运行，解决方案：
1.在本地登录成功后的 device 和 session 文件都复制到服务器上可解决。
2.本地手机挂爱加速代理或其他代理，与服务器ip同一地区再进行扫码

**Comment by SkyAerope** [comment]
> 曲线救国方针： 手机挂爱加速代理扫码，跟服务器同一个区域就行。 我上海的华为云扫码成功了

我广州百度云也成功了

**Comment by as56765** [comment]
> 曲线救国方针： 手机挂爱加速代理扫码，跟服务器同一个区域就行。 我上海的华为云扫码成功了

成都腾讯云成功了，老哥稳

**Comment by pino889** [comment]
您好，您的邮件我已经收到，我会尽快给您回复！祝工作顺利，心情愉快，谢谢！

**Comment by chaosChildrens** [comment]
我是日本阿里云，也有这个问题，然后服务器新增了vpn服务器，手机挂上去出国扫码成功了。而且我之前只能私聊，群里都是封控，现在群里也能用了。属于因祸得福了。

**Comment by K0zero** [comment]
> 要是go-http在服务器上运行，本人总结的解决方案： 1.在本地登录成功后的 device 和 session 文件都复制到服务器上可解决。 2.本地手机挂爱加速代理或其他代理，与服务器ip同一地区再进行扫码. 3.暴力去除安全检查（亲测有效）： --手机登入账号； --进入”账号安全“->“登录设备管理”->关闭”登录保护“； --进入”账号安全“->关闭”登录安全检查"； 关闭后如仍要求扫码可重复1,2步解决

请问go-http在本机登陆之后，device和session文件在哪里生成的啊，又要放到服务器的哪个文件路径呀？

**Comment by huang122124** [comment]
同样，都在你的go-cqhttp的文件夹里,路径都一样




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mrs4s/go-cqhttp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月1日(星期三) 上午10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mrs4s/go-cqhttp] [Bug]: 登录协议崩了 (Issue #1469)





  
要是go-http在服务器上运行，本人总结的解决方案： 1.在本地登录成功后的 device 和 session 文件都复制到服务器上可解决。 2.本地手机挂爱加速代理或其他代理，与服务器ip同一地区再进行扫码. 3.暴力去除安全检查（亲测有效）： --手机登入账号； --进入”账号安全“-&gt;“登录设备管理”-&gt;关闭”登录保护“； --进入”账号安全“-&gt;关闭”登录安全检查"； 关闭后如仍要求扫码可重复1,2步解决
  
请问go-http在本机登陆之后，device和session文件在哪里生成的啊，又要放到服务器的哪个文件路径呀？

**Comment by K0zero** [comment]
> 

为什么我在我ubuntu服务器安装之后没有go-cqhttp的文件夹，里面也只有data和logs两个文件夹，没找到日志里提到的device.json和什么session文件

**Comment by expliyh** [comment]
> > 
> 
> 为什么我在我ubuntu服务器安装之后没有go-cqhttp的文件夹，里面也只有data和logs两个文件夹，没找到日志里提到的device.json和什么session文件

如果是用deb安装的话这两个文件在用户目录

**Comment by wdvxdr1123** [comment]
现在可以使用滑块登录

**Comment by fallenleavesguy** [comment]
滑块登录要写什么配置吗，更新了，还是二维码

**Comment by SEANPNEX** [comment]
在本地(ubuntu 21.10)登陆后将session.token,device.json,config.yml上传到云端go-cqhttp目录下后解决了这个问题

**Comment by dan3577** [comment]
> ### 请确保您已阅读以上注意事项，并勾选下方的确认框。
> * [x]  我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
> * [x]  我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
> * [x]  我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
> * [x]  我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）
> 
> ### go-cqhttp 版本
> v1.0.0-rc1
> 
> ### 运行环境
> CentOS
> 
> ### 运行架构
> AMD64
> 
> ### 连接方式
> HTTP
> 
> ### 使用协议
> 0 | iPad
> 
> ### 重现步骤
> 登录协议崩了
> 
> ### 期望的结果是什么？
> 期待尽快修复
> 
> ### 实际的结果是什么？
> 现在新设备登录不上
> 
> ### 简单的复现代码/链接（可选）
> ```go
> ./go-cqhttp
> 提示二维码失效或登录环境非常用或存在危险，请保持登录地一致后再尝试
> ```
> 
> ### 日志记录（可选）
> _No response_
> 
> ### 补充说明（可选）
> _No response_

本地鸡扫码提示：扫码失败，已失效或者存在异常。
二维码都是刚更新的，只是手机在公司远程扫家里的主机

**Comment by pino889** [comment]
您好，您的邮件我已经收到，我会尽快给您回复！祝工作顺利，心情愉快，谢谢！

**Comment by HBcao233** [comment]
> 但是我是本地登录出现这种情况咋办啊，急啊！！！

连同一网络

**Comment by GreenBudsOnPotato** [comment]
> > 但是我是本地登录出现这种情况咋办啊，急啊！！！
> 
> 连同一网络

笑了，在同一网络上的（无奈）

**Comment by NoaDX** [comment]
搞chatgpt qq机器人，卡在这一步
本地登陆也没用（恼）
