### ISSUE TITLE
反向WS对_async的支持

### ISSUE THREAD

**Issue by wfjsw** [Mrs4s/go-cqhttp#147]
**环境信息**
go-cqhttp版本: 322b70c
运行环境: linux_amd64
连接方式: 反向WS(Universal)

**bug内容**
使用反向WS的统一接口调用任何API时均体验到时间逐渐增加的延迟。延迟发生过程中控制台无输出。
使用 HTTP API 接口则无上述延迟问题。
期间事件上报并无任何问题。

**复现方法**
借助 nonebot/aiocqhttp 连接 Universal Reverse Websocket 接口调用任意 API。有超时错误。

**Comment by Mrs4s** [comment]
#122

**Comment by wfjsw** [comment]
Not duplicate of #122. 

使用的API均没有任何理由阻塞。不过测试发现不是go-cqhttp的问题。
