### ISSUE TITLE
发图的时候，图片会有小概率的情况裂开

### ISSUE THREAD

**Issue by AkiraXie** [Mrs4s/go-cqhttp#149]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.20
运行环境: windows_i386
连接方式: 反向WS

**bug内容**
图片会有时候加载缓慢甚至裂开。

**复现方法**
bot在发图的时候，不管是base64方式，file方式还是url方式，都会有很小的概率复现这个bug。

**Comment by Mrs4s** [comment]
#65
