### ISSUE TITLE
[Bug]: 远程主机拒绝连接，求大佬救救（已经解决）

### ISSUE THREAD

**Issue by Enclaw** [Mrs4s/go-cqhttp#1499]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc1 

### 运行环境

Windows (64)

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

在一个Bot里的教程里填的ws://127.0.0.1:8080/onebot/v11/ws/

### 期望的结果是什么？

成功

### 实际的结果是什么？

显示连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: read tcp 127.0.0.1:58335->127.0.0.1:8080: wsarecv: An existing connection was forcibly closed by the remote host.

### 补充说明（可选）

是不是因为我的nonebot配置有问题，求大佬帮我一下

**Comment by TheresaQWQ** [comment]
日志和具体复现过程呢？

**Comment by Enclaw** [comment]
日志是这样的
![image](https://user-images.githubusercontent.com/105723386/168813729-f3186484-0c01-4051-a466-df41b35508cb.png)
然后复现过程就是把config.yml的反向地址改为ws://127.0.0.1:8080/onebot/v11/ws/，其他的没怎么动，py环境是3.10

**Comment by ishkong** [comment]
你运行bot了吗？

**Comment by Enclaw** [comment]
运行bot后是这样的
![image](https://user-images.githubusercontent.com/105723386/168814375-bd610056-8c17-4ff8-b8ae-b90cac5a155d.png)

**Comment by Enclaw** [comment]
如果实在不行的话我就换一个bot吧

**Comment by TheresaQWQ** [comment]
> 运行bot后是这样的 ![image](https://user-images.githubusercontent.com/105723386/168814375-bd610056-8c17-4ff8-b8ae-b90cac5a155d.png)

很显然，你程序没运行起来

**Comment by ishkong** [comment]
很显然你的后端并没有正常运行，这并不是go-cqhttp的问题，请前往相关项目下提交issue

**Comment by fkx4-p** [comment]
Please close the issue instead of changing the issue. Thx for your cooperation.
