### ISSUE TITLE
device文件配置

### ISSUE THREAD

**Issue by chenxuan353** [Mrs4s/go-cqhttp#15]
希望能简单说明一下……

**Comment by masnn** [comment]
device自动生成，没必要改

**Comment by chenxuan353** [comment]
主要是存在mirai字段，有点担心()

**Comment by masnn** [comment]
你也不会改，我也不会改，him188跑路了基本没人知道这些是啥

**Comment by chenxuan353** [comment]
可太难了

**Comment by chenxuan353** [comment]
https://source.android.google.cn/compatibility/android-cdd?hl=zh-cn#2_6_tablet_requirements

**Comment by chenxuan353** [comment]
finger_print->FINGERPRINT(页面内搜索)
https://source.android.google.cn/compatibility/android-cdd?hl=zh-cn#2_6_tablet_requirements
经过测试，修改之后登录成功，但是对登录显示的设备名无影响(修改了display、finger_print)，在登录记录里仍然显示mirai。
