### ISSUE TITLE
求易语言版API例子

### ISSUE THREAD

**Issue by LLZWWY** [Mrs4s/go-cqhttp#1503]
那啥 现在没易语言版API例子了吗？

**Comment by synodriver** [comment]
你可能在找：酷喵

**Comment by LLZWWY** [comment]
> 你可能在找：酷喵

以前确实有一套cqhttp的易语言API啊

**Comment by synodriver** [comment]
> > 你可能在找：酷喵
> 
> 以前确实有一套cqhttp的易语言API啊

那个是mirai-http协议的，不是onebot协议的

**Comment by LLZWWY** [comment]
> > > 你可能在找：酷喵
> > 
> > 
> > 以前确实有一套cqhttp的易语言API啊
> 
> 那个是mirai-http协议的，不是onebot协议的

这个具体协议清楚，但当时我下载的release里的版本然后用的那套易语言的写了个群消息管理确实能用。那套源码被弄丢了找不到了

**Comment by yihais** [comment]
调用http 还要例子嘛？
