### ISSUE TITLE
[Bug]: 网络URL无法发送图片，任何图片都是 GET“URL”Forwarding failure

### ISSUE THREAD

**Issue by Warrior-li** [Mrs4s/go-cqhttp#1507]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc1

### 运行环境

CentOS

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

使用网络url进行图片的发送。

### 期望的结果是什么？

将图片顺利发送出去

### 实际的结果是什么？

任何图片都为GET“URL”Forwarding failure，本地环境已经使用浏览器，curl，postman进行测试过了

**Comment by Warrior-li** [comment]
![image](https://user-images.githubusercontent.com/58515952/169701622-e1a5fd20-1256-40dd-a1d8-2bbb06b3c899.png)

**Comment by Warrior-li** [comment]
经过测试，为URl的语音也不行

**Comment by Ink-33** [comment]
尝试一下使用`curl`，`wget`等工具直接访问url
似乎是因为端口未放行

**Comment by Warrior-li** [comment]
> 尝试一下使用`curl`，`wget`等工具直接访问url 似乎是因为端口未放行

curl和wget工具都进行尝试过了，都能正确的得到或者下载图片，我配置的代理端口是本地的8118，监测也为放行

**Comment by Warrior-li** [comment]
> 似乎是因为端口未放行

已经查到错误，可以关闭了，打扰您时间了
