### ISSUE TITLE
[Bug]: 登录环境非常用或存在危险,请保持登录地一致后再尝试

### ISSUE THREAD

**Issue by Bearlele** [Mrs4s/go-cqhttp#1508]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

cfa35b6

### 运行环境

Linux

### 运行架构

x86

### 连接方式

WebSocket (正向)

### 使用协议

1 | Android Phone

### 重现步骤

首次登陆扫码，手机提示“登录环境非常用或存在危险,请保持登录地一致后再尝试”，服务器在广州，使用过ipad和android phone协议都是一样的结果

### 期望的结果是什么？

成功扫码进行登录

### 实际的结果是什么？

登录环境非常用或存在危险,请保持登录地一致后再尝试

**Comment by Ink-33** [comment]
duplicated #1469
