### ISSUE TITLE
[Bug]: Arm Linux开发板下登陆异常

### ISSUE THREAD

**Issue by A2Sumie** [Mrs4s/go-cqhttp#1512]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

rc1

### 运行环境

CentOS

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

WebSocket (反向)

### 使用协议

1 | Android Phone

### 重现步骤

树莓派400，CentOS 7
调整device.json等网络环境解除设备锁限制后登陆即可复现
*并没有去试dev版，抱歉，晚上有ddl不想再折腾了

### 期望的结果是什么？

顺利登陆并开始接收消息

### 实际的结果是什么？

登录成功（计划进行扫码协助的手机被踢出登陆）后立刻报错退出，日志如下
[root@SoftBank go-cqhttp]# ./go-cqhttp
[2022-05-24 20:52:39] [INFO]: 当前版本:v1.0.0-rc1
[2022-05-24 20:52:39] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2022-05-24 20:52:39] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2022-05-24 20:52:44] [INFO]: 开始尝试登录并同步消息...
[2022-05-24 20:52:44] [INFO]: 使用协议: Android Phone
[2022-05-24 20:52:46] [INFO]: Protocol -> connect to server: 43.135.106.161:8080
panic: runtime error: makeslice: len out of range

goroutine 67 [running]:
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadBytes(...)
	github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/reader.go:40
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).readSSOFrame(0x400047ec40, 0x40007561e0, {0x40000b2188, 0x169, 0x170})
	github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/internal/network/response.go:62 +0x170
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).ReadResponse(0x400047ec40, {0x4000552820, 0x18c, 0x18c})
	github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/internal/network/response.go:51 +0x310
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0x4000242580)
	github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:295 +0x188
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).connect.func1
	github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:120 +0x3f4

### 日志记录（可选）

```golang
[root@SoftBank go-cqhttp]# ./go-cqhttp
[2022-05-24 20:52:39] [INFO]: 当前版本:v1.0.0-rc1
[2022-05-24 20:52:39] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2022-05-24 20:52:39] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2022-05-24 20:52:44] [INFO]: 开始尝试登录并同步消息...
[2022-05-24 20:52:44] [INFO]: 使用协议: Android Phone
[2022-05-24 20:52:46] [INFO]: Protocol -> connect to server: 43.135.106.161:8080
panic: runtime error: makeslice: len out of range

goroutine 67 [running]:
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadBytes(...)
	github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/reader.go:40
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).readSSOFrame(0x400047ec40, 0x40007561e0, {0x40000b2188, 0x169, 0x170})
	github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/internal/network/response.go:62 +0x170
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).ReadResponse(0x400047ec40, {0x4000552820, 0x18c, 0x18c})
	github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/internal/network/response.go:51 +0x310
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0x4000242580)
	github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:295 +0x188
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).connect.func1
	github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:120 +0x3f4
```

### 补充说明（可选）

在一台debian10的armv7板（华硕tinker board）问题类似，使用armv7 rc1
[2022-05-24 13:06:37] [INFO]: 当前版本:v1.0.0-rc1
[2022-05-24 13:06:37] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2022-05-24 13:06:37] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2022-05-24 13:06:42] [INFO]: 开始尝试登录并同步消息...
[2022-05-24 13:06:42] [INFO]: 使用协议: Android Phone
[2022-05-24 13:06:43] [INFO]: Protocol -> connect to server: 43.135.106.161:8080
panic: runtime error: makeslice: len out of range

goroutine 52 [running]:
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadBytes(...)
	github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/reader.go:40
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).readSSOFrame(0x185c198, 0x1d39170, {0x1c04c08, 0x25a9, 0x25b0})
	github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/internal/network/response.go:62 +0x17c
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).ReadResponse(0x185c198, {0x1c00000, 0x25cc, 0x25cc})
	github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/internal/network/response.go:51 +0x360
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0x187c000)
	github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:295 +0x17c
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).connect.func1
	github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:120 +0x3b8

**Comment by wdvxdr1123** [comment]
see #1439
