### ISSUE TITLE
[Bug]: uploadLocalImage中mime.checkImage有几率panic

### ISSUE THREAD

**Issue by fzls** [Mrs4s/go-cqhttp#1514]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

810c781c25aed4e7de2361307994be1c99bb8555

### 运行环境

Ubuntu

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

机器人运行一段时间后，在回复一个图片时出现了panic，具体堆栈可见后面日志

### 期望的结果是什么？

不会panic，或者出错了可以刷个日志但不退出

### 实际的结果是什么？

程序退出运行了

### 日志记录（可选）

```golang
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x971479]

goroutine 141128 [running]:
github.com/Mrs4s/go-cqhttp/modules/mime.scan({0x0, 0x0})
        /root/qq_robot_go/modules/mime/mime.go:20 +0x39
github.com/Mrs4s/go-cqhttp/modules/mime.checkImage({0x0?, 0x0?})
        /root/qq_robot_go/modules/mime/mime.go:34 +0x34
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).uploadLocalImage(0xc0005c2000, {0x7?, 0xc00030c000?, 0x7a?}, 0xc00027e480)
        /root/qq_robot_go/coolq/bot.go:159 +0x10d
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).uploadMedia.func1()
        /root/qq_robot_go/coolq/bot.go:223 +0x56
github.com/Mrs4s/go-cqhttp/coolq.(*worker).do.func1()
        /root/qq_robot_go/coolq/bot.go:141 +0x5a
created by github.com/Mrs4s/go-cqhttp/coolq.(*worker).do
        /root/qq_robot_go/coolq/bot.go:139 +0x85
```

**Comment by wdvxdr1123** [comment]
堆栈有点短， 无法推断panic的原因

**Comment by Mrs4s** [comment]
总之先把异常处理了免得panic

**Comment by moian98** [comment]
我也遇到了同样的情况
