### ISSUE TITLE
call get_group_info() to update a new created group or new entered group will throw Exceptions

### ISSUE THREAD

**Issue by ChateauXiao** [Mrs4s/go-cqhttp#152]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.19
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
create a new qq group, then ask bot to get in the group. when the bot call bot.get_group_info(group_id=[new qq group id])
it will throw an Exception, even if you restart the go-cqhttp process,  this issue is still existed.

**复现方法**

**Comment by Mrs4s** [comment]
more detail needed (log ,console output)

**Comment by ChateauXiao** [comment]
mlist = await bot_.get_group_member_list(group_id=gobj.group_id)

    for mdict in mlist:
          ...

here mlist is NoneType, get_group_member_list() can not get any from this call()

with log here:
argument of type 'NoneType' is not iterable
