### ISSUE TITLE
添加转发节点参数 nickname

### ISSUE THREAD

**Issue by clacknya** [Mrs4s/go-cqhttp#1520]
**环境信息**
Linux x64

go-cqhttp版本: [v1.0.0-rc1](https://github.com/Mrs4s/go-cqhttp/releases/tag/v1.0.0-rc1)

**需要添加的功能内容**

在 [aiocqhttp](https://github.com/nonebot/aiocqhttp) 中 转发节点 的参数是使用 `nickname` 标识昵称，而 go-cqhttp 则使用 `name`，因此直接调用 `node_custom` 创建的节点进行转发会因为缺少参数报错。

https://github.com/nonebot/aiocqhttp/blob/3e4fcaedee96a98b4d6dfb07ebadc04db710e06f/aiocqhttp/message.py#L375-L385
``` python
    def node_custom(user_id: int,
                    nickname: str,
                    content: Message_T) -> 'MessageSegment':
        """合并转发自定义节点。"""
        if not isinstance(content, (str, MessageSegment, Message)):
            content = Message(content)
        return MessageSegment(type_='node', data={
            'user_id': str(user_id),
            'nickname': nickname,
            'content': str(content),
        })
```

希望能添加对 `nickname` 的兼容

**Comment by assassingyk** [comment]
user_id和uin这个参数其实也不统一，不过这个好像做了兼容倒是
