### ISSUE TITLE
[Bug?]: "48964"为什么会发不出去

### ISSUE THREAD

**Issue by Zzz2333** [Mrs4s/go-cqhttp#1525]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix2

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

必定能重现。使用go-cqhttp.exe登录账号，然后调用发送群消息的接口send_group_msg，发送“48964”这段内容，会发现无法发送，发送其它内容是没有问题的。最重要的是，使用安卓手机，官方客户端发送“48964”是可以的。这就很奇怪了，要说和谐，为啥官方客户端都没被和谐？
协议从0-5（除了4-企点协议）外都测过，都是一样的。
调用接口的返回值：
{
    "data": null,
    "msg": "SEND_MSG_API_ERROR",
    "retcode": 100,
    "status": "failed",
    "wording": "请参考 go-cqhttp 端输出"
}
go-cqhttp.exe 上显示的日志如下图：
![image](https://user-images.githubusercontent.com/28297857/171994380-a213b05a-bb56-4068-8b43-0ed0a7c4783f.png)

### 期望的结果是什么？

能够正常发送消息

### 实际的结果是什么？

无法发送

**Comment by synodriver** [comment]
你猜今天是什么日子，不仅发不出去，等下你bot还得寄

**Comment by Ink-33** [comment]
https://forums.go-cqhttp.org/

**Comment by Akegarasu** [comment]
这数字为什么发不出去你自己心理没有点 `b-tree` 吗

**Comment by Zzz2333** [comment]
？？？
实在不明白，这个有什么问题？
而且你们说是被和谐的话，官方客户端为什么反而能发？

**Comment by synodriver** [comment]
官方客户端钓鱼呢（

**Comment by FeiBam** [comment]
这是真来提交ISSUSE 还是来钓鱼啊

**Comment by Mrs4s** [comment]
服务端对Bot和用户的风控是不同的, 有差别很正常
