### ISSUE TITLE
[Bug]: 频道发送图片

### ISSUE THREAD

**Issue by Gingmzmzx** [Mrs4s/go-cqhttp#1538]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0 rc2

### 运行环境

CentOS

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

向频道发送图片时报错，且gocq退出

### 期望的结果是什么？

正常发送图片

### 实际的结果是什么？

![超级截屏_20220614_163130](https://user-images.githubusercontent.com/49107602/173532396-1e302562-4ab8-4557-a733-07a416efdeec.png)

**Comment by Mrs4s** [comment]
已修复
