### ISSUE TITLE
[Bug]: 带换行符的自定义合并转发消息无法发送

### ISSUE THREAD

**Issue by NotStuButPid** [Mrs4s/go-cqhttp#1549]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc2

### 运行环境

Windows (64)

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

发送一条使用带换行符的自定义消息的合并转发消息

### 期望的结果是什么？

发送一条含有带换行符的自定义消息的合并转发消息

### 实际的结果是什么？

没有发送，go-cqhttp也没有报错，响应数据为：
{"data":null,"msg":"","retcode":100,"status":"failed","wording":""}

### 简单的复现代码/链接（可选）

```golang
http://127.0.0.1:5700/send_group_forward_msg?group_id=XXX&messages='[{"type": "node","data": {"name": "自定义发送者","uin": "10086","content": "我是自定义消息\n哦不是换行符","seq": "5123","time": "3376656000"}}]
```

**Comment by wdvxdr1123** [comment]
请使用POST + Content-Type: application/json 调用此函数

**Comment by OhnkytaBlabdey** [comment]
> 请使用POST + Content-Type: application/json 调用此函数

go-cqhttp 版本
v1.0.0-rc4

运行环境
Debian 11

运行架构
SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux

连接方式
正向WebSocket

使用协议
Android Phone


请问正向websocket可以使用该接口吗

我发送了请求

```
{
  action: "send_group_forward_msg",
  params: {
    group_id: xx（群号）,
    message:[{
      type: "node",
      data: {
        name: "消息发送者A",
        uin: 10086,
        content: "111",
      }]
    }
  },
}
```
但是我得到的响应是
```
{"data":null,"msg":"","retcode":100,"status":"failed","wording":""}
```

**Comment by Ink-33** [comment]
> 
> 
> 
> > 请使用POST + Content-Type: application/json 调用此函数
> 
> go-cqhttp 版本
> v1.0.0-rc4
> 
> 运行环境
> Debian 11
> 
> 运行架构
> SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux
> 
> 连接方式
> 正向WebSocket
> 
> 使用协议
> Android Phone
> 
> 
> 请问正向websocket可以使用该接口吗
> 
> 我发送了请求
> 
> ```
> {
>   action: "send_group_forward_msg",
>   params: {
>     group_id: xx（群号）,
>     message:[{
>       type: "node",
>       data: {
>         name: "消息发送者A",
>         uin: 10086,
>         content: "111",
>       }]
>     }
>   },
> }
> ```
> 但是我得到的响应是
> ```
> {"data":null,"msg":"","retcode":100,"status":"failed","wording":""}
> ```

https://docs.go-cqhttp.org/api/#%E5%8F%91%E9%80%81%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91-%E7%BE%A4%E8%81%8A
![Screenshot_2023-03-17-11-34-02-248_com.tencent.mobileqq-edit.jpg](https://user-images.githubusercontent.com/51873347/225808131-ac551e5d-e226-4725-bc52-4ec260b6a019.jpg)
