### ISSUE TITLE
[Bug]: go-cqhttp update 更新版本时，提示 checksum 失败

### ISSUE THREAD

**Issue by jianmj** [Mrs4s/go-cqhttp#1553]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc2

### 运行环境

CentOS

### 运行架构

AMD64

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

```bash
cd /path/to/go-cqhttp/
./go-cqhttp update https://github.rc1844.workers.dev
```

### 期望的结果是什么？

更新成功

### 实际的结果是什么？

![image](https://user-images.githubusercontent.com/19400782/175464879-16183ecc-b3dd-470a-8178-5b0635191f18.png)

### 日志记录（可选）

```golang
[2022-06-24 12:35:34] [INFO]: 正在检查更新. 
[2022-06-24 12:35:34] [INFO]: 当前最新版本为 v1.0.0-rc3 
[2022-06-24 12:35:34] [WARNING]: 是否更新(y/N):  
y
[2022-06-24 12:35:36] [INFO]: 正在更新,请稍等... 
[2022-06-24 12:37:46] [ERROR]: checksum 失败! 
[2022-06-24 12:37:46] [INFO]: 按 Enter 继续....
```

**Comment by wdvxdr1123** [comment]
这是网络传输错误， 不是BUG
