### ISSUE TITLE
[Bug]: 和 efb-qq-slave 搭配进行消息转发时，无法转发自己的消息

### ISSUE THREAD

**Issue by jz8132543** [Mrs4s/go-cqhttp#1554]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc2

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

3 | MacOS

### 重现步骤

我使用 efb-qq-slave 并以 go-cqhttp 为客户端完成 QQ 和 TG 之间消息的转发
在QQ官方手机客户端给任意联系人发送消息

### 期望的结果是什么？

在 TG 中我能看到我给联系人发送的消息

### 实际的结果是什么？

在 TG 中没有我给联系人发送的消息

**Comment by Mrs4s** [comment]
缺少信息, 无法判断是不是 gocq 的问题

**Comment by jz8132543** [comment]
非常感谢您的帮助！
我查看日志
```
收到好友{对方昵称}({对方QQ号}) 的消息: 收不到 (224618622)
收到好友 {我的昵称}({我的QQ号}) 的消息: 哥你随便回我点什么 (-981288485)
```
我猜测可能是目前的信息不足以判断是我在发给谁。我会给 efb-qq-slave 提 issue，如果您有什么想法，欢迎交流。
最后谢谢您对这个问题的关注。
