### ISSUE TITLE
[Bug]: send_private_forward_msg 私聊发送的合并转发中的图片如果使用 [CQ:image,file=xxx.image] 形式则会在 Windows 上无法查看

### ISSUE THREAD

**Issue by Tsuk1ko** [Mrs4s/go-cqhttp#1558]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

发送这样的合并转发

```
[
  {
    "type": "node",
    "data": {
      "name": "xxx",
      "uin": "123",
      "content": "[CQ:image,file=yyy.image]"
    }
  }
]
```

即相当于将收到的图片通过 `file=hash.image` 的形式发送

### 期望的结果是什么？

能够正常显示图片

### 实际的结果是什么？

在 Windows 中无法查看
![image](https://user-images.githubusercontent.com/24877906/175771305-26baff77-7dce-4179-9820-e6ad5943faac.png)

在安卓中正常

其他平台由于 #1557 而无法测试

`send_group_forward_msg` 则是完全正常的

### 日志记录（可选）

```golang
日志中无警告或错误
```

**Comment by Akegarasu** [comment]
已修复，请测试最新的`actions`版本
