### ISSUE TITLE
api: 删除,更新以及查看群公告

### ISSUE THREAD

**Issue by Weltolk** [Mrs4s/go-cqhttp#1564]
**环境信息**

go-cqhttp版本: [v1.0.0-rc3](https://github.com/Mrs4s/go-cqhttp/releases/tag/v1.0.0-rc3)

**需要添加的功能内容**

删除,更新以及查看群公告

**Comment by Akegarasu** [comment]
更新公告本质上是创建了新的公告
查看群公告已经有了，`_get_group_notice`
删除群公告已经pr，请等待合并[MiraiGo](https://github.com/Mrs4s/MiraiGo/pull/284)

**Comment by ishkong** [comment]
> > 文档不是很全
> 
> 请问还有什么方法可以查看api呀?读源码吗?

在 ishkong/go-cqhttp-docs 提交issue，写明你认为已经有但是文档未更新的api，主动pr或者等待有缘人pr
