### ISSUE TITLE
[建议]建议在gitee添加国内镜像

### ISSUE THREAD

**Issue by axty666** [Mrs4s/go-cqhttp#1565]
**环境信息**

go-cqhttp版本: 

**需要添加的功能内容**

1.通过 [这里](https://gitee.com/projects/import/url) 创建gitee上的gocqhttp国内镜像
2.添加一项可选的设置，用来选择通过github还是gitee更新
（使用国内的vps进行更新/下载时速度很慢 耗时很长 体验不是太好）

**Comment by s2828** [comment]
建议你使用vpn 这种东西整到国内有点危险 不要把作者往火坑里推

**Comment by yanyongyu** [comment]
gitee现在需要**实名**并经过**平台审核**才能公开仓库
