### ISSUE TITLE
[Bug]: 过滤message_type时，meta_event也被过滤

### ISSUE THREAD

**Issue by moxidev** [Mrs4s/go-cqhttp#1571]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

Windows (64)

### 运行架构

ARM [32] (别名：AArch32 / ARMv7）

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

1. 设置过滤器内容为

`{
    "message_type": "guild"
}`

2. 启动go-cqhttp
3.  登录
4. 收到事件 出现问题

### 期望的结果是什么？

meta数据可以正常上报或者可选过滤

### 实际的结果是什么？

meta_event也被过滤
![image](https://user-images.githubusercontent.com/59305689/177142696-1b3f0a7a-fe10-44b8-afeb-6046a0cd0a0c.png)

**Comment by Akegarasu** [comment]
[文档](https://github.com/Mrs4s/go-cqhttp/blob/master/docs/EventFilter.md)中有写出，`事件过滤器会处理所有事件(包括心跳事件在内的元事件),请谨慎使用！！`
非bug，请自行添加心跳事件的过滤

**Comment by moxidev** [comment]
> [文档](https://github.com/Mrs4s/go-cqhttp/blob/master/docs/EventFilter.md)中有写出，`事件过滤器会处理所有事件(包括心跳事件在内的元事件),请谨慎使用！！` 非bug，请自行添加心跳事件的过滤

好吧这是我的疏忽，但是主观上message_type想成了qq协议的message而不是ws
