### ISSUE TITLE
支持解析红包吗

### ISSUE THREAD

**Issue by leinlin** [Mrs4s/go-cqhttp#1579]
**环境信息**

go-cqhttp版本: 

**需要添加的功能内容**

**Comment by super1207** [comment]
![image](https://user-images.githubusercontent.com/30586004/178090042-7879b569-cdd4-4917-bef3-5a16a10b5b8c.png)
看起来能收到红包消息，只是不能发，也不能领

**Comment by ishkong** [comment]
只能收到有红包消息，及口令等，不会支持发红包和领取红包，如有需要，请使用其它实现

**Comment by xuxin1** [comment]
@ishkong 有推荐方法吗？🐸
