### ISSUE TITLE
希望添加猜拳魔法表情

### ISSUE THREAD

**Issue by yuyuko233** [Mrs4s/go-cqhttp#1589]
**环境信息**

go-cqhttp版本: 
1.0.0-rc3
**需要添加的功能内容**

希望支持猜拳魔法表情

**Comment by SlightDust** [comment]
骰子好像有了？
![image](https://user-images.githubusercontent.com/53001305/179328121-d089d8a4-81c6-4ccd-9407-a689193dbf50.png)

**Comment by yuyuko233** [comment]
> 骰子好像有了？
> ![image](https://user-images.githubusercontent.com/53001305/179328121-d089d8a4-81c6-4ccd-9407-a689193dbf50.png)
> 

好像确实有了， 我是看文档上写着暂不支持........

**Comment by MingxuanGame** [comment]
猜拳已支持
[CQ:rps]
[CQ:rps,value=0]
0 石头
1 剪刀
2 布
支持版本为 rc2
