### ISSUE TITLE
event error: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tangwenjin** [Mrs4s/go-cqhttp#159]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.10
运行环境: windows_amd64

**bug内容**
开启或关闭群禁言时出错如图错误信息
![image](https://user-images.githubusercontent.com/23651148/90943872-64ec2100-e44e-11ea-9eb5-31e0d6607a70.png)
![image](https://user-images.githubusercontent.com/23651148/90943888-78978780-e44e-11ea-9ffa-3171c90b0e73.png)

**复现方法**

**Comment by Mrs4s** [comment]
已修复
