### ISSUE TITLE
[Bug]: Protocol -> sendPacket msg error: 46

### ISSUE THREAD

**Issue by RisingInIris2017** [Mrs4s/go-cqhttp#1596]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

36bf579

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

启动 go-cqhttp 本身，和 Nonebot 程序。
发送在 Nonebot 中注册的 Command，有些 Command 可以正常响应，
而有些则会出现 Nonebot 中无报错，而 go-cqhttp 报错 `Protocol -> sendPacket msg error: 46` 的情况，
随后 go-cqhttp 提示“发送失败，可能已被风控”。

开启强制分片发送、重新登录等方法都尝试过，不能解决问题。
上述报错仍会不稳定地复现。

### 期望的结果是什么？

不论被什么命令所调用，Bot 总可以稳定发送回复。

### 实际的结果是什么？

有些时候可以发送，有些时候不会。
机器人刚刚重启后的前几条消息比较稳定，多发几条消息就开始出现上述报错。

### 日志记录（可选）

```golang
https://paste.ubuntu.com/p/y2xrXHMFpq/
```

### 补充说明（可选）

已在 1.0.0-rc3 和 36bf579 两个版本上测试过，结果相同。
似乎 https://github.com/Mrs4s/go-cqhttp/issues/1487 的问题尽管已经 Closed，但并未解决。

**Comment by BobLiu0518** [comment]
我刚刚也遇到了这个问题（害怕

**Comment by BobLiu0518** [comment]
刚刚测试了一下，用自己的设备也发不出消息，疑似被腾讯风控

**Comment by madsvenn** [comment]
我发送xml消息的时候也出现这种情况

**Comment by tianpanyu123** [comment]
这并不是一个bug...这是腾讯的正常风控 可以在安全中心查到被限制

**Comment by lclbm** [comment]
#1487

**Comment by RisingInIris2017** [comment]
> 这并不是一个bug...这是腾讯的正常风控 可以在安全中心查到被限制

可以问一下是怎么查的吗？我用我这个bot账号登录安全中心，没有任何风险提示，还顺利改了密码，重新登录go-cqhttp仍然可以复现我issue中描述的问题

**Comment by xinyi-cherry** [comment]
> > 这并不是一个bug...这是腾讯的正常风控 可以在安全中心查到被限制
> 
> 可以问一下是怎么查的吗？我用我这个bot账号登录安全中心，没有任何风险提示，还顺利改了密码，重新登录go-cqhttp仍然可以复现我issue中描述的问题

手机登录QQ，在群里发一条消息，如果发不出去然后下面显示了一行点击检测啥的，点进去就可以了，如果没有就打开设置->账号安全->QQ安全中心->联系客服->账号->QQ功能检测，里面就可以解qwq（还要身份证就离谱）

**Comment by xinyi-cherry** [comment]
> > 这并不是一个bug...这是腾讯的正常风控 可以在安全中心查到被限制
> 
> 可以问一下是怎么查的吗？我用我这个bot账号登录安全中心，没有任何风险提示，还顺利改了密码，重新登录go-cqhttp仍然可以复现我issue中描述的问题

手机登录QQ，在群里发一条消息，如果发不出去然后下面显示了一行点击检测啥的，点进去就可以了，如果没有就打开设置->账号安全->QQ安全中心->联系客服->账号->QQ功能检测，里面就可以解qwq（还要身份证就离谱）

**Comment by Lu-Qi-777** [comment]
那啥...我也是无法发送群消息。然后开了个年费SVIP，过了20分钟左右自己好了

这是否有点。。。
