### ISSUE TITLE
[Bug]: 使用Docker镜像运行时遇到了`Protocol -> decrypt payload error: unknown flag` 错误

### ISSUE THREAD

**Issue by SaarChaffee** [Mrs4s/go-cqhttp#1607]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta7-fix2

### 运行环境

其它（请在下方说明）

### 运行架构

其它

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

编写`docker-compose.yml`
```yml
version: '3'
services:
  go-cqhttp:
    container_name: go-cqhttp
    image: pcrbot/gocqhttp:ffmpeg
    volumes:
      - ./go-cqhttp:/data:rw
    restart: always
```
在linux的`go-cqhttp`文件夹下和windows环境下下按照`https://docs.go-cqhttp.org/guide/config.html#%E9%85%8D%E7%BD%AE%E4%BF%A1%E6%81%AF`配置一样的`config.yml`
在windows下运行go-cq并完成登录和验证
将`device.json`和`session.token`一起复制到linux的`go-cqhttp`文件夹中
运行`sudo docker-compose up`

### 期望的结果是什么？

应该像直接运行windows和linux那样,显示
```log
[2022-07-31 18:50:52] [INFO]: 当前版本:v1.0.0-rc3 
[2022-07-31 18:50:52] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2022-07-31 18:50:52] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2022-07-31 18:50:57] [INFO]: 开始尝试登录并同步消息... 
[2022-07-31 18:50:57] [INFO]: 使用协议: iPad 
[2022-07-31 18:50:57] [INFO]: Protocol -> connect to server: 120.232.67.190:8080 
[2022-07-31 18:50:57] [WARNING]: Protocol -> device lock is disable. http api may fail. 
[2022-07-31 18:51:00] [INFO]: 登录成功 欢迎使用: ... 
[2022-07-31 18:51:00] [INFO]: 开始加载好友列表... 
[2022-07-31 18:51:00] [INFO]: 收到服务器地址更新通知, 将在下一次重连时应用.  
[2022-07-31 18:51:00] [INFO]: 共加载 4 个好友. 
[2022-07-31 18:51:00] [INFO]: 开始加载群列表... 
[2022-07-31 18:51:01] [INFO]: 共加载 7 个群. 
[2022-07-31 18:51:01] [INFO]: 资源初始化完成, 开始处理信息. 
[2022-07-31 18:51:01] [INFO]: アトリは、高性能ですから! 
[2022-07-31 18:51:01] [WARNING]: lambda 初始化失败: Post "http:///runtime/init/ready": http: no Host in request URL 
[2022-07-31 18:51:01] [INFO]: CQ WebSocket 服务器已启动: [::]:33437 
[2022-07-31 18:51:01] [INFO]: 正在检查更新. 
[2022-07-31 18:51:01] [INFO]: 检查更新完成. 当前已运行最新版本. 
[2022-07-31 18:51:01] [INFO]: 开始诊断网络情况 
[2022-07-31 18:51:03] [INFO]: 网络诊断完成. 未发现问题 
```
至此可以正常收到消息

### 实际的结果是什么？

```log
Starting go-cqhttp ... done
Attaching to go-cqhttp
go-cqhttp    | [2022-07-31 11:29:54] [INFO]: 当前版本:v1.0.0-beta7-fix2 
go-cqhttp    | [2022-07-31 11:29:54] [INFO]: 用户交流群: 721829413 
go-cqhttp    | [2022-07-31 11:29:54] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
go-cqhttp    | [2022-07-31 11:29:54] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
go-cqhttp    | [2022-07-31 11:29:59] [INFO]: 开始尝试登录并同步消息... 
go-cqhttp    | [2022-07-31 11:29:59] [INFO]: 使用协议: iPad 
go-cqhttp    | [2022-07-31 11:29:59] [INFO]: Protocol -> connect to server: 106.55.209.241:80 
go-cqhttp    | [2022-07-31 11:29:59] [ERROR]: Protocol -> decrypt payload error: unknown flag 
go-cqhttp    | [2022-07-31 11:30:14] [ERROR]: Protocol -> decrypt payload error: unknown flag 
go-cqhttp    | [2022-07-31 11:30:29] [FATAL]: 登录时发生致命错误: Packet timed out 
```

### 补充说明（可选）

使用的镜像是 [pcrbot/gocqhttp:ffmpeg](https://hub.docker.com/r/pcrbot/gocqhttp)
docker版本: 20.10.7, build 20.10.7-0ubuntu5~20.04.2
docker-compose版本: 1.25.0, build unknown

**Comment by MingxuanGame** [comment]
请更新至最新版本

**Comment by SaarChaffee** [comment]
> 请更新至最新版本

[Docker镜像](https://hub.docker.com/r/pcrbot/gocqhttp/tags)最新的是4个月前的

**Comment by MingxuanGame** [comment]
> > 请更新至最新版本
> 
> [Docker镜像](https://hub.docker.com/r/pcrbot/gocqhttp/tags)最新的是4个月前的

这个可以使用，不过建议使用 [GitHub docker 镜像](https://github.com/Mrs4s/go-cqhttp/pkgs/container/go-cqhttp)

**Comment by SaarChaffee** [comment]
> > > 请更新至最新版本
> > 
> > 
> > [Docker镜像](https://hub.docker.com/r/pcrbot/gocqhttp/tags)最新的是4个月前的
> 
> 这个可以使用，不过建议使用 [GitHub docker 镜像](https://github.com/Mrs4s/go-cqhttp/pkgs/container/go-cqhttp)

感谢，换了ghcr.io的镜像可以正常运行了
ghcr.io没得加速等了好久（躺）

**Comment by Yanluo918** [comment]
106.55.209.241:8080 被标记存在木马，行为如下

**Comment by Yanluo918** [comment]
MD5: 1c082cb3fc2b899e3816534bffbabcdf
Size: 6332416
FileType: PE32 Exe
Platform: WINDOWS
ProcessPath: C:\Users\ADMINI~1\AppData\Local\Temp\1663406769941532546_47f30efe_cloudsafeline_inc_sandbox_scan-a13679d3c06c4acc846a02c687641a97-0__reddrip.exe
PE_Timestamp: 2022-05-28 10:46:52
Process Tree: |____ppid: 1016-pid: 2108:"c:\users\admini~1\appdata\local\temp\1663406769941532546_47f30efe_cloudsafeline_inc_sandbox_scan-a13679d3c06c4acc846a02c687641a97-0__reddrip.exe"

Dropped: [u'c:\\users\\administrator\\appdata\\local\\temp\\cab87bd.tmp', u'c:\\windows\\libeay32.dll', u'c:\\users\\administrator\\appdata\\local\\temp\\tar8683.tmp', u'c:\\users\\administrator\\appdata\\local\\temp\\tar87be.tmp', u'c:\\users\\administrator\\appdata\\local\\microsoft\\windows\\temporary internet files\\content.ie5\\2pvjri1n\\serverlist[1].jsp', u'c:\\users\\administrator\\appdata\\locallow\\microsoft\\cryptneturlcache\\metadata\\94308059b57b3142e455b38a6eb92015', u'c:\\users\\administrator\\appdata\\locallow\\microsoft\\cryptneturlcache\\content\\f0accf77cdcbff39f6191887f6d2d357', u'c:\\users\\administrator\\appdata\\local\\temp\\cab8682.tmp', u'c:\\users\\administrator\\appdata\\locallow\\microsoft\\cryptneturlcache\\metadata\\f0accf77cdcbff39f6191887f6d2d357']
DNS:

TCP:
42.81.183.237:443
59.56.22.8:80
222.138.3.87:80
222.138.3.87:80
106.55.209.241:8080

HTTP:
:http://www.microsoft.com/pki/certs/MicRooCerAut_2010-06-23.crt
http://www.download.windowsupdate.com/msdownload/update/v3/static/trustedr/en/authrootstl.cab
