### ISSUE TITLE
[Feature]希望能增加邀请好友进群的功能

### ISSUE THREAD

**Issue by Cola-Ace** [Mrs4s/go-cqhttp#1617]
**环境信息**
go-cqhttp版本: linux armv7

**需要添加的功能内容**
希望能增加邀请好友进群的功能，具体api参数如下：
group_id 要邀请的群号
user_id 要邀请的QQ号
若机器人不在群里或机器人不为被邀请人好友则返回false

**Comment by 2331892928** [comment]
此功能会被滥用，你没发现go-cqhttp的api很多都是安全的，不会被滥用的么，不然你以为他们都凉了，go-cqhttp还没凉，连获取pskey的api都没有，你想要你的不安全功能，你可以自行下载go-cqhttp源码进行开发然后自用
