### ISSUE TITLE
支持手动输入 ticket

### ISSUE THREAD

**Issue by shigma** [Mrs4s/go-cqhttp#1619]
**环境信息**

go-cqhttp版本: 1.0.0-rc.3

**需要添加的功能内容**

考虑到官网访问性与可靠性问题，希望为「使用浏览器抓取滑条并登录」提供手动输入 ticket 方案。

具体设计：当用户输入 1 后进入 sliderCaptchaProcessor，在原有逻辑的基础上同时监听键盘输入。如有输入文本，则将其当成 ticket 并立即返回。

https://github.com/Mrs4s/go-cqhttp/blob/177ba9d8c2b1d86301f0bf3e0714710fe3c40af4/cmd/gocq/login.go#L147-L164

**Comment by shigma** [comment]
这个功能是我自己需要的，对一般用户可能用处不大。如果维护者觉得可以做的话，我愿意提供 PR。

**Comment by 2331892928** [comment]
很久以前就是手动输入的tk,现在你搞倒退？？？就跟智能手机充电不方便，发明了可拆卸电池。倒退发明。况且我们都是自作的框架。命令行只是在后台默默付出(管道dos)

**Comment by Ink-33** [comment]
> 很久以前就是手动输入的tk,现在你搞倒退？？？就跟智能手机充电不方便，发明了可拆卸电池。倒退发明。况且我们都是自作的框架。命令行只是在后台默默付出(管道dos) 所以go-cqhttp对所有需要输入的都做了默认处理，就是方便封装为可视化菜单式框架

很久以前人们只能打有线电话。现在无线网络如此发达，难道有线电话就应该被废除？

gocq加入由开发者托管的`ticket`在线填充方案，虽然很方便，但是就保证他一定能用吗？程序后端panic了怎么办？域名被墙了怎么办？这些你考虑过吗？

我还没提觉得第三方服务不安全的情况，不过有这种需求的人，大概都有能力修改源码自己编译，或者提一个友好的`feature request`

补充一句，我个人是反对gocq降低用户准入门槛的。为什么反对请你自己想想

**Comment by ilharp** [comment]
> 就跟智能手机充电不方便，发明了可拆卸电池。倒退发明。

充电宝，我的充电宝 😭😭😭

> 就是方便封装为可视化菜单式框架

只是好奇：「可视化菜单式框架」是什么？

**Comment by shigma** [comment]
> 很久以前就是手动输入的tk,现在你搞倒退？？？就跟智能手机充电不方便，发明了可拆卸电池。倒退发明。况且我们都是自作的框架。命令行只是在后台默默付出(管道dos) 所以go-cqhttp对所有需要输入的都做了默认处理，就是方便封装为可视化菜单式框架

我一开始就说了「**在原有逻辑的基础上**同时监听键盘输入」，这种改动**不会影响到任何现有用户的使用，反倒是之前的升级使得原本依赖键盘输入的用户无法继续使用新版本了**。请问你是不是觉得自己能用就够了，其他任何人用上 go-cqhttp 会少你一块肉吗？

**Comment by Mrs4s** [comment]
确实是正常需求 没必要争论的
下个版本会加回来
