### ISSUE TITLE
希望Go-cq能够返回当前QQ的skey跟pskey

### ISSUE THREAD

**Issue by vaecou** [Mrs4s/go-cqhttp#1620]
**环境信息**

go-cqhttp版本: 最新版本

**需要添加的功能内容**
希望Go-cq能够返回当前QQ的skey跟pskey

**Comment by vaecou** [comment]
> see #1517

没有增加的可能性了嘛🙄

**Comment by icarus-ai** [comment]
> > see #1517
> 
> 没有增加的可能性了嘛roll_eyes

大概是没有的

**Comment by vaecou** [comment]
> > > see #1517
> > 
> > 
> > 没有增加的可能性了嘛roll_eyes
> 
> 大概是没有的

OKOK，谢谢老哥，我去找找有没有什么自动更新和获取Skey的接口

**Comment by Mrs4s** [comment]
获取Cookie是敏感操作, 不会加的

**Comment by vaecou** [comment]
> 获取Cookie是敏感操作, 不会加的

好的，收到
