### ISSUE TITLE
[Bug]: [WARNING]: 连接到反向WebSocket Universal服务器 ws://tqq.52expo.top/ 时出现错误: unexpected EOF 

### ISSUE THREAD

**Issue by lap888** [Mrs4s/go-cqhttp#1630]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

go-cqhttp_darwin_amd64.tar.gz

### 运行环境

MacOS

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

[Bug]: [WARNING]: 连接到反向WebSocket Universal服务器 ws://tqq.52expo.top/ 时出现错误: unexpected EOF 
链接不上NGINX配置的反向代理 之前是没有问题的。

### 期望的结果是什么？

1

### 实际的结果是什么？

1

**Comment by 2659170494** [comment]
哥你情况和我很相似啊：https://github.com/nonebot/adapter-onebot/issues/26
被人说了是被腾讯服务器断开了连接，只能重启go-cqhttp
