### ISSUE TITLE
[Bug]: go-cqhttp/internal/文件未更新冲突

### ISSUE THREAD

**Issue by 764763903a** [Mrs4s/go-cqhttp#1635]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc1/包括以上版本 

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

上传或者发送图片

### 期望的结果是什么？

提供解决方案谢谢

### 实际的结果是什么？

提供解决方案谢谢

### 日志记录（可选）

```golang
event error: runtime error: invalid memory address or nil pointer dereference
goroutine 801 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*EventHandle[...]).dispatch.func1()
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220621083050-ae8c187aa59d/client/events.go:36 +0x59
panic({0x1079780, 0x1bf7a00})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/Mrs4s/go-cqhttp/internal/btree.(*DB).Insert(0x0, 0x1192160?, {0xc0033fc180?, 0xc001aee780?, 0xd6cf3f?})
        /usr/local/go/path/pkg/mod/github.com/764763903a/go-cqhttp@v1.1.6/internal/btree/btree.go:491 +0x2d
github.com/Mrs4s/go-cqhttp/internal/cache.(*Cache).Insert(0x1c8f340, {0xc000474700, 0x10, 0x7f0a256bd3a8?}, {0xc0033fc180, 0xb9, 0xb9})
        /usr/local/go/path/pkg/mod/github.com/764763903a/go-cqhttp@v1.1.6/internal/cache/cache.go:35 +0xdf
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).checkMedia(0xc0000d5880, {0xc001e322c0?, 0x1, 0xc001aeea08?}, 0x5d4e0d78)
        /usr/local/go/path/pkg/mod/github.com/764763903a/go-cqhttp@v1.1.6/coolq/event.go:686 +0x11c
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).SendPrivateMessage(0xc0000d5880, 0x3338da17, 0x1c4791dc, 0xc001aeebb8)
        /usr/local/go/path/pkg/mod/github.com/764763903a/go-cqhttp@v1.1.6/coolq/bot.go:320 +0x145
github.com/cdle/xdd/qbot.Main.func1(0x3338da17, {0x1018820?, 0xc001b66168?})
        /opt/xdd-plus/qbot/main.go:80 +0x348
github.com/cdle/xdd/models.(*Sender).SendImg(...)
        /opt/xdd-plus/models/command.go:73
github.com/cdle/xdd/models.glob..func35(0xc00049e000)
        /opt/xdd-plus/models/command.go:628 +0x113
github.com/cdle/xdd/models.glob..func9.1(...)
        /opt/xdd-plus/models/bot.go:155
github.com/cdle/xdd/models.glob..func9({0xc00196ca20, 0x3, 0x4?})
        /opt/xdd-plus/models/bot.go:156 +0x499d
github.com/cdle/xdd/models.glob..func5(0xc00029cd20?, {0xc0002c00e8, 0x6})
        /opt/xdd-plus/models/bot.go:57 +0xe7
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).privateMessageEvent(0xc0000d5880, 0x347f89fb98?, 0xc0023b8d40)
        /usr/local/go/path/pkg/mod/github.com/764763903a/go-cqhttp@v1.1.6/coolq/event.go:82 +0x1d2
github.com/Mrs4s/MiraiGo/client.(*EventHandle[...]).dispatch(0xc001b660d8, 0xc003152600?, 0xc0023b8d40)
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220621083050-ae8c187aa59d/client/events.go:40 +0x110
github.com/Mrs4s/MiraiGo/client.privateMessageDecoder(0xc003152600, 0xc00207d5a0?, 0xc0016ac030?)
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220621083050-ae8c187aa59d/client/c2c_processor.go:138 +0x245
github.com/Mrs4s/MiraiGo/client.(*QQClient).commMsgProcessor(0xc003152600, 0xc001b660d8, 0xc0002ea160)
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220621083050-ae8c187aa59d/client/c2c_processor.go:96 +0x4f0
github.com/Mrs4s/MiraiGo/client.(*QQClient).c2cMessageSyncProcessor(0xc003152600, 0xc000162dc0, 0xc0002ea160)
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220621083050-ae8c187aa59d/client/c2c_processor.go:67 +0x60c
github.com/Mrs4s/MiraiGo/client.decodeMessageSvcPacket(0xc001017200?, 0x435?, {0xc001017200, 0x435, 0x435})
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220621083050-ae8c187aa59d/client/decoders.go:387 +0xa5
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0028862d0)
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220621083050-ae8c187aa59d/client/network.go:346 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220621083050-ae8c187aa59d/client/network.go:332 +0x4b8
```

**Comment by Ink-33** [comment]
你这是二开的，谁写的找谁

**Comment by 764763903a** [comment]
> 你这是二开的，谁写的找谁

没二开。。。。直接用的源代码

**Comment by 764763903a** [comment]
用的1.0.0-rc3的源代码

**Comment by Ink-33** [comment]
> 用的1.0.0-rc3的源代码

https://github.com/Mrs4s/go-cqhttp/releases/tag/v1.0.0-rc3

**Comment by 764763903a** [comment]
> > 用的1.0.0-rc3的源代码
> 
> https://github.com/Mrs4s/go-cqhttp/releases/tag/v1.0.0-rc3

认真严肃的检查过代码了  一摸一样 git对比都用过了 一模一样

**Comment by 764763903a** [comment]
> 

唯独只加了两句用做监听的

**Comment by Ink-33** [comment]
你贴出来的stack明显就有官方代码以外的东西，请尝试使用**完全**未经修改的程序，进行复现

**Comment by 764763903a** [comment]
> 你贴出来的stack明显就有官方代码以外的东西，请尝试使用**完全**未经修改的程序，进行复现

2022/08/15 16:02:47.901 [I] [main.go:462]  测试图片

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe2a04d]

goroutine 483 [running]:
github.com/Mrs4s/go-cqhttp/internal/btree.(*DB).Insert(0x0, 0x11901c0?, {0xc000977b00?, 0xc00176d590?, 0xd6cbff?})
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/go-cqhttp@v1.0.0-rc3/internal/btree/btree.go:491 +0x2d
github.com/Mrs4s/go-cqhttp/internal/cache.(*Cache).Insert(0x1c8af60, {0xc000285330, 0x10, 0x7fb1909f6500?}, {0xc000977b00, 0xb9, 0xb9})
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/go-cqhttp@v1.0.0-rc3/internal/cache/cache.go:35 +0xdf
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).checkMedia(0xc00021d800, {0xc001ed3b60?, 0x1, 0xc00176d818?}, 0x5d4e0d78)
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/go-cqhttp@v1.0.0-rc3/coolq/event.go:680 +0x11c
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).SendPrivateMessage(0xc00021d800, 0x2d955eff, 0x1c4791dc, 0xc00176d9c8)
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/go-cqhttp@v1.0.0-rc3/coolq/bot.go:320 +0x145
github.com/cdle/xdd/qbot.Main.func1(0x2d955eff, {0x1016f80?, 0xc00115ddb8?})
        /opt/xdd-plus/qbot/main.go:80 +0x348
github.com/cdle/xdd/models.Test(0xc000365c70?)
        /opt/xdd-plus/models/wck.go:58 +0x6a
github.com/cdle/xdd/qbot.Main()
        /opt/xdd-plus/qbot/main.go:462 +0x20af
created by main.main
        /opt/xdd-plus/main.go:107 +0xe38
原版代码

**Comment by Mrs4s** [comment]
这个错误是未正常初始化btree示例导致的.
我们无法帮闭源修改版本debug, 本项目也不赞同闭源修改的行为

**Comment by 764763903a** [comment]
> 这个错误是未正常初始化btree实例导致的. 我们无法帮闭源修改版本debug, 本项目也不赞同闭源修改的行为

不需要这么苛刻把  大家只是交流讨论一下  当然我只是提供修复建议毕竟我没有参与全局开发。。。
修复方案如下
// Insert a new item with key 'hash' with the contents in 'data' to the
// database file.
func (d *DB) Insert(chash *byte, data []byte) {
	/* SHA-1 must be in writable memory */
	var hash [hashSize]byte
	copyhash(&hash[0], chash)
	if d != nil {
		_ = d.insertTopLevel(&d.top, &hash[0], data, len(data))
		freeQueued(d)
		d.flushSuper()
	}
}

**Comment by icarus-ai** [comment]
> > 这个错误是未正常初始化btree实例导致的. 我们无法帮闭源修改版本debug, 本项目也不赞同闭源修改的行为
> 
> 感谢指点 大家只是交流讨论一下 当然我只是提供修复建议毕竟我没有参与全局开发。。。 修复方案如下 // Insert a new item with key 'hash' with the contents in 'data' to the // database file. func (d *DB) Insert(chash _byte, data []byte) { /_ SHA-1 must be in writable memory */ var hash [hashSize]byte copyhash(&hash[0], chash) if d != nil { _ = d.insertTopLevel(&d.top, &hash[0], data, len(data)) freeQueued(d) d.flushSuper() } }

对象里判断对象是否存在 ！

**Comment by 764763903a** [comment]
> 

问题就是这个对象没有初始化    全局的修复无从下手除非整个项目读一遍

**Comment by icarus-ai** [comment]
> > 
> 
> 问题就是这个对象没有初始化 全局的修复无从下手除非整个项目读一遍

cache.Init() 了解下?
