### ISSUE TITLE
[Bug]: 入群欢迎上报多次

### ISSUE THREAD

**Issue by cxl2020MC** [Mrs4s/go-cqhttp#1638]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

rc3

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

新人入群

### 期望的结果是什么？

上报单次入群event数据

### 实际的结果是什么？

上报多次入群event数据
导致多次欢迎
并且上报数据有一定的延迟（1分钟）

### 补充说明（可选）

在大号上运行（当时有其他设备在线）

**Comment by BoyChai** [comment]
我也遇到了这个问题，偶尔出现上报多次的问题可能是因为go-cqhttp的上报超时时间过短，导致多次上报到你的接收端多次。你可以把超时时间调高或者上报次数调成一次

**Comment by cxl2020MC** [comment]
log中也没有看到超时

**Comment by cxl2020MC** [comment]
那一天罕见的只出现了一次超时

**Comment by cxl2020MC** [comment]
> > 我的超时时间已经设定为2分钟了（120s）
> 
> 很早之前

刚刚发现是1.5s（1500ms）

**Comment by cxl2020MC** [comment]
改改试试
