### ISSUE TITLE
[Bug]: 登录失败: 密码错误或账号被冻结

### ISSUE THREAD

**Issue by kcn3388** [Mrs4s/go-cqhttp#1646]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

Windows (64)

### 运行架构

x86

### 连接方式

WebSocket (反向)

### 使用协议

3 | MacOS

### 重现步骤

扫码登录后提示 登录失败: 密码错误或账号被冻结
[2022-08-24 22:51:14] [INFO]: 按 Enter 或等待 5s 后继续....
账号并没有被封禁，可以正常使用（不如说如果封号了还怎么扫码登录）
![image](https://user-images.githubusercontent.com/25716090/186451173-82077e20-0682-4aaf-a90e-c603aa1e56ed.png)

### 期望的结果是什么？

正常登录

### 实际的结果是什么？

扫码登录后提示 登录失败: 密码错误或账号被冻结

### 日志记录（可选）

```golang
[2022-08-24 22:48:22] [WARNING]: 恢复会话失败: exchange_emp failed: 15 , 尝试使用正常流程登录. 
[2022-08-24 22:48:52] [WARNING]: 登录失败: 密码错误或账号被冻结 
[2022-08-24 22:49:05] [WARNING]: 账号密码未配置, 将使用二维码登录. 
[2022-08-24 22:49:23] [WARNING]: 登录失败: 密码错误或账号被冻结 
[2022-08-24 22:49:39] [WARNING]: 账号密码未配置, 将使用二维码登录. 
[2022-08-24 22:49:39] [WARNING]: 虚拟设备信息不存在, 将自动生成随机设备. 
[2022-08-24 22:50:56] [WARNING]: 账号密码未配置, 将使用二维码登录. 
[2022-08-24 22:51:14] [WARNING]: 登录失败: 密码错误或账号被冻结
```

**Comment by Ink-33** [comment]
多试几次也不行吗？

**Comment by Mrs4s** [comment]
> > 多试几次也不行吗？
> 
> 不行，甚至改过密码和开关登录保护了

试试其他协议或者用密码登录, 不要扫码
最近扫码加强了风控

**Comment by kcn3388** [comment]
密码也不行

**Comment by kcn3388** [comment]
> 试试其他协议或者用密码登录, 不要扫码 最近扫码加强了风控

密码也不行

**Comment by JSYRD** [comment]
重新部署就可以用了orz

**Comment by Sam5440** [comment]
同样的问题，再次出现了emmm，但是是ipad协议无法登录，watch可正常登录

**Comment by kongbai39** [comment]
同样问题，而且每个协议都换过了都无法登录，但是自己在手机上是能登录的

- [2022-10-25 13:27:13] [INFO]: Protocol -> connect to server: [::ffff:42.81.194.99]:80
- [2022-10-25 13:27:13] [WARNING]: 登录需要滑条验证码, 请选择验证方式:
- [2022-10-25 13:27:13] [WARNING]: 1. 使用浏览器抓取滑条并登录
- [2022-10-25 13:27:13] [WARNING]: 2. 使用手机QQ扫码验证 (需要手Q和gocq在同一网络下).
- [2022-10-25 13:27:13] [WARNING]: 请输入(1 - 2) (将在10秒后自动选择1)：
- [2022-10-25 13:27:16] [WARNING]: 请前往该地址验证 -> （滑条验证）
- [2022-10-25 13:27:38] [WARNING]: 登录失败: 密码错误或账号被冻结
- [2022-10-25 13:27:38] [INFO]: 按 Enter 或等待 5s 后继续....

**Comment by DiaoChan1** [comment]
同样的问题 使用ipad登陆即显示：登录失败: 密码错误或账号被冻结

**Comment by FlyingStarlight** [comment]
> 同样的问题，再次出现了emmm，但是是ipad协议无法登录，watch可正常登录

同IPAD, Mac OS都不可以，用Watch可以了

**Comment by qycss** [comment]
> 同样的问题，再次出现了emmm，但是是ipad协议无法登录，watch可正常登录

屮 搞了3天 原来是这样

**Comment by lgc2333** [comment]
+1 除了企点其他协议都用过了 Watch也不行 希望能尽快修复

**Comment by KafCoppelia** [comment]
同，11/23今日除了企点其他所有协议都不行。

遇到的情况是某天bot账号被冻结，之后我手动解冻后就所有协议都无法登陆了，遇到的报错同上

**Comment by wordgao** [comment]
关注中。

**Comment by wordgao** [comment]
关注中。

**Comment by FreddieGeorge** [comment]
我也遇到了同样的问题，在账号被解冻之后无法再次登录，在手机端是能正常登录的

**Comment by FreddieGeorge** [comment]
> 

我尝试了重新部署，更换协议都不行

**Comment by FreddieGeorge** [comment]
我把 device.json 删除之后重新启动扫码就可以登录了，大家用这个办法试试吧

**Comment by BailPlus** [comment]
> 同样问题，而且每个协议都换过了都无法登录，但是自己在手机上是能登录的
> 
> * [2022-10-25 13:27:13] [INFO]: Protocol -> connect to server: [::ffff:42.81.194.99]:80
> * [2022-10-25 13:27:13] [WARNING]: 登录需要滑条验证码, 请选择验证方式:
> * [2022-10-25 13:27:13] [WARNING]: 1. 使用浏览器抓取滑条并登录
> * [2022-10-25 13:27:13] [WARNING]: 2. 使用手机QQ扫码验证 (需要手Q和gocq在同一网络下).
> * [2022-10-25 13:27:13] [WARNING]: 请输入(1 - 2) (将在10秒后自动选择1)：
> * [2022-10-25 13:27:16] [WARNING]: 请前往该地址验证 -> （滑条验证）
> * [2022-10-25 13:27:38] [WARNING]: 登录失败: 密码错误或账号被冻结
> * [2022-10-25 13:27:38] [INFO]: 按 Enter 或等待 5s 后继续....

同问

**Comment by xwklib** [comment]
> > 同样的问题，再次出现了emmm，但是是ipad协议无法登录，watch可正常登录
> 
> 同IPAD, Mac OS都不可以，用Watch可以了

+1

**Comment by Umamusume-Agnes-Digital** [comment]
我也遇到同样的问题，但自己的win端可以正常使用，但是部署到linux服务器上，session.token是失效的

**Comment by tcgkw** [comment]
我也遇到同样的问题，手机端可以正常登录，但linux服务器不行。试过删除device.json不行，最后是通过修改device.json里的protocol字段解决的，默认是5，我改成6不行，但改成3可以了

**Comment by cyczq11** [comment]
> 

 “最后是通过修改device.json里的”  这个文件在哪里找到呢

**Comment by lzmCloud** [comment]
device.json 里面 的 protocol 改成2可以了
