### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by sjtuli** [Mrs4s/go-cqhttp#1650]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [x] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

a73d27f

### 运行环境

MacOS

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

添加过滤器文件
内容如下：

{
    ".or": [
        {
            "message_type": "private"
        },
        {
            "message_type": "group",
            "anonymous": {
                ".eq": null
            }
        }
    ]
}

### 期望的结果是什么？

存在过滤器文件时，不需要在qq客户端发送消息，即可自动连接bot

### 实际的结果是什么？

与bot的连接变成惰性的了。连接断开后，无法自动连接到bot，需要在qq客户端发送一条消息，才会尝试连接bot
![截屏2022-08-26 13 50 27](https://user-images.githubusercontent.com/75962592/186832603-814f80be-fb6d-4f57-b9f0-f5498b6616e8.png)

**Comment by MingxuanGame** [comment]
https://github.com/nonebot/discussions/discussions/13#discussioncomment-2929516
