### ISSUE TITLE
[Bug]: macos协议不能用了，应该是tx更新了

### ISSUE THREAD

**Issue by liuzj288** [Mrs4s/go-cqhttp#1659]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

rc3

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

3 | MacOS

### 重现步骤

报错

### 期望的结果是什么？

11

### 实际的结果是什么？

111

### 简单的复现代码/链接（可选）

```golang
1
```

**Comment by wdvxdr1123** [comment]
关联PR: Mrs4s/MiraiGo#295

你可以在 https://github.com/Mrs4s/go-cqhttp/actions/runs/2963867776 中下载使用

**Comment by liuzj288** [comment]
> 关联PR: [Mrs4s/MiraiGo#295](https://github.com/Mrs4s/MiraiGo/pull/295)
> 
> 你可以在 https://github.com/Mrs4s/go-cqhttp/actions/runs/2963867776 中下载使用

这个怎么用，windows下直接替换原来的exe文件吗？

**Comment by kcn3388** [comment]
> 关联PR: [Mrs4s/MiraiGo#295](https://github.com/Mrs4s/MiraiGo/pull/295)
> 
> 你可以在 https://github.com/Mrs4s/go-cqhttp/actions/runs/2963867776 中下载使用

MacOS协议是不支持戳一戳吗

**Comment by DeSireFire** [comment]
我于2022.10.13. 下载[v1.0.0-rc3](https://github.com/Mrs4s/go-cqhttp/releases/tag/v1.0.0-rc3)

**Comment by Zxis233** [comment]
感谢！
