### ISSUE TITLE
[Bug]: 使用图文时 警告:  图片上传失败: image type error: application/octet-stream 

### ISSUE THREAD

**Issue by huigetql** [Mrs4s/go-cqhttp#1660]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

MacOS

### 运行架构

x86

### 连接方式

WebSocket (正向)

### 使用协议

3 | MacOS

### 重现步骤

在调用接口获取图片过后  经过 CQ:image转发 会触发。昨天是可以正常发送的，但是今天就会报image type error: application/octet-stream  导致无法上传照片并发送空的消息

### 期望的结果是什么？

1

### 实际的结果是什么？

1

### 日志记录（可选）

```golang
[2022-09-01 15:50:36] [WARNING]: 警告: 合并转发··· 图片上传失败: image type error: application/octet-stream
```

**Comment by huigetql** [comment]
....发现了个问题，官网教程上写的file 是文件名  url是网络地址 ，但是用url填网络地址会报错，用file反而没问题了
![image](https://user-images.githubusercontent.com/66297001/187864780-457d740a-3f45-4927-a70d-6cf6ead69bcd.png)

**Comment by Miuzarte** [comment]
刚也遇到了  还真是只能用file

**Comment by hezi-biancheng** [comment]
还真的是这样，提示image type error: application/octet-stream，file没问题，但是我要的图片会在网络上更新啊，没法下载下来
