### ISSUE TITLE
[Bug]:  [WARNING]: 登录失败: 密码错误或账号被冻结

### ISSUE THREAD

**Issue by kongcheng1212** [Mrs4s/go-cqhttp#1665]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

3 | MacOS

### 重现步骤

[2022-09-02 09:55:17] [INFO]: 当前版本:v1.0.0-rc3 
[2022-09-02 09:55:17] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2022-09-02 09:55:17] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2022-09-02 09:55:22] [INFO]: 开始尝试登录并同步消息... 
[2022-09-02 09:55:22] [INFO]: 使用协议: MacOS 
[2022-09-02 09:55:23] [INFO]: Protocol -> connect to server: 114.222.112.90:8080 
[2022-09-02 09:55:23] [WARNING]: 登录失败: 密码错误或账号被冻结 
[2022-09-02 09:55:23] [INFO]: 按 Enter 或等待 5s 后继续.... 

账号确认能够正常登录，账号密码无误

### 期望的结果是什么？

能够正常使用

### 实际的结果是什么？

能够正常使用

**Comment by synodriver** [comment]
这个确实可以复现，因为我也遇到了。不过我那个号被限制了群聊，现在看来私聊也不行了，直接不给登陆了。等下我调试看看

**Comment by kongcheng1212** [comment]
> 这个确实可以复现，因为我也遇到了。不过我那个号被限制了群聊，现在看来私聊也不行了，直接不给登陆了。等下我调试看看

谢谢

**Comment by pino889** [comment]
同遇到了，怎么解决

**Comment by Coder-Sakura** [comment]
+1

**Comment by pino889** [comment]
您好，您的邮件我已经收到，我会尽快给您回复！祝工作顺利，心情愉快，谢谢！

**Comment by Coder-Sakura** [comment]
> 同遇到了，怎么解决

参考这个[issue 1448](https://github.com/Mrs4s/go-cqhttp/issues/1448)，我换了好几种protocol设备类型才成功（最后是watch）

**Comment by zhzhongshi** [comment]
我也遇到了qwq

**Comment by IceCapriccio** [comment]
删掉device.json再运行一遍就可以了

**Comment by Umamusume-Agnes-Digital** [comment]
小号自己手动发送都发送不出应该被风控的信息，而且已经持续三个月了，可能是小号寄了

**Comment by pino889** [comment]
您好，您的邮件我已经收到，我会尽快给您回复！祝工作顺利，心情愉快，谢谢！

**Comment by Umamusume-Agnes-Digital** [comment]
我也通过扫码的方式能登录，但是仍然消息受限制，部分消息发不出去
