### ISSUE TITLE
[Bug]: 使用浏览器可以请求,但是通过curl和python却是502 Bad Gateway

### ISSUE THREAD

**Issue by Gumingjie0312** [Mrs4s/go-cqhttp#1670]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

Windows (64)

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

使用浏览器访问127.0.0.1:5700时有返回数据,但是当我使用curl时.却没有任何返回,状态为502

### 期望的结果是什么？

python和curl可以正常返回

### 实际的结果是什么？

502

### 简单的复现代码/链接（可选）

```golang
import requests


res = requests.get("http://127.0.0.1:5700", headers={
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.27"
})
print(res.text)
```

**Comment by Mrs4s** [comment]
![image](https://user-images.githubusercontent.com/12137562/188308729-04bfc9ff-91e8-4496-adb5-8125192c0af2.png)
无法复现

**Comment by Gumingjie0312** [comment]
> ![image](https://user-images.githubusercontent.com/12137562/188308729-04bfc9ff-91e8-4496-adb5-8125192c0af2.png) 无法复现

是不是device lock is disable. http api may fail.的问题

**Comment by Mrs4s** [comment]
> > ![image](https://user-images.githubusercontent.com/12137562/188308729-04bfc9ff-91e8-4496-adb5-8125192c0af2.png) 无法复现
> 
> 是不是device lock is disable. http api may fail.的问题

不是

**Comment by Gumingjie0312** [comment]
> > > ![image](https://user-images.githubusercontent.com/12137562/188308729-04bfc9ff-91e8-4496-adb5-8125192c0af2.png) 无法复现
> > 
> > 
> > 是不是device lock is disable. http api may fail.的问题
> 
> 不是

或者是不是因为开了代理的问题

**Comment by Mrs4s** [comment]
> > > > ![image](https://user-images.githubusercontent.com/12137562/188308729-04bfc9ff-91e8-4496-adb5-8125192c0af2.png) 无法复现
> > > 
> > > 
> > > 是不是device lock is disable. http api may fail.的问题
> > 
> > 
> > 不是
> 
> 或者是不是因为开了代理的问题

是

**Comment by Gumingjie0312** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/12137562/188308729-04bfc9ff-91e8-4496-adb5-8125192c0af2.png) 无法复现
> > > > 
> > > > 
> > > > 是不是device lock is disable. http api may fail.的问题
> > > 
> > > 
> > > 不是
> > 
> > 
> > 或者是不是因为开了代理的问题
> 
> 是

如何解决呢,这个程序怎么开代理,谢谢

**Comment by Mrs4s** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/12137562/188308729-04bfc9ff-91e8-4496-adb5-8125192c0af2.png) 无法复现
> > > > > 
> > > > > 
> > > > > 是不是device lock is disable. http api may fail.的问题
> > > > 
> > > > 
> > > > 不是
> > > 
> > > 
> > > 或者是不是因为开了代理的问题
> > 
> > 
> > 是
> 
> 如何解决呢,这个程序怎么开代理,谢谢

不是这个... 你应该吧环境变量里面的代理去掉, 不然 `curl` 和 `requests` 会尝试使用代理连接本地地址

**Comment by Gumingjie0312** [comment]
这就麻烦了,我为了pip去加了环境变量😂

**Comment by Gumingjie0312** [comment]
能不能考虑加一个代理

**Comment by Mrs4s** [comment]
> 能不能考虑加一个代理

不是, 这个是  `curl` 和 `requests` 用代理连接导致的, 不是加不加代理的问题

**Comment by Gumingjie0312** [comment]
好吧好吧,谢谢了
