### ISSUE TITLE
需要一条消息中带大量图片场景下的解决方案

### ISSUE THREAD

**Issue by Jadlokin-Scarlet** [Mrs4s/go-cqhttp#1673]
**环境信息**

go-cqhttp版本: 093605c

**需要添加的功能内容**
遇到一个场景是，发送一条消息可能带9张大图，导致http time out。之后也不知道是全部图都发出去了还是部分成功了还是整条消息都没发出去。无法重试
能否支持先单独上传图片，再用返回的图片id之类的东西发整条消息。或者有没有更好的解决方案。

**Comment by Ink-33** [comment]
可以试试构建合并转发

**Comment by Akegarasu** [comment]
你可以自己把每张图片分别发送到群号为 1 的群
