### ISSUE TITLE
我正在寻找一款discord 转发到 discord 的软件,人民币酬谢

### ISSUE THREAD

**Issue by 1771269478** [Mrs4s/go-cqhttp#1674]
**环境信息**

go-cqhttp最新版本: 

目前我使用了免费版..
![image](https://user-images.githubusercontent.com/102167146/188507837-836d5b30-9c0a-41aa-988c-15db878a8f40.png)
和
![image](https://user-images.githubusercontent.com/102167146/188507868-7bd7d979-f87c-46e7-af3d-a752b34b7873.png)

目前使用的 插眼,并转发到QQ群..
一切都很好.但是在转发图片的时候出现了问题.
我发现当别人发出的图片都是 https://cdn.discordapp.com/ 开头的时候..软件不会识别到有图片.<image>字符段返回none
我自己测试的时候,用网页端发出的图片.全部可以识别并被下载和转发
![7)HWZR86D_$OUM1$A`$@T7O](https://user-images.githubusercontent.com/102167146/188508107-216f1fbe-57eb-45f2-a7f3-137bd1e88fd6.png)

请问怎么可以解决 无法转发图片的问题.

另外如果做一个 discord 转发到 discord 的软件 1000人民币的预算可以做吗.盼复谢谢

微信电话 13962164888

**需要添加的功能内容**

**Comment by Mrs4s** [comment]
你可以去相关软件的repo提问, 这里不接受这类请求
