### ISSUE TITLE
[Bug]: 我在使用中出现了由于设备网络异常，需要被验证设备连接验证设备的热点或者在同一wifi下才可以成功，但是这是托管在云端服务器上的，不知道有人遇到类似的情况吗？还有教学文档怎么打不开了，是出了什么事吗？

### ISSUE THREAD

**Issue by h265642327** [Mrs4s/go-cqhttp#1675]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0

### 运行环境

Ubuntu

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

./go-cqhttp

### 期望的结果是什么？

扫描二维码成功登录

### 实际的结果是什么？

扫描失败

### 简单的复现代码/链接（可选）

```golang
。
```

### 日志记录（可选）

```golang
。
```

### 补充说明（可选）

。

**Comment by Natsumelan** [comment]
可以试试在本地登录后把本地文件复制到云服务器

**Comment by Norach-I** [comment]
我是本地VM虚拟机安装了和阿里云服务器同一版本的ubuntu22.04。然后本地安装扫码完毕后，将扫码后生成的文件打包拷贝到服务器上(包括device.json文件)。现在阿里云上面可以登陆成功了。

**Comment by Gingmzmzx** [comment]
同一网我直接连到我服务器开的v2ray然后开全局就好了
