### ISSUE TITLE
判断 TTY 环境决定交互形式

### ISSUE THREAD

**Issue by shigma** [Mrs4s/go-cqhttp#1678]
**环境信息**

go-cqhttp版本: 1.0.0-rc3

**需要添加的功能内容**

过去的倒计时自动选择、重启功能主要是为不方便输入的场景设计的，但过短的 timeout 会导致用户操作非常容易超时，过长的 timeout 又与设计初衷相违背。我建议取消倒计时逻辑，改为直接判断环境：

- 在 TTY 环境下：无倒计时逻辑，一直等待用户输入（或保留倒计时但加长时间为 10min，确保不会超时）
- 在非 TTY 环境下：在选项处直接进入默认分支，在非选项处直接退出

TTY 环境的判断可以使用 <https://github.com/ifrstr/isatty>。

如有需要我愿意提供 PR。

**Comment by Mrs4s** [comment]
可以这么改, 之前主要是因为判断 `console` 环境不准确所以没做, 原来已经有轮子了
![86MVW@Z_@E_TY{G9H48LNEG](https://user-images.githubusercontent.com/12137562/189148241-65d2f825-23fe-46bb-83c3-0549c8902713.jpg)

**Comment by shigma** [comment]
> 原来已经有轮子了

@ilharp 不久前才写的

**Comment by neiloe8023** [comment]
匿名管道怎么配置 TTY 环境？

**Comment by shigma** [comment]
> 匿名管道怎么配置 TTY 环境？

支持 FORCE_TTY 环境变量~

**Comment by neiloe8023** [comment]
> > 匿名管道怎么配置 TTY 环境？
> 
> 支持 FORCE_TTY 环境变量~


环境变量是可以，但有很多人不愿意用...
想知道有没有什么方法可以让匿名管道有TTY 环境
