### ISSUE TITLE
CQ码发送图片出错

### ISSUE THREAD

**Issue by Faultiness** [Mrs4s/go-cqhttp#169]
**环境信息**
go-cqhttp版本: v0.9.21
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
使用[CQ:image,file=file:///C:\\path_to_my_img.png]发送图片时，若路径或图片名中包含#或-则会导致报错。
![图片](https://user-images.githubusercontent.com/12472447/90972037-56823000-e548-11ea-993f-e70ca05f90c5.png)

**复现方法**
发送的图片名中包含#或-均会触发。

**Comment by Mrs4s** [comment]
临时解决方案: 可尝试使用Array形式上报数据

**Comment by Faultiness** [comment]
感谢！
目前发送图片是使用nonebot中的session.send()，暂不方便使用Array形式上报数据，不过已将图片名中的#和-进行了过滤。期待进一步的修复。
