### ISSUE TITLE
是不是现在qq的风控会对ip进行了?

### ISSUE THREAD

**Issue by lancer-wang** [Mrs4s/go-cqhttp#1704]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

Ubuntu

### 运行架构

x86

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

外网的vps
一个号被风控,
登陆另一个号,然后没发几条消息就被控
注册一个新号,然后也是没发几条就被控

### 期望的结果是什么？

避免风控

### 实际的结果是什么？

小号全被控

**Comment by zangxx66** [comment]
基本上没什么消息能发出去，vps换ip又麻烦

**Comment by lancer-wang** [comment]
> 基本上没什么消息能发出去，vps换ip又麻烦，如果能通过中间代理实现动态ip就好了

你的换ip可以吗,我被控的号,在本地都发不出去...

**Comment by mengzhiweilai** [comment]
强制分片选项修改为false即可
个人测试修改后恢复了
force-fragment: false

**Comment by shirleygrey** [comment]
> 强制分片选项修改为false即可 个人测试修改后恢复了 force-fragment: false

成功了！非常感谢！

**Comment by lancer-wang** [comment]
> 强制分片选项修改为false即可 个人测试修改后恢复了 force-fragment: false

(⊙o⊙)哇,终于成功了,非常感谢

**Comment by adquantum** [comment]
哇，用这个办法成功了，感谢🙏

**Comment by Yescafe** [comment]
我设置的 force-fragment 本来就是 false，依旧显示风控
