### ISSUE TITLE
[Bug]: 无法发送语音

### ISSUE THREAD

**Issue by cqzaiercn** [Mrs4s/go-cqhttp#1707]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

 v1.0.0-rc1

### 运行环境

Linux

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

环境：centos7虚拟机上
ffmpeg 已经安装并重启
![image](https://user-images.githubusercontent.com/37819946/192484926-a7600ecd-9ee6-46ae-8e6a-8ba5aefd9ba4.png)

### 期望的结果是什么？

可以发送语音

### 实际的结果是什么？

发送的消息实际为纯文本
![image](https://user-images.githubusercontent.com/37819946/192485013-c5962f30-927b-48a2-8e6a-b9a37c5f09c8.png)

**Comment by cqzaiercn** [comment]
重启软件好了

**Comment by woyuchuanhuaxunlu** [comment]
我也遇到这个问题了，求大佬帮忙
