### ISSUE TITLE
[Bug]: 扫描登录提示：当前设备网络不稳定或处于复杂网络环境

### ISSUE THREAD

**Issue by cqzaiercn** [Mrs4s/go-cqhttp#1708]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

 v1.0.0-rc1

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

3 | MacOS

### 重现步骤

当前设备网络不稳定或处于复杂网络环境

### 期望的结果是什么？

能登录

### 实际的结果是什么？

提示当前设备网络不稳定或处于复杂网络环境

**Comment by Sam5440** [comment]
rc3了都

**Comment by Khorasho** [comment]
滑动登录现在也失败了。 登录失败: 当前登录存在安全风险，请使用常用设备或通过手机号登录。

**Comment by dfmjndm** [comment]
> rc3了都

rc3同样失败，滑块不能用说要扫码，手机扫码就提示网络不稳定，连着服务器的代理都没用

**Comment by Sam5440** [comment]
今天本地登录，在同一个网络下登录手表或者iPad的协议，也开始提示网络风险或者其他提示，导致无法登录。
