### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Starrr-sea** [Mrs4s/go-cqhttp#1712]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

CentOS

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

正常的部署，http协议，其他功能全部正常

### 期望的结果是什么？

可以正常获取到群聊邀请者的QQ
operator_id字段

### 实际的结果是什么？

有个问题，QQ群聊的邀请新人会出现无法获取到邀请人的qq，该值变为了0，在最新版的rc3里依旧有这个问题，请问有什么解决方案吗
系统返回的值如下，其中operator_id的邀请人字段为0

### 简单的复现代码/链接（可选）

```golang
{ 'post_type': 'notice', 
  'notice_type': 'group_increase',
  'time': 1664247037, 
  'self_id': 3276394070, 
  'sub_type': 'approve',
  'group_id': 953026557,
  'operator_id': 0,
  'user_id': 3411808390}
```

**Comment by wdvxdr1123** [comment]
duplicate of #721

**Comment by Starrr-sea** [comment]
那这个邀请人的账号该怎么获取呢
