### ISSUE TITLE
[Bug]: 我在使用的时候不知道如何获取消息，能发送消息，尝试了网上好多种方法，都没有用

### ISSUE THREAD

**Issue by algfwq** [Mrs4s/go-cqhttp#1713]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

go-cqhttp_windows_amd64

### 运行环境

Windows (64)

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

from flask import Flask, request

app = Flask(__name__)

@app.route('/', methods=["POST"])
def post_data():
    if request.get_json().get('message_type') == 'private':  # 私聊信息
        uid = request.get_json().get('sender').get('user_id')  # 获取信息发送者的 QQ号码
        message = request.get_json().get('raw_message')  # 获取原始信息
        keyword(message, uid)  # 将 Q号和原始信息传到我们的后台

    if request.get_json().get('message_type') == 'group':  # 如果是群聊信息
        gid = request.get_json().get('group_id')  # 获取群号
        uid = request.get_json().get('sender').get('user_id')  # 获取信息发送者的 QQ号码
        message = request.get_json().get('raw_message')  # 获取原始信息
        keyword(message, uid, gid)  # 将 Q号和原始信息传到我们的后台

    return "None"

if __name__ == '__main__':
    app.run(debug=True, host='127.0.0.1', port=5700)  # 此处的 host和 port对应上面 yml文件的设置

这是我使用的获取消息的代码，但是发消息没有反应

### 期望的结果是什么？

输出接受到的消息

### 实际的结果是什么？

什么也没有得到

### 简单的复现代码/链接（可选）

```golang
from flask import Flask, request

app = Flask(__name__)


@app.route('/', methods=["POST"])
def post_data():
    if request.get_json().get('message_type') == 'private':  # 私聊信息
        uid = request.get_json().get('sender').get('user_id')  # 获取信息发送者的 QQ号码
        message = request.get_json().get('raw_message')  # 获取原始信息
        keyword(message, uid)  # 将 Q号和原始信息传到我们的后台

    if request.get_json().get('message_type') == 'group':  # 如果是群聊信息
        gid = request.get_json().get('group_id')  # 获取群号
        uid = request.get_json().get('sender').get('user_id')  # 获取信息发送者的 QQ号码
        message = request.get_json().get('raw_message')  # 获取原始信息
        keyword(message, uid, gid)  # 将 Q号和原始信息传到我们的后台

    return "None"


if __name__ == '__main__':
    app.run(debug=True, host='127.0.0.1', port=5700)  # 此处的 host和 port对应上面 yml文件的设置
```

**Comment by zht163** [comment]
https://onebot.dev/ecosystem.html

别造轮子了，用轮子
