### ISSUE TITLE
希望能有一个库，可以与Python适配

### ISSUE THREAD

**Issue by algfwq** [Mrs4s/go-cqhttp#1714]
**环境信息**

最新版，Windows64位

**需要添加的功能内容**

很简单，写一个python库，定义几个函数
函数可以直接调用机器人的API
希望能够加入自动获取机器人新消息的API

**Comment by Fros1er** [comment]
看看[Nonebot2](https://v2.nonebot.dev/)?

**Comment by wdvxdr1123** [comment]
see https://onebot.dev/ecosystem.html#onebot-11-10-cqhttp
