### ISSUE TITLE
[Bug]: 群聊中 reply 消息无法被 leveldb 正确记录？

### ISSUE THREAD

**Issue by Well2333** [Mrs4s/go-cqhttp#1715]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

dev测试版: https://github.com/Mrs4s/go-cqhttp/actions/runs/3079926018

### 运行环境

Ubuntu

### 运行架构

x86

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

群聊消息回复后，使用上报消息中的 `id` 字段对消息进行查询，即可出现

### 期望的结果是什么？

能够正常返回数据

### 实际的结果是什么？

[WARNING]: 获取消息时出现错误: get value error: leveldb: not found

### 简单的复现代码/链接（可选）

```golang
测试平台 nonebot-adapter-onebot v11
对应的代码 [可见此处](https://github.com/nonebot/adapter-onebot/blob/master/nonebot/adapters/onebot/v11/bot.py#L34)
```

**Comment by ilihu** [comment]
我刚刚在 v1.0.1 下测试过，reply 类型的消息，可以被 leveldb 正确记录
