### ISSUE TITLE
[Bug]: videoCQ码转换失败 [CQ:video,file=/data/bot/noneBot2/nonebot2/plugins/aaa.mp4]

### ISSUE THREAD

**Issue by YIXUANXUAN19** [Mrs4s/go-cqhttp#1718]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

Ubuntu

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

已经尝试使用了 ffmpeg 将视频转换，但是还是无法发送

### 期望的结果是什么？

成功发送视频

### 实际的结果是什么？

转换CQ码 ({"type": "video", "data": {"file": "/data/bot/noneBot2/nonebot2/plugins/aaa.mp4", "cache": null, "proxy": null, "timeout": null}}) 到MiraiGo Element时出现错误: invalid video 将忽略本段CQ码.

### 简单的复现代码/链接（可选）

```golang
#下面是我用 ffmpeg 将视频转换的代码
video_path = os.path.join(os.path.join(os.path.join(BASE_DIR, 'nonebot2'), 'plugins'), 'ttt.mp4')
output = os.path.join(os.path.dirname(video_path), "aaa.mp4")

# 使用ffmpeg 合并视频和音频
from ffmpy import FFmpeg
translator = FFmpeg(
    executable=r'E:\ffmpeg\bin\ffmpeg.exe',
    inputs={
        video_path: None,
    },
    outputs={
        output: '-c:v copy -strict experimental'
    }
)

translator.run()
```

**Comment by MingxuanGame** [comment]
如果你使用 nonebot2 可以使用 `MessageSegment.video` 传入 `pathlib.Path` 来发送本地视频文件

参考:
pathlib 文档:https://docs.python.org/zh-cn/3/library/pathlib.html
`MessageSegment.video`MessageSegment.video 文档:https://onebot.adapters.nonebot.dev/docs/api/v11/message#MessageSegment-video

如果直接传入，需要添加 `file://`，即 `file:///data/bot/noneBot2/nonebot2/plugins/aaa.mp4`

**Comment by YIXUANXUAN19** [comment]
> 如果你使用 nonebot2 可以使用 `MessageSegment.video` 传入 `pathlib.Path` 来发送本地视频文件
> 
> 参考: pathlib 文档:https://docs.python.org/zh-cn/3/library/pathlib.html `MessageSegment.video` 文档:https://onebot.adapters.nonebot.dev/docs/api/v11/message#MessageSegment-video
> 
> 如果直接传入，需要添加 `file://`，即 `file:///data/bot/noneBot2/nonebot2/plugins/aaa.mp4`

**Comment by YIXUANXUAN19** [comment]
> 如果你使用 nonebot2 可以使用 `MessageSegment.video` 传入 `pathlib.Path` 来发送本地视频文件
> 
> 参考: pathlib 文档:https://docs.python.org/zh-cn/3/library/pathlib.html `MessageSegment.video` 文档:https://onebot.adapters.nonebot.dev/docs/api/v11/message#MessageSegment-video
> 
> 如果直接传入，需要添加 `file://`，即 `file:///data/bot/noneBot2/nonebot2/plugins/aaa.mp4`

感谢，我忘记了需要设置成 file路径了
