### ISSUE TITLE
邀请加新群，没反应，需要重启后才有

### ISSUE THREAD

**Issue by AkiraXie** [Mrs4s/go-cqhttp#172]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.20
运行环境: windows_i386
连接方式: 反向WS

**bug内容**
邀请机器人加新群，没反应，需要重启后才有

**Comment by Mrs4s** [comment]
我这边无法复现 请问邀请进群的时候群设置/机器人账号设置以及是否在机器人账号登录其他平台客户端？

**Comment by AkiraXie** [comment]
邀请进群是直接进了，但是进群之后机器人没反应。群的设置就是允许任何人邀请进群，机器人没特别设置。机器人当时登录pc tim

**Comment by Mrs4s** [comment]
已找到问题, 下个版本修复
