### ISSUE TITLE
希望能给c++写一个头文件来调用

### ISSUE THREAD

**Issue by nimeng1299** [Mrs4s/go-cqhttp#1722]
py用nonebot可以很好的调用gocq
但在c++我还没找到像这样的插件（也许是我没找到）
希望能写一个差不多的头文件

**Comment by zhzhongshi** [comment]
[MiraiCQ](https://github.com/super1207/MiraiCQ) 或许可以帮到你

**Comment by nimeng1299** [comment]
> [MiraiCQ](https://github.com/super1207/MiraiCQ) 或许可以帮到你

MraiCQ的开发CDK似乎已经过时且不在更新了，例如[cqcppsdk](https://github.com/kyubotics/cqcppsdk)

**Comment by Mrs4s** [comment]
可以自己调用HTTP API, gocq不提供native api
