### ISSUE TITLE
[Bug]: 合并转发歌曲无显示

### ISSUE THREAD

**Issue by Klutton** [Mrs4s/go-cqhttp#1727]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

使用了如下json（的messages）传给/send_group_forward_msg
[{'type': 'node', 'data': {'name': '1', 'uin': '3444837140', 'content': [{'type': 'music', 'data': {'type': '163', 'id': '523035658'}}]}}, {'type': 'node', 'data': {'name': '2', 'uin': '3444837140', 'content': [{'type': 'music', 'data': {'type': '163', 'id': '1840780174'}}]}}, {'type': 'node', 'data': {'name': '3', 'uin': '3444837140', 'content': [{'type': 'music', 'data': {'type': '163', 'id': '1824020871'}}]}}]

### 期望的结果是什么？

![图片](https://user-images.githubusercontent.com/113648660/194918402-795361d6-bfdc-460f-9921-8016fdf3add1.png)
![Uploading 图片.png…]()
（期望结果只转发了一条）
在gocqhttp上显示我手动转发的是以id为内容的cq的content的转发消息

### 实际的结果是什么？

![图片](https://user-images.githubusercontent.com/113648660/194918523-96a8369e-9f06-49ee-8b57-d64f519de6c8.png)
![图片](https://user-images.githubusercontent.com/113648660/194918837-0d35f700-4ff9-4e01-88b7-3719ee022339.png)

### 补充说明（可选）

已经调试多次，不排除大脑因为太晚了犯病的可能性，不过确实是有过了几次代码打算打完issue睡觉，如果有问题请您指出，非常感谢

**Comment by wdvxdr1123** [comment]
duplicate with #1287
