### ISSUE TITLE
一次性发送三张图片,发不出去

### ISSUE THREAD

**Issue by dlfld** [Mrs4s/go-cqhttp#173]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.10
运行环境: windows server 2016 datacenter
连接方式: 只使用了5700端口进行,api请求

**bug内容**
请在这里详细描述bug的内容
一次性发送三张图片就发不出去,显示失败.
**复现方法**
请在这里分步骤的描述如何复现这个bug
一次性发送三张图片

**Comment by dailinfeng66** [comment]
版本号是v0.9.21   谢谢
