### ISSUE TITLE
[Bug][Security]: Array消息模式下发送特殊字符可以直接让ws断开连接

### ISSUE THREAD

**Issue by NepPure** [Mrs4s/go-cqhttp#1733]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

``

群里发个↑这个消息，bot直接ws断开，所有反向ws服务都会断开，然后全部重连。

100%复现

### 期望的结果是什么？

特殊字符不会导致异常

### 实际的结果是什么？

<img width="970" alt="image" src="https://user-images.githubusercontent.com/12379907/196324884-22bb0736-b872-414f-8fb7-804032516aa4.png">

### 简单的复现代码/链接（可选）

```golang
消息格式设置为`array`

``

群里发个↑这个消息
```

**Comment by Ink-33** [comment]
请确认一下特殊字符的unicode编码，或使用base64编码后在此回复特殊字符

**Comment by NepPure** [comment]
> 请确认一下特殊字符的unicode编码，或使用base64编码后在此回复特殊字符

应该是`\u5`

**Comment by Ink-33** [comment]
> > 请确认一下特殊字符的unicode编码，或使用base64编码后在此回复特殊字符
> 
> 应该是`\u5`

方便贴一下代码或者更加详细的细节吗，我这无法复现

**Comment by Mrs4s** [comment]
这个可能是你应用的问题
参考 https://libwebsockets.org/lws-api-doc-main/html/group__wsclose.html 文档
`LWS_CLOSE_STATUS_UNEXPECTED_CONDITION (1011) server is terminating the connection `
是服务端终止连接
但 `反向WS` 的情况下 gocq 是以 客户端 的身份连接的

**Comment by NepPure** [comment]
稍等我再确认一下，会尽快来补充细节

**Comment by NepPure** [comment]
<img width="967" alt="image" src="https://user-images.githubusercontent.com/12379907/196570637-e7dd7f7e-a91b-4661-8eaa-5cc429f103a2.png">

↑一定要在编辑模式下复制

<img width="170" alt="image" src="https://user-images.githubusercontent.com/12379907/196570722-6e7b57bb-5472-4379-9b39-d968cbad5304.png">

在QQ里发出的消息是上面那种问号不行，
下面那种不可见的可以触发这个问题

我分别尝试了nonebot2，C#的Sora，和nonebot1的HoshinoBot，使用**Array**模式都能重现这个问题

[特殊字符.txt](https://github.com/Mrs4s/go-cqhttp/files/9815879/default.txt)

↑我把那个特殊字符放在txt里面了，打开全文复制即可

**Comment by Mrs4s** [comment]
等我进一步测试看看

**Comment by Mrs4s** [comment]
确认是 `encoding/json` 库的问题, 我看看怎么解决比较好
