### ISSUE TITLE
[Bug]:  device lock is disable. http api may fail

### ISSUE THREAD

**Issue by luoysuan** [Mrs4s/go-cqhttp#1740]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

使用反向http时 无法调用
![image](https://user-images.githubusercontent.com/51365362/197440267-c40750e9-3f6c-45ff-a0c4-8c85b15403f4.png)

### 期望的结果是什么？

在发私聊时 回调http

### 实际的结果是什么？

并未回调

**Comment by luoysuan** [comment]
已解决

**Comment by luoysuan** [comment]
已解决

**Comment by youshou1** [comment]
> 

请问是如何解决的呢，这对我很重要

**Comment by cidaodao** [comment]
> 请问是如何解决的呢，这对我很重要

我也想知道

**Comment by ayakasuki** [comment]
怎么解决的？现在需要用到http协议

**Comment by jiangyin14** [comment]
> 怎么解决的？现在需要用到http协议

最新dev版本早已修复
