### ISSUE TITLE
[Bug]: go-cqhttp文档站疑似被墙

### ISSUE THREAD

**Issue by funnygeeker** [Mrs4s/go-cqhttp#1750]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0-rc2

### 运行环境

Windows (64)

### 运行架构

x86

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

经测试，通过浏览器直接访问文档站可获取到IP地址但无法正常的与服务器通行。

### 期望的结果是什么？

国内正常访问文档站

### 实际的结果是什么？

使用梯子之后可以正常访问

### 补充说明（可选）

（希望如果可以的话整个离线版文档供下载）

**Comment by wdvxdr1123** [comment]
[ishkong/go-cqhttp-docs](https://github.com/ishkong/go-cqhttp-docs)

**Comment by funnygeeker** [comment]
有换了几个设备，发现可能是浏览器的问题

**Comment by funnygeeker** [comment]
有换了几个设备，发现可能是浏览器的问题
