### ISSUE TITLE
[Bug]: 使用滑动验证码通过后报密码错误或被冻结

### ISSUE THREAD

**Issue by E1xP** [Mrs4s/go-cqhttp#1755]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [x] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

1 | Android Phone

### 重现步骤

在退出登录后，使用滑块验证码验证，并通过验证

### 期望的结果是什么？

正常通过登录验证

### 实际的结果是什么？

未通过验证，且密码正确，并未被封号
若通过同环境扫码则可以正常登陆

### 日志记录（可选）

```golang
[2022-11-01 14:12:13] [INFO]: 当前版本:v1.0.0-rc3 
[2022-11-01 14:12:13] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2022-11-01 14:12:13] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2022-11-01 14:12:18] [INFO]: 开始尝试登录并同步消息... 
[2022-11-01 14:12:18] [INFO]: 使用协议: Android Phone 
[2022-11-01 14:12:18] [INFO]: Protocol -> connect to server: [::ffff:183.47.102.213]:8080 
[2022-11-01 14:12:18] [WARNING]: 登录需要滑条验证码, 请选择验证方式:  
[2022-11-01 14:12:18] [WARNING]: 1. 使用浏览器抓取滑条并登录 
[2022-11-01 14:12:18] [WARNING]: 2. 使用手机QQ扫码验证 (需要手Q和gocq在同一网络下). 
[2022-11-01 14:12:18] [WARNING]: 请输入(1 - 2) (将在10秒后自动选择1)： 
[2022-11-01 14:12:21] [WARNING]: 请前往该地址验证 -> https://captcha.go-cqhttp.org/captcha?id=DfevCDE0&style=simple&aid=16&uin=2639651847&sid=6663352194716186818&cap_cd=9Ov3YCA2fllhWWQbW858Cpc7KkFCYAWf4G2bzDqfBV_HgnexiZ8x-g**&clientype=1&apptype=2 
[2022-11-01 14:12:38] [WARNING]: 登录失败: 密码错误或账号被冻结 
[2022-11-01 14:12:38] [INFO]: 按 Enter 或等待 5s 后继续....
```

### 补充说明（可选）

希望能够进一步修复该问题，若允许使用异地的滑块验证码进行验证，能进一步缓解无法与部署环境同网络扫码的问题。

**Comment by Gingmzmzx** [comment]
+1

**Comment by YangRucheng** [comment]
我也遇到了相同的问题, 重新运行go-cqhttp又能成功登陆

**Comment by MiaoXia0** [comment]
+1

**Comment by SonderXiaoming** [comment]
+1

**Comment by ol1u** [comment]
+1，多尝试几次就登录上了

**Comment by A1A2B3X** [comment]
+1 扫码也不行

**Comment by qiuchengxin** [comment]
+1 尝试很多次还是没登录上

**Comment by SakuraQuck** [comment]
+1 更换设备协议就能登上了

**Comment by E1xP** [comment]
23

**Comment by byx2020** [comment]
只能删除device.json用手机验证码登录了

**Comment by Robo5412** [comment]
下载个win版的，在自己电脑登录后把生成的“data”文件夹、device.json文件放到服务器替换文件就能登录了（或许还要一个session.token？）

**Comment by tksky1** [comment]
我目前只能让服务器开代理给手机连，才能扫码登录，其他方法都不行

**Comment by Gingmzmzx** [comment]
> 我目前只能让服务器开代理给手机连，才能扫码登录，其他方法都不行

我开代理给手机连，结果没几天ip就被封了 [悲]

**Comment by SonderXiaoming** [comment]
开设备锁，短信验证

**Comment by Spencer-star** [comment]
我开启了设备锁，删除了device.json。重新登录后未提示短信验证，直接弹出密码错误的提示。
在本地测试的时候，同样的dibian环境下，只有不填写密码的扫码登录可以使用，并且正常登录，证明账号并未冻结。
尝试修改配置文件里密码选项，无论是全角半角，是否添加单引号，都提示密码错误。使用go-cq重新生成配置文件，在重新生成的配置文件里进行修改，问题依旧。

**Comment by pasiiww** [comment]
> +1 更换设备协议就能登上了

怎么更换协议

**Comment by Spencer-star** [comment]
> 

device.json文件里修改。
最好是先删除了，然后让他重新生成一个，然后把protocol改成1（实际测试了2-5，只有1能用，可能是因为这个文件里还有其他配置要一起改才行。）.
在有设备锁的时候就会有短信验证的提示。
验证了短信之后就可以正常登录了。

**Comment by SakuraQuck** [comment]
只有安卓协议可以用，其他都会提示密码错误，每次我手机上机器人的号都会把gocq挤掉

**Comment by wcx929** [comment]
+1

**Comment by a974881061** [comment]
最好的解决办法就是windows电脑上下载一个go-cqhttp，然后和手机在同一个wifi下扫码登陆，登录成功把设备文件和token文件都上传服务器，这样服务器就能正常登录了

**Comment by LittleNightmare** [comment]
本地通过qq扫描登录后，上传`device.json`（同时也上传了`session.token`但我没在我服务器看见这个文件，可能之前挂了自动删了？）然后就能用了

**Comment by XiongJJ-XD** [comment]
> > 
> 
> device.json文件里修改。 最好是先删除了，然后让他重新生成一个，然后把protocol改成1（实际测试了2-5，只有1能用，可能是因为这个文件里还有其他配置要一起改才行。）. 在有设备锁的时候就会有短信验证的提示。 验证了短信之后就可以正常登录了。

感谢，自己的号被封了一天后登陆不上了，开启设备锁后修改protocol成功登录。

**Comment by Mrs4s** [comment]
已修复

**Comment by Night-GUA** [comment]
为什么我还是不行

**Comment by jiangyin14** [comment]
> 为什么我还是不行

贴日志 不贴日志就不要问问题
