### ISSUE TITLE
[Bug]: 使用go-cqhttp发送群消息，私聊消息无法发送

### ISSUE THREAD

**Issue by 475420186** [Mrs4s/go-cqhttp#1758]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

Windows (64)

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

使用go-cqhttp可以登录QQ，在控制台中查看消息
现在我想用Python发送消息到群或个人，执行程序后代码没有报错，但是QQ也没有收到发出去的消息

### 期望的结果是什么？

QQ群，个人可以收到消息

### 实际的结果是什么？

QQ群，个人未收到消息

### 简单的复现代码/链接（可选）

```golang
import socket
def send_msg(resp_dict):
    client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    ip = '113.96.18.253'

    client.connect((ip, 8080))
    msg_type = resp_dict['msg_type']  # 回复类型（群聊/私聊）
    number = resp_dict['number']  # 回复账号（群号/好友号）
    msg = resp_dict['msg']  # 要回复的消息
    # 将字符中的特殊字符进行url编码
    msg = msg.replace(" ", "%20")
    msg = msg.replace("\n", "%0a")
    if msg_type == 'group':
        payload = "GET /send_group_msg?group_id=" + str(
            number) + "&message=" + msg + " HTTP/1.1\r\nHost:" + ip + ":8080\r\nConnection: close\r\n\r\n"
    elif msg_type == 'private':
        payload = "GET /send_private_msg?user_id=" + str(
            number) + "&message=" + msg + " HTTP/1.1\r\nHost:" + ip + ":8080\r\nConnection: close\r\n\r\n"
    print("发送" + payload)
    client.send(payload.encode("utf-8"))
    client.close()
    return 0
if __name__ == '__main__':

    resp_dict = {'msg_type': 'group', 'number': '74339853', 'msg': '大家还好吗'}
    send_msg(resp_dict)
    resp_dict = {'msg_type': 'private', 'number': '994774147', 'msg': '你好'}
    send_msg(resp_dict)
```

**Comment by hfuulzy** [comment]
我今天遇到了一样的问题，通过查看日志发现报warning说临时会话已关闭。所以应该是这个功能被关闭了防止机器人被封号。
