### ISSUE TITLE
希望在图片过大时进行拦截

### ISSUE THREAD

**Issue by Ninzore** [Mrs4s/go-cqhttp#176]
**环境信息**
go-cqhttp版本: v0.9.20
运行环境: 任意
连接方式: 任意

**bug内容**
由于图片过大而导致发送失败时，bot目前会发送一段CQ码非常影响观感  
建议对大图进行拦截而不是发送原文

**复现方法**
随便找个大图发就行了

**Comment by chenxuxin188** [comment]
可以试着自己在后台把图片压到12MB以内

**Comment by Mrs4s** [comment]
目前已支持设置忽略错误的CQ码
