### ISSUE TITLE
[Bug]: 每次启动的时候，端口都会更换

### ISSUE THREAD

**Issue by A9ccive** [Mrs4s/go-cqhttp#1763]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc2

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

2 | Android Watch

### 重现步骤

每次启动都会更换端口
![WG2RLJ5VW7C$WZAU9C4 RH](https://user-images.githubusercontent.com/68762403/201701327-13755168-090f-43e3-9693-eabd9eeaa971.png)
![67LD7C9X06(FSJGCVR~8Q4B](https://user-images.githubusercontent.com/68762403/201701361-0224fb4a-de03-483d-951f-ef4272d16b92.png)

### 期望的结果是什么？

端口固定为一个

### 实际的结果是什么？

每次启动都会更换端口

**Comment by fizz-stack** [comment]
你的配置有问题，ip和端口没有正确缩进
