### ISSUE TITLE
[Bug]: 群打卡功能无法使用

### ISSUE THREAD

**Issue by CNlongY-Py** [Mrs4s/go-cqhttp#1767]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

Windows (64)

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

HTTP发送GET /send_group_sign 

### 期望的结果是什么？

群内打卡

### 实际的结果是什么？

群内无打卡且控制台没有任何反馈
无论后面接的什么数值都会返回{"data":null,"retcode":0,"status":"ok"}

### 简单的复现代码/链接（可选）

```golang
http://localhost:5700/send_group_sign
```

### 日志记录（可选）

```golang
没 有 反 馈
```

**Comment by synodriver** [comment]
这个功能是我写的……我刚才试了，好的很

**Comment by synodriver** [comment]
应该是你被tx标记了

**Comment by synodriver** [comment]
你加了群号吗（

**Comment by CNlong-Py** [comment]
加了群号和没加群号的反馈是一样的

**Comment by Ink-33** [comment]
看看你调用这个接口的代码

**Comment by CNlong-Py** [comment]
我直接浏览器测试的

**Comment by Ink-33** [comment]
你浏览器地址栏输的完整内容是什么
gocq配置里面打开debug模式，也一起贴一下执行结果

**Comment by CNlong-Py** [comment]
PS C:\Users\Administrator> curl

位于命令管道位置 1 的 cmdlet Invoke-WebRequest
请为以下参数提供值:
Uri: http://localhost:5700/send_group_sign?group_id=114514群号


StatusCode        : 200
StatusDescription : OK
Content           : {"data":null,"retcode":0,"status":"ok"}


[2022-11-16 22:46:09] [DEBUG]: HTTPServer接收到API调用: send_group_sign
[2022-11-16 22:46:09] [DEBUG]: Protocol -> rev pkt: OidbSvc.0xeb7 seq: 13956
[2022-11-16 22:46:09] [DEBUG]: Protocol -> Unhandled Command: OidbSvc.0xeb7
Seq: 13956

**Comment by q8018414** [comment]
实际上,我不管怎么测试都没有办法成功打卡。

**Comment by CNlong-Py** [comment]
或许是这个API代码的问题?

**Comment by q8018414** [comment]
![image](https://user-images.githubusercontent.com/70793915/206864934-98107bec-9830-487a-9cd9-7bb3f5a51ad7.png)
哇，兄弟。你这是24小时在线吗。。秒回。。

**Comment by CNlong-Py** [comment]
等了超级久了,还没解决

**Comment by q8018414** [comment]
![image](https://user-images.githubusercontent.com/70793915/206864996-75abb15f-8e1d-47e0-b17c-8b9f66ddf39e.png)
看代码是有这个API接口的。会不会时打包的问题？好神奇

**Comment by CNlong-Py** [comment]
我现在再试试

**Comment by CNlong-Py** [comment]
还是不行,依然{"data":null,"retcode":0,"status":"ok"}

**Comment by Ink-33** [comment]
登号看看打上没

**Comment by q8018414** [comment]
我用的docker的1.0.4版本。。直接报没有相关API

**Comment by CNlong-Py** [comment]
没有

**Comment by CNlong-Py** [comment]
我用的[go-cqhttp_windows_386.exe]
1.0.0-rc3

**Comment by Ink-33** [comment]
试试这个https://github.com/Mrs4s/go-cqhttp/suites/9705071225/artifacts/465149478

**Comment by q8018414** [comment]
可惜了不知道是不是作者docker没有更新了。。。

**Comment by CNlongY-Py** [comment]
升级到rc4就没问题了 难蚌
