### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by a974881061** [Mrs4s/go-cqhttp#1776]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

CentOS

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

本想做一个小红书图片去水印的机器人的，当我发送一次小红书分享链接时，日志中会不规则出现一次甚至是多次的这次消息，time和message_id也是一模一样，不存在我发送多次消息。

### 期望的结果是什么？

![image](https://user-images.githubusercontent.com/60080834/203554706-986f47f6-4eff-491e-989c-6e55498dc768.png)
只收到一条消息

### 实际的结果是什么？

一次甚至多条相同消息

**Comment by Ink-33** [comment]
出现这种情况有一个非常普遍的可能性：你的http服务端并没有正确的返回http响应头，导致gocq触发超时重试

需要您提供gocq log以及您的服务端的部分处理代码
