### ISSUE TITLE
功能建议: 希望添加频道申请事件

### ISSUE THREAD

**Issue by nnnn123456789** [Mrs4s/go-cqhttp#1779]
像加群申请一般的加入频道申请事件.

期望的参数: 频道id, 请求人id, 请求消息, 请求id, 请求人详细信息. 
快速操作: 批准/拒绝.

对应API: 审核频道加入请求API. 参数: 请求id, 通过状态, 拒绝原因.

**Comment by Mrs4s** [comment]
频道功能短期不会再研究了
