### ISSUE TITLE
无法接受到单向好友信息

### ISSUE THREAD

**Issue by corvo007** [Mrs4s/go-cqhttp#178]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.21-fix1
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
我有两个号全用的go-cqhttp，但有一个始终无法接受到单向好友或临时会话消息，尝试：
更新到最新release版本
用MiraiOK搭配cqhttp-mirai
更换服务器
删除device.json并重新生成
开VIP
更换监听端口
均无效，而另一个使用v0.9.19完全没有这些问题

**复现方法**
开启go-cqhttp与后端，向bot发送消息，窗口中**无任何信息出现**，若更换为MiraiOK搭配cqhttp-mirai，则**显示"Unknown message type xxxxxxxx: xxxxxxx"**，如图：
![WXMDLML2 WGIH)GFF_5LSME](https://user-images.githubusercontent.com/67192165/91007769-631d8b80-e60f-11ea-8fa9-88b993f242a4.png)
![U_%SV1LAJZ1Z@~DO_JW`_(4](https://user-images.githubusercontent.com/67192165/91007778-6749a900-e60f-11ea-8dd9-48460e497f60.png)

![I($AYWX%S3YREB0}A7J4@I9](https://user-images.githubusercontent.com/67192165/91007798-703a7a80-e60f-11ea-8c72-c65e6daa55dc.png)
![CNH%5~$0KH(FQKAPR`AWWH7](https://user-images.githubusercontent.com/67192165/91007804-73356b00-e60f-11ea-8efb-f6d4904cb3c0.png)

**Comment by corvo007** [comment]
补充：直至今天上午11点还能回复，一点半左右就彻底哑火了

**Comment by Mrs4s** [comment]
单向好友消息目前还不支持

**Comment by Mrs4s** [comment]
#98
