### ISSUE TITLE
[Bug]: 发送消息失败

### ISSUE THREAD

**Issue by coWhy** [Mrs4s/go-cqhttp#1781]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

MacOS

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

在ARM环境
 {"auto_escape":false,"group_id":680634950,"message":"今日算法已打卡题目数量: 5\n标题是: LeetCode热题100道-Day01\n分别是: 两数之和1，value存具体下标，测试,"message_type":"discuss","user_id":750208720} 
主要是message部分

可以试下足够长的字符串 和 较短的 较短的可以但是有限制，足够长的有时候可以，有时候不行，但是如果全是英文一点问题都没有 不知道是什么情况

一直报错
[GIN] 2022/11/25 - 23:48:59 | 200 |      39.291µs |       127.0.0.1 | POST     "/v1/cq/callback/8dface1f5821465b8ba4fd303a99fd16"
{"post_type":"message","message_type":"private","time":1669391340,"self_id":2719190494,"sub_type":"group","user_id":750208720,"message":"测试","raw_message":"测试","font":0,"sender":{"age":0,"group_id":680634950,"nickname":"linbot","sex":"unknown","user_id":750208720},"temp_source":0,"message_id":13008}

{"data":null,"msg":"SEND_MSG_API_ERROR","retcode":100,"status":"failed","wording":"请参考 go-cqhttp 端输出"}

### 期望的结果是什么？

期望能发出消息

### 实际的结果是什么？

没有发出去

### 简单的复现代码/链接（可选）

```golang
package tests

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"github.com/tidwall/gjson"
	"github.com/xiao-ren-wu/restgo"
	"go.uber.org/zap"
	"io"
	"net/http"
	"testing"
)

func CqCallback(ctx *gin.Context) {

	dataReader := ctx.Request.Body

	rawData, _ := io.ReadAll(dataReader)

	fmt.Println(string(rawData))

	postType, _, _, _, _, _, message := getRelationTypes(rawData)
	if postType == "message" {

		if message == "测试" {
			//str1 := "出游日期：11月27日\n行程安排如下：\n1、11:30 （参考时间）自行前往福满屯玺大铁锅（虹桥天街店）集合聚餐\n2、13:00 步行前往水裹.汤泉生活\n3、13:20 根据需求自行进行泡汤、汗蒸活动\n\n地址：申长路虹桥商务区龙湖虹桥天街B馆H栋B1层（虹桥英迪格酒店对面）\n出行方式：17号线到虹桥火车站--步行933米（约13分钟）至福满屯玺大铁锅（虹桥天街店）--步行297米(约4分钟)至水裹.泉生活\n水裹汤泉其他项目（自行了解，自费）\n注意：本次浴资票为单日6小时（例如：13点进场，需在19点之前离场），需要小伙伴们注意时间，超过时间需自费"
			str := "出游日期：11月27日\n行程安排如下：\n标题是:LeetC1\n分别是:两数之和1，value存具体下标，测试2，我想啊实打实测试，两数之和5\n完成进度为: 100.00%"
			//m := gjson.Result{
			//	Type: gjson.String,
			//	//Raw:  str,
			//	Str: str1,
			//}

			req := map[string]any{
				//"reply": str,
				"message_type": "private",
				"user_id":      750208720,
				"group_id":     680634950,
				"message":      str,
				"auto_escape":  false,
			}
			//

			resp, err := restgo.NewHttpBuilder().
				ContentType(restgo.ApplicationJson).
				Payload(req).
				Send(restgo.POST, fmt.Sprintf("http://localhost:8699/send_private_msg"))

			fmt.Println(resp.BodyStr())

			if err != nil {
				panic(err)
			}

		}

		ctx.JSONP(http.StatusOK, "")
	}
}

func getRelationTypes(bytes []byte) (string, string, string, string, string, string, string) {

	postType := gjson.Get(string(bytes), "post_type").String()

	messageType := gjson.Get(string(bytes), "message_type").String()

	subType := gjson.Get(string(bytes), "sub_type").String()

	noticeType := gjson.Get(string(bytes), "notice_type").String()

	requestType := gjson.Get(string(bytes), "request_type").String()

	metaEventType := gjson.Get(string(bytes), "meta_event_type").String()

	message := gjson.Get(string(bytes), "message").String()

	zap.S().Infof("[ post_type: %s, ( message_type: %s，sub_type: %s ), notice_type: %s, request_type: %s, meta_event_type: %s]",
		postType, messageType, subType, noticeType, requestType, metaEventType,
	)

	return postType, messageType, subType, noticeType, requestType, metaEventType, message

}

func TestHttp(t *testing.T) {
	engine := gin.Default()
	engine.POST("v1/cq/callback/8dface1f5821465b8ba4fd303a99fd16", CqCallback)
	_ = engine.Run(":8700")
}
```

**Comment by Mrs4s** [comment]
尝试更新最新版再看看
