### ISSUE TITLE
[Bug]: 使用滑条验证，登录网址后404 not found

### ISSUE THREAD

**Issue by xy-cloud-cn** [Mrs4s/go-cqhttp#1785]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

正常填写密码
[2022-12-02 21:27:04] [WARNING]: 登录需要滑条验证码, 请选择验证方式:
[2022-12-02 21:27:04] [WARNING]: 1. 使用浏览器抓取滑条并登录
[2022-12-02 21:27:04] [WARNING]: 2. 使用手机QQ扫码验证 (需要手Q和gocq在同一网络下).
[2022-12-02 21:27:04] [WARNING]: 请输入(1 - 2) (将在10秒后自动选择1)：
1

### 期望的结果是什么？

正常使用滑条验证

### 实际的结果是什么？

访问网址时出现404 not found，并且未超过有效时长

**Comment by BEshakalaka** [comment]
我也出现了这个问题，不晓得为什么，控制台出现了https://captcha.go-cqhttp.org/captcha?id=xxx地址，点进去，浏览器就显示”404 page not found“怀疑可能是服务端出现了问题...

**Comment by Mrs4s** [comment]
目前还在修改验证码处理器, TX改了一些东西

**Comment by xy-cloud-cn** [comment]
点错close了

**Comment by ConstasJ** [comment]
要不还是在docs里面重新加一个手动抓ticket的文档吧
昨天我就是自行上ssl.captcha.qq.com抓的
（简而言之，就是把”https://captcha.go-cqhttp.org/captcha?id=xxx&”后面的一大串字符直接贴到"https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?"然后在浏览器访问，并通过DevTools抓取一个通过验证后的请求，把JSON响应里的ticket直接贴到gocq即可）

**Comment by moxisuki** [comment]
> 要不还是在docs里面重新加一个手动抓ticket的文档吧 昨天我就是自行上ssl.captcha.qq.com抓的 （简而言之，就是把"[https://captcha.go-cqhttp.org/captcha?id=xxx&"后面的一大串字符直接贴到"https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?"然后在浏览器访问，并通过DevTools抓取一个通过验证后的请求，把JSON响应里的ticket直接贴到gocq即可）](https://captcha.go-cqhttp.org/captcha?id=xxx&%22%E5%90%8E%E9%9D%A2%E7%9A%84%E4%B8%80%E5%A4%A7%E4%B8%B2%E5%AD%97%E7%AC%A6%E7%9B%B4%E6%8E%A5%E8%B4%B4%E5%88%B0%22https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?%22%E7%84%B6%E5%90%8E%E5%9C%A8%E6%B5%8F%E8%A7%88%E5%99%A8%E8%AE%BF%E9%97%AE%EF%BC%8C%E5%B9%B6%E9%80%9A%E8%BF%87DevTools%E6%8A%93%E5%8F%96%E4%B8%80%E4%B8%AA%E9%80%9A%E8%BF%87%E9%AA%8C%E8%AF%81%E5%90%8E%E7%9A%84%E8%AF%B7%E6%B1%82%EF%BC%8C%E6%8A%8AJSON%E5%93%8D%E5%BA%94%E9%87%8C%E7%9A%84ticket%E7%9B%B4%E6%8E%A5%E8%B4%B4%E5%88%B0gocq%E5%8D%B3%E5%8F%AF%EF%BC%89)

支持

**Comment by ConstasJ** [comment]
现在captcha.go-cqhttp.org已经修好了。
不过我还是认为在doc里加上一个手动抓取ticket教程是个不错的主意
