### ISSUE TITLE
[Bug]: 正常运行两天后出错退出,重启又正常工作.

### ISSUE THREAD

**Issue by brestain** [Mrs4s/go-cqhttp#1789]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc1

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

正常运行约两天后报错退出,重启则正常运行.此现象已出现两次.

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

异常退出

### 日志记录（可选）

```golang
[2022-12-04 16:40:39] [ERROR]: Protocol -> panic on decoder MultiMsg.ApplyDown : runtime error: index out of range [0] with length 0
goroutine 197617 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
	github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:332 +0x5d
panic({0xb42f80, 0xc0000201f8})
	runtime/panic.go:1038 +0x215
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse(0xc000024140, 0x49, {0xc000024140, 0x49, 0x49})
	github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/multimsg.go:102 +0x885
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0005109b0)
	github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:343 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
	github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:329 +0x697
 
[2022-12-04 16:40:39] [ERROR]: 出现错误 packet decode error: MultiMsg.ApplyDown - runtime error: index out of range [0] with length 0. 详细信息已转储至文件 dumps/1669225044.dump 请连同日志提交给开发者处理
```

### 补充说明（可选）

[1669225044.zip](https://github.com/Mrs4s/go-cqhttp/files/10163293/1669225044.zip)

**Comment by wdvxdr1123** [comment]
duplicate with #1251
