### ISSUE TITLE
parse incoming packet error: invalid payload

### ISSUE THREAD

**Issue by xiaokaizhi** [Mrs4s/go-cqhttp#179]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.21-fix
运行环境: windows_amd64
连接方式: http

**bug内容**
[2020-08-24 15:03:07] [INFO]: 开始加载群列表...
2020/08/24 15:03:08 parse incoming packet error: invalid payload

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by xiaokaizhi** [comment]
关掉第二次打开就卡在开始加载群列表...  这里。新版本不是默认异步加载了吗怎么还是卡主了

**Comment by Mrs4s** [comment]
服务器是海外的？

**Comment by xiaokaizhi** [comment]
呵呵。国内的。我登录qq挺快的。打开qq网站也很快：（）

**Comment by xiaokaizhi** [comment]
[2020-08-24 **15:03:07**] [INFO]: 开始加载群列表...
2020/08/24 **15:03:08** parse incoming packet error: invalid payload

这个两条消息相隔1秒并没有等待很久

**Comment by xiaokaizhi** [comment]
我试过了v0.9.20版本没问题：（）

**Comment by Mrs4s** [comment]
请尝试 https://github.com/Mrs4s/go-cqhttp/actions/runs/223399207 这个版本

**Comment by Mrs4s** [comment]
理论上已修复 如还有问题请Reopen
