### ISSUE TITLE
[Bug]: mac m1 配置文件位置不对

### ISSUE THREAD

**Issue by xiseliuli** [Mrs4s/go-cqhttp#1790]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

MacOS

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

WebSocket (反向)

### 使用协议

3 | MacOS

### 重现步骤

$ ./go-cqhttp

### 期望的结果是什么？

若go-cqgttp目录下无配置文件则生成新的
若有配置文件，则使用配置文件

### 实际的结果是什么？

go-cqhttp 把配置文件生成在了 ~ 文件夹下

**Comment by xiseliuli** [comment]
<img width="742" alt="image" src="https://user-images.githubusercontent.com/51782608/206081208-58043eb4-f225-46ac-a990-e1105f6be5e7.png">

**Comment by xiseliuli** [comment]
我的问题，当我使用右键菜单启动时，配置文件会生成在 ～ 目录下，使用命令启动，配置文件生成位置正确

**Comment by zhc-1999** [comment]
能否生成在当前目录下，我感觉这样会比较好一点
