### ISSUE TITLE
[Bug]: 使用QQ新electron架构客户端（Mac）发送的图片bot端收到的图片地址http404

### ISSUE THREAD

**Issue by Guanyunhan** [Mrs4s/go-cqhttp#1795]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

2 | Android Watch

### 重现步骤

使用QQ新electron架构客户端（Mac）发送图片，bot端可以收到图片地址，但是http访问404，将图片通过手机客户端转发一次就正常了，疑似新版客户端使用了新的协议

### 期望的结果是什么？

修复bot端收不到图片的问题

### 实际的结果是什么？

bot端收不到图片

**Comment by Guanyunhan** [comment]
electron版客户端发出的图片地址：[CQ:image,file=61e198fc109d7c211fadf6324280251b.image,url=https://c2cpicdw.qpic.cn/offpic_new/0/Chh1XzJHR096dS1IOEdkZll6NV83X0VtUkESFLAMfhJWeVDQB9n5liwjxa9fFcG6GMJ-IP4KKPSV77y1-PsCMLm76AM4t9-c0w9YgIl6/0?term=3]
手机客户端发出的图片地址：[CQ:image,file=61e198fc109d7c211fadf6324280251b.image,url=https://c2cpicdw.qpic.cn/offpic_new/【QQ号】//【QQ号】-898734885-61E198FC109D7C211FADF6324280251B/0?term=2&amp;is_origin=0]

**Comment by dmlgzs** [comment]
我给 OICQ PR 了，https://github.com/takayama-lily/oicq/pull/475
~~只要有人移植到 MiraiGo 就好了~~

**Comment by yoyodi** [comment]
我也是使用新版MAC端QQ(版本: 6.9.10 (9733, 8336))向bot端发送图片，bot端收到的图片地址是这个样子：
[CQ:image,file=df38b456a924206cadccc22886fac2a3.image,subType=0,url=https://gchat.qpic.cn/download?appid=1407&amp;fileid=Chh1X0ZtaG8yMEhTYUpfVDRCZ2Z1UkVDYmcSFPDuWpSLYmNwcuEUxCgb2GwqyJShGPRxIP8KKP_F-KC6vv0CMP-16AM4pLbq3QFQgL2jAViAiXo&amp;rkey=CAMSSJY5X_KUSNXs_XO5PxSKElSSnK4HR02U2puv5_Q97N19WYSgDayT4WLth8w_5b1OxKiT6OwP2oPUgjTOJ6Bq0wDyChxggTJC3Q&amp;spec=0]
HTTP访问提示ERROR 400
协议protocol = 2
版本go-cqhttp rc0.4
连接方式HTTP
运行环境Ubuntu20.04 x64

**Comment by huankong233** [comment]
> 我也是使用新版MAC端QQ(版本: 6.9.10 (9733, 8336))向bot端发送图片，bot端收到的图片地址是这个样子： [CQ:image,file=df38b456a924206cadccc22886fac2a3.image,subType=0,url=https://gchat.qpic.cn/download?appid=1407&fileid=Chh1X0ZtaG8yMEhTYUpfVDRCZ2Z1UkVDYmcSFPDuWpSLYmNwcuEUxCgb2GwqyJShGPRxIP8KKP_F-KC6vv0CMP-16AM4pLbq3QFQgL2jAViAiXo&rkey=CAMSSJY5X_KUSNXs_XO5PxSKElSSnK4HR02U2puv5_Q97N19WYSgDayT4WLth8w_5b1OxKiT6OwP2oPUgjTOJ6Bq0wDyChxggTJC3Q&spec=0] HTTP访问提示ERROR 400 协议protocol = 2 版本go-cqhttp rc0.4 连接方式HTTP 运行环境Ubuntu20.04 x64

同问题，找到解决办法了吗

**Comment by huankong233** [comment]
> 我也是使用新版MAC端QQ(版本: 6.9.10 (9733, 8336))向bot端发送图片，bot端收到的图片地址是这个样子： [CQ:image,file=df38b456a924206cadccc22886fac2a3.image,subType=0,url=https://gchat.qpic.cn/download?appid=1407&fileid=Chh1X0ZtaG8yMEhTYUpfVDRCZ2Z1UkVDYmcSFPDuWpSLYmNwcuEUxCgb2GwqyJShGPRxIP8KKP_F-KC6vv0CMP-16AM4pLbq3QFQgL2jAViAiXo&rkey=CAMSSJY5X_KUSNXs_XO5PxSKElSSnK4HR02U2puv5_Q97N19WYSgDayT4WLth8w_5b1OxKiT6OwP2oPUgjTOJ6Bq0wDyChxggTJC3Q&spec=0] HTTP访问提示ERROR 400 协议protocol = 2 版本go-cqhttp rc0.4 连接方式HTTP 运行环境Ubuntu20.04 x64

新版的已经可以用了，但是需要替换几个字符
![image](https://github.com/Mrs4s/go-cqhttp/assets/49610758/e0970831-540c-4bd1-b599-36906941f94c)
url中的`amp;`替换为空即可直接打开
