### ISSUE TITLE
使用正整数作为消息ID

### ISSUE THREAD

**Issue by mnixry** [Mrs4s/go-cqhttp#18]
目前go-cqhttp的消息ID似乎为int32，但是由于cqhttp原有的消息ID是递增的正整数
为了保证兼容性，是否可以考虑把消息ID全部改为正整数？（递增就不用了）

**Comment by Mrs4s** [comment]
暂时不会做这方面的更改, 因为原CQ的msg id是它自己数据库的主键，而QQ只提供群内的msg id(int32)，为了保证兼容性，目前的全局ID是我自己计算的.
目前全局ID算法为`CRC32("{group-id}-{msg-id}".ToBytes())`. 所以会存在负数.
