### ISSUE TITLE
[Bug]: device.json protocol:5，即协议是ipad，但扫码登陆时仍提示是手表QQ

### ISSUE THREAD

**Issue by hfuulzy** [Mrs4s/go-cqhttp#1807]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

V1.0.0.0-rc3

### 运行环境

Linux

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

删除device.json和session.token，
./go-cqhttp    重新生成设备信息
扫码登陆
提示手表QQ

### 期望的结果是什么？

登陆设备是Ipad

### 实际的结果是什么？

手表QQ

**Comment by Gingmzmzx** [comment]
+1

**Comment by Mrs4s** [comment]
显示不影响

**Comment by hfuulzy** [comment]
> 显示不影响

 实际走的确实是安卓设备，在devices里能看到属性是Android，虽然通信协议还是5。至于实际的通信协议我不清楚
 我曾经碰巧遇到过设备显示是pad，在我的设备里也能看到已登录的是pad
至于说到底有没有什么影响， 目前没感知到，但我觉得这确实是个bug
