### ISSUE TITLE
使用[CQ:music]的image参数，但是在电脑端不能正常显示图片，手机端正常

### ISSUE THREAD

**Issue by lizkes** [Mrs4s/go-cqhttp#181]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.21-fix1
运行环境: docker-debian10
连接方式: 反向WS

**bug内容**

桌面端不显示图片
![snipaste_20200824_194730](https://user-images.githubusercontent.com/20457790/91041492-bc52e280-e642-11ea-9afd-7072b240d6f1.png)

手机端正常显示
![snipaste_20200824_194837](https://user-images.githubusercontent.com/20457790/91041545-d55b9380-e642-11ea-8b91-3437415f315c.png)
**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by KontorNoLimit** [comment]
有一类似问题是图片格式为webp引发的。非官方解答

**Comment by lizkes** [comment]
https://p1.music.126.net/S3liZdT3hhoNjIyXdmYAxA==/7873602766692554.jpg
这是图片的网络地址，是jpg格式

**Comment by lizkes** [comment]
目前发现通过网易云API获取的图片url来作为image时，会出现上述情况。
但是用QQ音乐API获取的图片url作为image时，电脑端和手机端都能正常显示

**Comment by lizkes** [comment]
发一张QQ音乐API获取的图片url作为对比
https://y.gtimg.cn/music/photo_new/T002R500x500M000003OLhsS1qBloo.jpg

**Comment by Ink-33** [comment]
电脑端不显示music的img是老特性了，似乎有域名白名单。想解决可能要把CQ:music对应的xml给重写了

**Comment by Mrs4s** [comment]
目前暂时请使用 `type=163` 或者 `type=qq` 这两个在最新版本改为了小程序发送, 会更稳定.
