### ISSUE TITLE
[Bug]: 国外vps登陆提示错误，比如说hax的vps不能登陆cq，你看有什么解决方案？

### ISSUE THREAD

**Issue by a2748556650** [Mrs4s/go-cqhttp#1810]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0

### 运行环境

CentOS

### 运行架构

None

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

在国外vps的hax安装完毕后配置，然后执行./go-cqhttp之后就提示报错

### 期望的结果是什么？

解决报错问题

### 实际的结果是什么？

解决报错问题

**Comment by yucho123987** [comment]
用Debian系可以，但是我无法登录我的QQ，无论如何都是密码错误或者被封

**Comment by xiangxiangxiong9** [comment]
> 用Debian系可以，但是我无法登录我的QQ，无论如何都是密码错误或者被封

用Android Phone `"protocol":1`

**Comment by yucho123987** [comment]
> > 用Debian系可以，但是我无法登录我的QQ，无论如何都是密码错误或者被封
> 
> 用Android Phone `"protocol":1`

问题解决了，感谢

**Comment by a2748556650** [comment]
> > 用Debian系可以，但是我无法登录我的QQ，无论如何都是密码错误或者被封
> 
> 用Android Phone `"protocol":1`

可以不用debian吗？国外vps内存才1g，有办法解决吗？

**Comment by xiangxiangxiong9** [comment]
> > > 用Debian系可以，但是我无法登录我的QQ，无论如何都是密码错误或者被封
> > 
> > 
> > 用Android Phone `"protocol":1`
> 
> 可以不用debian吗？国外vps内存才1g，有办法解决吗？

提示什么报错0.0

**Comment by yucho123987** [comment]
> > > > > 用Debian系可以，但是我无法登录我的QQ，无论如何都是密码错误或者被封
> > > > 
> > > > 
> > > > 用Android Phone `"protocol":1`
> > > 
> > > 
> > > 可以不用debian吗？国外vps内存才1g，有办法解决吗？
> > 
> > 
> > 提示什么报错0.0
> 
> ![image](https://user-images.githubusercontent.com/81173949/209151374-e3109f94-c4bd-4334-ba6a-8a0cdebb82a5.png)

我猜你用的是Hax的免费VPS，我的机器人也是跑在Hax VPS上的。Hax VPS默认情况下只能访问ipv6，而腾讯QQ服务器只有ipv4的地址，所以会出现这种情况。要解决这种情况，可以安装warp。下面的代码可以快速安装warp：
```
wget -N https://raw.githubusercontent.com/fscarmen/warp/main/menu.sh && bash menu.sh
```
