### ISSUE TITLE
希望可以添加创建群聊功能

### ISSUE THREAD

**Issue by li1553770945** [Mrs4s/go-cqhttp#1820]
**环境信息**

go-cqhttp版本: [v1.0.0-rc3](https://github.com/Mrs4s/go-cqhttp/releases/tag/v1.0.0-rc3) 

**需要添加的功能内容**

目前onebot标准中没有相关标准，请问是否可以添加创建群聊功能，以及拉人进群功能呢？

**Comment by qianjunakasumi** [comment]
MiraiGo 中声明为防止滥用，不支持主动邀请新成员进群。单独新建群聊的功能没有实际意义，大概率不会支持。

**Comment by li1553770945** [comment]
奥好的，其实我是想做一个oncall系统，就是用户向机器人发送特定问题，机器人拉问题对应的负责人和提问者建立一个群聊，中途还可以拉更多人进群，这样解决问题特别方便，既然不支持那就算了。
谢谢您的回复！
