### ISSUE TITLE
[Bug]: 获取合并转发失败

### ISSUE THREAD

**Issue by StarAdmire** [Mrs4s/go-cqhttp#1822]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

最新版本

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

当获取合并转发的消息中包含私聊消息时就会报错，群聊消息就正常

### 期望的结果是什么？

正常获取内容

### 实际的结果是什么？

控制台报错，无返回内容
2022/12/28 11:41:45 http: panic serving 127.0.0.1:56612: runtime error: invalid memory address or nil pointer dereference
goroutine 328 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1825 +0xbf
panic({0x7d8f00, 0xd0e180})
        runtime/panic.go:844 +0x258
github.com/Mrs4s/MiraiGo/client.(*forwardMsgLinker).link(0xc0000e3898, {0x892db2?, 0xc000254088?})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/multimsg.go:167 +0x1e6
github.com/Mrs4s/MiraiGo/client.(*QQClient).GetForwardMessage(0x0?, {0xc0000d4232?, 0x0?})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/multimsg.go:188 +0x165
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQGetForwardMessage(0xc0002b2b80, {0xc0000d4232?, 0x42?})
        github.com/Mrs4s/go-cqhttp/coolq/api.go:1578 +0x45
github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).call(0xc000265b20, {0xc000270146, 0xf}, {0x997260, 0xc000086420})
        github.com/Mrs4s/go-cqhttp/modules/api/api.go:93 +0x31e5
github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).Call(0xc000265b20, {0xc000270146, 0xf}, {0x997260, 0xc000086420})
        github.com/Mrs4s/go-cqhttp/modules/api/caller.go:34 +0xaa
github.com/Mrs4s/go-cqhttp/server.(*httpServer).ServeHTTP(0xc000512048, {0x99ae50, 0xc0002ec000}, 0xc000526200)
        github.com/Mrs4s/go-cqhttp/server/http.go:198 +0x827
net/http.serverHandler.ServeHTTP({0x999b50?}, {0x99ae50, 0xc0002ec000}, 0xc000526200)
        net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc00006f040, {0x99b138, 0xc000093080})
        net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        net/http/server.go:3071 +0x4db

**Comment by DreamsLing** [comment]
发送合并转发时消息带&也发不出

**Comment by wdvxdr1123** [comment]
Fixed in https://github.com/Mrs4s/MiraiGo/pull/287.
