### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by neiloe8023** [Mrs4s/go-cqhttp#1823]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

6bb98fc

### 运行环境

Windows (64)

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

使用匿名管道运行dev分支的最新版本的go-cqhttp_386.exe

### 期望的结果是什么？

可正常输入指令

### 实际的结果是什么？

无法输入指令，提示未检测到输入终端

### 补充说明（可选）

在之前的版本中都可以正常使用，怀疑新版版中是否加入了输入设备检测

**Comment by neiloe8023** [comment]
![pSS3GQS.md.png](https://s1.ax1x.com/2022/12/28/pSS3GQS.md.png)]
![pSS33z8.md.png](https://s1.ax1x.com/2022/12/28/pSS33z8.md.png)]

**Comment by Ink-33** [comment]
新版本引入了tty检测 #1772

**Comment by neiloe8023** [comment]
> 新版本引入了tty检测 #1772

好的，谢谢
