### ISSUE TITLE
[Bug]: Docker创建gocq提示权限不足（rc3可行）

### ISSUE THREAD

**Issue by Sam5440** [Mrs4s/go-cqhttp#1833]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [x] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

rc4

### 运行环境

Ubuntu

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

和rc3一样使用docker创建gocq的时候，
提示当前权限不足导致无法创建文件，
需要手动设置当前文件夹777权限才可以正常使用。

> 使用rc3版本创建的文件时候也出现同样问题，切换回rc3一切正常

### 期望的结果是什么？

可以正常创建初始化创建文件，读写目录下文件

### 实际的结果是什么？

无法创建文件

### 日志记录（可选）

```golang
usermod: no changes
---Setting umask to 002---
---Taking ownership of data...---
Starting...
```

### 补充说明（可选）

使用的都是官方镜像

**Comment by Sam5440** [comment]
---Checking if GID: 100 matches user---
usermod: no changes
---Setting umask to 002---
---Taking ownership of data...---
Starting...

**Comment by VergilGao** [comment]
你挂载到 /data 目录的文件夹权限是什么样的？
新版本增加了以非root用户（默认是 99:100 用户，可以通过指定环境变量的方式来指定用户，如 -e UID=1000 -e GID=1000）运行程序的逻辑，由此产生的所有文件的权限归属都是指定用户。如果是老版本创建的镜像产生的数据，文件归属应该是root用户。

**Comment by Sam5440** [comment]
> 你挂载到 /data 目录的文件夹权限是什么样的？ 新版本增加了以非root用户（默认是 99：100 用户，可以通过指定环境变量的方式来指定用户，如 -e UID=1000 -e GID=1000）运行程序的逻辑，由此产生的所有文件的权限归属都是指定用户。如果是老版本创建的镜像产生的数据，文件归属应该是root用户。 我写了一个说明，可以参考 #1896

看了看，对于某些无法添加自定义参数的况应该如何处理呢？

**Comment by VergilGao** [comment]
如果不支持 -e ，程序默认以 99:100 用户运行，你可以手动修改一下权限（不推荐，如果你的环境里有真实存在的 99:100 用户，那么你的 cqhttp 数据将会完全暴露给他）

**Comment by Sam5440** [comment]
好的谢谢，了解了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月23日(周四) 下午4:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Mrs4s/go-cqhttp] [Bug]: Docker创建gocq提示权限不足（rc3可行） (Issue #1833)




 
如果不支持 -e ，程序默认以 99:100 用户运行，你可以手动修改一下权限（不推荐，如果你的环境里有真实存在的 99:100 用户，那么你的 cqhttp 数据将会完全暴露给他）
