### ISSUE TITLE
[Bug]: 需要安全设备验证

### ISSUE THREAD

**Issue by dfmjndm** [Mrs4s/go-cqhttp#1835]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

rc4

### 运行环境

CentOS

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

0m[31m[2023-01-05 11:38:48] [ERROR]: Protocol -> sendPacket msg error: 需要使用安全设备验证 
[0m[33m[2023-01-05 11:38:53] [WARNING]: 群消息发送失败: 账号可能被风控. 
[0m

### 期望的结果是什么？

。

### 实际的结果是什么？

。

**Comment by dfmjndm** [comment]
如何使用安全设备验证?

**Comment by traceless0929** [comment]
> 如何使用安全设备验证?

解决了么？

**Comment by dfmjndm** [comment]
> > 如何使用安全设备验证?
> 
> 解决了么？

没有

**Comment by jieBieber** [comment]
你好！请问你这个问题解决了嘛

**Comment by cidaodao** [comment]
同问

**Comment by wling-art** [comment]
解决办法: https://github.com/Mrs4s/go-cqhttp/issues/1596#issuecomment-1190059333
