### ISSUE TITLE
临时消息发送失败

### ISSUE THREAD

**Issue by Mother-Ship** [Mrs4s/go-cqhttp#184]
**环境信息**
go-cqhttp版本: v0.9.16
运行环境: linux_amd64
连接方式: http

**bug内容**
群聊临时消息能收到上报，但是发送失败

加为好友后可以发送

希望开发者能帮助我打出go-cqhttp更详细的日志，现在控制台只有info和error级别的

顺带最新的release会丢消息。。没法验证是否修复了这个问题
**复现方法**
上号，A单向加B为好友，A调用/send_private_msg给B发群内临时消息，B收不到；B通过好友请求后能收到

**Comment by Mrs4s** [comment]
目前临时消息还不支持发送长消息, 请确认消息长度?

**Comment by Mother-Ship** [comment]
挺短的，两个数字。。
![image](https://user-images.githubusercontent.com/26121316/91080538-4cf7e580-e678-11ea-8422-b77be8d6ae2f.png)

**Comment by Mrs4s** [comment]
请尝试 https://github.com/Mrs4s/go-cqhttp/actions/runs/222349315 这个版本

**Comment by Mother-Ship** [comment]
[ERROR]: Protocol -> send msg error: 16 发送失败，请先添加对方为好友

报了这么一个错。。

**Comment by Mrs4s** [comment]
会不会是双方某一边的账号禁止了单向好友消息的接收？ 这个错误似乎在客户端上也看到过

**Comment by Mother-Ship** [comment]
![image](https://user-images.githubusercontent.com/26121316/91094082-e3360680-e68c-11ea-97d3-7b624246b5ae.png)
这么设置应该就可以了吧……

不过这么看大概不是你这边的问题了（
