### ISSUE TITLE
[Bug]: 如果加好友的人[加好友过于频繁]事件——加好友请求，无法正常触发

### ISSUE THREAD

**Issue by huankong233** [Mrs4s/go-cqhttp#1844]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc4

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

如果加好友的人[加好友过于频繁]

事件——加好友请求，无法正常触发

### 期望的结果是什么？

收到事件以及事件类型

### 实际的结果是什么？

没有返回结果

### 简单的复现代码/链接（可选）

```golang
~~~javascript
bot.on('request', async context => {
    console.log(context)
})
~~~
```

**Comment by Mrs4s** [comment]
这个应该是加好友的人被风控了
