### ISSUE TITLE
在QQ群发送[CQ:music]高几率无法发送，在私聊中正常

### ISSUE THREAD

**Issue by lizkes** [Mrs4s/go-cqhttp#185]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.21-fix1
运行环境: docker-debian10
连接方式: 反向WS

**bug内容**
私聊时一切正常
![snipaste_20200825_021745](https://user-images.githubusercontent.com/20457790/91081136-3a31e080-e679-11ea-8a52-297e2d892ebe.png)
群聊几乎不行，只有偶尔可以
![snipaste_20200825_021921](https://user-images.githubusercontent.com/20457790/91081257-69485200-e679-11ea-95c3-40f08bab7e63.png)

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by lizkes** [comment]
更新，现在私聊也不行了。应该是腾讯限制了

**Comment by scjtqs** [comment]
试试xml的呢？
```xml
[CQ:xml,data=<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="2" templateID="1" action="web" brief="&#91;分享&#93; 十年" sourceMsgId="0" url="https://i.y.qq.com/v8/playsong.html?_wv=1&amp;songid=4830342&amp;souce=qqshare&amp;source=qqshare&amp;ADTAG=qqshare" flag="0" adverSign="0" multiMsgFlag="0" ><item layout="2"><audio cover="http://imgcache.qq.com/music/photo/album_500/26/500_albumpic_89526_0.jpg" src="http://ws.stream.qqmusic.qq.com/C400003mAan70zUy5O.m4a?guid=1535153710&amp;vkey=D5315B8C0603653592AD4879A8A3742177F59D582A7A86546E24DD7F282C3ACF81526C76E293E57EA1E42CF19881C561275D919233333ADE&amp;uin=&amp;fromtag=3" /><title>十年</title><summary>陈奕迅</summary></item><source name="QQ音乐" icon="https://i.gtimg.cn/open/app_icon/01/07/98/56/1101079856_100_m.png" url="http://web.p.qq.com/qqmpmobile/aio/app.html?id=1101079856" action="app"  a_actionData="com.tencent.qqmusic" i_actionData="tencent1101079856://" appid="1101079856" /></msg>]
```

**Comment by lizkes** [comment]
已经确认是腾讯风控了XML的发送，换另一个QQ号就可以发送私聊了，但是群聊还是不行。
目前应该是没办法解决这个风控问题

**Comment by scjtqs** [comment]
那就没办法了



---原始邮件---
发件人: "lizkes"<notifications@github.com&gt;
发送时间: 2020年8月25日(周二) 上午10:42
收件人: "Mrs4s/go-cqhttp"<go-cqhttp@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"scjtqs"<scjtqs@qq.com&gt;;
主题: Re: [Mrs4s/go-cqhttp] 在QQ群发送[CQ:music]高几率无法发送，在私聊中正常 (#185)




 
已经确认是腾讯风控了XML的发送，换另一个QQ号就可以发送私聊了，但是群聊还是不行。
 目前应该是没办法解决这个风控问题
