### ISSUE TITLE
为"获取陌生人信息"添加个人说明

### ISSUE THREAD

**Issue by MeowRay** [Mrs4s/go-cqhttp#1853]
用于匹配关键字防🐔

personal_note string 个人说明

**Comment by Mrs4s** [comment]
QQ还有🐔的吗

**Comment by MeowRay** [comment]
> QQ还有🐔的吗

总是有人邀请这种的进群，有些还是写在名片图片的，如果名片也能加更好咯

![IMG_5839](https://user-images.githubusercontent.com/29674595/212277795-878ea59a-535d-408f-83e7-9dad35525222.PNG)

**Comment by wdvxdr1123** [comment]
bio更好
