### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Qiao-Paper** [Mrs4s/go-cqhttp#1862]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc4

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

在运行go-cqhttp并成功连接上QQ后报错
rc3和rc4都会出现

### 期望的结果是什么？

连接后应该会一直弹出反向WebSocket Universal服务器  时出现错误: : connect: connection refused 直到连接上

### 实际的结果是什么？

一直弹出最下面的warning，有时候会多出一行 如图2
![warning](https://user-images.githubusercontent.com/59883218/213081020-84616f17-432e-4ea7-9e7f-0135a449ee20.png)
![warning_2](https://user-images.githubusercontent.com/59883218/213081915-e7956918-5c5e-4fc7-8984-e3a3dc2d359d.png)

### 简单的复现代码/链接（可选）

```golang
./go-cqhttp
```

**Comment by Mrs4s** [comment]
这个问题已经修复了, 还没Release
