### ISSUE TITLE
[Bug]: 通过download_file下载的文件被占用(文件已在go-cqhttp中打开)

### ISSUE THREAD

**Issue by U1dd** [Mrs4s/go-cqhttp#1864]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc4

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

直接调用download_file api下载文件。

### 期望的结果是什么？

下载文件完成后能够立即对文件进行操作。

### 实际的结果是什么？

对文件进行操作时，提示文件已在go-cqhttp打开。
![image](https://user-images.githubusercontent.com/85346376/213401937-753fbd1c-cb93-415f-b8b6-9de481514a13.png)

### 简单的复现代码/链接（可选）

```golang
import shutil
from pathlib import Path
from tempfile import TemporaryDirectory

async def func(bot: Bot):
    with TemporaryDirectory() as tempdir:
        file_path = (await bot.download_file(url=url))['file']
        shutil.move(file_path, Path(tempdir).joinpath('123.txt'))  # PermissionError: [WinError 32]
```

### 补充说明（可选）

在64位Windows系统下等待大约一分钟后文件才会解除占用，gocq的rc3版本似乎没有这个问题。其他系统没有尝试过。

**Comment by LengYue12138** [comment]
我和你有一样的问题，解决思路就是复制移动【占用文件可复制】

**Comment by U1dd** [comment]
> 我和你有一样的问题，解决思路就是复制移动【占用文件可复制】

这样子的话，原文件就一直保留在cache文件夹里，得做清理工作，还是有点麻烦的。
dev分支修复了，感觉现在可以先用着dev分支的版本。

**Comment by LengYue12138** [comment]
您好，我已接收到您的邮件并会仔细阅读，如有紧急事项请通过手机联系我，谢谢！

**Comment by LengYue12138** [comment]
您好，我已接收到您的邮件并会仔细阅读，如有紧急事项请通过手机联系我，谢谢！
