### ISSUE TITLE
[Bug]: 发送群消息图片时显示：警告: 群xxxx图片上传失败: upload failed: echo error: failed to read byte: EOF

### ISSUE THREAD

**Issue by QyuJ123456** [Mrs4s/go-cqhttp#1865]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0rc4

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

使用CQ码发送本地或者base64图片

### 期望的结果是什么？

能正常发送图片

### 实际的结果是什么？

无法发送

### 简单的复现代码/链接（可选）

```golang
driver.get_screenshot_as_file("2aa.png")
in_file = ffmpeg.input(".\\2aa.png")
out_file = ffmpeg.output(in_file, ".\\2a.jpg")
out_file = ffmpeg.overwrite_output(out_file)
ffmpeg.run(out_file)
return r"[CQ:image,file=file:///C:/Users/12834/Desktop/go-cqhttp/scripts/2a.jpg]"

jsonText = '''
      {
           "action": "send_group_msg",
           "params": {
                   "group_id": %s,
                   "message": "%s"
           },
           "echo": "OK"
       }
''' % (rect_text['group_id'], return_text)
await websocket.send(jsonText)
```

### 日志记录（可选）

```golang
警告: 群xxxx图片上传失败: upload failed: echo error: failed to read byte: EOF
群消息发送失败: 消息为空.
```

**Comment by C0j23T** [comment]
后续：换了个网络就发出去了

**Comment by QyuJ123456** [comment]
> 后续：换了个网络就发出去了

草
