### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 2055135** [Mrs4s/go-cqhttp#1866]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0-rc4

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

使用zerobot插件的点歌模块出现的，出现一次崩溃

### 期望的结果是什么？

错误能够被修正

### 实际的结果是什么？

问题仍然出现

### 日志记录（可选）

```golang
[2023-01-23 20:28:03] [WARNING]: 警告: 群 343045650 富文本消息发送失败: timeout 
[2023-01-23 20:28:28] [ERROR]: Protocol -> panic on decoder MultiMsg.ApplyDown : runtime error: index out of range [0] with length 0
goroutine 67288770 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
	github.com/Mrs4s/MiraiGo@v0.0.0-20221202060717-4658474c60dd/client/network.go:335 +0x65
panic({0x89cee0, 0xc00040e2e8})
	runtime/panic.go:884 +0x212
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse(0xc00018a050?, 0x49?, {0xc00018a050, 0x49, 0x49})
	github.com/Mrs4s/MiraiGo@v0.0.0-20221202060717-4658474c60dd/client/multimsg.go:108 +0x9c5
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0000e1540)
	github.com/Mrs4s/MiraiGo@v0.0.0-20221202060717-4658474c60dd/client/network.go:346 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
	github.com/Mrs4s/MiraiGo@v0.0.0-20221202060717-4658474c60dd/client/network.go:332 +0x4cd
```

**Comment by wdvxdr1123** [comment]
duplicate with #1251
