### ISSUE TITLE
[Bug]: json卡片提示用安全设备验证

### ISSUE THREAD

**Issue by Gingmzmzx** [Mrs4s/go-cqhttp#1868]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0-rc4

### 运行环境

CentOS

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

群友在群里用模块发送了个json卡片，然后调用`send_msg`原封不动的再发送群友的这个json卡片
```
{"group_id":114514,"message":{"type":"xml","data":{"data":'{"actionData":""&#44;"actionData_A":""&#44;"app":"com.tencent.bot.task.deblock"&#44;"appID":""&#44;"config":{"autosize":1&#44;"ctime":1663990767&#44;"token":"6d3a825e9a1ca90143759955c2615d09"}&#44;"desc":""&#44;"extra":""&#44;"meta":{"detail":{"appID":""&#44;"botName":"Tencent bot"&#44;"content":"===菜单配置===\r\n修改菜单头#xxx\r\n修改菜单尾#xxx\r\n修改召唤指令#xxx\r\n修改图片字体#xxx\r\n开启/关闭图片模式\r\n开启/关闭卡片模式\r\n开启/关闭图片美化\r\n开启/关闭静默模式\r\n开启/关闭图片文字居中"&#44;"guildID":""&#44;"iconLeft":&#91;{"num":"20"}&#93;&#44;"iconRight":&#91;&#93;&#44;"subGuildID":"SUBGUILDID#"&#44;"title":""&#44;"titleColor":"blue"}}&#44;"prompt":"ZIC云端助手"&#44;"sourceAd":""&#44;"sourceName":""&#44;"sourceUrl":""&#44;"text":""&#44;"ver":"2.0.4.0"&#44;"view":"index"}'}}}
```

### 期望的结果是什么？

正常发送

### 实际的结果是什么？

![超级截屏_20230127_084517](https://user-images.githubusercontent.com/49107602/214982834-3ca118f6-b054-4c6a-8dc7-bbc16a9ae2dc.png)
说啥需要使用安全设备验证

### 日志记录（可选）

```golang
![超级截屏_20230127_084517](https://user-images.githubusercontent.com/49107602/214982834-3ca118f6-b054-4c6a-8dc7-bbc16a9ae2dc.png)
```

**Comment by kuankuan2007** [comment]
我也遇到了相同的问题,我这边的输出是
`[WARNING]: 群消息发送失败: 账号可能被风控.`
返回值为
`{"data":null,"msg":"SEND_MSG_API_ERROR","retcode":100,"status":"failed","wording":"send group message failed: blocked by server"}`
尝试过dev分支均出现相同情况
windows x64

**Comment by jieBieber** [comment]
> 你好！我这里也是这个报错，重新登录还是不行，消息一样发不出去

**Comment by jieBieber** [comment]
> 字面意思 请用手机登录QQ验证一次

你好！我这里也是这个报错，已经重新登录了，但消息还是发送不了

**Comment by jieBieber** [comment]
> > 字面意思 请用手机登录QQ验证一次
> 
> 你好！我这里也是这个报错，已经重新登录了，但消息还是发送不了

我的运行环境是Win10 go-cq版本是r4的

**Comment by bywhite0** [comment]
可能是json被腾讯ban了

**Comment by jieBieber** [comment]
> 可能是json被腾讯ban了

你好！我想问问有啥解决方法嘛

**Comment by bywhite0** [comment]
> > 可能是json被腾讯ban了
> 
> 你好！我想问问有啥解决方法嘛

没有，我也遇到过这个问题，用模块发也是无法发送

**Comment by jieBieber** [comment]
> > > 可能是json被腾讯ban了
> > 
> > 
> > 你好！我想问问有啥解决方法嘛
> 
> 没有，我也遇到过这个问题，用模块发也是无法发送

好的，谢谢
