### ISSUE TITLE
Http Failed: INCORRECT_CHARSET: Not UTF-8

### ISSUE THREAD

**Issue by PlexPt** [Mrs4s/go-cqhttp#187]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.10
运行环境: windows_amd64
连接方式: http post

**bug内容**
请在这里详细描述bug的内容
PicqBotX Http Failed: INCORRECT_CHARSET: Not UTF-8
接收到的post消息不是utf8

**复现方法**
请在这里分步骤的描述如何复现这个bug
PicqBotX

**Comment by PlexPt** [comment]
同样的配置 酷q air 就没问题

**Comment by Mrs4s** [comment]
POST是通过 `GOUT` 库提交的, 请检查相关框架有无问题

**Comment by PlexPt** [comment]
原版上无问题，今天切换到go-http才出现



---Original---

**Comment by Mrs4s** [comment]
请升级PICQ版本 https://github.com/HyDevelop/PicqBotX/blob/a2d30a4ddd02215810e295807eff462d31819412/src/main/java/cc/moecraft/icq/receiver/PicqHttpServer.java#L155-L159
相关逻辑已被修复
