### ISSUE TITLE
[Bug]: 引用回复收到了错误的消息 ID

### ISSUE THREAD

**Issue by MirrorCY** [Mrs4s/go-cqhttp#1876]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc4

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

并未找到 100% 复现的流程，但 [此 issue](https://github.com/koishijs/koishi/issues/956) 提供了许多相关的信息
- 启动 go-cq 并登录账号
- 群聊中发送任意消息
- 引用发送的消息回复任意消息
- 检查消息 id 是否正确对应

### 期望的结果是什么？

返回正确的消息 id

### 实际的结果是什么？

返回了错误的消息 id

### 简单的复现代码/链接（可选）

```golang
https://github.com/koishijs/koishi/issues/956
```

### 补充说明（可选）

![%282WLGKWT1HAG(%5~%JR$F](https://user-images.githubusercontent.com/37006258/215703238-3a1e50ce-2e45-4839-b9db-721a2711e54d.gif)
![B 18KX5%39YL0JCGH9B$P)S](https://user-images.githubusercontent.com/37006258/215703256-614e1914-9bf9-422b-bc8b-ee953d8b2c4d.jpg)
![_IS}HY4XYCXG08J )RHC6DX](https://user-images.githubusercontent.com/37006258/215703338-61e564ea-846f-485a-9855-f0f1914f02ab.png)

**Comment by Mrs4s** [comment]
已确认是第三方客户端实现问题
