### ISSUE TITLE
多账户支持

### ISSUE THREAD

**Issue by lanemi** [Mrs4s/go-cqhttp#1880]
**环境信息**
go-cqhttp版本: v1.0.0-rc4

**需要添加的功能内容**
查询了文档好像没有多QQ的支持方法。

能否支持多号

谢谢Thanks♪(･ω･)ﾉ

**Comment by Ink-33** [comment]
多复制粘贴几个主程序到不同文件夹

**Comment by Mrs4s** [comment]
可以采用多开的方式登录多个账户
目前的协议不太适合多账户管理
