### ISSUE TITLE
[Bug]: 回复消息删去提及后 gocq 仍带有

### ISSUE THREAD

**Issue by idanran** [Mrs4s/go-cqhttp#1887]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0-rc4

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

* 发送回复他人的消息，删去消息开头默认添加的提及（at），即将`[CQ:reply,id=000][CQ:at,qq=222] xxx`改为`[CQ:reply,id=000] xxx`。（由真人发送）

### 期望的结果是什么？

`[CQ:reply,id=000] xxx`
或` [CQ:reply,id=000][CQ:at,qq=222,hide=1] xxx`

### 实际的结果是什么？

`[CQ:reply,id=000][CQ:at,qq=222] xxx`

### 补充说明（可选）

以上CQ码为视觉可见的消息的替代。

**Comment by Mrs4s** [comment]
什么意思

**Comment by Ink-33** [comment]
我不确定，可能需要更多的信息才能回答

**Comment by idanran** [comment]
> 什么意思

在回复消息时，我们一般会删去自带的艾特，但是QQ仍保留有，不过不会显示出来。

**Comment by idanran** [comment]
> > 什么意思
> 
> 在回复消息时，我们一般会删去自带的艾特，但是QQ仍保留有，不过不会显示出来。

即使视觉上不可见，但是 gocq 的消息段仍和普通的艾特一致。
