### ISSUE TITLE
文字信息和图片CQ码在一次会话中一起发送出现图片无法显示情况

### ISSUE THREAD

**Issue by genres17** [Mrs4s/go-cqhttp#189]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.20
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
nonebot框架下，文字信息和图片CQ码在一次会话中一起发送出现图片无法显示情况，在手机端，图片可以预览大概但点进去就是裂图，pc端则直接显示图片失败

**复现方法**
让图片CQ码和文字内容在一个会话里发送，情况如下所示：
![图片](https://user-images.githubusercontent.com/60060093/91120160-99b6dd00-e6c7-11ea-863b-563e45da3f85.png)

**Comment by Mrs4s** [comment]
请使用最新版本 此问题已修复
