### ISSUE TITLE
[Bug]: 自定义音乐分享发出来是单个链接

### ISSUE THREAD

**Issue by kuankuan2007** [Mrs4s/go-cqhttp#1891]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc4

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

发送cq码[CQ:music,type=custom,url=http://bd.kuwo.cn/play_detail/1065516,audio=https://other-web-ra01-sycdn.kuwo.cn/d2a804075783b1376da98be57c14c06f/63e0e84e/resource/n1/128/13/98/1212471897.mp3,title=明天，你好,content=酷我音乐-牛奶咖啡,image=https://img4.kuwo.cn/star/albumcover/500/60/29/927119208.jpg]

### 期望的结果是什么？

一个酷我音乐的分享链接

### 实际的结果是什么？

![image](https://user-images.githubusercontent.com/109161762/216965564-6beaca6c-7893-4fbd-8787-6cecedb6edcb.png)

### 日志记录（可选）

```golang
上下文无有关记录，命令行提示发送成功
```

**Comment by wdvxdr1123** [comment]
可以尝试加入subtype=kuwo

**Comment by kuankuan2007** [comment]
感谢，问题已经解决了
