### ISSUE TITLE
[Bug]: 机器人已经是群管理的情况下依然不能发送私聊消息

### ISSUE THREAD

**Issue by lengyue-ck** [Mrs4s/go-cqhttp#1905]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [x] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc4 

### 运行环境

Linux

### 运行架构

None

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

机器人已经是群管理的情况下，仍然不能发送群私聊消息

### 期望的结果是什么？

可以发送 私聊消息

### 实际的结果是什么？

HTTP请求后返回
{
    "data": null,
    "msg": "SEND_MSG_API_ERROR",
    "retcode": 100,
    "status": "failed",
    "wording": "请参考 go-cqhttp 端输出"
}
控制台返回
[2023-02-12 17:45:50] [WARNING]: 发送临时会话消息失败: 已关闭临时会话信息发送功能 

我是群主，我去打开群私聊，依然也是上述情况（并且机器人是群管理）

**Comment by XingLanGo** [comment]
你好！我也在使用的过程中遇到了相同的问题：机器人无法通过群聊 调用发送私聊信息 达成临时会话的效果 群中已经开启了临时会话 机器人也是管理员 并且可以正常收到临时会话的日志 但即使填写了group_id参数也无法临时会话

**Comment by Mrs4s** [comment]
修改配置 `allow-temp-session` 为 `true` 即可
