### ISSUE TITLE
[CQ:music]不支持网易云音乐

### ISSUE THREAD

**Issue by Officeyutong** [Mrs4s/go-cqhttp#191]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.21-fix1
运行环境: linux amd64
连接方式: HTTP

**bug内容**
[CQ:music,type=163,id=xxxx]无法正常发送，提示"转换CQ码到MiraiGo Element时出现错误: unsupported music type: 163 将原样发送."
（但是原版的cqhttp是可以正常发送网易云音乐分享的）

**复现方法**
消息内容发送[CQ:music,type=163,id=12345678]即可

**Comment by F0ur** [comment]
看了下代码，目前只支持qq和custom
