### ISSUE TITLE
让 cqhttp 支持连接免费证书的 wss（安装根证书到系统）

### ISSUE THREAD

**Issue by yzy613** [Mrs4s/go-cqhttp#1910]
**环境信息**

go-cqhttp版本:  v1.0.0-rc4

**需要添加的功能内容**

增加一个 -k(--insecure) 启动参数，让反向 websocket 支持免费证书
```go
http.Client{
		Transport: &http.Transport{
			TLSClientConfig: &tls.Config{
				InsecureSkipVerify: HttpsInsecure,
				MinVersion:         tls.VersionTLS12,
			},
		},
	}
```

**Comment by SlimeNull** [comment]
不如直接允许在配置文件中配置 SSL 证书?

**Comment by yzy613** [comment]
> 不如直接允许在配置文件中配置 SSL 证书?

抱歉，少写了一个条件，反向 wss。让go-cqhttp作为客户端连接后端。

**Comment by b11p** [comment]
信任的证书不是看你系统信不信任吗，我一直用反向wss都没出过问题。你什么环境啊

**Comment by yzy613** [comment]
不然异地调用，ws 明文信息，很不安全XD

**Comment by yzy613** [comment]
> 信任的证书不是看你系统信不信任吗，我一直用反向wss都没出过问题。你什么环境啊

那你用的证书应该是至少一年一换吧。我的证书是3个月一换。用 acme.sh 自动申请部署的免费证书

**Comment by b11p** [comment]
我估计是你系统或者ca-certification之类的包太旧，没有le和zerossl的根证书，要么就是容器跑的镜像没装这个包，安装/更新一下就好了。实在不行手动把他们的根证书添加信任就可以了。

**Comment by yzy613** [comment]
> 我估计是你系统或者ca-certification之类的包太旧，没有le和zerossl的根证书，要么就是容器跑的镜像没装这个包，安装/更新一下就好了。实在不行手动把他们的根证书添加信任就可以了。

不是。反向 ws 是 cqhttp 作为客户端连接后端吧？我后端作为服务端部署的 ZeroSSL 根证书下发的证书，cqhttp 作为客户端连接会报 remote 证书不可信

**Comment by wdvxdr1123** [comment]
要更新系统信任证书，您需要执行以下步骤：

1. 下载证书：在您的 Linux 系统上运行以下命令：

```
$ wget https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt
```

这将下载名为 lets-encrypt-x3-cross-signed.pem.txt 的证书到当前目录。

2. 移动证书：使用以下命令将证书移到正确的位置：

```
$ sudo mv lets-encrypt-x3-cross-signed.pem.txt /usr/share/ca-certificates/
```

3. 更新证书列表：执行以下命令以更新证书列表：

```
$ sudo update-ca-certificates
```

执行此命令后，系统应该会显示一条消息，指示证书已成功安装。

现在，您可以在使用您申请的免费证书的应用程序中使用它。

--- powered by chatgpt

**Comment by yzy613** [comment]
### 最终解决办法（已经实践）

1. 下载或导出 ZeroSSL RSA Domain Secure Site CA.crt 证书

2. 将 ZeroSSL RSA Domain Secure Site CA.crt 移动到 `/usr/local/share/ca-certificates`

   ```shell
   $ sudo mv 'ZeroSSL RSA Domain Secure Site CA.crt' /usr/local/share/ca-certificates/
   ```

3. 更新 CA 证书

   ```shell
   $ sudo update-ca-certificates
   ```

**Comment by Ink-33** [comment]
其实你只需要在服务端配置证书的时候把ca证书和你站点的证书拼接到一起就可以了。大部分情况下出现x509 invalid错误都可以通过这种方法解决。

**Comment by yzy613** [comment]
> 其实你只需要在服务端配置证书的时候把ca证书和你站点的证书拼接到一起就可以了。大部分情况下出现x509 invalid错误都可以通过这种方法解决。

主要是我没这条件，因为我的证书 3 个月就会自动更换，每三个月手动拼接有些许繁琐。

**Comment by Ink-33** [comment]
> > 其实你只需要在服务端配置证书的时候把ca证书和你站点的证书拼接到一起就可以了。大部分情况下出现x509 invalid错误都可以通过这种方法解决。
> 
> 主要是我没这条件，因为我的证书 3 个月就会自动更换，每三个月手动拼接有些许繁琐。

证书自动化工具大多都可以自动部署fullchain，可以参考一下自动化工具的文档
