### ISSUE TITLE
[Bug]: 一直提示 登录失败: 密码错误或账号被冻结

### ISSUE THREAD

**Issue by CoolPlayLin** [Mrs4s/go-cqhttp#1916]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc4

### 运行环境

Ubuntu

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

正常登录

### 期望的结果是什么？

登录成功

### 实际的结果是什么？

![image](https://user-images.githubusercontent.com/96709586/219921716-ad6fc1e4-ebd7-4035-9a13-910cad8d0fcb.png)
并且QQ的设备列表出现一个未知设备，一直在线
![Screenshot_20230219_115345](https://user-images.githubusercontent.com/96709586/219921780-e77433e6-32a6-4771-9454-2c24f51aef42.jpg)
最后一个北京的才是正确的

**Comment by wdvxdr1123** [comment]
请重新生成device.json， 并将protocol改为6(AndroidPad协议)试试

**Comment by SernRounder** [comment]
出现同样的问题, 修改device.json后报错如下, 昨天之前还是正常运行状态
![image](https://user-images.githubusercontent.com/38492918/219923059-f48196b5-244c-42e0-b678-902306882898.png)

**Comment by wdvxdr1123** [comment]
当前device.json包含的设备信息可能被tx标记为不安全设备，你需要使用新的device.json文件

**Comment by chrysoljq** [comment]
我是 iPAD 协议登录有问题，其他几个协议（MACOS，手表）都正常
![image](https://user-images.githubusercontent.com/58966022/219932090-61c5108d-c2a9-47ef-8ef5-9cbfc84d9a4d.png)

**Comment by follow2015** [comment]
不是我一个人碰到啊，周六下午开始的。突然就不行了。然后电脑上的QQ提示要安装新版本的QQ才能登陆。我已经删除了cq重新编译了的。一样用的iPad协议

**Comment by koonoohaa** [comment]
一样的问题  上次QQ事故后突然就登不上去了  一直显示冻结和密码错误 所有协议都试过了

**Comment by clacknya** [comment]
确实新出现的，估计 tx 在搞什么。我在本地使用扫码可以登录，使用滑条不能登录。扫码登录成功的 `session.token` 可以放到服务器登录，但如果手机再登录，`session.token` 缓存就会作废，又得重新扫码登录。

**Comment by CoolPlayLin** [comment]
@wdvxdr1123 没有用

**Comment by cjj619** [comment]
我也是啊啊啊啊啊

**Comment by CoolPlayLin** [comment]
@wdvxdr1123 ??????????????????????

**Comment by CoolPlayLin** [comment]
@Mrs4s

**Comment by qiaohs** [comment]
gg，好几天了登不了，一直低频自用的从来不主动发消息。换协议删设备都不行

**Comment by chrysoljq** [comment]
> ![image](https://user-images.githubusercontent.com/96709586/222668618-dfb03006-4cfc-4bac-acd9-a4fd35402bc6.png) 死活登不上

切换下协议吧，试试手表、MacOS之类的

**Comment by ChinaRan0** [comment]
我将protocol改为2之后可以正常登录，但是有的群不能正常获取消息，需要在手机端点开一下才能获取到该群的消息，希望能改正bug，我群有300多个，点不过来，不知道各位有没有什么解决办法。

**Comment by CoolPlayLin** [comment]
改协议之后可以了

**Comment by CoolPlayLin** [comment]
改协议之后可以了

**Comment by EnderKC** [comment]
> 
请问改成什么协议

**Comment by CoolPlayLin** [comment]
@wdvxdr1123 
![image](https://user-images.githubusercontent.com/96709586/222935419-5b9d85fd-12d1-4190-9da6-e1722304bdcd.png)
[dump.zip](https://github.com/Mrs4s/go-cqhttp/files/10890494/1677976899.zip)
```
[2023-03-05 08:41:39] [ERROR]: Protocol -> panic on decoder MultiMsg.ApplyDown : runtime error: index out of range [0] with length 0
goroutine 3126 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
	github.com/Mrs4s/MiraiGo@v0.0.0-20221202060717-4658474c60dd/client/network.go:335 +0x65
panic({0x82cee0, 0xc00022e0f0})
	runtime/panic.go:884 +0x212
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse(0xc0000280f0?, 0x49?, {0xc0000280f0, 0x49, 0x49})
	github.com/Mrs4s/MiraiGo@v0.0.0-20221202060717-4658474c60dd/client/multimsg.go:108 +0x9c5
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc00005c370)
	github.com/Mrs4s/MiraiGo@v0.0.0-20221202060717-4658474c60dd/client/network.go:346 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
	github.com/Mrs4s/MiraiGo@v0.0.0-20221202060717-4658474c60dd/client/network.go:332 +0x4cd
 
[2023-03-05 08:41:39] [ERROR]: 出现错误 packet decode error: MultiMsg.ApplyDown - runtime error: index out of range [0] with length 0. 详细信息已转储至文件 dumps/1677976899.dump 请连同日志提交给开发者处理 
```

**Comment by Mrs4s** [comment]
#1942

**Comment by beanslee2012** [comment]
改成协议2，大群收不到机器人回应的消息，小群可以
