### ISSUE TITLE
希望能出一个给小白新手的从0开始的安装教程

### ISSUE THREAD

**Issue by Daroach0** [Mrs4s/go-cqhttp#1917]
出个从0开始的安装视频发在b站也好嘛可以不

**Comment by yzyyz1387** [comment]
安装教程：
- win: 下载完解压双击打开
- linux: 有图形界面）下载完解压安装；无图形界面：下载完解压启动

见 [已经写的很详细的官方文档](https://docs.go-cqhttp.org/guide/quick_start.html#%E4%BD%BF%E7%94%A8)

不是吧这也要教？
