### ISSUE TITLE
[Bug]:请问 每次发视频的时候都会抛出这个报错 extract video cover failed: exec: "ffmpeg": executable file not found in $PATH   我该去怎么解决？ ffmpeg早已经部署好了    也是全局变量      我刚升级到r4版本的时候能发视频 但是过几天就这样了   各种方法都试过了 都不行   

### ISSUE THREAD

**Issue by myfz-2002** [Mrs4s/go-cqhttp#1919]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc4

### 运行环境

CentOS

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

在发送视频 
[CQ:video,file=http.......]

### 期望的结果是什么？

能正常发送视频

### 实际的结果是什么？

extract video cover failed:
exec: "ffmpeg": executable file not found in $PATH
环境报错  可我ffmpeg环境没有问题

**Comment by myfz-2002** [comment]
请问 每次发视频的时候都会抛出这个报错 extract video cover failed: exec: "ffmpeg": executable file not found in $PATH   我该去怎么解决？ ffmpeg早已经部署好了    也是全局变量      我刚升级到r4版本的时候能发视频 但是过几天就这样了   各种方法都试过了 都不行

**Comment by Mrs4s** [comment]
请安装`ffmpeg` 并添加到环境变量 `PATH`
