### ISSUE TITLE
[Bug]:  2023/2/21 无法收到频道消息

### ISSUE THREAD

**Issue by GD-Slime** [Mrs4s/go-cqhttp#1921]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc4

### 运行环境

CentOS

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

2 | Android Watch

### 重现步骤

近期 #1916 的类似事件在我这里也发生了. 
ipad协议无法使用, 所以我更换了模拟的设备类型. 机器人正常连接.
但经过测试, 在Android Watch协议和 MacOS协议下均无法收到来自QQ频道的消息.

当然, 根据 #1394 , 可能macOS和手表本身就不能接收频道消息.
所以希望可以尽快修复ipad协议的登录问题(#1916 ), 感谢.

### 期望的结果是什么？

收到任意频道消息

### 实际的结果是什么？

位收到任意频道消息

### 日志记录（可选）

```golang
以下是登录日志:

> [2023-02-21 12:17:06] [INFO]: 当前版本:v1.0.0-rc4 
> [2023-02-21 12:17:06] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
> [2023-02-21 12:17:06] [INFO]: 开始尝试登录并同步消息... 
> [2023-02-21 12:17:06] [INFO]: 使用协议: Android Watch 
> [2023-02-21 12:17:07] [INFO]: Protocol -> connect to server: 43.135.106.161:8080 
> [2023-02-21 12:17:07] [WARNING]: 登录需要滑条验证码, 请选择验证方式:  
> [2023-02-21 12:17:07] [WARNING]: 1. 使用浏览器抓取滑条并登录 
> [2023-02-21 12:17:07] [WARNING]: 2. 使用手机QQ扫码验证 (需要手Q和gocq在同一网络下). 
> [2023-02-21 12:17:07] [WARNING]: 请输入(1 - 2)： 
> [2023-02-21 12:17:10] [WARNING]: 请前往该地址验证 -> https://captcha.go-cqhttp.org/*********** <- 或输入手动抓取的 ticket：（Enter 提交） 
> [2023-02-21 12:17:26] [WARNING]: 账号已开启设备锁, 按 Enter 向手机 ********** 发送短信验证码. 
> [2023-02-21 12:17:47] [WARNING]: 请输入短信验证码： (Enter 提交) 
> [2023-02-21 12:18:04] [INFO]: 登录成功 欢迎使用: ******** 
> [2023-02-21 12:18:04] [INFO]: 开始加载好友列表... 
> [2023-02-21 12:18:04] [INFO]: 共加载 4 个好友. 
> [2023-02-21 12:18:04] [INFO]: 开始加载群列表... 
> [2023-02-21 12:18:04] [INFO]: 共加载 1 个群. 
> [2023-02-21 12:18:04] [INFO]: 资源初始化完成, 开始处理信息. 
> [2023-02-21 12:18:04] [INFO]: アトリは、高性能ですから! 
> [2023-02-21 12:18:04] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:18080/onebot/v11/ws 
> [2023-02-21 12:18:04] [INFO]: 正在检查更新. 
> [2023-02-21 12:18:04] [INFO]: 已连接到反向WebSocket Universal服务器 ws://127.0.0.1:18080/onebot/v11/ws 
> [2023-02-21 12:18:04] [INFO]: 检查更新完成. 当前已运行最新版本. 
> [2023-02-21 12:18:04] [INFO]: 开始诊断网络情况 
> [2023-02-21 12:18:06] [INFO]: 收到服务器地址更新通知, 将在下一次重连时应用.  
> [2023-02-21 12:18:06] [INFO]: 网络诊断完成. 未发现问题 
> [2023-02-21 12:19:47] [INFO]: 收到群 ******* 内 ********* 的消息: 123 (******)
```

**Comment by oicv** [comment]
我也遇到了同样问题，怀疑是腾讯安全策略，群消息等均正常，只有频道无法收到普通消息，但是可以收到@机器人的频道消息

**Comment by GD-Slime** [comment]
> 我也遇到了同样问题，怀疑是腾讯安全策略，群消息等均正常，只有频道无法收到普通消息，但是可以收到@机器人的频道消息

刚测试了一下, 我这里连@机器人的消息也收不到了... 只有群消息才能收到

**Comment by GD-Slime** [comment]
今天找了一下, 之前其实有人发过类似问题的解决方法: [https://github.com/Mrs4s/go-cqhttp/issues/1755#issuecomment-1312659916](url)

**Comment by GD-Slime** [comment]
找了一下, 发现以前有人发过类似问题的解决方法 [这里](https://github.com/Mrs4s/go-cqhttp/issues/1755#issuecomment-1312659916)

**Comment by oicv** [comment]
> 找了一下, 发现以前有人发过类似问题的解决方法 [这里](https://github.com/Mrs4s/go-cqhttp/issues/1755#issuecomment-1312659916)

你的恢复正常了是吗？

**Comment by GD-Slime** [comment]
> 

没有 只是暂时用这个办法先恢复机器人运转了

**Comment by GD-Slime** [comment]
> > 找了一下, 发现以前有人发过类似问题的解决方法 [这里](https://github.com/Mrs4s/go-cqhttp/issues/1755#issuecomment-1312659916)
> 
> 你的恢复正常了是吗？

没有 只是暂时先让机器人恢复运转了 这办法毕竟也是非常规是吧(

**Comment by oicv** [comment]
> > > 找了一下, 发现以前有人发过类似问题的解决方法 [这里](https://github.com/Mrs4s/go-cqhttp/issues/1755#issuecomment-1312659916)
> > 
> > 
> > 你的恢复正常了是吗？
> 
> 没有 只是暂时先让机器人恢复运转了 这办法毕竟也是非常规是吧(

我的机器人倒是一直可以登录 就是频道只能收到at消息
