### ISSUE TITLE
希望群消息能同时发送 group_name 和 user_name

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [Mrs4s/go-cqhttp#1923]
**环境信息**
ubuntu docker
go-cqhttp版本: v1.0.0-rc4

https://docs.go-cqhttp.org/api/#%E8%8E%B7%E5%8F%96%E6%B6%88%E6%81%AF
目前 go-cqhttp 主动发送的QQ群消息里只有 `group_id`, 没有 `group_name`, 对于日志或者相关功能来说非常不方便，希望配置文件添加一个选项，允许用户开启后同时发送数据时附带群名称（发送者名称目前倒是可以在 `sender.nickname` 字段获取到）

**Comment by lhlyu** [comment]
可以获取[群信息](https://docs.go-cqhttp.org/api/#%E8%8E%B7%E5%8F%96%E7%BE%A4%E4%BF%A1%E6%81%AF)，程序做个缓存记录

**Comment by SlimeNull** [comment]
是的, 我也认为这个并无必要

**Comment by Mrs4s** [comment]
可以去 `onebot` 仓库提一下. 这边主要是实现协议
