### ISSUE TITLE
[Bug]: 回复语音消息，在聊天界面：发送方和接收方存在看不到消息的情况。有些端又能看到

### ISSUE THREAD

**Issue by af913337456** [Mrs4s/go-cqhttp#1927]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

r4

### 运行环境

MacOS

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

1. 执行程序;
2. 对方发消息来；
3. 回复本地语音文件，文件格式 mp3

### 期望的结果是什么？

在聊天界面能看到语音消息

### 实际的结果是什么？

在聊天界面能看到语音消息

**Comment by Mrs4s** [comment]
这个问题应该问TX
