### ISSUE TITLE
希望支持获取 Cookies

### ISSUE THREAD

**Issue by 18844626311** [Mrs4s/go-cqhttp#1929]
**需要添加的功能内容**
希望支持获取 Cookies  有了cookie可以做很gocq没有的功能

**Comment by Ink-33** [comment]
？



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "Mrs4s/go-cqhttp"                                                                                    ***@***.***&gt;;
Date:&nbsp;Fri, Feb 24, 2023 09:15 PM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;[Mrs4s/go-cqhttp] 希望支持获取 Cookies (Issue #1929)





 
需要添加的功能内容
 希望支持获取 Cookies  有了cookie可以做很gocq没有的功能
