### ISSUE TITLE
parse incoming packet error : invalid payload

### ISSUE THREAD

**Issue by wordgao** [Mrs4s/go-cqhttp#193]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: go-cqhttp-v0.9.21-fix1
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
![QQ截图20200825152927](https://user-images.githubusercontent.com/10544395/91145488-1ce82b00-e6e8-11ea-9bc6-e5b50a9cfcad.jpg)

**复现方法**
登陆时，基本上都会出现图片上的内容

**Comment by Mrs4s** [comment]
#179
