### ISSUE TITLE
能接收信息，但是没有反应[Bug]: 

### ISSUE THREAD

**Issue by knigth95** [Mrs4s/go-cqhttp#1933]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

r3 / r4 /r2均试过，一样的问题

### 运行环境

Ubuntu

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

2 | Android Watch

### 重现步骤

输入完所有信息就行，终端可以看到接收了消息(hello)，但是没有反应(登录时有此信息Protocol -> device lock is disable.http api may fail.)

### 期望的结果是什么？

user发出消息：hello
bot:你好有什么可以帮助

### 实际的结果是什么？

机器人无反应

**Comment by Mrs4s** [comment]
请检查应用, 不是gocq的问题
