### ISSUE TITLE
[Bug]: 登录失败: 你的用户身份已失效，为保证帐号安全，请你重新登录。

### ISSUE THREAD

**Issue by bling-yshs** [Mrs4s/go-cqhttp#1939]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [ ] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

rc0.4 与 https://github.com/Mrs4s/go-cqhttp/actions/runs/4280157128

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

**今天刚出现的新情况。目前大概有4人出现这种情况，我也成功复现**

登录**不常用的账号**时即可触发，无论是哪种方式(目前测试了http和反向websocket)，无论是密码登录还是扫码登录，都会触发这种情况

![image](https://user-images.githubusercontent.com/41812674/222088468-389fd4c4-7dfa-4446-b1e4-38dd1a9560d1.png)

### 期望的结果是什么？

登陆成功

### 实际的结果是什么？

[WARNING]: 登录失败: 你的用户身份已失效，为保证帐号安全，请你重新登录。

**Comment by ZZZ-zero** [comment]
我也遇到了

**Comment by xuanmeikawaii** [comment]
我刚刚也遇到了，解决方法是多换几个登录协议，，，我这个可以在Android watch（即protocol = 2）可以登录

**Comment by bling-yshs** [comment]
> 我刚刚也遇到了，解决方法是多换几个登录协议，，，我这个可以在Android watch（即protocol = 2）可以登录

诶，确实，我用安卓watch也成功了

**Comment by Anmours** [comment]
现在似乎只有protocol = 2才能登录！ 其他协议均失效

**Comment by starstens** [comment]
我也遇到了同样的问题，protocol = 2确实可以，可能因为登录的设备是手表QQ，协议和登录设备要一致？

**Comment by needhourger** [comment]
同样问题+1

**Comment by YXHXianYu** [comment]
+1。把device.json中的protocol改为2就成功了。

**Comment by BlackcatWatcher** [comment]
+1。不知道是不是新BUG：删掉了device.json，改为2后，用1模式浏览器验证，新设备要求手机验证码，输入正确的验证码后提示验证码错误。

**Comment by BobLiu0518** [comment]
今天的 mac QQ（V6.8.0，是老版本）也收到了下线提醒，说“当前QQ版本过低”，可能和这个也有关系

**Comment by MxEmerson** [comment]
同样的问题，现在只能把 protocol 改为2使用

**Comment by reine-ishyanami** [comment]
我也遇到了

**Comment by Raven-tu** [comment]
复现问题

**Comment by Mrs4s** [comment]
临时解决方案是不要使用扫码登录或者在密码登录过程中使用扫码解决设备锁.
正在修了

**Comment by gaogaotwo** [comment]
同样问题+1

**Comment by aohanhongzhi** [comment]
+1 
![image](https://user-images.githubusercontent.com/37319319/222173841-072adbfc-bed1-4efc-a0a4-1f348d7ca679.png)

**Comment by a1363184096** [comment]
qq更新了，没办法，等修，暂时只有安卓手表可用

**Comment by sherlockHlb** [comment]
protocol 在哪里设置呢,找不到

**Comment by sherlockHlb** [comment]
好的原来是拼写错误

**Comment by aohanhongzhi** [comment]
> protocol 在哪里设置呢,找不到

生成的device.json文件里有
![image](https://user-images.githubusercontent.com/37319319/222323465-67284302-9946-4e40-9eb3-0e1c3bf7af54.png)

**Comment by 2-3-8-4-0-3-6-9-9-2** [comment]
> 临时解决方案是不要使用扫码登录或者在密码登录过程中使用扫码解决设备锁. 正在修了

新版多了 TLV544  TLV545   TLV547   TLV548 。 看了go-cqhttp源码有 TLV547

**Comment by Kiana1314** [comment]
现在protocol = 2可以登上去  但是不知道为什么好几个群发消息gocq后台没有日志，机器人也无响应，时好时坏的

**Comment by xcy333** [comment]
> 现在protocol = 2可以登上去 但是不知道为什么好几个群发消息gocq后台没有日志，机器人也无响应，时好时坏的

相同问题

**Comment by MxEmerson** [comment]
> > 现在protocol = 2可以登上去 但是不知道为什么好几个群发消息gocq后台没有日志，机器人也无响应，时好时坏的
> 
> 相同问题

亲测手机同时登了之后把没收到消息的群一个一个点进去，就能收到消息了。比较神秘，根治还是等更新吧。

**Comment by Hfutsora** [comment]
> > > 现在protocol = 2可以登上去 但是不知道为什么好几个群发消息gocq后台没有日志，机器人也无响应，时好时坏的
> > 
> > 
> > 相同问题
> 
> 亲测手机同时登了之后把没收到消息的群一个一个点进去，就能收到消息了。比较神秘，根治还是等更新吧。

有个简单法子，踢了机器人再拉进来。。

**Comment by BeautifulBirds** [comment]
想问一下切换了Android watch还是要求扫码登录，看上面说不要扫码，这种情况是不是只能等更新了

**Comment by a1363184096** [comment]
> 想问一下切换了Android watch还是要求扫码登录，看上面说不要扫码，这种情况是不是只能等更新了

说起来不扫码登录我还没成功过，一直用的扫码登陆（

**Comment by SmallXJM** [comment]
> 现在protocol = 2可以登上去 但是不知道为什么好几个群发消息gocq后台没有日志，机器人也无响应，时好时坏的

貌似是服务器对watch的省电管理 那些设置了收到消息不提醒的群都不会收到消息

**Comment by Mrs4s** [comment]
可以尝试这个版本https://github.com/Mrs4s/go-cqhttp/actions/runs/4335877419
使用密码登录 不要用扫码
应该是没问题的

**Comment by LiuChangFreeman** [comment]
> 可以尝试这个版本https://github.com/Mrs4s/go-cqhttp/actions/runs/4335877419 使用密码登录 不要用扫码 应该是没问题的

Android Pad没问题了，其他的还是不行

**Comment by lvtiansama** [comment]
> 可以尝试这个版本 https://github.com/Mrs4s/go-cqhttp/actions/runs/4335877419 使用密码登录 不要用扫码 应该是没问题的

在使用该版本后，我可以正常登录，但是gocq返回的值和之前有所区别，比如缺少了一个‘message’的字典，检查发现该版本返回的格式与之前版本完全不同，请问这个问题是否会在后续修正，还是说我需要重构我的程序？

**Comment by 02mm** [comment]
感谢感谢！

**Comment by cy1159178778** [comment]
> 可以尝试这个版本https://github.com/Mrs4s/go-cqhttp/actions/runs/4335877419 使用密码登录 不要用扫码 应该是没问题的

根据id回复消息时会出现WARNING，并且聊天界面的显示也不正确，回复消息中的@斯卡蒂会转换成cq码在聊天界面中显示
[WARNING]: 转换消息 [CQ:at,target=1659051030,display=@斯卡蒂,subType=user] 到MiraiGo Element时出现错误: strconv.ParseInt: parsing "": invalid syntax.

**Comment by zmy15** [comment]
Android Pad好像也不行了

**Comment by clacknya** [comment]
> 可以尝试这个版本https://github.com/Mrs4s/go-cqhttp/actions/runs/4335877419 使用密码登录 不要用扫码 应该是没问题的

这个 Android Pad 前面可以登录，现在突然报版本过低无法登录了

**Comment by SaarChaffee** [comment]
这两天protocol换过去2能用，但是今天早上突然
```
[2023-03-08 12:20:21] [INFO]: 当前版本:v1.0.0-rc4
[2023-03-08 12:20:21] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2023-03-08 12:20:21] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2023-03-08 12:20:26] [INFO]: 开始尝试登录并同步消息...
[2023-03-08 12:20:26] [INFO]: 使用协议: Android Watch
[2023-03-08 12:20:27] [INFO]: Protocol -> connect to server: 183.47.102.62:8080
[2023-03-08 12:20:27] [WARNING]: 登录失败: 请使用手Q扫描二维码或短信登录。
[2023-03-08 12:20:27] [INFO]: 按 Enter 或等待 5s 后继续....
```

**Comment by wthee** [comment]
> 
无输入终端，无法正常选择提交方式
[0m[33m[2023-03-08 17:42:54] [WARNING]: 登录需要滑条验证码, 请选择验证方式:  
[0m[33m[2023-03-08 17:42:54] [WARNING]: 1. 使用浏览器抓取滑条并登录 
[0m[33m[2023-03-08 17:42:54] [WARNING]: 2. 使用手机QQ扫码验证 (需要手Q和gocq在同一网络下). 
[0m[33m[2023-03-08 17:42:54] [WARNING]: 请输入(1 - 2)： 
[0m[33m[2023-03-08 17:42:54] [WARNING]: 未检测到输入终端，自动选择1. 
[0m[33m[2023-03-08 17:42:54] [WARNING]: 请选择提交滑块ticket方式: 
[0m[33m[2023-03-08 17:42:54] [WARNING]: 1. 自动提交 
[0m[33m[2023-03-08 17:42:54] [WARNING]: 2. 手动抓取提交 
[0m[33m[2023-03-08 17:42:54] [WARNING]: 请输入(1 - 2)：

**Comment by wthee** [comment]
> 可以尝试这个版本https://github.com/Mrs4s/go-cqhttp/actions/runs/4335877419 使用密码登录 不要用扫码 应该是没问题的

无输入终端，无法正常选择提交方式
�[0m�[33m[2023-03-08 17:42:54] [WARNING]: 登录需要滑条验证码, 请选择验证方式:
�[0m�[33m[2023-03-08 17:42:54] [WARNING]: 1. 使用浏览器抓取滑条并登录
�[0m�[33m[2023-03-08 17:42:54] [WARNING]: 2. 使用手机QQ扫码验证 (需要手Q和gocq在同一网络下).
�[0m�[33m[2023-03-08 17:42:54] [WARNING]: 请输入(1 - 2)：
�[0m�[33m[2023-03-08 17:42:54] [WARNING]: 未检测到输入终端，自动选择1.
�[0m�[33m[2023-03-08 17:42:54] [WARNING]: 请选择提交滑块ticket方式:
�[0m�[33m[2023-03-08 17:42:54] [WARNING]: 1. 自动提交
�[0m�[33m[2023-03-08 17:42:54] [WARNING]: 2. 手动抓取提交
�[0m�[33m[2023-03-08 17:42:54] [WARNING]: 请输入(1 - 2)：

**Comment by Nana7mij** [comment]
3.9 bot使用protocol = 2也失效了，尝试重新生成device.json然后成功了，有同样问题的可以试一下

**Comment by sagnitude** [comment]
改成2以后可以登录，但是收不到消息

**Comment by Hfutsora** [comment]
> 改成2以后可以登录，但是收不到消息

机器人的群消息设置为 `接收并提示`, watch 大概是省电原因拿不到其他的。

**Comment by HornCopper** [comment]
我的Bot没有出现此类情况，protocol=2之后除了在线状态其他和非2的协议运行状况无异。

**Comment by L-M-Sherlock** [comment]
遇到同类问题，协议切换为 2 后结果是
[2023-03-11 12:49:50] [WARNING]: 登录失败: 请使用手Q扫描二维码或短信登录。

**Comment by TexInfinitz** [comment]
设置成接收消息并提醒

**Comment by mxlt02** [comment]
遇到同类问题，协议切换为 2 后结果是
[2023-03-11 12:49:50] [WARNING]: 登录失败: 请使用手Q扫描二维码或短信登录。
