### ISSUE TITLE
[Bug]: 登录失败: 密码错误或账号被冻结

### ISSUE THREAD

**Issue by sherlockHlb** [Mrs4s/go-cqhttp#1942]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

now

### 运行环境

Windows (64)

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

[2023-03-02 10:21:10] [INFO]: Protocol -> connect to server: 120.241.150.69:8080
[2023-03-02 10:21:10] [WARNING]: 登录失败: 密码错误或账号被冻结

### 期望的结果是什么？

期望登陆

### 实际的结果是什么？

实际账号没被封禁,账号密码正确也无法登陆

**Comment by mas-alone** [comment]
同https://github.com/Mrs4s/go-cqhttp/issues/1939

**Comment by sherlockHlb** [comment]
找到了,怎么删除帖子

**Comment by dongda-villager** [comment]
> 找到了,怎么删除帖子
老哥怎么解决的

**Comment by dongda-villager** [comment]
> 找到了,怎么删除帖子

老哥怎么解决的

**Comment by a1363184096** [comment]
> > 找到了,怎么删除帖子
> 
> 老哥怎么解决的

切安卓手表协议可用用

**Comment by dongda-villager** [comment]
> 

感谢，已解决！

**Comment by dongda-villager** [comment]
> > > 找到了,怎么删除帖子
> > 
> > 
> > 老哥怎么解决的
> 
> 切安卓手表协议可用用

感谢！已解决！

**Comment by kivid** [comment]
+1，修改device.json文件的协议就行了

**Comment by dongda-villager** [comment]
> +1，修改device.json文件的协议就行了

感谢！

**Comment by zangxx66** [comment]
可能是tx更新了版本了，我以为是号又被ban了，手机登录提示我qq版本过低，我猜可能是更新了最低版本的限制

**Comment by amazing-fish** [comment]
> > > 找到了,怎么删除帖子
> > 
> > 
> > 老哥怎么解决的
> 
> 切安卓手表协议可用用

请问该如何切？

**Comment by amazing-fish** [comment]
> > > > 找到了,怎么删除帖子
> > > 
> > > 
> > > 老哥怎么解决的
> > 
> > 
> > 切安卓手表协议可用用
> 
> 请问该如何切？

已找到，将device.josn中的protocol =5改为=2

**Comment by Mrs4s** [comment]
https://github.com/Mrs4s/go-cqhttp/actions/runs/4335839018 尝试使用这个版本

**Comment by NepPure** [comment]
> https://github.com/Mrs4s/go-cqhttp/actions/runs/4335839018 尝试使用这个版本

@Mrs4s 我用这个提示登录失败，QQ版本过低，用的是2安卓手表的协议

**Comment by coder-tq** [comment]
> https://github.com/Mrs4s/go-cqhttp/actions/runs/4335839018 尝试使用这个版本

使用ipad协议依旧提示“登录失败: 密码错误或账号被冻结”

**Comment by coder-tq** [comment]
> > > https://github.com/Mrs4s/go-cqhttp/actions/runs/4335839018 尝试使用这个版本
> > 
> > 
> > @Mrs4s 我用这个提示登录失败，QQ版本过低，用的是2和5的协议都不行
> 
> 删除原有的`device.json`，使用程序自动生成的再试试，默认的好像是aPAD了，也就是6协议 ![QQ截图20230306105007](https://user-images.githubusercontent.com/52590027/223008441-0ab3af6d-ba43-4dbd-9390-5c1b1dedc56a.png)

协议6成功登录，目前一切正常

**Comment by qycss** [comment]
刚刚尝试如下操作成功了，没有更新go-cq版本
1. 登录qq删除所有mirai设备
2. 在本地跑android_watch，扫码登录+设备锁验证码
3. 把device.json复制到服务器

**Comment by Reversedeer** [comment]
因人而异，我是被强t下线的

**Comment by sherlockHlb** [comment]
d开头的登录文件

1604051738 ***@***.***> 于2023年3月7日周二 10:19写道：

**Comment by NepPure** [comment]
> > https://github.com/Mrs4s/go-cqhttp/actions/runs/4335839018 尝试使用这个版本
> 
> @Mrs4s 我用这个提示登录失败，QQ版本过低，用的是2和5的协议都不行

我重新生成device.json好使了

**Comment by lancer-wang** [comment]
> https://github.com/Mrs4s/go-cqhttp/actions/runs/4335839018 尝试使用这个版本

用这个扫码之后提示该app尚未开通扫码登陆的权限

**Comment by lancer-wang** [comment]
> > https://github.com/Mrs4s/go-cqhttp/actions/runs/4335839018 尝试使用这个版本
> 
> ![image](https://user-images.githubusercontent.com/69783837/223345874-111744fa-a379-4fca-b29d-094a266177d7.png)

设备锁用手机验证码解锁可以登陆了

**Comment by Dreamworld204** [comment]
云服务器上重新登录, 要求必须同一个网络下扫码, 你们是怎么搞的呢?

**Comment by Kenda-12** [comment]
> 云服务器上重新登录, 要求必须同一个网络下扫码, 你们是怎么搞的呢?

在本地电脑扫码，将session.token文件传到云服务器

**Comment by RShock** [comment]
我在使用协议6时遇到了新的问题：
扫码结束后手机页面显示‘该APP尚未开通扫描二维码登陆的权限'，如果换用协议2则没有问题。

**Comment by Kenda-12** [comment]
Hello.This is an automatic reply from Kenda. Please elaborate on your matter in the email. I will reply to you later (if I think I need to reply).

**Comment by TechOtakupoi233** [comment]
> 我在使用协议6时遇到了新的问题： 扫码结束后手机页面显示‘该APP尚未开通扫描二维码登陆的权限'，如果换用协议2则没有问题。

aPad协议6重新生成device.json后，用滑条自动抓取登录成功。

**Comment by lulu666lulu** [comment]
> 我在使用协议6时遇到了新的问题： 扫码结束后手机页面显示‘该APP尚未开通扫描二维码登陆的权限'，如果换用协议2则没有问题。

使用密码登录，手机验证码过设备锁成功

**Comment by jerry-rain** [comment]
只有手表协议能登录，其他都是登录不了，扫码扫出来的永远都是登录手表的码

**Comment by nimeng1299** [comment]
> 

有没有好兄弟大概讲一下怎么用的，研究了一天没明白

**Comment by RShock** [comment]
设备锁

> > 我在使用协议6时遇到了新的问题： 扫码结束后手机页面显示‘该APP尚未开通扫描二维码登陆的权限'，如果换用协议2则没有问题。
> 
> 使用密码登录，手机验证码过设备锁成功

我现在遇到了新的问题：
使用协议6，滑条登陆后提示设备锁，扫码解除设备锁后再次登陆，继续提示`登录失败: 密码错误或账号被冻结]`
![2`OAZ}W `_4005{`_ FO H](https://user-images.githubusercontent.com/11630758/224465959-f422933a-eef1-4be2-9996-a9de682465b7.png)

**Comment by BiologyHazard** [comment]
我用ipad协议会弹这个提示，用手表协议就正常登录了。
这是为什么呢

**Comment by LR1093141031** [comment]
> 

protocol 改成2 已解决 thx

**Comment by justid** [comment]
确实现在只有手表协议扫码后可以使用
使用密码登录协议6 androidpad时, 提示**登录失败: 帐号或密码错误，请重新输入。 Code: 1**

**Comment by RShock** [comment]
就算用协议2，我的未被缓存过的图片都发不出去了。不清楚你们的情况。
```
[2023-03-13 13:28:34] [WARNING]: 警告: 群 287421381 图片上传失败: upload failed: dial tcp 175.27.12.205:80: i/o timeout
[2023-03-13 13:28:34] [WARNING]: 群消息发送失败: 消息为空.

```

**Comment by lowking** [comment]
> > > > > 找到了,怎么删除帖子
> > > > 
> > > > 
> > > > 老哥怎么解决的
> > > 
> > > 
> > > 切安卓手表协议可用用
> > 
> > 
> > 请问该如何切？
> 
> 已找到，将device.josn中的protocol =5改为=2

手表协议收不到群消息呢？

**Comment by ayakasuki** [comment]
隔壁ICQQ都解决了。。

**Comment by ayakasuki** [comment]
我把device.josn中带mirai字段都替换成Apple就可以了
![image](https://user-images.githubusercontent.com/20859971/225777911-c4faf5bf-6b71-4c55-a1a4-4187680753db.png)

**Comment by justid** [comment]
用dev版+新QQ号试了一下,可以密码登录.
推测原来的QQ号应该是被风控了只能使用最新版手Q登录, 从mirai上的文档获知可能返回值45, 只是go-cqhttp并不显示返回值,所以走了一些弯路

**Comment by jerry-rain** [comment]
> 

但是收不到撤回的消息

**Comment by whyiskey** [comment]
> > 云服务器上重新登录, 要求必须同一个网络下扫码, 你们是怎么搞的呢?
> 
> 在本地电脑扫码，将session.token文件传到云服务器

有人可以说下本地文件的登录信息怎么找吗？

**Comment by zangxx66** [comment]
> > > 云服务器上重新登录, 要求必须同一个网络下扫码, 你们是怎么搞的呢?
> > 
> > 
> > 在本地电脑扫码，将session.token文件传到云服务器
> 
> 有人可以说下本地文件的登录信息怎么找吗？

把cq-gohttp同目录的session.token上传到服务器就可以了

**Comment by whyiskey** [comment]
> > > > 云服务器上重新登录, 要求必须同一个网络下扫码, 你们是怎么搞的呢?
> > > 
> > > 
> > > 在本地电脑扫码，将session.token文件传到云服务器
> > 
> > 
> > 有人可以说下本地文件的登录信息怎么找吗？
> 
> 把go-cqhttp同目录的session.token上传到服务器就可以了

我刚刚试了一下，为什么我本地登录都上不去啊.....

**Comment by guestool** [comment]
> 

VPN
