### ISSUE TITLE
能否开源T544中的signer方法

### ISSUE THREAD

**Issue by icarus-ai** [Mrs4s/go-cqhttp#1954]
**环境信息**

go-cqhttp版本: dev

**需要添加的功能内容**

我这里移动打不开https://captcha.go-cqhttp.org/sdk/dandelion/energy 想把t544的singer方法搭在服务器上，如果不方便开源自动模式，给个获取方法也行

**Comment by LXY1226** [comment]
在猜了在猜了 😭

**Comment by Mrs4s** [comment]
目前的解决方案只能临时使用, 在服务端上用模拟器跑的.
回头想办法解决下国内连通性问题
等哪位大神把算法弄出来了只能emmm

**Comment by Mrs4s** [comment]
协议可以加群讨论 issue最好只讨论应用层问题
