### ISSUE TITLE
[Bug]: MacOS协议无法接收群戳一戳和好友戳一戳事件

### ISSUE THREAD

**Issue by Yuri-YuzuChaN** [Mrs4s/go-cqhttp#1956]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc4

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

3 | MacOS

### 重现步骤

在群聊和私聊中戳一戳Bot

### 期望的结果是什么？

在go-cqhttp控制台中应接收到戳一戳事件，并且会回复消息

### 实际的结果是什么？

在rc4以及dev版本控制台都没有收到戳一戳的事件，Bot消息无反应

### 简单的复现代码/链接（可选）

```golang
无
```

### 日志记录（可选）

```golang
无
```

### 补充说明（可选）

先前一直是ipad协议，没有更改插件内容，戳一戳功能一切正常，账号被冻结被迫切换成macos协议，出现这种问题

**Comment by fluttershyrr** [comment]
手表协议本来就不支持戳一戳吧

**Comment by Yuri-YuzuChaN** [comment]
> 手表协议本来就不支持戳一戳吧

这是macos协议不是手表

**Comment by LZYxiaobai** [comment]
> > 手表协议本来就不支持戳一戳吧
> 
> 这是macos协议不是手表

有没有可能，PC端也是没有戳一戳的（）
建议用最新的dev版，可以用aPad协议
[https://github.com/Mrs4s/go-cqhttp/actions/runs/4335877419](url)

**Comment by Yuri-YuzuChaN** [comment]
> 

文档中macos并没有限制，并且只写明了手表协议不支持戳一戳事件

**Comment by Yuri-YuzuChaN** [comment]
> > > 手表协议本来就不支持戳一戳吧
> > 
> > 
> > 这是macos协议不是手表
> 
> 有没有可能，PC端也是没有戳一戳的（） 建议用最新的dev版，可以用aPad协议 [https://github.com/Mrs4s/go-cqhttp/actions/runs/4335877419](url)

文档中macos并没有限制，并且只写明了手表协议不支持戳一戳事件
![Screenshot_2023-03-07-13-38-52-578_com android browser](https://user-images.githubusercontent.com/65105396/223330394-df6e8753-31e4-4e3f-8007-d470ca41c3c2.jpg)
![Screenshot_2023-03-07-13-38-05-750_com android browser](https://user-images.githubusercontent.com/65105396/223330283-bae5e8f5-54a3-4ea5-acec-04510cdbdea2.jpg)

**Comment by LZYxiaobai** [comment]
> > > > 手表协议本来就不支持戳一戳吧
> > > 
> > > 
> > > 这是macos协议不是手表
> > 
> > 
> > 有没有可能，PC端也是没有戳一戳的（） 建议用最新的dev版，可以用aPad协议 [https://github.com/Mrs4s/go-cqhttp/actions/runs/4335877419](url)
> 
> 文档中macos并没有限制，并且只写明了手表协议不支持戳一戳事件 ![Screenshot_2023-03-07-13-38-52-578_com android browser](https://user-images.githubusercontent.com/65105396/223330394-df6e8753-31e4-4e3f-8007-d470ca41c3c2.jpg) ![Screenshot_2023-03-07-13-38-05-750_com android browser](https://user-images.githubusercontent.com/65105396/223330283-bae5e8f5-54a3-4ea5-acec-04510cdbdea2.jpg)

我觉得应该只是文档遗漏了，毕竟咱用PC端聊天确实也看不到戳一戳信息的对吧。手表比较特殊，很多事件都是没有的，可能聊天消息也不是即时的，你要是真想用戳一戳的话可以去试试我刚刚发的那个dev版。

**Comment by Yuri-YuzuChaN** [comment]
> > > > > 手表协议本来就不支持戳一戳吧
> > > > 
> > > > 
> > > > 这是macos协议不是手表
> > > 
> > > 
> > > 有没有可能，PC端也是没有戳一戳的（） 建议用最新的dev版，可以用aPad协议 [https://github.com/Mrs4s/go-cqhttp/actions/runs/4335877419](url)
> > 
> > 
> > 文档中macos并没有限制，并且只写明了手表协议不支持戳一戳事件 ![Screenshot_2023-03-07-13-38-52-578_com android browser](https://user-images.githubusercontent.com/65105396/223330394-df6e8753-31e4-4e3f-8007-d470ca41c3c2.jpg) ![Screenshot_2023-03-07-13-38-05-750_com android browser](https://user-images.githubusercontent.com/65105396/223330283-bae5e8f5-54a3-4ea5-acec-04510cdbdea2.jpg)
> 
> 我觉得应该只是文档遗漏了，毕竟咱用PC端聊天确实也看不到戳一戳信息的对吧。手表比较特殊，很多事件都是没有的，可能聊天消息也不是即时的，你要是真想用戳一戳的话可以去试试我刚刚发的那个dev版。

issues已经说明使用过dev版本了

**Comment by Yuri-YuzuChaN** [comment]
并且用的debug模式，并没有任何结果

**Comment by LZYxiaobai** [comment]
> 并且用的debug模式，并没有任何结果

切成aPad协议，你说了你用的是MacOS协议

**Comment by wdvxdr1123** [comment]
我记得加入戳一戳时，gocq还没有MacOS协议， 所以当时的文档只提到了手表协议

**Comment by CCYellowStar** [comment]
> > > > > > 手表协议本来就不支持戳一戳吧
> > > > > 
> > > > > 
> > > > > 这是macos协议不是手表
> > > > 
> > > > 
> > > > 有没有可能，PC端也是没有戳一戳的（） 建议用最新的dev版，可以用aPad协议 [https://github.com/Mrs4s/go-cqhttp/actions/runs/4335877419](url)
> > > 
> > > 
> > > 文档中macos并没有限制，并且只写明了手表协议不支持戳一戳事件 ![Screenshot_2023-03-07-13-38-52-578_com android browser](https://user-images.githubusercontent.com/65105396/223330394-df6e8753-31e4-4e3f-8007-d470ca41c3c2.jpg) ![Screenshot_2023-03-07-13-38-05-750_com android browser](https://user-images.githubusercontent.com/65105396/223330283-bae5e8f5-54a3-4ea5-acec-04510cdbdea2.jpg)
> > 
> > 
> > 我觉得应该只是文档遗漏了，毕竟咱用PC端聊天确实也看不到戳一戳信息的对吧。手表比较特殊，很多事件都是没有的，可能聊天消息也不是即时的，你要是真想用戳一戳的话可以去试试我刚刚发的那个dev版。
> 
> issues已经说明使用过dev版本了

还是登不进去，只能用手表

**Comment by Mrs4s** [comment]
确实 `MacOS` 老版本不存在戳一戳这个东西
