### ISSUE TITLE
[Bug]: 机器人突然收不到某些群的消息

### ISSUE THREAD

**Issue by lancer-wang** [Mrs4s/go-cqhttp#1957]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc4

### 运行环境

Ubuntu

### 运行架构

None

### 连接方式

WebSocket (反向)

### 使用协议

2 | Android Watch

### 重现步骤

用安卓手表登陆之后，发现有的群收不到消息
有的群和私聊正常
把机器人踢出去再加回来，又能收到消息
但是过一会有概率又开始收不到
这时踢出去也是有效
不知道是否和安卓手表协议有关

### 期望的结果是什么？

正常收到消息

### 实际的结果是什么？

没有收到

**Comment by lancer-wang** [comment]
> 手表协议缺陷

主要现在其他协议都登陆不上
emmmm

**Comment by medicago087** [comment]
你用dev就可以安卓平板协议登录了

**Comment by lancer-wang** [comment]
> 你用dev就可以安卓平板协议登录了

https://github.com/Mrs4s/go-cqhttp/actions/runs/4335839018
用这个可以了

**Comment by Find-fengqingwu** [comment]
由于Android Watch协议的省电特性,当群被设置为不提醒的的时候，就不会接收消息
可以尝试同时在手机端登录，在群聊设置里重复开关一次消息免打扰
