### ISSUE TITLE
[Bug]: 完整的内容QQ发不出来，例如\n#

### ISSUE THREAD

**Issue by Spectual** [Mrs4s/go-cqhttp#1963]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

rc3

### 运行环境

MacOS

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

HTTP

### 使用协议

2 | Android Watch

### 重现步骤

我将机器人接入ChatGPT，让他写一段代码，最终返回的内容是完整的代码，但是qq发出来就只有前面一小部分，后面的内容被吞了。我尝试多次发现因为出现了这个字符组合：\n#
有什么解决方法吗？

### 期望的结果是什么？

发出完整的信息

### 实际的结果是什么？

qq发不出来完整的

**Comment by Spectual** [comment]
我发现是因为#、？、&是url的特殊字符，所以没有识别出来，有什么解决方法吗

**Comment by wdvxdr1123** [comment]
1. urlencode
2. 换POST，使用json，form传数据
