### ISSUE TITLE
无法接收到频道消息

### ISSUE THREAD

**Issue by skilittle** [Mrs4s/go-cqhttp#1966]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc4

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

2 | Android Watch

### 重现步骤

无法接收到频道消息

### 期望的结果是什么？

接收频道消息

### 实际的结果是什么？

完全接收不到频道消息，但是可以发送

**Comment by Mrs4s** [comment]
`Watch` 协议无法收频道消息

**Comment by Spectator133** [comment]
> `Watch` 协议无法收频道消息
可以借楼吗, 刚看到大佬还在, 近期被t下线后, 服务器上就登录不了了, 配置肯定没问题的因为近期还在运行, 更换新服务器(怀疑ip被封)及新账号依然无法登录, 同环境扫码后提示密码错误或被封禁.   不知道问题产生在哪,

**Comment by skilittle** [comment]
> > `Watch` 协议无法收频道消息
> > 可以借楼吗, 刚看到大佬还在, 近期被t下线后, 服务器上就登录不了了, 配置肯定没问题的因为近期还在运行, 更换新服务器(怀疑ip被封)及新账号依然无法登录, 同环境扫码后提示密码错误或被封禁.   不知道问题产生在哪,

协议改成Android Watch才行，最近抽风了
