### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Spectator133** [Mrs4s/go-cqhttp#1968]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3 & v1.0.0-rc4

### 运行环境

CentOS

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

正常登录  ./go-cqhttp

### 期望的结果是什么？

正常登录

### 实际的结果是什么？

[2023-03-11 14:22:41] [INFO]: 扫码成功, 请在手机端确认登录. 
[2023-03-11 14:22:49] [WARNING]: 登录失败: 密码错误或账号被冻结

### 补充说明（可选）

日志提示发送消息失败后, 退出重新登录, 同环境扫码后显示 登录失败: 密码错误或账号被冻结, 密码肯定正确的, 且无封禁, 手机及win qq正常登录,;

照着账号封禁的思路, 更换了账号, 删除device文件重试, 上述错误提示重现;

然后更换服务器(ip更换), 更换干净账号(新申请), 上述错误提示重现;

配置文件跑了3个月左右, 且之前成功运行过, 尝试修改也无果(因为没啥关键配置需要修改), 目前已经找不到解决思路, 遂来提问

**Comment by VermiIIi0n** [comment]
#1942
