### ISSUE TITLE
[Bug]: 登录失败，显示账号被冻结或密码错误

### ISSUE THREAD

**Issue by Lithium5C** [Mrs4s/go-cqhttp#1974]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc4

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

在Windows10系统下登录，扫描二维码后显示账号被冻结或密码错误（老一点的版本直接显示账号被冻结），但账号能正常在手机（Android系统）和电脑上都能正常登录

### 期望的结果是什么？

账号正常登录

### 实际的结果是什么？

登录失败，显示被冻结或密码错误，无法正常登录

**Comment by xianrui69** [comment]
附议+1；windows服务器上挂的cq也是这样，配置了正确的密码却提示这个

**Comment by xianrui69** [comment]
> 附议+1；windows服务器上挂的cq也是这样，配置了正确的密码却提示这个
> 
> Seconded +1;Windows server on the cq is the same, configured the correct password but prompted this

我尝试了修改密码，然后使用新密码；还有就是降级使用R3版本，但是结果一样

**Comment by whale-song** [comment]
+1，我的是直接扫码后显示账号被冻结
