### ISSUE TITLE
[Bug]: 使用dev分支之后，无法扫码验证，然后还会出现版本低

### ISSUE THREAD

**Issue by WillyerQ** [Mrs4s/go-cqhttp#1975]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

414f067

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

直接运行，然后验证方式选扫码验证时会出现
![F0A6D8085ECE2CB738ED8E417CB11099](https://user-images.githubusercontent.com/126785476/224700380-f991285a-5a07-44ac-b84f-474b778d9c26.jpg)
选浏览器抓取时会出现
![SSUSV2%~_M5@)}NO}E`PS8V](https://user-images.githubusercontent.com/126785476/224700516-79a4eb7a-3d21-4d1f-9be4-d7b93458fc04.png)

### 期望的结果是什么？

可以成功登陆

### 实际的结果是什么？

无法扫码验证，QQ版本过低

**Comment by WillyerQ** [comment]
Phone协议或者Android Pad协议一样出现版本低
![V@)HG9$%C8P2(I~A%@~Z KG](https://user-images.githubusercontent.com/126785476/224702890-5a4fe53c-463a-46d7-9a02-90aadb3425e7.png)
![QQ截图20230313203006](https://user-images.githubusercontent.com/126785476/224702922-df7799be-b5cb-40cd-b5db-5b344f8e3bd6.png)

**Comment by idlist** [comment]
![image0](https://user-images.githubusercontent.com/29368226/224914003-72a6dce7-76eb-4411-97d2-82af3ed484f2.png)

用的 dev 分支最新 CI Artifact，昨天试了一天和上面同情况，登录的时候始终未出现短信验证选项；今天再试了一下（使用同一个可执行文件）出现这个提示，遂终于登上号。

**Comment by Mrs4s** [comment]
414f067 版本太老了, 请更新最新的ci

**Comment by DiaoChan1** [comment]
> 

使用最新ci无法使用apad/phone 账号密码登录 但但是macos协议可以

**Comment by WillyerQ** [comment]
下载最新的CI之后，用Apad协议没有问题，可以正常登陆，但是用ipad协议会出现QQ版本低的报错，报错代码为235
