### ISSUE TITLE
处理某些好友消息非常慢

### ISSUE THREAD

**Issue by corvo007** [Mrs4s/go-cqhttp#198]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.22
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
处理某些好友消息非常慢，需要20秒甚至更长才能回复，而且控制台中收到消息时间会滞后20秒或者更长，报错如下：
![P_S 1W9Q7%O0}K1CU_N3~$7](https://user-images.githubusercontent.com/67192165/91302761-8c8a1300-e7d9-11ea-9aef-ad2050638441.png)

**复现方法**
1.设置bot为验证问题答案加好友
2.添加bot好友
3.发送消息

**Comment by sam01101** [comment]
没法复现，请问是否可以提供更详细的信息？
