### ISSUE TITLE
[Bug]: 获取频道消息api出错了

### ISSUE THREAD

**Issue by shandianex1** [Mrs4s/go-cqhttp#1980]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0.rc4

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

HTTP

### 使用协议

2 | Android Watch

### 重现步骤

get_guild_member_list 接口获取频道成员列表出错

### 期望的结果是什么？

返回频道成员

### 实际的结果是什么？

{
    "data": null,
    "msg": "API_ERROR",
    "retcode": 100,
    "status": "failed",
    "wording": "send packet error: Packet timed out"
}

**Comment by tom-snow** [comment]
试试新版本，另外是偶发还是特定群必发还是什么情况？

**Comment by shandianex1** [comment]
r
