### ISSUE TITLE
[Bug]:密码正确，而且没有被冻结

### ISSUE THREAD

**Issue by Shellless-Snail** [Mrs4s/go-cqhttp#1983]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc4

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

登录时密码正确，而且没有被冻结，却显示密码错误
![image](https://user-images.githubusercontent.com/52697574/225259530-b9a38403-3a37-445d-bb38-419e12ddfc46.png)

### 期望的结果是什么？

能正常登录

### 实际的结果是什么？

登录失败

**Comment by Flano-123** [comment]
用rc4版本，协议改为2，本地同Wifi情况下扫码登陆，然后将device.json 和session.token 拷贝到服务器端可解决（刚才解决的我也是）

**Comment by Shellless-Snail** [comment]
> 用rc4版本，协议改为2，本地同Wifi情况下扫码登陆，然后将device.json 和session.token 拷贝到服务器端可解决（刚才解决的我也是）

不行啊，我就是用相同的wifi，能扫码，但是说我密码错误，你有设置密码吗

**Comment by Flano-123** [comment]
> > 用rc4版本，协议改为2，本地同Wifi情况下扫码登陆，然后将device.json 和session.token 拷贝到服务器端可解决（刚才解决的我也是）
> 
> 不行啊，我就是用相同的wifi，能扫码，但是说我密码错误，你有设置密码吗

config.yml里面还是设置了密码的

**Comment by Mrs4s** [comment]
#1942 请使用最新的dev版本

**Comment by Shellless-Snail** [comment]
> > > 用rc4版本，协议改为2，本地同Wifi情况下扫码登陆，然后将device.json 和session.token 拷贝到服务器端可解决（刚才解决的我也是）
> > 
> > 
> > 不行啊，我就是用相同的wifi，能扫码，但是说我密码错误，你有设置密码吗
> 
> config.yml里面还是设置了密码的

我也是设置了密码的，账号也没冻结，你之前的异常也是密码错误或者账号冻结吗

**Comment by Flano-123** [comment]
> > > > 用rc4版本，协议改为2，本地同Wifi情况下扫码登陆，然后将device.json 和session.token 拷贝到服务器端可解决（刚才解决的我也是）
> > > 
> > > 
> > > 不行啊，我就是用相同的wifi，能扫码，但是说我密码错误，你有设置密码吗
> > 
> > 
> > config.yml里面还是设置了密码的
> 
> 我也是设置了密码的，账号也没冻结，你之前的异常也是密码错误或者账号冻结吗

各种错误都有，因为我每种协议都尝试了，感觉这个提示不是很准确。我也只能给你描述我刚刚成功的步骤 = =

**Comment by Shellless-Snail** [comment]
> 

最新的版本不是v1.0.0-rc4嘛
