### ISSUE TITLE
收不到全部类型好友消息，控制台不显示

### ISSUE THREAD

**Issue by LR1093141031** [Mrs4s/go-cqhttp#199]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.21fix
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
在windows10 或 windowsserver2012r2 上运行
都无法接收到好友消息，无论是否为单向好友

**复现方法**
持续存在此问题，从0.9.19 到 0.9.21fix 更换使用过 amd64 386等版本 仍存在问题

**Comment by Mrs4s** [comment]
请使用最新版
