### ISSUE TITLE
[Bug]: 转换消息 [CQ:forward,id=xxx]到MiraiGo Element时出现错误: forward 消息中必须包含 id.

### ISSUE THREAD

**Issue by 2659170494** [Mrs4s/go-cqhttp#1998]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc5

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

在新版QQ任意转发合并消息给机器人即可

### 期望的结果是什么？

在之前版本以及我写的代码中，go-cqhttp会重复发回对应的合并消息

### 实际的结果是什么？

更新过后，我只看到了文本版的[CQ:forward,id=xxx]。
并且日志中出现了[2023-03-19 23:21:40] [WARNING]: 转换消息 [CQ:forward,id=xxx] 到MiraiGo Element时出现错误: forward
消息中必须包含 id.

### 日志记录（可选）

```golang
[2023-03-19 23:21:39] [INFO]: 收到好友 绿色耀西(非放假不在线)(xxx) 的消息
: [CQ:forward,id=W855/kmx7oIiXGKZsTkHthAAq0iqgDaHkqvVrybAVjz3TswUdN6lRy2Md9Qb+Kr
I] (1369060575)
[2023-03-19 23:21:40] [DEBUG]: 上报Event数据 {"post_type":"message","message_typ
e":"private","time":1679239299,"self_id":xxx,"sub_type":"friend","user_id
":xxx,"target_id":xxx,"message":"[CQ:forward,id=W855/kmx7oIiXGKZsT
kHthAAq0iqgDaHkqvVrybAVjz3TswUdN6lRy2Md9Qb+KrI]","raw_message":"[CQ:forward,id=W
855/kmx7oIiXGKZsTkHthAAq0iqgDaHkqvVrybAVjz3TswUdN6lRy2Md9Qb+KrI]","font":0,"send
er":{"age":0,"nickname":"绿色耀西(非放假不在线)","sex":"unknown","user_id":xxx},"message_id":1369060575}
 到 http://127.0.0.1:1317
[2023-03-19 23:21:40] [DEBUG]: HTTPServer接收到API调用: send_private_msg
[2023-03-19 23:21:40] [WARNING]: 转换消息 [CQ:forward,id=W855/kmx7oIiXGKZsTkHthA
Aq0iqgDaHkqvVrybAVjz3TswUdN6lRy2Md9Qb+KrI] 到MiraiGo Element时出现错误: forward
消息中必须包含 id.
```

### 补充说明（可选）

代码没用任何框架，用网上的socket转http代码对接go-cqhttp

**Comment by 2659170494** [comment]
注：通过自带接口(/get_forward_msg?messages=W855/kmx7oIiXGKZsTkHthAAq0iqgDaHkqvVrybAVjz3TswUdN6lRy2Md9Qb+KrI)返回的消息是：{"data":null,"message":"消息不存在","msg":"MSG_NOT_FOUND","retcode":100,"status":"failed","wording":"消息不存在"}

**Comment by 2659170494** [comment]
#2001 转发消息解决了，但HTTP依旧出现找不到消息

**Comment by EnderFx2** [comment]
请使用/get_forward_msg?message_id=W855/kmx7oIiXGKZsTkHthAAq0iqgDaHkqvVrybAVjz3TswUdN6lRy2Md9Qb+KrI
参数名称是message_id

> #2001 转发消息解决了，但HTTP依旧出现找不到消息 @wdvxdr1123 @EnderFx2 🤔

**Comment by 2659170494** [comment]
@EnderFx2 谢谢awa
