### ISSUE TITLE
使用Termux运行arm64版本时报错：panic: runtime error: index out of range [-1] [Bug]: 

### ISSUE THREAD

**Issue by reine-ishyanami** [Mrs4s/go-cqhttp#2002]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc5

### 运行环境

UNIX (Android)

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

环境：在**Android**设备上使用**Termux**终端模拟器运行
1. 使用wget下载[go-cqhttp_linux_arm64.tar.gz](https://github.com/Mrs4s/go-cqhttp/releases/download/v1.0.0-rc5/go-cqhttp_linux_arm64.tar.gz)
2. 使用tar解压`mkdir go-cqhttp && tar -zxvf go-cqhttp_linux_arm64.tar.gz -C go-cqhttp`
3. 跳转到程序目录执行`./go-cqhttp`，直接回车
4. 填写QQ号和密码（可以不填）
5. 再次运行`./go-cqhttp`

### 期望的结果是什么？

登录成功，显示昵称，如下图
![image](https://user-images.githubusercontent.com/46278371/226235289-3dbc71bc-9aa2-4418-912d-16e181180ad2.png)

### 实际的结果是什么？

报错，程序结束运行
![image](https://user-images.githubusercontent.com/46278371/226235413-7f526290-e45d-436a-84b7-422489ce978c.png)

### 日志记录（可选）

```golang
[2023-03-20 02:44:06] [INFO]: 当前版本:v1.0.0-rc5
[2023-03-20 02:44:06] [WARNING]: 虚拟设备信息不存在, 将自动生成随机设备.
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/Mrs4s/MiraiGo/client/internal/auth.pkcs5Trimming(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230317162854-fd83d24f6794/client/internal/auth/qimei.go:107
github.com/Mrs4s/MiraiGo/client/internal/auth.aesDecrypt({0xb2b5e0, 0x0, 0x0}, {0x400029e140, 0x10, 0x10})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230317162854-fd83d24f6794/client/internal/auth/qimei.go:97 +0xe8
github.com/Mrs4s/MiraiGo/client/internal/auth.(*Device).RequestQImei(0x4000402000)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230317162854-fd83d24f6794/client/internal/auth/qimei.go:66 +0x6f4
github.com/Mrs4s/MiraiGo/client.GenRandomDevice()
        github.com/Mrs4s/MiraiGo@v0.0.0-20230317162854-fd83d24f6794/client/global.go:84 +0xcdc
github.com/Mrs4s/go-cqhttp/cmd/gocq.LoginInteract()
        github.com/Mrs4s/go-cqhttp/cmd/gocq/main.go:155 +0x364
main.main()
        github.com/Mrs4s/go-cqhttp/main.go:20 +0x28
```

### 补充说明（可选）

之前用过rc3和rc4，可以正常使用，没有出现过类似的bug

**Comment by tom-snow** [comment]
1、试试能不能用 32 位版本
2、是在 termux 的 proot 里面运行的吗

**Comment by cpms** [comment]
![image](https://user-images.githubusercontent.com/4178287/226310630-59ffd4ce-3c56-459b-b142-5b7050cd2f51.png)
我这边出现类似的情况，版本rc5，按照要求删除了device.json，x86架构，系统为64位的Rocky Linux，尝试了64位和32位的版本都是都一样起不来。

**Comment by reine-ishyanami** [comment]
> 1、试试能不能用 32 位版本 2、是在 termux 的 proot 里面运行的吗

用`termux-chroot`后解决了，谢谢

**Comment by enldm** [comment]
> 1、试试能不能用 32 位版本 2、是在 termux 的 proot 里面运行的吗

我用Userland下的Ubuntu同样的报错...
