### ISSUE TITLE
[Bug]: 无法上传群文件，不管路径写什么都提示 上传失败：文件不存在

### ISSUE THREAD

**Issue by sd3970566** [Mrs4s/go-cqhttp#2007]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

 v1.0.0 -rc5

### 运行环境

Windows (64)

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

1 | Android Phone

### 重现步骤

ret ＝ 编码_Utf8到Ansi (网页_访问_对象 (“http://127.0.0.1:5705/upload_group_file”, 0, “file=C:\README.md” ＋ “&group_id=173123783” ＋ “&name=README.md”))

尝试过把本地路径进行url编码  也不行喔

### 期望的结果是什么？

希望能够正常发送群文件。并且API文档里没有找到群文件转发另外一个群的功能。
之前用的其他框架支持 转发群文件文件

### 实际的结果是什么？

ret如下
“{"data":null,"message":"文件不存在","msg":"FILE_NOT_FOUND","retcode":100,"status":"failed","wording":"文件不存在"}

### 补充说明（可选）

希望修复上传群文件功能的基础上。再加一个转发群文件的功能

**Comment by OREOCODEDEV** [comment]
如果通信方式为 HTTP 建议在 issue 的 **重现步骤** 中直接提交有问题的请求地址，提交~~不常见的~~方法以及使用位置参数会降低描述的可读性
按照 go-cqhttp 文档，`file`参数如果使用本地文件应使用绝对路径且以`file:///`开头，例如`file:///C:\\Users\Richard\Pictures\1.png`

**Comment by sd3970566** [comment]
群文件分享给另外一个群可以实现吗？ 频繁上传文件会被官方拉黑， 如果是分享的话就没有问题。

**Comment by sd3970566** [comment]
posturl:  “http://127.0.0.1:5705/upload_group_file”
postdata: “file=file:///C:\README.md” ＋ “&group_id=173123783” ＋ “&name=README.md”
已经按这样提交了。还是提示“文件不存在”

**Comment by hnweizhi** [comment]
对的，我也是这样  怎么办 ？
