### ISSUE TITLE
[Bug]: 偶发性原样发送cq码

### ISSUE THREAD

**Issue by forchannot** [Mrs4s/go-cqhttp#2010]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

最新dev和rc5

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

**rc5的apad协议**
在正常使用nonebot端进行MessageSegment发送图片等时，偶发性经常由于网络超时（也许）导致发送结果为原cq码而非图片，重启gocq后大概率恢复正常。在之前的rc4和dev版本（rc5之前）使用的watch协议，rc3使用的ipad协议均没有出现过这个问题。已经排查过服务器网络没问题，且更换过github图片代理地址，暂未测试rc5的watch协议

### 期望的结果是什么？

能正常转化cq码

### 实际的结果是什么？

偶发性原样发送cq码

### 日志记录（可选）

```golang
'''
[2023-03-21 09:57:12] [WARNING]: 转换消息 [CQ:image,file=https://ghproxy.com/https://raw.githubusercontent.com/Nwflower/genshin-atlas/master/四风原典,type=,cache=true,proxy=true,timeout=] 到MiraiGo Element时出现错误: Get "https://ghproxy.com/https://raw.githubusercontent.com/Nwflower/genshin-atlas/master/%E5%9B%9B%E9%A3%8E%E5%8E%9F%E5%85%B8": context deadline exceeded (Client.Timeout exceeded while awaiting headers). 
'''
```

**Comment by 122809690** [comment]
同样遇到  偶发性发送原本的cq码   大概正常50次左右会遇到一次  
[2023-03-24 14:21:07] [WARNING]: 转换消息 [CQ:image,file=https://i.pixiv.re/img-original/img/2022/03/29/22/45/35/97266053_p0.jpg] 到MiraiGo Element时出现错误: context deadline exceeded (Client.Timeout or context cancellation while reading body).

**Comment by BearD01001** [comment]
貌似图片请求失败会这样，可能是图片原站把你的服务器 ip 限频了

**Comment by BearD01001** [comment]
貌似图片请求失败会这样，可能是图片原站把你的服务器 ip 限频了

**Comment by CMHopeSunshine** [comment]
确认网络正常，api也能正常访问，curl和python里都能稳定获取图片，但gocq这里就容易context deadline exceeded，rc5才出现这个问题，rc4是能稳定发的

**Comment by NanakoOfficial** [comment]
> 确认网络正常，api也能正常访问，curl和python里都能稳定获取图片，但gocq这里就容易context deadline exceeded，rc5才出现这个问题，rc4是能稳定发的

我也遇到了这个问题，rc4从来没出现过

**Comment by Mrs4s** [comment]
这个问题是因为rc5为默认的http client添加了超时设置 默认五秒

**Comment by CMHopeSunshine** [comment]
超时时间能否提供配置选项呢，5秒的话大一点的图片就很容易超时

**Comment by Janet-Baker** [comment]
> 这个问题是因为rc5为默认的http client添加了超时设置 默认五秒

请问添加到哪里了呢？能改吗？网速很慢，图片发不出去……

**Comment by 2598142880** [comment]
> > 超时时间能否提供配置选项呢，5秒的话大一点的图片就很容易超时
> 
> 我的也有，客户端服务器间网速很慢，就很容易超时。文字+图片的消息只发出了文字。
> 
> 找了找，是在这里 [174d99f](https://github.com/Mrs4s/go-cqhttp/commit/174d99f94b31cee8ca4b9f4a56e6d95d4ec51601) 更改的。超时时间改一下再编译，就可以发出来了。

大佬能否发我一下呢？我搞不懂什么编译。qq2598142880。求，不知道这样发符不符合规范
