### ISSUE TITLE
bot被禁言时无法退出群聊

### ISSUE THREAD

**Issue by xhl6666** [Mrs4s/go-cqhttp#202]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.22
运行环境: ubuntu_amd64
连接方式: 反向WS

**bug内容**
当bot在群内被禁言时，调用set_group_leave方法时报错"账号无可能被风控"，无法主动退群，取消bot的禁言后方可主动退群。

**复现方法**
在qq群内禁言bot，调用set_group_leave，bot无法退出群群聊。取消bot在群内禁言以后，又可以正常退群

**Comment by F0ur** [comment]
测试了下。。无法重现
另外
```
群消息发送失败: 账号可能被风控. 
```
这个提示只在send_group_message的时候才会出现，其他地方没有出现过风控2个字

**Comment by var-mixer** [comment]
打扰了，这个错误实际是在使用了[authMS](https://github.com/pcrbot/authMS)授权管理系统而出现的，我错误地将`send_group_msg()`和`set_group_leave()`使用了同一个`try`来抓取异常，因此被禁言时会发言失败从而提前退出，无法退群。目前已解决。
此问题并非go-cqhttp的问题，打扰了开发者了。
