### ISSUE TITLE
[Bug]: 如何在Mac中使用go-cqhttp？

### ISSUE THREAD

**Issue by HowardJones114514** [Mrs4s/go-cqhttp#2021]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

 - 

### 运行环境

MacOS

### 运行架构

None

### 连接方式

HTTP

### 使用协议

2 | Android Watch

### 重现步骤

买一台Mac或使用黑苹果系统

### 期望的结果是什么？

获得一个能在mac中运行的go-cqhttp

### 实际的结果是什么？

并没有获得一个能在mac中运行的go-cqhttp

**Comment by Mrs4s** [comment]
您好 我现在用的就是Mac

**Comment by Ink-33** [comment]
![image](https://user-images.githubusercontent.com/51873347/227697702-42ae9ad7-c232-4728-ace1-28cdb580c43f.png)
