### ISSUE TITLE
[Bug]: 音乐分享实际结果在新的版本的各种协议里面变成了新闻分享

### ISSUE THREAD

**Issue by gcorpse** [Mrs4s/go-cqhttp#2026]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc5

### 运行环境

Windows (64)

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

新版本的音乐分享出错了，变成了新闻分享

### 期望的结果是什么？

{"app":"com.tencent.structmsg","desc":"音乐","view":"music","ver":"0.0.0.1","prompt":"[分享]说爱你","meta":{"music":{"action":"","android_pkg_name":"","app_type":1,"appid":100497308,"ctime":1679854420,"desc":"蔡依林【VIP】","jumpUrl":"http:\/\/aqqmusic.tc.qq.com\/amobile.music.tc.qq.com\/C400003Auh9r2Z5Wys.m4a?guid=undefined&vkey=2912B9BCEBC74F8BDA5CB1EB46C51A62362C154D38164677941E7C05BE06FFAF2D2FFC42633AFBFEAEA70EA70E63C3CC7FEE4ECFEB92569A&uin=2508969256&fromtag=123032","musicUrl":"http:\/\/aqqmusic.tc.qq.com\/amobile.music.tc.qq.com\/C400003Auh9r2Z5Wys.m4a?guid=undefined&vkey=2912B9BCEBC74F8BDA5CB1EB46C51A62362C154D38164677941E7C05BE06FFAF2D2FFC42633AFBFEAEA70EA70E63C3CC7FEE4ECFEB92569A&uin=2508969256&fromtag=123032","preview":"http:\/\/y.gtimg.cn\/music\/photo_new\/T002R150x150M000000q5U9S2OLNg4.jpg","sourceMsgId":"0","source_icon":"https:\/\/p.qpic.cn\/qqconnect\/0\/app_100497308_1626060999\/100?max-age=2592000&t=0","source_url":"","tag":"QQ音乐","title":"说爱你","uin":2818536614}},"config":{"ctime":1679854420,"forward":true,"token":"15f648338bcbed0f2f7ea4cc61f857fd","type":"normal"}}

### 实际的结果是什么？

{"app":"com.tencent.structmsg","desc":"新闻","view":"news","ver":"0.0.0.1","prompt":"[分享]说爱你","meta":{"news":{"action":"","android_pkg_name":"","app_type":1,"appid":100497308,"ctime":1679853564,"desc":"蔡依林【VIP】","jumpUrl":"http:\/\/aqqmusic.tc.qq.com\/amobile.music.tc.qq.com\/C400003Auh9r2Z5Wys.m4a?guid=undefined&vkey=FEE36554617DE8604E7062AB3755A09CF7D554FBB3633C8D78574B0457BBF305A0DB95236EE8860A2322A879BE1E5398D5BB6E36895FD0E0&uin=2508969256&fromtag=123032","preview":"http:\/\/y.gtimg.cn\/music\/photo_new\/T002R150x150M000000q5U9S2OLNg4.jpg","source_icon":"https:\/\/p.qpic.cn\/qqconnect\/0\/app_100497308_1626060999\/100?max-age=2592000&t=0","source_url":"","tag":"QQ音乐","title":"说爱你","uin":2818536614}},"config":{"ctime":1679853564,"forward":true,"token":"a65795a3d705b825e7ab6a75c2b8a375","type":"normal"}}

### 简单的复现代码/链接（可选）

```golang
[CQ:music,type=custom,subtype=qq,title=标题,url=链接,audio=链接,image=封面,content=v386_作者]
```

**Comment by Yincmewy** [comment]
rc5修改了音乐自定义分享的参数，音频audio换为voice

**Comment by gcorpse** [comment]
> 
现在最新版本里的点歌，右边按键已经变得不可用，需要点进里面听，退出里面就不能听，这太不行了，不只是我有意见，看到的人都觉得蛋疼。你是说自己转换为voice上传语音听？那更不行呀，会被笑死。不知道有什么方式给弄回旧版本的？具体怎么做？
