### ISSUE TITLE
Feat req: support global http proxy

### ISSUE THREAD

**Issue by purerosefallen** [Mrs4s/go-cqhttp#2027]
**环境信息**

go-cqhttp版本: 1.0.0-rc5

**需要添加的功能内容**

When it comes to multiple accounts, which cannot be held by a single IP address, it's sometimes needed to login via another IP address by HTTP proxy. It's pretty common when 6 or more QQ accounts. in this way, we could deploy a cluster of HTTP proxies to login via different IP addresses.

**Comment by Mrs4s** [comment]
recommend using `Proxifier`, this feature won't be added
