### ISSUE TITLE
输入图片验证码后闪退

### ISSUE THREAD

**Issue by witpark** [Mrs4s/go-cqhttp#203]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.22
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
在一台电脑上用不同端口开了两个机器人。第二个机器人提示输入图片验证码后闪退

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by Mrs4s** [comment]
请查看log或者使用cmd打开机器人并提交具体错误

**Comment by chenruhai** [comment]
我也遇到了这个问题，0.9.40版本。据说1.0版本没有那个问题
