### ISSUE TITLE
[Bug]:有部分号码除手表协议外提示版本过低 apad报code：45  ipad报code：235

### ISSUE THREAD

**Issue by shenEEyi** [Mrs4s/go-cqhttp#2031]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

rc5

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

部分号码出现版本过低

### 期望的结果是什么？

可以正常登录

### 实际的结果是什么？

登录报code：45和code：235

**Comment by shenEEyi** [comment]
rc5版本

**Comment by zhangweizi** [comment]
相同问题，不知道什么原因

**Comment by NKDark** [comment]
+1,后面几个协议都不行，切换至mac协议后正常登陆

**Comment by xue1213888** [comment]
同样的+1

**Comment by wangozoo** [comment]
> +1,后面几个协议都不行，切换至mac协议后正常登陆

怎么切换协议啊

**Comment by AOSenKusa** [comment]
测试有用，如果报code：45，在device.json文件，修改"protocol"属性的值为3，就能切换协议成mac协议，然后重新运行就能成功登陆了。

**Comment by wangozoo** [comment]
> 测试有用，如果报code：45，在device.json文件，修改"protocol"属性的值为3，就能切换协议成mac协议，然后重新运行就能成功登陆了。

谢谢，有用的

**Comment by Mrs4s** [comment]
错误45现在已经好了
错误235换device

**Comment by xue1213888** [comment]
EN:Your email may be blocked!CN:你的邮件可能被屏蔽！JP:あなたのEメールがブロックされている可能性があります。
