### ISSUE TITLE
[Bug]: 1.0.0-rc5使用帮助，解决新人登录报错

### ISSUE THREAD

**Issue by umena337** [Mrs4s/go-cqhttp#2033]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0-rc5

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

2 | Android Watch

### 重现步骤

​
2023-03-28 时效性强，当前最新版本v1.0.0-rc5

本地虚拟机 linux服务器，纯净centos7安装使用

下载：[Releases · Mrs4s/go-cqhttp · GitHub](https://github.com/Mrs4s/go-cqhttp/releases)
下载go-cqhttp_1.0.0-rc5_linux_amd64.rpm
传到服务器，新建一个目录放/home/gocq1，会生成配置在同目录下
安装rpm -ivh go-cqhttp_1.0.0-rc5_linux_amd64.rpm
第一次运行 go-cqhttp
您的选择是:0
第一次运行后同目录会生成config.yml
进去改一行vi config.yml  就改里面qq号一行就行
第二次运行 go-cqhttp
会报，当前协议不支持二维码登录, 请配置账号密码登录.
第二次运行后同目录会生成device.json
进去改一个 vi device.json   将"protocol":6 改成 "protocol":2
第三次运行 go-cqhttp
才会跳出扫码
小号扫码登录才能成功

版本特性：其他协议qq改了，当前时段只有安卓手表协议还能用，而默认用的其他协议，所以直接用不行。首次使用用密码登录也不行，会跳出新设备扫码，用不了。

### 期望的结果是什么？

issue里不要再问登录失败问题了

### 实际的结果是什么？

issue再问登录失败问题

**Comment by Am2333** [comment]
必须同网段登录才行，服务器上部署的怎么做？我记得之前有Session替换的方法？这是不是需要补充一下

**Comment by Am2333** [comment]
> > 
> 
> 使用扫码登录不用同网段，我在服务器上试过了

好的，感谢

**Comment by Am2333** [comment]
> > 
> 
> 使用扫码登录不用同网段，我在服务器上试过了

按照步骤操作，最后一步提示还是因为不在同一网段
![E3D76B9FCAFA215C8A96A61208C05D80](https://user-images.githubusercontent.com/101511472/228502336-df725921-3b9a-4cb1-b786-3c313244d0e7.jpg)

**Comment by yccsfyzq** [comment]
> 

可以在服务器上装个openvpn之类的，然后手机连接服务器vpn，再登录qq扫码就是同网段扫码了
