### ISSUE TITLE
[Bug]: 新版本视频Video错误cannot run executable found relative to current directory.

### ISSUE THREAD

**Issue by gcorpse** [Mrs4s/go-cqhttp#2036]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc5

### 运行环境

Windows (64)

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

2 | Android Watch

### 重现步骤

以前的旧版本可以，但在最新rc5的版本，
调用视频会出错，是不是改了某些接口了？path里已经添加了ffmpeg环境。

[WARNING]: 转换消息 [CQ:video,file=file:///C:\Users\Administrator\Desktop\aaa.mp4] 到MiraiGo Element时出现错�? extract video cover failed: exec: "ffmpeg": cannot run executable found relative to current directory.

### 期望的结果是什么？

正常能正确

### 实际的结果是什么？

[WARNING]: 转换消息 [CQ:video,file=file:///C:\Users\Administrator\Desktop\aaa.mp4] 到MiraiGo Element时出现错�? extract video cover failed: exec: "ffmpeg": cannot run executable found relative to current directory.

### 简单的复现代码/链接（可选）

```golang
.../send_msg?message_type=group&user_id=66666&group_id=99999&message=[CQ:video,file=file:///C:\Users\Administrator\Desktop\aaa.mp4]
```

### 日志记录（可选）

```golang
[WARNING]: 转换消息 [CQ:video,file=file:///C:\Users\Administrator\Desktop\aaa.mp4] 到MiraiGo Element时出现错�? extract video cover failed: exec: "ffmpeg": cannot run executable found relative to current directory.
```

**Comment by Mrs4s** [comment]
由于升级了go版本, 现在开始不能执行工作目录下的 `ffmpeg` 了, 请添加环境变量

**Comment by gcorpse** [comment]
> 由于升级了go版本, 现在开始不能执行工作目录下的 了, 请添加环境变量`ffmpeg`

有的，我在环境变量里配置了，并且在msdos里也测试了在别的目录下ffmpeg可以用。并且我进一步测试发现，要是把环境变量的配置移除了，到时候提示就是别的错误，所以环境变量是正确的。希望能检查下，这个的确是新的改动有存在问题。也许...保留旧的在程序工作目录下的方式，当没有的时候再调用新的方式。保持兼容的
