### ISSUE TITLE
PC有群成员修改名片事件

### ISSUE THREAD

**Issue by yuanbin1998** [Mrs4s/go-cqhttp#204]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.10
运行环境: windows_amd64
连接方式: post

**bug内容**
之前酷Q得时候，群成员修改群名片是没有事件上报得，现在PC协议是有得，RC有没有兴趣兼容下，主要用于屏蔽一些名片广告。

**Comment by moobing** [comment]
+1 表示很需要这个

**Comment by Mrs4s** [comment]
我有空看看有没有这个事件

**Comment by takayama-lily** [comment]
貌似有人改名片收不到任何包，只有他发言的时候才能知道。

**Comment by yuanbin1998** [comment]
我仔细看看了，go-http好像是用得apad得协议，这个协议可能确实没有，只有PC应该有

**Comment by Mrs4s** [comment]
已支持
