### ISSUE TITLE
[Bug]: 视频发送给的url无法访问

### ISSUE THREAD

**Issue by longhao1987** [Mrs4s/go-cqhttp#2052]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0

### 运行环境

CentOS

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

3 | MacOS

### 重现步骤

客户端正常发送视频，bot能接收到

### 期望的结果是什么？

期望返回正常访问且可下载的url

### 实际的结果是什么？

但是返回的message里的url是这样的，无法访问，无法下载：
http://58.144.164.231:80/qqdownload?ver=537128930&amp;rkey=3081fd0201010481f53081f2020101020100020496f198800481a6333035313032303130303034333633303334303230313030303230343239366161336361303230333761316462393032303432396536336362373032303436343263343765343034313031633130376630383739356363675833303137656461316138383532616336653032303337613133663530323031303030343134303030303030303836363639366336353734373937303635303030303030303433313330333033310204642c47e604350000000866696c657479706500000004313030330000000b646f776e656e63727970740000000130000000047175696300000001300400&amp;filetype=1003&amp;videotype=1&amp;subvideotype=0&amp;term=unknow

**Comment by Mrs4s** [comment]
请 `unescape` 后再访问
