### ISSUE TITLE
[Bug]: 登录失败 code:45

### ISSUE THREAD

**Issue by CNlongY-Py** [Mrs4s/go-cqhttp#2053]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

go-cqhttp.exe -update-protocol

### 期望的结果是什么？

登录成功

### 实际的结果是什么？

抓取Ticket后显示
[WARNING]: 登录失败: 登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Code: 45

### 补充说明（可选）

删除device.json后仍然无果

使用windows_386后显示
 [WARNING]: 登录失败: 当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。 Code: 237
注:这台设备是登录过的

**Comment by Mrs4s** [comment]
请尝试用手机QQ登录 应该会提示需要身份验证 过一下试试

**Comment by CNlongY-Py** [comment]
手机登录没有提示身份验证,不过现在code:237

**Comment by Mrs4s** [comment]
能否留个联系方式 需要更多测试

**Comment by CNlongY-Py** [comment]
QQ:3464356490

**Comment by AIDanNy2023** [comment]
我也是同样的问题，一模一样，自动抓ticket或者手动抓ticket，登录的使用协议protocol用的是6，Apad，密码登录，同样的错误： 登录失败: 登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Code: 45； 难道莫非要用 WATCH 的扫码登录？那就太麻烦了。希望持续update

**Comment by AIDanNy2023** [comment]
最后还是用了 protocol 3 ， Mac协议登录通过了； 看来 1.0.0 正式版本也还是存在Code 45的问题，请版主知悉！

**Comment by CNlongY-Py** [comment]
好的我试试

**Comment by callng** [comment]
请不要使用超过8.9.35(包括)的协议，在新版本协议中将会验证包头部的sign(指pb)，如果错误或者没有填写就会”登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系“，如果使用8.9.28版本的协议那么一切正常。@CNlongY-Py @Mrs4s

**Comment by callng** [comment]
sign的来源：com.tencent.mobileqq.fe.FEKit 类，是一个native层算法，需要经过一系列初始化后调用getSign方法获取签名。

**Comment by Imagine6666** [comment]
> 

启动时如何指定protocal呢

**Comment by CNlongY-Py** [comment]
> > 
> 
> 启动时如何指定protocal呢

有一个device.json 里面可以改protocal

**Comment by Gho6** [comment]
要搭建签名服务器
