### ISSUE TITLE
[Bug]: [WARNING]: 登录失败: 登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Code: 45 

### ISSUE THREAD

**Issue by qq77522980** [Mrs4s/go-cqhttp#2056]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

1 | Android Phone

### 重现步骤

无法登录
检测到协议更新: 8.9.35.10440 -> 8.9.38.10545 
[2023-04-06 10:16:09] [INFO]: 如果登录时出现版本过低错误, 可尝试使用 -update-protocol 参数启动 
[2023-04-06 10:16:09] [INFO]: Protocol -> connect to server: 120.232.67.190:8080 
[2023-04-06 10:16:09] [WARNING]: 登录失败: 登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Code: 45 

即使用-update-protocol 参数启动，也是一样。

### 期望的结果是什么？

成功登录

### 实际的结果是什么？

登录失败:

**Comment by TeaBoss-Developer** [comment]
是新号吗,按理来说在gocqhttp\internal\encryption里我看到了544,不应该过不了校验,建议使用MacQQ登录.应该能解决您的问题.

**Comment by Leaderzhangyi** [comment]
遇到了同样的问题，先订阅了

**Comment by Mrs4s** [comment]
> 是新号吗,按理来说在gocqhttp\internal\encryption里我看到了544,不应该过不了校验,建议使用MacQQ登录.应该能解决您的问题.

提供的544算法测试可以过TLV的验证, 不过部分账号风控等级比较高可能要手Q登录一段时间才行
`45`是很多种风控的返回值 最极端的包括 `禁止在未知设备登录` 也会在官方客户端返回`45`

**Comment by TeaBoss-Developer** [comment]
> > 是新号吗,按理来说在gocqhttp\internal\encryption里我看到了544,不应该过不了校验,建议使用MacQQ登录.应该能解决您的问题.
> 
> 提供的544算法测试可以过TLV的验证, 不过部分账号风控等级比较高可能要手Q登录一段时间才行 `45`是很多种风控的返回值 最极端的包括 `禁止在未知设备登录` 也会在官方客户端返回`45`

了解,因为现在有两种情况,新号可能会有风控,那既然544可以过校验的话,问题算是未知了,对于我来说.现在解决办法应该也就手Q多挂一些时间或者使用Tim/MacQQ/LinuxQQ/手表扫码上线(我自行测试,与gi-cqhttp无关,新号我尝试只能在手表扫码和LinuxQQ密码登录)但是我在协议里面看到了MacQQ,所以此问题也许可以通过MacQQ登录解决(?)

**Comment by zhang-ykun** [comment]
同样的问题

**Comment by Mrs4s** [comment]
> > > 是新号吗,按理来说在gocqhttp\internal\encryption里我看到了544,不应该过不了校验,建议使用MacQQ登录.应该能解决您的问题.
> > 
> > 
> > 提供的544算法测试可以过TLV的验证, 不过部分账号风控等级比较高可能要手Q登录一段时间才行 `45`是很多种风控的返回值 最极端的包括 `禁止在未知设备登录` 也会在官方客户端返回`45`
> 
> 了解,因为现在有两种情况,新号可能会有风控,那既然544可以过校验的话,问题算是未知了,对于我来说.现在解决办法应该也就手Q多挂一些时间或者使用Tim/MacQQ/LinuxQQ/手表扫码上线(我自行测试,与gi-cqhttp无关,新号我尝试只能在手表扫码和LinuxQQ密码登录)但是我在协议里面看到了MacQQ,所以此问题也许可以通过MacQQ登录解决(?)

MacQQ曾经可以解决问题 但是现在强制推 `NTQQ` 了, 也会出现`235`强制升级新版本
可能部分风控高的号还是需要校验包头的`sign`, 也是一个 native 层的算法, 但是这个理论上会需要一些动态下发的参数, 所以暂时没研究.
总之这个问题主要还是账号风控等级太高, 实际上我测试很多这种账号拿官方客户端在新设备登录都会提示错误, 然后被引导到身份验证/人脸识别.
最好还是在官方客户端挂一段时间再说

**Comment by Mrs4s** [comment]
> 

如果仅仅是 `T544` 风控的号的话经过测试提供正确的`544`后就能登录了(随机是不行的, 所以服务端还是会校验)

**Comment by TeaBoss-Developer** [comment]
> > TeaBoss
> 
> 如果仅仅是 `T544` 风控的号的话经过测试提供正确的`544`后就能登录了(随机是不行的, 所以服务端还是会校验)

了解,我会尝试定位我账号存在的问题.另`Tim`/`LinuxQQ`疑似没有太严重的强校验,希望`go-cqhttp`贵软尽量更新一下此些协议.

**Comment by qq77522980** [comment]
> 是新号吗,按理来说在gocqhttp\internal\encryption里我看到了544,不应该过不了校验,建议使用MacQQ登录.应该能解决您的问题.

不是新号码，是已经挂了很久的QQ号码，安卓手机端也京擦汗给你会挂一下。

**Comment by TeaBoss-Developer** [comment]
> > 是新号吗,按理来说在gocqhttp\internal\encryption里我看到了544,不应该过不了校验,建议使用MacQQ登录.应该能解决您的问题.
> 
> 不是新号码，是已经挂了很久的QQ号码，安卓手机端也京擦汗给你会挂一下。

那据我的经验来看,如果是滑块以后出现的这两个问题,疑似是滑块的`t547`/`t548`的问题.先尝试一下`MacQQ`吧,实在不行`手表QQ`扫码上线.

**Comment by TeaBoss-Developer** [comment]
> > > > 是新号吗,按理来说在gocqhttp\internal\encryption里我看到了544,不应该过不了校验,建议使用MacQQ登录.应该能解决您的问题.
> > > 
> > > 
> > > 不是新号码，是已经挂了很久的QQ号码，安卓手机端也京擦汗给你会挂一下。
> > 
> > 
> > 那据我的经验来看,如果是滑块以后出现的这两个问题,疑似是滑块的`t547`/`t548`的问题.先尝试一下`MacQQ`吧,实在不行`手表QQ`扫码上线.
> 
> 按照你说的方法，我改了MACQQ，已经成功登录了，感谢感谢。。

暂时请使用此办法,剩下就得等贡献者们以及作者的更新了w.

**Comment by chenemiyi** [comment]
> 

MACQQ是需要mac端登陆认证吗？

**Comment by TeaBoss-Developer** [comment]
> > 
> 
> MACQQ是需要mac端登陆认证吗？

此话怎讲,`MacQQ`的流程与其他的是一样的.都是登录=>滑块=>设备锁.

**Comment by zhang-ykun** [comment]
修改设备配置信息



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: TeaBoss ***@***.***&gt;
发送时间: 2023年4月6日 17:55
收件人: Mrs4s/go-cqhttp ***@***.***&gt;
抄送: zhang-ykun ***@***.***&gt;, Manual ***@***.***&gt;
主题: Re: [Mrs4s/go-cqhttp] [Bug]: [WARNING]: 登录失败: 登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Code: 45  (Issue #2056)





    
MACQQ是需要mac端登陆认证吗？
  
此话怎讲,MacQQ的流程与其他的是一样的.都是登录=&gt;滑块=&gt;设备锁.

**Comment by chenzhifeng0025** [comment]
各位，如何修改设备信息为macqq啊

**Comment by Leaderzhangyi** [comment]
> 各位，如何修改设备信息为macqq啊
https://docs.go-cqhttp.org/guide/config.html#%E9%85%8D%E7%BD%AE%E4%BF%A1%E6%81%AF
仔细阅读，更改协议为MacOS

**Comment by chenzhifeng0025** [comment]
> MacQQ

这个在哪里改啊？

**Comment by chenzhifeng0025** [comment]
改好了，可以用了，谢谢

**Comment by sunwaylive** [comment]
> > MacQQ
> 
> 这个在哪里改啊？

Device.json, protocol字段改成3即可

**Comment by tao1344** [comment]
> > > > > 是新号吗，按理说在gocqhttp\internal\encryption里我看到了544，不应该过不了校园试验，建议使用MacQQ登录。应该能够解决您的问题。
> > > > 
> > > > 
> > > > 不是新号码，是已经挂了很久的QQ号码，安卓手机端也京擦汗给你会挂一下。
> > > 
> > > 
> > > 那据我的经验来看，如果是滑块以后出现的这两个问题，疑似是滑块的`t547`/`t548`的问题。先试一下`MacQQ`吧，实在不进行`手表QQ`扫描上线。
> > 
> > 
> > 按照你说的方法，我改了MACQQ，已经成功登录了，感谢感谢。。
> 
> 暂时请使用此方法，减下就得等捐献者以及作者的更新了w。

感谢，我也是这个问题，改了mac能正常登录了

**Comment by zhengxinonly** [comment]
我修改之后也可以了 感谢

**Comment by twguang** [comment]
同样的问题，不过我的是docker版，device.json里面没有`"protocol": 3,`这句代码，添加重启后还是会重现这个问题

**Comment by Cloud-wish** [comment]
协议2和3可以登录，但不能使用频道相关功能，还是希望开发者们能够修复这个Bug

**Comment by dmlgzs** [comment]
> MacQQ曾经可以解决问题 但是现在强制推 `NTQQ` 了, 也会出现`235`强制升级新版本 可能部分风控高的号还是需要校验包头的`sign`, 也是一个 native 层的算法, 但是这个理论上会需要一些动态下发的参数, 所以暂时没研究. 总之这个问题主要还是账号风控等级太高, 实际上我测试很多这种账号拿官方客户端在新设备登录都会提示错误, 然后被引导到身份验证/人脸识别. 最好还是在官方客户端挂一段时间再说

包头 sign 需要 uin、androidId (或IMEI)、cmd、body 包全部数据、seq 和 qimei36，除了 qimei 似乎并没有动态下发，seq 似乎关联性不大 (错误貌似也能登录)。整个签名是个 protobuf，塞在 MiraiGo 写着 qimei 的地方。
我自用的 oicq 里加上后解决了风控号的禁止登录的问题（同时账号的所有数据包都应该带签名，MessageSvc.PbSendMsg 也只有签名后才能正常发出消息）
目前都是调用 libfekit.so 生成的，希望后面会有算法

**Comment by TeaBoss-Developer** [comment]
> 

是这样的,现在主要的几个情况.
1.新号返回"45"
2.部分封过几次的号返回"45"
3.版本确实低了 "235"

1的解决办法就是您所说的加"sign",确实可以解决.
2的情况分好几种细分的情况了就,目前我尝试了sign+544+545,一些极端风控号并没有解决问题,但是部分正常报45的是可以过的.

**Comment by TeaBoss-Developer** [comment]
> > MacQQ曾经可以解决问题 但是现在强制推 `NTQQ` 了, 也会出现`235`强制升级新版本 可能部分风控高的号还是需要校验包头的`sign`, 也是一个 native 层的算法, 但是这个理论上会需要一些动态下发的参数, 所以暂时没研究. 总之这个问题主要还是账号风控等级太高, 实际上我测试很多这种账号拿官方客户端在新设备登录都会提示错误, 然后被引导到身份验证/人脸识别. 最好还是在官方客户端挂一段时间再说
> 
> 包头 sign 需要 uin、androidId (或IMEI)、cmd、body 包全部数据、seq 和 qimei36，除了 qimei 似乎并没有动态下发，seq 似乎关联性不大 (错误貌似也能登录)。整个签名是个 protobuf，塞在 MiraiGo 写着 qimei 的地方（[Mrs4s/MiraiGo@3a3355e00ad70242e5583d217d77874cbef4f606）。](https://github.com/Mrs4s/MiraiGo/commit/3a3355e00ad70242e5583d217d77874cbef4f606）。) 我自用的 oicq 里加上后解决了风控号的禁止登录的问题（同时账号的所有数据包都应该带签名，MessageSvc.PbSendMsg 也只有签名后才能正常发出消息） 目前都是调用 libfekit.so 生成的，希望后面会有算法

是这样的,现在主要的几个情况.
1.新号返回"45"
2.部分封过几次的号返回"45"
3.版本确实低了 "235"

1的解决办法就是您所说的加"sign",确实可以解决.
2的情况分好几种细分的情况了就,目前我尝试了sign+544+545,一些极端风控号并没有解决问题,但是部分正常报45的是可以过的.

**Comment by TeaBoss-Developer** [comment]
> 协议2和3可以登录，但不能使用频道相关功能，还是希望开发者们能够修复这个Bug

协议二对应的是`Android Watch‘,手表协议很多事件都是收不到的,属于硬性要求.
而协议三又是’Mac‘,由于本人不是’Mac‘用户,可能改‘NTQQ’了以后频道出现了某些问题,亦或者是其他.
因此这不属于是一个BUG而是一个限制,个人认为这个问题不好突破.
所以建议使用’1 5 6‘,如果能登陆上的情况下.

**Comment by Cloud-wish** [comment]
> > 协议2和3可以登录，但不能使用频道相关功能，还是希望开发者们能够修复这个Bug
> 
> 协议二对应的是`Android Watch`,手表协议很多事件都是收不到的,属于硬性要求. 而协议三又是`Mac`,由于本人不是`Mac`用户,可能改`NTQQ`了以后频道出现了某些问题,亦或者是其他. 因此这不属于是一个BUG而是一个限制,个人认为这个问题不好突破. 所以建议使用`1 5 6`,如果能登陆上的情况下.

频道功能在2、3不能用应该是QQ本身的限制，我的意思也是希望1、5、6能够解决Code 45的问题，我现在就是只有2、3能用，其它全部Code 45

**Comment by dmlgzs** [comment]
> 是这样的,现在主要的几个情况. 1.新号返回`45` 2.部分封过几次的号返回`45` 3.版本确实低了 `235`
> 
> 1的解决办法就是您所说的加`sign`,确实可以解决. 2的情况分好几种细分的情况了就,目前我尝试了`sign+544+545`,一些极端风控号并没有解决问题,但是部分正常报45的是可以过的.

光看 code 并不是完全一样的，45 返回的文本也有很多不同。有的是 `禁止登录：登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系`，这种一般就是缺少 T544/包头 sign；有的是 `禁止登录：你当前使用的QQ版本过低，请前往QQ官...` 这样的（不是 235 那个 guid 黑了的温馨提示），这种是被强制升级了，需要用最新版本，目前换成 8.9.50(537155547/537155595) 就可以解决；有的是 `禁止登录：你的账号因为存在安全风险，已进入安全保护状态，暂时不能登录`，这种应该只能手机上解了，理论上也可以实现相关的协议，估计要手机号验证/人脸/好友验证。

**Comment by TeaBoss-Developer** [comment]
> > 是这样的,现在主要的几个情况. 1.新号返回`45` 2.部分封过几次的号返回`45` 3.版本确实低了 `235`
> > 1的解决办法就是您所说的加`sign`,确实可以解决. 2的情况分好几种细分的情况了就,目前我尝试了`sign+544+545`,一些极端风控号并没有解决问题,但是部分正常报45的是可以过的.
> 
> 光看 code 并不是完全一样的，45 返回的文本也有很多不同。有的是 `禁止登录：登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系`，这种一般就是缺少 T544/包头 sign；有的是 `禁止登录：你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试` 这样的（不是 235 那个 guid 黑了的温馨提示），这种是被强制升级了，需要用最新版本，目前换成 8.9.50(537155547/537155595) 就可以解决；有的是 `禁止登录：你的账号因为存在安全风险，已进入安全保护状态，暂时不能登录`，这种应该只能手机上解了，理论上也可以实现相关的协议，估计要手机号验证/人脸/好友验证。

了解了,我所测试的那个极端的是 `您被限制在非常用设备登录`这种是无解的，得过人脸。`禁止登录：登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系`这个通过`sign`和`t544`确实可以解决。

**Comment by lin9081** [comment]
> > > MacQQ曾经可以解决问题 但是现在强制推 `NTQQ` 了, 也会出现`235`强制升级新版本 可能部分风控高的号还是需要校验包头的`sign`, 也是一个 native 层的算法, 但是这个理论上会需要一些动态下发的参数, 所以暂时没研究. 总之这个问题主要还是账号风控等级太高, 实际上我测试很多这种账号拿官方客户端在新设备登录都会提示错误, 然后被引导到身份验证/人脸识别. 最好还是在官方客户端挂一段时间再说
> > 
> > 
> > 包头 sign 需要 uin、androidId (或IMEI)、cmd、body 包全部数据、seq 和 qimei36，除了 qimei 似乎并没有动态下发，seq 似乎关联性不大 (错误貌似也能登录)。整个签名是个 protobuf，塞在 MiraiGo 写着 qimei 的地方（[Mrs4s/MiraiGo@3a3355e00ad70242e5583d217d77874cbef4f606）。](https://github.com/Mrs4s/MiraiGo/commit/3a3355e00ad70242e5583d217d77874cbef4f606%EF%BC%89%E3%80%82) 我自用的 oicq 里加上后解决了风控号的禁止登录的问题（同时账号的所有数据包都应该带签名，MessageSvc.PbSendMsg 也只有签名后才能正常发出消息） 目前都是调用 libfekit.so 生成的，希望后面会有算法
> 
> 是这样的,现在主要的几个情况. 1.新号返回`45` 2.部分封过几次的号返回`45` 3.版本确实低了 `235`
> 
> 1的解决办法就是您所说的加`sign`,确实可以解决. 2的情况分好几种细分的情况了就,目前我尝试了`sign+544+545`,一些极端风控号并没有解决问题,但是部分正常报45的是可以过的.

你好，我现在的情况就是1，请问这个加“sign”要怎么做呢，方便说一下吗

**Comment by heyi-byte** [comment]
请问这个情况怎么处理啊
![image](https://user-images.githubusercontent.com/52826441/235043041-d08955e5-70c2-48a7-bfcb-ceae996a3cf8.png)

**Comment by TeaBoss-Developer** [comment]
> > > > MacQQ曾经可以解决问题 但是现在强制推 `NTQQ` 了, 也会出现`235`强制升级新版本 可能部分风控高的号还是需要校验包头的`sign`, 也是一个 native 层的算法, 但是这个理论上会需要一些动态下发的参数, 所以暂时没研究. 总之这个问题主要还是账号风控等级太高, 实际上我测试很多这种账号拿官方客户端在新设备登录都会提示错误, 然后被引导到身份验证/人脸识别. 最好还是在官方客户端挂一段时间再说
> > > 
> > > 
> > > 包头 sign 需要 uin、androidId (或IMEI)、cmd、body 包全部数据、seq 和 qimei36，除了 qimei 似乎并没有动态下发，seq 似乎关联性不大 (错误貌似也能登录)。整个签名是个 protobuf，塞在 MiraiGo 写着 qimei 的地方（[Mrs4s/MiraiGo@3a3355e00ad70242e5583d217d77874cbef4f606）。](https://github.com/Mrs4s/MiraiGo/commit/3a3355e00ad70242e5583d217d77874cbef4f606%EF%BC%89%E3%80%82) 我自用的 oicq 里加上后解决了风控号的禁止登录的问题（同时账号的所有数据包都应该带签名，MessageSvc.PbSendMsg 也只有签名后才能正常发出消息） 目前都是调用 libfekit.so 生成的，希望后面会有算法
> > 
> > 
> > 是这样的,现在主要的几个情况. 1.新号返回`45` 2.部分封过几次的号返回`45` 3.版本确实低了 `235`
> > 1的解决办法就是您所说的加`sign`,确实可以解决. 2的情况分好几种细分的情况了就,目前我尝试了`sign+544+545`,一些极端风控号并没有解决问题,但是部分正常报45的是可以过的.
> 
> 你好，我现在的情况就是1，请问这个加“sign”要怎么做呢，方便说一下吗

这个只能在工程里动刀子的,作为用户一般是不咋可能改变包头有sign的.
建议还是尝试`MacQQ`登录,实在不行则只能  手表扫码上线了.

**Comment by TeaBoss-Developer** [comment]
> 请问这个情况怎么处理啊 ![image](https://user-images.githubusercontent.com/52826441/235043041-d08955e5-70c2-48a7-bfcb-ceae996a3cf8.png)

您这是自建的吧,检查一下是不是改了什么地方导致出了问题.

**Comment by heyi-byte** [comment]
> 

使用docker搭建的
这是我的配置文件
`
account: # 账号相关
  uin:  # QQ账号
  password: '' # 密码为空时使用扫码登录
  encrypt: false  # 是否开启密码加密
  status: 0      # 在线状态 请参考 https://docs.go-cqhttp.org/guide/config.html#在线状态
  relogin: # 重连设置
    delay: 3   # 首次重连延迟, 单位秒
    interval: 3   # 重连间隔
    max-times: 0  # 最大重连次数, 0为无限制
  use-sso-address: true
  allow-temp-session: false
heartbeat:
  interval: 5
message:
  post-format: string
  ignore-invalid-cqcode: false

  force-fragment: false
  fix-url: false
  proxy-rewrite: ''
  report-self-message: false
  remove-reply-at: false
  extra-reply-data: false
  skip-mime-scan: false

output:
  log-level: warn
  log-aging: 15
  log-force-new: true
  log-colorful: true
  debug: true # 开启调试模式
default-middlewares: &default
  access-token: ''
  filter: ''
  rate-limit:
    enabled: false # 是否启用限速
    frequency: 1  # 令牌回复频率, 单位秒
    bucket: 1     # 令牌桶大小

database: # 数据库相关设置
  leveldb:
    enable: true
  cache:
    image: data/image.db
    video: data/video.db


`

` {
    "protocol": 3,
    "display": "xxx",
    "product": "xxx",
    "device": "xxx",
    "board": "xxx",
    "model": "xxx",
    "finger_print": "xxx",
    "boot_id": "xxx",
    "proc_version": "xxx",
    "imei": "xxx",
    "brand": "xxx",
    "bootloader": "xxx",
    "base_band": "",
    "version": {
      "incremental": "xxx",
      "release": "xxx",
      "codename": "xxx",
      "sdk": 0
    },
    "sim_info": "xxx",
    "os_type": "xxx",
    "mac_address": "xxx",
    "ip_address": [
      
    ],
    "wifi_bssid": "xxx",
    "wifi_ssid": "xxx",
    "imsi_md5": "xxx",
    "android_id": "xxx",
    "apn": "xxx",
    "vendor_name": "xxx",
    "vendor_os_name": "xxx"
  } `

**Comment by TeaBoss-Developer** [comment]
> > 
> 
> 使用docker搭建的 这是我的配置文件 ` account: # 账号相关 uin: # QQ账号 password: '' # 密码为空时使用扫码登录 encrypt: false # 是否开启密码加密 status: 0 # 在线状态 请参考 [https://docs.go-cqhttp.org/guide/config.html#在线状态](https://docs.go-cqhttp.org/guide/config.html#%E5%9C%A8%E7%BA%BF%E7%8A%B6%E6%80%81) relogin: # 重连设置 delay: 3 # 首次重连延迟, 单位秒 interval: 3 # 重连间隔 max-times: 0 # 最大重连次数, 0为无限制 use-sso-address: true allow-temp-session: false heartbeat: interval: 5 message: post-format: string ignore-invalid-cqcode: false
> 
> force-fragment: false fix-url: false proxy-rewrite: '' report-self-message: false remove-reply-at: false extra-reply-data: false skip-mime-scan: false
> 
> output: log-level: warn log-aging: 15 log-force-new: true log-colorful: true debug: true # 开启调试模式 default-middlewares: &default access-token: '' filter: '' rate-limit: enabled: false # 是否启用限速 frequency: 1 # 令牌回复频率, 单位秒 bucket: 1 # 令牌桶大小
> 
> database: # 数据库相关设置 leveldb: enable: true cache: image: data/image.db video: data/video.db
> 
> `
> 
> ` { "protocol": 3, "display": "xxx", "product": "xxx", "device": "xxx", "board": "xxx", "model": "xxx", "finger_print": "xxx", "boot_id": "xxx", "proc_version": "xxx", "imei": "xxx", "brand": "xxx", "bootloader": "xxx", "base_band": "", "version": { "incremental": "xxx", "release": "xxx", "codename": "xxx", "sdk": 0 }, "sim_info": "xxx", "os_type": "xxx", "mac_address": "xxx", "ip_address": [
> 
> ```
> ],
> "wifi_bssid": "xxx",
> "wifi_ssid": "xxx",
> "imsi_md5": "xxx",
> "android_id": "xxx",
> "apn": "xxx",
> "vendor_name": "xxx",
> "vendor_os_name": "xxx"
> ```
> 
> } `

疑似是选中的tx服务器ip有问题,多试几次.docker版本我并没有研究多少......先尝试一下吧.

**Comment by TeaBoss-Developer** [comment]
> > 
> 
> 使用docker搭建的 这是我的配置文件 ` account: # 账号相关 uin: # QQ账号 password: '' # 密码为空时使用扫码登录 encrypt: false # 是否开启密码加密 status: 0 # 在线状态 请参考 [https://docs.go-cqhttp.org/guide/config.html#在线状态](https://docs.go-cqhttp.org/guide/config.html#%E5%9C%A8%E7%BA%BF%E7%8A%B6%E6%80%81) relogin: # 重连设置 delay: 3 # 首次重连延迟, 单位秒 interval: 3 # 重连间隔 max-times: 0 # 最大重连次数, 0为无限制 use-sso-address: true allow-temp-session: false heartbeat: interval: 5 message: post-format: string ignore-invalid-cqcode: false
> 
> force-fragment: false fix-url: false proxy-rewrite: '' report-self-message: false remove-reply-at: false extra-reply-data: false skip-mime-scan: false
> 
> output: log-level: warn log-aging: 15 log-force-new: true log-colorful: true debug: true # 开启调试模式 default-middlewares: &default access-token: '' filter: '' rate-limit: enabled: false # 是否启用限速 frequency: 1 # 令牌回复频率, 单位秒 bucket: 1 # 令牌桶大小
> 
> database: # 数据库相关设置 leveldb: enable: true cache: image: data/image.db video: data/video.db
> 
> `
> 
> ` { "protocol": 3, "display": "xxx", "product": "xxx", "device": "xxx", "board": "xxx", "model": "xxx", "finger_print": "xxx", "boot_id": "xxx", "proc_version": "xxx", "imei": "xxx", "brand": "xxx", "bootloader": "xxx", "base_band": "", "version": { "incremental": "xxx", "release": "xxx", "codename": "xxx", "sdk": 0 }, "sim_info": "xxx", "os_type": "xxx", "mac_address": "xxx", "ip_address": [
> 
> ```
> ],
> "wifi_bssid": "xxx",
> "wifi_ssid": "xxx",
> "imsi_md5": "xxx",
> "android_id": "xxx",
> "apn": "xxx",
> "vendor_name": "xxx",
> "vendor_os_name": "xxx"
> ```
> 
> } `

建议参考一下以下链接
`https://docs.go-cqhttp.org/guide/config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%9C%8D%E5%8A%A1%E5%99%A8ip`

**Comment by heyi-byte** [comment]
> 疑似是选中的tx服务器ip有问题,多试几次.docker版本我并没有研究多少......先尝试一下吧.

现在什么设备支持扫码登录啊？

**Comment by TeaBoss-Developer** [comment]
> > 疑似是选中的tx服务器ip有问题,多试几次.docker版本我并没有研究多少......先尝试一下吧.
> 
> 现在什么设备支持扫码登录啊？

2:Android Watch

具体参照这个
[v1.0.0-rc5]
Changelog
本次版本修复了包括 账号密码错误 等许多问题, 强烈建议升级.
在最近的更新中，QQ修复了扫码登录手机等协议的漏洞，今后只有Android Watch协议支持扫码登录。
从这个版本开始, 默认情况下需要访问 captcha.go-cqhttp.org 域名来获取签名, 请确保该域名未被DNS污染.
本次更新后请务必删除 session.token 和 device.json 文件重新创建.

**Comment by lin9081** [comment]
> > > 疑似是选中的tx服务器ip有问题,多试几次.docker版本我并没有研究多少......先尝试一下吧.
> > 
> > 
> > 现在什么设备支持扫码登录啊？
> 
> 2:Android Watch
> 
> 具体参照这个 [v1.0.0-rc5] Changelog 本次版本修复了包括 账号密码错误 等许多问题, 强烈建议升级. 在最近的更新中，QQ修复了扫码登录手机等协议的漏洞，今后只有Android Watch协议支持扫码登录。 从这个版本开始, 默认情况下需要访问 captcha.go-cqhttp.org 域名来获取签名, 请确保该域名未被DNS污染. 本次更新后请务必删除 session.token 和 device.json 文件重新创建.

非常感谢，总算是成功登陆了

**Comment by hhhuskytc** [comment]
我被风险了三个账号，大概是在下线时没有退干净程序，报错如下：
[2023-05-04 12:43:48] [WARNING]: 登录失败: 你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。 Code: 45
[2023-05-04 12:43:48] [WARNING]: 你的账号涉嫌违规被限制在非常用设备登录, 请在手机QQ登录并根据提示完成认证
[2023-05-04 12:43:48] [WARNING]: 或使用 -update-protocol 升级到最新协议后重试
我有五个账号，正常的账号可以在版本比较低的QQ上登陆，只有风险的这三个账号只能在最新版的QQ登陆。
protocol切换后也是均不能正常登陆，报错同上
是不是代表这三个号已经不能再使用gp-cqhttp进行登陆了？
我还可以通过什么方式达到登陆的目的？还是这个问题暂时只能等待开发者进行修复。

**Comment by TeaBoss-Developer** [comment]
> 

据您所描述的内容,疑似只能使用手表协议进行扫码登录.具体步骤为`config.yml`里面密码留空,`device.json`里面`protocol`切换为`2`.然后开启`gocqhttp`命令行程序,进行扫码登录（注,需要同网络,可以在自己电脑上扫码登陆了再上传至服务器等.)

**Comment by q123458384** [comment]
> > 
> 
> 据您所描述的内容,疑似只能使用手表协议进行扫码登录.具体步骤为`config.yml`里面密码留空,`device.json`里面`protocol`切换为`2`.然后开启`gocqhttp`命令行程序,进行扫码登录（注,需要同网络,可以在自己电脑上扫码登陆了再上传至服务器等.)

谢谢分享，暂时解决了

**Comment by JoffreyN** [comment]
已经是最新版了

**Comment by dfmjndm** [comment]
先订阅了，遇到了同样的问题，不是新号，挂了很长时间的号

**Comment by ilasx** [comment]
同样的问题

**Comment by Mrs4s** [comment]
#2183

**Comment by hhhope** [comment]
> 

自己电脑扫成功之后再把device和sesssion上传？问题是我没找到session.token我docker部署的

**Comment by zhx79513** [comment]
> 

在自己电脑上下载go-cqhttp，登陆验证成功后，再把device.json和session.token上传到docker里进行覆盖。
