### ISSUE TITLE
单向好友无法收到消息

### ISSUE THREAD

**Issue by dailinfeng66** [Mrs4s/go-cqhttp#206]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.22
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
单向好友无法收到消息,简单来说就是收不到单项好友的消息

**复现方法**
设置QQ机器人加好友的方式为,允许任何人, 具体设置方式是:手机QQ  设置->隐私->加我为好友的方式->允许任何人
设置成这个之后,有人加这个机器人会自动成为单向好友,(注:这个单向好友必须满足的条件是:这个ＱＱ和机器人此前并不是好友)当用户发消息给机器人机器人收不到,

**Comment by Mrs4s** [comment]
#98
