### ISSUE TITLE
[Bug]: 在A群能收到消息B群不行

### ISSUE THREAD

**Issue by Arturia169** [Mrs4s/go-cqhttp#2060]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0.0

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

2 | Android Watch

### 重现步骤

在A群发送消息“1”后端无记录，且指令无法响应
在B群发送消息"1"后端有记录，指令可以响应

### 期望的结果是什么？

能得到解决

### 实际的结果是什么？

不能得到解决

### 补充说明（可选）

==================
![image](https://user-images.githubusercontent.com/69199123/230379444-061ff4c6-e5f4-467f-bcf5-9b4c770e5f6c.png)
A群能收到
==================
B群收不到
![image](https://user-images.githubusercontent.com/69199123/230379582-4cb69023-63bc-4a6e-95e6-c28d2e7b2932.png)
==================

**Comment by Mrs4s** [comment]
手表协议需要将群设置为提醒才行
手表协议为了省电会忽略一些不重要的群
