### ISSUE TITLE
[Bug]: 建议升级最新版本后重试

### ISSUE THREAD

**Issue by sunwaylive** [Mrs4s/go-cqhttp#2065]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (正向)

### 使用协议

1 | Android Phone

### 重现步骤

1.下载了最新版本的 (https://github.com/Mrs4s/go-cqhttp/releases)
2.运行: go-cqhttp_windows_amd64.exe -update-protocol
协议是 Android Pad, 报错如图所示:
![image](https://user-images.githubusercontent.com/3489246/230538776-8a627b16-a48b-4009-9aca-829f39f8cfbd.png)

问题:
1. 已经是最新了, 请问应该去哪里下载更新的版本呢?

### 期望的结果是什么？

正常启动

### 实际的结果是什么？

启动失败, 让升级重试

**Comment by Mrs4s** [comment]
#2056
