### ISSUE TITLE
[Bug]: 登录验证后报错 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Mushan3420** [Mrs4s/go-cqhttp#2080]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0

### 运行环境

Ubuntu

### 运行架构

AMD64

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

配置完成后首次登录：
[2023-04-10 18:09:24] [INFO]: 当前版本:v1.0.0 
[2023-04-10 18:09:24] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2023-04-10 18:09:24] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2023-04-10 18:09:29] [INFO]: 开始尝试登录并同步消息... 
[2023-04-10 18:09:29] [INFO]: 使用协议: Android Pad 8.9.35.10440 
[2023-04-10 18:09:29] [INFO]: 正在检查协议更新... 
[2023-04-10 18:09:29] [INFO]: 检测到协议更新: 8.9.35.10440 -> 8.9.38.10545 
[2023-04-10 18:09:29] [INFO]: 如果登录时出现版本过低错误, 可尝试使用 -update-protocol 参数启动 
[2023-04-10 18:09:29] [INFO]: Protocol -> connect to server: 43.135.106.161:8080 
[2023-04-10 18:09:30] [WARNING]: 登录需要滑条验证码, 请验证后重试. 
[2023-04-10 18:09:30] [WARNING]: 请选择提交滑块ticket方式: 
[2023-04-10 18:09:30] [WARNING]: 1. 自动提交 
[2023-04-10 18:09:30] [WARNING]: 2. 手动抓取提交 
[2023-04-10 18:09:30] [WARNING]: 请输入(1 - 2)： 
1
[2023-04-10 18:09:39] [WARNING]: 请前往该地址验证 -> https://captcha.go-cqhttp.org/captcha?id=8K8Hh63p&style=simple&aid=16&uin=2296153186&sid=5370983126475726937&cap_cd=zI0zW6dug2M4dl7rVvHJ6ZXEtYFCq-6-QLenAAxEym1AlQZPoZBsTQ**&clientype=1&apptype=2  
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47109c]

goroutine 1 [running]:
sync.poolCleanup()
        sync/pool.go:245 +0x3c
io.copyBuffer({0xbfa160, 0xc00005c3a0}, {0x7f4808867318, 0xc00005c280}, {0x0, 0x0, 0x0})
        io/io.go:424 +0x117
io.Copy(...)
        io/io.go:386
github.com/Mrs4s/go-cqhttp/internal/download.Request.JSON({{0x0, 0x0}, {0xc00002c4c0, 0x38}, 0x0, 0x0, {0x0, 0x0}})
        github.com/Mrs4s/go-cqhttp/internal/download/download.go:108 +0x17e
github.com/Mrs4s/go-cqhttp/cmd/gocq.fetchCaptcha({0xc00028c700?, 0x3?})
        github.com/Mrs4s/go-cqhttp/cmd/gocq/login.go:260 +0xe5
github.com/Mrs4s/go-cqhttp/cmd/gocq.getTicket({0xc0001cc000, 0xce})
        github.com/Mrs4s/go-cqhttp/cmd/gocq/login.go:249 +0x2b2
github.com/Mrs4s/go-cqhttp/cmd/gocq.loginResponseProcessor(0xc000184000?)
        github.com/Mrs4s/go-cqhttp/cmd/gocq/login.go:169 +0x5e5
github.com/Mrs4s/go-cqhttp/cmd/gocq.commonLogin()
        github.com/Mrs4s/go-cqhttp/cmd/gocq/login.go:77 +0x3f
github.com/Mrs4s/go-cqhttp/cmd/gocq.LoginInteract()
        github.com/Mrs4s/go-cqhttp/cmd/gocq/main.go:310 +0x175c
main.main()
        github.com/Mrs4s/go-cqhttp/main.go:20 +0x2a

### 期望的结果是什么？

期望登录成功

### 实际的结果是什么？

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47109c]

### 简单的复现代码/链接（可选）

```golang
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47109c]

goroutine 1 [running]:
sync.poolCleanup()
        sync/pool.go:245 +0x3c
io.copyBuffer({0xbfa160, 0xc00005c3a0}, {0x7f4808867318, 0xc00005c280}, {0x0, 0x0, 0x0})
        io/io.go:424 +0x117
io.Copy(...)
        io/io.go:386
github.com/Mrs4s/go-cqhttp/internal/download.Request.JSON({{0x0, 0x0}, {0xc00002c4c0, 0x38}, 0x0, 0x0, {0x0, 0x0}})
        github.com/Mrs4s/go-cqhttp/internal/download/download.go:108 +0x17e
github.com/Mrs4s/go-cqhttp/cmd/gocq.fetchCaptcha({0xc00028c700?, 0x3?})
        github.com/Mrs4s/go-cqhttp/cmd/gocq/login.go:260 +0xe5
github.com/Mrs4s/go-cqhttp/cmd/gocq.getTicket({0xc0001cc000, 0xce})
        github.com/Mrs4s/go-cqhttp/cmd/gocq/login.go:249 +0x2b2
github.com/Mrs4s/go-cqhttp/cmd/gocq.loginResponseProcessor(0xc000184000?)
        github.com/Mrs4s/go-cqhttp/cmd/gocq/login.go:169 +0x5e5
github.com/Mrs4s/go-cqhttp/cmd/gocq.commonLogin()
        github.com/Mrs4s/go-cqhttp/cmd/gocq/login.go:77 +0x3f
github.com/Mrs4s/go-cqhttp/cmd/gocq.LoginInteract()
        github.com/Mrs4s/go-cqhttp/cmd/gocq/main.go:310 +0x175c
main.main()
        github.com/Mrs4s/go-cqhttp/main.go:20 +0x2a
```

### 补充说明（可选）

系统是 Ubuntu 22.04
安装方式是 apt install /tmp/go-cqhttp_1.0.0_linux_amd64.deb
协议应该是6，这里是自动生成的。

**Comment by Mushan3420** [comment]
和 https://github.com/Mrs4s/go-cqhttp/issues/2045 重复了

**Comment by AlexZhou1995** [comment]
同，也遇到这个错误

**Comment by oryx123** [comment]
我是同样的问题，问题出在我装了clash在同目录下，他们的config文件重叠了，我新建了文件夹，重新生成config就又有用了。

**Comment by Mushan3420** [comment]
> 我是同样的问题，问题出在我装了clash在同目录下，他们的config文件重叠了，我新建了文件夹，重新生成config就又有用了。

我没装clash，验证提交后就报错。

**Comment by yangrq1018** [comment]
+1 出现一样的问题

**Comment by oryx123** [comment]
你把config.yml删了，重新启动试试看

**Comment by Mushan3420** [comment]
> 你把config.yml删了，重新启动试试看

感谢回复，已经尝试多次，均可复现。

**Comment by remloyal** [comment]
解决了没，出现同样问题

**Comment by Mushan3420** [comment]
> 解决了没，出现同样问题

没解决，等下次开发者打包了二进制版本，我再试试看。

**Comment by Mrs4s** [comment]
请尝试最新版本

**Comment by ZYY-Yu** [comment]
> 请尝试最新版本

最新版本同复现，liunx系统

**Comment by ZYY-Yu** [comment]
> 请尝试最新版本

使用kill杀掉进程在启动修复。
