### ISSUE TITLE
[Bug]: qq版本过低，请升级更高版本，删除device.json文件

### ISSUE THREAD

**Issue by lingdub** [Mrs4s/go-cqhttp#2089]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.1

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

就是普通的powershell nb run --reload

### 期望的结果是什么？

登陆成功

### 实际的结果是什么？

登录失败，qq版本过低，请升级

**Comment by lingdub** [comment]
大佬们救救我

**Comment by maborosh** [comment]
同样的问题，现在只能用手表协议扫码登录

**Comment by clacknya** [comment]
把 device.json 文件删了看看

**Comment by lingdub** [comment]
删了在运行还会在生成

**Comment by lingdub** [comment]
我用的是apod登录

**Comment by icerxkx** [comment]
同样问题，ipad协议

**Comment by yanyongyu** [comment]
试试apad 6协议

**Comment by Ahanlei123** [comment]
离谱

**Comment by a1046700338** [comment]
你好，你可以看一下这篇[issues](https://github.com/Mrs4s/go-cqhttp/issues/2084#issuecomment-1506304274)
1.`device.json`文件中在"protocol":3,配置项，对应[设备信息](https://docs.go-cqhttp.org/guide/config.html#%E8%AE%BE%E5%A4%87%E4%BF%A1%E6%81%AF)
2.协议为3，即macos设备，可以选择扫码验证或短信验证，需要在`config.yml`文件中设置好密码。
就可以解决这个问题。

**Comment by lingdub** [comment]
改完以后依旧会报错

**Comment by lingdub** [comment]
还是设备被封禁，qq版本过低

**Comment by lingdub** [comment]
重新注册了个qq号改成了2就好了，谢谢大家的帮忙

**Comment by icerxkx** [comment]
看到最新merge的版本说错误235是设备被封禁，于是重新生成device.json，发现mac地址等信息没变，手动改了一下，输入设备锁短信密码后，ipad协议可以登录了。
建议重新生成device.json的时候自动换一个macos，wifi 地址之类的信息

**Comment by m30102** [comment]
> ifi 地址之类的信息

步骤能具体一点吗？我试了还是不行

**Comment by m30102** [comment]
> 看到最新merge的版本说错误235是设备被封禁，于是重新生成device.json，发现mac地址等信息没变，手动改了一下，输入设备锁短信密码后，ipad协议可以登录了。 建议重新生成device.json的时候自动换一个macos，wifi 地址之类的信息

步骤能具体一点吗？我试了还是不行

**Comment by icerxkx** [comment]
> > 看到最新merge的版本说错误235是设备被封禁，于是重新生成device.json，发现mac地址等信息没变，手动改了一下，输入设备锁短信密码后，ipad协议可以登录了。 建议重新生成device.json的时候自动换一个macos，wifi 地址之类的信息
> 
> 步骤能具体一点吗？我试了还是不行

重新生成device.json后，随便改一下里面的mac地址和wifi ssd，再登录，qq会认为设备变了，让扫码或者输入短信码解开设备锁，然后就好了

**Comment by lanlandexiaolan** [comment]
我的问题是，gocq能登录，但是手机上提示我qq版本过低，手机上无法登录了

**Comment by TeaBoss-Developer** [comment]
`Code:45`
先试 `MacQQ`能不能登录.
再试改device.json是否能登录.
最后如果都未解决,则只能手表扫码上线了.

**Comment by JoffreyN** [comment]
插眼

**Comment by Mrs4s** [comment]
#2056

**Comment by molanp** [comment]
最近好像是检测mirai，把device.json里的mirai改成品牌名（如vivo），大写的也要大写好像可以解决
反正目前我是荷这样解决的
