### ISSUE TITLE
二进制包解压后无法查看版本

### ISSUE THREAD

**Issue by crazywhalecc** [Mrs4s/go-cqhttp#209]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.22
运行环境: ubuntu-18.04.2LTS
连接方式: 反向WS

**bug内容**
没有命令行参数--version，--help之类的，而且启动后也没有写版本，服务器上部署时容易搞混版本，造成不便，希望可以加上一些看当前版本名称的地方。

**Comment by Mrs4s** [comment]
下个版本就会加入版本信息了
