### ISSUE TITLE
[Bug]: 发短视频,CQ码不解析

### ISSUE THREAD

**Issue by coolxitech** [Mrs4s/go-cqhttp#2094]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.01

### 运行环境

CentOS

### 运行架构

AMD64

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

[CQ:video,file=https://cn-hk-eq-bcache-02.bilivideo.com/upgcxcode/29/85/559318529/559318529-1-208.mp4?e=ig8euxZM2rNcNbN3nwdVhwdlhb43hwdVhoNvNC8BqJIzNbfq9rVEuxTEnE8L5F6VnEsSTx0vkX8fqJeYTj_lta53NCM=&amp;uipk=5&amp;nbs=1&amp;deadline=1681684439&amp;gen=playurlv2&amp;os=bcache&amp;oi=2996648795&amp;trid=00003bb81406686e4cc9b1cc2ee53b10b7deT&amp;mid=3493116378089995&amp;platform=html5&amp;upsig=61393dff7bf1955207e8aef871a8ba1d&amp;uparams=e&#44;uipk&#44;nbs&#44;deadline&#44;gen&#44;os&#44;oi&#44;trid&#44;mid&#44;platform&amp;cdnid=9596&amp;bvc=vod&amp;nettype=0&amp;bw=288607&amp;orderid=0&#44;1&amp;buvid=&amp;build=0&amp;mobi_app=&amp;logo=80000000,cover=https://i2.hdslb.com/bfs/archive/2380548a5114d25ba867523feecd03e4c120a54e.jpg]
这段CQ码已经完成转义,使用api调试工具通过http方式可发送成功,换到websocket死活不解析，尝试用代码发起http请求提交依然还是不解析.
搞到大半夜,整不会了.

### 期望的结果是什么？

视频发送成功

### 实际的结果是什么？

![图片](https://user-images.githubusercontent.com/20185794/232334707-f4a8e428-e8fa-4402-b696-f1bc306ad060.png)

**Comment by coolxitech** [comment]
尝试换数据结构无作用

**Comment by coolxitech** [comment]
到MiraiGo Element时出现错误: context deadline exceeded (Client.Timeout or context cancellation while reading body)

**Comment by coolxitech** [comment]
转换到本地路径就没问题了，就是偶尔会输出invalid video size.

**Comment by gcorpse** [comment]
出现invalid video size.是不是你的视频没有转码正确的问题？反正我就没发现过这种问题

**Comment by Mrs4s** [comment]
请将`http-timeout`值调高

**Comment by coolxitech** [comment]
> 请将`http-timeout`值调高

文档好像没写这个配置啊

**Comment by kirbystudy** [comment]
请问一下gocq对短视频大小有限制吗，视频大小是100MB以上就显示不出来了，直接是返回的是[CQ:video,file=file:///C:\QQ\qqbot\plugin\douyin\video\62c693a4e44d48b8aa72ecb7ffad62cf/62c693a4e44d48b8aa72ecb7ffad62cf.mp4]

**Comment by coolxitech** [comment]
> 请问一下gocq对短视频大小有限制吗，视频大小是100MB以上就显示不出来了，直接是返回的是[CQ:video,file=file:///C:\QQ\qqbot\plugin\douyin\video\62c693a4e44d48b8aa72ecb7ffad62cf/62c693a4e44d48b8aa72ecb7ffad62cf.mp4]

你猜它为什么叫短视频。

**Comment by kirbystudy** [comment]
> > 请问一下gocq对短视频大小有限制吗，视频大小是100MB以上就显示不出来了，直接是返回的是[CQ:video,file=file:///C:\QQ\qqbot\plugin\douyin\video\62c693a4e44d48b8aa72ecb7ffad62cf/62c693a4e44d48b8aa72ecb7ffad62cf.mp4]
> 
> 你猜它为什么叫短视频。

文件限制多少大小？

**Comment by kirbystudy** [comment]
文档上都没说明
