### ISSUE TITLE
能否支持获取群友签名？

### ISSUE THREAD

**Issue by GenesisAN** [Mrs4s/go-cqhttp#2096]
**环境信息**
架构:AMD64
OS:linux
go-cqhttp版本: v1.0.1

获取群友QQ签名
在获取个人信息的时候也能返回签名信息

**Comment by GenesisAN** [comment]
谢谢，了解了，不过！
帮助中心里[#获取陌生人信息](https://docs.go-cqhttp.org/api/#%E8%8E%B7%E5%8F%96%E9%99%8C%E7%94%9F%E4%BA%BA%E4%BF%A1%E6%81%AF)这个页面好像没更新对应的字段！

**Comment by ilihu** [comment]
> 谢谢，了解了，不过！ 帮助中心里[#获取陌生人信息](https://docs.go-cqhttp.org/api/#%E8%8E%B7%E5%8F%96%E9%99%8C%E7%94%9F%E4%BA%BA%E4%BF%A1%E6%81%AF)这个页面好像没更新对应的字段！

文档不及时的，以dev分支代码为准
