### ISSUE TITLE
[Bug]: 账号没有被冻结，但在扫码登录时提示账号密码错误或账号被冻结

### ISSUE THREAD

**Issue by SPLUS-VABLE** [Mrs4s/go-cqhttp#2099]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

WebSocket (反向)

### 使用协议

3 | MacOS

### 重现步骤

双击go-cqhttp.bat并进行扫码

### 期望的结果是什么？

登录成功

### 实际的结果是什么？

提示密码错误或账号被冻结

### 补充说明（可选）

![image](https://user-images.githubusercontent.com/42440354/232736701-c8f04ec8-544a-42d2-ae9d-1d18a7f76333.png)

**Comment by SPLUS-VABLE** [comment]
![image](https://user-images.githubusercontent.com/42440354/232737097-b4e9aa89-8f61-44b8-915f-c3944bb35385.png)

**Comment by Mrs4s** [comment]
更新 请不要做火星人

**Comment by Lost-little-dinosaur** [comment]
> 切换一下协议，在device.json里面，protocol字段

谢谢，终于成功啦
