### ISSUE TITLE
发送群消息经常发送失败，原因是很容被风控

### ISSUE THREAD

**Issue by yuanbin1998** [Mrs4s/go-cqhttp#211]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.10
运行环境: windows_amd64
连接方式: POST

**bug内容**
发送群消息有时候发送失败，疑似风控，我换账号也一样很快被风控。
[2020-08-28 12:56:50] [WARNING]: 上报Event数据到 www.test.work:1120/qqbot/coolq 失败: Post "http://www.test.work:1120/qqbot/coolq": context deadline exceeded 
[2020-08-28 12:56:50] [WARNING]: 群消息发送失败: 账号可能被风控. 

**复现方法**
我是假如发现有人发广告，会撤回广告、禁言、并艾特群主通知，现在艾特群主得消息好像发不出来了，去掉艾特也不行，但是之前成功过。

**Comment by shitianshiwa** [comment]
注意最新版本是v0.9.23，检查下版本号

**Comment by zxc7895531** [comment]
建议修改生存的device.json，否则风控几率较大

**Comment by zwa73** [comment]
俺也一样，直接群的event都接不到了

**Comment by zxc7895531** [comment]
请打开DEBUG模式并上传详细日志内容

**Comment by moshan1997** [comment]
我也一样，每次开了半小时左右之后就显示被风控，但是重启程序之后又没事了。

**Comment by d7185540** [comment]
是不是heartbeat_interval心跳没设置

**Comment by Mrs4s** [comment]
建议挂一周再看情况

**Comment by dzcpy** [comment]
解决了吗？

**Comment by chawaa** [comment]
![image](https://user-images.githubusercontent.com/59247295/113330345-31149a80-9351-11eb-969c-5e26819e3c17.png)
 一样的问题。讨论着就没了....怎么解决的？

**Comment by Ink-33** [comment]
> ![image](https://user-images.githubusercontent.com/59247295/113330556-733ddc00-9351-11eb-99e1-226a269e720c.png)
> 
> 一样的问题。讨论着就没了....怎么解决的？

你这号是真的被风控了...我估计你用官方客户端也不一定能发，毕竟风控这个东西太随缘了

**Comment by chawaa** [comment]
一半命令是生效的，另一半失效。按道理来说，真的风控，我全部都用不了。

**Comment by Ink-33** [comment]
> 一半命令是生效的，另一半失效。按道理来说，真的风控，我全部都用不了。

风控也是分种类的，有xml消息被风控，有json消息被风控，也有发消息全部被风控。
官方客户端正常那可以尝试更换device文件。
再次声明，风控是随机事件，有人挂三五个月都不会被风控，有人天天被风控。是否风控由tx根据网络环境，设备，发送的消息来判断。

**Comment by huangdongqin** [comment]
> 建议修改生存的device.json，否则风控几率较大

我改了一下device.json 把mirai的字样全部去掉重启可以了，不知道能坚持多久

**Comment by ZeroneBo** [comment]
device.json的protocol我从0（iPad）改成1（Android）就好了

**Comment by liyk123** [comment]
大概要综合所有的东西进行调整，设备信息，上报数据类型，是否强制分片，还有限速设置

**Comment by dzcpy** [comment]
哪位成功解决这个问题的，可以贴一个不容易被封的配置出来下吗？

**Comment by sam01101** [comment]
贴了没过多久就也风控了
改改配置，device.json就没事了

在 2021年8月9日週一 上午12:31，dzcpy ***@***.***> 寫道：
