### ISSUE TITLE
[Bug]: go-cqhttp cq码转换超时

### ISSUE THREAD

**Issue by leyasuzhou** [Mrs4s/go-cqhttp#2110]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

最新

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

 [WARNING]: 转换消息 [CQ:image,file=https://oaidalleapiprodscus.blob.core.windows.net/private/org-VrRIZoBThqityGbdBstBg4Um/user-drBGVq84uNM07vEj2EjsYgWj/img-e9q8xeVND5JBRJ0wLxsTFkps.png?st=2023-04-24T13%3A14%3A01Z&amp;se=2023-04-24T15%3A14%3A01Z&amp;sp=r&amp;sv=2021-08-06&amp;sr=b&amp;rscd=inline&amp;rsct=image/png&amp;skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&amp;sktid=a48cca56-e6da-484e-a814-9c849652bcb3&amp;skt=2023-04-24T14%3A08%3A41Z&amp;ske=2023-04-25T14%3A08%3A41Z&amp;sks=b&amp;skv=2021-08-06&amp;sig=KT/IN3YRUFpkm6QECzDPYU8e/YXSF8tF7YCSEWgFfWY%3D,type=show,id=40004] 到MiraiGo Element时出现错误: context deadline exceeded (Client.Timeout or context cancellation while reading body).

### 期望的结果是什么？

 [WARNING]: 转换消息 [CQ:image,file=https://oaidalleapiprodscus.blob.core.windows.net/private/org-VrRIZoBThqityGbdBstBg4Um/user-drBGVq84uNM07vEj2EjsYgWj/img-e9q8xeVND5JBRJ0wLxsTFkps.png?st=2023-04-24T13%3A14%3A01Z&amp;se=2023-04-24T15%3A14%3A01Z&amp;sp=r&amp;sv=2021-08-06&amp;sr=b&amp;rscd=inline&amp;rsct=image/png&amp;skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&amp;sktid=a48cca56-e6da-484e-a814-9c849652bcb3&amp;skt=2023-04-24T14%3A08%3A41Z&amp;ske=2023-04-25T14%3A08%3A41Z&amp;sks=b&amp;skv=2021-08-06&amp;sig=KT/IN3YRUFpkm6QECzDPYU8e/YXSF8tF7YCSEWgFfWY%3D,type=show,id=40004] 到MiraiGo Element时出现错误: context deadline exceeded (Client.Timeout or context cancellation while reading body).

### 实际的结果是什么？

 [WARNING]: 转换消息 [CQ:image,file=https://oaidalleapiprodscus.blob.core.windows.net/private/org-VrRIZoBThqityGbdBstBg4Um/user-drBGVq84uNM07vEj2EjsYgWj/img-e9q8xeVND5JBRJ0wLxsTFkps.png?st=2023-04-24T13%3A14%3A01Z&amp;se=2023-04-24T15%3A14%3A01Z&amp;sp=r&amp;sv=2021-08-06&amp;sr=b&amp;rscd=inline&amp;rsct=image/png&amp;skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&amp;sktid=a48cca56-e6da-484e-a814-9c849652bcb3&amp;skt=2023-04-24T14%3A08%3A41Z&amp;ske=2023-04-25T14%3A08%3A41Z&amp;sks=b&amp;skv=2021-08-06&amp;sig=KT/IN3YRUFpkm6QECzDPYU8e/YXSF8tF7YCSEWgFfWY%3D,type=show,id=40004] 到MiraiGo Element时出现错误: context deadline exceeded (Client.Timeout or context cancellation while reading body).

### 日志记录（可选）

```golang
[WARNING]: 转换消息 [CQ:image,file=https://oaidalleapiprodscus.blob.core.windows.net/private/org-VrRIZoBThqityGbdBstBg4Um/user-drBGVq84uNM07vEj2EjsYgWj/img-e9q8xeVND5JBRJ0wLxsTFkps.png?st=2023-04-24T13%3A14%3A01Z&amp;se=2023-04-24T15%3A14%3A01Z&amp;sp=r&amp;sv=2021-08-06&amp;sr=b&amp;rscd=inline&amp;rsct=image/png&amp;skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&amp;sktid=a48cca56-e6da-484e-a814-9c849652bcb3&amp;skt=2023-04-24T14%3A08%3A41Z&amp;ske=2023-04-25T14%3A08%3A41Z&amp;sks=b&amp;skv=2021-08-06&amp;sig=KT/IN3YRUFpkm6QECzDPYU8e/YXSF8tF7YCSEWgFfWY%3D,type=show,id=40004] 到MiraiGo Element时出现错误: context deadline exceeded (Client.Timeout or context cancellation while reading body).
```

**Comment by Lu7fer** [comment]
我也有类似的问题，但是并没有报错，只是发送的消息变成了cq码而不是图片，但是观察流量图片实际是上传了，缓存下也有URL对应的图片。但是实际上我使用的json消息而没有用cq码。
