### ISSUE TITLE
[Bug]: [2023年4月25日] 登录失败: 你当前使用的QQ版本过低 

### ISSUE THREAD

**Issue by GD-Slime** [Mrs4s/go-cqhttp#2111]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.1

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

选择ipad协议, 密码登录

### 期望的结果是什么？

正常登录并正常收发消息

### 实际的结果是什么？

登录失败: 你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。 Code: 45 

### 日志记录（可选）

```golang
[2023-04-25 06:39:34] [INFO]: 当前版本:v1.0.1 
[2023-04-25 06:39:34] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2023-04-25 06:39:34] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2023-04-25 06:39:39] [INFO]: 开始尝试登录并同步消息... 
[2023-04-25 06:39:39] [INFO]: 使用协议: iPad 8.9.33.614 
[2023-04-25 06:39:40] [INFO]: 正在检查协议更新... 
[2023-04-25 06:39:41] [INFO]: Protocol -> connect to server: *************
[2023-04-25 06:39:42] [WARNING]: 登录失败: 你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。 Code: 45 
[2023-04-25 06:39:42] [WARNING]: 你的账号涉嫌违规被限制在非常用设备登录, 请在手机QQ登录并根据提示完成认证 
[2023-04-25 06:39:42] [WARNING]: 或使用 -update-protocol 升级到最新协议后重试 
[2023-04-25 06:39:42] [INFO]: 按 Enter 继续....
```

### 补充说明（可选）

我今天登录自己的windowsQQ的时候, 也提示需要升级qq版本. 在重新安装最新版本winQQ后可以正常登录. 可能是腾讯定期的协议更新? 总之希望大佬尽快修复!

**Comment by Cloud-wish** [comment]
#2056

**Comment by GD-Slime** [comment]
> #2056
更改协议为macQQ确实可以登录, 但是我主要使用频道相关功能, 且macQQ似乎会顶掉winQQ的号? 所以不得不等大佬将ipad协议修好.

**Comment by GD-Slime** [comment]
> ### 请确保您已阅读以上注意事项，并勾选下方的确认框。
> * [x]  我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
> * [x]  我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
> * [x]  我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
> * [x]  我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）
> 
> ### go-cqhttp 版本
> 1.0.1
> 
> ### 运行环境
> Linux
> 
> ### 运行架构
> AMD64
> 
> ### 连接方式
> WebSocket (反向)
> 
> ### 使用协议
> 0 | iPad
> 
> ### 重现步骤
> 选择ipad协议, 密码登录
> 
> ### 期望的结果是什么？
> 正常登录并正常收发消息
> 
> ### 实际的结果是什么？
> 登录失败: 你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。 Code: 45
> 
> ### 简单的复现代码/链接（可选）
> _No response_
> 
> ### 日志记录（可选）
> ```go
> [2023-04-25 06:39:34] [INFO]: 当前版本:v1.0.1 
> [2023-04-25 06:39:34] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
> [2023-04-25 06:39:34] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
> [2023-04-25 06:39:39] [INFO]: 开始尝试登录并同步消息... 
> [2023-04-25 06:39:39] [INFO]: 使用协议: iPad 8.9.33.614 
> [2023-04-25 06:39:40] [INFO]: 正在检查协议更新... 
> [2023-04-25 06:39:41] [INFO]: Protocol -> connect to server: *************
> [2023-04-25 06:39:42] [WARNING]: 登录失败: 你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。 Code: 45 
> [2023-04-25 06:39:42] [WARNING]: 你的账号涉嫌违规被限制在非常用设备登录, 请在手机QQ登录并根据提示完成认证 
> [2023-04-25 06:39:42] [WARNING]: 或使用 -update-protocol 升级到最新协议后重试 
> [2023-04-25 06:39:42] [INFO]: 按 Enter 继续....
> ```
> 
> ### 补充说明（可选）
> 我今天登录自己的windowsQQ的时候, 也提示需要升级qq版本. 在重新安装最新版本winQQ后可以正常登录. 可能是腾讯定期的协议更新? 总之希望大佬尽快修复!

补充一下 现在我在本地环境尝试登录, 除了手表qq可以扫码登录外, 现在所有的密码登录都会提示涉嫌违规或者版本过低. 是账号被风控了吗? 可是我这是大号老号啊: (

**Comment by TeaBoss-Developer** [comment]
> > ### 请确保您已阅读以上注意事项，并勾选下方的确认框。
> > 
> > * [x]   我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
> > * [x]   我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
> > * [x]   我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
> > * [x]   我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）
> > 
> > ### go-cqhttp 版本
> > 1.0.1
> > ### 运行环境
> > Linux
> > ### 运行架构
> > AMD64
> > ### 连接方式
> > WebSocket (反向)
> > ### 使用协议
> > 0 | iPad
> > ### 重现步骤
> > 选择ipad协议, 密码登录
> > ### 期望的结果是什么？
> > 正常登录并正常收发消息
> > ### 实际的结果是什么？
> > 登录失败: 你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。 Code: 45
> > ### 简单的复现代码/链接（可选）
> > _No response_
> > ### 日志记录（可选）
> > ```go
> > [2023-04-25 06:39:34] [INFO]: 当前版本:v1.0.1 
> > [2023-04-25 06:39:34] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
> > [2023-04-25 06:39:34] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
> > [2023-04-25 06:39:39] [INFO]: 开始尝试登录并同步消息... 
> > [2023-04-25 06:39:39] [INFO]: 使用协议: iPad 8.9.33.614 
> > [2023-04-25 06:39:40] [INFO]: 正在检查协议更新... 
> > [2023-04-25 06:39:41] [INFO]: Protocol -> connect to server: *************
> > [2023-04-25 06:39:42] [WARNING]: 登录失败: 你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。 Code: 45 
> > [2023-04-25 06:39:42] [WARNING]: 你的账号涉嫌违规被限制在非常用设备登录, 请在手机QQ登录并根据提示完成认证 
> > [2023-04-25 06:39:42] [WARNING]: 或使用 -update-protocol 升级到最新协议后重试 
> > [2023-04-25 06:39:42] [INFO]: 按 Enter 继续....
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 补充说明（可选）
> > 我今天登录自己的windowsQQ的时候, 也提示需要升级qq版本. 在重新安装最新版本winQQ后可以正常登录. 可能是腾讯定期的协议更新? 总之希望大佬尽快修复!
> 
> 补充一下 现在我在本地环境尝试登录, 除了手表qq可以扫码登录外, 现在所有的密码登录都会提示涉嫌违规或者版本过低. 是账号被风控了吗? 可是我这是大号老号啊: (

您看一眼我主页的联系方式,我帮您定位一下原因试试吧.

**Comment by perkins4ai** [comment]
插眼

**Comment by JoffreyN** [comment]
插眼

**Comment by ShuFengYingt** [comment]
插眼

**Comment by Alvin-YS** [comment]
插眼+1

**Comment by Mrs4s** [comment]
#2056

**Comment by zhanghaoxing55** [comment]
我是protocol 3 也有这个问题 就2 可以

**Comment by VeQing** [comment]
2023-08-05 19:18:18 [W] gocqhttp 获取T544 sign时出现错误: data is empty
2023-08-05 19:18:18 [W] gocqhttp 登录需要滑条验证码, 请验证后重试.
2023-08-05 19:18:18 [W] gocqhttp 请选择提交滑块ticket方式: 
2023-08-05 19:18:18 [W] gocqhttp 1. 自动提交 
2023-08-05 19:18:18 [W] gocqhttp 2. 手动抓取提交 
2023-08-05 19:18:18 [W] gocqhttp 请输入(1 - 2)：
2023-08-05 19:18:18 [W] gocqhttp 请前往该地址验证 -> https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=2868481249&sid=6544489125147193338&cap_cd=NdNJtd8nUxlEWwK-SYUVj2WfE1sbaBXbtrBRf35LIjiZK--KAm_uag**&clientype=1&apptype=2 
2023-08-05 19:18:18 [W] gocqhttp 请输入ticket： (Enter 提交)
2023-08-05 19:18:21 [W] gocqhttp 获取T544 sign时出现错误: data is empty
2023-08-05 19:18:22 [W] gocqhttp 登录失败: 你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。 Code: 45 
2023-08-05 19:18:22 [W] gocqhttp 你的账号被限制登录, 请配置 SignServer 后重试

**Comment by VeQing** [comment]
已经用的是mac的协议了 但是还是登陆失败了
