### ISSUE TITLE
[Bug]: docker版账号无法登录，报告致命性错误

### ISSUE THREAD

**Issue by xgbc** [Mrs4s/go-cqhttp#2122]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

ghcr.io/mrs4s/go-cqhttp:master

### 运行环境

其它（请在下方说明）

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

2 | Android Watch

### 重现步骤

docker run -v /opt/docker/QQ/anke/config.yml:/data/config.yml -v /opt/docker/QQ/anke/device.json:/data/device.json -p 58001:5700 -d --name cqhttp_anke ghcr.io/mrs4s/go-cqhttp:master

### 期望的结果是什么？

登录 成功

### 实际的结果是什么？

软件报致命错误，并自动退出。

### 日志记录（可选）

```golang
stdout: ---Setup Timezone to Asia/Shanghai---
stdout: ---Checking if UID: 99 matches user---
stdout: ---Checking if GID: 100 matches user---
stdout: usermod: no changes
stdout: ---Setting umask to 002---
stdout: ---Taking ownership of data...---
stdout: Starting...
stdout: ]0;go-cqhttp (devel) © 2020 - 2023 Mrs4s[33m[2023-05-04 04:17:00] [WARNING]: 账号密码未配置, 将使用二维码登录. 
stdout: [0m[33m[2023-05-04 04:17:00] [WARNING]: 将在 5秒 后继续. 
stdout: [0m[37m[2023-05-04 04:17:05] [INFO]: 当前版本:(devel) 
stdout: [0m[37m[2023-05-04 04:17:05] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
stdout: [0m[37m[2023-05-04 04:17:05] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
stdout: [0m[37m[2023-05-04 04:17:10] [INFO]: 开始尝试登录并同步消息... 
stdout: [0m[37m[2023-05-04 04:17:10] [INFO]: 使用协议: Android Watch 2.0.8 
stdout: [0m[37m[2023-05-04 04:17:10] [INFO]: 正在检查协议更新... 
stdout: [0m[37m[2023-05-04 04:17:10] [INFO]: Protocol -> connect to server: 123.151.54.194:8080 
stdout: [0m[31m[2023-05-04 04:17:10] [ERROR]: Protocol -> connect server error: dial tcp error: dial tcp 123.151.54.194:8080: connect: connection refused 
stdout: [0m[1;31m[2023-05-04 04:17:10] [FATAL]: 登录时发生致命错误: dial tcp error: dial tcp 123.151.54.194:8080: connect: connection refused
```

### 补充说明（可选）

用我自己的windows电脑，安装最新的1.01版本测试没问题，但是使用软路由，操作系统LEDE OPENWRT x64版本，就不行了。原来软路由也是没问题的，我选的协议是2，日志里可以输出验证码，yml文件里除了http，其他地方都是默认配置，从昨天开始登录不上了，我删掉容器，重新登录，就提示connection refused，请麻烦帮忙看看，会是时间不对的问题吗

**Comment by wxz7801** [comment]
可能不会直接解决，只是有类似的经历：
某次gocqhttp镜像更新后，报类似错误。
检查之后重新生成了device.json session.token，把config.yml,device.json,session.token全部丢到docker路径后解决。
因为之前docker端没有session.token也能跑，所以当时就没有在意是否有session.token
不知道你是不是跟我类似的情况。

**Comment by xgbc** [comment]
我映射了device.json和congfig.yml,token没有映射，我在我的计算机上面装了docker测试，没有问题，之后我把我的软路由硬盘全部格式化了，重新安装，好了。。。。。
