### ISSUE TITLE
[Bug]: 按 Enter 继续.... 2023/5/11 16:40:45INFO当前版本:v1.0.1 2023/5/11 16:40:45INFO将使用 device.json 内的设备信息运行Bot. 2023/5/11 16:40:45INFO开始尝试登录并同步消息... 2023/5/11 16:40:45INFO使用协议: Android Watch 2.0.8 2023/5/11 16:40:46INFOProtocol -> connect to server: [::ffff:]: 2023/5/11 16:40:46WARNING登录失败: 请使用手Q扫描二维码或短信登录。 Code: 238

### ISSUE THREAD

**Issue by DPFd** [Mrs4s/go-cqhttp#2139]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.1

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

WebSocket (反向)

### 使用协议

2 | Android Watch

### 重现步骤

直接启动登录qq号

### 期望的结果是什么？

能登陆起qq机器人

### 实际的结果是什么？

登录不了

**Comment by DPFd** [comment]
按照正常情况启动后二维码没有弹窗

**Comment by add-chaos** [comment]
很巧，昨天能用的，今天炸了

**Comment by john35** [comment]
登录失败: 登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Code: 45 
[2023-05-15 21:09:12] [WARNING]: 你的账号涉嫌违规被限制在非常用设备登录, 请在手机QQ登录并根据提示完成认证
[2023-05-15 21:09:12] [WARNING]: 或使用 -update-protocol 升级到最新协议后重试

**Comment by 1823616178** [comment]
一样，code:238

**Comment by jyyhz** [comment]
> 登录失败: 登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Code: 45 [2023-05-15 21:09:12] [WARNING]: 你的账号涉嫌违规被限制在非常用设备登录, 请在手机QQ登录并根据提示完成认证 [2023-05-15 21:09:12] [WARNING]: 或使用 -update-protocol 升级到最新协议后重试

我也是这样的问题

**Comment by jyyhz** [comment]
> 按照正常情况启动后二维码没有弹窗

你把密码设置为空在运行一次gocqhttp

**Comment by DPFd** [comment]
> > 按照正常情况启动后二维码没有弹窗
> 
> 你把密码设置为空在运行一次gocqhttp

好的我解决了 是我没找到在哪里取消密码 谢谢

**Comment by pfvlz** [comment]
> > 按照正常情况启动后二维码没有弹窗
> 
> 你把密码设置为空运行一次gocqhttp

按照这样操作了。还是登陆不上。。

**Comment by jyyhz** [comment]
> > > 按照正常情况启动后二维码没有弹窗
> > 
> > 
> > 你把密码设置为空运行一次gocqhttp
> 
> 按照这样操作了。还是登陆不上。。 [2023-05-20 12:32:38] [WARNING]: 登录失败: 登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Code: 45 [2023-05-20 12:32:38] [WARNING]: 你的账号涉嫌违规被限制在非常用设备登录, 请在手机QQ登录并根据提示完成认证

你把device.json的protocol改成2了吗，如果改了的话正常来说应该不会出现这种情况的

**Comment by Mrs4s** [comment]
#2183
