### ISSUE TITLE
私聊使用报错显示

### ISSUE THREAD

**Issue by Kirietoan** [Mrs4s/go-cqhttp#214]
**环境信息**
go-cqhttp版本: v0.9.23
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
私聊发送消息后，程序监控显示error

**复现方法**
直接私聊 具体如图
私聊发送消息：![(K{_C73BSK VX`NQ16`8VKN](https://user-images.githubusercontent.com/42679669/91551501-d2231900-e95c-11ea-818b-f90d7522d707.png)
程序内监控回复：
![ZIKIA)PBKIICMH MHRBU 4O](https://user-images.githubusercontent.com/42679669/91551524-dfd89e80-e95c-11ea-9073-5bc4e835bf1f.png)

**Comment by Mrs4s** [comment]
请打开debug以提供更多信息

**Comment by Kirietoan** [comment]
发送一次消息后![PN(R_0}S1WG1%IY~7PH8Y}R](https://user-images.githubusercontent.com/42679669/91552154-eb789500-e95d-11ea-947b-47da8c792b9b.png)

**Comment by Kirietoan** [comment]
对了 群聊没有任何问题 正常的
