### ISSUE TITLE
增加新协议

### ISSUE THREAD

**Issue by Eric-Joker** [Mrs4s/go-cqhttp#2145]
**环境信息**

go-cqhttp版本: 1.0.1

**需要添加的功能内容**

node.js上有个icqq库，里头有一个协议是旧版安卓，貌似很稳定。

**Comment by MomentQYC** [comment]
确实，gocq新协议全挂了，icqq的旧版Android能上

**Comment by MomentQYC** [comment]
https://github.com/icqqjs/icqq/releases/tag/v0.3.0

**Comment by TeaBoss-Developer** [comment]
疑似8.8.88也不行了,我刚测的.那个更新好像是一个月前.

**Comment by ilihu** [comment]
mirai 那边协议修了 https://github.com/mamoe/mirai/commit/60d360baada2ba4ac37835fc2b5710ee8ddf84df

**Comment by SinKingCloud** [comment]
> mirai 那边协议修了 [mamoe/mirai@60d360b](https://github.com/mamoe/mirai/commit/60d360baada2ba4ac37835fc2b5710ee8ddf84df)

没有包头sign和t544 sign。白搭。过不去code 45

**Comment by echoidcf** [comment]
> > mirai 那边协议修了 [mamoe/mirai@60d360b](https://github.com/mamoe/mirai/commit/60d360baada2ba4ac37835fc2b5710ee8ddf84df)
> 
> 没有包头sign和t544 sign。白搭。过不去code 45

能详细讲讲具体卡在哪里了吗？大家一起想想办法。
我现在收集到的碎片信息是腾讯更新了某个复杂的加密算法（？），然后要求登录都要使用这个新算法。
但新算法暂时没有被逆向？

**Comment by Eric-Joker** [comment]
呃，go-cqhttp支持自定义协议 我自己写了个8.8.88的能正常用，我现在在外面一会发上来

**Comment by TeaBoss-Developer** [comment]
> 呃，go-cqhttp支持自定义协议 我自己写了个8.8.88的能正常用，我现在在外面一会发上来

8.8.88正常用吗

**Comment by dmlgzs** [comment]
> 8.8.88正常用吗

看账号的，有的正常，有的一样不行

**Comment by TeaBoss-Developer** [comment]
> > 8.8.88正常用吗
> 
> 看账号的，有的正常，有的一样不行

我看样子是sign风控号可以上了
但是其他风控号不知道为啥会报   您的QQ版本过低

**Comment by Eric-Joker** [comment]
我这正常，除了入群审核灵敏度有点低貌似没啥问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月1日(周四) 下午2:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Mrs4s/go-cqhttp] 增加新协议 (Issue #2145)




  
8.8.88正常用吗
  
看账号的，有的正常，有的一样不行

**Comment by 226612345** [comment]
> [1.txt](https://github.com/Mrs4s/go-cqhttp/files/11622145/1.txt) txt改成json，放到data/versionsri

这个真的可以，感谢。

**Comment by 0769559** [comment]
> [1.txt](https://github.com/Mrs4s/go-cqhttp/files/11622145/1.txt) txt改成json，放到data/versions里

亲测可用 感谢老哥。刚开始用不上还奇怪什么原因，结果是device.json里也得跟着配合改成1才能用上，请问这protocol是不是只能是1？

**Comment by Eric-Joker** [comment]
> > [1.txt](https://github.com/Mrs4s/go-cqhttp/files/11622145/1.txt) txt改成json，放到data/versions里
> 
> 亲测可用 感谢老哥。刚开始用不上还奇怪什么原因，结果是device.json里也得跟着配合改成1才能用上，请问这protocol是不是只能是1？

没研究过，文件名和文件里最后一个（应该是最后一个吧）的键值控制着。不知道换成别的协议能不能用

**Comment by 226612345** [comment]
> > > [1.txt](https://github.com/Mrs4s/go-cqhttp/files/11622145/1.txt) txt改成json，放到data/versionsri
> > 
> > 
> > 亲测可用 感谢老哥。刚开始用不上还奇怪什么原因，结果是device.json里也得跟着配合改成1才能用上，请问这protocol是不是只能是1？
> 
> 没研究过，文件名和文件里最后一个（应该是最后一个吧）的键值控制着。不知道换成别的协议能不能用

1是使用协议1，其他协议我试过了都会风控目前只有这个老版本安卓手机协议能稳定运行。

**Comment by AdolphQZ** [comment]
试了下，code:45 看来只有部分账号可以用

**Comment by Alcohol233** [comment]
> [1.txt](https://github.com/Mrs4s/go-cqhttp/files/11622145/1.txt) txt改成json，放到data/versions里
谨防code45，如果只是群聊消息被风控的话可以用这种方法解决，感谢老哥

**Comment by Eric-Joker** [comment]
> > [1.txt](https://github.com/Mrs4s/go-cqhttp/files/11622145/1.txt) txt改成json，放到data/versions里
> 
> 谨防code45，如果只是群聊消息被风控的话可以用这种方法解决，感谢老哥

我就是code45。。但是这个方式解决了

**Comment by 226612345** [comment]
今天这个老协议不让用了

**Comment by landall** [comment]
> Eric

除了正面解决算法，基本上其他的都会很快被消灭的。一个版本的登录数大量增加，在服务器端很容易看到。
