### ISSUE TITLE
[启动参数]：能否提供端口号配置？

### ISSUE THREAD

**Issue by 1226085293** [Mrs4s/go-cqhttp#2148]
**环境信息**

go-cqhttp版本: 1.0.1

**需要添加的功能内容**

能否添加启动参数的端口号配置，因为有时候端口总是被占用，想通过启动参数完成，而不是读写配置文件，这样项目每次 git 提交都会多一个不必要的文件

**Comment by jkjoy** [comment]
你该不会不看配置文件的吧

**Comment by 1226085293** [comment]
> 你该不会不看配置文件的吧

你不会不认识中文吧？

**Comment by SlimeNull** [comment]
但是配置文件中可能有多个协议, 如果通过启动参数来传递, 就不知道覆盖哪个协议的端口了 (?

**Comment by 1226085293** [comment]
> 但是配置文件中可能有多个协议, 如果通过启动参数来传递, 就不知道覆盖哪个协议的端口了 (?

-a 1 -b 2 -c 3
这是最常见的启动参数配置

**Comment by SlimeNull** [comment]
我的意思是说, 你的配置文件, 可能会有多个协议, 例如你同时使用了一个 HTTP 和 WebSocket, 那么在你通过命令行参数进行端口号配置的时候, go-cqhttp 如何知道你希望覆盖哪个协议呢?

**Comment by 1226085293** [comment]
> 我的意思是说, 你的配置文件, 可能会有多个协议, 例如你同时使用了一个 HTTP 和 WebSocket, 那么在你通过命令行参数进行端口号配置的时候, go-cqhttp 如何知道你希望覆盖哪个协议呢?

你不明白 key 的作用？-a是什么，-b是什么？-a和-b一样？

**Comment by wdvxdr1123** [comment]
配置文件中支持读取环境变量, 可以参照
https://github.com/Mrs4s/go-cqhttp/blob/master/docs/config.md#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

cc @ishkong  文档需要同步一下 docs.go-cqhttp.org
