### ISSUE TITLE
nonebot函数bot.send_msg()发送图片时只能发送CQ码

### ISSUE THREAD

**Issue by genres17** [Mrs4s/go-cqhttp#215]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.20
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
nonebot框架在使用如下部分代码发送图片时，只能发送图片的CQ码，不论是gif格式还是png都不行

`bot = nonebot.get_bot()
 file_name = '真步6星技能动画.gif'
 msg = f'[CQ:image,file={file_name}]'
  await bot.send_msg(group_id=group_id,message=msg,auto_escape=False) #auto_escape: 消息内容是否作为纯文本发送（即不解析 CQ 码），只在 `message` 字段是字符串时有效`

及时是png图片，也同样发送的是CQ码
会在控制台发出一下错误：
[WARNING]: 转换CQ码到MiraiGo Element时出现错误: invalid image 将原样发送.
**复现方法**
如上所述
![图片](https://user-images.githubusercontent.com/60060093/91563876-3d2b1a80-e972-11ea-9bdd-eaf06725fbfb.png)

**Comment by Mrs4s** [comment]
请确保  `真步6星技能动画.gif` 文件在 `data/images` 目录下存在

**Comment by genres17** [comment]
> 
> 
> 请确保 `真步6星技能动画.gif` 文件在 `data/images` 目录下存在

是我之前错改了images目录为image的问题，谢谢提醒
