### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by DPFd** [Mrs4s/go-cqhttp#2154]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.1

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

WebSocket (反向)

### 使用协议

2 | Android Watch

### 重现步骤

import random
from transformers import GPT2LMHeadModel, CpmTokenizer
import argparse
import os
import torch
import time
import re
import torch.nn.functional as F
from nonebot import Bot
from nonebot.plugin.on import on_message,on_command
from nonebot.adapters.onebot.v11 import GroupMessageEvent

if __name__ == '__main__':
    message_test = on_message()

  

  @message_test.handle()
    async def chat_(bot: Bot, event: GroupMessageEvent):  # _是因为其不需要被调用
        print(event.message)
        print(event.sender)
        print(event.self_id)
        content = event.message
        filename = r'E:\sue_bot\sue-bot\src\chat.txt'
        with open(filename, 'a') as file:
            file.write(str(content) + '\n')
        file.close()
        content=str(content)
        if type(content) == str:
            print(content)
            content = re.findall('[\u4e00-\u9fa5]+', content)
            content = ''.join(content)
            print(content)
        else:
            pass

        return content
这里的on_message在机器人正常启动后无效不知道为什么

### 期望的结果是什么？

让这串代码中的on_message可以实际动起来

### 实际的结果是什么？

启动后整个异步函数 甚至连print都是无效的

**Comment by Mrs4s** [comment]
应用问题请不要在这里提
