### ISSUE TITLE
[Bug]: 获取T544时出现问题: <nil>

### ISSUE THREAD

**Issue by IllTamer** [Mrs4s/go-cqhttp#2158]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.1

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

3 | MacOS

### 重现步骤

1. 启动gocq
2. 出现报错
3. 滑块ticket网站报错（521）

### 期望的结果是什么？

滑块ticket网站正常打开

### 实际的结果是什么？

报错521

### 日志记录（可选）

```golang
[ERROR]: 获取T544时出现问题: <nil>
```

**Comment by Happy2018new** [comment]
我使用的是已发布版本，目前仍然存在此问题。
***
系统架构 - `arm64`
运行平台 - `Android / Termux`
使用协议 - `默认协议`
***
![image](https://github.com/Mrs4s/go-cqhttp/assets/109064184/117eb737-3949-445a-905a-a312a01ac54d)

**Comment by clacknya** [comment]
+1

**Comment by lducsm** [comment]
是的，服务器挂了，https://captcha.go-cqhttp.org/出现Error code 521

**Comment by huaifengbusan** [comment]
想问一下这个Error code 521 大概什么时候修复呀，我也遇到同样问题了
![image](https://github.com/Mrs4s/go-cqhttp/assets/49608280/22879d09-49cf-4307-81df-7f3a7432ad7f)
大佬们

**Comment by 1173922902** [comment]
只有手动抓取登录了
![QQ图片20230522172907](https://github.com/Mrs4s/go-cqhttp/assets/44056856/8dd0c951-9a79-4a8c-b297-64860a1d96b3)

**Comment by huaifengbusan** [comment]
> 
请问一下你的滑块验证地址的前缀为啥不是这个呀 https://captcha.go-cqhttp.org/，你的代码是那个版本的呀

**Comment by 1173922902** [comment]
> > 
> 
> 请问一下你的滑块验证地址的前缀为啥不是这个呀 [https://captcha.go-cqhttp.org/，你的代码是那个版本的呀](https://captcha.go-cqhttp.org/%EF%BC%8C%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E6%98%AF%E9%82%A3%E4%B8%AA%E7%89%88%E6%9C%AC%E7%9A%84%E5%91%80)

最新版啊，滑块验证的时候选2就行了，用浏览器看一下响应ticket就行，只不过我是重启才出现的，至于新号登录，不清楚情况

**Comment by githeping** [comment]
> 你好，你用的是哪个版本？

**Comment by githeping** [comment]
> 只有手动抓取登录了 ![QQ图片20230522172907](https://user-images.githubusercontent.com/44056856/239867069-8dd0c951-9a79-4a8c-b297-64860a1d96b3.png)

你这个是哪个版本？

**Comment by githeping** [comment]
> > 你这个是哪个版本？
> 
> https://github.com/Mrs4s/go-cqhttp/releases/tag/v1.0.1

我这还登录不上，显示 Code: 237，频繁登录，在非常用设备登录，请问有解决方法吗

**Comment by huaifengbusan** [comment]
> > > 你这个是哪个版本？
> > 
> > 
> > https://github.com/Mrs4s/go-cqhttp/releases/tag/v1.0.1
> 
> 我这还登录不上，显示 Code: 237，频繁登录，在非常用设备登录，请问有解决方法吗

protocol 换成2 然后密码不用设置，进行扫码登录试试

**Comment by Kizuna-AII** [comment]
> > > 
> > 
> > 
> > 请问一下你的滑块验证地址的前缀为啥不是这个呀 [https://captcha.go-cqhttp.org/，你的代码是那个版本的呀](https://captcha.go-cqhttp.org/%EF%BC%8C%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E6%98%AF%E9%82%A3%E4%B8%AA%E7%89%88%E6%9C%AC%E7%9A%84%E5%91%80)
> 
> 最新版啊，滑块验证的时候选2就行了，用浏览器看一下响应ticket就行，只不过我是重启才出现的，至于新号登录，不清楚情况

你好，我想问一下如何用浏览器查看响应ticket呢？我用Chrome浏览器拖完滑块就直接全白了

**Comment by Kizuna-AII** [comment]
哦哦通过浏览器F12的Network就能抓取token了，但之后显示
`[2023-05-30 13:50:26] [WARNING]: 登录失败: 你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。 Code: 45 
[2023-05-30 13:50:26] [WARNING]: 你的账号涉嫌违规被限制在非常用设备登录, 请在手机QQ登录并根据提示完成认证 
[2023-05-30 13:50:26] [WARNING]: 或使用 -update-protocol 升级到最新协议后重试`
