### ISSUE TITLE
QQ请求失败描述希望能返回具体失败原因

### ISSUE THREAD

**Issue by nssnail** [Mrs4s/go-cqhttp#2159]
go-cqhttp版本: v1.0.1

当前功能：
失败都只会返回这个消息。并不能知道具体原因
![image](https://github.com/Mrs4s/go-cqhttp/assets/52697574/c2c63fb1-0647-42f6-a301-d95900b4f3f0)
希望：
失败的时候能返回具体失败原因

**Comment by Mrs4s** [comment]
已经做了的, 请检查你的版本
