### ISSUE TITLE
消息发送失败没有抛出异常

### ISSUE THREAD

**Issue by Pzzzzz5142** [Mrs4s/go-cqhttp#217]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.23
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
在消息过长发送失败时，python无法捕获这个异常。

**复现方法**
一开始发现这个bug是在私聊发送游戏公告时，原本用于捕获异常的try语句块并没有起到任何作用，从而在消息过长的情况下发送失败时，无法给用户提供相应的错误结果。后面发现原本使用酷q作为后端的代码无法正常使用。

这个代码是用于检测发送长度上限的：
```
async def _(session: CommandSession):
    r = 10000000
    l = 0
    while l < r:
        mid = (r + l) // 2
        try:
            await session.send("." * mid)
            l = mid + 1
        except:
            r = mid

    session.finish(f"{r}")
```

**Comment by Pzzzzz5142** [comment]
在图片发送失败的情况下能正常抛出异常

**Comment by Mrs4s** [comment]
消息上限目前为5000字节数
