### ISSUE TITLE
[Bug]: 无法登录

### ISSUE THREAD

**Issue by dfmjndm** [Mrs4s/go-cqhttp#2172]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.1

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

![image](https://github.com/Mrs4s/go-cqhttp/assets/57401901/a0a719f7-a5d8-49a0-8ccc-95991660d257)

### 期望的结果是什么？

完善

### 实际的结果是什么？

完善

**Comment by kililixi** [comment]
最近很难登了，昨天登的一个号刚被踢了，再登就45

**Comment by tediorelee** [comment]
一样的报错

**Comment by tediorelee** [comment]
> 

更新一下，修改协议protocol5成功登录上

**Comment by Momona0v0** [comment]
这边出现了同样的问题，使用协议2，并使用扫码登录后成功登录上，但并不知道能稳定在线多久。楼主可以尝试一下。

**Comment by ak48835** [comment]
> 

怎么修改协议（萌新

**Comment by Momona0v0** [comment]
> > 
> 
> 怎么修改协议（萌新

https://docs.go-cqhttp.org/guide/config.html#%E5%9C%A8%E7%BA%BF%E7%8A%B6%E6%80%81 中的“设备信息”里有

**Comment by honeway** [comment]
同样的问题，改几个protocol都不行了。

**Comment by otaku0721** [comment]
我甚至无法扫码登录，直接提示[WARNING]: 登录失败: 请使用手Q扫描二维码或短信登录。 Code: 238

**Comment by Momona0v0** [comment]
> 这边出现了同样的问题，使用协议2，并使用扫码登录后成功登录上，但并不知道能稳定在线多久。楼主可以尝试一下。

更新：又不能登录了。尝试几遍以后发现换号可行。但换号不是长久之计。许愿大佬们有办法解决这个问题
