### ISSUE TITLE
[Bug]: 群消息发送失败: 账号可能被风控.

### ISSUE THREAD

**Issue by liujingwei8610** [Mrs4s/go-cqhttp#2174]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.03rc

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

发群消息报错：

群消息发送失败: 账号可能被风控.

产生原因，进入控制台，按了一下回车，突然发了很多消息就被风控了

### 期望的结果是什么？

如何解除风控

### 实际的结果是什么？

还没有解除

**Comment by NoahAmethyst** [comment]
一样的问题

**Comment by NoahAmethyst** [comment]
试过切换协议，删除session,删除设备重新登都不行，问题是我手机消息正常发出来

**Comment by zeroxilo** [comment]
同样的问题。我本想说：
该问题可以临时用1删除原本的token，2在同一环境下扫码登入，3传token到服务器来解决
但今天这次更魔幻直接必须要重新周一套流程还要更新到最新版本qq了。而且这几天一天炸的比一天早。
tx到底整了什么活。。。

**Comment by PackageInstaller** [comment]
+1,手机能正常发文字/图片，bot上就什么都发不出，删除device.json文件重新生成都不行，用的mac协议

**Comment by NoahAmethyst** [comment]
> 

请问设备协议在哪儿找，我在文档里没有找到

**Comment by PackageInstaller** [comment]
> > 
> 
> 请问设备协议在哪儿找，我在文档里没有找到

**device.json** 中 **protocol** 字段

值|类型                    |限制
0 | Default/Unset | 当前版本下默认为iPad
1 | Android Phone | 无
2 | Android Watch | 无法接收 notify 事件、无法接收口令红包、无法接收撤回消息
3 | MacOS | 无
4 | 企点 | 只能登录企点账号或企点子账号
5 | iPad | 无
6 | aPad | 无

**Comment by NoahAmethyst** [comment]
我的解决方案：删除device文件里除了protocol的所有字段，删除sessiontoken，重新登录，目前可恢复群消息发送

**Comment by NoahAmethyst** [comment]
我的解决方案：删除device文件里除了protocol的所有字段，删除sessiontoken，重新登录，目前可恢复群消息发送

**Comment by NoahAmethyst** [comment]
> 我的解决方案：删除device文件里除了protocol的所有字段，删除sessiontoken，重新登录，目前可恢复群消息发送

补充：下午又被风控了

**Comment by G4-SIMPLE** [comment]
好像个人号全寄了

**Comment by bklol** [comment]
风控过一了一段时间会自己恢复一会然后过一会继续被风控

**Comment by NoahAmethyst** [comment]
> 风控过一了一段时间会自己恢复一会然后过一会继续被风控

是的，私聊没问题，我功能先转到私聊了

**Comment by NoahAmethyst** [comment]
> 风控过一了一段时间会自己恢复一会然后过一会继续被风控

是的，私聊没问题，我功能先转到私聊了

**Comment by zeiyu314** [comment]
+1，仍然风控

**Comment by hsyhhssyy** [comment]
各种解决方案都没啥用，现在我的号已经所有协议都登录不了了
手表协议是发不出去，其他协议是45

估计这波风控，大概率这些qqbot库都挺不过去了。
3月的时候，mirai的开发还在想办法解决风控问题，现在两边都开摆了

**Comment by sunzongzheng** [comment]
+1

**Comment by t-satoru** [comment]
我今天也寄了，不过还没尝试换协议

**Comment by xcy333** [comment]
G了，能接收信息就是不能发送，一发送就是风控

**Comment by bklol** [comment]
清空配置使用mac协议后暂时恢复 看之后多久还会风控

**Comment by Tobias272727** [comment]
> 

号1qq手表今天风控
号2qq手表2小时被风控
号1清空配置使用mac协议目前运行1h，看看能坚持多久

**Comment by G37H9** [comment]
> > 
> 
> 号1qq手表今天风控 号2qq手表2小时被风控 号1清空配置使用mac协议目前运行1h，看看能坚持多久

mac协议是几号来着忘记了

**Comment by Tobias272727** [comment]
> > > 
> > 
> > 
> > 号1qq手表今天风控 号2qq手表2小时被风控 号1清空配置使用mac协议目前运行1h，看看能坚持多久
> 
> mac协议是几号来着忘记了

3

**Comment by G37H9** [comment]
> > > 
> > 
> > 
> > 号1qq手表今天风控
> > 号2qq手表2小时被风控
> > 号1清空配置使用mac协议目前运行1h，看看能坚持多久
> 
> 可以试试像我那样改一些参数，改成真机的

怎么改

**Comment by zyr9** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 号1qq手表今天风控
> > > > 号2qq手表2小时被风控
> > > > 号1清空配置使用mac协议目标前运行1h，看看能坚持多久
> > > 
> > > 
> > > 可以试试像我那样改一些参数，改成真机的
> > 
> > 
> > 怎么改
> 
> 我的配置，可以试，不保证有效，从昨天风控后改的，两个群高度修仙，到现在还没有事，看能稳定多久 ![图像](https://user-images.githubusercontent.com/80018096/241726166-99165019-f827-49b6-8c78-dec0dcabf17f.png)

你是哪个版本的 最新的版本我除了手表协议 别的都显示code：45

**Comment by PackageInstaller** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 号1qq手表今天风控
> > > > > 号2qq手表2小时被风控
> > > > > 号1清空配置使用mac协议目标前运行1h，看看能坚持多久
> > > > 
> > > > 
> > > > 可以试试像我那样改一些参数，改成真机的
> > > 
> > > 
> > > 怎么改
> > 
> > 
> > 我的配置，可以试，不保证有效，从昨天风控后改的，两个群高度修仙，到现在还没有事，看能稳定多久 ![图像](https://user-images.githubusercontent.com/80018096/241726166-99165019-f827-49b6-8c78-dec0dcabf17f.png)
> 
> 你是哪个版本的 最新的版本我除了手表协议 别的都显示code：45

我也最新版，可能你号已经黑到家了（

**Comment by t-satoru** [comment]
![image](https://github.com/Mrs4s/go-cqhttp/assets/88642005/251872c6-8e14-469e-97af-7a383c3fcb7e)
macOS直接错误代码45

**Comment by t-satoru** [comment]
使用安卓Pad协议外加真实的设备信息登陆上了，不知道能活多久

**Comment by wolfxin2010** [comment]
号全部被风控，肿么办？

**Comment by Mrzqd** [comment]
+1

**Comment by zexinxu0604** [comment]
我的是删了device.json和session.token重新生成然后登录的，然后设成Macos，滑块验证完又有短信验证，短信验证过了就不提示风控了

**Comment by wc58** [comment]
我的三个号，都被封了，害

**Comment by Seele123** [comment]
+1 同手表协议被风控，只能私聊不能群发

**Comment by jinyu2022** [comment]
刚刚被风控

**Comment by HaunseerLin** [comment]
风控是暂时没办法在群聊里发消息的，但是可以发公告
( ・ω・)o-{{[〃]}}

**Comment by xiamo-sama** [comment]
手表协议风控，其他协议都无法登录`code:45`

**Comment by G4-SIMPLE** [comment]
今天8点到9点限时解控，9点以后又风控了

**Comment by G37H9** [comment]
> 

其实并不是只是解开了  你发几句话就又进去了

**Comment by G37H9** [comment]
> 今天8点到9点限时解控，9点以后又风控了

并不是  是解开了  你发几句话就又被风控了

**Comment by ddlixin** [comment]
> 风控过一了一段时间会自己恢复一会然后过一会继续被风控

是的，我也是一天会被解除风控两小时。两小时后继续会被封控。

**Comment by ddlixin** [comment]
> 今天8点到9点限时解控，9点以后又风控了

我也是，已经三天了

**Comment by UncoDong** [comment]
> 

有用，感谢🌹

**Comment by BiologyHazard** [comment]
> > 今天8点到9点限时解控，9点以后又风控了
> 
> 
> 
> 我也是，已经三天了

我也

**Comment by hsyhhssyy** [comment]
我猜楼上的这些办法，说是有用的，但是也只能有用个几小时不到一天
我觉得，遇到这种情况就代表腾讯标记你这个号了，换来换去也只不过能躲一时，最后最终还是要被风控

**Comment by PackageInstaller** [comment]
> 我猜楼上的这些办法，说是有用的，但是也只能有用个几小时不到一天
> 我觉得，遇到这种情况就代表腾讯标记你这个号了，换来换去也只不过能躲一时，最后最终还是要被风控

正解，号黑到家了啥也不管用，归根到底fuck Tencent 就是了

**Comment by 2055135** [comment]
> 我猜楼上的这些办法，说是有用的，但是也只能有用个几小时不到一天 我觉得，遇到这种情况就代表腾讯标记你这个号了，换来换去也只不过能躲一时，最后最终还是要被风控

建议换个手机注册，出现这情况腾讯把你的手机号列为风险了

**Comment by 2055135** [comment]
我的刚才出现了这种情况，但多次登录后就好了

**Comment by zeiyu314** [comment]
找到了一个永久、稳定、功能健全、不需要动协议、没有复杂配置的方法：




摆了，直接装个QQ用pynput模拟键盘吧。\QaQ/

我就不信还能给我杀了。

**Comment by NoahAmethyst** [comment]
> 找到了一个永久、稳定、功能健全、不需要动协议、没有复杂配置的方法：
> 
> 摆了，直接装个QQ用pynput模拟键盘吧。\QaQ/
> 
> 我就不信还能给我杀了。

是我他妈疯了还是你他妈疯了

太不优雅了

**Comment by ubualduwbe** [comment]
我的猫娘😭，我的猫娘😭

**Comment by Mrs4s** [comment]
#2183

**Comment by twgh** [comment]
> 
我觉得可行, 模拟按键挺简单的, 登录pc端一直开着群窗口, 只需要置剪贴板文本, 粘贴, 发送就行.
可以写一个独立的模拟按键程序出来, 推送消息过去, 它就执行模拟发送.

**Comment by zhx79513** [comment]
> > 
> 我觉得可行, 模拟按键挺简单的, 登录pc端一直开着群窗口, 只需要置剪贴板文本, 粘贴, 发送就行.
> 可以写一个独立的模拟按键程序出来, 推送消息过去, 它就执行模拟发送.
> 
> 

Linux server没有GUI，开不了QQ，就用不了这个办法了

**Comment by twgh** [comment]
> > > 
> > 
> > 
> > 我觉得可行, 模拟按键挺简单的, 登录pc端一直开着群窗口, 只需要置剪贴板文本, 粘贴, 发送就行.
> > 可以写一个独立的模拟按键程序出来, 推送消息过去, 它就执行模拟发送.
> 
> Linux server没有GUI，开不了QQ，就用不了这个办法了
如果最终发消息被风控的问题解决不了, 那就只能用这个方法了, 这个方法不会失效, 反正早做准备

**Comment by hsyhhssyy** [comment]
> > > > 
> > > 
> > > 
> > > 我觉得可行, 模拟按键挺简单的, 登录pc端一直开着群窗口, 只需要置剪贴板文本, 粘贴, 发送就行.
> > > 可以写一个独立的模拟按键程序出来, 推送消息过去, 它就执行模拟发送.
> > 
> > 
> > Linux server没有GUI，开不了QQ，就用不了这个办法了
> > 如果最终发消息被风控的问题解决不了, 那就只能用这个方法了, 这个方法不会失效, 反正早做准备

我觉得这个思路挺好的，大不了专门做一个windows虚拟机甚至arm虚拟机（QQ有Linux ARM版，基于NT的）跑这个程序，这个程序再暴露服务给Linux

不知道大佬开工了没有

**Comment by wangye-sj** [comment]
> 各种解决方案都没啥用，现在我的号已经所有协议都登录不了了 手表协议是发不出去，其他协议是45
> 
> 估计这波风控，大概率这些qqbot库都挺不过去了。 3月的时候，mirai的开发还在想办法解决风控问题，现在两边都开摆了

我的qq本来坚持2个月了，后来被一个大群拉过去之后一天就G了，真难啊  虽然摆了但是我挺佩服这些作者的，给他们点个赞

**Comment by twgh** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 我觉得可行, 模拟按键挺简单的, 登录pc端一直开着群窗口, 只需要置剪贴板文本, 粘贴, 发送就行.
> > > > 可以写一个独立的模拟按键程序出来, 推送消息过去, 它就执行模拟发送.
> > > 
> > > 
> > > Linux server没有GUI，开不了QQ，就用不了这个办法了
> > 
> > 如果最终发消息被风控的问题解决不了, 那就只能用这个方法了, 这个方法不会失效, 反正早做准备
> 
> 我觉得这个思路挺好的，大不了专门做一个windows虚拟机甚至arm虚拟机（QQ有Linux ARM版，基于NT的）跑这个程序，这个程序再暴露服务给Linux
> 
> 不知道大佬开工了没有

我已经写完了, 目前在windows服务器上运行了两天了，没啥问题，支持图片、表情和艾特cq码。这是目前我觉得最完美的解决办法了，只要协议还能登录和收到消息，这个方法就不会失效。

给你们思路: 我是用大漠插件实现的，可以后台粘贴，不影响前台。写一个独立的程序比较好，这样只需要对原机器人程序的发送群聊消息函数改动一下就行，消息发到这个独立的程序上，按消息队列执行模拟发送。

**Comment by zy623240311** [comment]
现在解决了吗

**Comment by hsyhhssyy** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 我觉得可行, 模拟按键挺简单的, 登录pc端一直开着群窗口, 只需要置剪贴板文本, 粘贴, 发送就行.
> > > > > 可以写一个独立的模拟按键程序出来, 推送消息过去, 它就执行模拟发送.
> > > > 
> > > > 
> > > > Linux server没有GUI，开不了QQ，就用不了这个办法了
> > > 
> > > 
> > > 如果最终发消息被风控的问题解决不了, 那就只能用这个方法了, 这个方法不会失效, 反正早做准备
> > 
> > 
> > 我觉得这个思路挺好的，大不了专门做一个windows虚拟机甚至arm虚拟机（QQ有Linux ARM版，基于NT的）跑这个程序，这个程序再暴露服务给Linux
> > 不知道大佬开工了没有
> 
> 我已经写完了, 目前在windows服务器上运行了两天了，没啥问题，支持图片、表情和艾特cq码。这是目前我觉得最完美的解决办法了，只要协议还能登录和收到消息，这个方法就不会失效。
> 
> 给你们思路: 我是用大漠插件实现的，可以后台粘贴，不影响前台。写一个独立的程序比较好，这样只需要对原机器人程序的发送群聊消息函数改动一下就行，消息发到这个独立的程序上，按消息队列执行模拟发送。

我自己也写了一个，用WPF，直接去模拟键鼠Ctrl+C Ctrl+V，不需要OCR，也不需要特殊句柄啥的，更加稳定，而且永远不会被ban。

**Comment by MarsZhu2541** [comment]
所以解决方案是什么
