### ISSUE TITLE
[Bug]: get_forward_msg接口报”消息不存在“

### ISSUE THREAD

**Issue by sunzongzheng** [Mrs4s/go-cqhttp#2176]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.1

### 运行环境

Ubuntu

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

2 | Android Watch

### 重现步骤

# 复现步骤
1. 通过`get_group_msg_history`获取群消息记录，记录中有一条转发消息
2. 通过转发消息的id，调用`/get_forward_msg`接口。会报`消息不存在`

![image](https://github.com/Mrs4s/go-cqhttp/assets/12635613/9132f470-4a1c-445b-a259-6a5feb19b2b2)

### 期望的结果是什么？

调用`/get_forward_msg`接口，能够正常获取到转发消息详情

### 实际的结果是什么？

调用`/get_forward_msg`接口，会报`消息不存在`

### 补充说明（可选）

# 奇怪的现象
我这边通过`get_group_msg_history`获取群消息历史，最近的5条消息始终为转发消息`[CQ:forward,id=xx]`，当有更新的消息时，之前较久的一条转发消息会变成正常的消息内容（非转发消息）

我这边只有一个群是这样，其他的是正常的

**Comment by mingzizhennanqu** [comment]
请问解决了吗，我撤回消息一直失败，报错也是message_id不存在

**Comment by sunzongzheng** [comment]
> 请问解决了吗，我撤回消息一直失败，报错也是message_id不存在

当时未解决，后续被腾讯查封一波登不上了，就没关注了
