### ISSUE TITLE
[Bug]: 现在连手表协议都登录不上去了，求更新主要的手表协议，其他的无所谓了

### ISSUE THREAD

**Issue by gcorpse** [Mrs4s/go-cqhttp#2181]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc5

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

2 | Android Watch

### 重现步骤

现在连手表协议都登录不上去了，求更新主要的手表协议，其他的无所谓了

### 期望的结果是什么？

现在连手表协议都登录不上去了，求更新主要的手表协议，其他的无所谓了

### 实际的结果是什么？

现在连手表协议都登录不上去了，求更新主要的手表协议，其他的无所谓了

**Comment by rhwong** [comment]
你要不要看看你在说什么
版本v1.0.0-rc5？

**Comment by 1797752637** [comment]
v1.0.1已经发布一个多月了

**Comment by ysf-wang** [comment]
v1.0.1手表协议倒是能登上去，现在问题是换一个号没发几条消息过一会儿就被风控，就很尴尬

**Comment by zombie110year** [comment]
我也是啊，v1.0.1 版本， 一个账号被风控后换另一个账号，然后大约一个小时又被风控了。
是不是腾讯服务器更新了什么，导致两边校验对不上了？

**Comment by lianlianaa** [comment]
我也是，其他协议都登不上，然后手表风控了

**Comment by IYATT-yx** [comment]
+1
消息发不出去了，显示被风控

**Comment by PercyDan54** [comment]
协议2345，只有2能登录，其他都问要滑条验证，然后是45或237，但是手表被风控

**Comment by gcorpse** [comment]
请更新手表到最新吧，让我们可以用着顶着，谢谢大大了

**Comment by zombie110year** [comment]
近期风控超严，我6个小时被风控4个账号，没小号用了都。

**Comment by IYATT-yx** [comment]
之前用的手表协议发不出消息了，我换到Mac的又可以了 ，不知道能不能坚持住

**Comment by TheLZY** [comment]
我的手表也被风控了 😥 一条消息都发不出去

**Comment by HaunseerLin** [comment]
别发群消息了，直接发群公告，无视风控。
写个脚本自动切换文本模式，风控就发公告，24小时候再发文本

**Comment by SakuraQuck** [comment]
现在本地就手表扫码可以登上，但是要搭建到服务器上又不能扫码登录，难受

**Comment by zyima** [comment]
1.0.1照样登不上

**Comment by IYATT-yx** [comment]
> 现在本地就手表扫码可以登上，但是要搭建到服务器上又不能扫码登录，难受

本地登录之后，把生成的文件一起拷贝到服务器上面，就能直接登录

**Comment by SakuraQuck** [comment]
> > 现在本地就手表扫码可以登录上，但要搭到服务器上又不能扫码登录，难受
> 
> 本地登录之后，把生成的文件一开始选中到服务器上面，就可以直接登录
不行，会显示恢复会话失败

**Comment by wanli123a** [comment]
+1
消息发不出去了，显示被风控

求作者大大更新

**Comment by BiologyHazard** [comment]
我也是，除了手表都不可用，手表协议被风控发不出消息
现在处于一种完全不可用的状态

**Comment by wanli123a** [comment]
> 我也是，除了手表都不可用，手表协议被风控发不出消息 现在处于一种完全不可用的状态

我跟你一样，同病相怜

**Comment by javencpdd** [comment]
我选择2号的手表协议也没登上去呀，第一次使用
![image](https://github.com/Mrs4s/go-cqhttp/assets/90599089/b9793243-fbe6-4220-859c-7a12760554f1)

**Comment by zombie110year** [comment]
> 我选择2号的手表协议也没登上去呀，第一次使用 [image](https://user-images.githubusercontent.com/90599089/241841391-b9793243-fbe6-4220-859c-7a12760554f1.png)

把 config.yml 里的密码留空，用扫码登录，手表协议用密码登录很难通过验证，我也从来没成功过。
扫码的时候手机和 go-cqhttp 所在的电脑要在同一个网络下，如果是要部署到服务器上的话，可以先在本地个人电脑上扫码登录，成功后把 session.token 复制到服务器上。

**Comment by Yuelioi** [comment]
使用协议3试试

- 登陆验证 选手动获取(自动的会报错)
- 如果再问你设备验证 选手机短信, 后面那个也不行(不知道为啥)

**Comment by javencpdd** [comment]
哦哦，谢谢

兔??子??
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mrs4s/go-cqhttp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月30日(星期二) 中午11:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mrs4s/go-cqhttp] [Bug]: 现在连手表协议都登录不上去了，求更新主要的手表协议，其他的无所谓了 (Issue #2181)





  
我选择2号的手表协议也没登上去呀，第一次使用 image
  
把 config.yml 里的密码留空，用扫码登录，手表协议用密码登录很难通过验证，我也从来没成功过。
 扫码的时候手机和 go-cqhttp 所在的电脑要在同一个网络下，如果是要部署到服务器上的话，可以先在本地个人电脑上扫码登录，成功后把 session.token 复制到服务器上。

**Comment by zombie110year** [comment]
我的QQ号今天上午莫名解封了，我改了机器人的代码，限制了发言频率为5分钟一次，目前运行了一个上午，没有被再次风控。
你们可以试试，1、限制发言频率；2、不加好友；3、不发合并转发消息（禁用相关的插件，或者修改插件代码）。

**Comment by wanli123a** [comment]
> 我选择2号的手表协议也没登上去呀，第一次使用 ![image](https://user-images.githubusercontent.com/90599089/241841391-b9793243-fbe6-4220-859c-7a12760554f1.png)

主要是手表协议登录也没用，发布出去消息- -只能登录接收消息。。 一发消息就风控，群里大佬建议换QQ, 换了QQ ，就活了半小时，可能是tx更新协议了。只能求佬解决了。，

**Comment by zombie110year** [comment]
> 使用协议3试试
> 
> * 登陆验证 选手动获取(自动的会报错)
> * 如果再问你设备验证 选手机短信, 后面那个也不行(不知道为啥)

我想请问一下，QQ的设备锁在哪开，我的账号都没开设备锁，导致只能登录手表，其它协议都登不上。
而且按照网上的教程，【设置】-【账号安全】-【登录设备管理】里面也没有相关的按钮，【设置】-【账号安全】下面的“安全登录检查”已启用，但好像不是设备锁，我登录 go-cqhttp 的时候仍然提示 device lock disabled, http api may fail。

![image](https://github.com/Mrs4s/go-cqhttp/assets/36528430/3dbeaa08-6309-4645-ab87-664ac0d222f9)

**Comment by javencpdd** [comment]
扫码登录也有问题
![image](https://github.com/Mrs4s/go-cqhttp/assets/90599089/e7c37f6d-74b7-4aba-a980-ae0a9ab98138)

**Comment by zombie110year** [comment]
> 扫码登录也有问题 [image](https://user-images.githubusercontent.com/90599089/241844434-e7c37f6d-74b7-4aba-a980-ae0a9ab98138.png)

这是go-cqhttp已经登陆上了，只是监听地址上没有找到机器人的端口。你机器人运行没有？

**Comment by javencpdd** [comment]
> > 扫码登录也有问题 [image](https://user-images.githubusercontent.com/90599089/241844434-e7c37f6d-74b7-4aba-a980-ae0a9ab98138.png)
> 
> 这是go-cqhttp已经登陆上了，只是监听地址上没有找到机器人的端口。你机器人运行没有？

不知道额，这个是在本地 用 go-cqhttp.exe -faststart 启动后就直接扫码了

**Comment by Yuelioi** [comment]
> > 使用协议3试试
> > 
> > * 登陆验证 选手动获取(自动的会报错)
> > * 如果再问你设备验证 选手机短信, 后面那个也不行(不知道为啥)
> 
> 我想请问一下，QQ的设备锁在哪开，我的账号都没开设备锁，导致只能登录手表，其它协议都登不上。 而且按照网上的教程，【设置】-【账号安全】-【登录设备管理】里面也没有相关的按钮，【设置】-【账号安全】下面的“安全登录检查”已启用，但好像不是设备锁，我登录 go-cqhttp 的时候仍然提示 device lock disabled, http api may fail。
> 
> ![image](https://user-images.githubusercontent.com/36528430/241844390-3dbeaa08-6309-4645-ab87-664ac0d222f9.png)

我也没有, 我只是验证滑块 还有手机验证码就好了. 目前过了半小时了, 没有问题

**Comment by javencpdd** [comment]
> > 扫码登录也有问题 [image](https://user-images.githubusercontent.com/90599089/241844434-e7c37f6d-74b7-4aba-a980-ae0a9ab98138.png)
> 
> 这是go-cqhttp已经登陆上了，只是监听地址上没有找到机器人的端口。你机器人运行没有？

找到了问题了，我是直接把服务器的配置复制到本地了，忘记改ip端口了

**Comment by MaiKer-ini** [comment]
同样的，1.0.1显示账号冻结 没法登录

**Comment by MaiKer-ini** [comment]
您好，小庞同学已收到~谢谢...我会尽快回复您！祝您生活愉快，工作顺利……

**Comment by baisepikaq** [comment]
我的上帝，我的小号全都显示45，我已经没有小号能用了

**Comment by snowtafir** [comment]
qq都给我冻结了，屮

**Comment by MaiKer-ini** [comment]
您好，小庞同学已收到~谢谢...我会尽快回复您！祝您生活愉快，工作顺利……
