### ISSUE TITLE
关于无法登录的问题，可以使用手机短信验证码登录

### ISSUE THREAD

**Issue by NAOLIU** [Mrs4s/go-cqhttp#2191]
**需要添加的功能内容**

一些相关资料：
https://github.com/cssxsh/fix-protocol-version/tree/v1.5.0

https://mirai.mamoe.net/topic/1653/%E5%8D%87%E7%BA%A7-mirai-%E8%87%B3-2-14-0-%E4%BD%BF%E7%94%A8%E6%96%B0%E7%9A%84%E7%9F%AD%E4%BF%A1%E9%AA%8C%E8%AF%81%E6%96%B9%E6%B3%95%E8%A7%A3%E5%86%B3%E8%AE%BE%E5%A4%87%E9%AA%8C%E8%AF%81

期待go-cqhttp能早日更新

**Comment by wolfxin2010** [comment]
期待go-cqhttp能早日更新++

**Comment by Alcohol233** [comment]
期待go-cqhttp能早日更新++

**Comment by FightingAction** [comment]
45触发不了验证码把
