### ISSUE TITLE
登录密码明文储存不安全

### ISSUE THREAD

**Issue by Ice-Cirno** [Mrs4s/go-cqhttp#22]
目前qq的登录密码明文储存在config中，在多用户共用服务器、服务器受外部攻击、所用软件有安全漏洞等情况下可能会被窃取。

考虑到自动重新登录的feature，建议：
- 首次登录时询问密码
- 使用密文存储密码

**Comment by masnn** [comment]
cqhttp能够解密表明其他软件也可以解密。
建议您优化 config.json 的文件权限。
