### ISSUE TITLE
[Bug]: 接收消息问题

### ISSUE THREAD

**Issue by QwindF** [Mrs4s/go-cqhttp#2200]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

2 | Android Watch

### 重现步骤

QQ机器人使用手表协议登入
出现个别群接收不到消息，但是使用机器人的账号发送一条消息后又恢复正常

### 期望的结果是什么？

机器人可以收到所有群聊的消息

### 实际的结果是什么？

有部分群聊接收不到，经常是人数少的群聊

**Comment by kanbereina** [comment]
应该是手表协议自身的问题
之前用过手表上的QQ(不是手表协议，是手表QQ)，也有同样的情况

**Comment by ol1u** [comment]
[https://github.com/Mrs4s/go-cqhttp/issues/1957#issuecomment-1461173508](url)

**Comment by ol1u** [comment]
#1957
