### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by pach128** [Mrs4s/go-cqhttp#2203]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.1

### 运行环境

CentOS

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

bot在群聊中功能正常，在私聊中无法返回消息，但从cq日志上看是有回复的

### 期望的结果是什么？

私聊功能正常

### 实际的结果是什么？

私聊无法返回消息

### 日志记录（可选）

```golang
[2023-06-07 10:22:02] [INFO]: 收到好友 xxxxx(xxxxxxxxxx) 的消息: 在？ (-1642706611) 
[2023-06-07 10:22:02] [INFO]: 发送好友 xxxxxxxxxx(xxxxxxxxxx)  的消息: [{"type":" ... (-405696232)
```

**Comment by tonyp8** [comment]
+1,且退出账号后无法重新登陆  code:45

**Comment by 2279881513** [comment]
+1

**Comment by SherkeyXD** [comment]
可能和风控有关，#2183 下面有提到过这种情况

**Comment by pach128** [comment]
> 
诶，但风控不是日志会有提示被风控了么

**Comment by 2279881513** [comment]
私聊和群都没用，但是 我登录上这个qq可以发送信息

**Comment by LYYZZ** [comment]
我也遇到这个问题了，安卓pad协议

**Comment by Mrs4s** [comment]
#2242
