### ISSUE TITLE
[Bug]: 由于使用了会话缓存，无法自动更新协议，请删除缓存后重试

### ISSUE THREAD

**Issue by Agnes4m** [Mrs4s/go-cqhttp#2220]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.1

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

~~协议是APad，你没改~~
win server2012
尝试使用更新协议参数启动，并且启动前已经删除data文件夹

### 期望的结果是什么？

更新协议并启动

### 实际的结果是什么？

![image](https://github.com/Mrs4s/go-cqhttp/assets/70925546/49710519-9197-4a1a-870f-8a97f8e5afb2)

**Comment by BlacK201** [comment]
删除 `session.token` 重新启动

**Comment by Moxin1044** [comment]
> 删除 `session.token` 重新启动

好像删除之后那一次启动有概率会更新，随后关闭又会出现问题。
