### ISSUE TITLE
[Bug]: 最新版本的 iOS QQ 无法显示 CQ:image

### ISSUE THREAD

**Issue by GitXin** [Mrs4s/go-cqhttp#2223]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.1

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

发送 [CQ:image,file=url] 格式的消息

### 期望的结果是什么？

所有客户端均能够正常显示图片

### 实际的结果是什么？

同一条消息，windows 端和 android 能够正常显示

![image](https://github.com/Mrs4s/go-cqhttp/assets/9160651/c1d1c344-4833-4660-bc09-4c2c66784bba)

ios 和 ipad 端 的 QQ 更新到最新版之后无法显示 CQ:image 图片，不过聊天记录里可以看到图片 

![IMG_0109](https://github.com/Mrs4s/go-cqhttp/assets/9160651/800b58ac-b7f1-4944-b4f2-18508781803f)

![IMG_0110](https://github.com/Mrs4s/go-cqhttp/assets/9160651/b9781e2b-1e01-4a47-84cf-e0141943476f)

**Comment by chaselen** [comment]
有问题很久了，希望早点解决

**Comment by Mrs4s** [comment]
1.1已经修复
