### ISSUE TITLE
[Bug]: 取协议T544问题

### ISSUE THREAD

**Issue by yhrbjsy** [Mrs4s/go-cqhttp#2228]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.1

### 运行环境

Ubuntu

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

![image](https://github.com/Mrs4s/go-cqhttp/assets/59187833/36810fad-a6d7-4cc1-adbc-58031ee29e9e)
![image](https://github.com/Mrs4s/go-cqhttp/assets/59187833/a85dec67-a074-4165-adaa-1b150c2c4198)
启动方式：./go-cqhttp -update-protocol  账户密码登录
使用手表和pad协议均出现获取T544问题

### 期望的结果是什么？

预期可正常获取协议

### 实际的结果是什么？

服务器为阿里云杭州，启动go-cqhttp未获取到协议，报T544错误

**Comment by zhaoyongping** [comment]
是那个sdk的应用崩了吧，直接浏览器访问，显示有问题
![image](https://github.com/Mrs4s/go-cqhttp/assets/26564245/76bbbde3-886c-4b4d-a9db-3fca78819262)

**Comment by X-Skirt-X** [comment]
同样的问题，在切换协议后code45问题解决，但是T544问题
## 换协议前
![image](https://github.com/Mrs4s/go-cqhttp/assets/91937041/0e6747e5-e599-4ab6-ba6f-1a0f25cb08c9)
## 换协议后
![image](https://github.com/Mrs4s/go-cqhttp/assets/91937041/67147284-1ca6-44f8-b091-90a27e28f91e)

虽然用的不是8.8.88的协议，但是8.9.50.10650的协议也是可用的

**Comment by Mrs4s** [comment]
#2242
