### ISSUE TITLE
[Bug]: 无法正常登录qq

### ISSUE THREAD

**Issue by AbelKeithsun** [Mrs4s/go-cqhttp#2229]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.1

### 运行环境

其它（请在下方说明）

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

2 | Android Watch

### 重现步骤

![image](https://github.com/Mrs4s/go-cqhttp/assets/33180419/b97ff6d9-6721-4aa9-a097-4238b5e10e0f)

### 期望的结果是什么？

能够正常登录

### 实际的结果是什么？

验证完之后就没有反应了

**Comment by AbelKeithsun** [comment]
![image](https://github.com/Mrs4s/go-cqhttp/assets/33180419/dbb538fe-fb93-4c0b-90d3-3984e8db78a6)

**Comment by LeeJSwit-HCN** [comment]
#2183

**Comment by LeeJSwit-HCN** [comment]
[https://github.com/Mrs4s/go-cqhttp/issues/2229](url)

**Comment by Strawxiguan** [comment]
> ![image](https://user-images.githubusercontent.com/33180419/247559828-dbb538fe-fb93-4c0b-90d3-3984e8db78a6.png)

可能是你设置密码了，手表只能扫码。亦或者是gocq和手机没有连接同一个局域网。如果不是的话就删除token和虚拟文件，重新生成。

**Comment by Mrs4s** [comment]
#2242
