### ISSUE TITLE
[Bug]: 无法登录QQ

### ISSUE THREAD

**Issue by HaoxuanYu2007** [Mrs4s/go-cqhttp#2232]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.1

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

![image](https://github.com/Mrs4s/go-cqhttp/assets/137419260/ee331703-9697-42ed-bfc5-03926c3e757e)

### 期望的结果是什么？

能够登录

### 实际的结果是什么？

无法登录

### 简单的复现代码/链接（可选）

```golang
[2023-06-22 22:17:00] [INFO]: 当前版本:v1.0.1
[2023-06-22 22:17:00] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2023-06-22 22:17:00] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2023-06-22 22:17:05] [INFO]: 开始尝试登录并同步消息...
[2023-06-22 22:17:05] [INFO]: 使用协议: Android Pad 8.9.35.10440
[2023-06-22 22:17:06] [INFO]: 正在检查协议更新...
[2023-06-22 22:17:06] [INFO]: 检测到协议更新: 8.9.35.10440 -> 8.8.88.7083
[2023-06-22 22:17:06] [INFO]: 如果登录时出现版本过低错误, 可尝试使用 -update-protocol 参数启动
[2023-06-22 22:17:06] [INFO]: Protocol -> connect to server: 36.155.205.230:8080
[2023-06-22 22:17:06] [WARNING]: 登录需要滑条验证码, 请验证后重试.
[2023-06-22 22:17:06] [WARNING]: 请选择提交滑块ticket方式:
[2023-06-22 22:17:06] [WARNING]: 1. 自动提交
[2023-06-22 22:17:06] [WARNING]: 2. 手动抓取提交
[2023-06-22 22:17:06] [WARNING]: 请输入(1 - 2)：
1
[2023-06-22 22:17:09] [WARNING]: 请前往该地址验证 -> https://captcha.go-cqhttp.org/captcha?id=hF08Lu5c&style=simple&aid=16&uin=3218660753&sid=1661277421746542537&cap_cd=wB6w4S_0wThEPMm318td5KVNq8NLXHRaFUEP4CBKrAGuI9G4G3WvFg**&clientype=1&apptype=2
[2023-06-22 22:17:28] [WARNING]: 登录失败: 登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Code: 45
[2023-06-22 22:17:28] [WARNING]: 你的账号涉嫌违规被限制在非常用设备登录, 请在手机QQ登录并根据提示完成认证
[2023-06-22 22:17:28] [WARNING]: 或使用 -update-protocol 升级到最新协议后重试
[2023-06-22 22:17:28] [INFO]: 按 Enter 继续....
```

**Comment by Strawxiguan** [comment]
手表扫码(protocol=2)或者创建1.json文件
用记事本创建：
{
"apk_id": "com.tencent.mobileqq",
"app_id": 537118044,
"sub_app_id": 537118044,
"app_key": "0S200MNJT807V3GE",
"sort_version_name": "8.8.88.7083",
"build_time": 1648004515,
"apk_sign": "a6b745bf24a2c277527716f6f36eb68d",
"sdk_version": "6.0.0.2497",
"sso_version": 19,
"misc_bitmap": 150470524,
"main_sig_map": 16724722,
"sub_sig_map": 66560,
"dump_time": 1648004515,
"protocol_type": 1
}
保存为1.json,protocol=1

**Comment by Strawxiguan** [comment]
换手表登陆，虽然概率风控

**Comment by Strawxiguan** [comment]
或者改为手机8.88协议
创建1.json
{
"apk_id": "com.tencent.mobileqq",
"app_id": 537118044,
"sub_app_id": 537118044,
"app_key": "0S200MNJT807V3GE",
"sort_version_name": "8.8.88.7083",
"build_time": 1648004515,
"apk_sign": "a6b745bf24a2c277527716f6f36eb68d",
"sdk_version": "6.0.0.2497",
"sso_version": 19,
"misc_bitmap": 150470524,
"main_sig_map": 16724722,
"sub_sig_map": 66560,
"dump_time": 1648004515,
"protocol_type": 1
}

**Comment by hezi-biancheng** [comment]
试过，要更改qq密码，但是改完显示：登录失败: 当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。还有登录过于频繁, 请在手机QQ登录并根据提示完成认证后等一段时间重试。是不是我的问题啊

**Comment by Strawxiguan** [comment]
> 试过，要更改qq密码，但是改完显示：登录失败: 当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。还有登录过于频繁, 请在手机QQ登录并根据提示完成认证后等一段时间重试。是不是我的问题啊

237就等一段时间，45就换号或者用手表协议

**Comment by Strawxiguan** [comment]
> 试过，要更改qq密码，但是改完显示：登录失败: 当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。还有登录过于频繁, 请在手机QQ登录并根据提示完成认证后等一段时间重试。是不是我的问题啊

code237是登录次数过多，如果还是code45就是寄了，换号或者用手表

**Comment by HaoxuanYu2007** [comment]
> 或者改为手机8.88协议 创建1.json { "apk_id": "com.tencent.mobileqq", "app_id": 537118044, "sub_app_id": 537118044, "app_key": "0S200MNJT807V3GE", "sort_version_name": "8.8.88.7083", "build_time": 1648004515, "apk_sign": "a6b745bf24a2c277527716f6f36eb68d", "sdk_version": "6.0.0.2497", "sso_version": 19, "misc_bitmap": 150470524, "main_sig_map": 16724722, "sub_sig_map": 66560, "dump_time": 1648004515, "protocol_type": 1 }

没听懂 创建完1.json后改咋办 如何引用1.json

**Comment by zhx79513** [comment]
> > 或者改为手机8.88协议 创建1.json { "apk_id": "com.tencent.mobileqq", "app_id": 537118044, "sub_app_id": 537118044, "app_key": "0S200MNJT807V3GE", "sort_version_name": "8.8.88.7083", "build_time": 1648004515, "apk_sign": "a6b745bf24a2c277527716f6f36eb68d", "sdk_version": "6.0.0.2497", "sso_version": 19, "misc_bitmap": 150470524, "main_sig_map": 16724722, "sub_sig_map": 66560, "dump_time": 1648004515, "protocol_type": 1 }
> 
> 没听懂 创建完1.json后改咋办 如何引用1.json

放到 data/versions/ 下边，启动不要用 -update-protocol 参数，先删掉 session.token 缓存

**Comment by whyiskey** [comment]
> 

可以请教下session.token 缓存在那个目录里面啊，还有启动不要用 -update-protocol 参数是什么意思啊，启动不是运行./go-cqhttp吗？

**Comment by whyiskey** [comment]
> > > 或者改为手机8.88协议 创建1.json { "apk_id": "com.tencent.mobileqq", "app_id": 537118044, "sub_app_id": 537118044, "app_key": "0S200MNJT807V3GE", "sort_version_name": "8.8.88.7083", "build_time": 1648004515, "apk_sign": "a6b745bf24a2c277527716f6f36eb68d", "sdk_version": "6.0.0.2497", "sso_version": 19, "misc_bitmap": 150470524, "main_sig_map": 16724722, "sub_sig_map": 66560, "dump_time": 1648004515, "protocol_type": 1 }
> > 
> > 
> > 没听懂 创建完1.json后改咋办 如何引用1.json
> 
> 放到 data/versions/ 下边，启动不要用 -update-protocol 参数，先删掉 session.token 缓存，device.json 里边 protocol 改为 1

可以请教下session.token 缓存在那个目录里面啊，还有启动不要用 -update-protocol 参数是什么意思啊，启动不是运行./go-cqhttp吗？

**Comment by 2575044704** [comment]
> 或者改为手机8.88协议 创建1.json { "apk_id": "com.tencent.mobileqq", "app_id": 537118044, "sub_app_id": 537118044, "app_key": "0S200MNJT807V3GE", "sort_version_name": "8.8.88.7083", "build_time": 1648004515, "apk_sign": "a6b745bf24a2c277527716f6f36eb68d", "sdk_version": "6.0.0.2497", "sso_version": 19, "misc_bitmap": 150470524, "main_sig_map": 16724722, "sub_sig_map": 66560, "dump_time": 1648004515, "protocol_type": 1 }

还是无法登录怎么办
<a href="https://sm.ms/image/5GD4WLEFuaZQ1fz" target="_blank"><img src="https://s2.loli.net/2023/06/23/5GD4WLEFuaZQ1fz.png" ></a>

**Comment by Strawxiguan** [comment]
> > 或者改为手机8.88协议 创建1.json { "apk_id": "com.tencent.mobileqq", "app_id": 537118044, "sub_app_id": 537118044, "app_key": "0S200MNJT807V3GE", "sort_version_name": "8.8.88.7083", "build_time": 1648004515, "apk_sign": "a6b745bf24a2c277527716f6f36eb68d", "sdk_version": "6.0.0.2497", "sso_version": 19, "misc_bitmap": 150470524, "main_sig_map": 16724722, "sub_sig_map": 66560, "dump_time": 1648004515, "protocol_type": 1 }
> 
> 还是无法登录怎么办 [![](https://camo.githubusercontent.com/e047fc3f534c87ba2d087df1dd0b91bde67515665f3200e02a7438e656be6cf8/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30362f32332f35474434574c454675615a5131667a2e706e67)](https://sm.ms/image/5GD4WLEFuaZQ1fz)

换号，或者手表

**Comment by ayakasuki** [comment]
gg 新的协议要sign，icqq上API已经能登tim了 gocq这边好像还没看见

**Comment by hezi-biancheng** [comment]
> > 或者改为手机8.88协议 创建1.json { “apk_id”： “com.tencent.mobileqq”， “app_id”： 537118044， “sub_app_id”： 537118044， “app_key”： “0S200MNJT807V3GE”， “sort_version_name”： “8.8.88.7083”， “build_time”： 1648004515， “apk_sign”： “a6b745bf24a2c277527716f6f36eb68d”， “sdk_version”： “6.0.0.2497”， “sso_version”： 19， “misc_bitmap”： 150470524， “main_sig_map”： 16724722， “sub_sig_map”： 66560， “dump_time”： 1648004515， “protocol_type”： 1 }
> 
> 还是无法登录怎么办 [![](https://camo.githubusercontent.com/e047fc3f534c87ba2d087df1dd0b91bde67515665f3200e02a7438e656be6cf8/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30362f32332f35474434574c454675615a5131667a2e706e67)](https://sm.ms/image/5GD4WLEFuaZQ1fz)

知道了，要开设备锁，但有的开了还是没用，现在我的小号里只有一个能用

**Comment by HanzLeader** [comment]
> 或者改为手机8.88协议 创建1.json { "apk_id": "com.tencent.mobileqq", "app_id": 537118044, "sub_app_id": 537118044, "app_key": "0S200MNJT807V3GE", "sort_version_name": "8.8.88.7083", "build_time": 1648004515, "apk_sign": "a6b745bf24a2c277527716f6f36eb68d", "sdk_version": "6.0.0.2497", "sso_version": 19, "misc_bitmap": 150470524, "main_sig_map": 16724722, "sub_sig_map": 66560, "dump_time": 1648004515, "protocol_type": 1 }

感谢大佬，方法非常有效！

**Comment by GitXin** [comment]
> gg 新的协议要sign，icqq上API已经能登tim了 gocq这边好像还没看见

想问下 icqq 是哪个项目啊

**Comment by MuuuShin** [comment]
可以看这一篇https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88

![image](https://github.com/Mrs4s/go-cqhttp/assets/97760035/d2655d73-7951-4165-8fe7-07249d117310)

8.8.88被集体全爆了
目前还是本地手表协议+扫码 传session和device回云端最靠谱

**Comment by whyiskey** [comment]
> 可以看这一篇https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88
> 
> ![image](https://user-images.githubusercontent.com/97760035/248532200-d2655d73-7951-4165-8fe7-07249d117310.png)
> 
> 8.8.88被集体全爆了 目前还是本地手表协议+扫码 传session和device回云端最靠谱

大神我找不到session在哪里啊，这是哪个目录下面的

**Comment by CCYellowStar** [comment]
> 可以看这一篇https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88
> 
> ![image](https://user-images.githubusercontent.com/97760035/248532200-d2655d73-7951-4165-8fe7-07249d117310.png)
> 
> 8.8.88被集体全爆了 目前还是本地手表协议+扫码 传session和device回云端最靠谱

手表每天只能用一会就一直风控

**Comment by ayakasuki** [comment]
> > gg 新的协议要sign，icqq上API已经能登tim了 gocq这边好像还没看见
> 
> 想问下 icqq 是哪个项目啊

icqqjs/icqq

**Comment by xl2729** [comment]
> 

就是gocq目录下的session.token

**Comment by xl2729** [comment]
> > 可以看这一篇https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88
> > ![image](https://user-images.githubusercontent.com/97760035/248532200-d2655d73-7951-4165-8fe7-07249d117310.png)
> > 8.8.88被集体全爆了 目前还是本地手表协议+扫码 传session和device回云端最靠谱
> 
> 大神我找不到session在哪里啊，这是哪个目录下面的
就是gocq目录下的session.token

**Comment by xl2729** [comment]
> > 可以看这一篇https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88
> > ![image](https://user-images.githubusercontent.com/97760035/248532200-d2655d73-7951-4165-8fe7-07249d117310.png)
> > 8.8.88被集体全爆了 目前还是本地手表协议+扫码 传session和device回云端最靠谱
> 
> 大神我找不到session在哪里啊，这是哪个目录下面的

就是gocq目录下的session.token

**Comment by Mrs4s** [comment]
#2242

**Comment by zheshi111** [comment]
> 或者改为手机8.88协议 创建1.json { "apk_id": "com.tencent.mobileqq", "app_id": 537118044, "sub_app_id": 537118044, "app_key": "0S200MNJT807V3GE", "sort_version_name": "8.8.88.7083", "build_time": 1648004515, "apk_sign": "a6b745bf24a2c277527716f6f36eb68d", "sdk_version": "6.0.0.2497", "sso_version": 19, "misc_bitmap": 150470524, "main_sig_map": 16724722, "sub_sig_map": 66560, "dump_time": 1648004515, "protocol_type": 1 }

提示237频繁，要等多久可以重新登录
