### ISSUE TITLE
[Bug]: 群消息发送失败: 账号可能被风控.

### ISSUE THREAD

**Issue by hezi-biancheng** [Mrs4s/go-cqhttp#2237]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

V1.0.1

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

今天登陆上去准备发送群消息，结果一直提示“群消息发送失败: 账号可能被风控.”

### 期望的结果是什么？

正常发送群消息

### 实际的结果是什么？

[2023-06-24 14:32:00] [WARNING]: 群消息发送失败: 账号可能被风控.

### 日志记录（可选）

```golang
[2023-06-24 14:31:29] [WARNING]: 群消息发送失败: 账号可能被风控. 
[2023-06-24 14:32:00] [WARNING]: 群消息发送失败: 账号可能被风控.
```

**Comment by crosage** [comment]
https://github.com/Mrs4s/go-cqhttp/issues/2183

**Comment by hezi-biancheng** [comment]
> #2183

很奇怪啊，一会儿被风控，一会儿登不上去，就很离谱

**Comment by hezi-biancheng** [comment]
> #2183

okok，解决了，能正常用了

**Comment by zy623240311** [comment]
> 

怎么解决的啊

**Comment by aldreamlau** [comment]
我都是一到半夜就被封了，很寿山
