### ISSUE TITLE
[Bug]: 安卓Pad协议登录会顶掉安卓手机端？

### ISSUE THREAD

**Issue by assassingyk** [Mrs4s/go-cqhttp#2239]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.1

### 运行环境

Linux

### 运行架构

None

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

device配置protocol是6，登录显示使用协议: Android Pad 8.9.35.10440，但是登录失败，Code45，提示账号涉嫌违规被限制在非常用设备登录；
使用 -update-protocol 后显示 协议版本已更新: 8.9.35.10440 -> 8.8.88.7083，可以登录，但实际登录的是安卓手机端，会顶掉手机上的号

### 期望的结果是什么？

使用安卓pad端登录

### 实际的结果是什么？

使用安卓手机端登录

**Comment by LanYangYang114514** [comment]
我也这样，好像是因为apad已经被抛弃了，现在装一个最新的安卓QQHD也不能登录

**Comment by KolinLoa** [comment]
风控很多号都不行了

**Comment by Mrs4s** [comment]
已修复
