### ISSUE TITLE
0.9.23 can not response to event group_increase, where as 0.9.21-fix1 work well.

### ISSUE THREAD

**Issue by ChateauXiao** [Mrs4s/go-cqhttp#224]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.23
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
0.9.23 do not have any reaction to event group_increase

**复现方法**

the same nonebot code work well in 0.9.21-fix1, but 0.9.23 do not work

**Comment by chenxuxin188** [comment]
我这也有这个问题。 我用的AIOCQHTTP 反向WS链接    on_notice('group.approve.increase') 没反应   invite的不知道还没试过    fix1的时候工作正常

**Comment by Pzzzzz5142** [comment]
群主拉人不审核是有事件上报的。但是申请之后同意是没有事件上报的。

**Comment by chenxuxin188** [comment]
测试了一下。。被邀请进群的时候是有事件上报的，也能正常做出回应。但是如果是别人申请入群导致的群人数增加，没有事件上报。

**Comment by Mrs4s** [comment]
> 测试了一下。。被邀请进群的时候是有事件上报的，也能正常做出回应。但是如果是别人申请入群导致的群人数增加，没有事件上报。

感谢测试，我检查下
