### ISSUE TITLE
腾讯云服务器启动时报错 登录时发生致命错误: Packet timed out[Bug]: 

### ISSUE THREAD

**Issue by Fan223** [Mrs4s/go-cqhttp#2240]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.1

### 运行环境

CentOS

### 运行架构

None

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

操作命令如下，我在本地 Windows 上运行 ./go-cqhttp -update-protocol 没有问题，可以成功接收到 QQ 消息并使用代码实现回复，同样的操作在服务器上报错：

![image](https://github.com/Mrs4s/go-cqhttp/assets/91018044/853b5014-7507-4447-8fba-d8b8d3905a9d)

配置文件如下，修改了账号密码，心跳时间和 http uri，同时 5700,5701,8080 端口均已开启且未占用

```
# go-cqhttp 默认配置文件

account: # 账号相关
  uin: qq# QQ账号
  password: '密码' # 密码为空时使用扫码登录
  encrypt: false  # 是否开启密码加密
  status: 0      # 在线状态 请参考 https://docs.go-cqhttp.org/guide/config.html#在线状态
  relogin: # 重连设置
    delay: 3   # 首次重连延迟, 单位秒
    interval: 3   # 重连间隔
    max-times: 0  # 最大重连次数, 0为无限制

  # 是否使用服务器下发的新地址进行重连
  # 注意, 此设置可能导致在海外服务器上连接情况更差
  use-sso-address: true
  # 是否允许发送临时会话消息
  allow-temp-session: false

heartbeat:
  # 心跳频率, 单位秒
  # -1 为关闭心跳
  interval: -1

message:
  # 上报数据类型
  # 可选: string,array
  post-format: string
  # 是否忽略无效的CQ码, 如果为假将原样发送
  ignore-invalid-cqcode: false
  # 是否强制分片发送消息
  # 分片发送将会带来更快的速度
  # 但是兼容性会有些问题
  force-fragment: false
  # 是否将url分片发送
  fix-url: false
  # 下载图片等请求网络代理
  proxy-rewrite: ''
  # 是否上报自身消息
  report-self-message: false
  # 移除服务端的Reply附带的At
  remove-reply-at: false
  # 为Reply附加更多信息
  extra-reply-data: false
  # 跳过 Mime 扫描, 忽略错误数据
  skip-mime-scan: false
  # 是否自动转换 WebP 图片
  convert-webp-image: false

output:
  # 日志等级 trace,debug,info,warn,error
  log-level: warn
  # 日志时效 单位天. 超过这个时间之前的日志将会被自动删除. 设置为 0 表示永久保留.
  log-aging: 15
  # 是否在每次启动时强制创建全新的文件储存日志. 为 false 的情况下将会在上次启动时创建的日志文件续写
  log-force-new: true
  # 是否启用日志颜色
  log-colorful: true
  # 是否启用 DEBUG
  debug: true # 开启调试模式

# 默认中间件锚点
default-middlewares: &default
  # 访问密钥, 强烈推荐在公网的服务器设置
  access-token: ''
  # 事件过滤器文件目录
  filter: ''
  # API限速设置
  # 该设置为全局生效
  # 原 cqhttp 虽然启用了 rate_limit 后缀, 但是基本没插件适配
  # 目前该限速设置为令牌桶算法, 请参考:
  # https://baike.baidu.com/item/%E4%BB%A4%E7%89%8C%E6%A1%B6%E7%AE%97%E6%B3%95/6597000?fr=aladdin
  rate-limit:
    enabled: false # 是否启用限速
    frequency: 1  # 令牌回复频率, 单位秒
    bucket: 1     # 令牌桶大小

database: # 数据库相关设置
  leveldb:
    # 是否启用内置leveldb数据库
    # 启用将会增加10-20MB的内存占用和一定的磁盘空间
    # 关闭将无法使用 撤回 回复 get_msg 等上下文相关功能
    enable: true
  sqlite3:
    # 是否启用内置sqlite3数据库
    # 启用将会增加一定的内存占用和一定的磁盘空间
    # 关闭将无法使用 撤回 回复 get_msg 等上下文相关功能
    enable: false
    cachettl: 3600000000000 # 1h

# 连接服务列表
servers:
  # 添加方式，同一连接方式可添加多个，具体配置说明请查看文档
  #- http: # http 通信
  #- ws:   # 正向 Websocket
  #- ws-reverse: # 反向 Websocket
  #- pprof: #性能分析服务器

  - http: # HTTP 通信设置
      address: 0.0.0.0:5700 # HTTP监听地址
      version: 11     # OneBot协议版本, 支持 11/12
      timeout: 5      # 反向 HTTP 超时时间, 单位秒，<5 时将被忽略
      long-polling:   # 长轮询拓展
        enabled: false       # 是否开启
        max-queue-size: 2000 # 消息队列大小，0 表示不限制队列大小，谨慎使用
      middlewares:
        <<: *default # 引用默认中间件
      post:           # 反向HTTP POST地址列表
      #- url: ''                # 地址
      #  secret: ''             # 密钥
      #  max-retries: 3         # 最大重试，0 时禁用
      #  retries-interval: 1500 # 重试时间，单位毫秒，0 时立即
      - url: http://127.0.0.1:5701/ # 地址
        secret: ''                  # 密钥
      #  max-retries: 10             # 最大重试，0 时禁用
      #  retries-interval: 1000      # 重试时间，单位毫秒，0 时立即
```

device.json 文件为默认生成的，未动

### 期望的结果是什么？

成功登录

### 实际的结果是什么？

登录报错 登录时发生致命错误: Packet timed out

### 日志记录（可选）

```golang
见重现步骤里的操作命令
```

**Comment by QiXingQXX** [comment]
看那个版本号更新到空了没，后台取协议的地方寄了

**Comment by BingKKni** [comment]
> 看那个版本号更新到空了没，后台取协议的地方寄了

我今天机器人莫名突然被踢下线后来也是这样登不上去了，换协议就45了，前几周弹45捣鼓了3小时才搞好

**Comment by BingKKni** [comment]
我今天机器人莫名突然被踢下线后来也是这样登不上去了，换协议就45了，前几周弹45捣鼓了3小时才搞好

**Comment by BingKKni** [comment]
> 我是私聊被屏蔽了，删token之后登不上，更新协议就致命错误，然后又继续用的旧token，应该能撑到问题解决

现在还有除手表以外的协议会用到token嘛，我用的是1.0.1最新版本

**Comment by QiXingQXX** [comment]
> 

我印象里是手表没有token，别的协议肯定是有的，之前icqq不能登陆的时候借用gocq的token就是这个

**Comment by BingKKni** [comment]
> > > 我是私聊被屏蔽了，删token之后登不上，更新协议就致命错误，然后又继续用的旧token，应该能撑到问题解决
> > 
> > 
> > 现在还有除手表以外的协议会用到token文件嘛，我用的是1.0.1最新版本 我看了一下只有手表协议目录下才有session.token，其他协议没有
> 
> 我印象里是手表没有token，别的协议肯定是有的，之前icqq不能登陆的时候借用gocq的token就是这个 你没看到token文件应该是没登陆上吧

我现在只能用手表协议才能登，其他协议全部报45，手机验证过了好几遍不是2XX就是45qwq...
这个机器人加了很多群的，不想开小号，真的没办法解决了吗

**Comment by QiXingQXX** [comment]
> > > > 我是私聊被屏蔽了，删token之后登不上，更新协议就致命错误，然后又继续用的旧token，应该能撑到问题解决
> > > 
> > > 
> > > 现在还有除手表以外的协议会用到token文件嘛，我用的是1.0.1最新版本 我看了一下只有手表协议目录下才有session.token，其他协议没有
> > 
> > 
> > 我印象里是手表没有token，别的协议肯定是有的，之前icqq不能登陆的时候借用gocq的token就是这个 你没看到token文件应该是没登陆上吧
> 
> 我现在只能用手表协议才能登，其他协议全部报45，手机验证过了好几遍不是2XX就是45qwq... 这个机器人加了很多群的，不想开小号，真的没办法解决了吗

我有基于yunzai-bot核心写过一个兼容层，但仅限http协议，不知道你要不要试试

**Comment by BingKKni** [comment]
试一下！怎么加你联系方式

**Comment by BingKKni** [comment]
> > > > > 我是私聊被屏蔽了，删token之后登不上，更新协议就致命错误，然后又继续用的旧token，应该能撑到问题解决
> > > > 
> > > > 
> > > > 现在还有除手表以外的协议会用到token文件嘛，我用的是1.0.1最新版本 我看了一下只有手表协议目录下才有session.token，其他协议没有
> > > 
> > > 
> > > 我印象里是手表没有token，别的协议肯定是有的，之前icqq不能登陆的时候借用gocq的token就是这个 你没看到token文件应该是没登陆上吧
> > 
> > 
> > 我现在只能用手表协议才能登，其他协议全部报45，手机验证过了好几遍不是2XX就是45qwq... 这个机器人加了很多群的，不想开小号，真的没办法解决了吗
> 
> 我有基于yunzai-bot核心写过一个兼容层，但仅限http协议，不知道你要不要试试
试一下！怎么加你联系方式

**Comment by BingKKni** [comment]
> > > > > 我是私聊被屏蔽了，删token之后登不上，更新协议就致命错误，然后又继续用的旧token，应该能撑到问题解决
> > > > 
> > > > 
> > > > 现在还有除手表以外的协议会用到token文件嘛，我用的是1.0.1最新版本 我看了一下只有手表协议目录下才有session.token，其他协议没有
> > > 
> > > 
> > > 我印象里是手表没有token，别的协议肯定是有的，之前icqq不能登陆的时候借用gocq的token就是这个 你没看到token文件应该是没登陆上吧
> > 
> > 
> > 我现在只能用手表协议才能登，其他协议全部报45，手机验证过了好几遍不是2XX就是45qwq... 这个机器人加了很多群的，不想开小号，真的没办法解决了吗
> 
> 我有基于yunzai-bot核心写过一个兼容层，但仅限http协议，不知道你要不要试试

怎么加你!!

**Comment by QiXingQXX** [comment]
> > > > > > 我是私聊被屏蔽了，删token之后登不上，更新协议就致命错误，然后又继续用的旧token，应该能撑到问题解决
> > > > > 
> > > > > 
> > > > > 现在还有除手表以外的协议会用到token文件嘛，我用的是1.0.1最新版本 我看了一下只有手表协议目录下才有session.token，其他协议没有
> > > > 
> > > > 
> > > > 我印象里是手表没有token，别的协议肯定是有的，之前icqq不能登陆的时候借用gocq的token就是这个 你没看到token文件应该是没登陆上吧
> > > 
> > > 
> > > 我现在只能用手表协议才能登，其他协议全部报45，手机验证过了好几遍不是2XX就是45qwq... 这个机器人加了很多群的，不想开小号，真的没办法解决了吗
> > 
> > 
> > 我有基于yunzai-bot核心写过一个兼容层，但仅限http协议，不知道你要不要试试
> 
> 怎么加你!!

1363184096

**Comment by BingKKni** [comment]
> > > > > > > 我是私聊被屏蔽了，删token之后登不上，更新协议就致命错误，然后又继续用的旧token，应该能撑到问题解决
> > > > > > 
> > > > > > 
> > > > > > 现在还有除手表以外的协议会用到token文件嘛，我用的是1.0.1最新版本 我看了一下只有手表协议目录下才有session.token，其他协议没有
> > > > > 
> > > > > 
> > > > > 我印象里是手表没有token，别的协议肯定是有的，之前icqq不能登陆的时候借用gocq的token就是这个 你没看到token文件应该是没登陆上吧
> > > > 
> > > > 
> > > > 我现在只能用手表协议才能登，其他协议全部报45，手机验证过了好几遍不是2XX就是45qwq... 这个机器人加了很多群的，不想开小号，真的没办法解决了吗
> > > 
> > > 
> > > 我有基于yunzai-bot核心写过一个兼容层，但仅限http协议，不知道你要不要试试
> > 
> > 
> > 怎么加你!!
> 
> q:1363184096

加了

**Comment by chuanSir123** [comment]
> 看那个版本号更新到空了没，后台取协议的地方寄了

对，更新为空了，以前能更新的，有办法直接修改版本号或者换协议地址么

**Comment by Fan223** [comment]
> > 看那个版本号更新到空了没，后台取协议的地方寄了
> 
> 对，更新为空了，以前能更新的，有办法直接修改版本号或者换协议地址么

我是之前本地登录成功过，生成了 session.token 文件，把这个 token 文件复制过来就会用这个会话的缓存，不会再更新为空了，可以成功登录。或者看上面说的手表协议好像可以直接登，修改 device.json 的 protocol 的值，具体看官方文档，不过这个我没试

**Comment by SunshineboyZj** [comment]
> > > 看那个版本号更新到空了没，后台取协议的地方寄了
> > 
> > 
> > 对，更新为空了，以前能更新的，有办法直接修改版本号或者换协议地址么
> 
> 我是之前本地登录成功过，生成了 session.token 文件，把这个 token 文件复制过来就会用这个会话的缓存，不会再更新为空了，可以成功登录。或者看上面说的手表协议好像可以直接登，修改 device.json 的 protocol 的值，具体看官方文档，不过这个我没试

换手表协议也没用，能登上去有有啥用，发几条消息就“群消息发送失败可能账号被风控”了
