### ISSUE TITLE
[Bug]: 部署了签名服务器之后依然出现风控问题，且删除相关文件后依然无法登陆

### ISSUE THREAD

**Issue by zzz6839** [Mrs4s/go-cqhttp#2244]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.1.0

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

```
$ docker compose run go-cqhttp
[+] Building 0.0s (0/0)                                                                                                                                                       
[+] Building 0.0s (0/0)                                                                                                                                                       
---Setup Timezone to Asia/Shanghai---
---Checking if UID: 99 matches user---
---Checking if GID: 100 matches user---
usermod: no changes
---Setting umask to 002---
---Taking ownership of data...---
Starting...
[2023-06-27 12:45:48] [INFO]: 当前版本:(devel) 
[2023-06-27 12:45:48] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2023-06-27 12:45:48] [INFO]: 使用服务器 http://192.168.1.154:6789 进行数据包签名 
[2023-06-27 12:45:48] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2023-06-27 12:45:53] [INFO]: 开始尝试登录并同步消息... 
[2023-06-27 12:45:53] [INFO]: 使用协议: Android Pad 8.9.63.11390 
[2023-06-27 12:45:53] [INFO]: 正在检查协议更新... 
[2023-06-27 12:45:54] [INFO]: Protocol -> connect to server: 59.83.207.254:8080 
[2023-06-27 12:45:54] [WARNING]: 登录需要滑条验证码, 请验证后重试. 
[2023-06-27 12:45:54] [WARNING]: 请选择提交滑块ticket方式: 
[2023-06-27 12:45:54] [WARNING]: 1. 自动提交 
[2023-06-27 12:45:54] [WARNING]: 2. 手动抓取提交 
[2023-06-27 12:45:54] [WARNING]: 请输入(1 - 2)： 
1
[2023-06-27 12:45:57] [WARNING]: 请前往该地址验证 -> 
[2023-06-27 12:46:07] [WARNING]: 登录失败: 你的帐号涉嫌违规被限制在非常用设备登录，请更换常用设备后重新登录并根据提示进行解封。 Code: 45 
[2023-06-27 12:46:07] [WARNING]: 你的账号被限制登录, 请配置 SignServer 后重试 
[2023-06-27 12:46:07] [INFO]: 按 Enter 继续.... 
```

### 期望的结果是什么？

可以正常且无风控登陆

### 实际的结果是什么？

风控Code: 45

### 补充说明（可选）

新号，使用docker运行且已经部署了qsign，但是风控了，之后根据 #2242 里面的内容删除device.json和session token，重新生成尝试登陆依然不成功，显示 code:45 ，协议为Apad。

**Comment by Mrs4s** [comment]
有些账号风控等级很高, 没办法的 换号吧

**Comment by ElainaFanBoy** [comment]
我也是这样，我老号也控

**Comment by ElainaFanBoy** [comment]
> 有些账号风控等级很高, 没办法的 换号吧
> 别拿新号做bot

我现在所有老号都被45了，没更新之前用updateprotocol还没事，现在加上signapi也45

**Comment by ElainaFanBoy** [comment]
> > 有些账号风控等级很高, 没办法的 换号吧
> > 别拿新号做bot
> 
> 我现在所有老号都被45了，没更新之前用updateprotocol还没事，现在加上signapi也45

解决了，我之前用的是别人的api，我自建了个然后同步了下andriod_id，去手机版解封一下重新上就好了

**Comment by Zxis233** [comment]
> > > 有些账号风控等级很高, 没办法的 换号吧
> > > 别拿新号做bot
> > 
> > 
> > 我现在所有老号都被45了，没更新之前用updateprotocol还没事，现在加上signapi也45
> 
> 解决了，我之前用的是别人的api，我自建了个然后同步了下andriod_id，去手机版解封一下重新上就好了

问问，手机版登录一直提示“你的帐号涉嫌违规被限制在非常用设备登录，请更换常用设备后重新登录并根据提示进行解封”，有啥解决方法吗

**Comment by ElainaFanBoy** [comment]
> > > > 有些账号风控等级很高, 没办法的 换号吧
> > > > 别拿新号做bot
> > > 
> > > 
> > > 我现在所有老号都被45了，没更新之前用updateprotocol还没事，现在加上signapi也45
> > 
> > 解决了，我之前用的是别人的api，我自建了个然后同步了下andriod_id，去手机版解封一下重新上就好了
> 
> 问问，手机版登录一直提示“你的帐号涉嫌违规被限制在非常用设备登录，请更换常用设备后重新登录并根据提示进行解封”，有啥解决方法吗

你是不是tim？我tim一开始也是这样，无法解除和登录，换最新版本qq登录就可以正常解封了

**Comment by Zxis233** [comment]
> > > > > 有些账号风控等级很高, 没办法的 换号吧
> > > > > 别拿新号做bot
> > > > 
> > > > 
> > > > 我现在所有老号都被45了，没更新之前用updateprotocol还没事，现在加上signapi也45
> > > 
> > > 
> > > 解决了，我之前用的是别人的api，我自建了个然后同步了下andriod_id，去手机版解封一下重新上就好了
> > 
> > 
> > 问问，手机版登录一直提示“你的帐号涉嫌违规被限制在非常用设备登录，请更换常用设备后重新登录并根据提示进行解封”，有啥解决方法吗
> 
> 你是不是tim？我tim一开始也是这样，无法解除和登录，换最新版本qq登录就可以正常解封了

已经更换三台设备，均为最新版QQ。

**Comment by ElainaFanBoy** [comment]
> > > > > > 有些账号风控等级很高, 没办法的 换号吧
> > > > > > 别拿新号做bot
> > > > > 
> > > > > 
> > > > > 我现在所有老号都被45了，没更新之前用updateprotocol还没事，现在加上signapi也45
> > > > 
> > > > 
> > > > 解决了，我之前用的是别人的api，我自建了个然后同步了下andriod_id，去手机版解封一下重新上就好了
> > > 
> > > 
> > > 问问，手机版登录一直提示“你的帐号涉嫌违规被限制在非常用设备登录，请更换常用设备后重新登录并根据提示进行解封”，有啥解决方法吗
> > 
> > 你是不是tim？我tim一开始也是这样，无法解除和登录，换最新版本qq登录就可以正常解封了
> 
> 已经更换三台设备，均为最新版QQ。

那我就不太清楚了

**Comment by Agnes4m** [comment]
同以上问题，在账号45提示非常用设备登录后，自己无法在pc，手机qq和tim上登录（都已确认是最新版本），因此无法解除风控。

再尝试解除冻结后提示没用冻结，但是号已无法在任何设备上登录，修改密码也无济于事。

看起来应该和我是同一个问题，蹲一个解决办法
