### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by leavedrop** [Mrs4s/go-cqhttp#2250]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc5

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

2 | Android Watch

### 重现步骤

在device.json中将protocol改成2了 cmd中启动仍然使用的是Android Pad协议

### 期望的结果是什么？

应该是使用Android watch协议了吧

### 实际的结果是什么？

[WARNING]: 当前协议不支持二维码登录, 请配置账号密码登录

### 补充说明（可选）

![image](https://github.com/Mrs4s/go-cqhttp/assets/86217087/c94d4ffc-f6ed-4b68-a56c-bcb11a0570d8)

**Comment by hezi-biancheng** [comment]
额，你还在用V1.1.0？

**Comment by hezi-biancheng** [comment]
还在用V1.0.0？

**Comment by leavedrop** [comment]
> 还在用V1.0.0？
跟版本没关系 这个问题我解决了 改成1.1了
