### ISSUE TITLE
[Bug]: 将bot用pyinstaller打包成exe的时候无法加载自定义插件？有人知道解决方法吗

### ISSUE THREAD

**Issue by prettend-s** [Mrs4s/go-cqhttp#2252]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0-rc3

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

2 | Android Watch

### 重现步骤

如题

### 期望的结果是什么？

![屏幕截图 2023-06-28 211642](https://github.com/Mrs4s/go-cqhttp/assets/99039892/f7d807d2-9389-4577-a9c7-add571f81bfa)

### 实际的结果是什么？

![屏幕截图 2023-06-28 211624](https://github.com/Mrs4s/go-cqhttp/assets/99039892/3c88a178-d51a-4e2f-a444-540f6b5a71a9)

### 补充说明（可选）

其他都是正常的能返回消息，就是导入的包都不见了

**Comment by kanrichan** [comment]
nonebot 问题请到 nonebot 仓库询问
