### ISSUE TITLE
[Bug]: 无法接收频道消息

### ISSUE THREAD

**Issue by leecoooo** [Mrs4s/go-cqhttp#2254]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

所有版本

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

WebSocket (正向)

### 使用协议

2 | Awatch

### 重现步骤

某些账号无法接收频道消息，无论是@还是打开消息通知都不行，群和私聊是正常的，接收和发送正常

### 期望的结果是什么？

接收到频道消息

### 实际的结果是什么？

无法接收频道消息

**Comment by 2mf8** [comment]
频道需要安卓协议（至少目前是这样）

**Comment by 2mf8** [comment]
而且相应子频道通知需要打开（还无法接收消息的话就把订阅点上）

**Comment by leecoooo** [comment]
> 频道需要安卓协议（至少目前是这样）

用Awatch可以扫描登录，用Apad被限制登录，就算设置了签名服务器还是一样

[2023-06-30 16:12:19] [WARNING]: 登录失败: 登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Code: 45
[2023-06-30 16:12:19] [WARNING]: 你的账号被限制登录, 请配置 SignServer 后重试
