### ISSUE TITLE
[Bug]: 签名服务器配置完提示未配置

### ISSUE THREAD

**Issue by CleMooling** [Mrs4s/go-cqhttp#2261]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.1.0

### 运行环境

Ubuntu

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

修改配置，如图（仅供示例参考）
（评论区补发）

### 期望的结果是什么？

正常进行登录流程

### 实际的结果是什么？

提示未配置签名验证服务器

**Comment by CleMooling** [comment]
![IMG_20230630_130959](https://github.com/Mrs4s/go-cqhttp/assets/93636342/4ebb74bd-7e78-419d-a82b-059bbfa37f54)
![Screenshot_2023-06-30-13-06-42-34_84d3000e3f4017145260f7618db1d683](https://github.com/Mrs4s/go-cqhttp/assets/93636342/80ad54b0-0221-4489-8f2c-1f079ad91629)

**Comment by CleMooling** [comment]
null

**Comment by hujusen** [comment]
看截图感觉你缺了缩进
