### ISSUE TITLE
[Bug]: 音乐自定义分享 没有办法正常使用

### ISSUE THREAD

**Issue by airdm** [Mrs4s/go-cqhttp#2281]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.1.0

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

音乐自定义分享 没有办法正常发出音乐内容 只能发出一个url链接

### 期望的结果是什么？

发送正常的音乐卡片

### 实际的结果是什么？

只是发出了一个url链接

### 简单的复现代码/链接（可选）

{
    "type": "music",
    "data": {
        "type": "custom",
        "url": "http://baidu.com",
        "audio": "http://baidu.com/1.mp3",
        "title": "音乐标题"
    }
}

**Comment by 2114460639** [comment]
rc5修改了参数，audio改为voice即可使用

**Comment by airdm** [comment]
> rc5修改了参数，audio改为voice即可使用

试了 没有效果还是只会发一个url链接 发的链接正好是json里data下的url内容

**Comment by airdm** [comment]
找到相关问题. 需要在data下添加一个subtype 参考格式如下
{
    "type": "music",
    "data": {
      "type": "custom",
      "url": "http://baidu.com/",
      "voice": "http://baidu.com/1.mp3",
      "title": "标题",
      "content": "副标题",
      "subtype": "163",
      "image": "图片地址"
    }
}
