### ISSUE TITLE
QQ音乐点歌是不是有点问题！

### ISSUE THREAD

**Issue by nicemoe** [Mrs4s/go-cqhttp#230]
![image](https://user-images.githubusercontent.com/39013459/91986990-02552800-ed60-11ea-8312-50b8605a4686.png)
![image](https://user-images.githubusercontent.com/39013459/91987015-0d0fbd00-ed60-11ea-8846-5e755b2ab979.png)
![image](https://user-images.githubusercontent.com/39013459/91987160-45af9680-ed60-11ea-9d4b-908183298aea.png)
好像是参数拼接少了&，框架0.9.23

**Comment by scjtqs** [comment]
应该是xml里面的url没有转义&符

**Comment by Mrs4s** [comment]
fixed.
