### ISSUE TITLE
[Bug]: 获取T544 sign时出现错误: encoding/hex: invalid byte: U+0069 'i'

### ISSUE THREAD

**Issue by neohary** [Mrs4s/go-cqhttp#2304]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.1.0

### 运行环境

Windows (64)

### 运行架构

x86

### 连接方式

WebSocket (反向)

### 使用协议

1 | Android Phone

### 重现步骤

1. 在config.json里配置了账号密码和sign-server，配置了反代地址，其他没动
2. device.json用的是默认配置
3. 运行go-cqhttp.bat，提示获取T544 sign时出现错误: encoding/hex: invalid byte: U+0069 'i'
4. 提示需要滑条验证码，选自动提交
5. 验证完后又出现获取T544 sign时出现错误: encoding/hex: invalid byte: U+0069 'i'
6. 返回登录失败，我的cqhttp已经是最新版本了，我的账号用tim和qq直接登录也没问题

### 期望的结果是什么？

账号正常登录

### 实际的结果是什么？

获取T544 sign时出现错误: encoding/hex: invalid byte: U+0069 'i'

### 日志记录（可选）
![QQ截图20230719104407](https://github.com/Mrs4s/go-cqhttp/assets/66161411/3fa3a436-b7c1-40d8-93c1-51ced3cfe0fa)

**Comment by mmmjie** [comment]
gocq 1.1对应的qsign1.1版
如使用qsign1.3版以上，需要使用gocq的dev版

**Comment by mmmjie** [comment]
建议直接使用qsign1.1版，然后配置守护程序，崩溃自动重启比较稳定

**Comment by neohary** [comment]
按照你的建议在本地配置了1.1版的，问题解决了

**Comment by lowking** [comment]
> gocq 1.1对应的qsign1.1版 如使用qsign1.3版以上，需要使用gocq的dev版

给部署1.1.7版本qsign的建议，可以自己编译dev分支（当前commit：0714aac1f0ad209644cc1a7db514305d19078dc6），然后配置文件按下图增加几个，就可以正常登录和发消息了
![image](https://github.com/Mrs4s/go-cqhttp/assets/33308659/dacc531f-42d6-48b1-aca2-f4d587addbbc)

**Comment by wangsan168** [comment]
> > 建议直接使用qsign1.1版，然后配置守护程序，崩溃自动重启比较稳定
> > Linux环境下使用qsign1.1版本启动时报错咋办
> 
> ```
> [root@VM-0-7-centos unidbg-fetch-qsign-1.1.0]# ls ./txlib/8.9.63/
> config.json  dtconfig.json  libfekit.so  libQSec.so
> [root@VM-0-7-centos unidbg-fetch-qsign-1.1.0]# ./bin/unidbg-fetch-qsign --basePath=txlib/8.9.63 --port=8080 --count=1 --android-id=xxx --host=0.0.0.0
> Exception in thread "main" java.lang.IllegalArgumentException: Lack of libfekit.so path.
>         at moe.fuqiuluo.comm.ArgsParser.get(ArgsParser.kt:25)
>         at MainKt.main(Main.kt:50)
> ```

这个key的值是什么

**Comment by wangsan168** [comment]
> > gocq 1.1对应的qsign1.1版 如使用qsign1.3版以上，需要使用gocq的dev版
> 
> 给部署1.1.7版本qsign的建议，可以自己编译dev分支（当前commit：0714aac1f0ad209644cc1a7db514305d19078dc6），然后配置文件按下图增加几个，就可以正常登录和发消息了 ![image](https://user-images.githubusercontent.com/33308659/257546969-dacc531f-42d6-48b1-aca2-f4d587addbbc.png)

这个key的值是什么

**Comment by lowking** [comment]
> > > gocq 1.1对应的qsign1.1版 如使用qsign1.3版以上，需要使用gocq的dev版
> > 
> > 
> > 给部署1.1.7版本qsign的建议，可以自己编译dev分支（当前commit：0714aac1f0ad209644cc1a7db514305d19078dc6），然后配置文件按下图增加几个，就可以正常登录和发消息了 ![image](https://user-images.githubusercontent.com/33308659/257546969-dacc531f-42d6-48b1-aca2-f4d587addbbc.png)
> 
> 这个key的值是什么

qsign1.1.7配置文件里面的

**Comment by xiwangly2** [comment]
> > gocq 1.1对应的qsign1.1版 如使用qsign1.3版以上，需要使用gocq的dev版
> 
> 给部署1.1.7版本qsign的建议，可以自己编译dev分支（当前commit：0714aac1f0ad209644cc1a7db514305d19078dc6），然后配置文件按下图增加几个，就可以正常登录和发消息了 ![image](https://user-images.githubusercontent.com/33308659/257546969-dacc531f-42d6-48b1-aca2-f4d587addbbc.png)

此回答有用，我尝试在https://github.com/fuqiuluo/unidbg-fetch-qsign/wiki/%E9%83%A8%E7%BD%B2%E5%9C%A8Docker跟进了这个issues
等下一个稳定版应该就行了（

**Comment by Gimme8** [comment]
请问为什么qsing1.1.0版没有txlib，该怎么配置

**Comment by Kobe972** [comment]
我用qsign 1.1.9还是不行
