### ISSUE TITLE
[Bug]: 群聊消息仅能发送十几个字

### ISSUE THREAD

**Issue by hnuuhc** [Mrs4s/go-cqhttp#2324]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.1.0

### 运行环境

Ubuntu

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

1 | Android Phone

### 重现步骤

在任何账号使用签名服务器(1.1.0/1.1.3/1.1.4/.1.15)登录后，均为群聊发送短消息正常，在超过十几个字后显示账号风控

### 期望的结果是什么？

消息正常发送

### 实际的结果是什么？

几个字的消息正常发送，超过十几个字就无法发送

### 日志记录（可选）

```golang
发送消息失败，账号可能被风控
```

**Comment by wuhen007** [comment]
gocq1.1只能用sign1.1版本，1.1上需要dev分支
CI : https://github.com/Mrs4s/go-cqhttp/actions/runs/5504923059

**Comment by hnuuhc** [comment]
> 

除签名服务器1.1.0版本，cqhttp使用的都是dev分支，在登录后就是简短的消息群聊发送正常，长一些就开始吞消息，不理解什么情况，要是真风控不应该全部都吞吗。

**Comment by hnuuhc** [comment]
> gocq1.1只能用sign1.1版本，1.1上需要dev分支 CI : https://github.com/Mrs4s/go-cqhttp/actions/runs/5504923059

除签名服务器1.1.0版本，cqhttp使用的都是dev分支，在登录后就是简短的消息群聊发送正常，长一些就开始吞消息，不理解什么情况，要是真风控不应该全部都吞吗。

**Comment by hezi-biancheng** [comment]
> > gocq1.1只能用sign1.1版本，1.1上需要dev分支 CI : https://github.com/Mrs4s/go-cqhttp/actions/runs/5504923059
> 
> 除签名服务器1.1.0版本，cqhttp使用的都是dev分支，在登录后就是简短的消息群聊发送正常，长一些就开始吞消息，不理解什么情况，要是真风控不应该全部都吞吗。

正常，你可能被腾讯盯上了，那有一个正常使用qq的人可以在那么短的时间发送那么长的消息

**Comment by hnuuhc** [comment]
> > > gocq1.1只能用sign1.1版本，1.1上需要dev分支 CI : https://github.com/Mrs4s/go-cqhttp/actions/runs/5504923059
> > 
> > 
> > 除签名服务器1.1.0版本，cqhttp使用的都是dev分支，在登录后就是简短的消息群聊发送正常，长一些就开始吞消息，不理解什么情况，要是真风控不应该全部都吞吗。
> 
> 正常，你可能被腾讯盯上了，那有一个正常使用qq的人可以在那么短的时间发送那么长的消息

但是我所有账号都这样子,而且测试环境,可能几小时才发个消息,这还能频繁不成,在原先使用8.8.8协议登陆时正常的账号,更换签名服务器后也会这样子吞长消息,我现在不清楚是哪里出问题了.

**Comment by wuhen007** [comment]
> > > > gocq1.1只能用sign1.1版本，1.1上需要dev分支 CI : https://github.com/Mrs4s/go-cqhttp/actions/runs/5504923059
> > > 
> > > 
> > > 除签名服务器1.1.0版本，cqhttp使用的都是dev分支，在登录后就是简短的消息群聊发送正常，长一些就开始吞消息，不理解什么情况，要是真风控不应该全部都吞吗。
> > 
> > 
> > 正常，你可能被腾讯盯上了，那有一个正常使用qq的人可以在那么短的时间发送那么长的消息
> 
> 但是我所有账号都这样子,而且测试环境,可能几小时才发个消息,这还能频繁不成,在原先使用8.8.8协议登陆时正常的账号,更换签名服务器后也会这样子吞长消息,我现在不清楚是哪里出问题了.
sign最新是1.1.7，可以最新版本测试，如果你用的是本地自己部署的签名，可以尝试公共api是否存在类似情况，反之亦然。如果都存在你说的情况，多半是账号问题。

**Comment by StevehimYu** [comment]
我也遇到了同样的问题，想知道如何解决呢？本来想做一个点歌机器人的....
