### ISSUE TITLE
请问支持企业QQ吗？

### ISSUE THREAD

**Issue by leoguan88** [Mrs4s/go-cqhttp#233]
请问支持企业QQ吗？企业QQ登录，提示如下：
登录失败: 帐号不存在或因安全问题登录受限，请联系当地经销商/官网客服处理。

v0.9.17的版本！请问该如何解决？

**Comment by scjtqs** [comment]
兼容企业qq有风险。

**Comment by Mrs4s** [comment]
不会支持
