### ISSUE TITLE
Feature request: 支持 unidbg-fetch-qsign 1.1.7

### ISSUE THREAD

**Issue by idanran** [Mrs4s/go-cqhttp#2330]
**环境信息**

go-cqhttp版本: 1.1.0

**需要添加的功能内容**

https://github.com/fuqiuluo/unidbg-fetch-qsign
https://github.com/rhwong/unidbg-fetch-qsign-onekey

**Comment by rhwong** [comment]
使用action版本

**Comment by idanran** [comment]
正式版咋还没更新呀？

**Comment by rhwong** [comment]
> 正式版咋还没更新呀？

那谁懂啊

**Comment by yihais** [comment]
还没测试好呢

**Comment by fumiama** [comment]
> > 正式版咋还没更新呀？
> 
> 那谁懂啊

主开发者太忙了
