### ISSUE TITLE
群列表刷新问题Bug

### ISSUE THREAD

**Issue by leoguan88** [Mrs4s/go-cqhttp#234]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.17
运行环境: windows_amd64
连接方式: POST

**bug内容**
机器人已进群，也收到进群事件，但收不到群里任何消息。
get_group_list 取到的群号，也没有刚进去的群
get_group_member_info 也取不到群成员
解决就像机器人不在群里一样。要重启，显示加载群后，才正常。

是否有方法刷新群的相关信息？而不需要重启！

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by Mrs4s** [comment]
请更新到最新版本
