### ISSUE TITLE
[Bug]: 开启数小时后，刷新 token 出现错误: This mutex is not locked server

### ISSUE THREAD

**Issue by hatsuyuki13** [Mrs4s/go-cqhttp#2347]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

dev

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

6 | aPad

### 重现步骤

不确定是哪里的问题。
docker里运行最新的go-cqhttp-dev和qsign-1.1.7，连接同一网络。
运行几个小时之后，go-cqhttp开始在刷新token时出现如下警告：

[2023-08-03 01:31:27] [INFO]: 正在刷新 token
[2023-08-03 01:31:32] [WARNING]: 刷新 token 出现错误: This mutex is not locked server: http://qsign:8080 
[2023-08-03 02:11:27] [INFO]: 正在刷新 token
[2023-08-03 02:11:32] [WARNING]: 刷新 token 出现错误: This mutex is not locked server: http://qsign:8080 

此时仍然可以接收和发送消息，但是再过几个小时可能就不行了。

qsign默认配置无修改，日志没有错误信息。
go-cqhttp部分配置如下：
  sign-server: 'http://qsign:8080'
  sign-server-bearer: '-'
  is-below-110: false
  key: '114514'
  auto-register: true
  auto-refresh-token: true
  refresh-interval: 40

### 期望的结果是什么？

刷新token成功

### 实际的结果是什么？

刷新token失败

**Comment by 1umine** [comment]
确定是最新的吗？最新的 `auto-register` 和 `auto-refresh-token` 应该都是默认false的

**Comment by fumiama** [comment]
怀疑是qsign server的报错，请更新最新dev版本看看新的log打印以确定。

**Comment by 1umine** [comment]
应该是有callback没提交上，token没法正常刷新，qsign 可能会返回 `This mutex is not locked server`，或者短时间内多次刷新了token也会出这个

**Comment by hatsuyuki13** [comment]
感谢大大们回复，gocq版本是actions docker最新的[3b99a82](https://github.com/Mrs4s/go-cqhttp/commit/3b99a825eb620350e7ff9c25fce99065c0d73dec)
token是每40分钟刷新一次，应该没短时间多次刷新。
开启debug日志后如下，还是没有什么有用的信息，大概可能是qsign的问题，这里就先关掉issue了。
![QQ截图20230804055133](https://github.com/Mrs4s/go-cqhttp/assets/85502450/cc31b957-5985-4f11-be72-95455f17ecaa)

**Comment by fumiama** [comment]
> 感谢大大们回复，gocq版本是actions docker最新的[3b99a82](https://github.com/Mrs4s/go-cqhttp/commit/3b99a825eb620350e7ff9c25fce99065c0d73dec) token是每40分钟刷新一次，应该没短时间多次刷新。 开启debug日志后如下，还是没有什么有用的信息，大概可能是qsign的问题，这里就先关掉issue了。 ![QQ截图20230804055133](https://user-images.githubusercontent.com/85502450/258245529-cc31b957-5985-4f11-be72-95455f17ecaa.png)

最新的日志主要就是为了确定 This mutex is not locked 是 qsign 的报错消息，现在已经可以确定确实如此。那么就有可能是这个原因了

> 应该是有callback没提交上，token没法正常刷新，qsign 可能会返回 `This mutex is not locked server`，或者短时间内多次刷新了token也会出这个。建议提供更多可能相关的日志，以及使用的gocq的来源（直接链接最好，方便找到相应代码）

**Comment by fumiama** [comment]
试试最新dev.

**Comment by 1umine** [comment]
> 最新的dev没有修复This mutex is not locked的问题。
> 
> ```
> (base) z@JOJO:~$ docker image inspect d0507a32e7eeffe1dd9f2c91b14720cfb0526b2352ea852c4544d67aa0812ffc
> [
>     {
>         "Id": "sha256:d0507a32e7eeffe1dd9f2c91b14720cfb0526b2352ea852c4544d67aa0812ffc",
>         "RepoTags": [
>             "ghcr.io/mrs4s/go-cqhttp:dev"
>         ],
>         "RepoDigests": [
>             "ghcr.io/mrs4s/go-cqhttp@sha256:39afa55975458c95047ffe99bf7fb86577060ec5b6ee47e0121dbd779a5318fb"
> ```
> ```
> 2023-08-06 00:03:58 [2023-08-06 00:03:58] [INFO]: 收到服务器地址更新通知, 将在下一次重连时应用.  
> 2023-08-06 00:06:54 [2023-08-06 00:06:54] [INFO]: 正在刷新 token 
> 2023-08-06 00:06:59 [2023-08-06 00:06:59] [WARNING]: 刷新 token 出现错误: code=1, msg: This mutex is not locked. server: http://192.168.1.154:6753 
> 2023-08-06 00:33:19 [2023-08-06 00:33:19] [INFO]: 收到好友 A( ) 的消息: 后台管理 (-
> 2023-08-06 00:33:20 [2023-08-06 00:33:20] [INFO]: 发送好友 ()  的消息: [{"type":  ... (-
> 2023-08-06 00:46:54 [2023-08-06 00:46:54] [INFO]: 正在刷新 token 
> 2023-08-06 00:46:59 [2023-08-06 00:46:59] [WARNING]: 刷新 token 出现错误: code=1, msg: This mutex is not locked. server: http://192.168.1.154:6753 
> 2023-08-06 01:26:54 [2023-08-06 01:26:54] [INFO]: 正在刷新 token 
> 2023-08-06 01:26:59 [2023-08-06 01:26:59] [WARNING]: 刷新 token 出现错误: code=1, msg: This mutex is not locked. server: http://192.168.1.154:6753
> ```

感觉是qsign的问题，可能还能追到unibdg上（
