### ISSUE TITLE
风控后自动重新登录（获取session）

### ISSUE THREAD

**Issue by BlackcatWatcher** [Mrs4s/go-cqhttp#2356]
**环境信息**

go-cqhttp版本: 
v1.1.0
**需要添加的功能内容**

状况：目前在signserver已配置的情况下，风控表现为一段时间后发送消息提示已风控，关掉gocq后重新打开，风控自动解除。
建议：新增一个配置项，或直接尝试。当检测到风控时，自动重新登录/获取session，或多次风控后允许直接关闭gocq（因为写了个小程序检测到关闭后自动重开）

**Comment by rhwong** [comment]
这不是风控了 这是你签名服务器掉线了
建议升级一哈

**Comment by BlackcatWatcher** [comment]
> 这不是风控了 这是你签名服务器掉线了 （比如网络不好的状况，比如注册过期的状况） 消息咩有经由签名服务器处理就发送了出去，就会被风控。 建议看action，里面有自动刷新token。 如果你还在用1.1.0那么你肯定qsign也是1.1.1以下，那么建议你升级到qsign1.1.7

感谢，已升级到94a3ff5，qsign1.1.7，确实增加了自动刷新token功能，希望尽早到正式版。
