### ISSUE TITLE
希望加群请求支持风险账号

### ISSUE THREAD

**Issue by tianque1** [Mrs4s/go-cqhttp#236]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.23
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
希望加群请求支持风险账号，像图中这种加群请求目前bot不会进行上报
![image](https://user-images.githubusercontent.com/37477320/92108223-96cf9100-ee19-11ea-89c8-fdc3936f1bb3.png)

**复现方法**
o(*￣▽￣*)ブ

**Comment by Mrs4s** [comment]
这个不是很好测试

**Comment by tianque1** [comment]
> 这个不是很好测试

是比较麻烦，刚才试了一下，用小号在同一个群来回踢十几次就会被标记风险(按照上次的情况来看1-3天后会自动解除)
同时小号申请这个群的时候管理员不会收到加群通知(也可能是管理员QQ因为短期踢人太多触发了什么规则)
申请其他群的时候会被归类到已过滤中
![image](https://user-images.githubusercontent.com/37477320/92212654-e0c18100-eec4-11ea-8c80-7ff343b61477.png)

![image](https://user-images.githubusercontent.com/37477320/92212709-f9319b80-eec4-11ea-8cff-52a202c10e7f.png)
