### ISSUE TITLE
关于发送语音的示例修改

### ISSUE THREAD

**Issue by samondlee** [Mrs4s/go-cqhttp#237]
啊这，dalao 原来在COOLQ发送语音的格式如何修改 才能符合 现在的go-cqhttp标准，在文档里没找到呀

用以下方式 发语音的时候会提示 [不支持的方法]

`hentai_audio=(".......你想在这里做什么？.amr","不能理解......不能理解......不能理解......amr")
roar_audio=("刷刷刷......刷刷刷.......amr","刷牙.amr","刷牙2.amr")
song_audio=("对吧！谁叫我是个高性能机器人呢嗯哼！.amr","呜呜......我好可怜.amr","眼泪也会在高兴的时候流呢.amr")

@sv.on_fullmatch(('变态','我是变态','我是绅士','变态可疑分子','可疑分子'))
async def chat_hentai(bot,ev):
    rec=random.choice(hentai_audio)
    await bot.send(ev,R.rec(rec).cqcode)

@sv.on_fullmatch(('娇喘',))
async def chat_roar(bot,ev):
    rec=random.choice(roar_audio)
    await bot.send(ev,R.rec(rec).cqcode)

@sv.on_fullmatch(('唱歌','唱首歌','来首歌','来唱首歌'), only_to_me=True)
async def sing(bot,ev):
    rec=random.choice(song_audio)
    await bot.send(ev,R.rec(rec).cqcode)

`

**Comment by samondlee** [comment]
`class ResRec(ResObj):
    @property
    def cqcode(self) -> MessageSegment:
        if hoshino.config.RES_PROTOCOL=='http':
            return MessageSegment.record(self.url)
        elif hoshino.config.RES_PROTOCOL=='file':
            return MessageSegment.record(f'file://{os.path.abspath(self.path)}')
        else:
            return MessageSegment.text('[不支持的方法]')
    
def get(path, *paths):
    return ResObj(os.path.join(path, *paths))

def rec(path, *paths):
    return ResRec(os.path.join('rec', path, *paths))

def img(path, *paths):
    return ResImg(os.path.join('img', path, *paths))
`


啊这，好像是R.py的模块= =不会改= =

**Comment by zangxx66** [comment]
可以参考我之前写的一个[语音模组](https://github.com/zangxx66/HoshinoBot-xcwRecord)  
语音以外的其他模组好像被我整出bug了别完全照搬

**Comment by samondlee** [comment]
> 可以参考我之前写的一个[语音模组](https://github.com/zangxx66/HoshinoBot-xcwRecord)
> 语音以外的其他模组好像被我整出bug了别完全照搬

啊这 感谢，是base64问题，file也不行换成http协议可以了
