### ISSUE TITLE
是否考虑支持vivo50签名服务器

### ISSUE THREAD

**Issue by qn8524king** [Mrs4s/go-cqhttp#2374]
**环境信息**
是否考虑支持https://github.com/kiliokuara/magic-signer-guide 这个签名服
目前看起来qsign有时候还会有点小问题，被封号的情况偶尔还是会出现，稳定但不完全稳定。。
而且那个签名服不开源，tx就算想针对他也不知道该从哪里下手，在一点上我们这些用机器人的账号vsTX是更为有利的

不然qsign天天被人看光底裤。。。（

当然还是希望保留qsign
go-cqhttp版本: 

**需要添加的功能内容**
希望可以添加对vivo50签名服的签名支持

**Comment by rhwong** [comment]
如果有人写支持当然是好事儿。
但是qsign目前来看如果您使用了大于1.1.5的版本，并不会偶尔导致封号，除非您触碰了黑产等内容，从行为层面被tx封禁。
而且不开源也并不意味着`我们这些用机器人的账号vsTX是更为有利`，你腾子哥想识别你是不是机器人，有的是法子。

**Comment by qn8524king** [comment]
> 如果有人写支持当然是好事儿。 但是qsign目前来看如果您使用了大于1.1.5的版本，并不会偶尔导致封号，除非您触碰了黑产等内容，从行为层面被tx封禁。 而且不开源也并不意味着`我们这些用机器人的账号vsTX是更为有利`，你腾子哥想识别你是不是机器人，有的是法子。

了解，具体封号的情况我再观察一下吧，因为不只是我，偶尔也会看到那个风控的discussions下有人说90天，所以想着是不是兼容其他签名会更好（
我的机器人最开始用1.14，被封，人脸解除后用1.16，两天后被封了3天，今天刚解除，改用1.17b+8.9.63协议
很奇怪，这东西是不是跟ip有关，我是挂腾讯云的，可能是IP黑了罢QAQ
封号理由都是“涉嫌进行业务违规操作”，担心下一次就是90天啥的了。
我本地和公司挂自己号+测试号的机器人qsign一点事都没。。所以我以为是不稳定的问题（

**Comment by 1umine** [comment]
看了下这个要实现感觉贼麻烦（

**Comment by rhwong** [comment]
> 天啥的了。

大概率还是号的问题，封号这个事情，除了1.1.0时期的2小时必封之外，都是号本身的问题。
因为在没有qsign之前，甚至追溯到cq时期，该封号也是有封号的，并不是说封号自qsign起。

**Comment by qn8524king** [comment]
了解了qaq
