### ISSUE TITLE
[Bug]: 企点qq无法登录

### ISSUE THREAD

**Issue by Sam5440** [Mrs4s/go-cqhttp#2379]
# 有企业号的各位可以加群来讨论一下 ，群号：891637894

### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.1.0

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

HTTP

### 使用协议

4 | 企点

### 重现步骤

登录

### 期望的结果是什么？

登录成功

### 实际的结果是什么？

无法登录

### 日志记录（可选）

```golang
[2023-08-16 23:27:02] [INFO]: 当前版本:v1.1.0
[2023-08-16 23:27:02] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2023-08-16 23:27:02] [WARNING]: 警告: 未配置签名服务器, 这可能会导致登录 45 错误码或发送消息被风控
[2023-08-16 23:27:02] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2023-08-16 23:27:07] [INFO]: 开始尝试登录并同步消息...
[2023-08-16 23:27:07] [INFO]: 使用协议: 企点 5.0.0
[2023-08-16 23:27:07] [INFO]: 正在检查协议更新...
[2023-08-16 23:27:07] [INFO]: Protocol -> connect to server: 183.47.110.220:8080
[2023-08-16 23:27:07] [WARNING]: 登录失败: 当前应用版本过低，请升级至最新版或联系客服沟通。 Code: 235
[2023-08-16 23:27:07] [WARNING]: 设备信息被封禁, 请删除 device.json 后重试.
[2023-08-16 23:27:07] [INFO]: 按 Enter 继续....
```

**Comment by wyf67** [comment]
[2023-08-17 10:26:42] [WARNING]: 获取T544 sign时出现错误: encoding/hex: invalid byte: U+0069 'i' 
[2023-08-17 10:26:42] [WARNING]: 登录失败: 登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。 Code: 45 
[2023-08-17 10:26:42] [WARNING]: 你的账号被限制登录, 请配置 SignServer 后重试

**Comment by xxyy3130** [comment]
[2023-08-17 16:46:53] [INFO]: 使用协议: 企点 5.0.0
[2023-08-17 16:46:53] [INFO]: Protocol -> connect to server: 119.147.190.138:8080
[2023-08-17 16:46:55] [WARNING]: 登录失败: 当前应用版本过低，请升级至最新版或联系客服沟通。 Code: 235
[2023-08-17 16:46:55] [WARNING]: 设备信息被封禁, 请删除 device.json 后重试.
[2023-08-17 16:46:55] [INFO]: 按 Enter 继续....

**Comment by MQpeng** [comment]
有处理方案么🤔

**Comment by Sam5440** [comment]
已经解决，多重启概率解决

**Comment by leoguan88** [comment]
重启了几十次了，还是一样的提示：
[2023-08-17 16:46:55] [WARNING]: 登录失败: 当前应用版本过低，请升级至最新版或联系客服沟通。 Code: 235
[2023-08-17 16:46:55] [WARNING]: 设备信息被封禁, 请删除 device.json 后重试.

**Comment by Sam5440** [comment]
重启登录成功的概率.在5%左右

> 重启了几十次了，还是一样的提示： [2023-08-17 16:46:55] [WARNING]: 登录失败: 当前应用版本过低，请升级至最新版或联系客服沟通。 Code: 235 [2023-08-17 16:46:55] [WARNING]: 设备信息被封禁, 请删除 device.json 后重试.

重启成功概率在50‰左右（doge

**Comment by MQpeng** [comment]
重试一直没效果

**Comment by leoguan88** [comment]
重启登录成功的概率.在5%左右，也叫解决？？
我重启了 100 次了，一次都还没有成功！不可能是概率问题

**Comment by liaosunny123** [comment]
我觉得不是概率问题，应该就是协议问题

**Comment by xxyy3130** [comment]
有解决方案了吗🥺

**Comment by Patricia-email** [comment]
不是概率问题吧， 我这边也是登录好多次也没登录上过
[2023-08-19 23:33:27] [INFO]: 当前版本:v1.1.0 
[2023-08-19 23:33:27] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2023-08-19 23:33:27] [INFO]: 使用服务器 http://127.0.0.1:8080 进行数据包签名 
[2023-08-19 23:33:27] [INFO]: 开始尝试登录并同步消息... 
[2023-08-19 23:33:27] [INFO]: 使用协议: 企点 5.0.0 
[2023-08-19 23:33:32] [INFO]: Protocol -> connect to server: 14.22.9.53:8080 
[2023-08-19 23:33:32] [WARNING]: 登录失败: 当前应用版本过低，请升级至最新版或联系客服沟通。 Code: 235 
[2023-08-19 23:33:32] [WARNING]: 设备信息被封禁, 请删除 device.json 后重试.

**Comment by kkgg0521** [comment]
如何处理 家人们

**Comment by kkgg0521** [comment]
> 不是概率问题吧， 我这边也是登录好多次也没登录上过， 也在本地搭了签名服务。 [2023-08-19 23:33:27] [INFO]: 当前版本:v1.1.0 [2023-08-19 23:33:27] [INFO]: 将使用 device.json 内的设备信息运行Bot. [2023-08-19 23:33:27] [INFO]: 使用服务器 http://127.0.0.1:8080 进行数据包签名 [2023-08-19 23:33:27] [INFO]: 开始尝试登录并同步消息... [2023-08-19 23:33:27] [INFO]: 使用协议: 企点 5.0.0 [2023-08-19 23:33:32] [INFO]: Protocol -> connect to server: 14.22.9.53:8080 [2023-08-19 23:33:32] [WARNING]: 登录失败: 当前应用版本过低，请升级至最新版或联系客服沟通。 Code: 235 [2023-08-19 23:33:32] [WARNING]: 设备信息被封禁, 请删除 device.json 后重试.

有解决办法了吗

**Comment by zhaoyongshui** [comment]
同上问题，在线等处理方案，大佬们

**Comment by zhaoyongshui** [comment]
搞得我快要奔溃了

**Comment by zhaoyongshui** [comment]
博主，可以建一个群呀，大家都可以在群里讨论相关问题，这样一起探讨解决方案

**Comment by kkgg0521** [comment]
> 博主，可以建一个群呀，大家都可以在群里讨论相关问题，这样一起探讨解决方案

咋样了

**Comment by zhaoyongshui** [comment]
还不行啊，试了很多办法，分析一下个人觉得应应该是 企点的协议是不是升级了，cq 中的起点xie y 是不是也要跟着升级一下才行呀

**Comment by Orange5771** [comment]
同样这个问题，企点协议要升级了

**Comment by Orange5771** [comment]
> 还不行啊，试了很多办法，分析一下个人觉得应应该是 企点的协议是不是升级了，CQ 中的起点xie y 是不是也要跟着升级一下才行呀
需要更新企点协议，怎么更新还不会

**Comment by KomeiDiSanXian** [comment]
如果要使用qsign来进行登陆，只能使用安卓协议，不支持其他平台的。一般使用的都是apad协议
具体可以看[这里](https://github.com/fuqiuluo/unidbg-fetch-qsign/blob/master/README.md)

**Comment by MQpeng** [comment]
> 如果要使用qsign来进行登陆，只能使用安卓协议，不支持其他平台的。一般使用的都是apad协议
> 具体可以看[这里](https://github.com/fuqiuluo/unidbg-fetch-qsign/blob/master/README.md)

支持企点么

**Comment by kkgg0521** [comment]
> 还不行啊，试了很多办法，分析一下个人觉得应应该是 企点的协议是不是升级了，cq 中的起点xie y 是不是也要跟着升级一下才行呀

有解决方法了吗

**Comment by MTmin** [comment]
> > 还不行啊，试了很多办法，分析一下个人觉得应应该是 企点的协议是不是升级了，cq 中的起点xie y 是不是也要跟着升级一下才行呀
> 
> 有解决方法了吗

新建一个4.json然后把最新的企点版本信息塞进去就行了

**Comment by freezingWu** [comment]
> > > 还不行啊，试了很多办法，分析一下个人觉得应应该是 企点的协议是不是升级了，cq 中的起点xie y 是不是也要跟着升级一下才行呀
> > 
> > 
> > 有解决方法了吗
> 
> 新建一个4.json然后把最新的企点版本信息塞进去就行了
能把步骤细说 一下？

**Comment by MTmin** [comment]
> > > > 还不行啊，试了很多办法，分析一下个人觉得应应该是 企点的协议是不是升级了，cq 中的起点xie y 是不是也要跟着升级一下才行呀
> > > 
> > > 
> > > 有解决方法了吗
> > 
> > 
> > 新建一个4.json然后把最新的企点版本信息塞进去就行了
> > 能把步骤细说 一下？

没啥具体步骤..就是那个appid我不知道哪里找...所以没有具体步骤等等大佬看看有没有大佬发的

**Comment by zhaoyongshui** [comment]
> > > 还不行啊，试了很多办法，分析一下个人觉得应该是企点的协议是不是升级了，cq中的起点xie y 是不是还要跟着升级一下才行呀
> > 
> > 
> > 有解决方法了吗
> 
> 新建一个4.json然后把最新的源点版本信息塞进去就行了

大佬，具体的能说一步骤吗

**Comment by kkgg0521** [comment]
卧槽 有解决办法了吗

**Comment by MTmin** [comment]
临时恢复方案,下载https://github.com/MTmin/go-cqhttp/actions/runs/5971849526 这个版本
然后 在/data/versions里面新建一个4.json把以下内容塞进去
{
  "apk_id": "com.tencent.qidian",
  "app_id": 537061587,
  "sub_app_id": 537036590,
  "app_key": "1CV185J6EU1UW3R7",
  "sort_version_name": "5.8.0",
  "build_time": 1630062176,
  "apk_sign": "314cf9fe7ec66d89608f766679a710b5",
  "sdk_version": "6.0.0.2484",
  "sso_version": 18,
  "misc_bitmap": 184024956,
  "main_sig_map": 34869472,
  "sub_sig_map": 66560,
  "dump_time": 1683193286,
  "protocol_type": 4
}

启动机器人即可,抱一丝好友列表获取不到所以我注释掉了编译了一个版本先用着,后续看看大佬们有没有新的方案

**Comment by zhaoyongshui** [comment]
> 临时恢复方案,下载https://github.com/MTmin/go-cqhttp/actions/runs/5971849526 这个版本 然后 在/data/versions里面新建一个4.json把以下内容塞进去 { "apk_id": "com.tencent.qidian", "app_id": 537061587, "sub_app_id": 537036590, "app_key": "1CV185J6EU1UW3R7", "sort_version_name": "5.8.0", "build_time": 1630062176, "apk_sign": "314cf9fe7ec66d89608f766679a710b5", "sdk_version": "6.0.0.2484", "sso_version": 18, "misc_bitmap": 184024956, "main_sig_map": 34869472, "sub_sig_map": 66560, "dump_time": 1683193286, "protocol_type": 4 }
> 
> 启动机器人即可,抱一丝好友列表获取不到所以我注释掉了编译了一个版本先用着,后续看看大佬们有没有新的方案

有效，🙏 多谢大佬指点，哎 ，不容易呀

**Comment by liaosunny123** [comment]
> 临时恢复方案,下载https://github.com/MTmin/go-cqhttp/actions/runs/5971849526 这个版本 然后 在/data/versions里面新建一个4.json把以下内容塞进去 { "apk_id": "com.tencent.qidian", "app_id": 537061587, "sub_app_id": 537036590, "app_key": "1CV185J6EU1UW3R7", "sort_version_name": "5.8.0", "build_time": 1630062176, "apk_sign": "314cf9fe7ec66d89608f766679a710b5", "sdk_version": "6.0.0.2484", "sso_version": 18, "misc_bitmap": 184024956, "main_sig_map": 34869472, "sub_sig_map": 66560, "dump_time": 1683193286, "protocol_type": 4 }
> 
> 启动机器人即可,抱一丝好友列表获取不到所以我注释掉了编译了一个版本先用着,后续看看大佬们有没有新的方案

目前这个方案是把好友列表的注释了吗？看起来是好友获取这块的协议换了？https://github.com/Mrs4s/go-cqhttp/issues/2369

**Comment by MTmin** [comment]
> 

是的,好友列表我暂时用不上来着,我就没怎么看直接注释了

**Comment by freezingWu** [comment]
![b25bcb39adef57a342e298fad623c90](https://github.com/Mrs4s/go-cqhttp/assets/18193979/79179c76-41b7-4119-a51b-4d610119900d)
临时方案目前可行。
![image](https://github.com/Mrs4s/go-cqhttp/assets/18193979/09e76d1c-6999-4b64-820b-f1f2f4495746)
相关位置我也贴一下。

**Comment by liaosunny123** [comment]
> > 
> 
> 是的,好友列表我暂时用不上来着,我就没怎么看直接注释了

这个临时的协议文件似乎也没有解决问题，在内部debug一下的话发现还是5.0.0
![image](https://github.com/Mrs4s/go-cqhttp/assets/30096937/94c7b76d-4ddb-47e3-9eba-e24b6ce825a3)

**Comment by kkgg0521** [comment]
> > > 
> > 
> > 
> > 是的,好友列表我暂时用不上来着,我就没怎么看直接注释了
> 
> 这个临时的协议文件似乎也没有解决问题，在内部debug一下的话发现还是5.0.0 ![image](https://user-images.githubusercontent.com/30096937/263173181-94c7b76d-4ddb-47e3-9eba-e24b6ce825a3.png)

这个方案我上去了 还存在其他问题吗

**Comment by MTmin** [comment]
> > > 
> > 
> > 
> > 是的,好友列表我暂时用不上来着,我就没怎么看直接注释了
> 
> 这个临时的协议文件似乎也没有解决问题，在内部debug一下的话发现还是5.0.0 ![image](https://user-images.githubusercontent.com/30096937/263173181-94c7b76d-4ddb-47e3-9eba-e24b6ce825a3.png)

版本号是我随便写的来着...实际上这个版本是可以登陆的,只是临时的解决方案,具体还得等大佬们

**Comment by kkgg0521** [comment]
> > > > 
> > > 
> > > 
> > > 是的,好友列表我暂时用不上来着,我就没怎么看直接注释了
> > 
> > 
> > 这个临时的协议文件似乎也没有解决问题，在内部debug一下的话发现还是5.0.0 ![image](https://user-images.githubusercontent.com/30096937/263173181-94c7b76d-4ddb-47e3-9eba-e24b6ce825a3.png)
> 
> 版本号是我随便写的来着...实际上这个版本是可以登陆的,只是临时的解决方案,具体还得等大佬们

可以的 能先应付上就行

**Comment by MTmin** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 是的,好友列表我暂时用不上来着,我就没怎么看直接注释了
> > > 
> > > 
> > > 这个临时的协议文件似乎也没有解决问题，在内部debug一下的话发现还是5.0.0 ![image](https://user-images.githubusercontent.com/30096937/263173181-94c7b76d-4ddb-47e3-9eba-e24b6ce825a3.png)
> > 
> > 
> > 版本号是我随便写的来着...实际上这个版本是可以登陆的,只是临时的解决方案,具体还得等大佬们
> 
> 可以的 能先应付上就行

极度应付.jpg

**Comment by Patricia-email** [comment]
> 66560

请教一下你这个json 内容是怎么获取？ 很nice

**Comment by leoguan88** [comment]
登录成功了，但收到一条群消息后，就自动退出了，没有任何日志

**Comment by freezingWu** [comment]
经过验测，只有appId是需要强制赋值的，"app_id": 537061587,  可以在device结构中填写即可, 4.json中的其他字段可以不要。然后，这个appid应该是一个范围值，比如53706158[1-9](这是正则写法)。

**Comment by Sam5440** [comment]
各位可以加群来讨论一下 ，群号：891637894
