### ISSUE TITLE
[Bug] 无法进行踢人操作: 

### ISSUE THREAD

**Issue by B1397KB** [Mrs4s/go-cqhttp#2380]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.1.0-dev-0cd156a

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

6 | aPad

### 重现步骤

调用http://127.0.0.1:5700/set_group_kick?group_id=group_id&user_id=user_id
时, 未能正确踢出用户
登录的bot账号确认为管理员, 被踢出用户确认为非管理员.
使用禁言, 可以正常禁言该用户.
api返回结果
{"data":null,"message":"","retcode":0,"status":"ok"}

### 期望的结果是什么？

正常踢出用户

### 实际的结果是什么？

未能踢出用户

**Comment by rhwong** [comment]
建议先去Action里换新版本尝试一下

**Comment by B1397KB** [comment]
已经解决, 问题是批量踢人的时候没有时间间隔, 导致风控, 加上一个冷却就可以了
