### ISSUE TITLE
[Bug]: 签名数据库频繁掉线

### ISSUE THREAD

**Issue by Cintser** [Mrs4s/go-cqhttp#2383]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.1.0

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

WebSocket (反向)

### 使用协议

6 | aPad

### 重现步骤

这是我用的gocq版本之类的信息
![image](https://github.com/Mrs4s/go-cqhttp/assets/98868806/46bf4625-6955-4341-abc9-ccaae6bc42c4)
照常运行gocq、bot、unidbg，不久后unidbg的窗口就没了，机器人也发不了消息，如果这时候再运行一次unidbg就能恢复正常

### 期望的结果是什么？

请问有什么办法能在签名数据库挂掉的时候自动恢复吗，或者让他不会挂掉

### 实际的结果是什么？

unidbg一天掉两三次
![}51YRC_ FL$N48_KQ1N2(C4](https://github.com/Mrs4s/go-cqhttp/assets/98868806/6764fbf3-4e8c-4287-a4f8-8c5593fac727)

**Comment by rhwong** [comment]
签名数据库是啥。。
然后
![image](https://github.com/Mrs4s/go-cqhttp/assets/58497504/1d63185b-7aba-43f5-aad9-9314e2ed7721)

**Comment by xiangxiangxiong9** [comment]
> 签名数据库是啥。。 然后 ![image](https://user-images.githubusercontent.com/58497504/261311560-1d63185b-7aba-43f5-aad9-9314e2ed7721.png)

估计是 [unidbg-fetch-qsign](https://github.com/fuqiuluo/unidbg-fetch-qsign)
