### ISSUE TITLE
[Bug]: 自定义音乐 没有播放按钮

### ISSUE THREAD

**Issue by kirbystudy** [Mrs4s/go-cqhttp#2387]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.1.0

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

WebSocket (正向)

### 使用协议

6 | aPad

### 重现步骤

音乐自定义分享发送后卡片是显示出来，但是没有显示播放按钮。

### 期望的结果是什么？

显示播放按钮，可以进行播放音乐。

### 实际的结果是什么？

不能播放音乐，没有显示播放按钮。

### 简单的复现代码/链接（可选）

```golang
[CQ:music,type=custom,url=//music.163.com/outchain/player?type=3&id=2526948508,audio=//music.163.com/outchain/player?type=3&id=2526948508,title=眩耀夜行,image=https://p1.music.126.net/GAKq_Rj5CYTSWQVZR_X3BA==/109951168796790378.jpg,subtype=163]
```

**Comment by lgc2333** [comment]
Duplicate https://github.com/Mrs4s/go-cqhttp/issues/2026#issuecomment-1487817315
