### ISSUE TITLE
上报数据失败，提示信息 EOF

### ISSUE THREAD

**Issue by Shigma** [Mrs4s/go-cqhttp#239]
**环境信息**

- go-cqhttp 版本: v0.9.22
- 运行环境: windows_amd64
- 连接方式: HTTP

**Bug 内容**

```
[WARNING]: 上报Event数据到 http://127.0.0.1:7070/event 失败: Post "http://127.0.0.1:7070/event": EOF
```

同时在客户端会报错 Socket Hang Up（废话）。

**复现方法**

很惭愧目前没有找到稳定复现方法，这个报错出现频率大概是每天 10 条，每天接收信息在 100000 这个量级，所以是一个低概率但是高频率的 bug。

PS：过去使用 CQHTTP 时看不到客户端报错，由此猜测是由于 go-cqhttp 而不是客户端导致的。

**Comment by shitianshiwa** [comment]
go-cqhttp 版本: v0.9.23 也偶尔会出现，原因不明

**Comment by rbameto** [comment]
如果你的配置文件里反向ws地址为
http://127.0.0.1:7070/ws/
那么配置文件里event地址应该为
http://127.0.0.1:7070/ws/event/
api同理

**Comment by Shigma** [comment]
> 如果你的配置文件里反向ws地址为
> http://127.0.0.1:7070/ws/
> 那么配置文件里event地址应该为
> http://127.0.0.1:7070/ws/event/
> api同理

老哥这是 http，而且我能正常使用就已经说明我配置没错了。

**Comment by Shigma** [comment]
![image](https://user-images.githubusercontent.com/33423008/94842909-862d2d80-044e-11eb-99af-7cdd713acd78.png)

v0.9.24-fix2 升级以后感觉报错反而变多了。

**Comment by Mrs4s** [comment]
> ![image](https://user-images.githubusercontent.com/33423008/94842909-862d2d80-044e-11eb-99af-7cdd713acd78.png)
> 
> v0.9.24-fix2 升级以后感觉报错反而变多了。

建议更新到最新版，这个是TX服务器爆炸

**Comment by 1505494529** [comment]
我的解决办法是在你这边5701端口的服务的最后固定做一个向5700端口的get请求，我用的node.js：axios.get('http://127.0.0.1:5700/')
但我并不明白不报错的原理，当我用
axios.get(’http://127.0.0.1:5700/‘).then(res=>console.log(res.data)
输出response的时候输出为
{
data: null,
msg: 'API_NOT_FOUND',
retcode: 404,
status: 'failed',
wording: 'API不存在'
}
好像就是一个失败的请求，但上报失败的提示就奇迹般的没了
