### ISSUE TITLE
[Bug]: dev 版本无法获取群荣誉信息，get_group_honor_info 接口返回空结果

### ISSUE THREAD

**Issue by 1umine** [Mrs4s/go-cqhttp#2390]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

5db03c7

### 运行环境

Windows (64)

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

WebSocket (反向)

### 使用协议

6 | aPad

### 重现步骤

使用 5db03c7 或以上版本
请求API: `/get_group_honor_info?group_id=666666&type=all`

### 期望的结果是什么？

正常获取群荣誉信息列表

### 实际的结果是什么？

所有结果均为空，data 仅包含群号字段，请求前群内已经产生了荣誉信息，如龙王等
```json
{
  "data": {
    "group_id": 6666666
  },
  "message": "",
  "retcode": 0,
  "status": "ok"
}
```

### 简单的复现代码/链接（可选）

```golang
见重现步骤
```

### 补充说明（可选）

这个获取不到荣誉信息的 bug 好像是在 7月28日 出现的 ，7.27 以及之前是可以正常获取的。
除此之外，似乎自 8.1 更新后日志经常出现 `一条消息最多包含一条reply元素` 这样的警告，在收到带有回复的消息时就有不小的概率发生。

**Comment by xiangxiangxiong9** [comment]
那个 _[WARNING]: 警告: 一条信息只能包含一个 Reply 元素._ 是我的锅 😢  #2397 0.0

好像获取群荣誉的JSON解析出问题了[MiraiGo侧] [tx对结果进行了一些改变...?]
https://github.com/Mrs4s/MiraiGo/blob/e4b6dc62fd76d8220d6681acff43fefb2c755547/client/http_api.go#L62-L75

好像多了个
;(function(){var s;(s=document.currentScript||document.scripts[document.scripts.length-1]).parentNode.removeChild(s);}());

**Comment by 1umine** [comment]
了解了

**Comment by 1umine** [comment]
已解决
