### ISSUE TITLE
[Bug]: 无法接收群聊消息

### ISSUE THREAD

**Issue by yufengya0420** [Mrs4s/go-cqhttp#2392]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.1.0-dev-0cd156a

### 运行环境

Windows (64)

### 运行架构

x86

### 连接方式

WebSocket (正向)

### 使用协议

5 | iPad

### 重现步骤

启动gocq，启动bds服务器

### 期望的结果是什么？

机器人正常接收消息并做出反应

### 实际的结果是什么？

机器人只能发送消息无法接收消息

**Comment by yufengya0420** [comment]
![5N{(YJ4N }~7{I27)`G620D](https://github.com/Mrs4s/go-cqhttp/assets/99462074/b498433d-2e84-45a8-96cc-8e75e15cfd8b)

**Comment by yufengya0420** [comment]
![4JV H%A5{C PL 08}SR_9DW](https://github.com/Mrs4s/go-cqhttp/assets/99462074/27d7998c-f1ee-4ad4-96ff-ad21d6aa8f24)

**Comment by yufengya0420** [comment]
![image](https://github.com/Mrs4s/go-cqhttp/assets/99462074/1111e9d8-4ed3-4099-9304-dc3151df25f4)

**Comment by yufengya0420** [comment]
serein的正则都不生效

**Comment by wxkj123** [comment]
我也遇到了相同的问题，不过是猫猫实例，无法接收群消息。使用的是mirai。

**Comment by yufengya0420** [comment]
> 
好像还真是 我之前开了免打扰忘了这回事了
