### ISSUE TITLE
配置qqsign签名服务器后仍错误码：45

### ISSUE THREAD

**Issue by ouhuangoaa** [Mrs4s/go-cqhttp#2398]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.1.0

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

1 | Android Phone

### 重现步骤

使用1.1.0 qqsign签名服务器签名后，启动gocqhttp

### 期望的结果是什么？

[2023-08-22 17:02:20] [INFO]: 当前版本:v1.1.0
[2023-08-22 17:02:20] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2023-08-22 17:02:20] [INFO]: 使用服务器 http://127.0.0.1:13579 进行数据包签名
[2023-08-22 17:02:20] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2023-08-22 17:02:25] [INFO]: 开始尝试登录并同步消息...
[2023-08-22 17:02:25] [INFO]: 使用协议: Android Phone 8.9.63.11390
[2023-08-22 17:02:25] [INFO]: 正在检查协议更新...
[2023-08-22 17:02:31] [INFO]: Protocol -> connect to server: 111.206.149.168:8080
[2023-08-22 17:02:35] [WARNING]: 登录需要滑条验证码, 请验证后重试.
[2023-08-22 17:02:35] [WARNING]: 请选择提交滑块ticket方式:
[2023-08-22 17:02:35] [WARNING]: 1. 自动提交
[2023-08-22 17:02:35] [WARNING]: 2. 手动抓取提交
[2023-08-22 17:02:35] [WARNING]: 请输入(1 - 2)：
1
[2023-08-22 17:02:37] [WARNING]: 请前往该地址验证 -> https://captcha.go-cqhttp.org/captcha?id=JsXkWZpU&style=simple&aid=16&uin=3655133085&sid=8281645925699713450&cap_cd=nPcjNkr0lbBnlaVhRzqNifDICyXYoLXvNK_Bd12YKVAjI8-rEhn23g**&clientype=1&apptype=2
[2023-08-22 17:02:55] [WARNING]: 登录成功

### 实际的结果是什么？

[2023-08-22 17:02:20] [INFO]: 当前版本:v1.1.0
[2023-08-22 17:02:20] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2023-08-22 17:02:20] [INFO]: 使用服务器 http://127.0.0.1:13579 进行数据包签名
[2023-08-22 17:02:20] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2023-08-22 17:02:25] [INFO]: 开始尝试登录并同步消息...
[2023-08-22 17:02:25] [INFO]: 使用协议: Android Phone 8.9.63.11390
[2023-08-22 17:02:25] [INFO]: 正在检查协议更新...
[2023-08-22 17:02:31] [INFO]: Protocol -> connect to server: 111.206.149.168:8080
[2023-08-22 17:02:35] [WARNING]: 登录需要滑条验证码, 请验证后重试.
[2023-08-22 17:02:35] [WARNING]: 请选择提交滑块ticket方式:
[2023-08-22 17:02:35] [WARNING]: 1. 自动提交
[2023-08-22 17:02:35] [WARNING]: 2. 手动抓取提交
[2023-08-22 17:02:35] [WARNING]: 请输入(1 - 2)：
1
[2023-08-22 17:02:37] [WARNING]: 请前往该地址验证 -> https://captcha.go-cqhttp.org/captcha?id=JsXkWZpU&style=simple&aid=16&uin=3655133085&sid=8281645925699713450&cap_cd=nPcjNkr0lbBnlaVhRzqNifDICyXYoLXvNK_Bd12YKVAjI8-rEhn23g**&clientype=1&apptype=2
[2023-08-22 17:02:55] [WARNING]: 登录失败: 你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。 Code: 45
[2023-08-22 17:02:55] [WARNING]: 你的账号被限制登录, 请配置 SignServer 后重试
[2023-08-22 17:02:55] [INFO]: 按 Enter 继续....

以下为qqsign：
Qsign API:http://127.0.0.1:13579
Qsign_version:1.1.0 TXlib_version:8.9.63 Android_id=bd6da53c8d071c68

**Comment by YumeMichi** [comment]
具体可以看一下discussion
https://github.com/Mrs4s/go-cqhttp/discussions/2245

**Comment by ouhuangoaa** [comment]
> qsign版本太低了吧，我这里用1.1.7，协议8.9.63是正常的。

换成1.1.7报错获取T544 sign时出现错误: encoding/hex: invalid byte: U+0069 'i'

**Comment by ouhuangoaa** [comment]
换成了1.1.0 dev gocq也报错45
[2023-08-22 17:56:38] [INFO]: 当前版本:bff4970
[2023-08-22 17:56:38] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2023-08-22 17:56:38] [INFO]: 使用服务器 http://127.0.0.1:13579 进行数据包签名
[2023-08-22 17:56:44] [INFO]: 连接至签名服务器: http://127.0.0.1:13579
[2023-08-22 17:56:57] [INFO]: 注册QQ实例 3648453201 成功: Instance loaded successfully.
[2023-08-22 17:56:57] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2023-08-22 17:56:57] [INFO]: 每 40 分钟将刷新一次签名 token
[2023-08-22 17:57:02] [INFO]: 开始尝试登录并同步消息...
[2023-08-22 17:57:02] [INFO]: 使用协议: Android Phone 8.9.63.11390
[2023-08-22 17:57:02] [INFO]: 正在检查协议更新...
[2023-08-22 17:57:04] [INFO]: Protocol -> connect to server: 123.125.0.195:8080
[2023-08-22 17:57:07] [INFO]: token 已更新： -> 634831384b4d477a71506976
[2023-08-22 17:57:07] [WARNING]: 登录需要滑条验证码, 请验证后重试.
[2023-08-22 17:57:07] [WARNING]: 请选择提交滑块ticket方式:
[2023-08-22 17:57:07] [WARNING]: 1. 自动提交
[2023-08-22 17:57:07] [WARNING]: 2. 手动抓取提交
[2023-08-22 17:57:07] [WARNING]: 请输入(1 - 2)：
[2023-08-22 17:57:07] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10005
1
[2023-08-22 17:57:09] [WARNING]: 请前往该地址验证 -> https://captcha.go-cqhttp.org/captcha?id=tHFg872h&style=simple&aid=16&uin=3648453201&sid=3224859673155110515&cap_cd=dalbW9pF-xLuyAWIvazIst8vNfxnyuHTwvunF0Mypl9N-OdbS3y2Zw**&clientype=1&apptype=2
[2023-08-22 17:57:22] [WARNING]: Callback error: Packet timed out, Or response data is empty
[2023-08-22 17:57:23] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10005
[2023-08-22 17:57:27] [WARNING]: 登录失败: 你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。 Code: 45
[2023-08-22 17:57:27] [WARNING]: 你的账号被限制登录, 请配置 SignServer 后重试
[2023-08-22 17:57:27] [INFO]: 按 Enter 继续....
[2023-08-22 17:57:38] [WARNING]: Callback error: Packet timed out, Or response data is empty

**Comment by duoduoduoduomicang** [comment]
> 一开始使用gocq登录，报错45，配置qsign后问题解决，一个小时左右被强制踢下线，再次报错45

我想请教下怎么配置 qsign

**Comment by rhwong** [comment]
> 

https://github.com/rhwong/unidbg-fetch-qsign-onekey/tree/test-1.1.7b2-go-cqhttp-x86

**Comment by rhwong** [comment]
> > 一开始使用gocq登录，报错45，配置qsign后问题解决，一个小时左右被强制踢下线，再次报错45
> 
> 我想请教下怎么配置 qsign
https://github.com/rhwong/unidbg-fetch-qsign-onekey/tree/test-1.1.7b2-go-cqhttp-x86

**Comment by geekzhu001** [comment]
> > qsign版本太低了吧，我这里用1.1.7，协议8.9.63是正常的。
> 
> 换成1.1.7报错获取T544 sign时出现错误: encoding/hex: invalid byte: U+0069 'i'

请问你解决这个问题了吗

**Comment by LynxCatTheThird** [comment]
> > qsign版本太低了吧，我这里用1.1.7，协议8.9.63是正常的。
> 
> 换成1.1.7报错获取T544 sign时出现错误: encoding/hex: invalid byte: U+0069 'i'

请查看有关密码的配置项，确认各处密码是否对应

**Comment by clpluie** [comment]
> 
用这个试试
https://github.com/1umine/go-cqhttp/actions/runs/5861714722

**Comment by MRSlouzk** [comment]
> 

我也是这个问题

**Comment by MRSlouzk** [comment]
> 换成了1.1.0 dev gocq也报错45 [2023-08-22 17:56:38] [INFO]: 当前版本:bff4970 [2023-08-22 17:56:38] [INFO]: 将使用 device.json 内的设备信息运行Bot. [2023-08-22 17:56:38] [INFO]: 使用服务器 http://127.0.0.1:13579 进行数据包签名 [2023-08-22 17:56:44] [INFO]: 连接至签名服务器: http://127.0.0.1:13579 [2023-08-22 17:56:57] [INFO]: 注册QQ实例 3648453201 成功: Instance loaded successfully. [2023-08-22 17:56:57] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. [2023-08-22 17:56:57] [INFO]: 每 40 分钟将刷新一次签名 token [2023-08-22 17:57:02] [INFO]: 开始尝试登录并同步消息... [2023-08-22 17:57:02] [INFO]: 使用协议: Android Phone 8.9.63.11390 [2023-08-22 17:57:02] [INFO]: 正在检查协议更新... [2023-08-22 17:57:04] [INFO]: Protocol -> connect to server: 123.125.0.195:8080 [2023-08-22 17:57:07] [INFO]: token 已更新： -> 634831384b4d477a71506976 [2023-08-22 17:57:07] [WARNING]: 登录需要滑条验证码, 请验证后重试. [2023-08-22 17:57:07] [WARNING]: 请选择提交滑块ticket方式: [2023-08-22 17:57:07] [WARNING]: 1. 自动提交 [2023-08-22 17:57:07] [WARNING]: 2. 手动抓取提交 [2023-08-22 17:57:07] [WARNING]: 请输入(1 - 2)： [2023-08-22 17:57:07] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10005 1 [2023-08-22 17:57:09] [WARNING]: 请前往该地址验证 -> https://captcha.go-cqhttp.org/captcha?id=tHFg872h&style=simple&aid=16&uin=3648453201&sid=3224859673155110515&cap_cd=dalbW9pF-xLuyAWIvazIst8vNfxnyuHTwvunF0Mypl9N-OdbS3y2Zw**&clientype=1&apptype=2 [2023-08-22 17:57:22] [WARNING]: Callback error: Packet timed out, Or response data is empty [2023-08-22 17:57:23] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10005 [2023-08-22 17:57:27] [WARNING]: 登录失败: 你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。 Code: 45 [2023-08-22 17:57:27] [WARNING]: 你的账号被限制登录, 请配置 SignServer 后重试 [2023-08-22 17:57:27] [INFO]: 按 Enter 继续.... [2023-08-22 17:57:38] [WARNING]: Callback error: Packet timed out, Or response data is empty

我也是这个问题

**Comment by q-sue** [comment]
45这种只有轻度违规才能解决，多次违规无解的

**Comment by ReiRzior** [comment]
![image](https://github.com/Mrs4s/go-cqhttp/assets/109207706/98189e28-b23a-4504-96ad-2e228d2da995)
成功解决了，用[rhwong](https://github.com/rhwong)大佬的Onekey仓库可以运行，蟹蟹!

**Comment by q-sue** [comment]
没有，换了个qq（风控次数少的）秒好，初步判断是号风控次数太多，即使用了dev和新版sign也无解

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Sh3nha1 ***@***.***&gt;
发送时间: 2023年9月12日 02:13
收件人: Mrs4s/go-cqhttp ***@***.***&gt;
抄送: q-sue ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Mrs4s/go-cqhttp] 配置qqsign签名服务器后仍错误码：45 (Issue #2398)





 
请问解决了吗？我也这样了

**Comment by Sh3nha1** [comment]
我已解决，解决办法，更换8.9.71协议

**Comment by q-sue** [comment]
这个协议不是go-cq运行的时候自动选择的吗，怎么更改他，我用的dev版



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Sh3nha1 ***@***.***&gt;
发送时间: 2023年9月13日 00:35
收件人: Mrs4s/go-cqhttp ***@***.***&gt;
抄送: q-sue ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Mrs4s/go-cqhttp] 配置qqsign签名服务器后仍错误码：45 (Issue #2398)





 
我已解决，解决办法，更换8.9.71协议

**Comment by Sh3nha1** [comment]
https://github.com/Mrs4s/go-cqhttp/issues/2404

**Comment by jerAx-cn** [comment]
可以试试把config.yml里account.use-sso-address改为false。我也是同样情况，改完就不报45了。

**Comment by buse88** [comment]
求个大神直接弄个现成能用的go-cqhttp（linux用）跟qqsign对应版本(docker版)让小白对应版本进行搭建

**Comment by changwenpeng** [comment]
> 求个大神直接弄个现成能用的go-cqhttp（linux用）跟qqsign对应版本（docker版）让小白对应版本进行搭建

看这里，我整理好了最新可用的
https://gitee.com/changwenpeng/gocqhttp-qqsign

**Comment by ReiRzior** [comment]
> ![image](https://user-images.githubusercontent.com/109207706/267194624-98189e28-b23a-4504-96ad-2e228d2da995.png) 成功解决了，用[rhwong](https://github.com/rhwong)大佬的Onekey仓库可以运行，蟹蟹!

9月22日反馈，bot还没被风控，舒服了

**Comment by Badistricia** [comment]
不论是用其他人的签名服务器还是自己的，都会出45，但是也和经常冻结有关？我自己的大号可以直接登录就是了，用了这位的方法后，小号现在也不45可以正常使用了，谢谢大佬们 [[ainio-lv](https://github.com/ainio-lv)](https://github.com/Mrs4s/go-cqhttp/issues/2398#issuecomment-1727714016)

**Comment by intling-luo** [comment]
换了8.9.71协议，完美结局

**Comment by buse88** [comment]
> 换了8.9.71协议，完美解决

用的是哪个版本的go-cq呢

**Comment by intling-luo** [comment]
> > 求个大神直接弄个现成能用的go-cqhttp（linux用）跟qqsign对应版本（docker版）让小白对应版本进行搭建
> 
> 看这里，我整理好了最新可用的 qqsign v1.1.9   gocqhttp dev版本 windows和linux
> https://gitee.com/changwenpeng/gocqhttp-qqsign
> 

用的是这位大佬的新版本gocq

**Comment by q-sue** [comment]
stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
stderr: 	at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:119)
stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
stderr: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
stderr: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
stderr: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
stderr: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
stderr: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:37)
stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:29)
stderr: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
stderr: 	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
stderr: 	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)
stderr: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
stderr: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
stderr: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
stderr: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
stderr: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
stderr: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
stderr: 	at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
stderr: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
stderr: 	at java.lang.Thread.run(Thread.java:750)
大佬们看看这是怎么回事，qsign总是这样


运行一段时间就出错，重启就正常
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ling ***@***.***&gt;
发送时间: 2023年10月1日 13:41
收件人: Mrs4s/go-cqhttp ***@***.***&gt;
抄送: q-sue ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Mrs4s/go-cqhttp] 配置qqsign签名服务器后仍错误码：45 (Issue #2398)





   
求个大神直接弄个现成能用的go-cqhttp（linux用）跟qqsign对应版本（docker版）让小白对应版本进行搭建
  
看这里，我整理好了最新可用的 qqsign v1.1.9   gocqhttp dev版本 windows和linux
 https://gitee.com/changwenpeng/gocqhttp-qqsign
  
用的是这位大佬的新版本gocq

**Comment by jiangyin14** [comment]
> stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
> 
> stderr: 	at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
> 
> stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:119)
> 
> stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
> 
> stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
> 
> stderr: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
> 
> stderr: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
> 
> stderr: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
> 
> stderr: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
> 
> stderr: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
> 
> stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:37)
> 
> stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:29)
> 
> stderr: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
> 
> stderr: 	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
> 
> stderr: 	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)
> 
> stderr: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
> 
> stderr: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
> 
> stderr: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
> 
> stderr: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
> 
> stderr: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
> 
> stderr: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 
> stderr: 	at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
> 
> stderr: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 
> stderr: 	at java.lang.Thread.run(Thread.java:750)
> 
> 大佬们看看这是怎么回事，qsign总是这样
> 
> 
> 
> 
> 
> 运行一段时间就出错，重启就正常
> 
> 发自我的iPhone
> 
> 
> 
> 
> 
> ------------------ 原始邮件 ------------------
> 
> 发件人: ling ***@***.***&gt;
> 
> 发送时间: 2023年10月1日 13:41
> 
> 收件人: Mrs4s/go-cqhttp ***@***.***&gt;
> 
> 抄送: q-sue ***@***.***&gt;, Comment ***@***.***&gt;
> 
> 主题: Re: [Mrs4s/go-cqhttp] 配置qqsign签名服务器后仍错误码：45 (Issue #2398)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>    
> 
> 求个大神直接弄个现成能用的go-cqhttp（linux用）跟qqsign对应版本（docker版）让小白对应版本进行搭建
> 
>   
> 
> 看这里，我整理好了最新可用的 qqsign v1.1.9   gocqhttp dev版本 windows和linux
> 
>  https://gitee.com/changwenpeng/gocqhttp-qqsign
> 
>   
> 
> 用的是这位大佬的新版本gocq
> 
>  
> 
> —
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> You are receiving this because you commented.Message ID: ***@***.***&gt;

用别人的服务吧 自己搞怪费劲的

**Comment by q-sue** [comment]
已经排查出问题了，是cqhttp的定时40分钟刷新token的问题，一到40分钟就会刷新失败，然后死了，这个东西能关吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jiangyin14 ***@***.***&gt;
发送时间: 2023年10月2日 11:49
收件人: Mrs4s/go-cqhttp ***@***.***&gt;
抄送: q-sue ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Mrs4s/go-cqhttp] 配置qqsign签名服务器后仍错误码：45 (Issue #2398)





  
stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
 
stderr: 	at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
 
stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:119)
 
stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
 
stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
 
stderr: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
 
stderr: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
 
stderr: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
 
stderr: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
 
stderr: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
 
stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:37)
 
stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:29)
 
stderr: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
 
stderr: 	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
 
stderr: 	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)
 
stderr: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
 
stderr: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
 
stderr: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
 
stderr: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
 
stderr: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
 
stderr: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 
stderr: 	at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
 
stderr: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 
stderr: 	at java.lang.Thread.run(Thread.java:750)
 
大佬们看看这是怎么回事，qsign总是这样
 
运行一段时间就出错，重启就正常
 
发自我的iPhone
 
------------------ 原始邮件 ------------------
 
发件人: ling @.***&gt;
 
发送时间: 2023年10月1日 13:41
 
收件人: Mrs4s/go-cqhttp @.***&gt;
 
抄送: q-sue @.&gt;, Comment @.&gt;
 
主题: Re: [Mrs4s/go-cqhttp] 配置qqsign签名服务器后仍错误码：45 (Issue #2398)
 
求个大神直接弄个现成能用的go-cqhttp（linux用）跟qqsign对应版本（docker版）让小白对应版本进行搭建
 
看这里，我整理好了最新可用的 qqsign v1.1.9   gocqhttp dev版本 windows和linux
 
https://gitee.com/changwenpeng/gocqhttp-qqsign
 
用的是这位大佬的新版本gocq
 
—
 
Reply to this email directly, view it on GitHub, or unsubscribe.
 
You are receiving this because you commented.Message ID: @.***&gt;
  
用别人的服务吧 自己搞怪费劲的

**Comment by jiangyin14** [comment]
> 已经排查出问题了，是cqhttp的定时40分钟刷新token的问题，一到40分钟就会刷新失败，然后死了，这个东西能关吗
> 
> 
> 
> 
> 
> 
> 
> 发自我的iPhone
> 
> 
> 
> 
> 
> ------------------ 原始邮件 ------------------
> 
> 发件人: jiangyin14 ***@***.***&gt;
> 
> 发送时间: 2023年10月2日 11:49
> 
> 收件人: Mrs4s/go-cqhttp ***@***.***&gt;
> 
> 抄送: q-sue ***@***.***&gt;, Comment ***@***.***&gt;
> 
> 主题: Re: [Mrs4s/go-cqhttp] 配置qqsign签名服务器后仍错误码：45 (Issue #2398)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>   
> 
> stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
> 
>  
> 
> stderr: 	at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
> 
>  
> 
> stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:119)
> 
>  
> 
> stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
> 
>  
> 
> stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
> 
>  
> 
> stderr: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
> 
>  
> 
> stderr: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
> 
>  
> 
> stderr: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
> 
>  
> 
> stderr: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
> 
>  
> 
> stderr: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
> 
>  
> 
> stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:37)
> 
>  
> 
> stderr: 	at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:29)
> 
>  
> 
> stderr: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
> 
>  
> 
> stderr: 	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
> 
>  
> 
> stderr: 	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)
> 
>  
> 
> stderr: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
> 
>  
> 
> stderr: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
> 
>  
> 
> stderr: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
> 
>  
> 
> stderr: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
> 
>  
> 
> stderr: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
> 
>  
> 
> stderr: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 
>  
> 
> stderr: 	at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
> 
>  
> 
> stderr: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 
>  
> 
> stderr: 	at java.lang.Thread.run(Thread.java:750)
> 
>  
> 
> 大佬们看看这是怎么回事，qsign总是这样
> 
>  
> 
> 运行一段时间就出错，重启就正常
> 
>  
> 
> 发自我的iPhone
> 
>  
> 
> ------------------ 原始邮件 ------------------
> 
>  
> 
> 发件人: ling @.***&gt;
> 
>  
> 
> 发送时间: 2023年10月1日 13:41
> 
>  
> 
> 收件人: Mrs4s/go-cqhttp @.***&gt;
> 
>  
> 
> 抄送: q-sue @.&gt;, Comment @.&gt;
> 
>  
> 
> 主题: Re: [Mrs4s/go-cqhttp] 配置qqsign签名服务器后仍错误码：45 (Issue #2398)
> 
>  
> 
> 求个大神直接弄个现成能用的go-cqhttp（linux用）跟qqsign对应版本（docker版）让小白对应版本进行搭建
> 
>  
> 
> 看这里，我整理好了最新可用的 qqsign v1.1.9   gocqhttp dev版本 windows和linux
> 
>  
> 
> https://gitee.com/changwenpeng/gocqhttp-qqsign
> 
>  
> 
> 用的是这位大佬的新版本gocq
> 
>  
> 
> —
> 
>  
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
>  
> 
> You are receiving this because you commented.Message ID: @.***&gt;
> 
>   
> 
> 用别人的服务吧 自己搞怪费劲的
> 
>  
> 
> —
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> You are receiving this because you commented.Message ID: ***@***.***&gt;

我记得SignServer端可以调整
