### ISSUE TITLE
群消息发送失败，账号可能被风控

### ISSUE THREAD

**Issue by d7185540** [Mrs4s/go-cqhttp#240]
[2020-09-05.log](https://github.com/Mrs4s/go-cqhttp/files/5177449/2020-09-05.log)
[device.txt](https://github.com/Mrs4s/go-cqhttp/files/5177450/device.txt)

**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.23
运行环境: windows_amd64
连接方式: WS

**bug内容**
到了凌晨，机器人能接受信息，但不能发送信息。修改了device.json文件。

**复现方法**
挂机时间一久就会出现

**Comment by Ink-33** [comment]
#211
