### ISSUE TITLE
[Bug]: 苹果电脑发送的图片的链接无法被打开，会出现400

### ISSUE THREAD

**Issue by Thexiaoyuqaq** [Mrs4s/go-cqhttp#2401]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.1.0

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

5 | iPad

### 重现步骤

当Mac成员发送图片，从gocq获取的图片链接是一个400无法打开的图片，而安卓和windows电脑的发送的可以正常打开

### 期望的结果是什么？

打开后是图片

### 实际的结果是什么？

打开后出现400 无法加载

### 日志记录（可选）

```golang
2023-08-23 13:33:56 [信息] Log| [消息][群聊] <$ÿĀ>纸薄的纸箱子<$�(1138746230) [member] 安然(xxxxx333): [CQ:image,file=7ffb0b994da058bf035eab3de04ef9d0.image,subType=1,url=https://gchat.qpic.cn/download?appid=1407&amp;fileid=Cgg0MjUzMzMzMxIU6mfMXiLFj_Ry_e3wtg0FFm22k0EYrZcBIP8KKMbZ7L2H8oADUIC9owE&amp;rkey=CAQSMAB6JWENi5LMDLhWMDG_ec9qsFcicn98ThqKpZZ3-kaEK1fyCJ2Cdo-wYOvoSxH3pg&amp;spec=0] (19xxxx9304)
```

**Comment by Thexiaoyuqaq** [comment]
我在制作一个二维码识别的功能 也就是违规检测
但是由于苹果端的图片无法被打开，也无法被下载，导致无法识别苹果用户发送的图片

**Comment by 1umine** [comment]
你是不是没有转义（）
可以打开的 https://gchat.qpic.cn/download?appid=1407&fileid=Cgg0MjUzMzMzMxIU6mfMXiLFj_Ry_e3wtg0FFm22k0EYrZcBIP8KKMbZ7L2H8oADUIC9owE&rkey=CAQSMAB6JWENi5LMDLhWMDG_ec9qsFcicn98ThqKpZZ3-kaEK1fyCJ2Cdo-wYOvoSxH3pg&spec=0
![image](https://gchat.qpic.cn/download?appid=1407&fileid=Cgg0MjUzMzMzMxIU6mfMXiLFj_Ry_e3wtg0FFm22k0EYrZcBIP8KKMbZ7L2H8oADUIC9owE&rkey=CAQSMAB6JWENi5LMDLhWMDG_ec9qsFcicn98ThqKpZZ3-kaEK1fyCJ2Cdo-wYOvoSxH3pg&spec=0)

**Comment by Thexiaoyuqaq** [comment]
> ```go
> https://gchat.qpic.cn/download?appid=1407&amp;fileid=Cgg0MjUzMzMzMxIU6mfMXiLFj_Ry_e3wtg0FFm22k0EYrZcBIP8KKMbZ7L2H8oADUIC9owE&amp;rkey=CAQSMAB6JWENi5LMDLhWMDG_ec9qsFcicn98ThqKpZZ3-kaEK1fyCJ2Cdo-wYOvoSxH3pg&amp;spec=0
> ```

长知识了，谢谢
