### ISSUE TITLE
Feature: 支持QQ协议版本 8.9.73 以及 SignServer v1.1.7

### ISSUE THREAD

**Issue by itzdrli** [Mrs4s/go-cqhttp#2404]
**环境信息**

go-cqhttp版本: 1.1.0

**需要添加的功能内容**

如题，我自己的QQ号因被风控导致无法使用8.9.63版本的QQ协议（APhone & APad + sign server）, 但是同ip下可以使用官方客户端登陆APhone的 8.9.73版本，因此希望能支持下

以及 [sign server](https://github.com/fuqiuluo/unidbg-fetch-qsign) 1.1.7 已支持到协议版本8.9.73辣

**Comment by KewenCode** [comment]
用dev分支的最新release

**Comment by itzdrli** [comment]
> 用dev分支的最新release

使用dev版登陆时还是8.9.63协议，基于最新的dev代码自己编译的

**Comment by KewenCode** [comment]
> > 用dev分支的最新release
> 
> 使用dev版登陆时还是8.9.63协议，基于最新的dev代码自己编译的

目前只有dev的release支持qs1.1.7
要修改登录协议需要在data/versions下手动添加对应协议的6.json（数字为协议编号）文件，协议文件可以在[MrXiaoM/qsign](https://github.com/MrXiaoM/qsign/tree/mirai/txlib) 中获取，修改文件名就行。
还有，73加料了，容易封

**Comment by rhwong** [comment]
别用73，会死

**Comment by itzdrli** [comment]
> 别用73，会死

63+sign登陆会45啊

**Comment by KewenCode** [comment]
> > 别用73，会死
> 
> 63+sign登陆会45啊

自增70协议方法都写出来了，照方法自增一个喜欢协议不就行了……
```
[2023-08-24 15:43:53] [INFO]: 使用协议: Android Pad 8.9.63.11390 
[2023-08-24 15:43:54] [INFO]: 从文件 data/versions/6.json 读取协议版本 Android Pad 8.9.70.11635. 
```

**Comment by itzdrli** [comment]
> > > 别用73，会死
> > 
> > 
> > 63+sign登陆会45啊
> 
> 自增70协议方法都写出来了，照方法自增一个喜欢协议不就行了……
> 
> ```
> [2023-08-24 15:43:53] [INFO]: 使用协议: Android Pad 8.9.63.11390 
> [2023-08-24 15:43:54] [INFO]: 从文件 data/versions/6.json 读取协议版本 Android Pad 8.9.70.11635. 
> [2023-08-24 15:43:59] [INFO]: Protocol -> connect to server: 117.62.243.221:8080 
> [2023-08-24 15:44:04] [INFO]: 正在检查协议更新...
> [2023-08-24 15:44:05] [INFO]: 收到服务器地址更新通知, 将在下一次重连时应用.  
> [2023-08-24 15:44:14] [INFO]: 检测到协议更新: 8.9.70.11635 -> 8.9.63.11390 
> ```

用aphone 71也一样不知道为什么
![image](https://github.com/Mrs4s/go-cqhttp/assets/52338732/86f2b640-c845-486c-ae82-79d3d5564b66)

**Comment by KewenCode** [comment]
你用的这个签名服务器，Android phone是71协议吗？

**Comment by itzdrli** [comment]
> 

没事了😅，刚才修改完sign server的配置没重启，现在登上了
