### ISSUE TITLE
[Bug]: 上报的cq码数据类型和文档不一样

### ISSUE THREAD

**Issue by yuyi2439** [Mrs4s/go-cqhttp#2406]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

d85d697

### 运行环境

Linux

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

WebSocket (正向)

### 使用协议

6 | aPad

### 重现步骤

应该直接接收包含cqcode的上报就能重现

### 期望的结果是什么？

{'type': 'reply', 'data': {'id': 1053723174}}

### 实际的结果是什么？

{'type': 'reply', 'data': {'id': '1053723174'}}

### 补充说明（可选）

使用的消息类型为array
期望和实际结果的格式是python中的dict

**Comment by yuyi2439** [comment]
比如[@某人](https://docs.go-cqhttp.org/cqcode/#%E6%9F%90%E4%BA%BA)，文档里写的参数`qq`是int类型，但是实际收到的是string类型

**Comment by 1umine** [comment]
文档更新感觉有点滞后，为了适配 onebot12 ，后面 id 这种标识类的东西应该都是逐渐转成 string 了，更通用一点

**Comment by yuyi2439** [comment]
> 文档更新感觉有点滞后，为了适配 onebot12 ，后面 id 这种标识类的东西应该都是逐渐转成 string 了，更通用一点

哦

**Comment by yuyi2439** [comment]
> 文档更新感觉有点滞后，为

> 比如[@某人](https://docs.go-cqhttp.org/cqcode/#%E6%9F%90%E4%BA%BA)，文档里写的参数`qq`是int类型，但是实际收到的是string类型

才发现这个写错了，应该是：[回复](https://docs.go-cqhttp.org/cqcode/#%E5%9B%9E%E5%A4%8D)，文档里写的参数`id`是int类型，但是实际收到的是string类型
