### ISSUE TITLE
[Bug]: 对方发起的临时会话，Bot调用send_msg接口可以成功发送消息但是回调报错

### ISSUE THREAD

**Issue by Dreamail** [Mrs4s/go-cqhttp#2407]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

dev branch

### 运行环境

Linux

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

HTTP

### 使用协议

6 | aPad

### 重现步骤

用户发起临时会话，Bot调用send_msg or send_private_msg接口（不添加group_id参数），可以成功发送消息但cqhttp后台没有日志输出且ws和http回调均报错：
`
{
  "data": null,
  "message": "请参考 go-cqhttp 端输出",
  "msg": "SEND_MSG_API_ERROR",
  "retcode": 100,
  "status": "failed",
  "wording": "请参考 go-cqhttp 端输出"
}
`

### 期望的结果是什么？

有日志输出且回调不报错

### 实际的结果是什么？

cqhttp后台没有日志输出且ws和http回调均报错

**Comment by xiangxiangxiong9** [comment]
https://github.com/Mrs4s/go-cqhttp/blob/a6fd7de65a062cb8a3112dca4b3cdbca822c020b/coolq/api.go#L697-L713
https://github.com/Mrs4s/go-cqhttp/blob/a6fd7de65a062cb8a3112dca4b3cdbca822c020b/coolq/api.go#L1020-L1046
https://github.com/Mrs4s/go-cqhttp/blob/a6fd7de65a062cb8a3112dca4b3cdbca822c020b/coolq/bot.go#L313-L408

_可能是因为没实现临时对话进数据库导致没有重新赋值id，返回-1导致错误的认为消息发送失败_
https://github.com/Mrs4s/go-cqhttp/blob/a6fd7de65a062cb8a3112dca4b3cdbca822c020b/coolq/bot.go#L375-L392

**Comment by panyuQ** [comment]
我也差不多时这样，调用send_msg 或 send_private_msg接口（添加group_id，不添加message_type）发送临时消息，后台报错（{ "data": null, "message": "请参考 go-cqhttp 端输出", "msg": "SEND_MSG_API_ERROR", "retcode": 100, "status": "failed", "wording": "请参考 go-cqhttp 端输出" }），但实际却收到了

**Comment by Dreamail** [comment]
问题出在临时信息没有成功入库（
开发者那边没实现，也有可能是协议侧本身的问题
