### ISSUE TITLE
[Bug]: fd6ef4a windows amd64 登录报错

### ISSUE THREAD

**Issue by Kaguya233qwq** [Mrs4s/go-cqhttp#2409]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

fd6ef4a

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | Default

### 重现步骤

生成yml配置文件后再次点击bat运行后出错

### 期望的结果是什么？

出现正常登录流程

### 实际的结果是什么？

报错。日志截图如下：
![image](https://github.com/Mrs4s/go-cqhttp/assets/53631287/65eb1e25-9943-4da6-9a26-a3ee492e9ead)

### 补充说明（可选）

https://github.com/Mrs4s/go-cqhttp/actions/runs/5997771894

**Comment by 1umine** [comment]
用这个 commit 前一个的构建版

**Comment by Kaguya233qwq** [comment]
收到了

**Comment by Kaguya233qwq** [comment]
感谢
