### ISSUE TITLE
dev版本跟最新版的签名服务器1.1.9会出现死循环的问题[Bug]: 

### ISSUE THREAD

**Issue by foxdad** [Mrs4s/go-cqhttp#2412]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

dev:79a194fb

### 运行环境

MacOS

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

HTTP

### 使用协议

5 | iPad

### 重现步骤

在这个分支我启动链接的的签名：unidbg-fetch-qsign-1.1.9 txlib 8.9.71 与 txlib 8.9.73
都会出现
<img width="970" alt="image" src="https://github.com/Mrs4s/go-cqhttp/assets/48538835/62e31dcd-7a39-4abf-9f4f-29451720900a">
<img width="804" alt="image" src="https://github.com/Mrs4s/go-cqhttp/assets/48538835/703fad01-c941-41c8-b085-cc6f1fd17370">

签名服务端的日志会有这些输出
<img width="576" alt="image" src="https://github.com/Mrs4s/go-cqhttp/assets/48538835/39383974-43f4-403f-b361-87c9bf14f475">

签名服务链接的是  txlib 8.9.63
启动的时候就会有hex的错误
<img width="782" alt="image" src="https://github.com/Mrs4s/go-cqhttp/assets/48538835/9474ab36-0af9-4733-af40-a65106419247">
输入签名就不能登录
<img width="849" alt="image" src="https://github.com/Mrs4s/go-cqhttp/assets/48538835/ec07771a-3d46-4fbe-8f07-f922f53e97ce">
签名服务器会出现
<img width="563" alt="image" src="https://github.com/Mrs4s/go-cqhttp/assets/48538835/57066542-df41-4a61-8693-ca90a3ae1339">

### 期望的结果是什么？

希望能链接签名不报错

### 实际的结果是什么？

签名不会死循环报错

**Comment by YumeMichi** [comment]
qsign只支持安卓协议吧

**Comment by rhwong** [comment]
不支持ipad协议，建议仔细查看qsign说明。
但是这个循环获取地址的问题确实有。

**Comment by NoCryingNoTears** [comment]
我使用的1.1.9的版本，用apad协议，8.9.73也出现同上死循环，有什么解决办法吗？
