### ISSUE TITLE
[Bug]: 滑块验证地址访问提示Connection timed out Error code 522

### ISSUE THREAD

**Issue by cnchens** [Mrs4s/go-cqhttp#2413]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.1.0

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

6 | aPad

### 重现步骤

执行go-cqhttp.bat（已经在config.yml里面配置了账号密码）

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

无法打开滑块验证地址，提示Connection timed out Error code 522

![图片](https://github.com/Mrs4s/go-cqhttp/assets/116929900/52322a55-812c-44c6-a560-e6eb285555de)

### 补充说明（可选）

初步怀疑是没有ipv6的问题，在更换到带有公网ipv6的网络后仍未解决

**Comment by jx9468** [comment]
手动抓取ticket可行，暂时可以先手动获取~

**Comment by xiaopeng12138** [comment]
同样的问题

**Comment by 1umine** [comment]
gocq captcha目前估计是寄了，tx好像更新了滑块验证方式，但是gocq还没更新（？

**Comment by WindStill** [comment]
gocq captcha 寄了，手动抓取又选择不了，我机器人已经失联两天了

**Comment by 1umine** [comment]
> gocq captcha 寄了，手动抓取又选择不了，我机器人已经失联两天了

要么就先别用docker运行了，或者外面登录好再传session和device到docker里

**Comment by WindStill** [comment]
> > gocq captcha 寄了，手动抓取又选择不了，我机器人已经失联两天了
> 
> 要么就先别用docker运行了，或者外面登录好再传session和device到docker里

我最近用的两个版本 1.1和dev，好像不生产session文件了，是需要单独配置吗？

**Comment by 1umine** [comment]
好像是会产生的，我的有session.token

**Comment by xiaopeng12138** [comment]
> > gocq captcha 寄了，手动抓取又选择不了，我机器人已经失联两天了
> 
> 要么就先别用docker运行了，或者外面登录好再传session和device到docker里

我目前就是在windows生成了session.token丢docker里面，device.json得一致

**Comment by Flano-123** [comment]
> > > gocq captcha 寄了，手动抓取又选择不了，我机器人已经失联两天了
> > 
> > 
> > 要么就先别用docker运行了，或者外面登录好再传session和device到docker里
> 
> 我目前就是在windows生成了session.token丢docker里面，device.json得一致

+1 1.0.0 rc4 版本 移除qsign服务器配置 用windows端扫码登陆获取session.token和device.json丢到服务器上还能用
