### ISSUE TITLE
[Bug]: 尝试登录时卡在检查更新失败

### ISSUE THREAD

**Issue by FreeDivers** [Mrs4s/go-cqhttp#2424]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.1.0

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

1 | Android Phone

### 重现步骤

在控制输入`.\go-cqhttp.exe`

### 期望的结果是什么？

正常登录进行使用

### 实际的结果是什么？

卡在`[WARNING]: 检查更新失败: Get "https://api.github.com/repos/Mrs4s/go-cqhttp/releases/latest": context deadline exceeded (Client.Timeout exceeded while awaiting headers) `

### 日志记录（可选）

```golang
[2023-09-03 03:04:40] [WARNING]: 警告: 未配置签名服务器, 这可能会导致登录 45 错误码或发送消息被风控 
[2023-09-03 03:04:51] [WARNING]: Protocol -> device lock is disable. http api may fail. 
[2023-09-03 03:05:06] [WARNING]: 检查更新失败: Get "https://api.github.com/repos/Mrs4s/go-cqhttp/releases/latest": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by xiangxiangxiong9** [comment]
_这很正常，国内不挂代理访问gh经常连接超时...大概?_

**Comment by fenfenyangyangmate** [comment]
我也碰到了这个问题运行一段时间就变成这样，强制停止后运行也不行，只能重启系统解决
![image](https://github.com/Mrs4s/go-cqhttp/assets/90970696/6283f506-c9a4-4516-9646-a31e5ab6aeef)
![image](https://github.com/Mrs4s/go-cqhttp/assets/90970696/70bed17d-9f1b-4be1-99d5-514869c134eb)

**Comment by FreeDivers** [comment]
我挂了代理也不行，服了，有时候又正常

> _这很正常，国内不挂**代理**访问gh经常连接超时...大概?_
