### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CangGuY** [Mrs4s/go-cqhttp#2429]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.1.1

### 运行环境

Linux

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

6 | aPad

### 重现步骤

使用1.1.1DEV版go-cqhttp以及unidbg-fetch-qsign-1.1.9作为签名服务器。服务运行于基于WSL2的Kali Linux，复现仅需要按照标准流程启动签名服务器和go-cqhttp。运行go-cqhttp后得到：
  ./go-cqhttp
[2023-09-10 03:26:48] [INFO]: 当前版本:f16d72f
[2023-09-10 03:26:48] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2023-09-10 03:26:48] [INFO]: 检查签名服务器：http://127.0.0.1:7761  (1/1)
[2023-09-10 03:26:48] [INFO]: 使用签名服务器 url=http://127.0.0.1:7761, key=wwww, auth=-
[2023-09-10 03:26:49] [WARNING]: 注册QQ实例时出现错误: java.lang.ExceptionInInitializerError. server: http://127.0.0.1:7761
[2023-09-10 03:26:49] [INFO]: 使用签名服务器：http://127.0.0.1:7761
[2023-09-10 03:26:49] [INFO]: 自动刷新 token 已关闭，token 过期后获取签名时将不会立即尝试刷新获取新 token
[2023-09-10 03:26:49] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2023-09-10 03:26:49] [INFO]: 每 40 分钟将刷新一次签名 token
[2023-09-10 03:26:54] [INFO]: 开始尝试登录并同步消息...
[2023-09-10 03:26:54] [INFO]: 使用协议: Android Pad 8.9.63.11390
[2023-09-10 03:26:54] [INFO]: 正在检查协议更新...
[2023-09-10 03:26:56] [INFO]: Protocol -> connect to server: 198.18.0.29:8080
[2023-09-10 03:26:56] [WARNING]: 获取T544 sign时出现错误: encoding/hex: invalid byte: U+002F '/'
[2023-09-10 03:26:56] [WARNING]: 获取签名为空，实例可能丢失，正在尝试重新注册
[2023-09-10 03:26:56] [WARNING]: 注册QQ实例时出现错误: Could not initialize class unicorn.Unicorn. server: http://127.0.0.1:7761
[2023-09-10 03:26:56] [WARNING]: 登录需要滑条验证码, 请验证后重试.
[2023-09-10 03:26:56] [WARNING]: 请选择提交滑块ticket方式:
[2023-09-10 03:26:56] [WARNING]: 1. 自动提交
[2023-09-10 03:26:56] [WARNING]: 2. 手动抓取提交
[2023-09-10 03:26:56] [WARNING]: 请输入(1 - 2)：
1
[2023-09-10 03:26:59] [WARNING]: 请前往该地址验证 -> https://captcha.go-cqhttp.org/captcha?id=QoSVHRBQ&style=simple&aid=16&uin=3277203022&sid=3173608038866929408&cap_cd=abnN9nN4SeO1SBuCXbVQ3VUtTacxFUli5_fBFvRj414r3icSLeMuPA**&clientype=1&apptype=2
[2023-09-10 03:27:21] [INFO]: 检查签名服务器：http://127.0.0.1:7761  (1/1)
[2023-09-10 03:27:21] [INFO]: 使用签名服务器 url=http://127.0.0.1:7761, key=wwww, auth=-
[2023-09-10 03:27:21] [WARNING]: 注册QQ实例时出现错误: Could not initialize class unicorn.Unicorn. server: http://127.0.0.1:7761
[2023-09-10 03:27:21] [WARNING]: 获取T544 sign时出现错误: encoding/hex: invalid byte: U+002F '/'
[2023-09-10 03:27:21] [WARNING]: 获取签名为空，实例可能丢失，正在尝试重新注册
[2023-09-10 03:27:21] [WARNING]: 注册QQ实例时出现错误: Could not initialize class unicorn.Unicorn. server: http://127.0.0.1:7761
[2023-09-10 03:27:22] [WARNING]: 登录失败: 登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。 Code: 45
[2023-09-10 03:27:22] [WARNING]: 你的账号被限制登录, 请配置 SignServer 后重试
[2023-09-10 03:27:22] [INFO]: 按 Enter 继续....
此时unidbg-fetch-qsign-1.1.9显示信息为：
 bash bin/unidbg-fetch-qsign --basePath=txlib/8.9.63
FEBond sum = 7680
Load Package = Protocol(qua=V1_AND_SQ_8.9.63_4194_YYB_D, version=8.9.63, code=4194, packageName=com.tencent.mobileqq)
03:26:40.813 [main] INFO ktor.application - Autoreload is disabled because the development mode is off.
03:26:41.119 [main] INFO ktor.application - Application started in 0.334 seconds.
03:26:41.123 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
03:26:41.138 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
03:26:41.138 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
03:26:41.139 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
03:26:41.139 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
03:26:41.139 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.storeFence: available
03:26:41.139 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
03:26:41.140 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
03:26:41.140 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
03:26:41.140 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
03:26:41.140 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
03:26:41.140 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
03:26:41.141 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
03:26:41.141 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 32 (sun.arch.data.model)
03:26:41.141 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 954466304 bytes
03:26:41.141 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
03:26:41.142 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
03:26:41.142 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
03:26:41.150 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.workdir: /tmp (io.netty.tmpdir)
03:26:41.150 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.deleteLibAfterLoading: true
03:26:41.150 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.tryPatchShadedId: true
03:26:41.150 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.detectNativeLibraryDuplicates: true
03:26:41.155 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 24
03:26:41.160 [main] DEBUG io.netty.util.concurrent.GlobalEventExecutor - -Dio.netty.globalEventExecutor.quietPeriodSeconds: 1
03:26:41.164 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
03:26:41.165 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
03:26:41.169 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
03:26:41.169 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
03:26:41.173 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
03:26:41.196 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 27138 (auto-detected)
03:26:41.197 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
03:26:41.197 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
03:26:41.199 [main] DEBUG io.netty.util.NetUtilInitializations - Loopback interface: lo (lo, 0:0:0:0:0:0:0:1%lo)
03:26:41.199 [main] DEBUG io.netty.util.NetUtil - /proc/sys/net/core/somaxconn: 4096
03:26:41.200 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 00:15:5d:ff:fe:ba:6a:aa (auto-detected)
03:26:41.210 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
03:26:41.210 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
03:26:41.229 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 24
03:26:41.229 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 24
03:26:41.229 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
03:26:41.229 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 9
03:26:41.229 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 4194304
03:26:41.229 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
03:26:41.229 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
03:26:41.229 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
03:26:41.229 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
03:26:41.229 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
03:26:41.229 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: false
03:26:41.229 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
03:26:41.238 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
03:26:41.238 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
03:26:41.238 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
03:26:41.249 [DefaultDispatcher-worker-1] INFO ktor.application - Responding at http://127.0.0.1:7761
03:26:48.842 [eventLoopGroupProxy-3-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
03:26:48.843 [eventLoopGroupProxy-3-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
03:26:48.843 [eventLoopGroupProxy-3-1] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@189905d
03:26:48.877 [eventLoopGroupProxy-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
03:26:48.877 [eventLoopGroupProxy-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
03:26:48.877 [eventLoopGroupProxy-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.chunkSize: 32
03:26:48.877 [eventLoopGroupProxy-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.blocking: false
03:26:48.878 [eventLoopGroupProxy-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.batchFastThreadLocalOnly: true
03:26:48.988 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.NativeLibraryUtil - processor is INTEL_32 os.arch is i386
03:26:48.989 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is LINUX_32 os.name is linux
03:26:48.989 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is LINUX_32 os.name is linux
03:26:48.989 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is natives/linux_32/
03:26:48.989 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is libunicorn.so
03:26:48.989 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.BaseJniExtractor - Couldn't find resource natives/linux_32/libunicorn.so
03:26:48.989 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is linux_32/
03:26:48.989 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is libunicorn.so
03:26:48.989 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.BaseJniExtractor - Couldn't find resource linux_32/libunicorn.so
03:26:48.989 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is META-INF/lib/linux_32/
03:26:48.989 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is libunicorn.so
03:26:48.989 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.BaseJniExtractor - Couldn't find resource META-INF/lib/linux_32/libunicorn.so
03:26:49.035 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is LINUX_32 os.name is linux
03:26:49.035 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is natives/linux_32/
03:26:49.035 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is libunicorn_java.so
03:26:49.035 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.BaseJniExtractor - Couldn't find resource natives/linux_32/libunicorn_java.so
03:26:49.035 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is linux_32/
03:26:49.035 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is libunicorn_java.so
03:26:49.035 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.BaseJniExtractor - Couldn't find resource linux_32/libunicorn_java.so
03:26:49.035 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is META-INF/lib/linux_32/
03:26:49.036 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is libunicorn_java.so
03:26:49.036 [eventLoopGroupProxy-4-2] DEBUG org.scijava.nativelib.BaseJniExtractor - Couldn't find resource META-INF/lib/linux_32/libunicorn_java.so

### 期望的结果是什么？

1

### 实际的结果是什么？

1

### 补充说明（可选）

大佬们救救孩子QAQ

**Comment by rhwong** [comment]
获取T544 sign时出现错误: encoding/hex: invalid byte: U+002F '/'

**Comment by rhwong** [comment]
qsign那边尝试使用0.0.0.0开启服务
