### ISSUE TITLE
[Bug]: CQ图片消息链接发生了变化

### ISSUE THREAD

**Issue by contr4l** [Mrs4s/go-cqhttp#2435]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.1.0

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

6 | aPad

### 重现步骤

正常运行go-cq，接收图片消息，格式发生了变化。
举例：
消息: [CQ:image,file=f6a6b489e7032f0649901d4cb3880b25.image,subType=1,url=https://gchat.qpic.cn&amp;rkey=CAMSMK9dKl3nqG6QFwzXzNPLwk0B0OntR-bwn4j_iFCviC2Qz8J8nbFkzRHeQXLgf2bVeg&amp;spec=0]

### 期望的结果是什么？

url可以访问到原始图片内容

### 实际的结果是什么？

urllib3.exceptions.LocationParseError: Failed to parse: 'gchat.qpic.cn&rkey=camsmk9dkl3nqg6qfwzxznplwk0b0ontr-bwn4j_ifcvic2qz8j8nbfkzrheqxlgf2bveg&spec=0', label empty or too long

### 补充说明（可选）

今天才发生如上状况，原来的url格式是offpic/xxx，将&进行转义后可以访问。

**Comment by contr4l** [comment]
当然这也可能是QQ的图片服务器发生了变化，希望有遇到过相似情况或知道原因的朋友给一些建议。

**Comment by contr4l** [comment]
到了晚上又好了，不知道rkey是什么机制...，先关掉了。

**Comment by ilyfairy** [comment]
有些图片的链接依旧有问题
[CQ:image,file=0155e87c7c024091a7833b9c0d0df10e.image,subType=1,url=https://gchat.qpic.cn&amp;rkey=CAQSMKt8AcihJaGW-jgw2QnEOxf9iXIqpySuAvjnkyH57E3iOGwN3NLdBYPD1oZ2-xAWCg&amp;spec=0]

**Comment by contr4l** [comment]
> 有些图片的链接依旧有问题 [CQ:image,file=0155e87c7c024091a7833b9c0d0df10e.image,subType=1,url=https://gchat.qpic.cn&rkey=CAQSMKt8AcihJaGW-jgw2QnEOxf9iXIqpySuAvjnkyH57E3iOGwN3NLdBYPD1oZ2-xAWCg&spec=0]

初步可以一刀切，如果是带路径的url就没问题，如果是rkey的就有问题，可以再等等吧。

**Comment by succulentxb** [comment]
遇到同样的问题，请问有什么解决方案吗？
