### ISSUE TITLE
[Bug]: GoCQ 意外崩溃，报错 `invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by lgc2333** [Mrs4s/go-cqhttp#2437]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

f16d72f

### 运行环境

Ubuntu 23.04

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

6 | aPad（尝试过 8.9.63，更换协议至 [8.9.70](https://github.com/MrXiaoM/qsign/blob/mirai/txlib/8.9.70/android_pad.json) 依然崩溃）

### 重现步骤

原因未知

~~在 `sign-servers` 下仅填写一个签名服务器配置，之后运行 GoCQ~~
~~（我也不知道具体原因是不是这个，看到某个群友说的）~~ 并不是

### 期望的结果是什么？

运行正常不崩溃

### 实际的结果是什么？

运行一段时间后崩溃

### 日志记录（可选）

```golang
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x974ec3]

goroutine 50 [running]:
github.com/Mrs4s/go-cqhttp/cmd/gocq.signStartRefreshToken(0x28)
    github.com/Mrs4s/go-cqhttp/cmd/gocq/qsign.go:400 +0x323
created by github.com/Mrs4s/go-cqhttp/cmd/gocq.LoginInteract
    github.com/Mrs4s/go-cqhttp/cmd/gocq/main.go:172 +0x545
```

**Comment by YumeMichi** [comment]
cmd/gocq/qsign.go 400行的cs.URL换成master.URL看看
