### ISSUE TITLE
希望可以支持同时接受string和array的上报数据

### ISSUE THREAD

**Issue by KBVsent** [Mrs4s/go-cqhttp#2443]
**环境信息**

centos7
go-cqhttp版本: 
1.1.0
**需要添加的功能内容**

目前我使用两个项目需要连接gocqhttp，但其中一个上报数据类型为string，一个为array，因此不能同时运行在同一个gocqhttp进程上，希望可以更新支持同时接受string和array的上报数据。

**Comment by 1umine** [comment]
使用array上报的方式，需要用string上报的那端接收到上报消息时使用raw_message字段应该就行了

**Comment by KBVsent** [comment]
> 使用array上报的方式，需要用string上报的那端接收到上报消息时使用raw_message字段应该就行了

如果需要改动代码是有很多方式可以解决的，但是就是希望可以直接接入，目前连接方式是可以同时设置多种的，不知道为什么上报数据不能同时设置两种。

**Comment by jiangyin14** [comment]
#2298
之前 #七百多 就有一个issue说过，到现在也没什么动静...
