### ISSUE TITLE
[Bug]: 无法通过iPad协议登录

### ISSUE THREAD

**Issue by ling-shuang** [Mrs4s/go-cqhttp#2448]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [x] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.1.0

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

5 | iPad

### 重现步骤

只需要执行go-cqhttp即可。不知道这是bug还是我自己的问题，我已经使用了外部的签名服务器的服务，他仍然提示我：请配置 SignServer 后重试 
![屏幕截图 2023-09-28 132914](https://github.com/Mrs4s/go-cqhttp/assets/114481409/28ada999-bbf7-463f-b303-b1f0bcd1dda7)

### 期望的结果是什么？

使用iPad协议能成功登陆。

### 实际的结果是什么？

无法成功登录

**Comment by ling-shuang** [comment]
虽然我能使用手表协议登录，但不过经常被风控，基本一天就封一次。我更希望使用iPad协议登陆。

**Comment by LYYZZ** [comment]
自己看，先有签名服务器再说吧。https://github.com/Mrs4s/go-cqhttp/issues/2242

**Comment by yiyihaohao** [comment]
> 自己看，先有签名服务器再说吧。#2242

签名服务器不是只支持安卓吗？现在也支持IPAD了？

**Comment by jiangyin14** [comment]
签名服务器很早之前就有iPad了，自己研究研究吧。

**Comment by lingyunQAQ** [comment]
> 自己看，先有签名服务器再说吧。#2242

为啥我使用docker弄验证服务器登录ipda和安卓还是提示45

**Comment by jiangyin14** [comment]
> > 自己看，先有签名服务器再说吧。#2242
> 
> 
> 
> 为啥我使用docker弄验证服务器登录ipda和安卓还是提示45
> 
> 

发日志，不然咋看啊
go-cqhttp换协议了吗？8.9.73/8.9.77

**Comment by lingyunQAQ** [comment]
> > > 自己看，先有签名服务器再说吧。#2242
> > 
> > 
> > 为啥我使用docker弄验证服务器登录ipda和安卓还是提示45
> 
> 发日志，不然咋看啊 go-cqhttp换协议了吗？8.9.73/8.9.77

木有啊还是默认的，但是换了好像还是登录不上去，日志和楼主一样

**Comment by fumiama** [comment]
配置签名服务器可解，但要注意使用签名服务器大概率陷入封号循环。
