### ISSUE TITLE
[Bug]: 运行一段时间，自动下线并报错panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zhtyirg3** [Mrs4s/go-cqhttp#2449]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [ ] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [ ] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [ ] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [ ] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

f16d72f

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

6 | aPad

### 重现步骤

用dev分支，用1.1.9qs,用了一段时间，这2天开始频繁自动下线，重新登陆一段时间后就报错，下线。

### 期望的结果是什么？

能够正常登陆并稳定运行

### 实际的结果是什么？

![e39e9818cfa8e2c3b7b8ecd790a8779d](https://github.com/Mrs4s/go-cqhttp/assets/55908974/378202f7-a06d-4b05-8cd6-8d4fabb387db)
报错截图

**Comment by jiangyin14** [comment]
你机器太渣了

**Comment by BakaReimu** [comment]
> 你机器太渣了

我13700K也这样，一段时间过后就会炸

**Comment by jiangyin14** [comment]
> > 你机器太渣了
> 
> 
> 
> 我13700K也这样，一段时间过后就会炸

不应该，目前我最新版本没有任何问题

**Comment by fumiama** [comment]
试试最新版。

**Comment by saltyplum** [comment]
拉最新的dev分支几天后还是出现了这问题

**Comment by zhtyirg3** [comment]
> 你机器太渣了

重启了服务器，好像这几天也没事了，再试试看看
