### ISSUE TITLE
[Bug]: 长消息及图片消息发送失败

### ISSUE THREAD

**Issue by StevehimYu** [Mrs4s/go-cqhttp#2450]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

go-cqhttp dev

### 运行环境

Ubuntu

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

0 | Default

### 重现步骤

启动机器人
然后对机器人执行发送长消息 / 图片的指令
使用/send_group_message 进行发送(就是发送群消息的那个)

### 期望的结果是什么？

发送成功

### 实际的结果是什么？

之后显示您的账号已被风控

### 补充说明（可选）

但事实上点歌的链接是可以发送的

**Comment by jiangyin14** [comment]
不给日志吗？
可能是SignServer没写

**Comment by fumiama** [comment]
您的账号已被风控

**Comment by StevehimYu** [comment]
> 您的账号已被风控

事实上我的账号并没有被风控啊，歌曲的CQ码还是可以发送的

**Comment by fumiama** [comment]
风控就是有些能发有些不能发，都发不出去那叫封号（
