### ISSUE TITLE
发送图文长消息时，手机QQ端上方会有空隔

### ISSUE THREAD

**Issue by xxyy3130** [Mrs4s/go-cqhttp#246]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.23
运行环境: windows_amd64
连接方式: 正向WS

**bug内容**
发送图文长消息时，在手机QQ显示的图片上方会有空隔

**复现方法**
例如发送消息：[CQ:image,file=https://iknow-pic.cdn.bcebos.com/500fd9f9d72a6059aa206b7e2a34349b033bbaa6]\n早上好*(੭*ˊᵕˋ)੭*\n中午好*(੭*ˊᵕˋ)੭*\n下午好*(੭*ˊᵕˋ)੭*\n晚上好*(੭*ˊᵕˋ)੭*
电脑端显示正常，手机端最上方则会有空隔

![image](https://user-images.githubusercontent.com/61443746/92317067-e76c0780-f02e-11ea-9398-17135bfbfc0e.png)

**Comment by wdvxdr1123** [comment]
我重现了，同时发现了一个奇怪的现象
手机中回复该消息前面有"[图片]"，发送出去后"[图片]"消失了，电脑上不会出现这个问题
![qq_pic_merged_1599362457367](https://user-images.githubusercontent.com/34832863/92317459-4fbce800-f033-11ea-9360-f4fd9ff0ab3e.jpg)
![qq_pic_merged_1599362347927](https://user-images.githubusercontent.com/34832863/92317464-5b101380-f033-11ea-9e4c-74cd46b3fcc8.jpg)
123是电脑上回复的

更有趣的是，用手机qq的截图功能截取这两个消息，图片又能显示出来了
![15a90ab91425ae8](https://user-images.githubusercontent.com/34832863/92317481-8dba0c00-f033-11ea-99ae-158b39680152.png)

**Comment by Mrs4s** [comment]
姑且怀疑是QQ莫名其妙的解析问题...

**Comment by Mrs4s** [comment]
请试试最新版还有没有问题

**Comment by xxyy3130** [comment]
> 请试试最新版还有没有问题

0.9.27版本还是会这样
![qq_pic_merged_1602032661489](https://user-images.githubusercontent.com/61443746/95275876-43b78680-087c-11eb-8047-ec9aa866f284.jpg)

**Comment by xxyy3130** [comment]
今天看到force_fragmented之前一直是true，测试发现force_fragmented=false时没有空隔，force_fragmented=true时有空隔出现

**Comment by My-Jie** [comment]
可以处理下空格再发吧

**Comment by Mrs4s** [comment]
> 今天看到force_fragmented之前一直是true，测试发现force_fragmented=false时没有空隔，force_fragmented=true时有空隔出现

应该是奇怪的解析问题，在最近的版本我已经将`force_fragmented`默认关闭了, 因为发现除了速度快以外没什么其他优点 兼容性还有比较大的问题

**Comment by sam01101** [comment]
最新Release已修复此问题, 目前没发现`电脑`, `Android`, `iPad`上有此问题
安卓我`QQ`和`TIM`我测试过了, 没问题
`电脑`我就`TIM`
`iPad`就`QQ`

**Comment by sam01101** [comment]
Ready to close @Mrs4s

**Comment by sam01101** [comment]
哼哼, 这个解决了谁close下啊啊啊啊啊啊啊

**Comment by xxyy3130** [comment]
v0.9.40-fix4 私聊没有此问题，群聊还是存在
![s](https://user-images.githubusercontent.com/61443746/111564946-8db27a00-87d5-11eb-8996-db755c2f809f.jpg)
![q](https://user-images.githubusercontent.com/61443746/111564952-91460100-87d5-11eb-97c1-d2c580dc8d82.jpg)

**Comment by Mrs4s** [comment]
这个问题比较麻烦, 估计得研究下QQ怎么解析的消息...

**Comment by Mrs4s** [comment]
测试了下这个空格是服务端加的, 可能有什么魔法参数...

**Comment by Mrs4s** [comment]
不对 不是服务端加的

**Comment by Mrs4s** [comment]
我这边复现失败了, 应该是解决了.
之前测试是因为输入姿势不对..

**Comment by xxyy3130** [comment]
v1.0.0-beta3 分片发送 群聊，测试还是有空隔
IOS端看到的：
![6638AE6FAD97C969C96C039231390379](https://user-images.githubusercontent.com/61443746/114851821-d0876200-9e14-11eb-89e3-acccdfd10bf1.png)
Android端看到的：
![qq_pic_merged_1618481018628](https://user-images.githubusercontent.com/61443746/114851961-eac14000-9e14-11eb-9964-458c2d53b3ae.jpg)

**Comment by sam01101** [comment]
妈耶

**Comment by sam01101** [comment]
> 分片发送

请关闭分片
