### ISSUE TITLE
[Bug]: dev版本打不开

### ISSUE THREAD

**Issue by Little1Yuan** [Mrs4s/go-cqhttp#2461]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

所有dev版本

### 运行环境

Linux

### 运行架构

其它

### 连接方式

HTTP

### 使用协议

6 | aPad

### 重现步骤

# su root ./go-cqhttp_linux_amd64 
./go-cqhttp_linux_amd64: ./go-cqhttp_linux_amd64: cannot execute binary file

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

# su root ./go-cqhttp_linux_amd64 
./go-cqhttp_linux_amd64: ./go-cqhttp_linux_amd64: cannot execute binary file

### 日志记录（可选）

```golang
无
```

### 补充说明（可选）

尝试过3个dev版本的所有Linux架构类型，全部cannot execute binary file
uname -a
Linux iZuf68gja99cvzc9kpo4tqZ 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jiangyin14** [comment]
运行
uname -a
返回的信息补充到issue里面

**Comment by Little1Yuan** [comment]
> 运行 uname -a 返回的信息补充到issue里面

Linux iZuf68gja99cvzc9kpo4tqZ 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by 1umine** [comment]
加执行权限了吗

**Comment by Little1Yuan** [comment]
> 加执行权限了吗

issue里写了，用的su root，后来chmod 777也是相同结果

**Comment by jiangyin14** [comment]
> > 运行 uname -a 返回的信息补充到issue里面
> 
> 
> 
> Linux iZuf68gja99cvzc9kpo4tqZ 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> 
> 

你这是低版本CentOS吧，用ubuntu高版本解君愁（CentOS 8 Stream亲测也可以用）
4.18.0内核版本太老了，最新的大版本号都6了

**Comment by Little1Yuan** [comment]
> > > 运行 uname -a 返回的信息补充到issue里面
> > 
> > 
> > Linux iZuf68gja99cvzc9kpo4tqZ 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> 
> 你这是低版本CentOS吧，用ubuntu高版本解君愁（CentOS 8 Stream亲测也可以用） 4.18.0内核版本太老了，最新的大版本号都6了

release能用就是dev用不了
这是服务器的，搞版本不太方便，我看看吧

**Comment by Little1Yuan** [comment]
> > > 运行 uname -a 返回的信息补充到issue里面
> > 
> > 
> > Linux iZuf68gja99cvzc9kpo4tqZ 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> 
> 你这是低版本CentOS吧，用ubuntu高版本解君愁（CentOS 8 Stream亲测也可以用） 4.18.0内核版本太老了，最新的大版本号都6了

我大概需要一个怎样版本的内核呢？准备用yum更新了

**Comment by ZhaoZuohong** [comment]
> 搞版本不太方便

可以尝试使用容器运行

**Comment by Little1Yuan** [comment]
问题已解决，谢了
