### ISSUE TITLE
[Bug]: 使用自动提交ticket，无法登录

### ISSUE THREAD

**Issue by awaa-col** [Mrs4s/go-cqhttp#2465]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

fd71785

### 运行环境

Windows (64)

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

0 | Default

### 重现步骤

我正常使用bat脚本进入go cq，配置好了账号密码与签名服务器，使用自动提交ticket，但时完成验证后没有反应

### 期望的结果是什么？

正常登入cq bot

### 实际的结果是什么？

CQ内截图
![image](https://github.com/Mrs4s/go-cqhttp/assets/125521033/2eed83f7-6ede-40c0-90be-260dc1935cf5)
Qsign内截图
![image](https://github.com/Mrs4s/go-cqhttp/assets/125521033/161b782f-a247-42df-9374-d58269c2906b)
![image](https://github.com/Mrs4s/go-cqhttp/assets/125521033/64f7a04e-69ec-4510-9002-c23ca46b5452)

### 补充说明（可选）

为了接入claude2，挂上了美国代理，使用的go cq为https://github.com/rhwong/unidbg-fetch-qsign-onekey中的自带的

**Comment by jiangyin14** [comment]
没事 多登录几次 这个问题时常出现 有概率的
用1umine/go-cqhttp的dev试试看

**Comment by maborosh** [comment]
> 没事 多登录几次 这个问题时常出现 有概率的 用1umine/go-cqhttp的dev试试看 而且8.9.63死了 换8.9.73 可参考
> 
> 1. https://github.com/fuqiuluo/unidbg-fetch-qsign/wiki#go-cqhttp
> 2. [尝试修复首次登录时容易出现 code -10005 和 packet timed out 的问题 #2463](https://github.com/Mrs4s/go-cqhttp/pull/2463)

用8.9.73容易被冻结吗？我的一个号成功登陆了，但过一段时间再看就被冻结了

**Comment by jiangyin14** [comment]
> > 没事 多登录几次 这个问题时常出现 有概率的 用1umine/go-cqhttp的dev试试看 而且8.9.63死了 换8.9.73 可参考
> 
> > 
> 
> > 1. https://github.com/fuqiuluo/unidbg-fetch-qsign/wiki#go-cqhttp
> 
> > 2. [尝试修复首次登录时容易出现 code -10005 和 packet timed out 的问题 #2463](https://github.com/Mrs4s/go-cqhttp/pull/2463)
> 
> 
> 
> 用8.9.73容易被冻结吗？我的一个号成功登录了，但过一段时间再看就被冻结了

我 8.9.73三周了没事，可以试试8.9.71，很多人用

**Comment by awaa-col** [comment]
问题解决了

**Comment by jiangyin14** [comment]
> > 没事 多登录几次 这个问题时常出现 有概率的 用1umine/go-cqhttp的dev试试看 而且8.9.63死了 换8.9.73 可参考
> 
> > 
> 
> > 1. https://github.com/fuqiuluo/unidbg-fetch-qsign/wiki#go-cqhttp
> 
> > 2. [尝试修复首次登录时容易出现 code -10005 和 packet timed out 的问题 #2463](https://github.com/Mrs4s/go-cqhttp/pull/2463)
> 
> 
> 
> 用8.9.73容易被冻结吗？我的一个号成功登录了，但过一段时间再看就被冻结了

我的账号被冻结了，大冻（10天），抓紧上8.9.80，73也不行了

**Comment by maborosh** [comment]
> > > 没事 多登录几次 这个问题时常出现 有概率的 用1umine/go-cqhttp的dev试试看 而且8.9.63死了 换8.9.73 可参考
> > 
> > 
> > > 
> > 
> > 
> > > 1. https://github.com/fuqiuluo/unidbg-fetch-qsign/wiki#go-cqhttp
> > 
> > 
> > > 2. [尝试修复首次登录时容易出现 code -10005 和 packet timed out 的问题 #2463](https://github.com/Mrs4s/go-cqhttp/pull/2463)
> > 
> > 
> > 用8.9.73容易被冻结吗？我的一个号成功登录了，但过一段时间再看就被冻结了
> 
> 我的账号被冻结了，大冻（10天），抓紧上8.9.80，73也不行了

qsign有8.9.80版本的吗？
