### ISSUE TITLE
[Bug]: 太容易死了，1天不到就冻结，有没有稳定的框架啊

### ISSUE THREAD

**Issue by xlsqwg** [Mrs4s/go-cqhttp#2469]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

dev

### 运行环境

CentOS

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

6 | aPad

### 重现步骤

所有协议都试过了，照样容易死，活不过2天，自己搭建的签名服务器1.1.7，1.1.9都试过了，一样死的快

### 期望的结果是什么？

没有期望，想换个稳定点框架，谁有

### 实际的结果是什么？

冻结了好几个号了，很烦

**Comment by RexQian** [comment]
珍爱生命 远离QQ

**Comment by fumiama** [comment]
试试red
