### ISSUE TITLE
添加ECMAScript的插件支持

### ISSUE THREAD

**Issue by wdvxdr1123** [Mrs4s/go-cqhttp#247]
引入ECMAScript插件可以在不修改go-cqhttp本身代码的情况下，给go-cqhttp添加一些功能
我尝试过用[Otto]( https://github.com/robertkrimen/otto )实现，但Otto已近9个月没更新了，同时不会支持ES6的新特性，也不会支持node.js
最近我发现了一个项目 [goja]( https://github.com/dop251/goja ),支持部分ES6和Node.JS

我感觉用go集成ffmpeg实现全格式语音发送有点困难，我觉得可以用goja跑npm上的 wx-voice 来转换语音格式

**Comment by scjtqs** [comment]
实在golang不行，可以考虑 docker-compose这样的联合部署嘛

**Comment by Mrs4s** [comment]
可以考虑集成lua脚本引擎?

**Comment by wdvxdr1123** [comment]
目前经过测试，确认可以用JS调用MiraiGo的API（包括事件，但不支持箭头函数，代码有点丑），感觉还需要封装，http好像有点难实现原版CQHTTP插件中的on_missed_action

**Comment by Shigma** [comment]
goja 性能肯定不如 v8，我正好在开发一个基于 v8 的 mirai-go binding（虽然也夹杂了大量 go-cqhttp 的代码），可以考虑一下：https://github.com/shigma/atri

**Comment by dzcpy** [comment]
我觉得这个需求不应该在go-cqhttp层面解决吧？这只是一个http的接口。想用 js 完全可以加一个上层的 js 调用，比如 [koishijs](https://github.com/koishijs/koishi) 在那里处理就好了，golang 嵌入 js，感觉怪怪的，而且对性能也有影响吧

**Comment by Shigma** [comment]
@dzcpy 我觉得一方面这确实有点脱离这个库目前的开发重心，但另一方面这与这个库的初衷也不能说完全违背。因为即使是 js 只要是做接口映射的话，确实做的也是 cqhttp (onebot) 协议的实现。如果要在这个仓库中完成的话，可以考虑这种结构：

``` diff
  root
  ├ coolq
  ├ global
+ ├ node
+ │ ├ main.go    // 将阻塞方法转化为回调函数，同时接口封装成 cgo 可用的形式
+ │ ├ addon.cc   // 使用 v8 和 libuv 将所有功能封装成可被 js 调用的函数和类
+ │ └ index.js
  └ server
```

**Comment by wdvxdr1123** [comment]
这个js插件主要是拓展cqhttp的功能，原版cqhttp可以使用C++开发插件，RC也提供了长轮询扩展和垃圾清理拓展
只是目前我实现有点脱离这方面了，我再想想其他方案
最开始是想直接用go开发插件的，但是没有找到好的解决方案，内置的plugin只能再类unix上使用，第三方的基本是基于tcp实现

**Comment by dzcpy** [comment]
其实如果整个框架不用 go 而是用 typescript / javascript 来开发，应该会灵活得多

**Comment by wdvxdr1123** [comment]
> 其实如果整个框架不用 go 而是用 typescript / javascript 来开发，应该会灵活得多。期待将来有个 js-cqhttp 就方便了。开发效率上来讲，js 比 go 还是方便一些

你可以去看看隔壁[oicq]( https://github.com/takayama-lily/oicq )

**Comment by dzcpy** [comment]
@wdvxdr1123 多谢推荐，我研究研究

**Comment by Shigma** [comment]
oicq 作为 js 项目还用 agpl 我个人就觉得没什么意义了……

顺便，如果要结合性能和开发速度的话，还是 go 做底层实现 + js binding 最好，oicq 的性能上肯定还是差点。

**Comment by dzcpy** [comment]
go 是比 js 快点，但这个项目本身也不大，本来也是一个底层接口转 http 的项目。我感觉要想扩展还不如直接 fork 从上面改了。插件

**Comment by Shigma** [comment]
不担心性能的话不如直接上 koishi 了（

**Comment by Shigma** [comment]
当然说到底做不做原生支持还看 @Mrs4s 怎么想。

我想表达的意思是，如果不做 binding 的话，无论是 oicq 和 cq-websocket 还是 koishi 都差不多，用哪个都是一样的。既然【插件总觉得适合放在上层一点的逻辑上】就更没必要专门选择 oicq 了。如果做 binding 的话，现在 js 生态都在 node 那里，肯定得想办法支持最新的 node 特性。这方面我做过一段时间的尝试，有一定的经验（并且这些经验是跟 koishi 无关的），提出一种可行的解决方式而已。

**Comment by Ink-33** [comment]
在go-cqhttp上面直接扩展功能的话，js确实是一个好选择，正如上面说的js开发效率比go高，但也要考虑到性能的问题。这个东西得慢慢斟酌，shigma/atri是一个好办法，但应该还有其他解决方式。go的局限性在这里，兼容js的插件不是很方便，要我来说不如fork然后直接改来的快(



&nbsp;




------------------&nbsp;Original&nbsp;------------------

**Comment by Ink-33** [comment]
在go-cqhttp上面直接扩展功能的话，js确实是一个好选择，正如上面说的js开发效率比go高，但也要考虑到性能的问题。这个东西得慢慢斟酌，shigma/atri是一个好办法，但应该还有其他解决方式。go的局限性在这里，兼容js的插件不是很方便，要我来说不如fork然后直接改来的快(


------------------&nbsp;Original&nbsp;------------------

**Comment by dzcpy** [comment]
fork 后改 +1
