### ISSUE TITLE
[Bug]: 连接到反向WebSocket Universal服务器 被拒绝

### ISSUE THREAD

**Issue by black-zero358** [Mrs4s/go-cqhttp#2475]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.2.0

### 运行环境

Ubuntu

### 运行架构

None

### 连接方式

WebSocket (反向)

### 使用协议

2 | Android Watch

### 重现步骤

![image](https://github.com/Mrs4s/go-cqhttp/assets/53086059/b17256c5-398a-49d6-8e9a-a57dda3a3821)
![image](https://github.com/Mrs4s/go-cqhttp/assets/53086059/d540d4d1-497c-4284-ba3f-f50a719d43ec)

nonebot没有接收到链接请求，对ws地址作何修改，都是提示connection refused，猜测是go-cq自身的设置或者权限问题？

将ubuntu系统重置后，把上个系统的文件原封不动的迁移到新系统
运行时便会提示
[2023-10-12 21:48:23] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8001/onebot/v11/ws 时出现错误: dial tcp 127.0.0.1:8001: connect: connection refused

### 期望的结果是什么？

当然是正常链接

### 实际的结果是什么？

[2023-10-15 22:16:32] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:8001/onebot/v11/ 
[2023-10-15 22:16:32] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8001/onebot/v11/ 时出现错误: dial tcp 127.0.0.1:8001: connect: connection refused

**Comment by LsrlYrsc** [comment]
你的bot后端没有打开，ws反向是前端主动连接后端的协议
~~这种问题难道你本人不清楚情况吗~~

**Comment by black-zero358** [comment]
> 你的bot**后端**没有打开，ws反向是**前端主动连接后端**的协议，所以后端在未开启的情况下，前端主动连接未回复导致的失败 ~这种问题难道你本人不清楚情况吗~ 还有，你**期望的结果**是~connection refuse~吗，请你分析完整自己的问题再来发issue :)![127485C0A48806645894CBD7F2A51194_0.gif](https://user-images.githubusercontent.com/111047831/275285885-f48bcd0f-5bb4-4936-9840-cabd539a9905.gif) [ ![127485C0A48806645894CBD7F2A51194_0.gif](https://user-images.githubusercontent.com/111047831/275285885-f48bcd0f-5bb4-4936-9840-cabd539a9905.gif) ](https://user-images.githubusercontent.com/111047831/275285885-f48bcd0f-5bb4-4936-9840-cabd539a9905.gif) [ ](https://user-images.githubusercontent.com/111047831/275285885-f48bcd0f-5bb4-4936-9840-cabd539a9905.gif)

根据你的回复我修改了issue的部分内容
后端肯定是开着的，这次出现的问题以前没有遇到过，我一时也想不出是哪里出的问题

**Comment by LsrlYrsc** [comment]
> > 你的bot**后端**没有打开，ws反向是**前端主动连接后端**的协议，所以后端在未开启的情况下，前端主动连接未回复导致的失败 ~这种问题难道你本人不清楚情况吗~ 还有，你**期望的结果**是~connection refuse~吗，请你分析完整自己的问题再来发issue :)![127485C0A48806645894CBD7F2A51194_0.gif](https://user-images.githubusercontent.com/111047831/275285885-f48bcd0f-5bb4-4936-9840-cabd539a9905.gif) [ ![127485C0A48806645894CBD7F2A51194_0.gif](https://user-images.githubusercontent.com/111047831/275285885-f48bcd0f-5bb4-4936-9840-cabd539a9905.gif) ](https://user-images.githubusercontent.com/111047831/275285885-f48bcd0f-5bb4-4936-9840-cabd539a9905.gif) [ ](https://user-images.githubusercontent.com/111047831/275285885-f48bcd0f-5bb4-4936-9840-cabd539a9905.gif)
> 
> 根据你的回复我修改了issue的部分内容
> 后端肯定是开着的，这次出现的问题以前没有遇到过，我一时也想不出是哪里出的问题

你需要再三确认你的后端是否打开并且是正确的端口和正确的协议(ws/ws-reserve)

本人没有用过**docker**(我猜想你是docker容器)，但是我认为docker容器的端口不互通，你需要确认一下是否开放了端口

**Comment by LsrlYrsc** [comment]
> > > 你的bot**后端**没有打开，ws反向是**前端主动连接后端**的协议，所以后端在未开启的情况下，前端主动连接未回复导致的失败 ~这种问题难道你本人不清楚情况吗~ 还有，你**期望的结果**是~connection refuse~吗，请你分析完整自己的问题再来发issue :)![127485C0A48806645894CBD7F2A51194_0.gif](https://user-images.githubusercontent.com/111047831/275285885-f48bcd0f-5bb4-4936-9840-cabd539a9905.gif) [ ![127485C0A48806645894CBD7F2A51194_0.gif](https://user-images.githubusercontent.com/111047831/275285885-f48bcd0f-5bb4-4936-9840-cabd539a9905.gif) ](https://user-images.githubusercontent.com/111047831/275285885-f48bcd0f-5bb4-4936-9840-cabd539a9905.gif) [ ](https://user-images.githubusercontent.com/111047831/275285885-f48bcd0f-5bb4-4936-9840-cabd539a9905.gif)
> > 
> > 根据你的回复我修改了issue的部分内容
> > 后端肯定是开着的，这次出现的问题以前没有遇到过，我一时也想不出是哪里出的问题
> 
> 你需要再三确认你的后端是否打开并且是正确的端口和正确的协议(ws/ws-reserve)
> 
> 本人没有用过**docker**(我猜想你是docker容器)，但是我认为docker容器的端口不互通，你需要确认一下是否开放了端口

我刚刚看见了issue的图片（加载的好慢）
我没有看类似于端口开放的提示，请问是正确的端口吗

**Comment by LsrlYrsc** [comment]
照理来说，你下面应该会有一个Onebot的端口打开提示，但是并没有，我找找图片（将在下面展示）

**Comment by black-zero358** [comment]
> > > > 你的bot**后端**没有打开，ws反向是**前端主动连接后端**的协议，所以后端在未开启的情况下，前端主动连接未回复导致的失败 ~这种问题难道你本人不清楚情况吗~ 还有，你**期望的结果**是~connection refuse~吗，请你分析完整自己的问题再来发issue :)![127485C0A48806645894CBD7F2A51194_0.gif](https://user-images.githubusercontent.com/111047831/275285885-f48bcd0f-5bb4-4936-9840-cabd539a9905.gif) [ ![127485C0A48806645894CBD7F2A51194_0.gif](https://user-images.githubusercontent.com/111047831/275285885-f48bcd0f-5bb4-4936-9840-cabd539a9905.gif) ](https://user-images.githubusercontent.com/111047831/275285885-f48bcd0f-5bb4-4936-9840-cabd539a9905.gif) [ ](https://user-images.githubusercontent.com/111047831/275285885-f48bcd0f-5bb4-4936-9840-cabd539a9905.gif)
> > > 
> > > 
> > > 根据你的回复我修改了issue的部分内容
> > > 后端肯定是开着的，这次出现的问题以前没有遇到过，我一时也想不出是哪里出的问题
> > 
> > 
> > 你需要再三确认你的后端是否打开并且是正确的端口和正确的协议(ws/ws-reserve)
> > 本人没有用过**docker**(我猜想你是docker容器)，但是我认为docker容器的端口不互通，你需要确认一下是否开放了端口
> 
> 我刚刚看见了issue的图片（加载的好慢） 我没有看类似于端口开放的提示，请问是正确的端口吗

go-cq和nonebot（venv）都是直接运行的，没有使用docker，链接本地端口不需要特地开放吧？下图是8080端口使用情况
![image](https://github.com/Mrs4s/go-cqhttp/assets/53086059/8e86c27a-473f-4505-a206-2103698c7451)
此时的go-cq日志仍是connection refused。nb日志仍没有链接相关信息

ws部分的配置如下：
`servers:
  - ws-reverse:
      universal: ws://127.0.0.1:8080/onebot/v11/ws/
`

**Comment by LsrlYrsc** [comment]
![Screenshot_2023-10-15-22-35-14-13_1dc0b008cf3e27ddb1943311a918955a.jpg](https://github.com/Mrs4s/go-cqhttp/assets/111047831/c9f58741-420f-4006-975f-ac56fd0b9b86)

**Comment by black-zero358** [comment]
> ![Screenshot_2023-10-15-22-35-14-13_1dc0b008cf3e27ddb1943311a918955a.jpg](https://user-images.githubusercontent.com/111047831/275332553-c9f58741-420f-4006-975f-ac56fd0b9b86.jpg)
> 
> 最下面的提示

嗯，注意到了。nb的日志确实缺少了相关的条目（我上个系统的nb确实会输出类似于running on http的日志）。我会尝试重新创建nb项目才测试

**Comment by black-zero358** [comment]
> ![Screenshot_2023-10-15-22-35-14-13_1dc0b008cf3e27ddb1943311a918955a.jpg](https://user-images.githubusercontent.com/111047831/275332553-c9f58741-420f-4006-975f-ac56fd0b9b86.jpg)
> 
> 最下面的提示 可能没有公信度 我将在ubuntu环境继续测试

![image](https://github.com/Mrs4s/go-cqhttp/assets/53086059/b6e4cf13-64bb-44ca-9aef-36d53a479ee0)
问题已经解决，应该是创建项目的时候没有勾选fastAPI驱动器的缘由，导致了上面的问题。

非常感谢你的帮助
