### ISSUE TITLE
v0.9.24无法正常登录

### ISSUE THREAD

**Issue by mnixry** [Mrs4s/go-cqhttp#248]
**环境信息**
- go-cqhttp版本: v0.9.24
- 运行环境: linux_amd64
- 连接方式: 反向WS

**bug内容**
在gocqhttp更新并迁移完成配置文件以后,无法正常登录,显示帐号或密码错误
我能确定帐号和密码是正确的

**复现方法**
1. 更新gocqhttp到v0.9.24
2. 配置好文件登录

**Comment by wdvxdr1123** [comment]
我用了最新版，是正常的

**Comment by mnixry** [comment]
> 我用了最新版，是正常的

蛮怪的.jpg

**Comment by Mrs4s** [comment]
奇怪了 我这边没这种问题.jpg 检查下有没有多的空格？

**Comment by mnixry** [comment]
> 奇怪了 我这边没这种问题.jpg 检查下有没有多的空格？

刚刚看了一下release 发现一个有趣的事情
