### ISSUE TITLE
[Bug]: 彻底挂啦 用go登陆一个挂一个

### ISSUE THREAD

**Issue by Lioncky** [Mrs4s/go-cqhttp#2493]
# 注意啦 

不管是旧的go还是新的 刚刚彻底挂了 挂了以后8.9.76限制不可能录 8.9.78正常
不经常用 但是突然大面积拉闸估计出事情了

**Comment by zenghx** [comment]
用watch苟活

**Comment by diyigemt** [comment]
明天就是开发者大会了，不知道之后的走向会怎么样

**Comment by duoshoumiao** [comment]
> 用watch苟活

那风控后要等多久

**Comment by zenghx** [comment]
> > 用watch苟活
> 
> 那风控后要等多久

我现在是晚上被禁言，第二天白天又好了

**Comment by duoshoumiao** [comment]
> > > 用watch苟活
> > 
> > 那风控后要等多久
> 
> 我现在是晚上被禁言，第二天白天又好了

只有晚上不能用吗

**Comment by 1umine** [comment]
> > > > 用watch苟活
> > > 
> > > 那风控后要等多久
> > 
> > 我现在是晚上被禁言，第二天白天又好了
> 
> 只有晚上不能用吗

是每天只能发个10条左右的消息

**Comment by lee86** [comment]
腾讯的qqbot api再等等看看吧...现在个人开发者只能申请到频道的机器人，企业开发者可以使用qq和群机器人...

**Comment by jiangyin14** [comment]
换个新的协议试试看吧，现在出8.9.90了，前面还有80，83，85，88可以换，再换一换新协议看嘛

**Comment by 1umine** [comment]
> 是每天只能发个10条左右的消息

使用手表协议
```json
{
  "apk_id": "com.tencent.qqlite",
  "app_id": 537140974,
  "sub_app_id": 537140974,
  "sort_version_name": "2.1.7",
  "build_time": 1654570540,
  "apk_sign": "a6b745bf24a2c277527716f6f36eb68d",
  "sdk_version": "6.0.0.2366",
  "sso_version": 5,
  "misc_bitmap": 16252796,
  "main_sig_map": 16724722,
  "sub_sig_map": 66560,
  "dump_time": "1654570540",
  "protocol_type": 2
}
```
填入 `data/versions/2.json` 
似乎可以解除群聊的风控，但是私聊又会风控（悲）

**Comment by lee86** [comment]
> > 是每天只能发个10条左右的消息
> 
> 使用手表协议登陆
> 
> ```json
> {
>   "apk_id": "com.tencent.qqlite",
>   "app_id": 537140974,
>   "sub_app_id": 537140974,
>   "sort_version_name": "2.1.7",
>   "build_time": 1654570540,
>   "apk_sign": "a6b745bf24a2c277527716f6f36eb68d",
>   "sdk_version": "6.0.0.2366",
>   "sso_version": 5,
>   "misc_bitmap": 16252796,
>   "main_sig_map": 16724722,
>   "sub_sig_map": 66560,
>   "dump_time": "1654570540",
>   "protocol_type": 2
> }
> ```
> 
> 填入 `data/versions/2.json` 似乎可以解除群聊的风控，但是私聊又会风控（悲）

手表协议以前就这样好像...有时候都以为挂了

**Comment by 1umine** [comment]
> > > 是每天只能发个10条左右的消息
> > 
> > 使用手表协议登陆
> > 
> > ```json
> > {
> >   "apk_id": "com.tencent.qqlite",
> >   "app_id": 537140974,
> >   "sub_app_id": 537140974,
> >   "sort_version_name": "2.1.7",
> >   "build_time": 1654570540,
> >   "apk_sign": "a6b745bf24a2c277527716f6f36eb68d",
> >   "sdk_version": "6.0.0.2366",
> >   "sso_version": 5,
> >   "misc_bitmap": 16252796,
> >   "main_sig_map": 16724722,
> >   "sub_sig_map": 66560,
> >   "dump_time": "1654570540",
> >   "protocol_type": 2
> > }
> > ```
> > 
> > 填入 `data/versions/2.json` 似乎可以解除群聊的风控，但是私聊又会风控（悲）
> 
> 手表协议以前就这样好像...有时候都以为挂了

之前是群聊风控私聊不控，这个是私聊风控群聊不控（

**Comment by Ayase-Naka-a** [comment]
> > > > 是每天只能发个10条左右的消息
> > > 
> > > 
> > > 使用手表协议登陆
> > > ```json
> > > {
> > >   "apk_id": "com.tencent.qqlite",
> > >   "app_id": 537140974,
> > >   "sub_app_id": 537140974,
> > >   "sort_version_name": "2.1.7",
> > >   "build_time": 1654570540,
> > >   "apk_sign": "a6b745bf24a2c277527716f6f36eb68d",
> > >   "sdk_version": "6.0.0.2366",
> > >   "sso_version": 5,
> > >   "misc_bitmap": 16252796,
> > >   "main_sig_map": 16724722,
> > >   "sub_sig_map": 66560,
> > >   "dump_time": "1654570540",
> > >   "protocol_type": 2
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 填入 `data/versions/2.json` 似乎可以解除群聊的风控，但是私聊又会风控（悲）
> > 
> > 
> > 手表协议以前就这样好像...有时候都以为挂了
> 
> 之前是群聊风控私聊不控，这个是私聊风控群聊不控（

感谢分享方法，先试试

**Comment by CatOverrun** [comment]
80， 85 安卓平板 手表 均挂。
静等了，不折腾了

**Comment by Adogs1** [comment]
> 腾讯的qqbot api再等等看看吧...现在个人开发者只能申请到频道的机器人，企业开发者可以使用qq和群机器人...

现在有类似cqhttp的个人频道机器人吗？我想用于连接Minecraft与QQ

**Comment by jiangyin14** [comment]
> > 腾讯的qqbot api再等等看看吧...现在个人开发者只能申请到频道的机器人，企业开发者可以使用qq和群机器人...
> 
> 
> 
> 现在有类似cqhttp的个人频道机器人吗？我想用于连接Minecraft与QQ

https://github.com/17TheWord/nonebot-plugin-mcqq
有nonebot/python基础可以看看，部署相对简单，支持频道
熟悉yunzai的话也可以看看https://github.com/CikeyQi/mc-plugin
也是支持trssyz用频道适配器的

**Comment by Adogs1** [comment]
> > > 腾讯的qqbot api再等等看看吧...现在个人开发者只能申请到频道的机器人，企业开发者可以使用qq和群机器人...
> > 
> > 
> > 现在有类似cqhttp的个人频道机器人吗？我想用于连接Minecraft与QQ
> 
> https://githubfast.com/17TheWord/nonebot-plugin-mcqq 有nonebot/python基础可以看看，部署相对简单，支持频道 熟悉yunzai的话也可以看看 https://githubfast.com/CikeyQi/mc-plugin 也是支持trssyz用频道适配器的 yunzai还有 https://gitee.com/xiaofei20625/space-xiao_minecraft 具体没测试trss（也就是频道接入）可不可行

是基于官方的bot吗？不会被风控？

**Comment by waner1998** [comment]
境外目前一切正常

**Comment by ASAServer** [comment]
qq升级9版本 架构变了，我的机器人也全挂了。

**Comment by jiangyin14** [comment]
> > > > 腾讯的qqbot api再等等看看吧...现在个人开发者只能申请到频道的机器人，企业开发者可以使用qq和群机器人...
> 
> > > 
> 
> > > 
> 
> > > 现在有类似cqhttp的个人频道机器人吗？我想用于连接Minecraft与QQ
> 
> > 
> 
> > https://githubfast.com/17TheWord/nonebot-plugin-mcqq 有nonebot/python基础可以看看，部署相对简单，支持频道 熟悉yunzai的话也可以看看 https://githubfast.com/CikeyQi/mc-plugin 也是支持trssyz用频道适配器的 yunzai还有 https://gitee.com/xiaofei20625/space-xiao_minecraft 具体没测试trss（也就是频道接入）可不可行
> 
> 
> 
> 是基于官方的bot吗？不会被风控？

第一个链接里面的可以使用nonebot的qq-adapter，接入官方SDK，不会被搞

**Comment by changwenpeng** [comment]
[![image](https://github.com/Mrs4s/go-cqhttp/assets/106914239/b6d8f4f8-80e2-4413-ab90-af061b701252)
](https://gitee.com/changwenpeng/gocqhttp-qqsign)
来这里了

**Comment by Lioncky** [comment]
本人已找到替代方案 这个issue关闭了
