### ISSUE TITLE
[Bug]: 自定义回复消息发送显示异常

### ISSUE THREAD

**Issue by LengYue12138** [Mrs4s/go-cqhttp#2494]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.2.0

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

HTTP

### 使用协议

6 | aPad

### 重现步骤

发送复现代码

### 期望的结果是什么？

![1](https://github.com/Mrs4s/go-cqhttp/assets/103752341/d635e24f-d6b1-4358-a266-e226bd46adb8)

### 实际的结果是什么？

![2](https://github.com/Mrs4s/go-cqhttp/assets/103752341/7512bb66-2587-4d72-9a40-e5e69cf9d044)

### 简单的复现代码/链接（可选）

```golang
http://127.0.0.1:5700/send_group_msg?group_id=12345678&message=[CQ:reply,id=215960718,seq=76690,qq=2133763860,time=1699763125,text=文字][CQ:at,qq=12345678] 文字
```

**Comment by sevenstars0** [comment]
我也有这个问题，使用[CQ:reply,id=1234567890]无法正常显示，id就是从事件里获取的message_id。现在先用@功能代替吧，也不知道什么时候修复。

**Comment by LengYue12138** [comment]
您好，我已接收到您的邮件并会仔细阅读，如有紧急事项请通过手机联系我，谢谢！
