### ISSUE TITLE
能否新增支持，自动从qsign-api获得协议信息？

### ISSUE THREAD

**Issue by mmmjie** [Mrs4s/go-cqhttp#2499]
现在用新的qsign 协议除了api要更新，本地协议文件也要手动更新，就是6.json 那个。
我没用过mirai，似乎那边好像是自动从api获得协议信息，不需要手动配置本地协议？

目前用的sm提供的api，直接更新QQ就可以了，不需要逆向获得协议文件和信息，
但go-cq本地的协议文件手动获取就变的很麻烦了。

反馈版本：1.2.0

**Comment by ovooa** [comment]
协议信息位于安装包的dex层，自行提取
