### ISSUE TITLE
cardimage是否只能在手机查看

### ISSUE THREAD

**Issue by zangxx66** [Mrs4s/go-cqhttp#250]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: go-cqhttp-v0.9.24-linux-amd64
运行环境: linux-amd64
连接方式: 反向WS

**bug内容**
请在这里详细描述bug的内容
使用MessageSegment构造cardimage类型的CQ码，只能在手机上面查看，PC会显示空白消息，请问cardimage只能在手机查看，还是它不支持PC版的TIM
**复现方法**
请在这里分步骤的描述如何复现这个bug
1.使用MessageSegment构造cardimage类型的CQ码  
2.await bot.send(event,  pic)发送上一步构造好的CQ码  
3.TIM PC只能看到空白消息，手机端可查看图片卡片

**Comment by scjtqs** [comment]
tim那边我不确认是否支持，因为我也没用过。pc qq，mac qq，安卓和ios应该都能看得到的。毕竟就是个特殊点的xml。
目前有一个已知问题：
1、ios可以直接看到图片，但是点击图片图片的时候，加载一直0%。这个应该是图片上传到tx的时候参数和xml有点没对齐，后面慢慢找找原因。
