### ISSUE TITLE
[Bug]: 无法发送回复消息

### ISSUE THREAD

**Issue by xiaosuyyds** [Mrs4s/go-cqhttp#2505]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.2.0

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

HTTP

### 使用协议

6 | aPad

### 重现步骤

再次发送带有回复消息的群消息

### 期望的结果是什么？

成功发送回复消息

### 实际的结果是什么？

回复消息发送不出来但是附带的其他消息却可以
例如：发送[CQ:reply,text=test！,qq=123456] HelloWorld 结果: HelloWorld
再例如：发送[CQ:reply,id=123456] test 结果: test
日志中也没有提示CQ码转换异常

**Comment by jiangyin14** [comment]
没图咋看
而且不要用1.2.0，你的问题在开发版中很可能已经被修复了

**Comment by PhyX-Meow** [comment]
我遇到了同样的问题，具体表现是发不出形如这样的引用消息
![image](https://github.com/Mrs4s/go-cqhttp/assets/17513581/ec87626b-21e7-49f2-b301-5059a0df9373)
bot发出来的消息只有文本部分，而不会引用消息源

**Comment by xiaosuyyds** [comment]
在最新的dev版本中此bug已被修复
