### ISSUE TITLE
正向 ws 连接失败，空 Token 或传入格式错误

### ISSUE THREAD

**Issue by Lancercmd** [Mrs4s/go-cqhttp#251]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.24
运行环境: windows_amd64
连接方式: 正向WS

**bug内容**
有 access_token 且一致的情况下，连接 go-cqhttp 提示已拒绝 Websocket 请求：空 Token 或传入格式错误
关键配置相同的情况下，v0.9.22 无此问题

**复现方法**
在设置一个 access_token 的前提下部署 Tsuk1ko/cq-picsearcher-bot 并成功运行

**Comment by Tsuk1ko** [comment]
@Mrs4s 使用的是 [momocow/node-cq-websocket](https://github.com/momocow/node-cq-websocket)，v0.9.23 正常，v0.9.24 出现上述情况

附上 Wireshark 抓包 [go-cqhttp-wireshark.zip](https://github.com/Mrs4s/go-cqhttp/files/5189939/go-cqhttp-wireshark.zip)

是否是这一逻辑改动导致的问题？

https://github.com/Mrs4s/go-cqhttp/compare/v0.9.23...v0.9.24#diff-f5d1e41840e76e574d59587161666897L207-R241

**Comment by Mrs4s** [comment]
> @Mrs4s SDK 使用的是 [momocow/node-cq-websocket](https://github.com/momocow/node-cq-websocket)，v0.9.23 正常，v0.9.24 出现上述情况
> 
> 附上 Wireshark 抓包 [go-cqhttp-wireshark.zip](https://github.com/Mrs4s/go-cqhttp/files/5189939/go-cqhttp-wireshark.zip)
> 
> 是否是这一逻辑改动导致的问题？
> 
> [v0.9.23...v0.9.24diff-f5d1e41840e76e574d59587161666897L207-R241](https://github.com/Mrs4s/go-cqhttp/compare/v0.9.23...v0.9.24diff-f5d1e41840e76e574d59587161666897L207-R241)

感谢抓包，已确认是新版本的bug, 正在处理

**Comment by CabbCat** [comment]
问一下设置了access token之后要如何上传token呢，新手不是很懂orz
