### ISSUE TITLE
[CQ:reply] 在安卓手机 QQ 上无法正常显示

### ISSUE THREAD

**Issue by xb2016** [Mrs4s/go-cqhttp#253]
**环境信息**
go-cqhttp版本: v0.9.22 - v0.9.24
运行环境: windows_amd64
连接方式: 正向WS

**bug内容**
自 0.9.22 版本起，`[CQ:reply]` 在安卓手机 QQ 上无法正常显示回复，而在 PC 上正常显示，如下图：
![图片](https://user-images.githubusercontent.com/31783875/92543843-11b40400-f27f-11ea-8300-638c5c39854d.png)
![图片](https://user-images.githubusercontent.com/31783875/92543865-1d9fc600-f27f-11ea-8395-9ba773a1501e.png)

另，在安卓 QQ 8.1 以下版本会导致该条消息不可见，需要重启手机 QQ 才会显示，同时如上图一样也不能正常显示回复

**复现方法**
发送任意 `[CQ:reply]`

**Comment by Mrs4s** [comment]
请尝试 https://github.com/Mrs4s/go-cqhttp/actions/runs/247290134

**Comment by xb2016** [comment]
测试正常了，感谢
