### ISSUE TITLE
支持官版api

### ISSUE THREAD

**Issue by jdnjk** [Mrs4s/go-cqhttp#2532]
**环境信息**

go-cqhttp版本: 

**需要添加的功能内容**
都放开了，可以进q群

**Comment by jdnjk** [comment]
> ![image](https://github.com/user-attachments/assets/55af2504-f7d9-47b5-ba65-a7097622e88e)
> 

那个老久没改了，现在是个人可以

**Comment by RushCN** [comment]
可以用了？

**Comment by jdnjk** [comment]
> 可以用了？
> 

q群部分功能可以使用

**Comment by RushCN** [comment]
> > 可以用了？
> > 
> 
> q群部分功能可以使用

一个月才4条主动信息够啥用啊（）

**Comment by metaforget** [comment]
现在有能用官方机器人的项目吗

**Comment by RushCN** [comment]
> 现在有能用官方机器人的项目吗

koishi和nonebot都行

**Comment by cxbyyq** [comment]
能拉群消息吗？

**Comment by jdnjk** [comment]
> > > 可以用了？
> > > 
> > 
> > q群部分功能可以使用
> 
> 一个月才4条主动信息够啥用啊（）

沙箱体验无限主动

**Comment by jdnjk** [comment]
> 能拉群消息吗？
机器人进群可以自动发送
