### ISSUE TITLE
接收bilibili小程序信息时出错

### ISSUE THREAD

**Issue by rbameto** [Mrs4s/go-cqhttp#255]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.24
运行环境: CentOS Linux release 7.8.2003 (Core)
连接方式: 反向WS

**bug内容**
无法接收bilibili小程序信息
收到时提示
`[ERROR]: Protocol -> panic on decoder: runtime error: invalid memory address or nil pointer dereference `

v0.9.23时正常

**复现方法**
b站手机app分享至qq群内

**Comment by ishkong** [comment]
同样遇到
go-cqhttp版本：actions/runs/245477636
`[2020-09-09 14:09:51] [DEBUG]: Protocol -> rev pkt: OnlinePush.PbPushGroupMsg seq: 13969 
[2020-09-09 14:09:51] [DEBUG]: Protocol -> rev pkt: MultiMsg.ApplyDown seq: 13895 
[2020-09-09 14:09:51] [ERROR]: Protocol -> panic on decoder: runtime error: invalid memory address or nil pointer dereference `

**Comment by wdvxdr1123** [comment]
挺神奇的，从b站发的不行，经过转发的可以正常接收

**Comment by zangxx66** [comment]
我也遇到了，不仅是小程序卡片，网页分享卡片也不行，我猜测应该是[CQ:rich]都有这问题  
go-cqhttp版本：go-cqhttp-v0.9.24-linux-amd64  
[ERROR]: Protocol -> panic on decoder: runtime error: invalid memory address or nil pointer dereference

**Comment by Mrs4s** [comment]
可能是我吧小程序部分改炸了，马上看看
