### ISSUE TITLE
 创建群-选人建群 无法接收到信息。

### ISSUE THREAD

**Issue by DieMoe233** [Mrs4s/go-cqhttp#257]
**环境信息**
go-cqhttp版本: v0.9.24 （从源码编译
运行环境: windows_amd64

**bug内容**
本来想用miraiGo的协议重构塔塔露底层的，然后发现，应用新协议后，部分群的信息无法同步成功。

发现复现方法了。

**复现方法**
创建群聊，选人建群。
以此方式建的群，统一收不到消息。

**Comment by Mrs4s** [comment]
应该是群过多造成的？ 目前我有策略是不响应群列表内不存在的群

**Comment by DieMoe233** [comment]
> 应该是群过多造成的？ 目前我有策略是不响应群列表内不存在的群

使用分类建群没有此问题。

**Comment by DieMoe233** [comment]
已解决。

**Comment by Mrs4s** [comment]
@DieMoe233 有空能不能帮忙测试下这个版本 https://github.com/Mrs4s/go-cqhttp/actions/runs/247256595 能不能正常获取到超过1000个群
