### ISSUE TITLE
反向ws邀请进群不推送event

### ISSUE THREAD

**Issue by jdgjxxchy** [Mrs4s/go-cqhttp#259]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.24
运行环境: windows_amd64, maxOS
连接方式: 反向WS

**bug内容**
RT, 邀请机器人进群之后, 表现为:
1. 提示 成功发送邀请, 待管理员审核.
2. 私聊对话框内不再有 邀请进群消息.
3. 没有上报被邀请的信息.

**复现方法**
0.9.24版本邀请机器人进群

**Comment by corvo007** [comment]
补充：在go登录时登录bot号并手动发送邀请，控制台与私聊窗口中皆没有任何入群邀请

**Comment by var-mixer** [comment]
即便不登录go-cqhttp，单纯用手机登录此账号，依然接收不到加群邀请。可能是账号原因，前日开始偶尔出现，今日开始所有机器人账号都收不到加群邀请。

**Comment by chenxuxin188** [comment]
应该TX服务器的问题。我这也是一样，有一个QQ一直

```
[2020-09-11 18:51:22] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
[2020-09-11 18:51:25] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
[2020-09-11 18:51:28] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
[2020-09-11 18:51:32] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
[2020-09-11 18:51:35] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
[2020-09-11 18:51:38] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
```

同样的QQ，我在我自己加的电脑连220开头的IP的服务器完全没有问题，但是
`120.232.18.xxx`

这个的就一直报错

**Comment by chenxuxin188** [comment]
> 应该TX服务器的问题。我这也是一样，有一个QQ一直
> 
> ```
> [2020-09-11 18:51:22] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> [2020-09-11 18:51:25] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> [2020-09-11 18:51:28] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> [2020-09-11 18:51:32] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> [2020-09-11 18:51:35] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> [2020-09-11 18:51:38] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> ```
> 
> 同样的QQ，我在我自己加的电脑连220开头的IP的服务器完全没有问题，但是
> `120.232.18.xxx`
> 
> 这个的就一直报错

不是报错，就是一直在重连，然后偶尔来个`[2020-09-11 18:51:42] [ERROR]: Protocol -> panic on decoder: EOF`

**Comment by Mrs4s** [comment]
> > 应该TX服务器的问题。我这也是一样，有一个QQ一直
> > ```
> > [2020-09-11 18:51:22] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > [2020-09-11 18:51:25] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > [2020-09-11 18:51:28] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > [2020-09-11 18:51:32] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > [2020-09-11 18:51:35] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > [2020-09-11 18:51:38] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > ```
> > 
> > 
> > 同样的QQ，我在我自己加的电脑连220开头的IP的服务器完全没有问题，但是
> > `120.232.18.xxx`
> > 这个的就一直报错
> 
> 不是报错，就是一直在重连，然后偶尔来个`[2020-09-11 18:51:42] [ERROR]: Protocol -> panic on decoder: EOF`

请使用最新的Release

**Comment by chenxuxin188** [comment]
> > > 应该TX服务器的问题。我这也是一样，有一个QQ一直
> > > ```
> > > [2020-09-11 18:51:22] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > > [2020-09-11 18:51:25] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > > [2020-09-11 18:51:28] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > > [2020-09-11 18:51:32] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > > [2020-09-11 18:51:35] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > > [2020-09-11 18:51:38] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > > ```
> > > 
> > > 
> > > 同样的QQ，我在我自己加的电脑连220开头的IP的服务器完全没有问题，但是
> > > `120.232.18.xxx`
> > > 这个的就一直报错
> > 
> > 
> > 不是报错，就是一直在重连，然后偶尔来个`[2020-09-11 18:51:42] [ERROR]: Protocol -> panic on decoder: EOF`
> 
> 请使用最新的Release

我现在有用的是0.9.24没fix的

> > > 应该TX服务器的问题。我这也是一样，有一个QQ一直
> > > ```
> > > [2020-09-11 18:51:22] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > > [2020-09-11 18:51:25] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > > [2020-09-11 18:51:28] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > > [2020-09-11 18:51:32] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > > [2020-09-11 18:51:35] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > > [2020-09-11 18:51:38] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > > ```
> > > 
> > > 
> > > 同样的QQ，我在我自己加的电脑连220开头的IP的服务器完全没有问题，但是
> > > `120.232.18.xxx`
> > > 这个的就一直报错
> > 
> > 
> > 不是报错，就是一直在重连，然后偶尔来个`[2020-09-11 18:51:42] [ERROR]: Protocol -> panic on decoder: EOF`
> 
> 请使用最新的Release

好了没问题了

**Comment by jdgjxxchy** [comment]
> > > 应该TX服务器的问题。我这也是一样，有一个QQ一直
> > > ```
> > > [2020-09-11 18:51:22] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > > [2020-09-11 18:51:25] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > > [2020-09-11 18:51:28] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > > [2020-09-11 18:51:32] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > > [2020-09-11 18:51:35] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > > [2020-09-11 18:51:38] [INFO]: Protocol -> connect to server: 120.232.18.61:8080 
> > > ```
> > > 
> > > 
> > > 同样的QQ，我在我自己加的电脑连220开头的IP的服务器完全没有问题，但是
> > > `120.232.18.xxx`
> > > 这个的就一直报错
> > 
> > 
> > 不是报错，就是一直在重连，然后偶尔来个`[2020-09-11 18:51:42] [ERROR]: Protocol -> panic on decoder: EOF`
> 
> 请使用最新的Release

使用了最新的release 还是偶尔接收不到加群邀请 可能是tx问题?

**Comment by allofee** [comment]
最新版基本都收不到邀请加群的消息，手机QQ也收不到邀请通知，像是账号风险的问题

**Comment by corvo007** [comment]
> 最新版基本都收不到邀请加群的消息，手机QQ也收不到邀请通知，像是账号风险的问题

是的，我有个账号已经彻底不行了，连手动上号加群都不行了，应该是进黑名单了

**Comment by sam01101** [comment]
应该是腾讯的风控问题, 请注意好机器人的防护, 以免被风控

**Comment by sam01101** [comment]
Ready to close @Mrs4s
