### ISSUE TITLE
临时聊天信息发送失败

### ISSUE THREAD

**Issue by wordgao** [Mrs4s/go-cqhttp#26]
临时聊天信息发送失败

**Comment by Mrs4s** [comment]
为防止滥用，目前仅支持临时消息的接收，并且无计划支持发送.

**Comment by wordgao** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
            您好，我的用途主要是根据客户的关键字来判断自己的数据库信息是否匹配，当匹配的时候，则建立会话机制，因为我的用途就是监控所有群用户信息，并通过程序过滤，因为需要对话的不一定是好友。所以目前发现不能临时会话，另外因为目前很多群禁止了临时会话，当非好友状态时，我会@用户，但目前发现@用户也无法正常使用。
        
    
        
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                wordgao
                            
                    
                        
                            
                                    wordgao@gmail.com
                            
                        
                
            
        
        
    
    在2020年8月4日 22:58，Mrs4s<notifications@github.com> 写道： 




为防止滥用，目前仅支持临时消息的接收，并且无计划支持发送.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Mrs4s** [comment]
目前并没有计划支持临时消息发送。被滥用的可能性很大
