### ISSUE TITLE
私聊收到 reply id 与发送不一致

### ISSUE THREAD

**Issue by Shigma** [Mrs4s/go-cqhttp#261]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.24
运行环境: windows_amd64
连接方式: http

**bug内容**
如题。

**复现方法**
调用 send_private_msg，返回的消息 ID 为 `-1860966221`，然后在同一会话中回复上述消息，发现开头是 `[CQ:reply,id=1994677360]`，两者并不一致。

**Comment by Mrs4s** [comment]
需要修改私聊为long text发送才能修复此bug

**Comment by liliangshan** [comment]
临时解决了，# 为Reply附加更多信息
  extra-reply-data: true 打开可以取到原消息的内容，然后对里面的数据匹配指定回复保存

**Comment by jianmj** [comment]
> 临时解决了，# 为Reply附加更多信息
> extra-reply-data: true 打开可以取到原消息的内容，然后对里面的数据匹配指定回复保存

好耶，我赶紧换成 v1 版本， 感谢

**Comment by wdvxdr1123** [comment]
请尝试使用版本 [ca16e4c](https://github.com/Mrs4s/go-cqhttp/actions/runs/852491411)

**Comment by sam01101** [comment]
> 请尝试使用版本 [ca16e4c](https://github.com/Mrs4s/go-cqhttp/actions/runs/852491411)

好的, 明天尝试
