### ISSUE TITLE
启用access_token无法连接：空Token或传入格式错误

### ISSUE THREAD

**Issue by pokebox** [Mrs4s/go-cqhttp#262]
**环境信息**
go-cqhttp版本: v0.9.24
运行环境: windows_amd64
连接方式: WS

**bug内容**
由0.9.23更新到0.9.24后，首先配置文件不兼容，更新配置文件后保持原有access_token信息。启动服务，使用websocket方式连接时失败并在服务端弹出警告：
`[2020-09-11 10:13:30] [WARNING]: 已拒绝 127.0.0.1:38037 的 Websocket 请求: 空Token或传入格式错误`
在0.9.23之前版本无问题。

**复现方法**
config.json设置access_token信息，连接端使用ws://127.0.0.1:12345/?access_token=xxxx方式连接，将导致连接失败。

**Comment by Mrs4s** [comment]
#251
