### ISSUE TITLE
心跳包设为0时无法关闭

### ISSUE THREAD

**Issue by pokebox** [Mrs4s/go-cqhttp#263]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: master (09aa852308c314b92c02943f493918e2887f1be4)
运行环境: windows_amd64
连接方式: WS

**bug内容**
config.json中将心跳包设为0时，无法关闭心跳包功能。
代码中似乎改成了小于0关闭，0默认为5秒一次，确认后续是否继续按目前逻辑工作并更新文档。

**复现方法**
在设置config.json
`"heartbeat_interval": 0,`启动程序，在开启debug模式下每5秒显示一次推送event。

**Comment by wdvxdr1123** [comment]
-1是关闭，你没看readme（滑稽

**Comment by pokebox** [comment]
> -1是关闭，你没看readme（滑稽

嗐，现在明明cqhttp.md没更新（狗头
