### ISSUE TITLE
占用率显示100%

### ISSUE THREAD

**Issue by rubbish-wang** [Mrs4s/go-cqhttp#265]
环境信息
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.24
运行环境: windows_amd64
连接方式: 反向WS

[2020-09-11 11:16:42] [INFO]: Protocol -> connect to server: x.x.x.x:8080
[2020-09-11 11:16:46] [INFO]: Protocol -> connect to server: x.x.x.x:8080
[2020-09-11 11:16:03] [INFO]: Protocol -> connect to server: x.x.x.x:8080
[2020-09-11 11:16:05] [INFO]: Protocol ->panic on decoder：EOF

**Comment by rubbish-wang** [comment]
> 环境信息
> 请根据实际使用环境修改以下信息
> go-cqhttp版本: v0.9.24
> 运行环境: windows_amd64
> 连接方式: 反向WS
> 
> [2020-09-11 11:16:42] [INFO]: Protocol -> connect to server: x.x.x.x:8080
> [2020-09-11 11:16:46] [INFO]: Protocol -> connect to server: x.x.x.x:8080
> [2020-09-11 11:16:03] [INFO]: Protocol -> connect to server: x.x.x.x:8080
> [2020-09-11 11:16:03] [INFO]: Protocol ->panic on decoder：EOF

**Comment by Wgaham** [comment]
和版本无关 v0.9.23也可复现，怀疑和mirai有关，可能tx修改了协议

**Comment by Akegarasu** [comment]
同样问题 看起来是miraiGO的问题 突然出问题应该就是tx改了

**Comment by LR1093141031** [comment]
问题同样
![QQ图片20200911131512](https://user-images.githubusercontent.com/50727631/92865635-23d5a400-f431-11ea-8bfa-a684d5a280b3.png)
![QQ图片20200911131503](https://user-images.githubusercontent.com/50727631/92865638-2506d100-f431-11ea-8b15-12d2102cfa1d.png)

**Comment by pokebox** [comment]
![image](https://user-images.githubusercontent.com/8972828/92865857-6d25f380-f431-11ea-8b2c-cbdc41bfdc61.png)
linux占用率正常，但是在报同样错误，功能使用暂时也正常。

**Comment by allofee** [comment]
是今天突然出现的问题，内存占用也爆炸了

`panic on decoder: EOF`

**Comment by ivanallen** [comment]
![image](https://user-images.githubusercontent.com/12481610/92874533-b3cc1b80-f43a-11ea-9e8c-d2e14a4694d6.png)

![image](https://user-images.githubusercontent.com/12481610/92874553-b9c1fc80-f43a-11ea-9a30-edbdc5c604d2.png)

**Comment by Mrs4s** [comment]
#266

**Comment by witpark** [comment]
我的也是恢复到22版本就好了
