### ISSUE TITLE
最新版arm下CPU 内存爆掉的 

### ISSUE THREAD

**Issue by samondlee** [Mrs4s/go-cqhttp#266]
go-cqhttp版本: v0.9.24
运行环境: arm armbian phicomm N1
连接方式: 反向WS
![捕获](https://user-images.githubusercontent.com/8521327/92860524-ef5ee980-f42a-11ea-98dc-9feffac66f3c.PNG)

**bug内容**
请在这里详细描述bug的内容

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by samondlee** [comment]
只跑了一个hoshinot 加了3个群 而且使用率并不高

**Comment by LR1093141031** [comment]
![QQ图片20200911131503](https://user-images.githubusercontent.com/50727631/92865505-fbe64080-f430-11ea-8763-e9ea817c07a7.png)
![QQ图片20200911131512](https://user-images.githubusercontent.com/50727631/92865508-fc7ed700-f430-11ea-881a-e06c2ccdf304.png)

**Comment by RJCooLEST** [comment]
am64与386同样也出现该问题，与上述问题描述一致，原因不明确。

**Comment by Mrs4s** [comment]
此错误是因为TX某些服务器突然爆炸导致的，将在今天晚上之前解决

**Comment by Mrs4s** [comment]
请尝试最新版的Release
