### ISSUE TITLE
不确定是因为风控还是协议的问题，长消息发不了

### ISSUE THREAD

**Issue by chenxuxin188** [Mrs4s/go-cqhttp#269]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.24 - fix2
运行环境:  linux_amd64
连接方式: 反向WS

**bug内容**
不知道是不是因为服务器协议变了还是风控

`收到服务器地址更新通知, 将在下一次重连时应用. 服务器地址: 124.156.215.228:10001 服务: others `

提示这个的QQ长消息发不了。没提示这个的正常。

消息：
`'浏览器打开军火库军团页面网址（新增造船厂）\n先进官网登陆自己的账号，然后打开对应的网址即可\n官网https://worldofwarships.eu/en/news\n军火库\nhttps://armory.worldofwarships.eu/en\n造船厂\nhttps://dockyard.worldofwarships.eu/\n军团\nhttps://clans.worldofwarships.eu/clans/gateway/wows/profile\n仓库\nhttp://warehouse.worldofwarships.eu\n技能模拟器\nhttps://worldofwarships.asia/zh-tw/content/commander-skill-simulator/?skills=&ship=Battleship\n模型查看\nhttps://gamemodels3d.com/games/worldofwarships/\n浩舰-海战爱好者\nhttps://iwarship.net/'`

这么长的

短的消息带网页的能正常发，图片语音什么的也都没问题

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by Mrs4s** [comment]
fixed
