### ISSUE TITLE
群用户权限判断失真

### ISSUE THREAD

**Issue by wordgao** [Mrs4s/go-cqhttp#27]
发现新的问题了，不能临时聊天，临时聊天失败。
发现判断群用户权限失真，用户识别信息以及权限好像与CQ的有差异，不知道是否有颠倒字段顺序。

**Comment by Mrs4s** [comment]
能否贴一下怎么判断权限的

**Comment by wordgao** [comment]
还在继续测试中，有可能与缓存有关系。等确认后发您邮箱。

**Comment by wordgao** [comment]
请查收邮件中的截图。

**Comment by remiliacn** [comment]
我怎么记得好像原来的CoolQ也有判断qq群内成员权限失真的这个问题？

**Comment by Mrs4s** [comment]
可能是缓存的因素，我检查代码后并没有发现有什么不对的地方
[CQHTTP文档](https://richardchien.gitee.io/coolq-http-api/docs/4.15/#/API?id=get_group_member_info-%E8%8E%B7%E5%8F%96%E7%BE%A4%E6%88%90%E5%91%98%E4%BF%A1%E6%81%AF)
代码:
https://github.com/Mrs4s/go-cqhttp/blob/bc47267c3c9d5f616ce2db4c1d7dcb4b4eb6c8a5/coolq/api.go#L528-L536
请尝试在请求加入 `no_cache` 参数
