### ISSUE TITLE
在发送图片信息后紧接发送文字信息有时会错位接受

### ISSUE THREAD

**Issue by Pzzzzz5142** [Mrs4s/go-cqhttp#271]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.24-fix2
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
发完图然后发文字的话接受设备消息收取错位。

**复现方法**
先发一个图片消息，然后发文字消息。当前在前台收消息的设备在接受消息的时候是错位获取的。但是其他设备收取消息是没有错位问题的。
当前设备为Mac QQ：
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/31173671/92986955-f51f0280-f4f0-11ea-81ea-fb611bbd806c.png">
消息错位了！

与此同时的ipad QQ（未在前台获取消息）：
![IMG_80513808C38C-1](https://user-images.githubusercontent.com/31173671/92986981-20095680-f4f1-11ea-8d4a-0ab49fb0ed5d.jpeg)

与此同时的iphone QQ（未在前台获取消息）：
![IMG_972CE3848C39-1](https://user-images.githubusercontent.com/31173671/92986993-33b4bd00-f4f1-11ea-8c1a-6cb47c4adf97.jpeg)

如果多个设备在前台接受消息，有些设备是正常顺序，有些是错位接受。

**Comment by Pzzzzz5142** [comment]
发消息的方式是`bot.send_private_msg`。（之前在cq上是🈚️问题的（（（

**Comment by Ink-33** [comment]
这难道不是接受设备网络问题吗（（（

**Comment by wdvxdr1123** [comment]
你可以用_rate_limit限速，速度慢了就不会错位了(雾

**Comment by Pzzzzz5142** [comment]
（好有道理（（（事我的问题了

> 你可以用_rate_limit限速，速度慢了就不会错位了(雾
