### ISSUE TITLE
cq码插空格会导致无法识别

### ISSUE THREAD

**Issue by Pzzzzz5142** [Mrs4s/go-cqhttp#272]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.24-fix2
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
cq码插入空格会导致其无法被识别

**复现方法**
<img width="598" alt="image" src="https://user-images.githubusercontent.com/31173671/92993769-e3585200-f526-11ea-9339-07ae41dac38c.png">

其他cq码未能测试。但是json的cq码也有类似问题。这导致不能直接使用`str(*json对象*)`来完成data的填充。（虽然能直接拼接字符串完成相似功能（（

**Comment by Mrs4s** [comment]
消息段相关请参考文档 [CQ码格式](https://github.com/howmanybots/onebot/blob/master/v11/specs/message/string.md#cq-%E7%A0%81%E6%A0%BC%E5%BC%8F)
> 注意
CQ 码中不应有多余的空格，例如不应该使用 [CQ:face, id=178]。
CQ 码的参数值可以包含空格、换行、除 [],& 之外的特殊符号等。在解析时，应直接取 [CQ: 后、第一个 , 或 ] 前的部分为功能名，第一个 , 之后到 ] 之间的部分为参数，按 , 分割后，每个部分第一个 = 前的内容为参数名，之后的部分为参数值。例如 [CQ:share,title=标题中有=等号,url=http://baidu.com] 中，功能名为 share，title 参数值为 标题中有=等号，url 参数值为 http://baidu.com。

另外`[CQ:json]`是value的空格无法解析？

**Comment by Pzzzzz5142** [comment]
是 因为直接str一个json对象，py会自动填充很多空格。（所以我直接复制粘贴json的字符串拼起来就vans了

**Comment by Pzzzzz5142** [comment]
（貌似本身也不是什么大问题，毕竟str(json)产生的也是单引号而不是qq要的双引号

**Comment by Shigma** [comment]
go-cqhttp 按照 onebot 标准进行实现，个人认为决不应该产生与 onebot 标准有异的行为。
