### ISSUE TITLE
无法撤回私聊消息（key not found in the bucket id）

### ISSUE THREAD

**Issue by v587ygq** [Mrs4s/go-cqhttp#274]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.24-fix2
运行环境: windows_amd64 和 windows_386
连接方式: 反向WS

**bug内容**

私聊消息发送成功，但无法撤回，debug 日志如下
```
[DEBUG]: WS接收到API调用: send_msg 参数: {"user_id":***,"message":"你好"} 
[DEBUG]: Protocol -> rev pkt: MessageSvc.PbSendMsg seq: 13889 
[DEBUG]: WS接收到API调用: delete_msg 参数: {"message_id":733404684} 
[WARNING]: 获取信息时出现错误: key not found in the bucket id: 733404684 
```
`QQ号已用***隐藏`

应该可以排除风控，**因为群消息可以撤回，但是私聊消息无法撤回**。

已尝试方案：

- 开启 enable_db
- `device.json` 添加 `"protocol": 1`
- 使用 windows_amd64 和 windows_386 版本

都无法解决，不知道是不是 bug ？

**复现方法**

调用api发送私聊消息再撤回

**Comment by wdvxdr1123** [comment]
386是数据库问题，我觉得 amd64应该和 #261 问题差不多吧
