### ISSUE TITLE
反向WebSocket上报断开时heartbeat积压问题

### ISSUE THREAD

**Issue by yanyongyu** [Mrs4s/go-cqhttp#275]
**环境信息**
go-cqhttp版本: v0.9.24
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
反向WebSocket断开后再连接，断开时的 **heartbeat** 会一瞬间全部上报，断开时的 heartbeat 不应该在再次连接后上报吧

**复现方法**
反向websocket连接，断开应用端，等待几秒(>heartbeat interval)，再次启动应用端，断开时的heartbeat会同时出现

**Comment by Mrs4s** [comment]
应该是底层库的问题，问题不大暂时推迟
