### ISSUE TITLE
CPU经常90%，一天挂掉2次左右

### ISSUE THREAD

**Issue by witpark** [Mrs4s/go-cqhttp#279]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.24-fix
运行环境: windows_amd64
连接方式: HTTP

**bug内容**
CPU经常90%，一天挂掉2次左右，群大于有几百个。是不是windos版本的性能有问题。需要切换到linux

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by witpark** [comment]
建议方向调整到性能和稳定性上来。功能就不要在加了：）

**Comment by Mrs4s** [comment]
请更新到最新版本并打开debug提供更多信息

**Comment by Mrs4s** [comment]
请提供cpu使用异常时的日志

**Comment by Mrs4s** [comment]
![Snipaste_2020-09-15_10-55-02](https://user-images.githubusercontent.com/12137562/93159995-001ca180-f742-11ea-9280-62c57a9a37ab.png)

**Comment by witpark** [comment]
![图片](https://user-images.githubusercontent.com/24600586/93181284-de83e000-f76a-11ea-9480-308f122af7f4.png)
![图片](https://user-images.githubusercontent.com/24600586/93181308-e479c100-f76a-11ea-9af6-90b5a12bb403.png)

**Comment by witpark** [comment]
今天开了debug模式。重现了

**Comment by witpark** [comment]
刚刚又挂了。错误信息还是上面截图的

**Comment by Mrs4s** [comment]
请问挂掉是指什么 Panic吗

**Comment by witpark** [comment]
就是命令行窗口关了

**Comment by Mrs4s** [comment]
请不要双击打开，用cmd或者powershell运行，这样就能捕捉到panic时的输出

**Comment by witpark** [comment]
好的明白了。

**Comment by witpark** [comment]
![图片](https://user-images.githubusercontent.com/24600586/93433661-abbc2200-f8f9-11ea-95dc-af60c0c940d7.png)

**Comment by witpark** [comment]
这次我没有双击有panic错误信息了。你看一下

**Comment by ZelKnow** [comment]
相同的问题，我使用的是v0.9.25版本
运行环境: windows_386
连接方式: 反向ws
报错类似，panic时cpu使用率，流入带宽和系统读IOPS突变

**Comment by Mrs4s** [comment]
请尝试最新版还有没有此问题

**Comment by witpark** [comment]
上午用了最新的版本。现在又出现了：（）

**Comment by witpark** [comment]
![图片](https://user-images.githubusercontent.com/24600586/93737280-5479c280-fc15-11ea-82dd-4dc2e138a724.png)

**Comment by Mrs4s** [comment]
> ![图片](https://user-images.githubusercontent.com/24600586/93737280-5479c280-fc15-11ea-82dd-4dc2e138a724.png)
> 
> 

打开debug看看有没有报错

**Comment by witpark** [comment]
![图片](https://user-images.githubusercontent.com/24600586/93836817-7aa36f00-fcb6-11ea-9680-51e88c9a4e5b.png)

**Comment by witpark** [comment]
[DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 10700 
[DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 10701 
 [DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 10702 
[DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 10705 
[DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 10703 
[DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 10704 
[DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 10708 
[DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 10706 
[DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 10707 
 [DEBUG]: Protocol -> rev pkt: OnlinePush.PbPushTransMsg seq: 10733

**Comment by witpark** [comment]
![图片](https://user-images.githubusercontent.com/24600586/93836966-04ebd300-fcb7-11ea-8808-7a9b7d82a8b7.png)

**Comment by witpark** [comment]
[2020-09-22 09:20:06] [DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 10705
[2020-09-22 09:20:06] [DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 10703
[2020-09-22 09:20:06] [DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 10704
[2020-09-22 09:20:06] [DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 10708
[2020-09-22 09:20:07] [DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 10706
[2020-09-22 09:20:07] [DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 10707
[2020-09-22 09:20:07] [DEBUG]: Protocol -> rev pkt: OnlinePush.PbPushTransMsg seq: 10733
panic: interface conversion: interface {} is nil, not client.groupMemberListResponse

goroutine 450453 [running]:
github.com/Mrs4s/MiraiGo/client.(*QQClient).GetGroupMembers(0xc0000b0000, 0xc018fbb6c0, 0x43f5cd, 0xd02dc0, 0x
b00c8, 0xc0000b0000)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200919153352-249af274638d/client/client.go:739 +0x2fc
github.com/Mrs4s/MiraiGo/client.(*QQClient).GetGroupList.func1(0xc0000b0000, 0xc018fbb6c0, 0xc02219a110)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200919153352-249af274638d/client/client.go:719 +0x68
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).GetGroupList
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200919153352-249af274638d/client/client.go:717 +0x139
