### ISSUE TITLE
多行消息变成了 \r 发送

### ISSUE THREAD

**Issue by Shigma** [Mrs4s/go-cqhttp#28]
![image](https://user-images.githubusercontent.com/33423008/89329248-2110c200-d6c1-11ea-9618-b12880c1437c.png)

硬要说的话 \r\n 和 \n 都在理，但是这……？

**Comment by Mrs4s** [comment]
草 还真的变成\r了

**Comment by masnn** [comment]
好 我知道为什么我会写出那个replace了
https://github.com/koishijs/koishi/issues/36

**Comment by Shigma** [comment]
……怪不得我看到那个 issue 的时候一脸懵逼。

**Comment by masnn** [comment]
transfer issue一键甩锅（不是

**Comment by Shigma** [comment]
咦这个是修复了吗？今天看 log 好像已经有 \n 了
