### ISSUE TITLE
当发送的消息字数过多时，发送消息会失败

### ISSUE THREAD

**Issue by ChugerXiao** [Mrs4s/go-cqhttp#282]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.10
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
当发送的消息字数过多时，发送消息会失败。

**复现方法**
让机器人发送大量消息（行数、字数）。发送会失败

**Comment by Mrs4s** [comment]
请更新到最新版本
