### ISSUE TITLE
撤回群组消息失败

### ISSUE THREAD

**Issue by yangchao1024** [Mrs4s/go-cqhttp#284]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.25
运行环境: windows_amd64
连接方式: HTTP

**bug内容**
撤回群组消息失败
[WARNING]: 获取信息时出现错误: key not found in the bucket id: 523990545

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by Mrs4s** [comment]
请确定开启了db并确实是使用的amd64架构

**Comment by yangchao1024** [comment]
我确定开启了db，并且使用的是amd64架构
linux ubuntu和window 我都试过了，都不行

**Comment by yangchao1024** [comment]
问题解决，感谢，我用错架构了
