### ISSUE TITLE
建议将 access_token 响应头部 Token 改为 Bearer

### ISSUE THREAD

**Issue by v587ygq** [Mrs4s/go-cqhttp#289]
在反向 WebSocket鉴权的时候收到的头部为
```
Authorization: Token abc
```

头部是 `Token` 而不是 `Bearer`，是否应该改为 `Bearer` ? （仅建议）

**Comment by Mrs4s** [comment]
目前主要是为了兼容性... 老cqhttp曾经把这里打错了 为了兼容性就一直保留到现在

**Comment by v587ygq** [comment]
> 目前主要是为了兼容性... 老cqhttp曾经把这里打错了 为了兼容性就一直保留到现在

原来是这样
