### ISSUE TITLE
机器人全员禁言失效（群主）

### ISSUE THREAD

**Issue by My-Jie** [Mrs4s/go-cqhttp#291]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.25
运行环境: 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
连接方式: http

**bug内容**
机器人设置为群主，无法操作全员禁言

**复现方法**
1、直接调用接口访问
data = {
        'group_id': group_id,
        'enable': enable,
}
requests.post(url=host + '/set_group_whole_ban', data=data)

2、接口返回结果
{'data': None, 'retcode': 0, 'status': 'ok'}

3、实际没有全员禁言成功

**Comment by My-Jie** [comment]
附带一个问题
入群审批接口
set_group_add_request
flag, sub_type, approve  3个参数
approve = True  本来应该是同意入群，执行后，却是拒绝了

**Comment by Mrs4s** [comment]
请再次测试新版本

**Comment by Mrs4s** [comment]
理论已修复
