### ISSUE TITLE
运行几个小时后，就会提示账号被风控，重启就恢复了

### ISSUE THREAD

**Issue by yangchao1024** [Mrs4s/go-cqhttp#293]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.25
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
运行几个小时后，就会提示账号被风控，重启就恢复了
账号是2005年的真实老号，不是小号，用其他版本cqhttp就没有问题。只有go-cqhttp会出现这个问题

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by Mrs4s** [comment]
是真的风控了，请多挂一段时间就会好。
