### ISSUE TITLE
机器人转发表情包网络超时错误导致转发失败

### ISSUE THREAD

**Issue by ly1102** [Mrs4s/go-cqhttp#296]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.25
运行环境: ubuntu_amd64
连接方式: 反向WS

**bug内容**
访问QQ图片/表情包的请求希望可以优化，手机QQ/Chrome浏览器访问图片都 没问题，但是机器人访问很久都访问不了，然后发送失败，直接发送了原CQ码

**复现方法**
我是从cqhttp-mirai迁移过来的，在之前由于表情包已经缓存过了，所以发送没问题。
但是迁移后两边的缓存文件不兼容，导致需要重新发送表情包时，需要重新去请求。

而机器人如果在短时间内没有及时转发好友或者群友的表情包生成缓存，
并且这个表情包较长时间没有再次被发送过，那么机器人会一直发送失败。

但是我使用手机QQ去访问这个表情包的url是可以看到图片的，怀疑是请求图片的UA等造成的访问被拒绝。希望可以优化。

如果再对机器人发送一次这个表情包，再次发送之前的表情包就可以秒发送。

**Comment by Mrs4s** [comment]
能否贴一下获取图片失败的报错截图

**Comment by ly1102** [comment]
> 能否贴一下获取图片失败的报错截图
![image](https://user-images.githubusercontent.com/15363304/93559046-58a5a600-f9b1-11ea-8a33-3737adc555b6.png)
我调到debug模式，重启go-cq，然后这个消息又很快发出来了。。。

**Comment by Mrs4s** [comment]
最新版已优化
