### ISSUE TITLE
使用外部IP作为HTTP API host会导致闪退

### ISSUE THREAD

**Issue by chelomei** [Mrs4s/go-cqhttp#297]
**环境信息**
go-cqhttp版本: v0.9.25
运行环境: windows_amd64
连接方式: HTTP API

**bug内容**
使用外部IP作为HTTP API host会导致闪退,debug记录提示"[ERROR]: listen tcp x.x.x.x:x: bind:The requested address is not valid in its context. ";" [INFO]: 请检查端口是否被占用."

**复现方法**
使用外部IP作为HTTP API host

**Comment by Mrs4s** [comment]
此报错为ip无效错误，我无法控制

**Comment by Ink-33** [comment]
外部ip都没分配给你网络接口你监听个啥

```
You are trying to bind to an IP address that is not actually assigned to your network interface.
```
[see this](https://stackoverflow.com/questions/38958233/the-requested-address-is-not-valid-in-its-context-error)
