### ISSUE TITLE
v0.9.25-fix2出现panic错误

### ISSUE THREAD

**Issue by zangxx66** [Mrs4s/go-cqhttp#298]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: go-cqhttp-v0.9.25-fix2-linux-amd64.tar.gz
运行环境: linux-amd64
连接方式: 反向WS

**bug内容**
请在这里详细描述bug的内容  
root@VM-0-7-ubuntu:~/go# ./go-cqhttp
[2020-09-20 00:21:14] [INFO]: 当前版本:v0.9.25-fix2 
[2020-09-20 00:21:14] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2020-09-20 00:21:14] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2020-09-20 00:21:19] [INFO]: 开始尝试登录并同步消息... 
[2020-09-20 00:21:19] [INFO]: 使用协议: Android Phone 
panic: EOF

goroutine 1 [running]:
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadBytes(...)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200919153352-249af274638d/binary/reader.go:40
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadInt32(0xc00039fbf0, 0x3)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200919153352-249af274638d/binary/reader.go:60 +0x13b
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadString(0xc00039fbf0, 0xc0003c9c20, 0xc0003e7400)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200919153352-249af274638d/binary/reader.go:65 +0x2f
main.main()
        /github/workspace/main.go:258 +0x1a98

**复现方法**
请在这里分步骤的描述如何复现这个bug  
执行v0.9.25-fix2后报错，并退出程序了

**Comment by Mrs4s** [comment]
请删除 `servers.bin` 并重试
