### ISSUE TITLE
群聊数较多时，无法接收到加群邀请事件

### ISSUE THREAD

**Issue by ZelKnow** [Mrs4s/go-cqhttp#299]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.25-fix3
运行环境: windows_386
连接方式: 反向WS

**bug内容**
机器人加群数量超过1000，邀请机器人进入新群时无法接收到邀请事件。使用加群数量少的小号测试，可以正常接收到邀请事件。

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by takayama-lily** [comment]
有可能是被风控了。你可以用官方客户端登陆，看看是否能正常收到。

**Comment by ZelKnow** [comment]
> 有可能是被风控了。你可以用官方客户端登陆，看看是否能正常收到。

试了一下确实用官方客户端也收不到，应该是被风控了。
