### ISSUE TITLE
现在能否发送其他类型消息?

### ISSUE THREAD

**Issue by daofeng2015** [Mrs4s/go-cqhttp#3]
类似于xml,json,app这种类型的,我看cqhttp好像没有支持,还有什么闪照什么的,还有一点你readme中的api的链接最好换成国内的那个地址.

**Comment by Mrs4s** [comment]
支持的消息类型请参考 [MiraiGo](https://github.com/Mrs4s/MiraiGo#%E6%B6%88%E6%81%AF%E7%B1%BB%E5%9E%8B) 更多的还在开发中.

**Comment by Mrs4s** [comment]
目前已支持
- [CQ:image]
- [CQ:face]
- [CQ:at]
- [CQ:share]
- [CQ:reply]
- [CQ:node]

暂无计划兼容其他CQ码.
