### ISSUE TITLE
[BUG] 过大的图片无法上传？

### ISSUE THREAD

**Issue by TurboHsu** [Mrs4s/go-cqhttp#302]
**环境信息**
go-cqhttp版本: v0.9.25-fix3
运行环境: linux_amd64
连接方式: 反向WS
（127.0.0.1:60089 上运行的是Nginx）
**bug内容**
在此版本中，疑似过大的图片无法发送？
![屏幕截图 2020-09-20 140123](https://user-images.githubusercontent.com/47477044/93702556-d13f6a80-fb49-11ea-8e4f-5fdd807b72d8.png)

这是我在反向WS发送图片的时候发现的问题，同样的图片在v0.9.18上不会出现发送报错
在0.9.25下，发送100k左右的图片可以成功发送。

（先切老版本用着吧
**复现方法**
使用nonebot  await session.send(MessageSegment.image('http://127.0.0.1:60089/animage.jpg'))，图片大小差不多3M

**Comment by Mrs4s** [comment]
换其他图片试试？ 都无法发送吗

**Comment by TurboHsu** [comment]
测试20kb的图片可发送 1.5M的图片无法发送。
服务器香港Azure，（地域或者号的问题未排除，但是奇怪的是老版本却没有问题）

**Comment by Mrs4s** [comment]
私聊上传图片失败的问题已修复.
