### ISSUE TITLE
嘗試連接到不可用 IP 報錯

### ISSUE THREAD

**Issue by AkazaRenn** [Mrs4s/go-cqhttp#307]
**环境信息**
go-cqhttp版本: v0.9.25-fix3
运行环境: ubuntu_amd64
连接方式: 正向WS

**bug内容**
啓動時會卡在 `[INFO]: Protocol -> connect to server: 169.50.133.213:10001`，一段時間后（2 分鐘左右）出現
```
[ERROR]: Protocol -> connect server error: dial tcp 169.50.133.213:10001: connect: connection timed out
[INFO]: Protocol -> connect to server: 158.175.76.52:10001
panic: runtime error: invalid memory address or nil pointer dereference
```

**复现方法**
正常啓動 go-cqhttp，正常使用一段時間后收到
```
[ERROR]: Protocol -> connection dropped by server: EOF
[INFO]: Protocol -> connect to server: 169.50.133.212:10001
[INFO]: 收到服务器地址更新通知, 将在下一次重连时应用. 地址信息已储存到 servers.bin 文件
```
下一次重啓時會嘗試鏈接到 169.50.133.212:10001 並卡住，因爲這個地址不可用導致崩潰，只能手動刪除 servers.bin 重新獲取地址

**Comment by Mrs4s** [comment]
关于崩溃已找到问题，将会在下个版本修复.
由于我无法判断TX下发的地址是否有效，所以目前只能修复因为连接问题导致的panic.

**Comment by AkazaRenn** [comment]
> 关于崩溃已找到问题，将会在下个版本修复.
> 由于我无法判断 TX 下发的地址是否有效，所以目前只能修复因为连接问题导致的 panic.

原來這個地址不影響使用嗎？要是影響的話我覺得可以在重連 n 次失敗后重新獲取地址。

**Comment by Mrs4s** [comment]
服务器地址是TX觉得你连的服务器不对时才会主动推送，我无法主动获取..

**Comment by AkazaRenn** [comment]
> 服务器地址是 TX 觉得你连的服务器不对时才会主动推送，我无法主动获取..

明白了，感謝

**Comment by Mrs4s** [comment]
#309
