### ISSUE TITLE
全员禁言接口/入群审批接口 失效，角色：群主

### ISSUE THREAD

**Issue by My-Jie** [Mrs4s/go-cqhttp#312]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.25-fix3
运行环境: Linux 7
连接方式: http

**bug内容**
1、机器人角色为群主，全员禁言无效（管理员角色暂未测试）
2、机器人角色为群主，入群审批全为拒绝

**复现方法**
1、set_group_whole_ban_async  全员禁言接口
data = {
        'group_id': group_id,
        'enable': enable,
    }
enable 不论是True 还是False 都无效
返回结果：{'data': None, 'retcode': 0, 'status': 'ok'}
2、set_group_add_request_async  入群审批接口
data = {
        'flag': flag,
        'sub_type': sub_type,
        'approve': approve,
        'reason': reason
    }
sub_type = 'add'
approve 不论 True 还是False 都是拒绝加入

**Comment by My-Jie** [comment]
更正下：
入群审批接口，机器人为管理员角色时，approve 不论 True 还是False 也是拒绝加入

**Comment by Mrs4s** [comment]
![image](https://user-images.githubusercontent.com/12137562/94338400-6cda4a80-0024-11eb-966a-d04d1cee7d5e.png)
我这边复现失败了，能否给一下更详细的信息？

**Comment by My-Jie** [comment]
使用的python语言
import requests
host = 'http://127.0.0.1:5700'

1、全体禁言
data = {
        'group_id': 群号number,
        'enable': True,
    }
r = requests.post(url=host + '/set_group_whole_ban', data=data)
print(r.json())
 {'data': None, 'retcode': 0, 'status': 'ok'}

2、入群审批
data = {
        'flag': '1600653565346174',  #  上报数据中获取
        'sub_type': 'add',
        'approve': True,
        'reason': ''
    }
requests.post(url=host + '/set_group_add_request', data=data)


发起请求后，go-cqhttp日志中并没有报错日志输出，暂无其他信息了

**Comment by My-Jie** [comment]
全体禁言功能 ，无意尝试了下 字符串“true”  “false”成功了。。。审批那个还没有机会测试，可能也是这样吧

**Comment by My-Jie** [comment]
审批功能同样如此，需要字符串的 true 和false 不是bool
