### ISSUE TITLE
分片消息组合异常

### ISSUE THREAD

**Issue by danyang685** [Mrs4s/go-cqhttp#315]
**环境信息**
go-cqhttp版本: v0.9.25-fix3（一段时间以内的其他版本也有此问题）
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
array模式下，接收到的群长文本消息被分成数个text，未按正确的顺序排列
然而，使用QQ Windows版发送相同的消息，并未被分成多个text，array内仅包含一个text元素，内容正常

**复现方法**
1. 使用nonebot(go-cqhttp)的await session.send(msg)发送文本消息，消息约350个字（特征：若干的由顿号 `、` 分割的词语）
2. 使用aiocqhttp(go-cqhttp)的on_message('group')事件接收文本消息
3. 得到的event中，message列表内text排列不正确
4. raw_message完全按message列表内的顺序排列，也不正确
5. QQ客户端上接收的消息符合预期
6. 使用QQ客户端发送相同消息，接收正常

**Comment by danyang685** [comment]
经过测试，将array模式切换为string模式，收到的event中，message和raw_message仍存在同样的问题。

**Comment by wdvxdr1123** [comment]
请关闭强制分片发送

**Comment by danyang685** [comment]
> 请关闭强制分片发送

感谢回复！

在消息接收方的机器人上进行此配置后，问题依然存在。
消息发送方的机器人不受我的控制。

消息接收方的go-cqhttp能否设法正确接收已经被分片发送的消息？
