### ISSUE TITLE
群聊 get_group_msg 出错

### ISSUE THREAD

**Issue by U2FsdGVkX1** [Mrs4s/go-cqhttp#319]
**环境信息**
go-cqhttp版本: v0.9.25-fix3
运行环境: linux_amd64
连接方式: 正向WS

**bug内容**
使用 get_group_msg 函数无法获取到被回复的消息，并且当前使用的是AMD64架构版本
![image](https://user-images.githubusercontent.com/11484206/94323385-2a832000-ffc8-11ea-9fb9-ff6456a98a67.png)
另附上数据库文件：https://1drv.ms/u/s!An0DK5Y-VeCrwCi-VsW5xhXnmPqq?e=PooceC

**复现方法**
收到回复消息的cq码之后，原样传递给 get_group_msg 函数，然后提示 key not found in the bucket id

**Comment by Mrs4s** [comment]
暂且计划于1.0更换内置数据库，目前这个数据库问题还挺多的

**Comment by ly1102** [comment]
> 暂且计划于1.0更换内置数据库，目前这个数据库问题还挺多的
现在好像也不能获取了，0.9.29 。是直接改了接口成get_msg吗？
