### ISSUE TITLE
Linux x64 0.9.12似乎依然存在好友消息多次上报的问题

### ISSUE THREAD

**Issue by Mother-Ship** [Mrs4s/go-cqhttp#32]
日志中伴随报错：
[WARNING]: 上报Event数据到 【脱敏】 失败: Post "【脱敏】": context deadline exceeded 

群聊消息正常。。

**Comment by Mrs4s** [comment]
可以使用ws试试 这个是http上报服务器超时了.

**Comment by liggest** [comment]
> 可以使用ws试试 这个是http上报服务器超时了.

您好，我也遇到了这个警告。
似乎这个警告出现后gocq就不再向我的后台上报了
请问有什么除了重启程序以外的办法解决这个问题吗？

**Comment by Mrs4s** [comment]
> > 可以使用ws试试 这个是http上报服务器超时了.
> 
> 您好，我也遇到了这个警告。
> 似乎这个警告出现后gocq就不再向我的后台上报了
> 请问有什么除了重启程序以外的办法解决这个问题吗？

出现这个警告并不会导致无法上报: 
https://github.com/Mrs4s/go-cqhttp/blob/8094553bdb053dad55a7939000a1423e53313475/server/http.go#L173-L194
请检查目标server是否阻塞，建议使用ws上报数据

**Comment by liggest** [comment]
> BindBody

我的后台是基于python的flask，比较简单的那种
每次出现这个问题之后只要重启一下gocq程序就可以解决
似乎和flask服务端那边没有什么关系
从我部署gocq程序的昨晚到现在一共出现了两次这样的问题
我在观察一下吧，谢谢您

一个题外话，您给出的代码里面似乎包含了和cqhttp一样的secret加密，请问这个要怎么在配置中体现呢？
我在切换到gocq之后没找到能在哪里设置secret，只能先把服务端那边的加密验证注释掉了

**Comment by Mrs4s** [comment]
> > BindBody
> 
> 我的后台是基于python的flask，比较简单的那种
> 每次出现这个问题之后只要重启一下gocq程序就可以解决
> 似乎和flask服务端那边没有什么关系
> 从我部署gocq程序的昨晚到现在一共出现了两次这样的问题
> 我在观察一下吧，谢谢您
> 
> 一个题外话，您给出的代码里面似乎包含了和cqhttp一样的secret加密，请问这个要怎么在配置中体现呢？
> 我在切换到gocq之后没找到能在哪里设置secret，只能先把服务端那边的加密验证注释掉了


post_urls是个map
结构: 
````
{
    "url": "secret"
}
````

**Comment by liggest** [comment]
> > > BindBody
> > 
> > 
> > 我的后台是基于python的flask，比较简单的那种
> > 每次出现这个问题之后只要重启一下gocq程序就可以解决
> > 似乎和flask服务端那边没有什么关系
> > 从我部署gocq程序的昨晚到现在一共出现了两次这样的问题
> > 我在观察一下吧，谢谢您
> > 一个题外话，您给出的代码里面似乎包含了和cqhttp一样的secret加密，请问这个要怎么在配置中体现呢？
> > 我在切换到gocq之后没找到能在哪里设置secret，只能先把服务端那边的加密验证注释掉了
> 
> post_urls是个map
> 结构:
> 
> ```
> {
>     "url": "secret"
> }
> ```

了解了，谢谢您
如果这边再出现上面的警告，我会再来报告情况

**Comment by liggest** [comment]
您好，我这边再次出现了上面的警告
这次我试了试好友消息，发现确实偶尔有好友消息被多次上报的问题
（我测试用的"-hello"输入有时候会收到多次反馈）
上述是小问题，我这边比较严重的是报了警告之后，从服务端调用http API（send_group_msg）没法让消息发出去
似乎是发出去的post报文没有被正确响应
尝试输出响应报文的json，无论post几次，都得到下面的结果，message_id也没有变化
`{"data":{"message_id":-1993251931},"retcode":0,"status":"ok"}`

私聊（send_private_msg）就不存在这个问题

**Comment by Mother-Ship** [comment]
> 可以使用ws试试 这个是http上报服务器超时了.

可否麻烦您提供配置项来修改超时时间和重试次数呢？（我这边懒得对上报服务端做优化了……）

**Comment by liggest** [comment]
#38 
又看了一下，似乎我遇到的问题和这边比较相似

**Comment by Shigma** [comment]
![image](https://user-images.githubusercontent.com/33423008/89779995-2186de00-db43-11ea-8463-f526fed6ad17.png)

似乎重启以后也会有这种情况，我裂开了.jpg

**Comment by Mrs4s** [comment]
fixed.
