### ISSUE TITLE
登录失败: 当前版本过低，请先升级到手机QQ最新版本

### ISSUE THREAD

**Issue by monokuma233** [Mrs4s/go-cqhttp#322]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.26
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
启动提示“登录失败: 当前版本过低，请先升级到手机QQ最新版本”

**复现方法**
启动提示“登录失败: 当前版本过低，请先升级到手机QQ最新版本”

**Comment by Mrs4s** [comment]
#308
