### ISSUE TITLE
新群成员入群问题

### ISSUE THREAD

**Issue by qinpersevere** [Mrs4s/go-cqhttp#326]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.26
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
新成员入群信息存在遗漏，因为群内有Q群管家，观察到Q群管家已经发送了入群欢迎，但没有收到新成员入群事件；有时在之后会收到该成员的群内发言，同时收到入群事件推送:
![image](https://user-images.githubusercontent.com/22725102/94399432-e6477980-0199-11eb-8fb5-eafbb37608c4.png)
![image](https://user-images.githubusercontent.com/22725102/94399445-ed6e8780-0199-11eb-9a29-940863e219b7.png)
同时新成员入群经常会报错：
![image](https://user-images.githubusercontent.com/22725102/94399551-29095180-019a-11eb-93bb-78d50c7aeed1.png)

ps.  使用v0.9.24-fix2不会报错，但也存在新成员入群信息和发言遗漏问题，类似 #288 

**复现方法**
暂无明确复现方法，但怀疑新成员入群会有一定概率触发

**Comment by Mrs4s** [comment]
#320
