### ISSUE TITLE
使用v0.9.26正向WS时的两个bug

### ISSUE THREAD

**Issue by SakamotoSukoshi** [Mrs4s/go-cqhttp#331]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.26
运行环境: windows_amd64
连接方式: 正向WS

### 1
**bug内容**
我的机器人加入了1049个群，但是只能显示加载1000或999个群，通过get_group_list返回的JSON也只有1000或999个对象

**复现方法**
加入的群超过1000，并`ws.send('{"action":"get_group_list"}')`

### 2
**bug内容**
如果开启enable_db，我的机器人就无法接收message信息，只能收到撤回、禁言等notice信息

**复现方法**
在config.json中设置`"enable_db": true,`

**Comment by Mrs4s** [comment]
1.由于TX限制，开启时的群列表加载只能获取到前1000个群，目前我对这方面做了一些优化，未获取到的群在启动后第一次收到消息时会手动刷新这个群的信息。
2.请等待1.0的更换数据库计划

**Comment by SakamotoSukoshi** [comment]
感谢回复
