### ISSUE TITLE
[CQ:tts] 在PC端QQ无法正常显示

### ISSUE THREAD

**Issue by Exsper** [Mrs4s/go-cqhttp#346]
**环境信息**
go-cqhttp版本: v0.9.27
运行环境: windows_amd64
连接方式: 正向WS

**bug内容**
发送[CQ:tts] 在PC端QQ显示裂图，但是在手机QQ上显示正常并且可以正常播放

**复现方法**
发送 [CQ:tts,text=文字内容] 时出现
bot未设置性别

**Comment by wdvxdr1123** [comment]
可能是PC端版本过老
