### ISSUE TITLE
Protocol -> parse incoming packer error: return code unsuccessful: -10001

### ISSUE THREAD

**Issue by arily** [Mrs4s/go-cqhttp#347]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.24
运行环境: linux_amd64
连接方式: WS

**bug内容**
自动重连可能失败了？
5|go-cqhtt | [2020-10-07 23:32:20] [INFO]: 收到群 **** 的消息: （这是消息）(-2127716222) 
5|go-cqhtt | [2020-10-07 23:32:27] [INFO]: Protocol -> connect to server: 203.205.255.221:8080 
5|go-cqhtt | [2020-10-07 23:32:30] [ERROR]: Protocol -> parse incoming packer error: return code unsuccessful: -10001 

**复现方法**
可能只能等。

**Comment by Mrs4s** [comment]
这个似乎是BOT被其他客户的挤掉了或者会话过期了，比较麻烦

**Comment by arily** [comment]
大概我连续开了一个月有这么一次 多半是过期了.
暂时没有对策吗

**Comment by swsun111** [comment]
您好，你这个问题解决了吗，我也遇到了这个问题，不知如何解决
