### ISSUE TITLE
私聊音乐分享收不到

### ISSUE THREAD

**Issue by xxyy3130** [Mrs4s/go-cqhttp#348]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.28
运行环境: windows_amd64
连接方式: WS

**bug内容**
好友私聊发送音乐分享收不到

**复现方法**
分别尝试发送了[CQ:music,type=163,id=1303289043]和[CQ:music,type=qq,id=275416867]
日志无报错，但是私聊收不到，群聊可以收到

**Comment by Mrs4s** [comment]
忘记更新私聊了(
