### ISSUE TITLE
图片保存在./data/images/路径下的时候发送失败

### ISSUE THREAD

**Issue by remiliacn** [Mrs4s/go-cqhttp#35]
会报错 `image not exists` 或者 `invalid local file`

**Comment by Mrs4s** [comment]
`/data/images` 下是特殊的文件格式, 需要发送普通文件的话请使用 `[CQ:image,file=file:///]` 格式的CQ码
.image文件结构参考: https://github.com/Mrs4s/go-cqhttp/blob/master/docs/file.md#%E5%9B%BE%E7%89%87%E7%BC%93%E5%AD%98%E6%96%87%E4%BB%B6

**Comment by remiliacn** [comment]
好像这样就行了哎 #36
