### ISSUE TITLE
发送群聊失败,帐号有风险,重新运行却能发送

### ISSUE THREAD

**Issue by 572705296** [Mrs4s/go-cqhttp#350]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.27
运行环境: windows_amd64/32
连接方式: WS

**bug内容**
请在这里详细描述bug的内容
测试群机器人,第一天没什么问题,第二天机器人无法发送短的群消息,log提示有风险,但长群消息和私聊消息能发送,重新运行go-cqhttp.exe后就能发送,过一段时间后又这样子了。
**复现方法**
![78CK U0OGDHL)2Q~A1_E6LM](https://user-images.githubusercontent.com/37203843/95535941-55d02b00-0a1c-11eb-8d2e-118e0f4ab6d0.png)
![C8OH~HP{E @ CIQNSM@H1JO](https://user-images.githubusercontent.com/37203843/95535946-5963b200-0a1c-11eb-8b5b-c54034c56daf.png)

**Comment by Mrs4s** [comment]
#38
