### ISSUE TITLE
9.28 arm版本启动出错

### ISSUE THREAD

**Issue by samondlee** [Mrs4s/go-cqhttp#356]
V0.928
arm debian，armbian 5.77  S905X 斐讯N1

之前的版本都正常包括0927 现在无法启动

Oct 12 17:54:19 aml main[6487]: github.com/Mrs4s/MiraiGo/client.(*QQClient).Login(0x17c4c40, 0x1000, 0x1000, 0x17db000)
Oct 12 17:54:19 aml main[6487]:         /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201008134448-b53aaceaa1b4/client/client.go:209
Oct 12 17:54:19 aml main[6487]: github.com/Mrs4s/go-cqhttp/server.(*webServer).Dologin(0xda2d88)
Oct 12 17:54:19 aml main[6487]:         /github/workspace/server/apiAdmin.go:102 +0xf8
Oct 12 17:54:19 aml main[6487]: github.com/Mrs4s/go-cqhttp/server.(*webServer).Run(0xda2d88, 0x1789800, 0xc, 0x17c4c40, 0x2)
Oct 12 17:54:19 aml main[6487]:         /github/workspace/server/apiAdmin.go:91 +0x1d8
Oct 12 17:54:19 aml main[6487]: main.main()
Oct 12 17:54:19 aml main[6487]:         /github/workspace/main.go:254 +0x6d0
Oct 12 17:54:19 aml systemd[1]: mirai.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 12 17:54:19 aml systemd[1]: mirai.service: Failed with result 'exit-code'.

**Comment by samondlee** [comment]
已经尝试包括 重置device.json config.json全部删除后 重新配置仍然无法启动

**Comment by Mrs4s** [comment]
能否附上日志上下文 具体的错误信息被截去了

**Comment by wdvxdr1123** [comment]
我觉得和 #349 是一个问题
