### ISSUE TITLE
请求：要发送语音，ffmpeg需要如何设置呢

### ISSUE THREAD

**Issue by My-Jie** [Mrs4s/go-cqhttp#357]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.98
运行环境: linux
连接方式: post

请教内容：
ffmpeg 需要如何进行配置才能使用
到MiraiGo Element时出现错误: exec: "ffmpeg": executable file not found in $PATH

**Comment by My-Jie** [comment]
目前已使用腾讯tts合成mps格式的语音，使用CQ码就报上面的错误

**Comment by Mrs4s** [comment]
将编译好的可执行文件, 如 `ffmpeg.exe / ffmpeg` 放入工作目录即可, 或添加到 `PATH` 环境变量.

**Comment by My-Jie** [comment]
感谢，成功了

**Comment by undefined-moe** [comment]
ffmpeg解编码器有相应要求吗

**Comment by Mrs4s** [comment]
> ffmpeg解编码器有相应要求吗

根据你需要发送的格式配置就行

**Comment by undefined-moe** [comment]
不需要amr编码器是吧（之前我为了转amr还得手动编辑ffmpeg

**Comment by Mrs4s** [comment]
> 不需要amr编码器是吧（之前我为了转amr还得手动编译ffmpeg

需要...

**Comment by My-Jie** [comment]
> 草草草那我要这功能有何用（摔
我用的Linux系统，在ffmpeg.org[官网地址](https://ffmpeg.org/download.html#build-linux)下载的 Linux Static Builds 版本。
解压后，将里面的 ffmpeg 添加的环境变量中。
我语音是用的腾讯tts合成，MP3格式。
就没有其他配置了。
昨天尝试了tta，老是系统繁忙，暂时放弃
目前一切正常

**Comment by 15015070064** [comment]
> 将编译好的可执行文件, 如 `ffmpeg.exe / ffmpeg` 放入工作目录即可, 或添加到 `PATH` 环境变量.

你好，我是ubuntu环境，已经配置好path，但是仍然是一样的错误，请问你有什么建议吗
