### ISSUE TITLE
普通群员邀请他人入群、管理员审批入群，没有上报数据

### ISSUE THREAD

**Issue by My-Jie** [Mrs4s/go-cqhttp#359]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.8
运行环境: linux
连接方式: post

**bug内容**
1、当群员邀请他人时，收不到上报数据。
2、管理员审批后，收不到上报数据

**复现方法**
1、群里普通群员，邀请他人入群动作
2、两种情况：他人申请入群的审批，群员邀请入群的审批

**Comment by sam01101** [comment]
+1 mirai里也出现同样的bug, 估计是协议问题

**Comment by My-Jie** [comment]
看来只有等mirai修复了呢

**Comment by Mrs4s** [comment]
加群事件理论上会同步的来着，是需要增加邀请事件吗

**Comment by My-Jie** [comment]
群员邀请数据上报，应该属于request消息类吗？管理审批后的上报属于notice类吗？

**Comment by sam01101** [comment]
如果机器人为群主此bug并不会出现，真奇怪

**Comment by sam01101** [comment]
但如果机器人是管理员这个bug却会出现

**Comment by My-Jie** [comment]
> 但如果机器人是管理员这个bug却会出现

好像是的，我正式用的群里机器人是管理员，调试用的群里机器人是群主

**Comment by wfjsw** [comment]
检查群主是不是把机器人的审批权限下了？

**Comment by sam01101** [comment]
> 检查群主是不是把机器人的审批权限下了？

这是其一，但我没下也会发生这个问题

**Comment by My-Jie** [comment]
> 检查群主是不是把机器人的审批权限下了？

没有下的，因为像那些自己申请入群的通知，是能够收到的。

**Comment by Mrs4s** [comment]
目前正在重构这部分的逻辑，下个版本应该会改善

**Comment by My-Jie** [comment]
> 目前正在重构这部分的逻辑，下个版本应该会改善

幸苦你啦！Mrs4s~

**Comment by My-Jie** [comment]
这个问题似乎还是没有解决呢，没有数据上报

**Comment by sam01101** [comment]
剛Release我就測試過了，確實是未解決，建議重新開啟issue

**Comment by Mrs4s** [comment]
最好能打开debug模式并附上操作前后相关日志以方便排查

**Comment by My-Jie** [comment]
开启dubug模式，从日志上查看并未发现可用消息，也无报错等提示。
我就说一下我的处理过程吧，以“申请入群”为例：
1、bot的角色是管理员
2、有人申请入群，会收到上报数据：
{'comment': '问题：********\n答案：*****', 'flag': '1603877797655602', 'group_id': 12345678, 'post_type': 'request', 'request_type': 'group', 'self_id': 5555555, 'sub_type': 'add', 'time': 1603877797, 'user_id': 777777}
3、我会去匹配comment字段里面答案后面的字符串，自己设定了一个答案的list
4、当匹配上入群的答案时，调用/set_group_add_request接口批准入群，然后加一些自己的后续逻辑。
5、当不满足匹配时，就放过，不处理该条上报数据。
6、同时，其他管理员会收到需要人工审核同意、拒绝的通知（bot自动审批后就是结果通知了）。
7、此时，点击同意入群的按钮，查看上报数据，并没有有关“同意”的上报数据
8、如果没有这个操作的上报数据，也就无法做人工审核后的操作逻辑了
![image](https://user-images.githubusercontent.com/39127734/97532746-f4cfbd80-19f1-11eb-9a81-3cdc8e316778.png)

**Comment by sam01101** [comment]
刚刚截到, 附送其他管理员同意加群并群员进群的图, 不确定是否有用
![image](https://user-images.githubusercontent.com/25792361/98000306-53989b00-1e27-11eb-85c4-007718773beb.png)

流程: 

1. 群员申请进群 (未知时间)
2. 其他管理员同意进群 (刚才)

**Comment by wfjsw** [comment]
看起来没有包含什么有用数据，大概需要截长一点

**Comment by sam01101** [comment]
> 看起来没有包含什么有用数据，大概需要截长一点

对不起，它真的就这么长

**Comment by Mrs4s** [comment]
有点没有理解这个issue的问题.
以下是正常的逻辑，希望能指出哪一步出现了问题
1. 群员申请入群，如果有request上报就属于正常情况.
2. 忽略request，如果其他管理员处理了这个请求，将不会有单独的事件上报.
3. 当新群员进入群时，会有一个入群的Event.
4. 此时通过 `/get_group_system_msg` 获取群系统消息的话会发现该请求已经 `checked`.

**Comment by sam01101** [comment]
dump, 详细记录已经在QQ和群主进行了, 因此没能贴上
