### ISSUE TITLE
.ocr_image接口错误 (error: read data/images: The handle is invalid.)

### ISSUE THREAD

**Issue by BlackcatWatcher** [Mrs4s/go-cqhttp#369]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.29
运行环境: windows_386   linux_386
连接方式: 正向WS

**bug内容**
使用ws向win客户端和linux客户端发送数据均会出现：error: read data/images: The handle is invalid.
发送内容：{ "action": ".ocr_image", "params": {"file":"地址"}, "echo": "1" }
地址尝试过：
1、462375dc12f3e4544641bf53645f4266.image
2、{462375DC-12F3-E454-4641-BF53645F4266}.jpg
(以及去掉后缀)
看源文件后发现用了bot.makeImageElem，又试了file URI、url和base64编码填到地址里发送都是上面这个错误。

有用法的话希望更新一下文档

**Comment by Mrs4s** [comment]
目前仅支持ocr收到的图片，相关文档正在添加

**Comment by Mrs4s** [comment]
https://github.com/Mrs4s/go-cqhttp/blob/master/docs/cqhttp.md#%E5%9B%BE%E7%89%87ocr 文档已更新

**Comment by Pzzzzz5142** [comment]
图片id是指什么呢？是用户发送的图片的消息id还是什么别的东西？
```
[2020-12-07 11:45:31] [INFO]: 收到好友  的消息: [CQ:image,file=e66ac24d832e7535f238f3d71dd48ab8.image] (850847330) 
[2020-12-07 11:45:35] [WARNING]: load image error: invalid image 
```
image中填`850847330`看起来是不对的。

**Comment by zonglang** [comment]
> > 图片id是指什么呢？是用户发送的图片的消息id还是什么别的东西？
> > ```
> > [2020-12-07 11:45:31] [INFO]: 收到好友  的消息: [CQ:image,file=e66ac24d832e7535f238f3d71dd48ab8.image] (850847330) 
> > [2020-12-07 11:45:35] [WARNING]: load image error: invalid image 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > image中填`850847330`看起来是不对的。
> 
> 实测图片id是 e66ac24d832e7535f238f3d71dd48ab8.image

尝试用「 e66ac24d832e7535f238f3d71dd48ab8.image」但是还是会报「ocr image error: image error」的错误

**Comment by Gingmzmzx** [comment]
> e66ac24d832e7535f238f3d71dd48ab8.image

感谢感谢！！是真的
