### ISSUE TITLE
Bot登录出错,interface {} is nil, not *client.GroupSystemMessages

### ISSUE THREAD

**Issue by xxyy3130** [Mrs4s/go-cqhttp#375]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.29-fix1
运行环境: windows_amd64
连接方式: WS

**bug内容**
panic: interface conversion: interface {} is nil, not *client.GroupSystemMessages

**复现方法**
Bot登录时出错，测试了一些QQ有的一直出错，有的正常

![image](https://user-images.githubusercontent.com/61443746/97112999-6e318c80-1722-11eb-8396-bc650f4b24b1.png)

**Comment by Mrs4s** [comment]
已修复 等待Release
