### ISSUE TITLE
私聊持续上传图片失败

### ISSUE THREAD

**Issue by LR1093141031** [Mrs4s/go-cqhttp#378]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.29fix2
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
![QQ图片20201027195640](https://user-images.githubusercontent.com/50727631/97300083-ec13a600-1890-11eb-881e-79a32f355129.png)
![QQ图片20201027195647](https://user-images.githubusercontent.com/50727631/97300092-eddd6980-1890-11eb-93ea-537156257f78.png)

**复现方法**
10月26日突然出现问题，登录提示使用安卓pad协议
群消息正常发送，在重启程序，系统，更换其他电脑及网络均出现该问题
在上传图片失败时，如果仅有图片时，则会发送空消息 接收方有消息提示音，但看不到消息。
使用电脑版QQ、安卓手机版QQ、使用该账号均能正常发送图片。
更换go-cqhttp版本、删除所有程序目录下子文件，仍旧出现问题

**Comment by Mrs4s** [comment]
尝试更换账号试试？

**Comment by LR1093141031** [comment]
> 尝试更换账号试试？

陷入沉思，更换账号之后，新账号可以发图。那就是TX只风控了这个账号的一个特定设备类型？

**Comment by Mrs4s** [comment]
奇怪 怀疑是什么新的风控...
之前账号发图时候频繁

**Comment by LR1093141031** [comment]
> 奇怪 怀疑是什么新的风控...
> 之前账号发图时候频繁

每天发图数量不超过50张的程度吧，而且只有私聊是这样的。群聊没关系

**Comment by LR1093141031** [comment]
![image](https://user-images.githubusercontent.com/50727631/97466719-5fdfac80-197e-11eb-85c8-a1fd55e59a91.png)
另一个号码现在连消息发送失败都不提醒了，被直接拦截所有带图片的消息，接收方看不到且没有消息提示音。

**Comment by Mrs4s** [comment]
看情况应该是一个风控，我这边暂时无能为力

**Comment by HinanawiCook** [comment]
me too

**Comment by Sing-Chancial** [comment]
我也出现这个问题了linux7.6 cqhttp是最新的  我是正向反响ws都在用 出现问题前同样执行过一次关闭所有bot和相关进程以及重启服务器 之后登录cqhttp报错无法连接数据库登录失败 bot的qq从关闭到这里为止都还在线 手机登录qq后删除了设备信息强制下线后可以正常登录 之后就是一模一样的问题了

**Comment by AOALI123** [comment]
看见大家都有这个问题 我就放心了

**Comment by AOALI123** [comment]
> 看见大家都有这个问题 我就放心了

我突然有个神奇的想法 既然是某种不确定的风控 那 遇事不决先给冲个会员试试 我以前确实拿这招解决过一些神奇的类似风控的问题

**Comment by LR1093141031** [comment]
> > 看见大家都有这个问题我就放心了
> 
> 我突然有个神奇的想法既然是某种不确定的风控那遇事不决先给冲个会员尝试我以前确实拿了这招解决过一些神奇的类似风控的问题

hhhh，你先试试。不过tx在某些东西上确实是比较势利。要是可以我也冲

**Comment by AOALI123** [comment]
> > > 看见大家都有这个问题我就放心了
> > 
> > 
> > 我突然有个神奇的想法既然是某种不确定的风控那遇事不决先给冲个会员尝试我以前确实拿了这招解决过一些神奇的类似风控的问题
> 
> hhhh，你先试试。不过tx在某些东西上确实是比较势利。要是可以我也冲

我冲了 目前效果还没有 等几天看看我来汇报

**Comment by Mrs4s** [comment]
请尝试这个版本 https://github.com/Mrs4s/go-cqhttp/actions/runs/357888673 理论上修复了

**Comment by AOALI123** [comment]
> 请尝试这个版本 https://github.com/Mrs4s/go-cqhttp/actions/runs/357888673 理论上修复了

已下载测试 目前恢复正常 感谢
