### ISSUE TITLE
挂的时间长了(几小时)，群聊无法发送3个以上字节

### ISSUE THREAD

**Issue by takayama-lily** [Mrs4s/go-cqhttp#38]
只能发送1-2个字节，1个汉字也无法发送(大概占3字节的原因)，私聊没有问题。
用mirai-native的cqhttp也出现过这个问题，怀疑是协议里的bug。
控制台一切正常(没开debug)。mirai-native的控制台也是一切正常，并且提示发送成功。
![D AEE YMW}0T7_PD 8%@Z7F](https://user-images.githubusercontent.com/12014361/89375816-78e31380-d729-11ea-8bb5-25fad468764a.png)
暂时没有更多的情报了。
还有一些零碎的，整理好了发上来。

**Comment by takayama-lily** [comment]
不可见字符(空格、换行)貌似不受限制
![5HY9NQ$J1~ 7C4T78$(F{QF](https://user-images.githubusercontent.com/12014361/89376811-92855a80-d72b-11ea-91a5-f82761e96467.png)

**Comment by mnixry** [comment]
被风控了这是，不是程序问题（大概

**Comment by Shigma** [comment]
+1 我也这么认为

**Comment by Mrs4s** [comment]
我这边无法复现，也怀疑是风控导致的.

**Comment by mnixry** [comment]
> 这个问题看起来不属于程序问题，更类似于触发了腾讯的风控机制

题外话：
似乎go-mirai的风控时间比mirai要长？很奇怪
我的bot在go-mirai下挂了24h+还是处于类似的风控状态，但是用原本的mirai风控程度就没有那么高

**Comment by remiliacn** [comment]
我经常用的QQ机器人号复现issue失败，上周刚注册几乎没怎么用过的机器人号挂服务器偶尔会出现这种问题。
应该是风控的元素。

**Comment by allofee** [comment]
遇到过运行时间长了之后发出去的消息收不到，重新登录可以立即恢复正常。

**Comment by Mrs4s** [comment]
经测试应该是风控因素导致的.

**Comment by Arnie97** [comment]
我发现风控发不出去的时候，返回的 message_id 相同，
暂时用检测到 message_id 重复时重新登录作为 workaround 了。

**Comment by allofee** [comment]
> 我发现风控发不出去的时候，返回的 message_id 相同，
> 暂时用检测到 message_id 重复时重新登录作为 workaround 了。

这个 workaround 现在没法自动实现吧。

**Comment by takayama-lily** [comment]
我现在已经遇不到这个问题了。
朋友用mirai-native一开始也遇到，过了几天就好了。

**Comment by libsyc** [comment]
遇到同一个问题，重启就成功了
