### ISSUE TITLE
手机无法正常显示gif格式的图片

### ISSUE THREAD

**Issue by zangxx66** [Mrs4s/go-cqhttp#380]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.29-fix2
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
发送gif格式的图片只能在pc端正常显示

**复现方法**
MessageSegment.image(f'file:////root/HoshinoBot/res/img/1.gif')  
通过此方法构造的cq码，gif格式图片仅pc端能显示，手机端无法点开大图，预览图也不会动

**Comment by Mrs4s** [comment]
请确认发送的GIF帧数小于300帧，测试了一下大于300帧的GIF会出现问题

**Comment by shitianshiwa** [comment]
> 请确认发送的GIF帧数小于300帧，测试了一下大于300帧的GIF会出现问题

大于300帧是发不出去，服务器会阻止。这个应该不能解释gif在移动端的显示问题吧？

**Comment by Scarlet-Climax** [comment]
移动端QQ把图片加入收藏，然后在收藏中（下载原图）可以正常显示。
移动端TIM未测试。
