### ISSUE TITLE
支持获取陌生群信息

### ISSUE THREAD

**Issue by IMSUVEN** [Mrs4s/go-cqhttp#383]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.29-fix2
运行环境: windows_amd64
连接方式: 反向WS&http

**bug内容**
启用反向W或http请求API(get_group_info)，测试了多个群聊，都都会返回{'data': None, 'retcode': 100, 'status': 'failed'}

**复现方法**
以http为例，启动gocq后，requests请求”http://127.0.0.1:5700/get_group_info?group_id=~“

**Comment by sam01101** [comment]
接口已改回CQ版本的```get_msg```

**Comment by IMSUVEN** [comment]
> 接口已改回CQ版本的```get_msg```

get_msg是获取某条消息的消息详情吧。
现在是获取群信息的get_group_info失效了

**Comment by Mrs4s** [comment]
请问群数量是否超过了999

**Comment by IMSUVEN** [comment]
> 请问群数量是否超过了999

查询群信息需要加入该群才能查询吗？

**Comment by sam01101** [comment]
> > 请问群数量是否超过了999
> 
> 查询群信息需要加入该群才能查询吗？

你可以自己测试一下

**Comment by Mrs4s** [comment]
> > 请问群数量是否超过了999
> 
> 查询群信息需要加入该群才能查询吗？

需要啊.....

**Comment by sam01101** [comment]
> > > 请问群数量是否超过了999
> > 
> > 
> > 查询群信息需要加入该群才能查询吗？
> 
> 需要啊.....

欸, 真的? 我还以为可以只能查询到表面的信息

**Comment by IMSUVEN** [comment]
> > > 请问群数量是否超过了999
> > 
> > 
> > 查询群信息需要加入该群才能查询吗？
> 
> 需要啊.....

测试了一下，已经加入的群可以使用这个api
如果获取未加入的群的群信息，有其他api可以使用吗？

目前要应用于其他人邀请加群时，检测群名称是否满足条件

**Comment by Mrs4s** [comment]
> > > > 请问群数量是否超过了999
> > > 
> > > 
> > > 查询群信息需要加入该群才能查询吗？
> > 
> > 
> > 需要啊.....
> 
> 测试了一下，已经加入的群可以使用这个api
> 如果获取未加入的群的群信息，有其他api可以使用吗？
> 
> 目前要应用于其他人邀请加群时，检测群名称是否满足条件

我考虑做个另外的api查询吧...

**Comment by IMSUVEN** [comment]
> > > > > 请问群数量是否超过了999
> > > > 
> > > > 
> > > > 查询群信息需要加入该群才能查询吗？
> > > 
> > > 
> > > 需要啊.....
> > 
> > 测试了一下，已经加入的群可以使用这个api
> > 如果获取未加入的群的群信息，有其他api可以使用吗？
> > 
> > 目前要应用于其他人邀请加群时，检测群名称是否满足条件
> 
> 我考虑做个另外的api查询吧...

谢谢
