### ISSUE TITLE
提示QQ版本过低无法登陆

### ISSUE THREAD

**Issue by Jray616** [Mrs4s/go-cqhttp#385]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.10
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
提示QQ版本过低无法登陆

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by Mrs4s** [comment]
密码错误或账号被冻结
