### ISSUE TITLE
connection dropped by server

### ISSUE THREAD

**Issue by AiharaMei** [Mrs4s/go-cqhttp#388]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.29-fix2
运行环境: linux_amd64
连接方式: 反向WS&HTTP

**bug内容**
[2020-11-01 00:50:56] [ERROR]: Protocol -> connection dropped by server: EOF 
[2020-11-01 00:50:56] [INFO]: Protocol -> connect to server: 157.255.13.77:80 
之前也发生过一次以为是版本问题，换了v0.9.29-fix2之后用了几天也出现了这个问题

**复现方法**
不清楚如何复现

**Comment by Mrs4s** [comment]
如果自动重连后无任何其他问题就不用管，这个是网络波动

**Comment by sam01101** [comment]
> **环境信息**
> 请根据实际使用环境修改以下信息
> go-cqhttp版本: v0.9.29-fix2
> 运行环境: linux_amd64
> 连接方式: 反向WS&HTTP
> 
> **bug内容**
> [2020-11-01 00:50:56] [ERROR]: Protocol -> connection dropped by server: EOF
> [2020-11-01 00:50:56] [INFO]: Protocol -> connect to server: 157.255.13.77:80
> 之前也发生过一次以为是版本问题，换了v0.9.29-fix2之后用了几天也出现了这个问题
> 
> **复现方法**
> 不清楚如何复现

请关闭issuse

**Comment by yuban01652** [comment]
我这里从0.9.25升上来后会一直持续报这个消息，但不影响使用。
我删了device.json让它重新生成设备，就不会报错了，不知道是否通用。
