### ISSUE TITLE
发送到语音在iOS设备听不了

### ISSUE THREAD

**Issue by var-mixer** [Mrs4s/go-cqhttp#390]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.29
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
语音只能在安卓设备和电脑上听，iOS设备点一下就立刻停止播放。原始格式为mp3，已配置ffmpeg。直接发送的silk语音也无法播放。

与此相对另一个问题是GIF图只能在iOS看而不能在安卓手机看，安卓点开就是空白……挺奇怪的，看了下已经有人提出了。

**复现方法**
发送一段语音，在iOS设备最新版QQ客户端点击播放。（测试是使用的是iPad，并连接了蓝牙耳机）

**Comment by Mrs4s** [comment]
QQ的客户端是真的狗屎

**Comment by planevina** [comment]
我也遇到这个问题了，闪一下就停止了，是qq客户端的问题吗
那我还是只有在服务器端直接先压成amr格式
