### ISSUE TITLE
毫无预告的堵塞

### ISSUE THREAD

**Issue by sam01101** [Mrs4s/go-cqhttp#391]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.10
运行环境: linux arm 64
连接方式: 反向WS

**bug内容**
![image](https://user-images.githubusercontent.com/25792361/98001016-1e407d00-1e28-11eb-92d2-625e57737f73.png)
![image](https://user-images.githubusercontent.com/25792361/98001106-3b754b80-1e28-11eb-9a6c-d05549c480f6.png)
![image](https://user-images.githubusercontent.com/25792361/98001138-43cd8680-1e28-11eb-993b-68f5be6b6b67.png)

**复现方法**
无法复现, 突然发生
(所以有点多余, 但我决定还是先report)

**Comment by sam01101** [comment]
算了真的是多余的

**Comment by Mrs4s** [comment]
这个真的是应用层过慢，请检查 go-cqhttp 与相关应用之间的网络连接

**Comment by sam01101** [comment]
![image](https://user-images.githubusercontent.com/25792361/98007677-a164d180-1e2e-11eb-9ee7-d19d31061dc5.png)
