### ISSUE TITLE
http_config配置中增加了post_url无法接收到信息

### ISSUE THREAD

**Issue by jiachengbo830101** [Mrs4s/go-cqhttp#392]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.26
运行环境: windows2012
连接方式: 反向WS

**bug内容**
原酷Q版本中配置好POST_URL地址后，群里发送的消息，使用PHP的file_get_contents('php://input')可以获取到POST_URL地址接收的内容，可以实现群消息记录，现在在HTTP_CONFIG里加入不能够使用，请大神指导
"http_config": {
		"enabled": true,
		"host": "127.0.0.1",
		"port": 5700,
		"timeout": 0,
		"post_url": "http://127.0.0.1:8080/index.php",
		"post_urls": {}
	},

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by Mrs4s** [comment]
请看文档，在 go-cqhttp中需要填写的是 post_urls 字段，不放心可以使用自动转移配置文件
