### ISSUE TITLE
好友会话发送部分长消息时出错

### ISSUE THREAD

**Issue by ZCchann** [Mrs4s/go-cqhttp#393]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.29-fix2 
运行环境: centos7
连接方式: post url
脚本语音 python3

**bug内容**
通过http post 连接脚本 脚本使用CQ码发送网络图片 返回错误日志
传送参数：
{
        "user_id": eval_cqp_data['user_id'],
        "message": "[CQ:image,url=https://i.pixiv.cat/img-master/img/2020/03/25/00/00/08/80334602_p0_master1200.jpg]”
    }
错误日志：
 [WARNING]: 转换CQ码 [CQ:image,url=https://i.pixiv.cat/img-master/img/2020/03/25/00/00/08/80334602_p0_master1200.jpg] 到MiraiGo Element时出现错误: read data/images: is a directory 将原样发送. 
————————————————————————————

或发送下列信息给go-cqhttp
{'user_id': 1544988551, 'message': '[CQ:image,file=https://img1.saucenao.com/res/pixiv/969/9690586_s.jpg?auth=0Y1P9FIg3s0jA8keuroxVQ&exp=1604479726]\n相似度 41.18%\n作者名称 燐@三次忍にお熱\n图片名称 池袋に来んなっつったよなあ\nP站id 9690586\n图片链接 \nhttps://www.pixiv.net/member_illust.php?mode=medium&illust_id=9690586'}

日志信息：
[2020-11-04 15:13:51] [INFO]: 发送好友  的消息: [CQ:image, ... (2126345555) 
[2020-11-04 15:14:01] [WARNING]: 上报Event数据 {"font":0,"message":"[CQ:image,file=6944a049d406405ad917ee7fa35b1b99.image,url=http://c2cpicdw.qpic.cn/offpic_new/1544988551//1544988551-3534086829-6944A049D406405AD917EE7FA35B1B99/0?term=2]","message_id":1601658368,"message_type":"private","post_type":"message","raw_message":"[CQ:image,file=6944a049d406405ad917ee7fa35b1b99.image]","self_id":XXXXXX,"sender":{"age":0,"nickname":"zc","sex":"unknown","user_id":1544988551},"sub_type":"friend","time":1604474027,"user_id":XXXXXX} 到 http://127.0.0.1:5000/ 失败: retry fail 

若发送信息中不带有[CQ:image] 则不报错

**Comment by Mrs4s** [comment]
请使用 `[CQ:image,file=https://i.pixiv.cat/img-master/img/2020/03/25/00/00/08/80334602_p0_master1200.jpg]`

**Comment by ZCchann** [comment]
使用[CQ:image,file=XXXXXX]只发送图片可以 发送图片带文字的内容就会报错了

**Comment by ZCchann** [comment]
请问发送内容是否有长度限制？

**Comment by ZCchann** [comment]
请问发送图片+文字内容是否有长度限制？
我这边早上按照您之前回复的CQ码发送图片无问题 但是总内容长度超出一定范围后会出现go-cqhttp无法发送内容
而且会出现一个现象，内容已发送但是返回一个报错日志
![image](https://user-images.githubusercontent.com/49514149/98191286-d1f25b80-1f53-11eb-9dd4-00c539c2b584.png)

**Comment by Mrs4s** [comment]
> 请问发送图片+文字内容是否有长度限制？
> 我这边早上按照您之前回复的CQ码发送图片无问题 但是总内容长度超出一定范围后会出现go-cqhttp无法发送内容
> 而且会出现一个现象，内容已发送但是返回一个报错日志
> ![image](https://user-images.githubusercontent.com/49514149/98191286-d1f25b80-1f53-11eb-9dd4-00c539c2b584.png)

这个错误是上报数据到应用层HTTP服务器失败，请检查应用

**Comment by ZCchann** [comment]
> > 请问发送图片+文字内容是否有长度限制？
> > 我这边早上按照您之前的回复的CQ码发送图片无问题但是总内容长度超出一定范围后会出现go-cqhttp无法发送内容并且
> > 会出现一个现象，内容已发送但是返回一个报错日志
> > ![图片](https://user-images.githubusercontent.com/49514149/98191286-d1f25b80-1f53-11eb-9dd4-00c539c2b584.png)
> 
> 这个错误是上报数据到应用层HTTP服务器失败，请检查应用

我QQ上收到消息了 但是日志会提示报错

**Comment by Mrs4s** [comment]
> > > 请问发送图片+文字内容是否有长度限制？
> > > 我这边早上按照您之前的回复的CQ码发送图片无问题但是总内容长度超出一定范围后会出现go-cqhttp无法发送内容并且
> > > 会出现一个现象，内容已发送但是返回一个报错日志
> > > ![图片](https://user-images.githubusercontent.com/49514149/98191286-d1f25b80-1f53-11eb-9dd4-00c539c2b584.png)
> > 
> > 
> > 这个错误是上报数据到应用层HTTP服务器失败，请检查应用
> 
> 我QQ上收到消息了 但是日志会提示报错

这个是上报 Event 到应用出错的，和QQ没任何关系

**Comment by ZCchann** [comment]
> > > > 请问发送图片+文字内容是否有长度限制？
> > > > 我这边早上按照您之前的回复的CQ码发送图片无问题但是总内容长度超出一定范围后会出现go-cqhttp无法发送内容并且
> > > > 会出现一个现象，内容已发送但是返回一个报错日志
> > > > ![图片](https://user-images.githubusercontent.com/49514149/98191286-d1f25b80-1f53-11eb-9dd4-00c539c2b584.png)
> > > 
> > > 
> > > 这个错误是上报数据到应用层HTTP服务器失败，请检查应用
> > 
> > 
> > 我QQ上收到消息了 但是日志会提示报错
> 
> 这个是上报 Event 到应用出错的，和QQ没任何关系

这个报错我看看怎么检查
那请问一下 从我的应用发送“图片”+“文字”信息 超出一定长度以后 go-cqhttp发送的内容 在QQ上无法显示这个有办法可以处理么？

**Comment by Mrs4s** [comment]
> > > > > 请问发送图片+文字内容是否有长度限制？
> > > > > 我这边早上按照您之前的回复的CQ码发送图片无问题但是总内容长度超出一定范围后会出现go-cqhttp无法发送内容并且
> > > > > 会出现一个现象，内容已发送但是返回一个报错日志
> > > > > ![图片](https://user-images.githubusercontent.com/49514149/98191286-d1f25b80-1f53-11eb-9dd4-00c539c2b584.png)
> > > > 
> > > > 
> > > > 这个错误是上报数据到应用层HTTP服务器失败，请检查应用
> > > 
> > > 
> > > 我QQ上收到消息了 但是日志会提示报错
> > 
> > 
> > 这个是上报 Event 到应用出错的，和QQ没任何关系
> 
> 这个报错我看看怎么检查
> 那请问一下 从我的应用发送“图片”+“文字”信息 超出一定长度以后 go-cqhttp发送的内容 在QQ上无法显示这个有办法可以处理么？

超过一定长度具体是多长，发送时有没有报错

**Comment by Mrs4s** [comment]
另外临时会话是不支持长消息的

**Comment by ZCchann** [comment]
> 另外临时会话是不支持长消息的

对话类型是好友会话
发送下面这段信息 QQ聊天窗口可以收到信息
{'user_id': 1544988551, 'message': '[CQ:image,file=https://img1.saucenao.com/res/pixiv/8490/84908439_p0_master1200.jpg?auth=aLKUZLHlWi9-vfYv6pmI1A&exp=1604548983]相似度 92.38%\nP站id 84908439\n'}
——————————
这段信息在QQ聊天窗口就看不到了 发送不出来
{'user_id': 1544988551, 'message': '[CQ:image,file=https://img1.saucenao.com/res/pixiv/6912/69122139_p0_master1200.jpg?auth=aOQElqIPWryDXjuZHIAlrw&exp=1604549105] \n相似度 79.32%\n作者名称 きみしま青\n图片名称 咲希ちゃんとバカンス\nP站id 69122139\n图片链接 \nhttps://www.pixiv.net/member_illust.php?mode=medium&illust_id=69122139'}

**Comment by ZCchann** [comment]
另外 上报Event数据错误的部分我看了一下

我的应用的操作步骤
我发送指令给机器人——机器人返回指令——我发送图片给机器人——机器人返回搜图结果

会返回上报Event数据错误是在机器人返回搜图结果的部分
而且比较奇怪的是 时间线如下：
10:30:07 go-cqhttp收到我从QQPC客户端发送的图片
10:30:10 我的应用发送内容给go-cqhttp QQ PC客户端收到了消息  应用返回信息 "POST / HTTP/1.1" 200 -
10:30:14 go-cqhttp日志提示上报Event数据错误

**Comment by Mrs4s** [comment]
我晚上试试能不能复现

**Comment by ZCchann** [comment]
> 我晚上试试能不能复现

感谢！

**Comment by Mrs4s** [comment]
> 另外 上报Event数据错误的部分我看了一下
> 
> 我的应用的操作步骤
> 我发送指令给机器人——机器人返回指令——我发送图片给机器人——机器人返回搜图结果
> 
> 会返回上报Event数据错误是在机器人返回搜图结果的部分
> 而且比较奇怪的是 时间线如下：
> 10:30:07 go-cqhttp收到我从QQPC客户端发送的图片
> 10:30:10 我的应用发送内容给go-cqhttp QQ PC客户端收到了消息 应用返回信息 "POST / HTTP/1.1" 200 -
> 10:30:14 go-cqhttp日志提示上报Event数据错误

这个是一个Event上报出错了
具体的话就是 go-cqhttp 的 `http client` 试图 `POST` Event 数据到应用层的 `http server`, 但是重试五次之后这个请求仍然失败了, 才会出现这个报错

**Comment by ZCchann** [comment]
> 我晚上试试能不能复现

群聊 发送图片+文字 长内容也会不显示 要麻烦您查看一下 感谢
