### ISSUE TITLE
咨询一下接收事件的配置文档具体在哪

### ISSUE THREAD

**Issue by bbhxwl** [Mrs4s/go-cqhttp#394]
咨询一下接收事件的配置文档具体在哪，没找到，第一次用这个，刚会使用http接口发送消息之类的。暂时还不会被动接收消息事件，没找到具体文档在哪里。

**Comment by Mrs4s** [comment]
https://github.com/howmanybots/onebot/blob/master/v11/specs/event/README.md https://github.com/Mrs4s/go-cqhttp/blob/master/docs/cqhttp.md
