### ISSUE TITLE
新QQ无法使用go-cqhttp

### ISSUE THREAD

**Issue by lbftime** [Mrs4s/go-cqhttp#396]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.29 and v0.9.21
运行环境: linux
连接方式: 反向WS

**bug内容**
新QQ号登录后，出现错误导致无法登录，错误信息如下：
[WARNING]: 登录失败: 当前版本过低，请先升级到手机QQ最新版本。

**复现方法**
新注册QQ号，使用go-cqhttp登录。

**Comment by Mrs4s** [comment]
密码错误或者账号被冻结
