### ISSUE TITLE
get_msg 无法正常获取发送消息的CQ码

### ISSUE THREAD

**Issue by jianmj** [Mrs4s/go-cqhttp#397]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.29-fix2
运行环境: centos 7
连接方式: WS

**bug内容**
使用 go-cqhttp 发送一个带 CQ码的图文消息，但是返回的响应数据里
只显示文字部分

**复现方法**
1.使用 ws 方式 ，发送群消息
![image](https://user-images.githubusercontent.com/19400782/98230780-83b27c00-1f96-11eb-8426-d4a0a4c42a65.png)
2.使用 消息ID 查询 
![image](https://user-images.githubusercontent.com/19400782/98230912-af356680-1f96-11eb-9c59-63740a97e63b.png)

**Comment by Mrs4s** [comment]
试试接收的消息，应该能获取到cq码。 发送我检查下 应该是bug

**Comment by Mrs4s** [comment]
发送确实是bug

**Comment by jianmj** [comment]
抱歉回复迟了，接收消息是有带 CQ码的
