### ISSUE TITLE
重连限制失效的问题

### ISSUE THREAD

**Issue by KotoriK** [Mrs4s/go-cqhttp#398]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.29
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
断了个网，gocq这边开始自动重试，每次重试报一个“An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.”，然后紧接着又继续重试，高速占用CPU与内存，并产生大量的log，让本身就不富裕的内存雪上加霜
反正我吃个饭回来看到1个G的log人傻了
**复现方法**
在电脑内存不足的时候断网（？）

**Comment by Mrs4s** [comment]
请尝试调整重试上限和重试间隔, 太低的话可能会导致重试过快

**Comment by KotoriK** [comment]
但是我的重连配置是：
"relogin": {
		"enabled": true,
		"relogin_delay": 5,
		"max_relogin_times": 100
	},
因网络断开的重连失败，达到这个上限后会自动退出
问题是上面给你报告的这个异常不会正确触发这个重连限制

**Comment by Mrs4s** [comment]
能否把错误时的日志贴一下

**Comment by KotoriK** [comment]
1.4个G 我已经删掉了
就是重复地报An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.

**Comment by Mrs4s** [comment]
得看具体是什么地方报错。。。 
请问是Protocol的报错还是go-cqhttp的报错?

**Comment by KotoriK** [comment]
我看了一下之前的log回忆了一下
似乎是这样一组的log循环：
[2020-11-04 18:46:36] [INFO]: Protocol -> connect to server: 42.81.172.81:80 
[2020-11-04 18:46:38] [INFO]: Protocol -> connect to server: 113.96.12.217:80 
[2020-11-04 18:46:38] [INFO]: Protocol -> connect to server: 114.221.144.89:8080 
然后最后一条跟一个connect failed和之前说的那个错误

**Comment by Mrs4s** [comment]
请问是报错的前缀是否是 `connection dropped by server: xxxx`

**Comment by KotoriK** [comment]
应该不是 这个时候互联网是已经断开了的
然后我就看到我的两个go-cqhttp.exe都占到了1G左右的内存空间，同时有20%的CPU占用
然后打开cli就看到疯狂跳信息

**Comment by Mrs4s** [comment]
非常奇怪，底层的重连也有次数限制的，可能需要等下次复现保留日志来分析了

**Comment by KotoriK** [comment]
因为我是吃完饭回来才看到 所以并不清楚它这样持续了多久
（一个G的log文件直接爆内存打不开我就删掉了）

**Comment by KotoriK** [comment]
我猜内存爆破是不断地创建连接导致的吧？如果正常走了重连逻辑应该不会这样
我Recuva一下看看能不能把log拉回来

**Comment by Mrs4s** [comment]
只看错误信息的话问题应该是吧连接数消耗完了，存在连接泄露的问题

**Comment by Mrs4s** [comment]
似乎没再遇到类似问题了
