### ISSUE TITLE
日志中文乱码

### ISSUE THREAD

**Issue by xxyy3130** [Mrs4s/go-cqhttp#399]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.29-fix2
运行环境: windows_amd64
连接方式: WS

**bug内容**
log文件中文乱码

**复现方法**
![image](https://user-images.githubusercontent.com/61443746/98333529-ec9fff80-203b-11eb-9fa9-6742f4313115.png)

**Comment by Mrs4s** [comment]
请使用 `notepad++` `vs code` 等编辑器，不要使用windows自带的记事本
