### ISSUE TITLE
暂时找到的bug

### ISSUE THREAD

**Issue by daofeng2015** [Mrs4s/go-cqhttp#4]
1.好友私聊消息撤回失败
![image](https://user-images.githubusercontent.com/14891398/88662286-5428e380-d10c-11ea-9bf0-ec94b0b6ebcf.png)
![image](https://user-images.githubusercontent.com/14891398/88662356-6c006780-d10c-11ea-9cb6-c24f85b16f7f.png)
2.群单独禁言的时长默认值为0,取消禁言,而不是文档所写的30*60
![image](https://user-images.githubusercontent.com/14891398/88664698-0910cf80-d110-11ea-8e4f-e1d8c7063a30.png)
3.群全体禁言无法关闭
![image](https://user-images.githubusercontent.com/14891398/88664968-745aa180-d110-11ea-92eb-5f88665e6927.png)
暂时就找到这几个....

**Comment by Mrs4s** [comment]
Q2 已修复
Q1和Q3为MiraiGo实现问题，将在那边进行修复
