### ISSUE TITLE
Post "HTTP://127.0.0.1:8080": context deadline exceeded.

### ISSUE THREAD

**Issue by jiangjiangflies** [Mrs4s/go-cqhttp#401]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.30
运行环境: windows_amd64
连接方式: CQ HTTP

**bug内容**
Post "HTTP://127.0.0.1:8080": context deadline exceeded.

**复现方法**
请问上报消息的时候是不是有时间限制？QQ收到消息的时候，我会运行一个爬虫程序，再将结果上报，处理得快的话就可以上报成功，慢的话总是失败。

**Comment by Mrs4s** [comment]
A. 请设置配置文件中的 `http_config.timeout` 调大超时限制. (单位秒)
B. 切换到ws连接方式
C. 将会长时间阻塞响应的操作异步化.

**Comment by voidyi** [comment]
另外这里有重试机制，能否加个上报推送重试次数配置呢，避免多次重试

**Comment by voidyi** [comment]
另外这里有重试机制，能否加个上报推送重试次数配置呢，避免多次重试
![image](https://user-images.githubusercontent.com/25685086/145914977-6763bebf-470f-4c18-8a63-c5fba1fad47d.png)

**Comment by jiangjiangflies** [comment]
来信已收到！祝好！
