### ISSUE TITLE
带连接的长消息发布出去。

### ISSUE THREAD

**Issue by chenxuxin188** [Mrs4s/go-cqhttp#406]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.30
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
带连接的长消息发布出去。
我的bot带B站动态提醒功能，当转发视频的时候：
![image](https://user-images.githubusercontent.com/30059986/98636672-40ca1d00-2377-11eb-9ba0-34c5ff50137b.png)
会提醒：
![image](https://user-images.githubusercontent.com/30059986/98636697-4de70c00-2377-11eb-8f10-3856cfc02d46.png)

内容为  转发的之间戳+转发内容+视频标题+视频链接。
但是转发内容和视频标题长一些的时候，就发送不出去了。
比如这个：
![image](https://user-images.githubusercontent.com/30059986/98636805-74a54280-2377-11eb-8e43-6ca3dc3c243d.png)

会发送失败

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by Mrs4s** [comment]
消息内容能否给个例子

**Comment by chenxuxin188** [comment]
就比如最后一张图
```
[2020-11-10 20:09:30]
im in a video?
ok, repost and go back to sleepzzzzzzzzzzzzzz:
【直播虚拟酱第一期】hiiro初唱aimer曲 拉法赌输成光头
https://www.bilibili.com/video/BVxxxxxxxxxxxx
```

**Comment by xb2016** [comment]
+1 我也遇到过好几次此类问题了 前面这条示例我也发不出去

**Comment by chenxuxin188** [comment]
目前只能把链接分开单独发了_(:з」∠)_
