### ISSUE TITLE
希望添加重启 api

### ISSUE THREAD

**Issue by SK-415** [Mrs4s/go-cqhttp#407]
希望能支持 onebot 的 [`set_restart`](https://github.com/howmanybots/onebot/blob/master/v11/specs/api/public.md#set_restart-%E9%87%8D%E5%90%AF-onebot-%E5%AE%9E%E7%8E%B0) api

不直接用 admin api 是因为 admin api 需要单独开启一个端口, 不同的 go-cqhttp 的 admin api 还不能用同一个端口. 同时我通过后端 nonebot 的 api 也无法获取到指定 bot 的 admin api 监听的是哪个端口, 这对开发诸如自动重启造成了困难. 

我需要开发重启方法还是因为 #382 和 #343 的问题, 目前我是在发现连续发送失败之后会尝试重启 go-cqhttp, 总体效果还不错, 也算间接解决了这个问题. 但是没有 onebot 实现的重启 api, 我只能直接在系统里查找 go-cqhttp 的进程杀死后重启. 不仅极不优雅, 对于多平台适配也很麻烦.

**Comment by zangxx66** [comment]
我建议是自己在nonebot开一个http接口，用来控制go-cqhttp，机器人掉线并不影响nonebot部分的使用，例如带web的插件

**Comment by SK-415** [comment]
> 我建议是自己在nonebot开一个http接口，用来控制go-cqhttp，机器人掉线并不影响nonebot部分的使用，例如带web的插件

我一开始也是这个思路，但是这对于多个 go-cqhttp 连接同一个 nonebot 很不友好，每个 go-cqhttp 的 admin 端口都不一样，我在 nonebot 中还无法通过诸如 `get_version_info` 这些 api 获取每个 bot 开启 admin 的端口是哪个, 这样我为了重启还得事先一个一个设置好每个 bot 对应的端口号. 为了减少这种不必要的设置, 我才迫不得已直接操作进程.
