### ISSUE TITLE
私聊图片上传失败

### ISSUE THREAD

**Issue by AOALI123** [Mrs4s/go-cqhttp#408]
搜图机器人搜图以后 群内图片发送正常 私聊图片显示上传失败 原因不明
![D9%1{)00}9}1U@))B{5K8@N](https://user-images.githubusercontent.com/48720541/98695527-b4871c80-23ad-11eb-9a13-40abc2d5c915.png)

环境信息
go-cqhttp版本: v0.9.30
运行环境: winserver2008
连接方式: 反向WS

**Comment by AOALI123** [comment]
![MK_3~7RLSH85Y9%E@8P0E5W](https://user-images.githubusercontent.com/48720541/98695675-da142600-23ad-11eb-8e4e-431cb1113beb.png)

**Comment by AOALI123** [comment]
救救孩子

**Comment by Mrs4s** [comment]
#378
