### ISSUE TITLE
消息接受有概率重复

### ISSUE THREAD

**Issue by mnixry** [Mrs4s/go-cqhttp#41]
在同时在配置文件中启用ws，ws_reverse和http时，通过ws_reverse会发出多条重复的消息

p.s.这个问题我没有测试，但是有几个人反映了

update.这个问题貌似复现方法不稳定但确实存在 @Kyomotoi 目前遇到了这个问题

**Comment by Kyomotoi** [comment]
跟进：配置中关闭ws、http，只保留ws_reverse时，会返回多次重复信息
如果搭配NoneBot使用，则在NoneBot会解析两次，发送两次返回

**Comment by Mrs4s** [comment]
目前逻辑是同时存在universal server和event server的话就会同时给这两个服务器推送事件，理论上应该不会单独重复。


> 跟进：配置中关闭ws、http，只保留ws_reverse时，会返回多次重复信息
> 如果搭配NoneBot使用，则在NoneBot会解析两次，发送两次返回

请问重复推送的情况下go-cqhttp的日志有没有重复打印

**Comment by Kyomotoi** [comment]
> 目前逻辑是同时存在universal server和event server的话就会同时给这两个服务器推送事件，理论上应该不会单独重复。
> 
> > 跟进：配置中关闭ws、http，只保留ws_reverse时，会返回多次重复信息
> > 如果搭配NoneBot使用，则在NoneBot会解析两次，发送两次返回
> 
> 请问重复推送的情况下go-cqhttp的日志有没有重复打印
>
>  go-cqhttp日志内并没有重复打印

**Comment by 0akarma** [comment]
> 跟进：配置中关闭ws、http，只保留ws_reverse时，会返回多次重复信息
> 
> 如果搭配NoneBot使用，则在NoneBot会解析两次，发送两次返回

我用的时候，关闭ws、ws_reverse，只用http也会随机返回多次重复信息

**Comment by Mrs4s** [comment]
这个似乎是比较奇怪的情况，我这边暂时没办法复现

**Comment by Shigma** [comment]
我这可以复现，给一个例子：

![image](https://user-images.githubusercontent.com/33423008/89498528-faea3f80-d7f0-11ea-9b01-0e0d817ce0fb.png)

红色框是一种期望的输入/输出，蓝色框是另一种期望的输入/输出，但是中途某个红色框输入被触发了两次。

![image](https://user-images.githubusercontent.com/33423008/89498639-3127bf00-d7f1-11ea-84cc-7d410447c452.png)

这里控制台的第三行就是重复的。

**Comment by Kyomotoi** [comment]
继这个问题：
经过新版本测试，发现**群聊**和**私聊**中回应消息依然存在**返回多次重复信息**，日志内正常
私聊
![](https://pic.downk.cc/item/5f2bb38914195aa59461545d.png)
群聊
![](https://pic.downk.cc/item/5f2bb36314195aa594614518.png)

幸苦了！orz

**Comment by DeSireFire** [comment]
同上，我这边出现了同样的问题。
使用go-cqhttp同时使用ws和反向ws功能时，出现消息重复的现象。
反向ws对接了yobot项目，正向ws对接的是CQ-picfinder-robot项目
以下是我的配置文件信息
```text
{
	"uin": XXX,
	"password": "XXX",
	"enable_db": true,
	"access_token": "test",
	"relogin": false,
	"relogin_delay": 0,
	"http_config": {
		"enabled": false,
		"host": "0.0.0.0",
		"port": 5700,
		"post_urls": {}
	},
	"ws_config": {
		"enabled": true,
		"host": "0.0.0.0",
		"port": 6700
	},
	"ws_reverse_servers": [{
		"enabled": true,
		"reverse_url": "ws://xxx/ws/",
		"reverse_api_url": "ws://xxxx/ws/api/",
		"reverse_event_url": "ws://xxx/ws/event/",
		"reverse_reconnect_interval": 3000
	}],
	"debug": false
}
```

![image](https://user-images.githubusercontent.com/18726905/89550558-555cbd80-d83c-11ea-8554-74cc58d97c96.png)

如果作者需要我提供部署好的yobot接口，
来方便复现bug的话，可以给我留个邮箱，我把接口和token给你发过去。
经过对比，发现正向ws对接CQ-picfinder-robot回复不会出现消息重复。
但是反向ws对接的项目会出现消息重复。
（确定yobot本身没有问题）

**Comment by Mrs4s** [comment]
> 同上，我这边出现了同样的问题。
> 使用go-cqhttp同时使用ws和反向ws功能时，出现消息重复的现象。
> 反向ws对接了yobot项目，正向ws对接的是CQ-picfinder-robot项目
> 以下是我的配置文件信息
> 
> ```
> {
> 	"uin": XXX,
> 	"password": "XXX",
> 	"enable_db": true,
> 	"access_token": "test",
> 	"relogin": false,
> 	"relogin_delay": 0,
> 	"http_config": {
> 		"enabled": false,
> 		"host": "0.0.0.0",
> 		"port": 5700,
> 		"post_urls": {}
> 	},
> 	"ws_config": {
> 		"enabled": true,
> 		"host": "0.0.0.0",
> 		"port": 6700
> 	},
> 	"ws_reverse_servers": [{
> 		"enabled": true,
> 		"reverse_url": "ws://xxx/ws/",
> 		"reverse_api_url": "ws://xxxx/ws/api/",
> 		"reverse_event_url": "ws://xxx/ws/event/",
> 		"reverse_reconnect_interval": 3000
> 	}],
> 	"debug": false
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/18726905/89550558-555cbd80-d83c-11ea-8554-74cc58d97c96.png)
> 
> 如果作者需要我提供部署好的yobot接口，
> 来方便复现bug的话，可以给我留个邮箱，我把接口和token给你发过去。
> 经过对比，发现正向ws对接CQ-picfinder-robot回复不会出现消息重复。
> 但是反向ws对接的项目会出现消息重复。
> （确定yobot本身没有问题）

同时配置 `reverse_url` 和 `reverse_event_url` 的情况下消息会重复属正常情况, 下个版本我会优化

**Comment by Shigma** [comment]
上面发的是 http 的情况，ws 也可复现：

![image](https://user-images.githubusercontent.com/33423008/89568487-f86e0100-d855-11ea-9b31-e58e15fa9efd.png)

**Comment by Mrs4s** [comment]
私聊消息重复是另一个问题，正在排查

**Comment by purerosefallen** [comment]
Which mode is considered safe? http or ws or reverse ws

**Comment by Mrs4s** [comment]
fixed
