### ISSUE TITLE
关于循环掉线重连的可能原因

### ISSUE THREAD

**Issue by Sirius-System** [Mrs4s/go-cqhttp#417]
**环境信息**
go-cqhttp版本: v0.9.30-fix2
运行环境: windows_amd64
连接方式: 正向WS

**bug内容**
BUG的表现为go-cqhttp没有接收到任何消息的约17分钟后出现掉线重连，并每隔17分钟出现一次，这在前几天已经提交了BUG汇报，因今天更新到v0.9.30-fix2后依然出现该问题，所以考虑是否本人的使用环境是否和他人或者开发者有不同。

直接说我这边的原因：因为我go-cqhttp是一直从旧版本升级上来的（即每次更新只替换exe文件），怀疑因为一直使用的是旧版本配置文件，所以出现了问题
今天删除掉所有旧文件并重新配置后，就没再出现[ERROR]: Protocol -> connection dropped by server: EOF 报错，0.9.30版本后优化了重连机制，可能就是这条报错信息触发了重连，所以在我没再出现[ERROR]: Protocol -> connection dropped by server: EOF 后，也就没有出现掉线重连了（在0.9.30之前虽然也有出现该报错，但不会触发重连，也没发现go-cqhttp因为这条报错而真实掉线）
稍微对照了一下新旧文件夹里的文件，明显看出区别的是旧文件夹里存在servers.bin这个旧版本里用于缓存服务器IP的文件，除此之外没发现有其他不同（包括部分配置文件的内容）（可能有遗漏）

在书写本汇报的时候，将版本升级到了0.9.31，使用了半个小时暂时没出现同样的问题

**Comment by Mrs4s** [comment]
最新版本应该优化了链路情况，可以再试试
