### ISSUE TITLE
程序运行失败

### ISSUE THREAD

**Issue by Singularity-Syo** [Mrs4s/go-cqhttp#42]
初次使用，想请问一下 release 的可执行文件是还有什么依赖需要安装吗？
账号密码检查过可以正常登陆QQ，配置完 config 后再次运行 go-cqhttp.exe
每次都到这里窗口就自动关闭，就没有后续了，也没有报错信息，看起来像是闪退
![QQ图片20200806020627](https://user-images.githubusercontent.com/54591184/89451652-1886bd00-d78f-11ea-8909-471405109e8a.png)

**Comment by Mrs4s** [comment]
请在cmd中运行

**Comment by remiliacn** [comment]
看一下`./log`下面的log，感觉应该是设备锁的问题。

**Comment by Singularity-Syo** [comment]
> 看一下`./log`下面的log，感觉应该是设备锁的问题。

啊，确实如此，在cmd下显示了设备锁

**Comment by Singularity-Syo** [comment]
> 请在cmd中运行

是这样啊，谢谢
