### ISSUE TITLE
发送过大的Base64图片失败：Request header is too large

### ISSUE THREAD

**Issue by Widecss** [Mrs4s/go-cqhttp#421]
**环境信息**
go-cqhttp版本: v0.9.30-fix1
运行环境: windows_amd64
连接方式: http_api

**bug内容**
send_message接口请求失败并提示Request header is too large

**复现方法**
当我使用python编写程序与go-cqhttp进行http接口请求，使用get请求向send_message接口发送过长的base64图片cq码时，会出现http请求失败(431)并提示Request header is too large，此时服务端并不会log此错误，而我将同样的base64图片cq码通过reply发送则正常
![image](https://user-images.githubusercontent.com/13403908/99349075-0829c680-28d6-11eb-919d-ab9964bad0e3.png)

**Comment by Mrs4s** [comment]
请问你是怎么调用的，这个错误应该是HTTP的Header过大，但是请求应该会放在Body
难道你是直接用Query传参的吗

**Comment by Ink-33** [comment]
> 请问你是怎么调用的，这个错误应该是HTTP的Header过大，但是请求应该会放在Body
> 难道你是直接用Query传参的吗

他说get请求应该就是Query传了个巨大base64(

**Comment by Widecss** [comment]
> 请问你是怎么调用的，这个错误应该是HTTP的Header过大，但是请求应该会放在身体
> 难道你是直接用Query传参的吗
确实（），因为在酷Q上这样传是没有问题的w，所以一直没改，太麻烦的话就算了吧w，总之是有这么一个情况

**Comment by Mrs4s** [comment]
> > 请问你是怎么调用的，这个错误应该是HTTP的Header过大，但是请求应该会放在身体
> > 难道你是直接用Query传参的吗
> 
> 确实（），因为在酷Q上这样传是没有问题的w，所以一直没改，太麻烦的话就算了吧w，总之是有这么一个情况

这个是你用的库的问题...

**Comment by Ink-33** [comment]
> > 请问你是怎么调用的，这个错误应该是HTTP的Header过大，但是请求应该会放在身体
> > 难道你是直接用Query传参的吗
> 
> 确实（），因为在酷Q上这样传是没有问题的w，所以一直没改，太麻烦的话就算了吧w，总之是有这么一个情况
> 

改成用POST传参吧

**Comment by Widecss** [comment]
> > > 请问你是怎么调用的，这个错误应该是HTTP的Header过大，但是请求应该会放在身体
> > > 难道你是直接用Query传参的吗
> > 
> > 
> > 确实（），因为在酷Q上这样传是没有问题的w，所以一直没改，太麻烦的话就算了吧w，总之是有这么一个情况
> 
> 改成用POST传参吧

好的（）

**Comment by Widecss** [comment]
> > > 请问你是怎么调用的，这个错误应该是HTTP的Header过大，但是请求应该会放在身体
> > > 难道你是直接用Query传参的吗
> > 
> > 
> > 确实（），因为在酷Q上这样传是没有问题的w，所以一直没改，太麻烦的话就算了吧w，总之是有这么一个情况
> 
> 这个是你用的库的问题...

倒不是，不过已经明白问题了，感谢（）
