### ISSUE TITLE
QQ账号无法登陆，显示上网环境异常

### ISSUE THREAD

**Issue by Maplefstar** [Mrs4s/go-cqhttp#422]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.31
运行环境: windows_x86_64
连接方式: HTTP

**bug内容**
用正确的账号密码登陆时需要文字验证码，验证通过后显示：“[WARNING]: 登录失败: 当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。”
该账号的设备锁已经打开，无安全问题

**复现方法**
1、 打开设备锁
2、 写入正确的账号密码
3、 运行go-cqhttp.exe文件

**Comment by wsmnwc** [comment]
我也遇到相同问题，设备锁（现在叫安全保护）已打开

**Comment by daofeng2015** [comment]
请使用最新版本,记得不要用apad版本

**Comment by Maplefstar** [comment]
> 
> 
> 请使用最新版本,记得不要用apad版本

照做了还是没用，可能我的网络环境真有问题，回头挂服务器上应该就好了

**Comment by wsmnwc** [comment]
> 请使用最新版本,记得不要用apad版本

感谢回复，不知道是不是卸了MongDB的原因，莫名其妙的好了...

**Comment by allofee** [comment]
> > 请使用最新版本,记得不要用apad版本
> 
> 感谢回复，不知道是不是卸了MongDB的原因，莫名其妙的好了...

啊这，有什么关系？

**Comment by blackjackgg** [comment]
出现这个问题删掉device.json 重新启动就可以了 最新版亲测可用

**Comment by cheny658** [comment]
0.9.35也出现这个问题，本地windows和服务器Ubuntu18.04都出现这个问题，请问应该如何解决。上述的删掉device.json的方法尝试过了，没生效

**Comment by yxn4065** [comment]
https://blog.csdn.net/yxn4065/article/details/124355637这有解决方法不知道是不是这个问题
