### ISSUE TITLE
同意群邀请失败

### ISSUE THREAD

**Issue by Faultiness** [Mrs4s/go-cqhttp#423]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.29-fix2
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
无法通过set_group_add_request()通过群邀请，偶尔无法通过set_friend_add_request()通过好友请求。
为减小被风控的概率，目前的策略是收到群邀请或/好友请求后在本地文件储存flag，同时使用定时器定时通过群邀请。

对于群邀请储存的json部分：
![图片](https://user-images.githubusercontent.com/12472447/99375000-2dcac600-28fe-11eb-8439-260606218b36.png)

debug模式下报错截图：
![图片](https://user-images.githubusercontent.com/12472447/99374481-949baf80-28fd-11eb-82cf-1283d09ae668.png)

**复现方法**
1. 收到群邀请后本地储存flag
2. 调用await bot.set_group_add_request(flag = str(flag), type = 'invite', approve = True)通过群邀请

**Comment by Mrs4s** [comment]
此问题应该有 go-cqhttp 端的报错，请检查一下

**Comment by Faultiness** [comment]
set_group_add_request()和set_friend_add_request()的定时任务设置均被设置为每分钟运行。go-cqhttp端日志如下：
![图片](https://user-images.githubusercontent.com/12472447/99578718-30b9d980-2a18-11eb-9eb0-748140303fb6.png)

**Comment by Mrs4s** [comment]
请尝试最新版本，并记录日志

**Comment by Faultiness** [comment]
已尝试使用release中最新版go-cqhttp-v0.9.31-fix1。go-cqhttp和nonebot日志如下：
![图片](https://user-images.githubusercontent.com/12472447/99630186-5e347080-2a74-11eb-9108-885a331d3179.png)
![图片](https://user-images.githubusercontent.com/12472447/99630237-7ad0a880-2a74-11eb-8663-0bbd101a82de.png)

**Comment by Mrs4s** [comment]
没有其他报错的？

**Comment by Faultiness** [comment]
> 
> 
> 没有其他报错的？

Emm 没有

**Comment by Mrs4s** [comment]
`set_friend_add_request` 的话如果你收到一个新的请求，在 go-cqhttp 端重启后就无法处理了
group应该没这个限制

**Comment by Faultiness** [comment]
啊加好友还有这个限制吗...（不知道有没有办法可以解决一下

另：收到好友在人数较少的群组（<50人？）的邀请时会自动通过请求，但此时仍将自动储存flag（bot无法得知已自动入群）。再次调用set_group_add_request()并传入flag时会报错。例如：
![图片](https://user-images.githubusercontent.com/12472447/99631547-be2c1680-2a76-11eb-9b6c-f499171c0f4e.png)
![图片](https://user-images.githubusercontent.com/12472447/99631576-c8e6ab80-2a76-11eb-8357-b50b398ec4a6.png)

**Comment by Mrs4s** [comment]
建议使用 `get_group_system_msg` 先对消息进行检查再处理
