### ISSUE TITLE
有没有仿真的device.json？

### ISSUE THREAD

**Issue by crazywhalecc** [Mrs4s/go-cqhttp#43]
现在是mirai的

**Comment by Mrs4s** [comment]
Mrs4s/MiraiGo#9

**Comment by allofee** [comment]
cat /proc/version
cat /proc/sys/kernel/random/boot_id
cat /system/build.prop

**Comment by MayuriNFC** [comment]
(/system/build.prop)ro.build.display.id
(/system/build.prop)ro.build.product
(/system/build.prop)ro.product.system.device
board
(/system/build.prop)ro.product.system.model
(/system/build.prop)ro.system.build.fingerprint/ro.build.fingerprint
(/proc/sys/kernel/random/boot_id)
(/proc/version)
protocol
imei
(/system/build.prop)ro.product.system.brand
bootloader ("unknown")
base_band ("")
(/system/build.prop)ro.build.version.incremental/ro.system.build.version.incremental
(/system/build.prop)ro.system.build.version.release
(/system/build.prop)ro.build.version.codename
(/system/build.prop)ro.build.version.sdk/ro.system.build.version.sdk
sim_info 
os_type ("android")
mac_address
ip_address
wifi_bssid
wifi_ssid
imsi_md5
android_id
apn
(/vendor/default.prop)ro.product.vendor.name
vendor_os_name

**Comment by MayuriNFC** [comment]
> (/system/build.prop)ro.build.display.id (/system/build.prop)ro.build.product (/system/build.prop)ro.product.system.device board (/system/build.prop)ro.product.system.model (/system/build.prop)ro.system.build.fingerprint/ro.build.fingerprint (/proc/sys/kernel/random/boot_id) (/proc/version) protocol imei (/system/build.prop)ro.product.system.brand bootloader ("unknown") base_band ("") (/system/build.prop)ro.build.version.incremental/ro.system.build.version.incremental (/system/build.prop)ro.system.build.version.release (/system/build.prop)ro.build.version.codename (/system/build.prop)ro.build.version.sdk/ro.system.build.version.sdk sim_info os_type ("android") mac_address ip_address wifi_bssid wifi_ssid imsi_md5 android_id apn (/vendor/default.prop)ro.product.vendor.name vendor_os_name

不建议把过多信息真实填写
