### ISSUE TITLE
[CQ:record]要怎么用

### ISSUE THREAD

**Issue by chenxuxin188** [Mrs4s/go-cqhttp#431]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.31-fix1
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
我有一个MP3，放在go-cqhttp的根目录，data里的voice。
然后我试了下CQ码
```
[CQ:record,file=fox.mp3]    提示
转换CQ码到MiraiGo Element时出现错误: exec: "ffmpeg": executable file not found in %PATH% 将忽略本段CQ码.

[CQ:record,file=E:\\go-cqhttp\\fox.mp3] 提示syntax error
[CQ:record,file=./fox.mp3] 也是一样。
CQrecord要怎么用_(:з」∠)_

```

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by Mrs4s** [comment]
同 `[CQ:image]`, `file`字段指向本地文件时也需要使用URL格式, 例如 `[CQ:record,file=file:///E:\\fox.mp3]`

**Comment by Mrs4s** [comment]
同时需要预先安装 `ffmpeg` 以实现任意格式的发送, 具体安装方法可以百度或Google

**Comment by chenxuxin188** [comment]
谢谢
