### ISSUE TITLE
无法收到回复机器人消息中的图片

### ISSUE THREAD

**Issue by synodriver** [Mrs4s/go-cqhttp#432]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: go-cqhttp-v0.9.31-fix1
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
回复机器人图片时，预期接收到 [CQ:reply,id=-xxxxx][CQ:at,qq=xxxxx] [CQ:at,qq=xxxxx] [CQ:image,file=XXXXX] ，但是实际上最后一个消息段不存在，是一个空格（' '）

**复现方法**
回复机器人一张图片（是回复不是直接at）

**Comment by Shigma** [comment]
我这里似乎遇到了相同的问题。

**Comment by HungryBunny-wei** [comment]
我也遇到了一样的问题, 机器人发送带有图片的消息. 然后别人回复的条消息的时候replyID对不上

**Comment by yanyongyu** [comment]
nonebot2 在接收到消息的时候进行了预处理，把回复的消息进行了提取并自动获取源消息，回复的消息存储在event中

**Comment by synodriver** [comment]
编译最新版 昵昵亲自修复了
