### ISSUE TITLE
完成了基础配置 验证HTTP失败

### ISSUE THREAD

**Issue by wsmnwc** [Mrs4s/go-cqhttp#434]
大佬你好，我刚开始学习Bot的部署方法，翻阅了issue仍然有一些疑问，烦请大佬解答，非常感谢
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.31-fix1
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
按照quickstart中的步骤完成了基础配置，bot能够正常接收消息，**但在验证http是否成功配置时返回{"data":null,"retcode":100,"status":"failed"}**
![image](https://user-images.githubusercontent.com/24580021/99669781-ee91a600-2ab2-11eb-8b8b-b7f83fd11d09.png)

### go-cqhttp配置如下：
"uin": 账号,
	"password": "密码",
	"encrypt_password": false,
	"password_encrypted": "",
	"enable_db": true,
	"access_token": "",
	"relogin": {
		"enabled": true,
		"relogin_delay": 3,
		"max_relogin_times": 0
	},
	"_rate_limit": {
		"enabled": false,
		"frequency": 1,
		"bucket_size": 1
	},
	"ignore_invalid_cqcode": false,
	"force_fragmented": true,
	"heartbeat_interval": 0,
	"http_config": {
		"enabled": true,
		"host": "0.0.0.0",
		"port": 5700,
		"timeout": 0,
		"post_urls": {}
	},
	"ws_config": {
		"enabled": true,
		"host": "0.0.0.0",
		"port": 6700
	},
	"ws_reverse_servers": [
		{
			"enabled": true,
			"reverse_url": "ws://127.0.0.1:8080/ws/",
			"reverse_api_url": "ws://127.0.0.1:8080/ws/api/",
			"reverse_event_url": "ws://127.0.0.1:8080/ws/event/",
			"reverse_reconnect_interval": 3000
		}
	],
	"post_message_format": "string",
	"use_sso_address": false,
	"debug": false,
	"log_level": "",
	"web_ui": {
		"enabled": true,
		"host": "0.0.0.0",
		"web_ui_port": 9999,
		"web_input": false
	}

所用插件[ELF_RSS](https://github.com/Quan666/ELF_RSS)
按照步骤进行了迁移
### 插件配置如图：
![image](https://user-images.githubusercontent.com/24580021/99669946-1f71db00-2ab3-11eb-85d0-dd2da1899d7c.png)

**复现方法**
1.运行go-cqhttp.exe
2.运行插件（shift+右键打开powershell或命令行输入 hypercorn run:app -b 0.0.0.0:8080 ）

**Comment by Ink-33** [comment]
请问您是如何进行验证的？使用HTTP的话请提供一下完整的调用参数（query或post body）

**Comment by wsmnwc** [comment]
> 请问您是如何进行验证的？使用HTTP的话请提供一下完整的调用参数（query或post body）

感谢您的回复！我是使用了quickstart中的`http://127.0.0.1:5700/send_private_msg?user_id=[qq号]&message=[信息]`

**Comment by fkx4-p** [comment]
@wsmnwc Please, if possible show me your link. You can change your QQ number and the message into strings like "removed"

**Comment by Ink-33** [comment]
> > 请问您是如何进行验证的？使用HTTP的话请提供一下完整的调用参数（query或post body）
> 
> 感谢您的回复！我是使用了quickstart中的`http://127.0.0.1:5700/send_private_msg?user_id=[qq号]&message=[信息]` 
> 

你是不是把方括号也加上了...

**Comment by wsmnwc** [comment]
> @wsmnwc Please, if possible show me your link. You can change your QQ number and the message into strings like "removed"

Thanks for replying！i have already found the mistake that i forget to delete the **square brackets**...

**Comment by wsmnwc** [comment]
> > > 请问您是如何进行验证的？使用HTTP的话请提供一下完整的调用参数（query或post body）
> > 
> > 
> > 感谢您的回复！我是使用了quickstart中的`http://127.0.0.1:5700/send_private_msg?user_id=[qq号]&message=[信息]`
> 
> 你是不是把方括号也加上了...

是这样的...抱歉占用您的时间了，重试了一下已经OK了，还想要请教一下，请问如何调用插件教程中提到的API呢，我私聊bot发送了一系列命令都没有得到回应，包括添加订阅等等

**Comment by Ink-33** [comment]
> > > > 请问您是如何进行验证的？使用HTTP的话请提供一下完整的调用参数（query或post body）
> > > 
> > > 
> > > 感谢您的回复！我是使用了quickstart中的`http://127.0.0.1:5700/send_private_msg?user_id=[qq号]&message=[信息]`
> > 
> > 你是不是把方括号也加上了...
> 
> 是这样的...抱歉占用您的时间了，重试了一下已经OK了，还想要请教一下，请问如何调用插件教程中提到的API呢，我私聊bot发送了一系列命令都没有得到回应，包括添加订阅等等

您指的是`ELS_RSS`吗？
很抱歉由于我没有使用过这个插件，无法为您继续提供帮助。建议您
- 检查`ELS_RSS`的log，确认插件是否收到调用请求或有错误抛出

**Comment by wsmnwc** [comment]
> > > > > 请问您是如何进行验证的？使用HTTP的话请提供一下完整的调用参数（query或post body）
> > > > 
> > > > 
> > > > 感谢您的回复！我是使用了quickstart中的`http://127.0.0.1:5700/send_private_msg?user_id=[qq号]&message=[信息]`
> > > 
> > > 
> > > 你是不是把方括号也加上了...
> > 
> > 
> > 是这样的...抱歉占用您的时间了，重试了一下已经OK了，还想要请教一下，请问如何调用插件教程中提到的API呢，我私聊bot发送了一系列命令都没有得到回应，包括添加订阅等等
> 
> 您指的是`ELS_RSS`吗？
> 很抱歉由于我没有使用过这个插件，无法为您继续提供帮助。建议您
> 
> * 检查`ELS_RSS`的log，确认插件是否收到调用请求或有错误抛出

好的，非常感谢您的解答！

**Comment by wsmnwc** [comment]
> > > > > 请问您是如何进行验证的？使用HTTP的话请提供一下完整的调用参数（query或post body）
> > > > 
> > > > 
> > > > 感谢您的回复！我是使用了quickstart中的`http://127.0.0.1:5700/send_private_msg?user_id=[qq号]&message=[信息]`
> > > 
> > > 
> > > 你是不是把方括号也加上了...
> > 
> > 
> > 是这样的...抱歉占用您的时间了，重试了一下已经OK了，还想要请教一下，请问如何调用插件教程中提到的API呢，我私聊bot发送了一系列命令都没有得到回应，包括添加订阅等等
> 
> 您指的是`ELS_RSS`吗？
> 很抱歉由于我没有使用过这个插件，无法为您继续提供帮助。建议您
> 
> * 检查`ELS_RSS`的log，确认插件是否收到调用请求或有错误抛出
抱歉还有一处疑问想请教，请问在目前的情况下，想要bot回复信息或者实现本项目中提到的一些功能（如发送消息）应该如何进行操作？如果内容较为繁琐的话麻烦您告知我方法或者教程

**Comment by wsmnwc** [comment]
> > > > > 请问您是如何进行验证的？使用HTTP的话请提供一下完整的调用参数（query或post body）
> > > > 
> > > > 
> > > > 感谢您的回复！我是使用了quickstart中的`http://127.0.0.1:5700/send_private_msg?user_id=[qq号]&message=[信息]`
> > > 
> > > 
> > > 你是不是把方括号也加上了...
> > 
> > 
> > 是这样的...抱歉占用您的时间了，重试了一下已经OK了，还想要请教一下，请问如何调用插件教程中提到的API呢，我私聊bot发送了一系列命令都没有得到回应，包括添加订阅等等
> 
> 您指的是`ELS_RSS`吗？
> 很抱歉由于我没有使用过这个插件，无法为您继续提供帮助。建议您
> 
> * 检查`ELS_RSS`的log，确认插件是否收到调用请求或有错误抛出

抱歉还有一处疑问想请教，请问在目前的情况下，想要bot回复信息或者实现本项目中提到的一些功能（如发送消息）应该如何进行操作？如果内容较为繁琐的话麻烦您告知我方法或者教程

**Comment by fkx4-p** [comment]
Sending message with HTML with [MDUI](https://www.mdui.org/):

```
<div id="tab-uid" class="mdui-col-sm-6 mdui-col-md-4">
    <div class="mdui-textfield mdui-textfield-floating-label mdui-textfield-has-bottom">
        <label class="mdui-textfield-label">
            message
        </label>
        <input class="mdui-textfield-input" id="mess" type="text" required>
    </div>
</div>
<div id="tab-uid" class="mdui-col-sm-6 mdui-col-md-4">
    <div class="mdui-textfield mdui-textfield-floating-label mdui-textfield-has-bottom">
        <label class="mdui-textfield-label">
            id
        </label>
        <input class="mdui-textfield-input" id="uid" type="number" required>
    </div>
</div>
<div class="mdui-container" style="margin-bottom: 80px">
    <button class="mdui-btn mdui-btn-raised mdui-ripple mdui-color-theme-accent" id="input-but"
        onclick=javascrtpt:jump()>GO!</button>
    <script>
        function jump() {
            const ws = new WebSocket('removed');
            ws.onopen = function () {
                var tmp = {"action": "send_private_msg","params": {"user_id": `${document.getElementById('uid').value}`,"message": `${document.getElementById('mess').value}`},"echo": "123"};
                var tmp2 = JSON.stringify(tmp);
                console.log(tmp2);
                ws.send(tmp2);
                ws.close();
            };
        }
    </script>
</div>
```

Receiving message & getting friends list with js&HTML with MDUI

```
const ws = new WebSocket('removed')

ws.onopen = function () {
    var gettemp = { "action": "get_friend_list" };
    var tmp2 = JSON.stringify(gettemp);
    ws.send(tmp2);
}

ws.onmessage = e => {
    // console.log(e);
    var datas = JSON.parse(e.data);
    info.innerHTML += '<font color="black">' + e.data + '</font>' + '<br/>';
    info.innerHTML += '<font color="red">' + datas.sender.nickname + '(' + datas.sender.user_id + ')' + ':' + datas.raw_message + '</font>' + '<br/>';
}
```

**Comment by wsmnwc** [comment]
> Sending message with HTML with [MDUI](https://www.mdui.org/):
> 
> ```
> <div id="tab-uid" class="mdui-col-sm-6 mdui-col-md-4">
>     <div class="mdui-textfield mdui-textfield-floating-label mdui-textfield-has-bottom">
>         <label class="mdui-textfield-label">
>             message
>         </label>
>         <input class="mdui-textfield-input" id="mess" type="text" required>
>     </div>
> </div>
> <div id="tab-uid" class="mdui-col-sm-6 mdui-col-md-4">
>     <div class="mdui-textfield mdui-textfield-floating-label mdui-textfield-has-bottom">
>         <label class="mdui-textfield-label">
>             id
>         </label>
>         <input class="mdui-textfield-input" id="uid" type="number" required>
>     </div>
> </div>
> <div class="mdui-container" style="margin-bottom: 80px">
>     <button class="mdui-btn mdui-btn-raised mdui-ripple mdui-color-theme-accent" id="input-but"
>         onclick=javascrtpt:jump()>GO!</button>
>     <script>
>         function jump() {
>             const ws = new WebSocket('removed');
>             ws.onopen = function () {
>                 var tmp = {"action": "send_private_msg","params": {"user_id": `${document.getElementById('uid').value}`,"message": `${document.getElementById('mess').value}`},"echo": "123"};
>                 var tmp2 = JSON.stringify(tmp);
>                 console.log(tmp2);
>                 ws.send(tmp2);
>                 ws.close();
>             };
>         }
>     </script>
> </div>
> ```
> 
> Receiving message & getting friends list with js&HTML with MDUI
> 
> ```
> const ws = new WebSocket('removed')
> 
> ws.onopen = function () {
>     var gettemp = { "action": "get_friend_list" };
>     var tmp2 = JSON.stringify(gettemp);
>     ws.send(tmp2);
> }
> 
> ws.onmessage = e => {
>     // console.log(e);
>     var datas = JSON.parse(e.data);
>     info.innerHTML += '<font color="black">' + e.data + '</font>' + '<br/>';
>     info.innerHTML += '<font color="red">' + datas.sender.nickname + '(' + datas.sender.user_id + ')' + ':' + datas.raw_message + '</font>' + '<br/>';
> }
> ```

Thank you for your prompt reply， It is somewhat hard to understand...i want to know how to interactive with bot in the QQgroup，perhaps i should do something such as call the API？Sorry again for troubling you

**Comment by fkx4-p** [comment]
```
const ws = new WebSocket('removed');
ws.onopen = function () {
    var tmp = { "action": "send_private_msg", "params": { "user_id": bala, "message": bala }, "echo": "123" };
    var tmp2 = JSON.stringify(tmp);
    ws.send(tmp2);
    ws.close();
};
```

The 'tmp' part is changeable, according to [This](https://github.com/Mrs4s/go-cqhttp/blob/master/docs/cqhttp.md)

P.S.:You are welcome to send Chinese to me, writing in English on Github is just my stupid habit :P

**Comment by wsmnwc** [comment]
> ```
> const ws = new WebSocket('removed');
> ws.onopen = function () {
>     var tmp = { "action": "send_private_msg", "params": { "user_id": bala, "message": bala }, "echo": "123" };
>     var tmp2 = JSON.stringify(tmp);
>     ws.send(tmp2);
>     ws.close();
> };
> ```
> 
> The 'tmp' part is changeable, according to [This](https://github.com/Mrs4s/go-cqhttp/blob/master/docs/cqhttp.md)
> 
> P.S.:You are welcome to send Chinese to me, writing in English on Github is just my stupid habit :P

原来如此，这段如何实现差不多能够理解了，就是对html一无所知...非常感谢大佬指点，我再去研究一下
