### ISSUE TITLE
撤回限制

### ISSUE THREAD

**Issue by sam01101** [Mrs4s/go-cqhttp#435]
**环境信息**
go-cqhttp版本: v0.9.31-fix1 03c33409540e84a0fb19d336c1694d8ccd85aa0b
运行环境: Debian arm64
连接方式: 反向WS
协议: iPad

**bug内容**
撤回在一定时间有一定数量的限制, 是否如此?

**复现方法**
写一个Demo, 当有人发信息就撤回该信息(echo的相反)
发送到一定数量后没有撤回返回信息

等到突然一堆这样的封包发过来了, 你就可以继续撤回了
![image](https://user-images.githubusercontent.com/25792361/99678579-ec7d1680-2ab5-11eb-983f-a230e4ba9a07.png)

**Comment by sam01101** [comment]
已经测试, 在上面的封包接收前, 你最多可以大约撤回10条

**Comment by Mrs4s** [comment]
有空我这边也测试下，没处理过这么极端的场景.

**Comment by sam01101** [comment]
> 有空我这边也测试下，没处理过这么极端的场景.

大量撤回信息的问题, 我这边就挺严重的

如果可以我希望撤回能够返回一定的结果而不是nil

**Comment by sam01101** [comment]
已知目前返回OnlinePush将会是撤回后大约5秒收到

**Comment by Mrs4s** [comment]
撤回应该是这个包，有可能是解析错误

**Comment by sam01101** [comment]
> 撤回应该是这个包，有可能是解析错误

不，不可能
這個我和nonebot群友聊了下，他們說這個是返回結果的包

因為撤回已經早5秒，基本上瞬間發了

**Comment by sam01101** [comment]
> 撤回应该是这个包，有可能是解析错误

Online的包估计是返回撤回结果

**Comment by sam01101** [comment]
对了，顺便提点out topic的

交流群已经申请5次以上了，Github也填了
怎么没同意

**Comment by Mrs4s** [comment]
同意了

**Comment by sam01101** [comment]
https://github.com/mamoe/mirai/issues/425#issuecomment-656632237

发现有人提交过类似issue, 但最终以"调用方处理"结束.
但目前的issuse, 除了没法处理撤回失败外, 还没法接收撤回成功信息

**Comment by sam01101** [comment]
目測 https://github.com/Mrs4s/MiraiGo/commit/b5cce86b4d910428e2acf1dba0483ebacba576f7 已提供相关返回
至于进一步的更新就等PR或者作者了
