### ISSUE TITLE
BOT收不到自己成为龙王的notify

### ISSUE THREAD

**Issue by chenxuxin188** [Mrs4s/go-cqhttp#439]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.31-fix1
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
bot收不到自己成为龙王的notify。

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by chenxuxin188** [comment]
其他什么群聊之火的那些我没去注意_(:з」∠)_但是龙王我确认过，群里提示谁是龙王的时候，如果bot是龙王的话是没任何反应的。

**Comment by sam01101** [comment]
请问目前是否还有这个bug?

**Comment by sam01101** [comment]
现在应该修复了, 但会重复发送
如果造成困扰请手动去重
