### ISSUE TITLE
无法解析接收的语音文件

### ISSUE THREAD

**Issue by 4-bili** [Mrs4s/go-cqhttp#440]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.31-fix2
运行环境: Debian10_aarch64
连接方式: 反向WS

**bug内容**
无法打开/解析接收的语音文件。ffprobe和Mediainfo均无法获取/解析文件信息。

**复现方法**
尝试解析data/voices/下的语音文件

**Comment by wdvxdr1123** [comment]
tx的语言格式为silk，需要使用silk decoder解码

**Comment by 4-bili** [comment]
感谢指点！
经测试[此项目](https://github.com/kn007/silk-v3-decoder)可完成音频的编/解码。
