### ISSUE TITLE
配置文件都打开了webui为何访问还是404

### ISSUE THREAD

**Issue by rongi5** [Mrs4s/go-cqhttp#443]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.10
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
请在这里详细描述bug的内容

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by Mrs4s** [comment]
请提供更多信息
