### ISSUE TITLE
onebot标准实现建议

### ISSUE THREAD

**Issue by synodriver** [Mrs4s/go-cqhttp#444]
戳一戳的实现与[onebot标准](https://github.com/howmanybots/onebot/blob/master/v11/specs/message/segment.md)的不一致,可否实现一样的消息段类型？

**Comment by Mrs4s** [comment]
Onebot标准的戳一戳目前是指私聊的窗口抖动，并不是群聊双击头像.
目前还需要进一步完善Onebot标准.

**Comment by Shigma** [comment]
@synodriver 有关 poke 我暂时觉得 go-cqhttp 实现的比较好，onebot 那里稍后我会讨论一下要不要改掉 spec（

**Comment by synodriver** [comment]
目前看来有两种poke,一种是私聊的**魔改**屏幕抖动,还有种就是双击头像那个,两个都是poke的话cq码怎么写呢？*(*

**Comment by sam01101** [comment]
> 目前看来有两种poke,一种是私聊的**魔改**屏幕抖动,还有种就是双击头像那个,两个都是poke的话cq码怎么写呢？_(_

用群聊类型(

**Comment by TheresaQWQ** [comment]
> 目前看来有两种poke,一种是私聊的**魔改**屏幕抖动,还有种就是双击头像那个,两个都是poke的话cq码怎么写呢？*(*
> 

加个type（（（
