### ISSUE TITLE
新版本疑似内存泄露

### ISSUE THREAD

**Issue by ly1102** [Mrs4s/go-cqhttp#445]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.31-fix2
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
内存泄露，使用大概半小时后，服务器内存直接爆掉了。
但是另一个没多少消息的机器人就没事，内存占用也比较少

**复现方法**
使用nonebot，并且最新版go-cq，使用大概不到一小时，nonebot收不到消息了，服务器内存爆了

**Comment by ly1102** [comment]
我试了下29版本，又切回来，结果被封了。。。

**Comment by Mrs4s** [comment]
需要更多信息以确认问题

**Comment by sam01101** [comment]
我运行了几天，并没有遇到你说的内存泄漏

请检查清楚是不是哪里有累积数据
