### ISSUE TITLE
新创建的群聊获取不到的问题

### ISSUE THREAD

**Issue by dxasqw** [Mrs4s/go-cqhttp#448]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.31-fix2
运行环境: windows_amd64
连接方式: http

**bug内容**
新创建的群聊获取不到,重启后可以获取到

**复现方法**
新创建的群聊获取不到,重启后可以获取到

**Comment by Mrs4s** [comment]
请问是BOT本人的号在其他客户端创建的群?

**Comment by dxasqw** [comment]
其他QQ创建完马上就把BOT拉进群了，群里有聊天信息，但是获取群列表没有这个新群

**Comment by dxasqw** [comment]
> [机器人]？

具体是 非BOT QQ号创建群聊的时候把机器人拉进群了，然后马上修改了群聊名称。
再次获取群列表的时候 群名称还是之前创建的群名称

**Comment by dxasqw** [comment]
> 请问是BOT本人的号在其他客户端创建的群?

具体是 非BOT QQ号创建群聊的时候把机器人拉进群了，然后马上修改了群聊名称。
再次获取群列表的时候 群名称还是之前创建的群名称

**Comment by Mrs4s** [comment]
调用 `get_group_list` 和 `get_group_info` 时带上 `no_cache` flag即可刷新缓存
