### ISSUE TITLE
付费入群收不到提示

### ISSUE THREAD

**Issue by 502647092** [Mrs4s/go-cqhttp#453]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.31
运行环境: linux_amd64
连接方式: 正向WS

**bug内容**
付费群 成员加入没有提示
成员退出有提示
![image](https://user-images.githubusercontent.com/10203793/100540721-f3f0ac80-3279-11eb-857d-324b65b9dc29.png)
![image](https://user-images.githubusercontent.com/10203793/100540729-0a970380-327a-11eb-8a69-69ac6d31137c.png)

**复现方法**

**Comment by sam01101** [comment]
https://github.com/mamoe/mirai/issues/641

**Comment by sam01101** [comment]
btw我们没付费群/小号没绑定实名, 没法复现

**Comment by Mrs4s** [comment]
https://github.com/Mrs4s/go-cqhttp/actions/runs/389917924 请尝试这个版本, 已经修复

**Comment by 502647092** [comment]
嗯 测试过了 可以收到消息了
