### ISSUE TITLE
bot 发送消息的id与 回复消息中获取的replyid 出现不匹配

### ISSUE THREAD

**Issue by jianmj** [Mrs4s/go-cqhttp#454]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.31-fix1
运行环境: centos 7
连接方式: WS

**bug内容**
使用bot 发送一条消息 ，并记录这个消息id，使用qq回复 这条消息时，reply CQ码里读取的id与 发送时的id 偶尔存在 不匹配的情况 
log 日志里显示 发送记录
![image](https://user-images.githubusercontent.com/19400782/100564115-07902780-32fb-11eb-9db2-9a4adc3ebddb.png)
读取到回复消息内容
![image](https://user-images.githubusercontent.com/19400782/100566000-d2d29f00-32ff-11eb-9e5e-68138c17d5f1.png)

相同消息内容的偶发性复现
![image](https://user-images.githubusercontent.com/19400782/100566080-0b727880-3300-11eb-8e85-d90e5ea33d4d.png)

**复现方法**
使用 send_group_msg 方法发送消息 ，消息内容
WsMan更新了作品 1130\nhttps://pixiv.net/i/86000405\n[CQ:image,file=file:////qq/file/c2361943c56b89c7e9723a5a64f8c2f6.jpg]

**Comment by Mrs4s** [comment]
关掉强制分片试试？

**Comment by jianmj** [comment]
感谢回复  ，force_fragmented:false ，关闭分片后，模拟测试多次均未出现此问题了。

**Comment by jianmj** [comment]
关闭强制分片后 发送的消息 经常出现 被风控的情况 ，在分片情况下 是否有办法 通过 CQ码中的 reply id 获取到原始消息 。

**Comment by Mrs4s** [comment]
会尝试处理这个问题

**Comment by sam01101** [comment]
#261

**Comment by jianmj** [comment]
![image](https://user-images.githubusercontent.com/19400782/109993427-3deca100-7d47-11eb-9408-a9cf19dff6f5.png)
已升级到 go-cqhttp-v0.9.40-fix3 ，问题还是会复现

**Comment by sam01101** [comment]
> ![image](https://user-images.githubusercontent.com/19400782/109993427-3deca100-7d47-11eb-9408-a9cf19dff6f5.png)
> 已升级到 go-cqhttp-v0.9.40-fix3 ，问题还是会复现

#261

**Comment by jianmj** [comment]
> > ![image](https://user-images.githubusercontent.com/19400782/109993427-3deca100-7d47-11eb-9408-a9cf19dff6f5.png)
> > 已升级到 go-cqhttp-v0.9.40-fix3 ，问题还是会复现
> 
> #261

明白了，谢谢

**Comment by liliangshan** [comment]
v1.0.0-beta3，没有开分片照样ID不对，和上面的情况一样

**Comment by sam01101** [comment]
大家别回报了，有啥问题去 #261 
这里已经关闭了，请不要再回复了
261是开着的，说明问题还没解决
要等到OB v12才可以解决
