### ISSUE TITLE
[feature] 更好的Debug追踪支持

### ISSUE THREAD

**Issue by Mrs4s** [Mrs4s/go-cqhttp#459]
- [x] 为所有的 `error` `panic` 加上堆栈追踪.
- [x] 在debug模式下开启`pprof server`, 方便排除内存泄露.

**Comment by ly1102** [comment]
资瓷，我今天下午又内存泄露了，想登上去看看报错信息啥的，结果SSH都进去不了，只有直接重启服务器了，然后更新了最新版的gocq
