### ISSUE TITLE
[bug] CQ回复和at卡片不能使用

### ISSUE THREAD

**Issue by Cai-Tang** [Mrs4s/go-cqhttp#46]
在nonebot使用CQ:reply卡片得到:
        转换CQ码到MiraiGo Element时出现错误: unsupported cq code: reply 将忽略本段CQ码. 
使用at卡片[CQ:at,qq=123456]在qq群显示@123456(而不是at昵称)
使用[CQ:at,qq={123456}]或[CQ:at,123456]偶尔可以正常发送(经常发送不出来)
通过Array上报亦然
go-cqhttp 版本v0.9.13
OS: Arch Linux ARM armv7l 
Kernel: 5.4.51-1-ARCH

**Comment by Mrs4s** [comment]
`reply` 只支持发送到群, 并且必须开启内嵌数据库.
at 的问题已经解决了, 请等待 Release 或者去 Actions 拉测试版

**Comment by alexwocall** [comment]
好的, 感谢.
