### ISSUE TITLE
IOS无法听取gocqhttp发送的语音 安卓和PCQQ都没有问题

### ISSUE THREAD

**Issue by Monodesu** [Mrs4s/go-cqhttp#460]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.33
运行环境: windows_amd64
连接方式: 正向WS

**bug内容**
ios可以接收到语音 但是无法播放
其它端没有问题

**复现方法**
调用gocqhttp发送一个语音文件即可

**Comment by Mrs4s** [comment]
#390
