### ISSUE TITLE
戳一戳有较大概率发送无效

### ISSUE THREAD

**Issue by railannad** [Mrs4s/go-cqhttp#464]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.33
运行环境: CentOS8
连接方式: 反向WS

**bug内容**
go的控制台显示已发送，但实际上有较大概率收不到  
发送方式是在nonebot2下使用 `func.finish(message=[CQ:poke,qq=xxx])` 
![image](https://user-images.githubusercontent.com/36919867/101055589-0003a380-35c5-11eb-83f9-83f29980d8d1.png)
![image](https://user-images.githubusercontent.com/36919867/101055623-0b56cf00-35c5-11eb-810a-5e2b20069f4a.png)

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by Mrs4s** [comment]
我记得戳一戳有频率限制...

**Comment by railannad** [comment]
> 我记得戳一戳有频率限制...

bot作为被动回戳的一方，在只有一个用户交互的情况下，只要能收到提醒就不会被限制吧，因为即使有限制也是用户(我)先被限制而不是bot。 

现在是0:29，我刚戳了几下还是没反应

**Comment by Mrs4s** [comment]
我下个版本加上戳一戳的返回解析, 可能会有错误信息

**Comment by sam01101** [comment]
已修复, 并生成了新的bug
