### ISSUE TITLE
反复提示输入验证码

### ISSUE THREAD

**Issue by yuxiaolejs** [Mrs4s/go-cqhttp#465]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.33
运行环境: windows_amd64
连接方式: HTTP API

**bug内容**
请在这里详细描述bug的内容
在输入验证码按enter之后，反复要求重新输入验证码
本人确定验证码输入正确，换用0.9.31版本不存在该问题
已在三台windows主机上进行测试，等linux服务器测试完后将继续跟进
Log如下
[2020-12-04.log](https://github.com/Mrs4s/go-cqhttp/files/5640496/2020-12-04.log)

**复现方法**
请在这里分步骤的描述如何复现这个bug
选择一个要求输入验证码的协议并进行连接

**Comment by Mrs4s** [comment]
请尝试使用其他的设备信息

**Comment by Mrs4s** [comment]
或打开设备锁

**Comment by yuxiaolejs** [comment]
补充：出现问题时设备锁是开的，设备信息也更新过了
解决方案：首先检查了log，发现有未完成的验证，打开链接扫码，之后多次更换设备后解决
差不多一共换了20多次设备，不停的删除device.json，反复尝试，最后同一个设备试了两次然后就解决了
非常感谢作者大大！！
