### ISSUE TITLE
存在漏消息

### ISSUE THREAD

**Issue by MuJint** [Mrs4s/go-cqhttp#466]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.10
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
群聊存在漏消息，随机挑选几个幸运儿漏消息

**复现方法**
私聊发截图

**Comment by fkx4-p** [comment]
1.Please use a newer version of go-cqhttp
2.Please make sure that you are not banned(in any forms) by Tencent
3.Please note that the loss of some messages is normal and unavoidable
4.Please comment again if the above answers are not useful
