### ISSUE TITLE
配置文件问题

### ISSUE THREAD

**Issue by zhanglianxin** [Mrs4s/go-cqhttp#469]
容器启动。版本：v0.9.33。

当配置文件不存在时，读取不到某些配置项会报错。

![](https://p.sda1.dev/0/cf728c674918e47b77ae3bca6e99e366/QQ20201206-174302.png)

另外，当实例比较多时，逐个添加配置文件比较麻烦。

建议：环境变量和配置文件可共同作用，但环境变量会覆盖配置文件。

**Comment by Mrs4s** [comment]
请尝试最新版本

**Comment by zhanglianxin** [comment]
> 请尝试最新版本

你好，未解决。

**Comment by sam01101** [comment]
请尝试最新版本
