### ISSUE TITLE
API:get_msg获取闪照时,"message"字段为空

### ISSUE THREAD

**Issue by railannad** [Mrs4s/go-cqhttp#470]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.33-fix1
运行环境: CentOS 8
连接方式: 反向WS

**bug内容**
当消息内容为闪照时，get_msg获取消息内容返回结果中'message'字段为空

**复现方法**
自己写的插件，当监听到有人撤回消息时，获取消息ID，再根据消息ID获取消息内容以实现"防撤回"功能，但是当消息内容为闪照时，"message"字段为空

我电脑上装了防撤回插件加上是用手机撤回的，所以看不到撤回提示
![image](https://user-images.githubusercontent.com/36919867/101319088-55c59d80-389c-11eb-9718-6f91b5c447b2.png)

补个图： 如果消息内容为图片时，会直接显示出来

![image](https://user-images.githubusercontent.com/36919867/101320742-37ad6c80-389f-11eb-92b2-fa0ec2f74930.png)

**Comment by wdvxdr1123** [comment]
请尝试只发送message中的内容

**Comment by railannad** [comment]
> 请尝试只发送message中的内容

![image](https://user-images.githubusercontent.com/36919867/101321088-c15d3a00-389f-11eb-958f-500724c77aa0.png)
我是看到闪照发送失败才发送完整json调试的
思路是抓取到cq码之后把"type=flash,"删掉。  没想到message为空

**Comment by railannad** [comment]
> 请尝试只发送message中的内容

![image](https://user-images.githubusercontent.com/36919867/101321218-fec1c780-389f-11eb-88a0-2a722ebf0fe2.png)
我是看到闪照发送失败才改代码使其发送完整响应来调试的，只发送message字段的话会发送失败：消息为空

**Comment by sam01101** [comment]
已修复
