### ISSUE TITLE
私聊撤回信息出现错误, 但信息正常被撤回

### ISSUE THREAD

**Issue by sam01101** [Mrs4s/go-cqhttp#471]
**环境信息**
go-cqhttp版本: v0.9.10
运行环境: any
连接方式: 反向WS

**bug内容**
![image](https://user-images.githubusercontent.com/25792361/101446284-f62fc680-395d-11eb-929a-3a6380fcbfc3.png)

**复现方法**
私聊撤回机器人自己信息

**Comment by Mrs4s** [comment]
已修复
