### ISSUE TITLE
安卓端 GIF 无法正常显示

### ISSUE THREAD

**Issue by SK-415** [Mrs4s/go-cqhttp#474]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.33-fix1
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
请在这里详细描述bug的内容

可能与 #380 与 #139 表现相同。

安卓端收到由 go-cqhttp 发送的 GIF 无法正常播放，且通过图片编辑器打开发现只有第一帧的图片。此时如果使用其他客户端再向该安卓端发送同一张 GIF，会被判定为同一张图片，直接从缓存调用之前那张无法正确播放的图片。

此情况只存在于安卓端，在 电脑TIM 与 iphone端 查看同一张图均显示正常。

以下分别我测试中使用的一张 GIF 与 安卓端收到后导出的问题图片。

发送的图片：
![test](https://user-images.githubusercontent.com/36433929/101692317-07d2b480-3aab-11eb-9641-5a1788549c36.gif)

安卓端收到的图片：
![receive](https://user-images.githubusercontent.com/36433929/101692875-ca225b80-3aab-11eb-8b3a-09a4bde38ae5.gif)

**复现方法**
请在这里分步骤的描述如何复现这个bug

使用 go-cqhttp 向一个安卓客户端发送一张该客户端此前从未接收过的 GIF，收到后将无法正常播放。

**Comment by zangxx66** [comment]
没有问题，尝试最新版本go-cqhttp

**Comment by Mrs4s** [comment]
无法复现，需要提供更多信息
