### ISSUE TITLE
无法登录，错误192

### ISSUE THREAD

**Issue by Cyame** [Mrs4s/go-cqhttp#475]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.34
运行环境: Linux_Ubuntu16.04_amd64
连接方式: 反向WS

**bug内容**

0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[2020-12-10 10:16:55] [DEBUG]: Protocol -> decode pkt wtlogin.login error: unknown login response: 192
github.com/Mrs4s/MiraiGo/client.decodeLoginResponse
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201209180326-c07a8a9c8a83/client/decoders.go:169
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201209180326-c07a8a9c8a83/client/client.go:1015
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
[2020-12-10 10:16:55] [FATAL]: 遇到错误: unknown login response: 192

**复现方法**
一开始是OK的，只是在此服务器上出现登录错误，不清楚原因...

**Comment by Mrs4s** [comment]
请打开debug模式登录并上传输出

**Comment by Cyame** [comment]
[2020-12-10.log](https://github.com/Mrs4s/go-cqhttp/files/5670329/2020-12-10.log)
我这边只能找到今天重启时候错误的log，事实上它似乎是8日突然中断的，中断的部分我在日志里没有找到...

**Comment by Cyame** [comment]
![QQ图片20201210125544](https://user-images.githubusercontent.com/32809305/101723495-5bfb8a00-3ae7-11eb-9cdb-e8a1353fd436.jpg)
中断后的部分只留下这个截图 *第一行即为12-08.log的最后一行*

**Comment by Mrs4s** [comment]
好的 我排查下

**Comment by Cyame** [comment]
当然似乎不是非常普遍的问题（或许服务器端口这边配置有问题...？）但是WS的服务是放在另外的服务器上的，这个过程中需要保持什么端口开放吗？

*只有港服倒了 在其他地区服务器上即便没更新似乎也安然无恙*
