### ISSUE TITLE
可不可以增加一个代理ip连接tx服务器的功能

### ISSUE THREAD

**Issue by wmsafe** [Mrs4s/go-cqhttp#476]
环境信息
go-cqhttp版本：v0.9.34
运行环境：Windows_amd64
连接方式：HTTPAPI

如题....
因为一个IP尝试登录次数过多，跳验证码输入验证完成后会一直跳验证码最后程序会直接退出，提示上网环境网络异常。
我尝试过所有设备版本，并且确保QQ已经开启设备锁 而且验证码全部都输入正确。虚拟设备信息也删了很多次，还是无法解决，可能就是tx将我的电脑IP给封掉了，尝试太多次登录。

**Comment by Ink-33** [comment]
windows下请尝试使用`Proxifier`对go-cqhttp进行代理

**Comment by Mrs4s** [comment]
短期内不会增加代理支持
