### ISSUE TITLE
cardimage参数建议

### ISSUE THREAD

**Issue by foxwhite25** [Mrs4s/go-cqhttp#478]
把makeShowPic(cardimage)中的brief参数(&#91;分享&#93;我看到一张很赞的图片，分享给你，快来看！)改变成可以使用cq码来改变。
https://github.com/Mrs4s/go-cqhttp/blob/9a4b28455963ed6eb1f3021db453642af6dba419/coolq/cqcode.go#L889-L928

**Comment by fkx4-p** [comment]
1.This is not an issue, so use a pull request instead.

**Comment by foxwhite25** [comment]
1.If I know how the structure of this piece of code works I will not sent a issue
2.Who are you mr. myenglishissogood?

> 1.This is not an issue, so use a pull request instead.
