### ISSUE TITLE
群消息重复发送，显示发送失败：可能被风控，尝试分片发送

### ISSUE THREAD

**Issue by xxyy3130** [Mrs4s/go-cqhttp#479]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.34
运行环境: windows_amd64
连接方式: 正向WS

**bug内容**
群消息成功发送了却显示 发送失败：账号可能被风控. 将尝试分片发送......
然后就发了两条出去

**复现方法**
运行一段时间后偶尔会出现

![image](https://user-images.githubusercontent.com/61443746/101762741-c547c100-3b18-11eb-97ad-2ab218e083cb.png)

**Comment by foxwhite25** [comment]
可以把config里的强制分片打开

**Comment by xxyy3130** [comment]
> 可以把config里的强制分片打开

但是强制分片有时会出现奇遇的解析问题

**Comment by foxwhite25** [comment]
#454 在做了在做了

**Comment by chenxuuu** [comment]
强制分片也会出现这种情况，奇怪了
而且只是消息发不出去，但是禁言之类的管理操作都正常

**Comment by zanjie1999** [comment]
我从mirai的Java版本换了过来，只要在线时间一长（大约半小时）群消息均发不出，提示被风控，重启恢复，之前用mirai的时候没有遇到过这种问题  
有空的话能否检查一下是不是代码问题？  
或者能不能做一个发不出去就自动重新登录的功能？

**Comment by sam01101** [comment]
> 我从mirai的Java版本换了过来，只要在线时间一长（大约半小时）群消息均发不出，提示被风控，重启恢复，之前用mirai的时候没有遇到过这种问题
> 有空的话能否检查一下是不是代码问题？
> 或者能不能做一个发不出去就自动重新登录的功能？

请回答以下问题:
1. 请问 `device.json` 是否在使用原本`mirai`的?
2. 如果不是, 请问上线了多久(从迁移到go-cqhttp`上线的一刻起

**Comment by zanjie1999** [comment]
> > 我从mirai的Java版本换了过来，只要在线时间一长（大约半小时）群消息均发不出，提示被风控，重启恢复，之前用mirai的时候没有遇到过这种问题
> > 有空的话能否检查一下是不是代码问题？
> > 或者能不能做一个发不出去就自动重新登录的功能？
> 
> 请回答以下问题:
> 
> 1. 请问 `device.json` 是否在使用原本`mirai`的?
> 2. 如果不是, 请问上线了多久(从迁移到go-cqhttp`上线的一刻起

1. 不是，因为不兼容，放过来直接报错
2. 大约半小时就开始了，至今未结束，服务器是固定ip，换回mirai的话一切正常

**Comment by Mrs4s** [comment]
> > > 我从mirai的Java版本换了过来，只要在线时间一长（大约半小时）群消息均发不出，提示被风控，重启恢复，之前用mirai的时候没有遇到过这种问题
> > > 有空的话能否检查一下是不是代码问题？
> > > 或者能不能做一个发不出去就自动重新登录的功能？
> > 
> > 
> > 请回答以下问题:
> > 
> > 1. 请问 `device.json` 是否在使用原本`mirai`的?
> > 2. 如果不是, 请问上线了多久(从迁移到go-cqhttp`上线的一刻起
> 
> 1. 不是，因为不兼容，放过来直接报错
> 2. 大约半小时就开始了，至今未结束，服务器是固定ip，换回mirai的话一切正常

更换平台如果不转移设备文件的话会被暂时风控
需要挂一周左右才会解除

**Comment by zanjie1999** [comment]
尝试转换了一下`mirai`的`device.json`
里面是类似于这样的内容：
`{"display":[77,73,82,65,73,46,52,57,48,56,57,55,46,48,48,49],...`

使用浏览器的f12的console运行下面的转换代码，复制最后的结果就是`go-cqhttp`能够兼容的`device.json`
```
a=将mirai的json贴在这里
for (i  in a){
    if (typeof(a[i])!='string'){
        a[i]=String.fromCharCode(...a[i])
    }
}
console.log(a)

**Comment by sam01101** [comment]
可以写个js出来自动转换
如果要兼容的话可以开issue
