### ISSUE TITLE
Is this project allowed for commercial use?

### ISSUE THREAD

**Issue by purerosefallen** [Mrs4s/go-cqhttp#48]
We want to make QQ bots for a text RPG game, using this project as the bot backend, making profits. Now I wonder if this project is allowed for commercial use. If not for free, how would I be able to purchase a license?
In addition, I noticed that you changed the license to AGPLv3 from a specific commit. May I use the code before that commit as MIT?

**Comment by remiliacn** [comment]
[License](https://github.com/Mrs4s/go-cqhttp/blob/master/LICENSE)

**Comment by purerosefallen** [comment]
I saw the above license, but it started from a recent commit.
May I use the code **before** that commit as MIT, the old license?

**Comment by takayama-lily** [comment]
可以吧，但是要开源。

**Comment by Shigma** [comment]
> I saw the above license, but it started from a recent commit.
> May I use the code **before** that commit as MIT, the old license?

用哪个版本的代码，就对应哪个版本的协议。

**Comment by remiliacn** [comment]
> When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.

[License (old)](https://github.com/Mrs4s/go-cqhttp/blob/feb4ff4ac9a759e69b0b023cd5caf6d20f877616/LICENSE)

**Comment by Mrs4s** [comment]
在不修改go-cqhttp代码和标注来源的情况下，允许基于go-cqhttp协议的bot商业化使用.
