### ISSUE TITLE
go-cqhttp登录几秒后突然退出

### ISSUE THREAD

**Issue by raindown200709** [Mrs4s/go-cqhttp#485]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.10
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
Windows10登录go-cqhttp后，几秒不到就被退出了，只登录了一个QQ号，没有占用端口，而到服务器登录没有问题

**Comment by Ink-33** [comment]
麻烦使用控制台启动，并上传一下log，以便确定问题

**Comment by fkx4-p** [comment]
1.How did use reverseWebSocket without even starting the server?
2.Use a command prompt to start the program and record the logs by adding ">example.log" and upload the file or copying the logs or we won't be able to find the problem.

**Comment by vanish666** [comment]
[ERROR]: listen tcp 0.0.0.0:5700: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by vanish666** [comment]
三个错误、警告，运行几秒退出
[ERROR]:Protocol -> unknown group msg: 0
[WARNING]: 事件过滤器启动失败: open filter.json: The system cannot find the file specified.
[ERROR]: listen tcp 0.0.0.0:5700: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by Ink-33** [comment]
- 1，参考docs/EventFilter.md配置事件过滤器
- 2，看起来是权限问题或者5700端口被占用，使用`netstat -ano`确认一下5700端口是否被占用

**Comment by Mrs4s** [comment]
> [ERROR]: listen tcp 0.0.0.0:5700: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

请尝试以管理员身份/root 账户运行, 可能是由于安全政策导致无法监听低位端口
