### ISSUE TITLE
采用release发布 而不是pre-release 不然API没法取到最后一个release版本

### ISSUE THREAD

**Issue by 502647092** [Mrs4s/go-cqhttp#488]
如标题

**Comment by Mrs4s** [comment]
什么api

**Comment by 502647092** [comment]
> 什么api

https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#get-the-latest-release

**Comment by 502647092** [comment]
https://api.github.com/repos/Mrs4s/go-cqhttp/releases/latest
此地址无法取到pre-release数据

**Comment by yanyongyu** [comment]
你可以用 `List Releases API` 替代

https://api.github.com/repos/Mrs4s/go-cqhttp/releases?per_page=1&page=0

**Comment by Mrs4s** [comment]
https://github.com/Mrs4s/go-cqhttp/blob/d50442b85f55649060406255d88f961fb32cf109/main.go#L373-L387

请参考此处代码

**Comment by 502647092** [comment]
好的 感谢回复
