### ISSUE TITLE
【功能建议】希望新增/_get_group_notice和/_send_group_notice

### ISSUE THREAD

**Issue by zangxx66** [Mrs4s/go-cqhttp#493]
看了原cqhttp的接口，是可以获取和发送群公告的，希望这个功能能够添加上去

**Comment by wdvxdr1123** [comment]
目前 _send_group_notice Api已经实现， /_get_group_notice还未实现

**Comment by lindongbin** [comment]
希望能和mirai一样会支持群公告的相关操作
https://github.com/mamoe/mirai/pull/1141
