### ISSUE TITLE
回复消息报告的ID不正确

### ISSUE THREAD

**Issue by U2FsdGVkX1** [Mrs4s/go-cqhttp#494]
**环境信息**
go-cqhttp版本: go-cqhttp-v0.9.34
运行环境: linux-amd64
连接方式: 正向WS

**bug内容**
之前反馈过这个问题（https://github.com/Mrs4s/go-cqhttp/issues/319）
某些消息发送时记录的消息ID，与回复时得到的消息ID不一致
![image](https://user-images.githubusercontent.com/11484206/102029341-1988c480-3de9-11eb-981a-b14225d460d4.png)

当时说是数据库问题，不过虽然现在更换数据库了还是如此（并且已经删除过data目录，还是无效）
另附数据库文件：https://1drv.ms/u/s!An0DK5Y-VeCrwDLIpQL771MwNA60?e=z4Rt0X

**复现方法**
随缘复现，有一些消息就会出现这种情况

**Comment by Mrs4s** [comment]
#454
