### ISSUE TITLE
API: get_msg获取语音消息时, 返回的message中file/url内容为空

### ISSUE THREAD

**Issue by jasmineamber** [Mrs4s/go-cqhttp#496]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.34-fix1
运行环境: ubuntu 4.15.0-20-generic
连接方式: 反向WS

**bug内容**
get_msg获取语音消息内容, 返回的message中file/url内容为空

**复现方法**
用手机App在群组中发送一条语音消息，根据日志中获得message_id调用get_msg接口, 返回值如下
{
    "data": {
        "group": true,
        "group_id": 12334456,
        "message": "[CQ:record,file=,url=]",
        "message_id": -1643156286,
        "real_id": 4300,
        "sender": {
            "nickname": "X",
            "user_id": 1234567
        },
        "time": 1608011911
    },
    "retcode": 0,
    "status": "ok"
}

**Comment by cppakko** [comment]
一样的问题
环境信息
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.34-fix1
运行环境: ubuntu 4.15.0-124-generic
连接方式: http

bug内容
get_msg获取消息内容, 返回的message中file/url内容为空

复现方法
发送图片 并回复该图片消息 对获取的message_id调用get_msg接口
{
    "data": {
        "group": true,
        "group_id": 1041084231,
        "message": "[CQ:image,file=,url=]",
        "message_id": 577125409,
        "real_id": 1654,
        "sender": {
            "nickname": "xxxxx",
            "user_id": 123456789
        },
        "time": 1608217389
    },
    "retcode": 0,
    "status": "ok"
}

**Comment by Mrs4s** [comment]
由于语音消息的下载链接有时效性，很抱歉这个问题暂时无法解决, 请使用下个版本会添加的 `message_raw` 字段从本地读取语音数据.
