### ISSUE TITLE
at全体成员失败后不会产生报错

### ISSUE THREAD

**Issue by SK-415** [Mrs4s/go-cqhttp#497]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: 0.9.34-fix1
运行环境: Windows10 amd64
连接方式: 反向ws
使用协议: Android Phone

**bug内容**
请在这里详细描述bug的内容

群内没有管理员权限或者@全体成员次数已经耗光的情况下，包含 [CQ:at,qq=all] 的消息不会被发出，控制台也不会产生报错。

希望在@全体失败的时候可以自动转换为文本或者产生报错方便 bot 可以处理，现在 bot 无法获知@全体是否失败。如果可以添加查询剩余@全体次数的 api 就更好了。

**复现方法**
请在这里分步骤的描述如何复现这个bug

如上

**Comment by Mrs4s** [comment]
我看怎么处理比较好

**Comment by Mrs4s** [comment]
已加入 API `get_group_at_all_remain` 用于获取@全体剩余次数, 请等待Release

**Comment by SK-415** [comment]
好的，感谢
