### ISSUE TITLE
因data目录下，多媒体文件夹名称改变，导致老的插件上报的CQ码无法正常运作

### ISSUE THREAD

**Issue by LollipopGeneral** [Mrs4s/go-cqhttp#499]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: 
运行环境: 
连接方式: 
使用协议: 

**bug内容**
请在这里详细描述bug的内容
data目录下，三个多媒体文件夹名称改变：
image->images
video->videos
record->voices
导致原生CQ码无法正常运作。
文件放在原目录相对路径下，需要复制到新文件夹下才行
[CQ:image,file=test.jpg]
插件会将test.jpg保存在image下，而test.jpg不在images中，从而导致图片不能正常发送

希望可以兼容老的目录，或者改回老的目录

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by Mrs4s** [comment]
感谢提出, 下个版本会加上兼容性处理的

**Comment by Mrs4s** [comment]
已处理
