### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by masnn** [Mrs4s/go-cqhttp#5]
rt.

也许是[CQ:file]之类（？

**Comment by Mrs4s** [comment]
目前只能尝试有限支持群文件上传事件, 群文件管理短期内应该不会做

**Comment by Mrs4s** [comment]
已兼容 `group_upload` 事件, 具体可查看 https://cqhttp.cc/docs/4.15/#/Post?id=%E7%BE%A4%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0

**Comment by masnn** [comment]
(计划在此issue持续跟进feature request.

- [ ] set_group_leave
- [ ] send_like

**Comment by Mrs4s** [comment]
> (计划在此issue持续跟进feature request.
> 
> * [ ]  set_group_leave
> * [ ]  send_like

send_like 应该不会做，毕竟是mirai衍生项目。
set_group_leave还在测试

**Comment by Mrs4s** [comment]
已支持 `/set_group_leave`

**Comment by masnn** [comment]
是否考虑支持同时登录多个账号
