### ISSUE TITLE
Protocol -> parse incoming packer error: return code unsuccessful: -10001 能否主动获知？

### ISSUE THREAD

**Issue by leoguan88** [Mrs4s/go-cqhttp#500]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: 
v0.9.24-fix2 
运行环境: 
windows Svr2016
连接方式: 
post
使用协议: 
http

**bug内容**
请在这里详细描述bug的内容

Protocol -> parse incoming packer error: return code unsuccessful: -10001
这个似乎是BOT被其他客户的挤掉了或者会话过期了，但有办法主动获知吗？
经常是掉线好几个小时，才发现，就漏了好多消息了！

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by Mrs4s** [comment]
请更新版本

**Comment by leoguan88** [comment]
更新版本后，就不会掉线？还是有什么办法掉线了，就可以主动获知？
