### ISSUE TITLE
get_msg可能无法获取到正确信息

### ISSUE THREAD

**Issue by ishkong** [Mrs4s/go-cqhttp#503]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本:  v0.9.34-fix1
运行环境:  Linux x64 centos7
连接方式: 反向WS
使用协议: Ipad

**bug内容**
get_msg获取到的含有CQ码的内容可能为空

**复现方法**
概率问题

![成功获取](https://i.loli.net/2020/12/17/6QGwezl5xft1FUp.png)
![未成功获取](https://i.loli.net/2020/12/17/2QoDCkaRU8EJvs9.png)

类似问题
#496

**Comment by railannad** [comment]
借个楼，大佬 #470 也康一下

**Comment by Mrs4s** [comment]
已修复
