### ISSUE TITLE
撤回成功却返回失败

### ISSUE THREAD

**Issue by 305148442** [Mrs4s/go-cqhttp#505]
go-cqhttp版本: v0.9.34-fix1
运行环境: windows64位
连接方式: 反向WS
使用协议: 安卓手机

**复现方法**
使用delete_msg

[
![图片](https://user-images.githubusercontent.com/72788720/102585666-c180f380-4143-11eb-8fab-02d46caf9c14.png)
](url)

**Comment by 305148442** [comment]
[](url
![图片](https://user-images.githubusercontent.com/72788720/102585816-00af4480-4144-11eb-979f-2e0cdd75cb8b.png)
)

**Comment by Mrs4s** [comment]
#491
