### ISSUE TITLE
ws reverse 发送图片失败，http 协议没问题

### ISSUE THREAD

**Issue by theprimone** [Mrs4s/go-cqhttp#507]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: go-cqhttp-v0.9.35-fix1-windows-amd64
运行环境: windows 10
连接方式: ws reverse
使用协议: websocket

**bug内容**
同样的图片消息在 websocket 和 http 协议中结果不同

**复现方法**
通过 nonebot@2 发送消息如下：
```
// 图片原始链接：https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=1071961525,4038809800&fm=26&gp=0.jpg
[CQ:image,file=https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=1071961525&#44;4038809800&amp;fm=26&amp;gp=0.jpg]
```
控制台报错：
![image](https://user-images.githubusercontent.com/18096089/102710341-9259b600-42ec-11eb-8a5d-26932f07d24d.png)

通过 http 直接发送同样的消息，一切正常：
![image](https://user-images.githubusercontent.com/18096089/102710411-0a27e080-42ed-11eb-83d1-1006a44b4772.png)

**Comment by molehzy** [comment]
把 逗号 和 & 进行URL编码试试

**Comment by theprimone** [comment]
> 把 逗号 和 & 进行URL编码试试

我把图片链接已经转义了，你的意思是把整个CQ码都转义吗？

**Comment by theprimone** [comment]
> 把 逗号 和 & 进行URL编码试试

试过了，把逗号也转义还是一样的问题，不过还特地试了没有特殊符号的图片地址就没问题了 \_(:3J∠)\_

**Comment by theprimone** [comment]
群里大佬给了指导意见，使用数组格式发送没问题，且地址不需要转义。

**Comment by theprimone** [comment]
直接关闭了，这是不修复了吗？:joy:

**Comment by Ink-33** [comment]
你把整条url给url encode试试

**Comment by theprimone** [comment]
> 你把整条url给url encode试试

试过了，还是不行
