### ISSUE TITLE
WS 对不存在的 API 调用不返回数据

### ISSUE THREAD

**Issue by yanyongyu** [Mrs4s/go-cqhttp#508]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: latest
运行环境: any
连接方式: ws reverse
使用协议: 0

**bug内容**
当调用一个不存在的api时，gocq不会返回1404 api不存在的信息

**复现方法**
调用一个不存在的api

**Comment by Ink-33** [comment]
#509 可以close了
