### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by 1476110462** [Mrs4s/go-cqhttp#51]
账号密码均无误，登陆失败，麻烦师傅帮忙看下，谢谢师傅
![图片](https://user-images.githubusercontent.com/47727764/89660679-42152500-d904-11ea-8984-85e37e0f6153.png)

**Comment by Mrs4s** [comment]
此信息为服务器返回，请再次检查配置文件账号密码是否有误，以及文件编码是否错误
