### ISSUE TITLE
QQ登录错误: 当前上网环境异常. 将更换服务器并重试. 如果频繁遇到此问题请打开设备锁. 

### ISSUE THREAD

**Issue by hswyxj** [Mrs4s/go-cqhttp#513]
环境信息
go-cqhttp版本: 0.9.35-fix1
运行环境: windows_x86_64
连接方式: HTTP

bug内容
用正确的账号密码登陆时需要文字验证码，验证通过后显示：(重复几次验证验证码都一样)
[2020-12-24 09:43:32] [WARNING]: 错误: 当前上网环境异常. 将更换服务器并重试. 如果频繁遇到此问题请打开设备锁. 
[2020-12-24 09:43:33] [WARNING]: 请输入验证码 (captcha.jpg)： (Enter 提交) 
[2020-12-24 09:43:45] [INFO]: captcha.jpg删除成功 
[2020-12-24 09:43:45] [FATAL]: 遇到错误: Packet failed to send: write tcp 127.0.0.1:50722->120.232.18.61:8080: use of closed network connection 

该账号的（所谓的设备锁）登录保护已经打开（关闭的一样），无安全问题
（手机qq和电脑都能正常登录的，重置密码后重试也一样）

复现方法
1、 打开（关闭都一样）登录保护（所谓的设备锁）
2、 写入正确的账号密码
3、 运行go-cqhttp.exe文件

**Comment by ZhaoWeicheng98** [comment]
遇到了相同的问题。我的一个账号，无安全问题，安卓和iOS手机、电脑、iPad均能正常登录，不论是否打开登录保护均会出现相同的问题。但另一个账号能够正常登录。

环境信息
go-cqhttp版本: 0.9.35-fix1
运行环境: windows_x86_64
连接方式: 反向ws

**Comment by Mrs4s** [comment]
试试 Watch 协议?

**Comment by ZhaoWeicheng98** [comment]
> 试试 Watch 协议?

iPad、Watch和mac协议都尝试了，情况一致（需要输入验证码，均提示网络环境异常，且没有拉起设备锁，数次输入验证码后断开连接）；Android Phone也无法拉起设备锁。

**Comment by cheny658** [comment]
本人也遇到同样问题，而且并不是必现的，昨天还是可以的，今天就报错上网环境异常
环境信息
go-cqhttp版本: 0.9.35-fix1-windows-arm64
运行环境: windows_x86_64
连接方式: 反向ws

**Comment by hswyxj** [comment]
> > 试试 Watch 协议?
> 
> iPad、Watch和mac协议都尝试了，情况一致（需要输入验证码，均提示网络环境异常，且没有拉起设备锁，数次输入验证码后断开连接）；Android Phone也无法拉起设备锁。

对 我也试了  不行

**Comment by hswyxj** [comment]
> > > 试试 Watch 协议?
> > 
> > 
> > iPad、Watch和mac协议都尝试了，情况一致（需要输入验证码，均提示网络环境异常，且没有拉起设备锁，数次输入验证码后断开连接）；Android Phone也无法拉起设备锁。
> 
> 对 我也试了 不行

刚刚又试了下，可以了 = =  拉起了设备锁了  真是无语

**Comment by hswyxj** [comment]
也不知道啥原因昨天不行，昨天qq登录了一天，今天重试又行了

**Comment by ZhaoWeicheng98** [comment]
> 也不知道啥原因昨天不行，昨天qq登录了一天，今天重试又行了

坏耶，我这边还是不行。而且使用Watch协议的时候还出现了一次 遇到错误: unknown login response: 21 的问题。

**Comment by Mrs4s** [comment]
下个版本会处理这个问题

**Comment by Mrs4s** [comment]
理论上已修复

**Comment by Mrs4s** [comment]
目前看来临时解决方案通过率还是不怎么高, 需要进一步优化.

**Comment by ZhaoWeicheng98** [comment]
使用0.9.36版本后可以成功认证，但成功率不高，且如果5次重试后不更换设备的话就几乎完全不能成功。

另外拉起设备锁后，如果选择手机验证码，在正确发送验证码后会出现“遇到错误: Packet failed to send: write tcp 192.168.50.18:60396->114.221.144.34:8080: use of closed network connection” 错误并退出；使用手机QQ扫码验证后可以正常认证。

**Comment by Mrs4s** [comment]
请试试最新版, 应该OK了
