### ISSUE TITLE
V0.9.14新版无法正常收发信息

### ISSUE THREAD

**Issue by wordgao** [Mrs4s/go-cqhttp#52]
V0.9.14新版无法正常收发信息

**Comment by Mrs4s** [comment]
请提供更多信息

**Comment by wordgao** [comment]
经过测试发现 开启 http_config以及 ws_config 会影响到reverse_url数据的正常收发，服务对接用到的是ws，reverse_api_url，reverse_event_url 这2个为空，use_ws=false

**Comment by wordgao** [comment]
同时也对数据的收发产生很大的延迟，请核实。

**Comment by wordgao** [comment]
ws地址全部设置有效后的延迟更大。

**Comment by wordgao** [comment]
不排除有可能是依赖包读取不完整导致，信息收发不稳定或失败，另外开启ws的时候信息收发也是不正常的。

**Comment by Mrs4s** [comment]
无法复现此问题，将降低优先级处理

**Comment by Mrs4s** [comment]
请前往 [Actions](https://github.com/Mrs4s/go-cqhttp/actions/runs/200713787) 的 `Artifacts` 下载最新测试版，并打开debug再试试

**Comment by GreyElaina** [comment]
建议使用 danger.js, 一瞬关闭不遵守 issue template 的 issue,,,

**Comment by wordgao** [comment]
@Mrs4s EMAIL上发联系您，给您实现状态。大概明天会在线与您连线。

**Comment by Mrs4s** [comment]
> @Mrs4s EMAIL上发联系您，给您实现状态。大概明天会在线与您连线。

求你多给点bug相关信息吧，真让我抓瞎的吗
