### ISSUE TITLE
转换CQ码时出现错误: first path segment in URL cannot contain colon 将忽略.

### ISSUE THREAD

**Issue by xxyy3130** [Mrs4s/go-cqhttp#521]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: 0.9.36-fix2
运行环境: windows_amd64
连接方式: 正向WS
使用协议: AndroidPhone

**bug内容**
[WARNING]: 转换CQ码 [image,file=https://www.baidu.com/img/flexible/logo/pc/result.png] 时出现错误: Get "https://www.baidu.com/img/flexible/logo/pc/result.png": parse "heartbeat_interval: 0": first path segment in URL cannot contain colon 将忽略. 

**复现方法**
发送网络图片时出现，例如[CQ:image,file=https://www.baidu.com/img/flexible/logo/pc/result.png]

**Comment by xxyy3130** [comment]
😂破案了，proxy_rewrite配置的原因
proxy_rewrite: "" 可以
proxy_rewrite:  不可以

**Comment by sam01101** [comment]
谢谢回报, 可以关闭issuse了
