### ISSUE TITLE
connection dropped by server: EOF一直不断重复是什么原因

### ISSUE THREAD

**Issue by raindown200709** [Mrs4s/go-cqhttp#522]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: go-cqhttp-v0.9.36-fix2-windows-amd64
运行环境: 服务器Windows Server 2016
连接方式: 反向WS
使用协议: Onebot

**bug内容**
这个不断离线登录，是什么原因
https://s3.ax1x.com/2020/12/29/rbRlsU.png

**Comment by Mrs4s** [comment]
下个版本修复

**Comment by GinNide** [comment]
同样出现这种情况 机器无法使用

**Comment by Mrs4s** [comment]
已修复

**Comment by allenx555** [comment]
更新fix3后仍有该问题

**Comment by Matayoru233** [comment]
楼上那位，在配置文件里面开启使用服务器下发的重连地址可以解决这个问题，至少我目前是通过这个方法解决的
use_sso_address：true

**Comment by Matayoru233** [comment]
> 更新fix3后仍有该问题，在日志内循环报错，但是使用似乎没问题了
在配置文件里面开启使用服务器下发的重连地址可以解决这个问题，至少我目前是通过这个方法解决的
use_sso_address：true
还有听他们说把device里面的设备改成Android phone也行
protocol：1

**Comment by Mrs4s** [comment]
> > 更新fix3后仍有该问题，在日志内循环报错，但是使用似乎没问题了
> > 在配置文件里面开启使用服务器下发的重连地址可以解决这个问题，至少我目前是通过这个方法解决的
> > use_sso_address：true
> > 还有听他们说把device里面的设备改成Android phone也行
> > protocol：1

报错是因为服务器下发了一个畸形包, 理论上不影响使用, 回头会一并结局的
