### ISSUE TITLE
手机QQ合并转发 go-cqhttp发送的消息，出现图片丢失的情况

### ISSUE THREAD

**Issue by jianmj** [Mrs4s/go-cqhttp#523]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: go-cqhttp-v0.9.36-fix3
运行环境: centos 7
连接方式:   ws
使用协议:  0(iPad)

**bug内容**
安卓手机 使用QQ（V8.5.0） 合并转发多条由 go-cqhttp发送的 带图片与文字消息 的消息时，图片会被文字[图片]取代，此问题目前只在手机上发现，PC端无此问题

**复现方法**
1.选择 多条由 go-cqhttp发送的消息 
![image](https://user-images.githubusercontent.com/19400782/103351993-e8dea580-4adf-11eb-8937-691b0957d921.png)
2.合并转发到另一个群里
3.查看转发内容，发现消息内容里的图片消失了
![image](https://user-images.githubusercontent.com/19400782/103352039-11ff3600-4ae0-11eb-91c5-396dd7ebc8b0.png)

**Comment by sam01101** [comment]
QQ自身问题
![YIX _GO9~_17})6D`%}C3}Q](https://user-images.githubusercontent.com/25792361/103352297-d1ec8300-4ae0-11eb-8f37-73dcfac4c21d.jpg)

**Comment by jianmj** [comment]
> QQ自身问题
> ![YIX _GO9~_17})6D`%}C3}Q](https://user-images.githubusercontent.com/25792361/103352297-d1ec8300-4ae0-11eb-8f37-73dcfac4c21d.jpg)

我使用这个qq 号，手动发送类似消息再转发，没有出现这个问题，┑(~Д~)┍

**Comment by Mrs4s** [comment]
需要更多的测试

**Comment by sam01101** [comment]
> > QQ自身问题
> > ![YIX _GO9~_17})6D`%}C3}Q](https://user-images.githubusercontent.com/25792361/103352297-d1ec8300-4ae0-11eb-8f37-73dcfac4c21d.jpg)
> 
> 我使用这个qq 号，手动发送类似消息再转发，没有出现这个问题， ╮(╯_╰)╭

我懂, 因为我也发生过
手动发送也是一样的问题

**Comment by sam01101** [comment]
已修复

**Comment by ishkong** [comment]
要不reopen 放着吧，我又复现了

**Comment by jianmj** [comment]
嗯 ， 更新 版本后，使用新版本的go-cqhttp 发送消息再转发，还是复现了
