### ISSUE TITLE
实际消息发送成功，接口确报异常：exception:28 : Operation timed out after 3001 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by hswyxj** [Mrs4s/go-cqhttp#525]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: go-cqhttp-v0.9.36
运行环境: window7_64
连接方式: http
使用协议: iPad

**bug内容**
调用发送群聊消息接口 /send_group_msg
实际消息发送成功，接口确报异常：exception:28 : Operation timed out after 3001 milliseconds with 0 bytes received

**复现方法**
配置文件http_config的超时时间是10
"http_config": {
	"timeout": 10,
}

1、调用发送群聊消息接口 /send_group_msg
2、实际消息发送成功（日志文件也没有错误信息，是正常发送的）
3、接口确报异常：exception:28 : Operation timed out after 3001 milliseconds with 0 bytes received

**Comment by Mrs4s** [comment]
这个是PHP的异常, 应该是你框架的. 请检查 `HttpClient` 的超时设置
