### ISSUE TITLE
已经显示“发送好友”但是没有收到消息

### ISSUE THREAD

**Issue by cheny658** [Mrs4s/go-cqhttp#529]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本:  0.9.36 fix3  windows amd64
运行环境:  windows 10
连接方式:  反向ws
使用协议:  iPad

**bug内容**
一些信息群聊可以正常接收，私聊却接收不到，确定是同一段文本，且终端都显示了
发送好友 *********(********)  的消息: [{"type":  ... (625577671)字段

**Comment by cheny658** [comment]
目前发现包含url的文本经常出现这个情况

**Comment by w403360244** [comment]
我也出现这个问题了go-cqhttp版本: go-cqhttp-v0.9.36-windows-amd64, 目前感觉像是消息长度的问题,貌似是超过多长,对方就收不到信息了~

**Comment by sam01101** [comment]
腾讯风控了
