### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by allofee** [Mrs4s/go-cqhttp#53]
不确定是哪部分代码的问题

panic: runtime error: slice bounds out of range [148:146]

goroutine 1 [running]:
github.com/Mrs4s/go-cqhttp/server.(*websocketServer).onBotPushEvent(0x12fae20, 0xc000756150)
        /root/gocqhttp/go-cqhttp-3078884107/server/websocket.go:298 +0x51f
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).dispatchEventMessage(0xc000096280, 0xc000756150)
        /root/gocqhttp/go-cqhttp-3078884107/coolq/bot.go:178 +0x52
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).StartHeartbeat(0xc000096280)
        /root/gocqhttp/go-cqhttp-3078884107/coolq/bot.go:70 +0x6c
main.main()
        /root/gocqhttp/go-cqhttp-3078884107/main.go:184 +0xc91

**Comment by remiliacn** [comment]
https://github.com/Mrs4s/go-cqhttp/blob/b61fe4e43e79711908c984bacf87b8b965951109/server/websocket.go#L293-L304

**Comment by allofee** [comment]
sorry 应该是我自己修改的代码导致的问题
