### ISSUE TITLE
回复口令无法领取红包

### ISSUE THREAD

**Issue by jiaxinonly** [Mrs4s/go-cqhttp#530]
你好，我使用扩展API[CQ:redbag,title=恭喜发财]获取title的内容，然后发送title，无法领取到口令红包，请问是怎么回事？
**文字是没有错误的，我复制测试过**
![image](https://user-images.githubusercontent.com/57223696/103450501-8c070900-4cf2-11eb-8ddb-5ae95bb3fd42.png)

**Comment by ishkong** [comment]
暂不支持领取红包

**Comment by jiaxinonly** [comment]
> 暂不支持领取红包

也就是说，QQ口令红包并不是简单的发送口令就可以领取的，对吗？

**Comment by ishkong** [comment]
> > 暂不支持领取红包
> 
> 也就是说，QQ口令红包并不是简单的发送口令就可以领取的，对吗？

是的，如果你有领取红包的需求，推荐使用小栗子

**Comment by jiaxinonly** [comment]
> > > 暂不支持领取红包
> > 
> > 
> > 也就是说，QQ口令红包并不是简单的发送口令就可以领取的，对吗？
> 
> 是的，如果你有领取红包的需求，推荐使用小栗子

好的，谢谢！

**Comment by Yiwen-Chan** [comment]
🌿
