### ISSUE TITLE
0.9.37无法发送语音

### ISSUE THREAD

**Issue by Cappuccilo** [Mrs4s/go-cqhttp#538]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: 0.9.37
运行环境: ubuntu
连接方式: 反向ws
使用协议: Android Phone

**bug内容**
bot无法发送语音。

**复现方法**
更新到0.9.37后，bot无法发送语音，回退到0.9.36后，可以正常发送语音

**Comment by tushanxiaodu** [comment]
go-cqhttp版本: 0.9.37
运行环境: windows_amd64
连接方式: ws_reverse
使用协议: Android Phone
bug内容
bot无法发送语音。遇到相同问题

**Comment by Mrs4s** [comment]
正在处理了

**Comment by SlightDust** [comment]
遇到了同样的情况，回退到9.36可以发。大佬加油
