### ISSUE TITLE
经常出现time out错误信息

### ISSUE THREAD

**Issue by wordgao** [Mrs4s/go-cqhttp#54]
经常出现time out错误信息

**Comment by wordgao** [comment]
![002](https://user-images.githubusercontent.com/10544395/89703550-76c5c280-d97e-11ea-8124-8b906ebb68b2.jpg)
这个应该shi是加载依赖包的超时提示，以及读取好友列表失败的提示。

**Comment by Mrs4s** [comment]
网络超时

**Comment by Mrs4s** [comment]
请追踪 Mrs4s/MiraiGo#12
