### ISSUE TITLE
已经显示“发送群”但是没有收到消息

### ISSUE THREAD

**Issue by Rainie7777** [Mrs4s/go-cqhttp#543]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: go-cqhttp-v0.9.37-fix1
运行环境: 阿里云ECS alibaba cloud liunx 2
连接方式: 反向ws
使用协议: iPad

**bug内容**
完全相同的信息，私聊可以接受到，群消息则接受不到，终端都显示了发送消息，未提示风控
消息内容含有链接，force_fragmented和fix_url都是true

**Comment by Mrs4s** [comment]
风控客户端没办法处理
