### ISSUE TITLE
红包运气王QQ号错误

### ISSUE THREAD

**Issue by hao58231** [Mrs4s/go-cqhttp#545]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.37-fix1
运行环境: linux-amd64
连接方式: 反向ws
使用协议: Android Phone

**bug内容**
运气王QQ号(target_id)恒为最后领取红包的QQ号,换IPAD协议也是如此。

**复现方法**
群里发送多人红包并全部领取，go-cqhttp的推送的Event信息有误

**Comment by Mrs4s** [comment]
已修复
