### ISSUE TITLE
病毒误报？还是我电脑中毒了。

### ISSUE THREAD

**Issue by wordgao** [Mrs4s/go-cqhttp#546]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: go-cqhttp-v0.9.37-fix1-windows-amd64
运行环境: windows 2019 server
连接方式: 反向
使用协议: ipad

**bug内容**
不定时出现360病毒警告！
[
![11](https://user-images.githubusercontent.com/10544395/104014496-161d0900-51ee-11eb-8cf3-b8d08c557570.jpg)
](url)
![22](https://user-images.githubusercontent.com/10544395/104014511-1cab8080-51ee-11eb-8f18-e2fdf6629519.jpg)

**复现方法**
不确定！

**Comment by Mrs4s** [comment]
不是我的问题, 请去找360
这边建议您卸载360呢

**Comment by fkx4-p** [comment]
https://habo.qq.com/file/showdetail?pk=ADcGY11uB2AIO1s5U2o%3D
请。
