### ISSUE TITLE
开发手机app集群管理

### ISSUE THREAD

**Issue by bbhxwl** [Mrs4s/go-cqhttp#553]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: 
运行环境: 
连接方式: 
使用协议: 

**bug内容**
想知道这个项目的协议长久吗？想利用这个自己开发个ios和android的一个软件管理多个qq的软件，出门比较方便。还能开发一些插件，这个协议会容易失效么。

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by Mrs4s** [comment]
开源项目, 就算我不维护了也能让其他人接手维护

**Comment by Ink-33** [comment]
利用此开源协议开发其他软件是您的权利，但请留意您开发的任何程序都受到AGPL-3.0的限制，也就是说您需要公开您的程序源代码。感谢您对开源社区做出贡献
