### ISSUE TITLE
【功能建议】能否新增群成员私聊，限制为仅管理员可用此功能以规避滥用

### ISSUE THREAD

**Issue by Darley-Wey** [Mrs4s/go-cqhttp#556]

**Comment by yuudi** [comment]
关于插件的问题请反馈给相应插件作者。

**Comment by Mrs4s** [comment]
可以考虑

**Comment by sam01101** [comment]
这个我有考虑过, 但如果要更改就可能会触发`机器人必须为被动`的问题
也就是允许机器人主动发起临时会话

这样会导致一个问题: `可以在未加群的情况下主动向群主/管理员发起临时会话进行骚扰`

引用mirai的`README.md`
> [**不会支持的协议**](https://github.com/mamoe/mirai#%E4%B8%8D%E4%BC%9A%E6%94%AF%E6%8C%81%E7%9A%84%E5%8D%8F%E8%AE%AE)
> ...
> 敏感操作，如主动添加好友、主动加入群、主动邀请好友加群

如果 @Mrs4s 允许的话, 我可以在`send_private_msg`添加`group`参数去让机器人主动发起临时会话

待回复...

**Comment by sam01101** [comment]
如果限制为管理员可用, 我倒是建议在插件里面判断一下, 应该不难

目前的情况就是`群成员必须主动向机器人发起临时会话`

**Comment by sam01101** [comment]
没问题，是我误解了意思
