### ISSUE TITLE
发送语音时会有.silk文件出现在与go-cqhttp同级目录

### ISSUE THREAD

**Issue by LambdaYH** [Mrs4s/go-cqhttp#561]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.38
运行环境: Debian 10.5
连接方式: 反向ws
使用协议: ipad

**bug内容**
发送语音时会有.silk文件出现在与go-cqhttp同级目录
```
1a7bef11d1297d64cf21b52403d95239.silk  965265a34bd97c06aea0e53de9da4bb8.silk  device.json
2abb1b951238fa9acfb848f7f6f0a6a6.silk  cbec072010af54e4d85a327a15ca87d8.silk  fd1cefabda92239f8a0834ae62f93ca5.silk
4be717c2c9d4483a469b7569d3e76466.silk  codec                                  go-cqhttp
6de2de749c124edcfe519291a07ccadb.silk  config.hjson                           logs
839581afa46230fd4532c38fbba84469.silk  data

```

**复现方法**
发送.wav语音文件

**Comment by Ink-33** [comment]
您好，这是正常的。QQ采用的语音编码格式为silk，gocq需要将wav编码为silk文件才能发送。

预计接下来将会把silk文件的缓存移动至缓存目录

**Comment by LambdaYH** [comment]
> 您好，这是正常的。QQ采用的语音编码格式为silk，gocq需要将wav编码为silk文件才能发送。
> 
> 预计接下来将会把silk文件的缓存移动至缓存目录

嗯 我也是觉得silk不应该出现在这，导致目录很乱

**Comment by ishkong** [comment]
> > 您好，这是正常的。QQ采用的语音编码格式为silk，gocq需要将wav编码为silk文件才能发送。
> > 预计接下来将会把silk文件的缓存移动至缓存目录
> 
> 嗯 我也是觉得silk不应该出现在这，导致目录很乱

这可能并不正常，据写这一块的开发者 @wdvxdr1123 说，文件应该会生成在 `data/cache' 里
