### ISSUE TITLE
可能被风控，尝试分片发送时，群发消息就会重复发送两条一样的消息

### ISSUE THREAD

**Issue by hswyxj** [Mrs4s/go-cqhttp#562]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: go-cqhttp-v0.9.38-linux-amd64
运行环境: linux-amd64
连接方式: http
使用协议: Android Phone

**bug内容**
[2021-01-14 14:10:13] [WARNING]: 群消息发送失败: 账号可能被风控. 
[2021-01-14 14:10:13] [WARNING]: 将尝试分片发送...

前提：没有开启强制分片发送
调用群发消息接口，QQ日志显示：账号可能被风控，尝试分片发送时，
群就会重复发送两条一样的消息

**复现方法**
调用群发消息接口发相对类似的消息或其他消息，有些比较长，有些比较短，偶然会发生，QQ日志显示：可能被风控，尝试分片发送时，群发消息就会重复发送两条一样的消息的情况

**Comment by chitanda-suki** [comment]
同问题，强制开启分片可解决

**Comment by hswyxj** [comment]
> 同问题，强制开启分片可解决
强制开启分片  是否有其他问题出现？
