### ISSUE TITLE
强吻一下啊  [WARNING]: 连接到反向Websocket Universal服务器 ws://127.0.0.1:3000 时出现错误: unexpected EOF

### ISSUE THREAD

**Issue by wandefou** [Mrs4s/go-cqhttp#563]
使用的是 nodejs socket.io 
配置文件如下:
// 反向WS设置
    ws_reverse_servers: [
        // 可以添加多个反向WS推送
        {
            // 是否启用该推送
            enabled: true
            // 反向WS Universal 地址
            // 注意 设置了此项地址后下面两项将会被忽略
            // 留空请使用 ""
            reverse_url: "ws://127.0.0.1:3000"
            // 反向WS API 地址
            reverse_api_url: "ws://127.0.0.1:3000/api"
            // 反向WS Event 地址
            reverse_event_url: "ws://127.0.0.1:3000/et"
            // 重连间隔 单位毫秒
            reverse_reconnect_interval: 3000
        }
    ]

- server.js

var express = require('express');
var app = express();
var server = require('http').Server(app);
const io = require('socket.io')
const socket = io(server,{path:""});
const apiSocket = io(server,{path:"/api"});
const etSocket = io(server,{path:"/et"});
socket.on('connection', (socket) => {
  console.log(" con")
});
apiSocket .on('connection', (socket) => {
  console.log(" api")
});
etSocket .on('connection', (socket) => {
  console.log(" et")
});

server.listen(3000, function () {
  console.log('server listening on port 3000');
});

-问题:
[2021-01-15 13:00:27] [WARNING]: 连接到反向Websocket Universal服务器 ws://127.0.0.1:3000 时出现错误: unexpected EOF

请帮助一下,谢谢!

**Comment by ishkong** [comment]
请尝试不要填写reverse_url，当存在reverse_url时，go可能不会连接下面两个地址

**Comment by wandefou** [comment]
湿了一下
第一个留空 第二个留空 第三个留空(等等各种排列组合的情况)  都是报错  [WARNING]: 连接到反向Websocket Universal服务器 ws://127.0.0.1:3000 时出现错误: unexpected EOF
额.. 请麻烦帮助一下哈

**Comment by v587ygq** [comment]
参考 [stackoverflow](https://stackoverflow.com/questions/34370507/socket-connection-closed-before-receiving-a-handshake-response) ，socketio 库需要服务端和客户端配套使用。如果要与 go-cqhttp 连接，应使用更底层的 ws 库，参考下面示例
```js
var express = require('express');
var app = express();
var server = require('http').Server(app);
const io = require('ws')
const socket = new io.Server({ path: '/', noServer: true });
socket.on('connection', (socket) => {
    console.log(" api")
});

server.on('upgrade', () => {
    socket.emit('connection')
})

server.listen(3000, function () {
    console.log('server listening on port 3000');
});
```

如果需要完整的框架可以参考 https://github.com/v587ygq/cqbot/blob/master/src/index.js

**Comment by wandefou** [comment]
嗯嗯  对的  事实证明那玩意儿用不了   可以使用  nodejs-websocket 或者其他的  哦了
射射你 , 十分感射!
