### ISSUE TITLE
【功能建议】能否新增查询指定群是否开起全员禁言接口

### ISSUE THREAD

**Issue by Vang-z** [Mrs4s/go-cqhttp#565]
如果在发送消息时群开启了全员禁言，机器人会尝试分片发送消息，最后返回被风控错误
![Snipaste_2021-01-15_20-02-16](https://user-images.githubusercontent.com/44422499/104725375-f9904c00-576c-11eb-9ac9-e0b811e9efbe.png)

**Comment by qianjunakasumi** [comment]
解决这个问题不一定新增所描述的接口，只需在发送消息前判断是否禁言，避免将复杂度转移外部
