### ISSUE TITLE
部分短视频上传失败

### ISSUE THREAD

**Issue by biuuu** [Mrs4s/go-cqhttp#577]
**环境信息**
go-cqhttp版本: v0.9.38-fix1
运行环境: windows 10
连接方式: http
使用协议: MacOS

**bug内容**
发送短视频时部分视频能成功发送，部分始终发送失败。视频文件用本地或http结果相同。
如果自己预先用手机发送相同视频文件之后，BOT发送相同文件也会成功。
由于这个特点，不太确定成功的视频是否是因为其他人发送过，所以才成功了。
```[2021-01-19 11:15:38] [DEBUG]: HTTPServer接收到API调用: send_msg
[2021-01-19 11:15:38] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbDeleteMsg seq: 13899
[2021-01-19 11:15:38] [DEBUG]: Protocol -> continue sync with flag: CONTINUME
[2021-01-19 11:15:39] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbGetMsg seq: 13900
[2021-01-19 11:15:39] [DEBUG]: Protocol -> rev pkt: PttCenterSvr.GroupShortVideoUpReq seq: 13901
[2021-01-19 11:15:39] [WARNING]: 警告: 私聊 ***** 消息短视频上传失败: upload video file error: upload failed: 70
[2021-01-19 11:15:39] [WARNING]: 好友消息发送失败: 消息为空.
[2021-01-19 11:15:40] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbDeleteMsg seq: 13903
[2021-01-19 11:15:40] [DEBUG]: Protocol -> continue sync with flag: CONTINUME
[2021-01-19 11:15:40] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbGetMsg seq: 13905
[2021-01-19 11:15:40] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbDeleteMsg seq: 13906
```

**复现方法**
成功发送的视频：https://shinycolors.enza.fun/assets/83ffe29918b07ffa0b442b3ed4152defb376d5e65d8482cf98e345622c67f24f.mp4?v=3

发送失败的视频：
https://shinycolors.enza.fun/assets/47489f49a8dd7e7c3911a5554307197de9108e6eafffb86a5920304b4ee2b31e.mp4?v=6

**Comment by shitianshiwa** [comment]
用go-cqhttp v0.9.38-fix1 直接发原视频会报
```
[WARNING]: 警告: 群聊 ***** 消息短视频上传失败: upload video file error: upload failed: 70
[WARNING]: 群聊消息发送失败: 消息为空.
```
用tim手机客户端手动发一次视频后，再用go-cqhttp发可以成功，
找到pcqq下载的短视频缓存和原文件进行二进制对比发现和原来的视频一样（视频大小1.56MB）

**Comment by Mrs4s** [comment]
已修复

**Comment by Miuzarte** [comment]
> 已修复

1.0.0 beta3仍然遇到了这个问题,无法直接上传视频,也用同样的方法成功复现了楼上[https://github.com/Mrs4s/go-cqhttp/issues/577#issuecomment-766287042](url)

**Comment by sam01101** [comment]
> > 已修复
> 
> 1.0.0 beta3仍然遇到了这个问题,无法直接上传视频,也用同样的方法成功复现了楼上[shitianshiwa commented on 24 Jan](https://github.com/Mrs4s/go-cqhttp/issues/577#issuecomment-766287042)
> 在Android phone和iPad协议上都复现过

70 是代表视频内容格式错误
请检查视频内容，有必要的话请手动`ffmpeg`转成`mp4`
如果不行，应该还是格式问题

**Comment by sam01101** [comment]
反向issue时间到~

**Comment by sam01101** [comment]
等下，我记得这不是加密的问题吗？ @Mrs4s

**Comment by Miuzarte** [comment]
> > > 已修复
> > 
> > 1.0.0 beta3仍然遇到了这个问题,无法直接上传视频,也用同样的方法成功复现了楼上[shitianshiwa commented on 24 Jan](https://github.com/Mrs4s/go-cqhttp/issues/577#issuecomment-766287042)
> > 在Android phone和iPad协议上都复现过
> 
> 70 是代表视频内容格式错误
> 请检查视频内容，有必要的话请手动`ffmpeg`转成`mp4`
> 如果不行，应该还是格式问题

我apt了一个ffmpeg之后没70过了，是gocq在自己调用吗

**Comment by sam01101** [comment]
> > > > 已修复
> > > 
> > > 
> > > 1.0.0 beta3仍然遇到了这个问题,无法直接上传视频,也用同样的方法成功复现了楼上[shitianshiwa commented on 24 Jan](https://github.com/Mrs4s/go-cqhttp/issues/577#issuecomment-766287042)
> > > 在Android phone和iPad协议上都复现过
> > 
> > 
> > 70 是代表视频内容格式错误
> > 请检查视频内容，有必要的话请手动`ffmpeg`转成`mp4`
> > 如果不行，应该还是格式问题
> 
> 我apt了一个ffmpeg之后没70过了，是gocq在自己调用吗

gocq本身有使用`ffmpeg`进行转换

**Comment by Miuzarte** [comment]
> > > > > 已修复
> > > > 
> > > > 
> > > > 1.0.0 beta3仍然遇到了这个问题,无法直接上传视频,也用同样的方法成功复现了楼上[shitianshiwa commented on 24 Jan](https://github.com/Mrs4s/go-cqhttp/issues/577#issuecomment-766287042)
> > > > 在Android phone和iPad协议上都复现过
> > > 
> > > 
> > > 70 是代表视频内容格式错误
> > > 请检查视频内容，有必要的话请手动`ffmpeg`转成`mp4`
> > > 如果不行，应该还是格式问题
> > 
> > 我apt了一个ffmpeg之后没70过了，是gocq在自己调用吗
> 
> gocq本身有使用`ffmpeg`进行转换

这个本身是指release中内置了ffmpeg？
我没安装ffmpeg之前自己尝试发送本地视频也是失败（不使用'cq-picsearcher-bot'）

**Comment by sam01101** [comment]
哦，我懂了
`gocq` 本身并没有附带 `ffmpeg`，需要用户自行安装

**Comment by sam01101** [comment]
> > 已修复
> 
> 1.0.0 beta3仍然遇到了这个问题,无法直接上传视频,也用同样的方法成功复现了楼上[shitianshiwa commented on 24 Jan](https://github.com/Mrs4s/go-cqhttp/issues/577#issuecomment-766287042)
> 在Android phone和iPad协议上都复现过

这个问题就是由于没看文档而造成的问题，总之
如果要发送短视频就请自行安装ffmpeg
gocq可不会主动为用户安装东西，而且内置会导致binary的大小芜湖起飞🐉

**Comment by Miuzarte** [comment]
> > > 已修复
> > 
> > 1.0.0 beta3仍然遇到了这个问题,无法直接上传视频,也用同样的方法成功复现了楼上[shitianshiwa commented on 24 Jan](https://github.com/Mrs4s/go-cqhttp/issues/577#issuecomment-766287042)
> > 在Android phone和iPad协议上都复现过
> 
> 这个问题就是由于没看文档而造成的问题，总之
> 如果要发送短视频就请自行安装ffmpeg
> gocq可不会主动为用户安装东西，而且内置会导致binary的大小芜湖起飞🐉

建议github的wiki不维护的话就直接指向网站吧，我平时都看的github wiki

**Comment by sam01101** [comment]
> > > > 已修复
> > > 
> > > 
> > > 1.0.0 beta3仍然遇到了这个问题,无法直接上传视频,也用同样的方法成功复现了楼上[shitianshiwa commented on 24 Jan](https://github.com/Mrs4s/go-cqhttp/issues/577#issuecomment-766287042)
> > > 在Android phone和iPad协议上都复现过
> > 
> > 
> > 这个问题就是由于没看文档而造成的问题，总之
> > 如果要发送短视频就请自行安装ffmpeg
> > gocq可不会主动为用户安装东西，而且内置会导致binary的大小芜湖起飞🐉
> 
> 建议github的wiki不维护的话就直接指向网站吧，我平时都看的github wiki

#804

**Comment by 675535** [comment]
经测试，小于3M的视频经常发送失败，95%~100%，大于3M视频100%发送成功。原因未知。
