### ISSUE TITLE
[feature] 对大文件的下载兼容

### ISSUE THREAD

**Issue by sam01101** [Mrs4s/go-cqhttp#578]
目前对太大的文件(>900M)会下载失败, 因此需要调整代码以兼容下载

**Comment by Ink-33** [comment]
要不大文件调用aria2c(&nbsp;




Ink33
深圳市煜辉泰电子科技有限公司


 联系我









&nbsp;




------------------&nbsp;Original&nbsp;------------------

**Comment by Ink-33** [comment]
要不大文件调用aria2c(

**Comment by sam01101** [comment]
我都差点忘了这个issue(虽然是今天早上开的)
就些尴尬问题,API timeout
