### ISSUE TITLE
在go-cqhttp不开分片的情况下，机器人自己的带图片消息被撤回后，机器人发送被撤回消息会出现转发的情况

### ISSUE THREAD

**Issue by AkiraXie** [Mrs4s/go-cqhttp#586]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: 0.9.38-fix1
运行环境: linux-amd64
连接方式: 反向WS
使用协议: ipad

**bug内容**
在没开强制分片的情况（开分片正常）下，机器人的带图信息被撤回之后，再次发送被撤回消息会用转发的形式出现。
以下是bug截图和开debug后的日志截图
![}NI%MW8NIXFTKOLZXA41OB](https://user-images.githubusercontent.com/50363732/105569853-619fed00-5d80-11eb-9189-618499112bc6.png)
![image](https://user-images.githubusercontent.com/50363732/105569907-dbd07180-5d80-11eb-9519-b1da98e93864.png)

![{I0)59DF32NQ@WUJ)XR4UGR](https://user-images.githubusercontent.com/50363732/105569857-66fd3780-5d80-11eb-8fdd-eae0eeec930a.png)

**复现方法**
1.  机器人的带图消息被管理员撤回，触发`group_recall`事件，机器人接受事件并记录message_id
2.  机器人调用`get_msg`API，获取被撤回的消息(`raw_message`字段和`message`字段都可以)
3.  机器人调用`send_group_msg`API发送被撤回的消息，此时将发送转发消息而不是普通消息。

**Comment by sam01101** [comment]
请检查清楚你原本的代码是否正确

我等下写复现结果

**Comment by AkiraXie** [comment]
赞美昵昵！
