### ISSUE TITLE
【功能建议】希望update更新程序能加个默认同意所有选项的选项

### ISSUE THREAD

**Issue by mengshouer** [Mrs4s/go-cqhttp#588]
希望update后加个-y同意的选项，或者加个新指令。
这样方便使用bat或者ps1弄个全自动更新+运行(

**Comment by wdvxdr1123** [comment]
可以使用
echo y| ./go-cqhttp update

**Comment by mengshouer** [comment]
> 可以使用
> echo y| ./go-cqhttp update

行了(
