### ISSUE TITLE
即使指定了日志级别为warn，logs文件夹中依然会保存info级别的日志文件

### ISSUE THREAD

**Issue by zhanbao2000** [Mrs4s/go-cqhttp#589]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: go-cqhttp-v0.9.38-fix1
运行环境: windows_amd64
连接方式: http
使用协议: iPad

**bug内容**
在config.hjson指定了log_level为warn后，logs文件夹中会出现形如2021-01-22-warn.log这样的日志，其中保存的是warn及以上级别的日志。但同时也会出现形如2021-01-22.log这样的日志，其中保存的是info级别及以上的日志，并且无论将log_level设置为何，该日志都将出现。由于聊天记录也属于info级别，并且本人的机器人被拉入了大量的群，一天下来这个日志文件将很庞大（几乎全部都是聊天记录）

**复现方法**
1、将config.hjson的log_level指定为warn
2、双击go-cqhttp.exe并运行一段时间
3、之后即可在logs文件夹里发现带有info级别的日志文件

**Comment by xuthus5** [comment]
@zhanbao2000 在 #580  中解决了该问题。
