### ISSUE TITLE
反向ws断开会无法获取群荣誉信息

### ISSUE THREAD

**Issue by zangxx66** [Mrs4s/go-cqhttp#593]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.39
运行环境: linux_amd64
连接方式: 反向WS
使用协议: MacOS

**bug内容**
nonebot开启了热重载，热更新文件后反向WS会断开几秒，自动重新连接后调用```get_group_honor_info```会无法正常返回数据

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by SlightDust** [comment]
遇到了同样的问题。
go-cqhttp的log：

> [2021-01-29 16:07:35] [INFO]: 昨日 对唔住！优衣姐！(1085289815) 在群 817040795 内发言最积极, 获得 龙王 标识。 
nonebot提示KeyError: 'current_talkative'
[2021-01-29 16:07:36,130 nonebot] ERROR: An exception occurred while handling event notice.notify.honor:
[2021-01-29 16:07:36,130 nonebot] ERROR: 'current_talkative'

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/nonebot/notice_request.py", line 82, in handle_notice_or_request
>     await _bus.emit(ev_name, session)
>   File "/usr/local/lib/python3.8/site-packages/aiocqhttp/bus.py", line 35, in emit
>     results += await asyncio.gather(*coros)
>   File "/root/qqbot/HoshinoBot/hoshino/service.py", line 371, in wrapper
>     return await func(session)
>   File "/root/qqbot/HoshinoBot/hoshino/modules/my_chat/my_chat.py", line 208, in new_longwang
>     current_talkactive = data['current_talkative']
> KeyError: 'current_talkative'

**Comment by SlightDust** [comment]
遇到了同样的问题。
go-cqhttp的log：

> [2021-01-29 16:07:35] [INFO]: 昨日 对唔住！优衣姐！(1085289815) 在群 817040795 内发言最积极, 获得 龙王 标识。

nonebot提示KeyError: 'current_talkative'

> [2021-01-29 16:07:36,130 nonebot] ERROR: An exception occurred while handling event notice.notify.honor:
> [2021-01-29 16:07:36,130 nonebot] ERROR: 'current_talkative'
> 
> Traceback (most recent call last):
> File "/usr/local/lib/python3.8/site-packages/nonebot/notice_request.py", line 82, in handle_notice_or_request
> await _bus.emit(ev_name, session)
> File "/usr/local/lib/python3.8/site-packages/aiocqhttp/bus.py", line 35, in emit
> results += await asyncio.gather(*coros)
> File "/root/qqbot/HoshinoBot/hoshino/service.py", line 371, in wrapper
> return await func(session)
> File "/root/qqbot/HoshinoBot/hoshino/modules/my_chat/my_chat.py", line 208, in new_longwang
> current_talkactive = data['current_talkative']
> KeyError: 'current_talkative'

**Comment by SlightDust** [comment]
使用版本是v0.9.38-fix1

**Comment by sam01101** [comment]
开debug，看推送的Event
看下JSON里面的字样

**Comment by Mrs4s** [comment]
应该修复了

**Comment by Jerry-FaGe** [comment]
> 应该修复了

貌似还没有，`current_talkative `这个字段还是时有时无，而且每个群有没有也不一定，已经重启过了

- 没有的情况（参数为all获取的，参数为talkative的时候更迷惑）

```
 {
	'emotion_list': None,
	'group_id': 1082xxxx07,
	'legend_list': [{
		'avatar': 'http://thirdqq.qlogo.cn/g?b=oidb&k=GBdia3YFHUo6NW45tS6EMHQ&s=640',
		'description': '连续发消息89天',
		'nickname': '人工智障',
		'user_id': 1878xxxx24
	}],
	'performer_lis': [{
		'avatar': 'http://thirdqq.qlogo.cn/g?b=oidb&k=eRbSeALOB7zHvvdL4NA56g&s=640',
		'description': '连续发消息7天',
		'nickname': 'Jerry痞孓╭',
		'user_id': 61xxxx968
	}],
	'strong_newbie_list': None,
	'talkative_list': [{
		'avatar': 'http://thirdqq.qlogo.cn/g?b=oidb&k=nwphBffq1I7nKFtpWMD80A&s=640',
		'description': '3天，最长蝉联1天',
		'nickname': '屌丝',
		'user_id': 403xxxx94
	}, {
		'avatar': 'http://thirdqq.qlogo.cn/g?b=oidb&k=eRbSeALOB7zHvvdL4NA56g&s=640',
		'description': '21天，最长蝉联5天',
		'nickname': 'Jerry痞孓╭',
		'user_id': 61xxxx968
	}, {
		'avatar': 'http://thirdqq.qlogo.cn/g?b=oidb&k=GBdia3YFHUo6NW45tS6EMHQ&s=640',
		'description': '44天，最长蝉联19天',
		'nickname': '人工智障',
		'user_id': 1878xxxx24
	}]
}
```

- 有的情况

```
{
	'current_talkative': {
		'avatar': 'http://thirdqq.qlogo.cn/g?b=oidb&k=GBdia3YFHUo6NW45tS6EMHQ&s=',
		'day_count': 1,
		'nickname': '凯露酱',
		'user_id': 1878xxxx24
	},
	'emotion_list': None,
	'group_id': 485xxxx87,
	'legend_list': [{
		'avatar': 'http://thirdqq.qlogo.cn/g?b=oidb&k=GBdia3YFHUo6NW45tS6EMHQ&s=640',
		'description': '连续发消息89天',
		'nickname': '凯露酱',
		'user_id': 1878xxxx24
	}],
	'performer_lis': None,
	'strong_newbie_list': None,
	'talkative_list': [{
		'avatar': 'http://thirdqq.qlogo.cn/g?b=oidb&k=GBdia3YFHUo6NW45tS6EMHQ&s=640',
		'description': '65天，最长蝉联40天',
		'nickname': '凯露酱',
		'user_id': 1878xxxx24
	}, {
		'avatar': 'http://thirdqq.qlogo.cn/g?b=oidb&k=nfoOQjnj5vNSicWiaLkIBpjQ&s=640',
		'description': '7天，最长蝉联5天',
		'nickname': 'CC',
		'user_id': 377xxxx58
	}, {
		'avatar': 'http://thirdqq.qlogo.cn/g?b=oidb&k=eRbSeALOB7zHvvdL4NA56g&s=640',
		'description': '4天，最长蝉联2天',
		'nickname': 'Jerry_FaGe',
		'user_id': 61xxxx968
	}, {
		'avatar': 'http://thirdqq.qlogo.cn/g?b=oidb&k=hQRHibvVygGTn6aCpFNCx5Q&s=640',
		'description': '3天，最长蝉联2天',
		'nickname': 'Jerry_ALU',
		'user_id': 3398xxxx77
	}]
}
```
