### ISSUE TITLE
[BUG] group_message中sender.role字段错误

### ISSUE THREAD

**Issue by Ninzore** [Mrs4s/go-cqhttp#595]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: 0.9.39
运行环境: Debian 10
连接方式: 正向WS
使用协议: iPad

**bug内容**
对于有一些人，group_message中sender.role字段会有错误，不是管理员却显示为admin，同一个人在不同的群均如此

**复现方法**
有一些人可以触发，具体需要什么条件尚不明确，目前已知的信息有：
不是管理员，也不曾为管理员，并且在所有群均不为管理
是个小号，和大号曾经关联过（现在并不是关联状态），大号目前为一个群的管理

**Comment by Ninzore** [comment]
好像也会偶发抽风？有待继续测试

**Comment by Mrs4s** [comment]
已处理 请等待下个版本release
