### ISSUE TITLE
[Feat]有无让实例自动后台运行的命令行选项

### ISSUE THREAD

**Issue by KotoriK** [Mrs4s/go-cqhttp#597]
Linux部署运行的时候，go-cqhttp的生命周期会和当前的登录会话绑定，一旦退出ssh会话程序就挂起了，要套个```screen```才能保持后台运行。
所以有没有直接保持后台运行不需要挂screen的操作

就我理解好像是可以注册成服务？

**Comment by yuudi** [comment]
nohup ./gocqhttp >gocq.log 2>&1 &

**Comment by kokororin** [comment]
supervisor

**Comment by KotoriK** [comment]
可 学到了
