### ISSUE TITLE
文本超过一定长度后，链接会被截断，无法正常显示

### ISSUE THREAD

**Issue by biuuu** [Mrs4s/go-cqhttp#599]
**环境信息**
go-cqhttp版本: v0.9.39
运行环境: win10
连接方式: http
使用协议: MacOS

**bug内容**
有时链接会被截断成两个，有时候整个消息直接无法在PC客户端上显示。但手机QQ上还能看见。

![image](https://user-images.githubusercontent.com/10892119/105966011-0ee76d80-60bf-11eb-8765-1376ae6093fa.png)

**复现方法**
使用以下文本，在群里发送或私聊都可以。
> 123456789012345「旭丘分校」的学生，仅有五人。 虽然学年性格各不相同，但大家一起做菜、一起捉虫、一起试着练习乐器……春夏秋冬四季变换的乡村生活，一直都那么让人兴奋。 虽然一如既往地平和，但在欢笑和感动当中，心中也变得温暖起来。 悠哉悠哉的几位成员所度过的日常，再一次开始了。https://www.bilibili.com/bangumi/play/ss36204/

**Comment by Mrs4s** [comment]
这是QQ客户端渲染bug, 无法解决. 请关闭强制分片即可
