### ISSUE TITLE
v0.9.15 私聊事件 反向ws无法收到事件

### ISSUE THREAD

**Issue by ggrp-china** [Mrs4s/go-cqhttp#60]
v0.9.15 私聊qot的事件反向ws没有收到，其他事件如群消息，群消息撤回能收到。

环境：win10
版本：v0.9.15-windows-amd64

**Comment by ggrp-china** [comment]
只开启ws_reverse_servers也出现此问题

**Comment by SakuraDon99** [comment]
+1 我也遇到这个问题

**Comment by wordgao** [comment]
后台不变的情况下，利用其他插件正常，但是gocq会存在收发不正常，又或者延迟很严重。

**Comment by wordgao** [comment]
有时候正常的完全感觉不到任何问题，之后可能就不正常了，我不知道go的那里的循环出问题了，期待大佬能检查一下。

**Comment by wordgao** [comment]
从之前的几个版本就出现了这个问题的，我已经反馈了好几个版本类似的相同问题，间歇性的出现，ws连接不上报数据，有时候正常的没话说，有时候让人有点无厘头。。
 v0.1.9.12的版本，也许会正常一点，测试的时候没发现间歇性的问题。

**Comment by Mrs4s** [comment]
最新版本应该修复, 再次出现请reopen此issue.
