### ISSUE TITLE
图文消息概率丢失图片

### ISSUE THREAD

**Issue by zangxx66** [Mrs4s/go-cqhttp#600]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.39
运行环境: linux_amd64
连接方式: 反向ws
使用协议: MacOS

**bug内容**
![QQ截图20210128120255](https://user-images.githubusercontent.com/14540861/106088584-3727a880-6161-11eb-8b0b-205725168f42.png)

**复现方法**
发送图文消息，图片会概率丢失，无论是file还是base64协议都会出现这个问题

**Comment by sam01101** [comment]
请问是否可以提供图片链接测试

**Comment by zangxx66** [comment]
日志没显示完整的发送消息，我开debug观察几天看看

**Comment by sam01101** [comment]
请问问题是否依赖存在?

**Comment by xiangxiangxiong9** [comment]
> 请问问题是否依然存在?

恭喜我又中奖了…
有时候发送正常，有时候发送失败[upload failed]
Debug中无明显错误
>>[话说RM是啥？？]

**Comment by sam01101** [comment]
> > 请问问题是否依然存在?
> 
> 恭喜我又中奖了…
> 有时候发送正常，有时候发送失败[upload failed]
> Debug中无明显错误
> 
> > > [话说RM是啥？？]

https://github.com/Mrs4s/go-cqhttp/labels

**Comment by zangxx66** [comment]
> 请问问题是否依然存在?

这个问题时有时无，还不好复现，log只能看到上传图片失败

**Comment by xiangxiangxiong9** [comment]
> > > 请问问题是否依然存在?
> > 
> > 
> > 恭喜我又中奖了…
> > 有时候发送正常，有时候发送失败[upload failed]
> > Debug中无明显错误
> > > > [话说RM是啥？？]
> 
> https://github.com/Mrs4s/go-cqhttp/labels

oh…

**Comment by clacknya** [comment]
我发现我的问题是只能发已经发过的图片，发送新图片就上传失败……如果手动在客户端上成功发送一次，用cq就正常发送了。这种是不是被风控了？

**Comment by sam01101** [comment]
大概率是被风控了, 因为已发过的图片会在腾讯服务器缓存
然后可以直接发送

**Comment by xiangxiangxiong9** [comment]
> 我发现我的问题是只能发已经发过的图片，发送新图片就上传失败……如果手动在客户端上成功发送一次，用cq就正常发送了。这种是不是被风控了？

我这是已经发过的图片报上传失败...[代码里写的是本地路径]
