### ISSUE TITLE
带图片的 [CQ:reply] 在 PC QQ 上显示错位

### ISSUE THREAD

**Issue by xb2016** [Mrs4s/go-cqhttp#604]
**环境信息**
go-cqhttp版本: v0.9.39，往期版本也存在此问题
运行环境: windows-amd64
连接方式: 正向 WS
使用协议: iPad

**bug内容**
如果发送内容为图片+文本，则在 PC QQ 上会显示错位，Android QQ 正常，详见图片

**复现方法**
![图片](https://user-images.githubusercontent.com/31783875/106420777-4c207680-6496-11eb-9705-6306badd23f2.png)

**Comment by sam01101** [comment]
![image](https://user-images.githubusercontent.com/25792361/106437209-feb10300-64af-11eb-95a6-2ea31828f6b7.png)
复现了, 手机看没有问题

**Comment by Mrs4s** [comment]
这个问题是QQ解析的错误, 官方是会在 `reply` 和实际信息之间增加一个空格, 下个版本我会处理下
