### ISSUE TITLE
使用反向HTTP POST返回值为空

### ISSUE THREAD

**Issue by AptS-1547** [Mrs4s/go-cqhttp#607]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.39-fix1
运行环境: Windows Server 2016 x64
连接方式: 反向HTTP POST
使用协议: iPad

**bug内容**
在使用go-cqhttp反向HTTP POST时，发现POST给PHP的值为空

**复现方法**
使用反向HTTP POST发送给PHP，并把POST的值写入文件，打开文件发现为空白
![QQ20210202-0](https://user-images.githubusercontent.com/60606821/106570750-421f7600-6571-11eb-815b-158bf5871374.png)

**Comment by mnixry** [comment]
是不是应该用
```php
json_decode($_POST)
```

**Comment by scjtqs** [comment]
请使用 ` $content = file_get_contents('php://input');`

**Comment by AptS-1547** [comment]
用了decode还是没有消息

**Comment by scjtqs** [comment]
php处理raw的post请求，没法用 $_POST的

**Comment by AptS-1547** [comment]
好的谢谢（那我先写作业去了

**Comment by AptS-1547** [comment]
但是为啥返回的信息中没有消息内容
