### ISSUE TITLE
ws心跳报错

### ISSUE THREAD

**Issue by shfeat** [Mrs4s/go-cqhttp#608]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: 
运行环境: 
连接方式: 
使用协议: 

**bug内容**
请在这里详细描述bug的内容

**复现方法**
请在这里分步骤的描述如何复现这个bug
![image](https://user-images.githubusercontent.com/10511524/106576656-62066800-6578-11eb-8b9d-586605d2bf4b.png)
心跳报错，status字段怎么变结构体了？

**Comment by sam01101** [comment]
https://docs.go-cqhttp.org/api/#获取状态
![image](https://user-images.githubusercontent.com/25792361/106599066-858adc00-6593-11eb-97e5-755790f748bd.png)
![image](https://user-images.githubusercontent.com/25792361/106599082-89b6f980-6593-11eb-89b5-c044f27df53b.png)

**Comment by Mrs4s** [comment]
心跳的 `status` 字段同 `get_status` API返回值
