### ISSUE TITLE
[CQ:image]发送问题

### ISSUE THREAD

**Issue by remiliacn** [Mrs4s/go-cqhttp#61]
**环境信息**
go-cqhttp版本: v0.9.10
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
使用CQ码[CQ:image]发送图片，发送失败（体现形式为已plain text的方式发布）

**复现方法**
发送的CQ码：
`[CQ:image,file=9270C3EED22819E3CF947CF02913926F.jpg,url=https://c2cpicdw.qpic.cn/offpic_new/634915227//634915227-1623552237-9270C3EED22819E3CF947CF02913926F/0?term=2]`

在发送时，图片文件不存在（不在`./data/images`目录下），但是URL中的图片有效且可以通过复制到浏览器的方法打开显示。

**Comment by remiliacn** [comment]
这个发生情况是因为在CQ还活着的时候，我机器人有个语料记录的功能，有人加了一个语料的回复是回复一张图片，然后机器人就记下来了。今天有人触发了那个语料，文件虽然已经不在了，但是我看了一下URL里面的这张图片还是能打开显示的。

**Comment by Mrs4s** [comment]
请使用[CQ:image,file=https://c2cpicdw.qpic.cn/offpic_new/634915227//634915227-1623552237-9270C3EED22819E3CF947CF02913926F/0?term=2]发送, 或者将原CQ的.cqimg文件复制到 `data/images` 文件夹

**Comment by Mrs4s** [comment]
这部分后续版本会优化下
