### ISSUE TITLE
图片发送失败 显示para error

### ISSUE THREAD

**Issue by GLANAX** [Mrs4s/go-cqhttp#612]
发送显示para error然后就是提示被风控了
也可能是我自身问题

**Comment by AptS-1547** [comment]
有可能是风控了（很大可能

**Comment by GLANAX** [comment]
> 有可能是风控了（很大可能

刚刚看了一下 提示的不是风控 是消息为空
手机协议
go-cqhttp-v0.9.39-fix1-windows-386.exe

**Comment by GLANAX** [comment]
![SAP6(}_MF_(~ I9 J__RD%U](https://user-images.githubusercontent.com/61342380/106844362-4c618180-66e3-11eb-820a-c3afa7e38a55.png)

**Comment by AptS-1547** [comment]
文件选对了没（

**Comment by GLANAX** [comment]
=
![a](https://user-images.githubusercontent.com/61342380/106844706-386a4f80-66e4-11eb-8039-2877e3be9dd0.png)

**Comment by GLANAX** [comment]
> 文件选对了没（

可能是我的问题 不会上传文件

**Comment by YumeMichi** [comment]
图片cq部分的代码贴一下

**Comment by GLANAX** [comment]
> 图片cq部分的代码贴一下

我用的是Base64编码 [CQ:image,url=base64://xxx]

**Comment by sam01101** [comment]
我目前使用Png转Base64，也没发现使用有问题
顺带一提是二维码

**Comment by YumeMichi** [comment]
> 我目前使用Png转Base64，也没发现使用有问题
> 顺带一提是二维码

你那边用的是file还是url

**Comment by sam01101** [comment]
> > 我目前使用Png转Base64，也没发现使用有问题
> > 顺带一提是二维码
> 
> 你那边用的是file还是url

建议都用`file`

**Comment by GLANAX** [comment]
> > > 我目前使用Png转Base64，也没发现使用有问题
> > > 顺带一提是二维码
> > 
> > 
> > 你那边用的是file还是url
> 
> 建议都用`file`

用file正常了 谢谢  我没注意到
