### ISSUE TITLE
求问怎么在树莓派 设置成开机自启动啊？

### ISSUE THREAD

**Issue by c834482351** [Mrs4s/go-cqhttp#613]

**Comment by sam01101** [comment]
外部链接: https://www.cnblogs.com/downey-blog/p/10473939.html

**Comment by Ink-33** [comment]
在网上搜索systemd使用教程或者自己编写守护程序

**Comment by c834482351** [comment]
谢谢各位

**Comment by sam01101** [comment]
分钟内结束话题(

**Comment by c834482351** [comment]
> 1分钟内结束话题(

我试试看 我的是树莓派 在 home/pi/cqhttp 里面 该这么添加啊

**Comment by sam01101** [comment]
别问了, 我也是树莓派

因为太懒所以装了宝塔(

**Comment by sam01101** [comment]
![image](https://user-images.githubusercontent.com/25792361/106851312-f562a900-66f0-11eb-8252-a4dce6ec5180.png)

这个是路径, 修改这个就可以了
往里面添加指令

**Comment by c834482351** [comment]
> ![image](https://user-images.githubusercontent.com/25792361/106851312-f562a900-66f0-11eb-8252-a4dce6ec5180.png)
> 
> 这个是路径, 修改这个就可以了
> 往里面添加指令

好的 我试试

**Comment by Ink-33** [comment]
宝塔用计划任务那不是一下搞定（

**Comment by c834482351** [comment]
> > ![image](https://user-images.githubusercontent.com/25792361/106851312-f562a900-66f0-11eb-8252-a4dce6ec5180.png)
> > 这个是路径, 修改这个就可以了
> > 往里面添加指令
> 
> 好的 我试试

faststart 是什么意思

**Comment by sam01101** [comment]
> 宝塔用计划任务那不是一下搞定（

不行的, 你必须自启动
_计划任务会导致重复执行_

**Comment by sam01101** [comment]
> > > ![image](https://user-images.githubusercontent.com/25792361/106851312-f562a900-66f0-11eb-8252-a4dce6ec5180.png)
> > > 这个是路径, 修改这个就可以了
> > > 往里面添加指令
> > 
> > 
> > 好的 我试试
> 
> faststart 是什么意思

跳过前五秒倒数, 直接登录

**Comment by c834482351** [comment]
> > > > ![image](https://user-images.githubusercontent.com/25792361/106851312-f562a900-66f0-11eb-8252-a4dce6ec5180.png)
> > > > 这个是路径, 修改这个就可以了
> > > > 往里面添加指令
> > > 
> > > 
> > > 好的 我试试
> > 
> > 
> > faststart 是什么意思
> 
> 跳过前五秒倒数, 直接登录

我就是这么设置的但是没启动啊

**Comment by c834482351** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/25792361/106851312-f562a900-66f0-11eb-8252-a4dce6ec5180.png)
> > > > > 这个是路径, 修改这个就可以了
> > > > > 往里面添加指令
> > > > 
> > > > 
> > > > 好的 我试试
> > > 
> > > 
> > > faststart 是什么意思
> > 
> > 
> > 跳过前五秒倒数, 直接登录
> 
> 我就是这么设置的但是没启动啊

![QQ截图20210204140607](https://user-images.githubusercontent.com/44868578/106852005-41621d80-66f2-11eb-8187-e2d973f10faa.png)

**Comment by sam01101** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/25792361/106851312-f562a900-66f0-11eb-8252-a4dce6ec5180.png)
> > > > > > 这个是路径, 修改这个就可以了
> > > > > > 往里面添加指令
> > > > > 
> > > > > 
> > > > > 好的 我试试
> > > > 
> > > > 
> > > > faststart 是什么意思
> > > 
> > > 
> > > 跳过前五秒倒数, 直接登录
> > 
> > 
> > 我就是这么设置的但是没启动啊
> 
> ![QQ截图20210204140607](https://user-images.githubusercontent.com/44868578/106852005-41621d80-66f2-11eb-8187-e2d973f10faa.png)

你确定`go-cqhttp`是你的执行档了吗？
名字可别错了

忘记提醒了, 这个如果需要设置成后台需要添加`&`

举例:
`home/pi/cqhttp/go-cqhttp faststart &`

**Comment by c834482351** [comment]
> > > > > > > ![image](https://user-images.githubusercontent.com/25792361/106851312-f562a900-66f0-11eb-8252-a4dce6ec5180.png)
> > > > > > > 这个是路径, 修改这个就可以了
> > > > > > > 往里面添加指令
> > > > > > 
> > > > > > 
> > > > > > 好的 我试试
> > > > > 
> > > > > 
> > > > > faststart 是什么意思
> > > > 
> > > > 
> > > > 跳过前五秒倒数, 直接登录
> > > 
> > > 
> > > 我就是这么设置的但是没启动啊
> > 
> > 
> > ![QQ截图20210204140607](https://user-images.githubusercontent.com/44868578/106852005-41621d80-66f2-11eb-8187-e2d973f10faa.png)
> 
> 你确定`go-cqhttp`是你的执行档了吗？
> 名字可别错了
> 
> 忘记提醒了, 这个如果需要设置成后台需要添加`&`
> 
> 举例:
> `home/pi/cqhttp/go-cqhttp faststart &`

我试了试 还是不行啊
![我0](https://user-images.githubusercontent.com/44868578/106871402-29e45e00-670d-11eb-8481-867508c8cd15.png)

**Comment by sam01101** [comment]
> > > > > > > > ![image](https://user-images.githubusercontent.com/25792361/106851312-f562a900-66f0-11eb-8252-a4dce6ec5180.png)
> > > > > > > > 这个是路径, 修改这个就可以了
> > > > > > > > 往里面添加指令
> > > > > > > 
> > > > > > > 
> > > > > > > 好的 我试试
> > > > > > 
> > > > > > 
> > > > > > faststart 是什么意思
> > > > > 
> > > > > 
> > > > > 跳过前五秒倒数, 直接登录
> > > > 
> > > > 
> > > > 我就是这么设置的但是没启动啊
> > > 
> > > 
> > > ![QQ截图20210204140607](https://user-images.githubusercontent.com/44868578/106852005-41621d80-66f2-11eb-8187-e2d973f10faa.png)
> > 
> > 
> > 你确定`go-cqhttp`是你的执行档了吗？
> > 名字可别错了
> > 忘记提醒了, 这个如果需要设置成后台需要添加`&`
> > 举例:
> > `home/pi/cqhttp/go-cqhttp faststart &`
> 
> 我试了试 还是不行啊
> ![我0](https://user-images.githubusercontent.com/44868578/106871402-29e45e00-670d-11eb-8481-867508c8cd15.png)

https://blog.csdn.net/liuyanfeier/article/details/62422742

**Comment by sam01101** [comment]
你要是再不行就去 #597

**Comment by c834482351** [comment]
> 你要是再不行就去 #597

谢谢了老铁
