### ISSUE TITLE
发送语音后，无法发送文本消息

### ISSUE THREAD

**Issue by wdvxdr1123** [Mrs4s/go-cqhttp#62]
**环境信息**
go-cqhttp版本: v0.9.15
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
发送语音后，无法发送文本消息，只能发送语音消息

**复现方法**
通过一个命令，同时发送一段文本消息和语音消息
一段时间后，只能接受到语音消息
正常情况:
![bug1](https://user-images.githubusercontent.com/34832863/89723803-8e0fb900-da2d-11ea-97cc-65970a7e3411.png)
异常情况:
![bug2](https://user-images.githubusercontent.com/34832863/89723805-90721300-da2d-11ea-8963-4dc7a56b6b78.png)

**Comment by Mrs4s** [comment]
请问是在同一条消息同时发送语音和文本还是分多次发送的?

**Comment by wdvxdr1123** [comment]
分多次发送

**Comment by Mrs4s** [comment]
![test](https://user-images.githubusercontent.com/12137562/89723904-16428e00-da2f-11ea-9ba3-c71aef8207d6.jpg)
我这边复现失败了，可能是什么边界情况，请再观察一下

**Comment by wdvxdr1123** [comment]
这个bug要发送很久才会出现，我先凑合用下吧

**Comment by wordgao** [comment]
从之前的几个版本就出现了这个问题的，我已经反馈了好几个版本类似的相同问题，间歇性的出现，ws连接不上报数据，有时候正常的没话说，有时候让人有点无厘头。。
可以试试 v0.1.9.10 或 v0.1.9.12的版本，也许会正常一点，测试的时候不会出现间歇性的问题。
v0.1.9.11版本基本上不能用，这个程序报错，基本上用不了几分钟就会自动退出。

**Comment by wdvxdr1123** [comment]
这个bug我又遇到了，经过测试，并不是不能发送文本，而是只能发送文本大小为2字节的文本

**Comment by Mrs4s** [comment]
目前看来应该是风控因素#38， 目前看来换到新的平台需要挂机一周才能解除风控

**Comment by wordgao** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        加下我Q 257386 可以实现ws无上报信息的状态，谢谢。
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                wordgao
                            
                    
                        
                            
                                    wordgao@gmail.com
                            
                        
                
            
        
        
    
    在2020年8月9日 13:28，wdvxdr1123<notifications@github.com> 写道： 



Closed #62.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
