### ISSUE TITLE
[feature] 跳过上传到群/个人QQ, 直接上传(图片/语音/短视频)

### ISSUE THREAD

**Issue by sam01101** [Mrs4s/go-cqhttp#622]
灵感来自:
https://github.com/project-mirai/mirai-api-http/blob/master/docs/API.md#图片文件上传
![image](https://user-images.githubusercontent.com/25792361/107231300-16156080-6a5b-11eb-9d4e-3511ffbe7fb3.png)

https://github.com/project-mirai/mirai-api-http/blob/master/docs/API.md#语音文件上传
![image](https://user-images.githubusercontent.com/25792361/107231329-20375f00-6a5b-11eb-8fba-ee64d1fbf520.png)

直接上传到服务器而不是聊天室

需要解决的问题: 如何直接上传到服务器而不用
`groupCode`
https://github.com/Mrs4s/MiraiGo/blob/800bf525ed0e91f0b292c07d6d51c46fa98ee010/client/image.go#L28
`target`
https://github.com/Mrs4s/MiraiGo/blob/800bf525ed0e91f0b292c07d6d51c46fa98ee010/client/image.go#L121

**Comment by fengx1a0** [comment]
所以有无无视文件类型的功能，直接文件任意上传

**Comment by sam01101** [comment]
> 所以有无无视文件类型的功能，直接文件任意上传

You're so funny that asking at a feature request

**Comment by sam01101** [comment]
> 所以有无无视文件类型的功能，直接文件任意上传

群文件上传已经有了, 请看文档

**Comment by Mrs4s** [comment]
> 所以有无无视文件类型的功能，直接文件任意上传

目前除了群文件上传接口外都有格式检查, 不能实现任意格式文件上传的

**Comment by Mrs4s** [comment]
这个功能用途并不多，短时间应该不会做

**Comment by CL-Jeremy** [comment]
> 这个功能用途并不多，短时间应该不会做

这个功能我非常希望能加入。目前是 Mirai 用户，我的机器人在发送所有媒体文件时都会执行四遍预上传（并且因为 Mirai 的私信不使用 Highway，我会将媒体作为群图片上传，之后再秒传到实际目标），四遍都不成功的话会替换为自定义的占位符（如：包含来源地址或简介），同时在合并 segment 后（Mirai 称含有多个 segment 的消息为 MessageChain）同样会发送四遍，最后 fallback 为文本。这样作搬运类用途使用时，可以灵活控制每个发送失败的部分应该如何进行后续处理，确保可以及时转发最大限度保持完整度的消息（经常会碰到的情况：puppeteer 截图发送失败但网络图片成功，反之亦然；从短视频制作的 GIF 动图发送失败（如文件过大）；个别情况下遇到服务器抽风无论如何也无法发出图片）。

个人粗略计算，这一年多来从我的日本机房使用 Mirai 发送，超过 4 MB 的图片至少有 40% 需要三次上传以上才可以发送成功，一次就成功的概率相当之低，甚至最后上传成功、发送成功后也有一定概率发生图片失效（概率相对较低，当然这是谁也没办法的事情）。如果能够实现单独上传功能的话，至少在失败重试方面可以更好应对服务器问题了。

诚然，接口设计方面如何取舍是很大的问题，至少这完全不符合 OneBot 的逻辑，使用第三方 SDK 封装就会很突兀。当然，用来封装的话，可以不暴露相关接口给终端用户进行显式调用，而是仅供第三方 SDK 底层实现相关功能（如：可以用来支持对 altText 和重试策略的自主实现，供进阶用户手动 override——虽然这不符合跨平台的思路，但实际上需要和服务器斗智斗勇的也没有其他平台了，苦笑）。

当然，如果有意直接将“媒体文件上传失败重试策略”单独拿出来，提供精细化调节选项（如：进一步扩展 CQ 码并加入 alttext 可选字段，在配置文件中提供更多延时方面的选项），大概会是个更好的办法（隔离度更高，API 变动更少，但相对地，使用范围也变窄）。

**Comment by sam01101** [comment]
> > 这个功能用途并不多，短时间应该不会做
> 
> 这个功能我非常希望能加入。目前是 Mirai 用户，我的机器人在发送所有媒体文件时都会执行四遍预上传（并且因为 Mirai 的私信不使用 Highway，我会将媒体作为群图片上传，之后再秒传到实际目标），四遍都不成功的话会替换为自定义的占位符（如：包含来源地址或简介），同时在合并 segment 后（Mirai 称含有多个 segment 的消息为 MessageChain）同样会发送四遍，最后 fallback 为文本。这样作搬运类用途使用时，可以灵活控制每个发送失败的部分应该如何进行后续处理，确保可以及时转发最大限度保持完整度的消息（经常会碰到的情况：puppeteer 截图发送失败但网络图片成功，反之亦然；从短视频制作的 GIF 动图发送失败（如文件过大）；个别情况下遇到服务器抽风无论如何也无法发出图片）。
> 
> 个人粗略计算，这一年多来从我的日本机房使用 Mirai 发送，超过 4 MB 的图片至少有 40% 需要三次上传以上才可以发送成功，一次就成功的概率相当之低，甚至最后上传成功、发送成功后也有一定概率发生图片失效（概率相对较低，当然这是谁也没办法的事情）。如果能够实现单独上传功能的话，至少在失败重试方面可以更好应对服务器问题了。
> 
> 诚然，接口设计方面如何取舍是很大的问题，至少这完全不符合 OneBot 的逻辑，使用第三方 SDK 封装就会很突兀。当然，用来封装的话，可以不暴露相关接口给终端用户进行显式调用，而是仅供第三方 SDK 底层实现相关功能（如：可以用来支持对 altText 和重试策略的自主实现，供进阶用户手动 override——虽然这不符合跨平台的思路，但实际上需要和服务器斗智斗勇的也没有其他平台了，苦笑）。
> 
> 当然，如果有意直接将“媒体文件上传失败重试策略”单独拿出来，提供精细化调节选项（如：进一步扩展 CQ 码并加入 alttext 可选字段，在配置文件中提供更多延时方面的选项），大概会是个更好的办法（隔离度更高，API 变动更少，但相对地，使用范围也变窄）。

妈耶长文

行行行，你怎么有诚意我也不好说什么了

**Comment by sam01101** [comment]
_Assigned to @sam01101 by @sam01101, code `single_upload`_
Feature: API Adding
- `upload_image`
- `upload_voice`
- `upload_short_video`

go-cqhttp Impl: https://github.com/Mrs4s/go-cqhttp/pull/859

**Comment by sam01101** [comment]
DFFDIOSGONIOHSERHLUHIUBIUIW5789NYWVVUIV58PWYCNPY8V5SNUVHV86B7DR5NYDBYVSYDEFRTGYHUIKOLP;L'LKJHGFD4EFRTGYHUMIO,KP.L/;0-OIUOMRYETC3245E6TG78YHU8,KOPL.KIJU78Y67T54ED5FRTGBYHUJI,P.L,P;KOJU543W2Q1Q3SWEDTRYTFGYIUHOIPKO[P-0[0P987YTFRDESWTEDFRTGYUIHOIJMPO,KP./[/O0IKJNMK,P.L[;'=-P0O9IU8HYGT76FR5DE43W23SECVBYGUNHIJMK,OGARW3ETPOKO-[=O-'P;I.LJ,KH VNBCGDFVSSETDRYFHYXVZSW33WRZSWA32EAWFXSTEGBUN 8PL9U,IHKJM XDSAWSEDRFVGFDSEWSEDEW2QWWASEDRTFGYHJKJUHIJKOPL;[LKO-[=;LPKO[;LP'
;LP[;.,MLKJIOKLM,NKJBHUJIKM,LNBJHVGYHBJ VGDRFCFXDSRDEWSXSZAWQWSXDCDZSAWSXDCFVGN MNBHNJM JIKOL.;,LP[;'LPOP;

**Comment by sam01101** [comment]
草, 不小心发出去了
刚在擦键盘
