### ISSUE TITLE
CQ码链接分享和自定义音乐的图片无法显示

### ISSUE THREAD

**Issue by liaoyinuo** [Mrs4s/go-cqhttp#625]
尝试多次仍无法使两者正确显示图片
不排除是我输入的链接格式问题

已知：
1.加http或https前缀的图片于上两者均无法显示
2.不加前缀的图片在自定义音乐会显示一个灰色底板，但加载不出来，而在链接分享仍未无法显示
3.已尝试jpg,png格式，已尝试更改图片分辨率，均不奏效

另，如果可以的话，希望文档中尽量给出包含可选项的示例

**Comment by Ink-33** [comment]
请问您是如何构建CQ码的？我这边无法复现

**Comment by liaoyinuo** [comment]
1.[CQ:music,type=custom,url=http://baidu.com,audio=http://baidu.com/1.mp3,title=音乐标题,image=http://i2.hdslb.com/bfs/face/e4a96182845f5fd28124830971d5a9319ebb4a6f.jpg]

![1](https://user-images.githubusercontent.com/55882882/107456320-f1200b00-6b8a-11eb-87c3-b609b27b1201.jpg)

2.[CQ:music,type=custom,url=http://baidu.com,audio=http://baidu.com/1.mp3,title=音乐标题,image=i2.hdslb.com/bfs/face/e4a96182845f5fd28124830971d5a9319ebb4a6f.jpg]

![2](https://user-images.githubusercontent.com/55882882/107456338-fbdaa000-6b8a-11eb-9043-c4e3af45d6c0.jpg)

**Comment by Mrs4s** [comment]
这个应该是tx的限制, QQ只会显示白名单域名下的图片

**Comment by liaoyinuo** [comment]
刚刚进行测试，网易云和QQ音乐域名下的图片均不能使用
恳请开发者给一个能显示图片的CQ码例子

**Comment by YumeMichi** [comment]
试了一下 手机上可以正常显示图片

**Comment by FLRSCN** [comment]
我的解决方法是先把封面发到某个群里，获取CQ:Image里的url作为音乐的图片url，这样手机和电脑上都能正常显示
