### ISSUE TITLE
QQ礼物改版了，原来的CQ码不能用了

### ISSUE THREAD

**Issue by SlightDust** [Mrs4s/go-cqhttp#626]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.40
运行环境: centos7.6
连接方式: 反向ws
使用协议: iPad

**bug内容**
QQ礼物改版了，原来gift的CQ码无法使用，若强行使用的话QQ会显示赠送0朵鲜花
![% UKGQF6S2 H1ZSK`JBJZDE](https://user-images.githubusercontent.com/53001305/107425264-b81b7280-6b59-11eb-8604-df365582cd39.jpg)

**复现方法**
发送礼物均会出现

**Comment by wdvxdr1123** [comment]
目前QQ没有免费礼物了，应该删除 `[CQ:gift]` 的支持
