### ISSUE TITLE
可以收到自己的群聊消息吗

### ISSUE THREAD

**Issue by dlytang** [Mrs4s/go-cqhttp#627]
请问可以收到机器人自己在群里发的消息吗？

**Comment by daofeng2015** [comment]
> 请问可以收到机器人自己在群里发的消息吗？

文档里有说明.机器人自己群里发信息早就支持了

**Comment by dlytang** [comment]
> > 请问可以收到机器人自己在群里发的消息吗？
> 
> 文档里有说明.机器人自己群里发信息早就支持了

可是机器人在群里发消息，控制台并没有输出，需要配置什么嘛，看了一下文档也没有找到

**Comment by daofeng2015** [comment]
> > > 请问可以收到机器人自己在群里发的消息吗？
> > 
> > 
> > 文档里有说明.机器人自己群里发信息早就支持了
> 
> 可是机器人在群里发消息，控制台并没有输出，需要配置什么嘛，看了一下文档也没有找到

https://docs.go-cqhttp.org/api/#%E5%8F%91%E9%80%81%E7%BE%A4%E6%B6%88%E6%81%AF 这个就是发消息的http-api

**Comment by dlytang** [comment]
> > > > 请问可以收到机器人自己在群里发的消息吗？
> > > 
> > > 
> > > 文档里有说明.机器人自己群里发信息早就支持了
> > 
> > 
> > 可是机器人在群里发消息，控制台并没有输出，需要配置什么嘛，看了一下文档也没有找到
> 
> https://docs.go-cqhttp.org/api/#%E5%8F%91%E9%80%81%E7%BE%A4%E6%B6%88%E6%81%AF 这个就是发消息的http-api

啊 不是这意思，比如机器人是IPAD端，然后我登录手机端发个群消息，机器人能收到嘛

**Comment by Mrs4s** [comment]
在做了

**Comment by dlytang** [comment]
> 在做了

嗷嗷 感谢

**Comment by sam01101** [comment]
实际上没有，因为指令都直接被忽略了，那么怎么接收（
如果要加接收自己信息就会导致群和私聊一起来

**Comment by Mrs4s** [comment]
已支持
