### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by fengx1a0** [Mrs4s/go-cqhttp#629]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: 0.9.40
运行环境: Linux
连接方式: 正常连接
使用协议: iPad

**bug内容**
无法登录，尝试了三个qq号，其中一个新创建的qq，一个12年的三无绑定老qq

**复现方法**
直接登录
三个qq正确填入qq号密码后相同报错
![Y965XBIC`IQNG_QH(7P4504](https://user-images.githubusercontent.com/74698099/107654843-fd58b500-6cbd-11eb-9371-6d9e99cfa288.png)

**Comment by sam01101** [comment]
请检查号码是否可以正常登录

**Comment by fengx1a0** [comment]
师傅新年快乐，明明在跨年还来打扰你，师傅可以试一下3634964319 密码exa2364644233
祝师傅牛年快乐！

**Comment by Ink-33** [comment]
请使用官方客户端检查能否登录。
另：即使是正常账号也会因异常登录导致临时冻结

**Comment by fengx1a0** [comment]
官方客户端具体指哪个客户端，指ipad上官方app吗

**Comment by sam01101** [comment]
> 师傅新年快乐，明明在跨年还来打扰你，师傅可以试一下3634964319 密码exa2364644233
> 祝师傅牛年快乐！

![N{AIQY}~771F7LP($3EAMNS](https://user-images.githubusercontent.com/25792361/107656238-ebc3dd00-6cbe-11eb-927d-17b26f46c90a.jpg)

为什么你可以光明正大的把QQ账号和密码发出来

**Comment by Ink-33** [comment]
> 官方客户端具体指哪个客户端，指ipad上官方app吗

什么端都行，只要是QQ官方的就行

**Comment by fengx1a0** [comment]
因为是新qq，啥都没

**Comment by fengx1a0** [comment]
> > 官方客户端具体指哪个客户端，指ipad上官方app吗
> 
> 什么端都行，只要是QQ官方的就行

嗯，新qq和近期创建的qq号都需要手机验证码或者扫码登录，但是我的自己的老qq不需要扫码，还是登不上

**Comment by fengx1a0** [comment]
我用我一直用的qq登录还是不行，我的配置全是默认配置

**Comment by sam01101** [comment]
> 我用我一直用的qq登录还是不行，我的配置全是默认配置

官方QQ是否可以登录? 如果是, 那么理论上也可以登录go-cqhttp

**Comment by fengx1a0** [comment]
我ios的手机qq和windows的TIM都可以正常登录这三个qq，师傅可以试一下我上面给的那个号，验证码直接发给我我评论给你

**Comment by Ink-33** [comment]
尝试更换gocq的登录协议

**Comment by fengx1a0** [comment]
指把ipad换成其他协议尝试吗？我去搞下

**Comment by sam01101** [comment]
@fengx1a0 
https://ti.qq.com/safe/verify?_wv=2&_wwv=128&envfrom=double-check&uin=3634964319&sig=a6VQLurIJ37LhZnA7SKeC7LhBOJ5rFw6H92k6UENqPvFzVLMlz5x88muLFyBCh6bYwTcoeeTeV700o2dzs5dFYLK%2FRIoiCO6wYI5HIbkhXI%3D

请帮忙验证一下

**Comment by fengx1a0** [comment]
> @fengx1a0
> https://ti.qq.com/safe/verify?_wv=2&_wwv=128&envfrom=double-check&uin=3634964319&sig=a6VQLurIJ37LhZnA7SKeC7LhBOJ5rFw6H92k6UENqPvFzVLMlz5x88muLFyBCh6bYwTcoeeTeV700o2dzs5dFYLK%2FRIoiCO6wYI5HIbkhXI%3D
> 
> 请帮忙验证一下

![Y965XBIC`IQNG_QH(7P4504](h
![CUTYQA$ {(M047MN0V0)7 7](https://user-images.githubusercontent.com/74698099/107657784-748f4880-6cc0-11eb-971d-51f017aece5b.png)
ttps://user-images.githubusercontent.com/74698099/107657759-6ccfa400-6cc0-11eb-9928-feb9557dcb94.png)

**Comment by fengx1a0** [comment]
不支持滑动验证，啊这

**Comment by sam01101** [comment]
![image](https://user-images.githubusercontent.com/25792361/107657829-7fe27400-6cc0-11eb-8871-16e765eb40dc.png)

我这边也可以正常登录, 真的无法复现
![N4XUH@ KHCY(T2 `@T EU T](https://user-images.githubusercontent.com/25792361/107657877-8c66cc80-6cc0-11eb-853e-f32df46872d9.jpg)

**Comment by fengx1a0** [comment]
我靠

**Comment by fengx1a0** [comment]
不是，难道是我docker的原因？不可能的啊，我内网都是最纯净的

**Comment by sam01101** [comment]
[device.zip](https://github.com/Mrs4s/go-cqhttp/files/5966424/device.zip)

我这边可以给你我验证成功的device.json
您可以试一试能不能删除旧的然后贴上然后尝试登录

**Comment by Ink-33** [comment]
建议重新整个device.json，顺便把你config贴出来看看

**Comment by fengx1a0** [comment]
谢谢hxd，我马上搞

**Comment by fengx1a0** [comment]
{
	"uin": ,
	"password": "",
	"encrypt_password": false,
	"password_encrypted": "",
	"enable_db": true,
	"access_token": "",
	"relogin": {
		"enabled": true,
		"relogin_delay": 3,
		"max_relogin_times": 0
	},
	"_rate_limit": {
		"enabled": false,
		"frequency": 1,
		"bucket_size": 1
	},
	"ignore_invalid_cqcode": false,
	"force_fragmented": false,
	"heartbeat_interval": 0,
	"http_config": {
		"enabled": true,
		"host": "0.0.0.0",
		"port": 10000,
		"timeout": 0,
		"post_urls": {
			"robot:9999": "HexQBot"
		}
	},
	"ws_config": {
		"enabled": false,
		"host": "0.0.0.0",
		"port": 10000
	},
	"ws_reverse_servers": [
		{
			"enabled": false,
			"reverse_url": "ws://robot:9999",
			"reverse_api_url": "ws://robot:9999",
			"reverse_event_url": "ws://robot:9999",
			"reverse_reconnect_interval": 3000
		}
	],
	"post_message_format": "string",
	"use_sso_address": false,
	"debug": false,
	"log_level": "",
	"web_ui": {
		"enabled": true,
		"host": "0.0.0.0",
		"web_ui_port": 9999,
		"web_input": false
	}
}

**Comment by sam01101** [comment]
请问更换`device.json`后是否可以正常登录?

**Comment by fengx1a0** [comment]
> [device.zip](https://github.com/Mrs4s/go-cqhttp/files/5966424/device.zip)
> 
> 我这边可以给你我验证成功的device.json
> 您可以试一试能不能删除旧的然后贴上然后尝试登录

师傅牛啊，竟然好了，我直接跪倒

**Comment by fengx1a0** [comment]
师傅怎么做到的啊，刚刚师傅拿我号做了什么验证做到的

**Comment by sam01101** [comment]
![NH14H`B3GF_~`QB50$9D9GX](https://user-images.githubusercontent.com/25792361/107659226-e3b96c80-6cc1-11eb-9d51-6f9040034316.jpg)
有点丢人, 不过我建议你还是赶紧`Close Issue`了事

**Comment by fengx1a0** [comment]
应该不是配置的原因吧，我本地有备份我再去复现下

**Comment by fengx1a0** [comment]
别吧，刚刚师傅弄的那个安全验证是怎么搞的，我手机扫了下就突然能用了

**Comment by Ink-33** [comment]
...

**Comment by sam01101** [comment]
> 别吧，刚刚师傅弄的那个安全验证是怎么搞的，我手机扫了下就突然能用了

不, 这是为了你好, 你最好趁现在还没人笑话的时候关issue

**Comment by fengx1a0** [comment]
啊这，那能教下刚刚师傅咋搞的那个一串网址的验证，不能我就关issue了

**Comment by sam01101** [comment]
> 啊这，那能教下刚刚师傅咋搞的那个一串网址的验证，不能我就关issue了

https://docs.go-cqhttp.org/faq/slider.html

**Comment by fengx1a0** [comment]
谢谢师傅，还有10多分种就跨年了，希望师傅新的一年身体健康，牛气满满！

**Comment by Ink-33** [comment]
关issue吧
![-1e3cad4365622802.jpg](https://user-images.githubusercontent.com/51873347/107660351-1f086b00-6cc3-11eb-96ab-6e4d36c2d6a6.jpg)

**Comment by fengx1a0** [comment]
那个，我直接账号密码怎么办，直接暴露在公网上确实不太行

**Comment by fengx1a0** [comment]
能删，那没事了

**Comment by Ink-33** [comment]
> 那个，我直接账号密码怎么办，直接暴露在公网上确实不太行

你可以把那条回复删了啊，然后改密码

**Comment by fengx1a0** [comment]
singlefile已保存，今天有幸能和两位师傅叨扰，2020收尾血赚
![1](https://user-images.githubusercontent.com/74698099/107660898-b1a90a00-6cc3-11eb-8b32-fb6e8fc98e15.jpg)

**Comment by Ink-33** [comment]
> 能删，那没事了

我建议你还是赶快去改一下，gocq每一个watcher都收到了包含账密的邮件，不然哪这么快就有来解决issue的老哥（）

**Comment by fengx1a0** [comment]
啊？gayhub协同开发这么离谱？我马上就去改下

**Comment by fengx1a0** [comment]
有无大师傅给个扣扣好友嘛，我扣扣1978893157，想和大佬贴贴，我是个非常靠谱的dd头子
![2](https://user-images.githubusercontent.com/74698099/107661829-9be81480-6cc4-11eb-8f68-f93491d82b06.jpg)

**Comment by Ink-33** [comment]
> 有无大师傅给个扣扣好友嘛，我扣扣1978893157，想和大佬贴贴，我是个非常靠谱的dd头子
> ![2](https://user-images.githubusercontent.com/74698099/107661829-9be81480-6cc4-11eb-8f68-f93491d82b06.jpg)
> 

你可以探索一下gocq源码然后找到交流群群号(
> 注：有两个群

**Comment by Yukari316** [comment]
![} }V}2 Y%SP~C%9ROZ_FEYX](https://user-images.githubusercontent.com/7535224/107666257-482bfa00-6cc9-11eb-82bc-b9baa854cedf.jpg)
