### ISSUE TITLE
机器人无法接收加群请求事件

### ISSUE THREAD

**Issue by hqshi** [Mrs4s/go-cqhttp#630]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: go-cqhttp-v0.9.40-windows-amd64
运行环境: win10 1904
连接方式: 反向websocket
使用协议: ipad

**bug内容**
无法收到事件:加群请求/邀请，但是可以收到其他类型的事件

**复现方法**
暂时只有群主身份的账号，加群后无论是控制台log还是Nonebot2都没有入群消息的提示
![image](https://user-images.githubusercontent.com/34450149/107771394-a8787580-6d75-11eb-9f63-2cc700989200.png)

**Comment by sam01101** [comment]
你好, 請先查看以下issue是否對你有幫助:
#359 #312 #299 #172

**Comment by hqshi** [comment]
> 你好, 請先查看以下issue是否對你有幫助:
> #359 #312 #299 #172

谢谢提示，我看了一下issue

**Comment by hqshi** [comment]
1. #359 经测试无论机器人是否审批权限都收不到消息，但是审批后的通知有消息

**Comment by sam01101** [comment]
请问如果机器人是管理员是否遇到同样的问题?

**Comment by hqshi** [comment]
Girhub的不太习惯，排版似乎有点乱。由于无法收到上报消息，因此也无法调用 #312 的审批接口。同样的，在PC QQ客户端能收到申请消息，排除被风控的可能性。
现有测试是机器人收取测试账号加群申请，与 #172 不同 加群后收到了同意加群的事件

**Comment by hqshi** [comment]
> 请问如果机器人是管理员是否遇到同样的问题?

由于测试账号有限无法准确的测试机器人身份为管理员时加群申请的结果。但是查询使用中机器人权限为管理员的群的消息记录也为发现加群申请的记录

**Comment by hqshi** [comment]
配置文件为Nonebot2提供的[配置文件](https://v2.nonebot.dev/guide/cqhttp-guide.html)。在配置中开启debug模式后加群进行测试，控制台没有展示推送相关event的事件。在相应的log文件也找不到含有requests的事件

**Comment by hqshi** [comment]
经过测试普通成员邀请群员加入时可以收到加群申请

**Comment by hqshi** [comment]
经过用户群大佬的提示和自己的测试结果发现，电脑端在线就无法收到加群申请，手机QQ端在线可以

**Comment by sam01101** [comment]
`iPad`, `Android Phone`的协议对吧？

**Comment by hqshi** [comment]
> `iPad`, `Android Phone`的协议对吧？

机器人客户端协议是'ipad',其余为QQ官方客户端
