### ISSUE TITLE
Q群CQ码@某人时，如果对方昵称带emoji时无法被at到

### ISSUE THREAD

**Issue by mengshouer** [Mrs4s/go-cqhttp#631]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本:  go-cqhttp-v0.9.40-windows-amd64
运行环境:  winserver 2019
连接方式:  反向WS
使用协议:  iPad+Android Phone

**bug内容**
Q群CQ码@某人时，如果对方昵称带emoji时无法被at到

**复现方法**
随便改个群名片带emoji，然后用[CQ:at,qq=xxx]进行at
PS: 新版QQ好像无法修改群名片添加emoji，旧版QQ可以。刚才拿旧版QQ试了一下

**Comment by sam01101** [comment]
你好, 我复现失败, 即使添加了emoji也是可以At的
请问你的Emoji是指普通的还是QQ的?

**Comment by mengshouer** [comment]
windows10的win+.唤出来的emoji

**Comment by mengshouer** [comment]
🎆🎇🧨✨🎉🎊🎃🎄🎋🎍🎎🎏🎐🎑🧧例(

**Comment by sam01101** [comment]
![Uploading image.png…]()

**Comment by sam01101** [comment]
![image](https://user-images.githubusercontent.com/25792361/107791956-87248300-6d8f-11eb-9805-007da129f089.png)
这个是Win10的Emoji, 请解释

**Comment by mengshouer** [comment]
这个@，出现的只有文字，不算@，被@的人不会受到提醒

**Comment by sam01101** [comment]
我iPad也给你截个图

**Comment by Ink-33** [comment]
> 这个@，出现的只有文字，不算@，被@的人不会受到提醒

官方客户端at有无提醒？

**Comment by sam01101** [comment]
![DHIF4LB}7 C@KJ9~PPQ`ADN](https://user-images.githubusercontent.com/25792361/107792390-0e71f680-6d90-11eb-87d9-6dfa6dcdaed0.jpg)

**Comment by mengshouer** [comment]
> > 这个@，出现的只有文字，不算@，被@的人不会受到提醒
> 
> 官方客户端at有无提醒？

看了一眼，手机客户端有消息，PCQQ看不到

**Comment by sam01101** [comment]
> > > 这个@，出现的只有文字，不算@，被@的人不会受到提醒
> > 
> > 
> > 官方客户端at有无提醒？
> 
> 看了一眼，手机客户端有消息，PCQQ看不到

我问一下, 你是不是开着界面然后发送At的?

**Comment by mengshouer** [comment]
> > > > 这个@，出现的只有文字，不算@，被@的人不会受到提醒
> > > 
> > > 
> > > 官方客户端at有无提醒？
> > 
> > 
> > 看了一眼，手机客户端有消息，PCQQ看不到
> 
> 我问一下, 你是不是开着界面然后发送At的?

啊，是我傻了，PCQQ看着没显示加粗亮底，然后有群友和我说没@到，我以为没有。实测关掉Q群会接受到@。打扰了！

**Comment by mengshouer** [comment]
再次感谢解答！
