### ISSUE TITLE
问个傻子问题

### ISSUE THREAD

**Issue by xiaowine** [Mrs4s/go-cqhttp#642]
咋获取上报数据，求各位举个栗子

**Comment by sam01101** [comment]
https://github.com/Mrs4s/go-cqhttp/issues/633
https://github.com/Mrs4s/go-cqhttp/issues/633
https://github.com/Mrs4s/go-cqhttp/issues/633
https://github.com/Mrs4s/go-cqhttp/issues/633
https://github.com/Mrs4s/go-cqhttp/issues/633

**Comment by Mrs4s** [comment]
请参考文档

**Comment by xiaowine** [comment]
> 请参考文档

我觉得我是瞎子，看了几篇都没看见

**Comment by sam01101** [comment]
> > 请参考文档
> 
> 我觉得我是瞎子，看了几篇都没看见

请仔细阅读文档
