### ISSUE TITLE
`/_send_group_notice` 貌似具有 150 字符的字数限制

### ISSUE THREAD

**Issue by Tsuk1ko** [Mrs4s/go-cqhttp#649]
**环境信息**
go-cqhttp版本: 0.9.40
运行环境: Windows
连接方式: All
使用协议: All

**bug内容**
`/_send_group_notice` 无法发送超出 150 字符的内容（1汉字算3字符），但群公告上限是 600 字
debug 模式下未见异常，日志也无异常

**复现方法**
这里提供两个达到上限的例子，多一个字符就无法发出
```
// 150 英文数字
012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789

// 50 汉字
零一二三四五六七八九零一二三四五六七八九零一二三四五六七八九零一二三四五六七八九零一二三四五六七八九
```

**Comment by Mrs4s** [comment]
可能需要更换一个发送群公告的方式

**Comment by Mrs4s** [comment]
目前使用的 `UpdateMemo` 作为底层API, 可能需要更换为群公告的HTTP接口
