### ISSUE TITLE
反向HTTP时，快速回复的at_sender字段不起作用。

### ISSUE THREAD

**Issue by Zhongren233** [Mrs4s/go-cqhttp#651]
- [ ] 我已经阅读"提问前需知 [图+文]": https://github.com/Mrs4s/go-cqhttp/issues/633

**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.40
运行环境: windows_amd64
连接方式: 反向HTTP POST
使用协议: 

**bug内容**
快速回复的at_sender字段不起作用。

**复现方法**
必定复现

```
2021-02-19 11:41:53.546  INFO 332 --- [io-23563-exec-6] m.z.e.p.s.impl.QuickReplyServiceImpl     : 收到group1097526643的讯息:/pr count 一卡
2021-02-19 11:41:53.752  INFO 332 --- [io-23563-exec-6] m.z.e.producer.controller.BotController  : {"reply":"一卡人数为:2371","at_sender":true}
```

![image](https://user-images.githubusercontent.com/62706664/108454622-a3e91b00-72a7-11eb-88c7-849cdc4b60c2.png)

不太懂如何开启debug，所以没有这方面的日志，抱歉

**Comment by Ink-33** [comment]
at_sender还没入版，你用的是正式版gocq？

**Comment by Mrs4s** [comment]
下个版本就会支持了

**Comment by Zhongren233** [comment]
> at_sender还没入版，你用的是正式版gocq？

不太了解什么意思，不过我是通过这个的快速操作看的。
目前使用的版本是0.9.40
https://github.com/howmanybots/onebot/blob/master/v11/specs/event/message.md#%E7%BE%A4%E6%B6%88%E6%81%AF

**Comment by Zhongren233** [comment]
> 下个版本就会支持了

ok，辛苦

**Comment by Mrs4s** [comment]
已支持
