### ISSUE TITLE
本地图片发送群消息失败

### ISSUE THREAD

**Issue by Mr-Gump** [Mrs4s/go-cqhttp#653]
本地文件路径有效（通过curl测试可以下载）
file:///root/mybot/plugins/lend_and_borrow/img_cache/3df5442c.png
发送消息：
[CQ:image,file=file:///root/mybot/plugins/lend_and_borrow/img_cache/3df5442c.png]
报错：
转换CQ码到MiraiGo Element时出现错误: file not found 将忽略本段CQ码.

**Comment by Mr-Gump** [comment]
补充:本地开了一个 httpserver 更改 file=http://127.0.0.1:8000/3df5442c.png  从依旧显示找不到文件
将 127.0.0.1 改为公网ip之后才可以正常访问

**Comment by Wang-Yaowu** [comment]
根据文档中表述，应该将图片文件存放于 go-cqhttp 二进制文件同级目录下的 data/images 目录中，通过相对目录的方式去读取。比如我的 go-cqhttp 存放位置为 /opt/root/cqhttp/go-cqhttp，图片存放位置为 /opt/root/cqhttp/data/images/default.jpg，这样我可以通过 [CQ:image,file=default.jpg] 来发送图片。

**Comment by Mr-Gump** [comment]
哦哦哦,原来是这样的,昨天研究了好久,多谢大佬

**Comment by Ink-33** [comment]
如果您还有其他问题欢迎您继续提问，若您没有其他问题烦请您close这个issue

**Comment by StarXinXin** [comment]
多谢大佬们，话说我研究了两天了，终于可以发出去图片了
