### ISSUE TITLE
反向WS连接出现403

### ISSUE THREAD

**Issue by raindown200709** [Mrs4s/go-cqhttp#658]
- [x] 我已经阅读"提问前需知 [图+文]": `Mrs4s/go-cqhttp/issues/633`

**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.40-fix1
运行环境: Windows Server 2016
连接方式: 反向WS

**bug内容**
<img src = 'https://ftp.bmp.ovh/imgs/2021/02/ee8d86fea2d7a453.png' />

<img src = 'https://ftp.bmp.ovh/imgs/2021/02/b3b473414d3e5185.png' />

**Comment by Ink-33** [comment]
请翻阅nonebot文档自行解决

**Comment by zhzRedstone** [comment]
5700端口？？
不是HTTP API的端口吗？

**Comment by Mrs4s** [comment]
请检查应用层的设置

**Comment by sam01101** [comment]
提示：如果使用`nonebot2`，请记得你**已经添加cqhttp container**
文档参考：https://v2.nonebot.dev/guide/getting-started.html

```python
driver = nonebot.get_driver()
driver.register_adapter("cqhttp", CQHTTPBot)
```
