### ISSUE TITLE
机器人发送的合并转发消息无法撤回

### ISSUE THREAD

**Issue by 2938137849** [Mrs4s/go-cqhttp#661]
- [ ] 我已经阅读"提问前需知 [图+文]": `Mrs4s/go-cqhttp/issues/633`

**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.38-fix1
运行环境: debian 10
连接方式: ws
使用协议: 0

**bug内容**
请在这里详细描述bug的内容
使用机器人发送的合并转发消息，无法撤回，也不会在日志中显示

**复现方法**
请在这里分步骤的描述如何复现这个bug
比如合并转发CQ码： `[CQ:node,name=测试,uin=123,content=测试]`
实际发送成功：
![image](https://user-images.githubusercontent.com/37367930/108733884-d7f36300-7569-11eb-9817-cf48085b0404.png)
返回值中获取到消息id，然后对这条合并转发消息使用 `delete_msg` api撤回，但是返回没有这条消息：
![image](https://user-images.githubusercontent.com/37367930/108734206-30c2fb80-756a-11eb-91a4-4934a5453b48.png)
同时提示撤回失败，消息不存在：
![image](https://user-images.githubusercontent.com/37367930/108734536-8a2b2a80-756a-11eb-87fe-63d7e72ad37f.png)

**Comment by 2938137849** [comment]
再贴个我用nodejs测试的代码
![image](https://user-images.githubusercontent.com/37367930/108735123-1f2e2380-756b-11eb-8662-17ab5d206b58.png)

**Comment by sam01101** [comment]
您好, 这是你自身问题, 请找出方法解决

https://user-images.githubusercontent.com/25792361/108735283-53094900-756b-11eb-9151-fdc2c7bd0b68.mp4

**Comment by sam01101** [comment]
> 比如合并转发CQ码： `[CQ:node,name=测试,uin=123,content=测试]`

请使用`send_group_forward_msg`发送转发信息

**Comment by sam01101** [comment]
用node来发转发信息的你是第一个

**Comment by 2938137849** [comment]
好的，我再测试一下

**Comment by sam01101** [comment]
我建议你立即关闭issue, 因为问题解决了
