### ISSUE TITLE
当私聊消息过多时,可能bot无法接受消息,会卡住,必须重启后发了一条消息才行

### ISSUE THREAD

**Issue by xiaowine** [Mrs4s/go-cqhttp#664]
- [x ] 我已经阅读"提问前需知 [图+文]": `Mrs4s/go-cqhttp/issues/633`

**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本:  go-cqhttp-v0.9.40-fix2
运行环境: windows 10 20H2
连接方式: http
使用协议: 

当私聊消息过多时,可能bot无法接受消息,会卡住,必须重启后发了一条消息才行
![image](https://user-images.githubusercontent.com/68009112/109005074-815e6400-76e4-11eb-80ff-7098ec2a2bd8.png)
![image](https://user-images.githubusercontent.com/68009112/109005186-a3f07d00-76e4-11eb-9242-6befa4bb0fd7.png)

**Comment by timi137137** [comment]
会不会是因为你的代码问题？我这边昨天用vbs私聊刷了500条信息没见到卡住

**Comment by xiaowine** [comment]
> 会不会是因为你的代码问题？我这边昨天用vbs私聊刷了500条信息没见到卡住

ws接收端问题？

**Comment by timi137137** [comment]
> > 会不会是因为你的代码问题？我这边昨天用vbs私聊刷了500条信息没见到卡住
> 
> ws接收端问题？

不清楚你了，我是自己开发的SDK。正常，建议排除一下吧
![image](https://user-images.githubusercontent.com/36812439/109378601-ea292480-790e-11eb-93b2-277839c4c721.png)我是异步处理的，我一直刷他就慢慢一批批回。没卡

**Comment by xiaowine** [comment]
> > > 会不会是因为你的代码问题？我这边昨天用vbs私聊刷了500条信息没见到卡住
> > 
> > 
> > ws接收端问题？
> 
> 不清楚你了，我是自己开发的SDK。正常，建议排除一下吧
> ![image](https://user-images.githubusercontent.com/36812439/109378601-ea292480-790e-11eb-93b2-277839c4c721.png)我是异步处理的，我一直刷他就慢慢一批批回。没卡

我直接用的Releases的exe，也没嵌套

**Comment by timi137137** [comment]
> > > > 会不会是因为你的代码问题？我这边昨天用vbs私聊刷了500条信息没见到卡住
> > > 
> > > 
> > > ws接收端问题？
> > 
> > 
> > 不清楚你了，我是自己开发的SDK。正常，建议排除一下吧
> > 我是异步处理的，我一直刷他就慢慢一批批回。没卡
> 
> 我直接用的Releases的exe，也没嵌套

那就不清楚了，但是能保证肯定没问题。建议排查协议问题等

**Comment by Mrs4s** [comment]
打开debug看看

**Comment by xiaowine** [comment]
> 打开debug看看

现在卡住了,显示接受到了信息,并且后端调用了api发送信息
![image](https://user-images.githubusercontent.com/68009112/109387204-f3c88180-793a-11eb-8e9e-025a53ab2db8.png)
重启后出现重复的雪崩消息
![image](https://user-images.githubusercontent.com/68009112/109387227-1a86b800-793b-11eb-9b1a-e3752e1fd250.png)

**Comment by Ink-33** [comment]
请检查你的'http://127.0.0.1:5701/post'能否正常连接，从debug上看是因为连接超时导致的重试。
另，若您使用正向ws进行通讯，您可能需要关闭HTTP上报，改为使用ws的消息上报。

**Comment by xiaowine** [comment]
> 请检查你的 'http://127.0.0.1:5701/post' 能否正常连接，从debug上看是因为连接超时导致的重试。
> 另，若您使用正向ws进行通讯，您可能需要关闭HTTP上报，改为使用ws的消息上报。

我简单写了个后端测试了一下,暂时没有问题,不过我需要再试试

**Comment by xiaowine** [comment]
> 请检查你的 'http://127.0.0.1:5701/post' 能否正常连接，从debug上看是因为连接超时导致的重试。
> 另，若您使用正向ws进行通讯，您可能需要关闭HTTP上报，改为使用ws的消息上报。

虽然A处成功接收消息且没出现问题 , 但之后在B处运行会雪崩重复之前消息

**Comment by sam01101** [comment]
这个issue太久没活跃了, 我这里提问是否可以提供视频复现方法?

**Comment by xiaowine** [comment]
> 这个issue太久没活跃了, 我这里提问是否可以提供视频复现方法?

在后续版本解决了

**Comment by sam01101** [comment]
感谢反馈，请问是否可以手动关闭issue？
