### ISSUE TITLE
same nonebot code can accept group request with session.approve(), but go-cqhttp seems doesnt have any reaction on it 

### ISSUE THREAD

**Issue by ChateauXiao** [Mrs4s/go-cqhttp#67]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.11
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
we have a group request event code in nonebot, it was worked perfect in coolq client.
since some reason that beyond human control, i switch my coolq client to go-aqhttp. 

but the same nonebot code seems do not accept the  session: SessionCommand   session.approve() method to run properly
 
**复现方法**
it always recurs when i run the same code in nonebot.

**Comment by wordgao** [comment]
@ChateauXiao 15的版本有解决这个问题的。

**Comment by rMuchan** [comment]
如果是邀请bot进群的处理失效了的话，大概是因为gocq上报了错误的事件。gocq会把它当成发给群管的那种申请加群事件，其中申请人是bot自己。
#12 似乎被开发者大大理解成日志文字错误了，其实我是想说这个问题来着（）

**Comment by rMuchan** [comment]
https://github.com/Mrs4s/MiraiGo/blob/7a84cfae679575724884851962f54a53ebfee695/client/decoders.go#L672-L692
我的测试里看起来C2CInviteJoinGroupFlag这个字段一直是0，GroupMsgType在申请中为1，在邀请中为2。大概是协议有变化？

**Comment by ChateauXiao** [comment]
> @ChateauXiao 15的版本有解决这个问题的。

now i upgrade the version to v0.9.17 , but this problem is still existed ~

**Comment by tianque1** [comment]
> > @ChateauXiao 15的版本有解决这个问题的。
> 
> now i upgrade the version to v0.9.17 , but this problem is still existed ~

You can change that “session.approve()” to use "set_group_add_request"
for exp: 
"await session.bot.set_group_add_request(flag=session.ctx['flag'],sub_type='add',approve=True)"

**Comment by ChateauXiao** [comment]
> > > @ChateauXiao 15的版本有解决这个问题的。
> > 
> > 
> > now i upgrade the version to v0.9.17 , but this problem is still existed ~
> 
> You can change that “session.approve()” to use "set_group_add_request"
> for exp:
> "await session.bot.set_group_add_request(flag=session.ctx['flag'],sub_type='add',approve=True)"
> This code will approve somebody into the group

it works in my case, thank you so much! [thump up]

what's more, i still want it be fixed from go-cqhttp side, to make my nonebot code unchanged.

**Comment by Mrs4s** [comment]
fixed.
