### ISSUE TITLE
send_group_forward_msg发送失败

### ISSUE THREAD

**Issue by GLANAX** [Mrs4s/go-cqhttp#670]
- [ ] 我已经阅读"提问前需知 [图+文]": `Mrs4s/go-cqhttp/issues/633`

**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: go-cqhttp-v0.9.40-fix2-windows-386
运行环境: Windows
连接方式: POST
使用协议: Android Phone

**bug内容**
请在这里详细描述bug的内容
send_group_forward_msg 自定义消息合并转发 消息过多发送的结果是OK，但没有看到消息
![image](https://github.com/GLANAX/a/blob/main/image.png?raw=true)
这里的数组按照 拓展API CQCode填写
![image](https://github.com/GLANAX/a/blob/main/image2.png?raw=true)
请求已按照文档要求发送
![image](https://github.com/GLANAX/a/blob/main/image3.png?raw=true)
![image](https://github.com/GLANAX/a/blob/main/image4.png?raw=true)
**复现方法**
请在这里分步骤的描述如何复现这个bug
多个消息数组

**Comment by GLANAX** [comment]
Uploading lv_0_20210225183346.mp4…

)]

**Comment by GLANAX** [comment]
https://user-images.githubusercontent.com/61342380/109141525-cc39b380-7798-11eb-97b3-59f6046c7371.mp4

**Comment by GLANAX** [comment]
![Uploading IMG_0342.PNG…]()

**Comment by GLANAX** [comment]
![IMG_0342](https://user-images.githubusercontent.com/61342380/109142302-aeb91980-7799-11eb-8e5e-ed42e63ef949.PNG)

**Comment by sam01101** [comment]
我遇到过, 这个请你必须检查清楚你的json格式

**Comment by sam01101** [comment]
Ready to close @Mrs4s
