### ISSUE TITLE
HTTP POST 上报接收不到信息

### ISSUE THREAD

**Issue by LFMcxixif** [Mrs4s/go-cqhttp#673]
上报信息是上报到我写的一个php中，但是我收不到，test.json是空的

![QQ截图20210226145206](https://user-images.githubusercontent.com/69949204/109265952-4d00ba00-7842-11eb-9d9b-3a09f1335077.png)
![QQ截图20210226145226](https://user-images.githubusercontent.com/69949204/109265957-4eca7d80-7842-11eb-8745-a8e8f8439561.png)
![QQ截图20210226145335](https://user-images.githubusercontent.com/69949204/109266050-73bef080-7842-11eb-806f-5185d12ed244.png)
![QQ截图20210226145341](https://user-images.githubusercontent.com/69949204/109266054-74f01d80-7842-11eb-962b-42547752e51b.png)

**Comment by Mrs4s** [comment]
这个是应用层的问题

**Comment by YumeMichi** [comment]
用`php://input`试试
