### ISSUE TITLE
发送信息无法换行

### ISSUE THREAD

**Issue by LFMcxixif** [Mrs4s/go-cqhttp#674]
在群聊中发送信息无法换行
如果其他人发送含有换行的消息，在上报的数据中会有\r\n出现

![IMG_20210226_230856](https://user-images.githubusercontent.com/69949204/109317501-bc4ccd00-7887-11eb-9617-7c38899ce149.jpg)
![IMG_20210226_230831](https://user-images.githubusercontent.com/69949204/109317485-b820af80-7887-11eb-9f82-bfa305541e8c.jpg)

**Comment by sam01101** [comment]
https://github.com/Mrs4s/go-cqhttp/discussions/656#discussioncomment-388189

**Comment by Ink-33** [comment]
#633

**Comment by sam01101** [comment]
我快想提个PR把自定义issue关掉了

**Comment by sam01101** [comment]
不, 我现在去提好了

**Comment by LFMcxixif** [comment]
啊谢谢啦，qwq

**Comment by MungJI** [comment]
请问换行是怎么解决的，633问题页面404了

**Comment by fallenleavesguy** [comment]
我也想知道

**Comment by LFMcxixif** [comment]
> 我也想知道
> 请问换行是怎么解决的，633问题页面404了

换行符需要url编码才可以
