### ISSUE TITLE
虚空接收私聊消息

### ISSUE THREAD

**Issue by zangxx66** [Mrs4s/go-cqhttp#679]
**环境信息**

go-cqhttp版本: v0.9.40-fix2
运行环境: linux_amd64
连接方式: 反向ws
使用协议: macos

**bug内容**
```[2021-02-28 08:38:30] [INFO]: 收到好友 PicACG(444742616) 的消息: 竞技场推送 开 (-1475315403)                                          [2021-02-28 08:38:30] [INFO]: 发送好友 444742616(444742616)  的消息: [{"type":  ... (-334264283)```  
![Screenshot_20210228-085310_QQ](https://user-images.githubusercontent.com/14540861/109404658-1bebcb00-79a3-11eb-858d-4b1d55002ae8.png)

**复现方法**
bot会虚空接受私聊消息，时不时出现

**Comment by Mrs4s** [comment]
老问题了,  还在想办法处理

**Comment by Mrs4s** [comment]
#352
