### ISSUE TITLE
a conf with only ws reverse worked fine in v0.9.11, but get coredump in v0.9.16

### ISSUE THREAD

**Issue by ChateauXiao** [Mrs4s/go-cqhttp#68]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.16
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**

# config.json
{
  "uin": [qq uid],
  "password": "[qq password]",
  "enable_db": true,
  "access_token": "",
  "relogin": true,
  "relogin_delay": 30,
  "ws_reverse_servers": [
    {
      "enabled": true,
      "reverse_url": "ws://nonebot:8080/ws/",
      "reverse_reconnect_interval": 3000
    }
  ],
  "debug": true
}

# error log:
[2020-08-10 03:51:13] [INFO]: 共加载 4 个好友.
[2020-08-10 03:51:13] [INFO]: 开始加载群列表...
[2020-08-10 03:51:15] [INFO]: 共加载 4 个群.
[2020-08-10 03:51:15] [INFO]: 信息数据库初始化完成.
[2020-08-10 03:51:15] [INFO]: 开始尝试连接到反向Websocket Universal服务器: ws://nonebot:8080/ws/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa90232]

goroutine 1 [running]:
github.com/Mrs4s/go-cqhttp/server.(*websocketClient).connectUniversal(0xc000450380)
	/github/workspace/server/websocket.go:139 +0x1f2
github.com/Mrs4s/go-cqhttp/server.(*websocketClient).Run(0xc000450380)
	/github/workspace/server/websocket.go:68 +0x18c
main.main()
	/github/workspace/main.go:202 +0xb85

**复现方法**
always recur

**Comment by Mrs4s** [comment]
#66
