### ISSUE TITLE
分享消息到mac qq，未显示成卡片

### ISSUE THREAD

**Issue by tianruiMM** [Mrs4s/go-cqhttp#689]
**环境信息**

go-cqhttp版本: go-cqhttp v0.9.38-fix1 
运行环境: linux
连接方式: 反向ws
使用协议: mac

**bug内容**
使用MessageSegment.share分享内容，
```
msg = MessageSegment.share(url='https://github.com/Ice-Cirno/HoshinoBot/blob/master/hoshino/modules/pcrclanbattle/clanbattle/README.md',
                               title='PUSH',
                               content='update readme')
await session.send(ret)
```

mac-qq客户端收到如下信息

```
【链接】https://github.com/Ice-Cirno/HoshinoBot/blob/master/hoshino/modules/pcrclanbattle/clanbattle/README.md
https://github.com/Ice-Cirno/HoshinoBot/blob/master/hoshino/modules/pcrclanbattle/clanbattle/README.md
```
![image](https://user-images.githubusercontent.com/29766033/109460451-7ec08d80-7a9b-11eb-91be-f752eefaddde.png)

手机端可以收到卡片样式的消息
![image](https://user-images.githubusercontent.com/29766033/109460614-d5c66280-7a9b-11eb-95fc-dc7deaac3b4c.png)

**期望的行为**
期望 电脑版qq客户端也能收到分享的卡片样式，而非单纯的链接。

**复现方法**
使用MessageSegment.share分享内容，查看mac qq客户端消息，

**Comment by Mrs4s** [comment]
我怀疑是macQQ本身不支持卡片

**Comment by Mrs4s** [comment]
试了下原来是支持的, 已经修复了
