### ISSUE TITLE
_send_group_notice无法设置群公告

### ISSUE THREAD

**Issue by zangxx66** [Mrs4s/go-cqhttp#691]
**环境信息**

go-cqhttp版本:  https://github.com/Mrs4s/go-cqhttp/actions/runs/614751409
运行环境:  linux_amd64
连接方式: 反向ws
使用协议: MacOS

**bug内容**
``` 
[2021-03-03 16:46:47] [INFO]: 收到群 墨丘利财团(719892154) 内 PicACG(444742616) 的消息: 设置群公告112233 (-1008059941)
[2021-03-03 16:46:48] [INFO]: 收到群 墨丘利财团(719892154) 内 小仓唯(735742327) 的消息: 我好了 (1398088778)
[2021-03-03 16:46:48] [INFO]: 发送群 719892154(719892154)  的消息: [{"type":  ... (1398088778)    
```

**复现方法**
调用_send_group_notice设置群公告，机器人具有管理员权限，确认没有超过最大字数限制，调用接口后没有任何报错信息，qq群公告并没有更新

**Comment by mizhiyugan529** [comment]
同样出现这个问题，_send_group_notice有时成功，大部分时候失效
go-cqhttp版本: go-cqhttp-v0.9.40-fix4
运行环境: linux_amd64
连接方式: 反向ws
使用协议: ipad

**Comment by sam01101** [comment]
> 同样出现这个问题，_send_group_notice有时成功，大部分时候失效。同样无任何报错
> go-cqhttp版本: go-cqhttp-v0.9.40-fix4
> 运行环境: linux
> 连接方式: 反向ws
> 使用协议: ipad

确实有这个bug, 从以前开始到现在

**Comment by sirodeneko** [comment]
环境信息

go-cqhttp版本: v0.9.40-fix5
运行环境: linux
连接方式: ws 和 http
使用协议: http

bug内容

调用 _send_group_notice 无效
可能原因：token过期，导致请求失败
重启后调用成功

复现方法

长时间上线后调用api

希望程序可以自动进行token的更新，而且代码中直接把错误忽略了，不太好，毕竟不是需要立即返回的函数

**Comment by RainChain-Zero** [comment]
报告同样的问题，在linux环境下，使用正向ws，ipad协议，无任何报错，公告并未发送。

使用http调用，返回信息如下：
```javascript
{
    "data": null,
    "msg": "GROUP_NOT_FOUND",
    "retcode": 100,
    "status": "failed",
    "wording": "群聊不存在"
}
```
已确认群聊存在
