### ISSUE TITLE
无法接收临时对话[上游依赖库问题…？从0305→0302]

### ISSUE THREAD

**Issue by xiangxiangxiong9** [Mrs4s/go-cqhttp#699]
**环境信息**

go-cqhttp版本: DEV-95f22278981fb1cba583d24ea418dd0206e9b0db [Merge pull request #698 from sam01101/dev]
运行环境: Ubuntu 21.04 arm64
连接方式: 反向WS
使用协议: iPad / Android Phone

**bug内容**

向机器人发送临时对话，但是日志里没有出现临时对话的文本[即使是打开Debug]且反向WS没有收到对应的Event
**复现方法**

怎么复现...也就是向机器人发送临时对话消息发现的...

**Comment by sam01101** [comment]
哇, 真TM随便

**Comment by sam01101** [comment]
可能是我忘记加上了, 我去看下

**Comment by sam01101** [comment]
我不确定你遇到什么问题, 我们一个一个慢慢来 (~~换以前要打钱的~~)

环境:
- 协议: MacOS
- 连接: 正向WS(假的) / HTTP(发送信息)

情况一:
- 用户 -> 机器人
![image](https://user-images.githubusercontent.com/25792361/110130945-92a22180-7e04-11eb-8f00-c8eee327395c.png)

因为是主动发起的, 所以后面也不需要`group_id`了
![image](https://user-images.githubusercontent.com/25792361/110131241-e90f6000-7e04-11eb-8e31-24d5da7fc67b.png)

情况二:
- 机器人 -> 用户 (如果进行了前面的步骤请重启一次不然会有缓存)
![image](https://user-images.githubusercontent.com/25792361/110131588-43a8bc00-7e05-11eb-89de-bfc587076f1a.png)

注意这里用了`gorup_id`
![image](https://user-images.githubusercontent.com/25792361/110131667-5ae7a980-7e05-11eb-9a23-e4d6dc499402.png)

如果用户一直没回复机器人的话, 机器人就必须一直提供`group_id` (一直主动对话) 直到用户回复

![image](https://user-images.githubusercontent.com/25792361/110131842-8cf90b80-7e05-11eb-9c0f-fc79e30c079e.png)

这里有回复的(最新的`A!`就是)

**Comment by sam01101** [comment]
接下来, 你的问题:
> 向机器人发送临时对话，但是日志里没有出现临时对话的文本[即使是打开Debug]且反向WS没有收到对应的Event

反向WS我这里给你看下:

QQ:
![image](https://user-images.githubusercontent.com/25792361/110132666-61c2ec00-7e06-11eb-8859-4b4983afe0d7.png)

收到的WS信息 (反向WS):
![image](https://user-images.githubusercontent.com/25792361/110132760-7b643380-7e06-11eb-82ce-93281659516b.png)

我想问下, 你的问题呢?

**Comment by xiangxiangxiong9** [comment]
> 接下来, 你的问题:
> 
> > 向机器人发送临时对话，但是日志里没有出现临时对话的文本[即使是打开Debug]且反向WS没有收到对应的Event
> 
> 反向WS我这里给你看下:
> 
> QQ:
> ![image](https://user-images.githubusercontent.com/25792361/110132666-61c2ec00-7e06-11eb-8859-4b4983afe0d7.png)
> 
> 收到的WS信息 (反向WS):
> ![image](https://user-images.githubusercontent.com/25792361/110132760-7b643380-7e06-11eb-82ce-93281659516b.png)
> 
> 我想问下, 你的问题呢?

刚刚切换了一下协议[MacOS]
但是还是没收到…[用户→机器人]…
我明天在电脑上再试试[Ubuntu 20.04 x86_64]…刚关…

**Comment by Ink-33** [comment]
need more info  
RM?

**Comment by sam01101** [comment]
> need more info
> RM?

RM有可能

**Comment by xiangxiangxiong9** [comment]
> 接下来, 你的问题:
> 
> > 向机器人发送临时对话，但是日志里没有出现临时对话的文本[即使是打开Debug]且反向WS没有收到对应的Event
> 
> 反向WS我这里给你看下:
> 
> QQ:
> ![image](https://user-images.githubusercontent.com/25792361/110132666-61c2ec00-7e06-11eb-8859-4b4983afe0d7.png)
> 
> 收到的WS信息 (反向WS):
> ![image](https://user-images.githubusercontent.com/25792361/110132760-7b643380-7e06-11eb-82ce-93281659516b.png)
> 
> 我想问下, 你的问题呢?

现在是 能发送[有回馈] 但是 不能接收…
[刚刚去从Actions下载并替换了本地版本]

**Comment by Ink-33** [comment]
> > 接下来, 你的问题:
> > 
> > > 向机器人发送临时对话，但是日志里没有出现临时对话的文本[即使是打开Debug]且反向WS没有收到对应的Event
> > 
> > 反向WS我这里给你看下:
> > 
> > QQ:
> > ![image](https://user-images.githubusercontent.com/25792361/110132666-61c2ec00-7e06-11eb-8859-4b4983afe0d7.png)
> > 
> > 收到的WS信息 (反向WS):
> > ![image](https://user-images.githubusercontent.com/25792361/110132760-7b643380-7e06-11eb-82ce-93281659516b.png)
> > 
> > 我想问下, 你的问题呢?
> 
> 现在是 能发送[有回馈] 但是 不能接收…
> [刚刚去从Actions下载并替换了本地版本]

请提供log

**Comment by sam01101** [comment]
请问是否尝试过用手机登录机器人账号然后发送?

另外提醒一句, 新加入go-cqhttp的机器人需要挂一段时间才可以正常使用

**Comment by xiangxiangxiong9** [comment]
> 请问是否尝试过用手机登录机器人账号然后发送?
> 
> 另外提醒一句, 新加入go-cqhttp的机器人需要挂一段时间才可以正常使用

挂了有一周了…[并且2.27[一过1天]时的临时对话正常接收]

**Comment by sam01101** [comment]
> > 请问是否尝试过用手机登录机器人账号然后发送?
> > 另外提醒一句, 新加入go-cqhttp的机器人需要挂一段时间才可以正常使用
> 
> 挂了有一周了…[并且2.27[一过1天]时的临时对话正常接收]

> 请问是否尝试过用手机登录机器人账号然后发送?

**Comment by xiangxiangxiong9** [comment]
> > > 请问是否尝试过用手机登录机器人账号然后发送?
> > > 另外提醒一句, 新加入go-cqhttp的机器人需要挂一段时间才可以正常使用
> > 
> > 
> > 挂了有一周了…[并且2.27[一过1天]时的临时对话正常接收]
> 
> > 请问是否尝试过用手机登录机器人账号然后发送?

刚刚在手机上尝试了一次…
消息发出去了[接收用的QQ号收到了消息]，但是机器人日志里仍然没有临时对话消息…

**Comment by sam01101** [comment]
> > > > 请问是否尝试过用手机登录机器人账号然后发送?
> > > > 另外提醒一句, 新加入go-cqhttp的机器人需要挂一段时间才可以正常使用
> > > 
> > > 
> > > 挂了有一周了…[并且2.27[一过1天]时的临时对话正常接收]
> > 
> > 
> > > 请问是否尝试过用手机登录机器人账号然后发送?
> 
> 刚刚在手机上尝试了一次…
> 消息发出去了[接收用的QQ号收到了消息]，但是机器人日志里仍然没有临时对话消息…

尝试切换账号, 试一试另外一个账号是否有同样的问题

如果真的有, 我真的帮不了你了

**Comment by xiangxiangxiong9** [comment]
刚刚把两个账户调过来了
'''
[2021-03-05 23:41:59] [DEBUG]: Protocol -> rev pkt: ConfigPushSvc.PushDomain seq: 56079
[2021-03-05 23:41:59] [DEBUG]: Protocol -> Unhandled Command: ConfigPushSvc.PushDomain
Seq: 56079
This message can be ignored.
[2021-03-05 23:41:59] [DEBUG]: Protocol -> rev pkt: ConfigPushSvc.PushReq seq: 56077
[2021-03-05 23:41:59] [DEBUG]: Protocol -> got file storage svc push.
[2021-03-05 23:42:18] [DEBUG]: Protocol -> rev pkt: MessageSvc.PushNotify seq: 616
[2021-03-05 23:42:18] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbGetMsg seq: 13891
[2021-03-05 23:42:18] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbDeleteMsg seq: 13892
[2021-03-05 23:42:26] [DEBUG]: Protocol -> rev pkt: Heartbeat.Alive seq: 13893
[2021-03-05 23:42:36] [DEBUG]: Protocol -> rev pkt: MessageSvc.PushNotify seq: 30951
[2021-03-05 23:42:36] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbGetMsg seq: 13894
[2021-03-05 23:42:36] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbDeleteMsg seq: 13895
[2021-03-05 23:42:57] [DEBUG]: Protocol -> rev pkt: Heartbeat.Alive seq: 13896
[2021-03-05 23:43:10] [DEBUG]: Protocol -> rev pkt: MessageSvc.PushNotify seq: 20572
[2021-03-05 23:43:10] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbGetMsg seq: 13897
[2021-03-05 23:43:10] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbDeleteMsg seq: 13898
[2021-03-05 23:43:14] [DEBUG]: Protocol -> rev pkt: MessageSvc.PushNotify seq: 27132
[2021-03-05 23:43:14] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbGetMsg seq: 13899
[2021-03-05 23:43:14] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbDeleteMsg seq: 13900
[2021-03-05 23:43:27] [DEBUG]: Protocol -> rev pkt: Heartbeat.Alive seq: 13901
[2021-03-05 23:43:48] [DEBUG]: Protocol -> rev pkt: MessageSvc.PushNotify seq: 21642
[2021-03-05 23:43:48] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbGetMsg seq: 13902
'''

**Comment by sam01101** [comment]
问题是否存在?

**Comment by xiangxiangxiong9** [comment]
> 问题是否存在?

嗯……

**Comment by xiangxiangxiong9** [comment]
> 问题是否存在?

倒是日志里出来一些奇怪的东西[之前的号群有点热闹]

**Comment by xiangxiangxiong9** [comment]
@sam01101 
我刚刚去你的fork仓库clone了下并build…
能收到临时对话消息…
上游问题？？

**Comment by xiangxiangxiong9** [comment]
@sam01101 
我用你仓库里的 go.mod go.sum 替换这个仓库的并build了一下…仍然能收到临时对话…
上游问题…[确信]
[关闭issue]

**Comment by xiangxiangxiong9** [comment]
从Commit e36a9a95c59fe76469f69b9a393e86e2df8523c4 那次更新MiraiGo后就一直收不到临时对话消息了…
0302的版本没事，一更新到0304的就坏了…

**Comment by xiangxiangxiong9** [comment]
好吧。。这就是**依赖库**问题吧。。。
Ubuntu 20.04 amd64 环境也不行

**Comment by Ink-33** [comment]
怪

**Comment by sam01101** [comment]
是不是我MiraiGo更新了什么然后没PR？我去看下

**Comment by sam01101** [comment]
这个关闭一下

**Comment by xiangxiangxiong9** [comment]
> 这个关闭一下

Oh

**Comment by liliangshan** [comment]
**环境信息**

go-cqhttp版本: 自己编译最新git版本
运行环境:windows2012 R2x64 
连接方式: websocket
使用协议: ipad

**bug内容**
通过 http://wpa.qq.com/msgrd?v=3&uin=3571028606&site=qq&menu=yes 发起的会话，Bot无法收到
![QQ图片20210320181836](https://user-images.githubusercontent.com/25602657/111866634-d3c03700-89a9-11eb-80a3-b35d69208f14.png)


**复现方法**
通过 https://shang.qq.com/v3/widget.html 给Bot的QQ开启临时会话权限，然后用一个未加好友的QQ发送信息，这时Bot无法接收到内容
