### ISSUE TITLE
Request for a Dockerfile

### ISSUE THREAD

**Issue by purerosefallen** [Mrs4s/go-cqhttp#7]
In the past we deploy CoolQ HTTP API with this docker image: [https://cqhttp.cc/docs/4.15/#/Docker](https://cqhttp.cc/docs/4.15/#/Docker)
We were used to deploying it with Docker, with the app itself and QQ robot part in the same `docker-compose.yml` file. As for CoolQ came down, we would like to move to this project instead.
Could you spend a little time to make a similar Docker image, configuring the QQ robot with environment variables, to help us move to this project? Thanks.

**Comment by masnn** [comment]
no need to use docker.
it's so simple.
just run ./go-cqhttp & fill in the config.
No more steps.

**Comment by purerosefallen** [comment]
In addition, you said in release [v0.9.8](https://github.com/Mrs4s/go-cqhttp/releases/tag/v0.9.8), configuring with environment variables became possible. Could you tell me how configure it with that?

**Comment by Mrs4s** [comment]
Docker supports is under development.  but will not be released until the verification code processing solution found .

**Comment by ishland** [comment]
I think you can request users to write the code to a file.

**Comment by skyzh** [comment]
We have made a `Dockerfile` in this PR https://github.com/SJTU-Plus/ManageBotDocker/pull/1/files . You may refer to this example.

**Comment by Arnie97** [comment]
Closed by #47

**Comment by scjtqs** [comment]
可以瞅瞅我的Dockerfile 带 healthcheck和环境变量配置的。启动方式建议使用docker-compose的

**Comment by Mrs4s** [comment]
> 可以瞅瞅我的Dockerfile 带 healthcheck和环境变量配置的。启动方式建议使用docker-compose的
> https://github.com/scjtqs/docker-miraigo

目前主要问题是验证码输入, 在没找到好办法前我暂时不提供官方的docker镜像

**Comment by scjtqs** [comment]
目前我是这样处理的:
docker-compose up 等出现手机锁，复制链接到浏览器，解锁后，ctrl +c取消掉
重新 docker-compose up -d就行了



---Original---

**Comment by purerosefallen** [comment]
> > 可以瞅瞅我的Dockerfile 带 healthcheck和环境变量配置的。启动方式建议使用docker-compose的
> > https://github.com/scjtqs/docker-miraigo
> 
> 目前主要问题是验证码输入, 在没找到好办法前我暂时不提供官方的docker镜像

I usually add a `stdin_open` option, docker attach` in, and enter the captcha code.
Anyway, it should not be a problem to enter a code.
An alternative way is, to wait for a file for captcha code, for more friendly interaction.

**Comment by scjtqs** [comment]
> > > 可以瞅瞅我的Dockerfile 带 healthcheck和环境变量配置的。启动方式建议使用docker-compose的
> > > https://github.com/scjtqs/docker-miraigo
> > 
> > 
> > 目前主要问题是验证码输入, 在没找到好办法前我暂时不提供官方的docker镜像
> 
> I usually add a `stdin_open` option, docker attach` in, and enter the captcha code.
> Anyway, it should not be a problem to enter a code.
> An alternative way is, to wait for a file for captcha code, for more friendly interaction.

确实，不过必须是docker run 这种方式起的容器，docker-compose方式的似乎不行

**Comment by purerosefallen** [comment]
@scjtqs It's OK with docker-compose. Just use `docker attach` to to get in.
