### ISSUE TITLE
反向 WS调用 .handle_quick_operation 响应私聊

### ISSUE THREAD

**Issue by crazywhalecc** [Mrs4s/go-cqhttp#701]
**环境信息**

go-cqhttp版本: v0.9.40-fix3
运行环境: darwin-amd64（macOS Big Sur 11.3 Beta 3）
连接方式: 反向 WebSocket
使用协议: 默认协议（iPad）

**bug内容**

反向 WebSocket 调用 `.handle_quick_operation` 时，如果私聊消息不指定群消息快速操作的参数 `at_sender` 为 `false` 的话，私聊也会 at，并且显示为 QQ 号码，正常情况下私聊消息不应该使用此参数。

**复现方法**

框架代码：发送 `你好`，回复 `你好啊！`，且只对 `message_type == 'group'` 的事件的回复带上 `at_sender = 'false'` 参数
向机器人私聊：`你好`，回复 `@我的QQ号 你好啊！`
向群内发送：`你好`，回复 `你好啊！`
复现成功

**Comment by sam01101** [comment]
啊。。。。是不是一定要用这个API？

**Comment by sam01101** [comment]
我去Follow up一下

**Comment by sam01101** [comment]
私聊显示QQ号的问题是因为没读取到名字

**Comment by crazywhalecc** [comment]
> 啊。。。。是不是一定要用这个API？

这个之前在 CQHTTP 里面是给 SDK 或者框架调用的，因为要优雅的回复，所以这个 API 我写入框架里面了，但是私聊本来就不该响应 `at_sender` 参数的，私聊消息的快速回复本应该不支持此参数。

这个 API 怎么说，为 WebSocket 设计的这个 API 我觉得可以根据下一版的 OneBot 标准进行调整，虽说之前有但确实也不是一定要用的。

**Comment by sam01101** [comment]
我会把`at_sender`限制在群中使用

**Comment by sam01101** [comment]
#702
