### ISSUE TITLE
关于go-cqhttp启动初始化bug上报

### ISSUE THREAD

**Issue by timi137137** [Mrs4s/go-cqhttp#714]
**环境信息**

go-cqhttp版本: v0.9.40-fix4
运行环境: Windows10 20H2 64bit
连接方式: 正向WebSocket
使用协议: iPad

**bug内容**

go-cqhttp正在加载时（指WebSocket服务器启动后）立马连接并发送API调用会失效，但后台会显示接收到发送的信息。相对应的测试过启动完成后的go-cqhttp是能正常使用的。因此是否应该在Websocket连接后添加一个短暂的延时？

![image](https://user-images.githubusercontent.com/36812439/110951841-7a8c4e00-8380-11eb-93fd-220b05236c89.png)

**复现方法**

让一个客户端每5秒尝试连接一次go-cqhttp服务器,在第一次尝试失败时启动go-cqhttp即可复现。（已成功复现3次以上）

**Comment by sam01101** [comment]
这里强烈建议在自己的框架实现

**Comment by timi137137** [comment]
> 这里强烈建议在自己的框架实现5秒延迟

我觉得我不是乱发issue的脑残(
![image](https://user-images.githubusercontent.com/36812439/110952740-862c4480-8381-11eb-9c11-435258200d12.png)

**Comment by sam01101** [comment]
> > 这里强烈建议在自己的框架实现5秒延迟
> 
> 我觉得我不是乱发issue的脑残(
> ![image](https://user-images.githubusercontent.com/36812439/110952740-862c4480-8381-11eb-9c11-435258200d12.png)

哦, 就是你客户端本身已经实现了, 但还是出现此情况?

**Comment by timi137137** [comment]
> > > 这里强烈建议在自己的框架实现5秒延迟
> > 
> > 
> > 我觉得我不是乱发issue的脑残(
> > ![image](https://user-images.githubusercontent.com/36812439/110952740-862c4480-8381-11eb-9c11-435258200d12.png)
> 
> 哦, 就是你客户端本身已经实现了, 但还是出现此情况?

当然，不然我也不会过来上报了，延迟是调过几次的

**Comment by Mrs4s** [comment]
我怀疑是QQ的限制, 刚登录无法发送信息.
请问有没有任何报错 或者群聊消息能不能以同样的方式复现?

**Comment by timi137137** [comment]
> 我怀疑是QQ的限制, 刚登录无法发送信息.
> 请问有没有任何报错 或者群聊消息能不能以同样的方式复现?

没有报错，后台显示收到调用信息（看第一张图），但是QQ处没有收到信息。QQ没有风控（因为过几秒就好了）。应该是刚登录的原因，所以建议连接后稍微延迟几秒等待初始化

**Comment by Mrs4s** [comment]
回头考虑试试群消息有无此限制?

**Comment by timi137137** [comment]
> 回头考虑试试群消息有无此限制?

没问题，现在试

**Comment by timi137137** [comment]
群消息测试完毕，可以在毫秒内发送。并没有上述问题
![image](https://user-images.githubusercontent.com/36812439/110954389-672eb200-8383-11eb-92db-571a379398fe.png)

**Comment by Mrs4s** [comment]
那应该是QQ对私聊的限制, 这个我推荐在应用层解决emmm
我这边处理的话会导致全部api调用都会有延迟

**Comment by timi137137** [comment]
> 那应该是QQ对私聊的限制, 这个我推荐在应用层解决emmm
> 我这边处理的话会导致全部api调用都会有延迟

那OK，我就在这留个底。当记录吧
