### ISSUE TITLE
set_group_kick is not worked for my part

### ISSUE THREAD

**Issue by ChateauXiao** [Mrs4s/go-cqhttp#72]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.17
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
i use on_command() decroator for a command with set_group_kick() , but it doesn't work in my code.

**复现方法**
all situation

**Comment by Mrs4s** [comment]
![kick](https://user-images.githubusercontent.com/12137562/89765364-c0521100-db28-11ea-9b7d-9a74d340d0ae.jpg)
please check your code.
