### ISSUE TITLE
无法使用反向WS

### ISSUE THREAD

**Issue by Cathgao** [Mrs4s/go-cqhttp#73]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.17
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
无法使用反向WS
左为go-cqhttp配置，右为酷Q的cqhttp配置
![gocq](https://user-images.githubusercontent.com/21031564/89782350-b4c21280-db47-11ea-8789-d6dca833bbfc.png)

运行后提示
```
[2020-08-10 20:27:35] [INFO]: 开始尝试连接到反向Websocket Universal服务器: ws://127.0.0.1:9222
[2020-08-10 20:27:35] [WARNING]: 连接到反向Websocket Universal服务器 ws://127.0.0.1:9222 时出现错误: websocket.Dial ws://127.0.0.1:9222: bad status
```
![QQ截图20200810202928](https://user-images.githubusercontent.com/21031564/89782603-33b74b00-db48-11ea-98b8-a36e6964285e.png)

**Comment by Cathgao** [comment]
同时运行yobot的截图
![tb](https://user-images.githubusercontent.com/21031564/89784899-11bfc780-db4c-11ea-9c21-e6d8428b5792.png)

**Comment by chenxuan353** [comment]
你在端口后面加/ws

**Comment by Cathgao** [comment]
> 你在端口后面加/ws
> ![image](https://user-images.githubusercontent.com/48858695/89787606-54839e80-db50-11ea-9c4c-4116d8a966f8.png)

可以使用了，非常感谢！
