### ISSUE TITLE
无法发送语音

### ISSUE THREAD

**Issue by DreamMiu** [Mrs4s/go-cqhttp#741]
**环境信息**

go-cqhttp版本: go-cqhttp-v0.9.40-fix4
运行环境: centos7
连接方式: zhamao框架
使用协议: ipa

**bug内容**

无法发送语音并且在群上直接回显[CQ:record,file=http://clouds.xxx.cn/jiaochuang.mp3]

**复现方法**

调试 CQ:record触发
encode silk failed: convert pcm file error: exec: "ffmpeg": executable file not found in $PATH 将原样发送

**Comment by Ink-33** [comment]
#740 您的问题已经得到解答，请不要刷issue
