### ISSUE TITLE
关于群消息字数限制咨询 /send_group_msg

### ISSUE THREAD

**Issue by 4815180** [Mrs4s/go-cqhttp#744]
**环境信息**

go-cqhttp版本: v0.9.40-fix4

**需要添加的功能内容**

请问大佬， 我在通过调用 /send_group_msg 发现字数有限制，字数过多时，通过python get 调用相应api后，日志无任何显示，消息也无法正常发送，是否有可能实现字符数多一些？ 感谢大佬的回复

**Comment by timi137137** [comment]
#633

**Comment by 4815180** [comment]
> #633

日志无任何显示。。我是通过python调用api， 有什么办法可以debug么

**Comment by Ink-33** [comment]
#633

**Comment by sam01101** [comment]
亲, 这里建议您先查看 #633 哦~
 ![](e0bd0b7d74a7e7d574315a8f36dccb95.image,url=http://gchat.qpic.cn/gchatpic_new/2996532668/2182548878-2149732928-E0BD0B7D74A7E7D574315A8F36DCCB95/0?term=3)

**Comment by sam01101** [comment]
![Y}CJ IQGH`0M{`O%O~3H0I](https://user-images.githubusercontent.com/25792361/111782869-803fe180-88f4-11eb-82ad-48133fb2fae3.jpg)

**Comment by Mrs4s** [comment]
一般来说是风控问题, 请尝试打开分片发送. 理论上单条消息最多能发5000字的

**Comment by sam01101** [comment]
> 版本：1.0.0 beta
> 协议：ipad
> 环境：centos 7
> 
> 100个字符可以正常发送：
> curl -vvv -H "Content-Type:application/json" -d '{"message_type":"group","group_id":"559152165", "message":"1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111","auto_escape":true}' http://10.2.145.233:5700/send_msg
> 
> * Trying 10.2.145.233...
> * TCP_NODELAY set
> * Connected to 10.2.145.233 (10.2.145.233) port 5700 (#0)
> 
> > POST /send_msg HTTP/1.1
> > Host: 10.2.145.233:5700
> > User-Agent: curl/7.64.1
> > Accept: _/_
> > Content-Type:application/json
> > Content-Length: 180
> 
> * upload completely sent off: 180 out of 180 bytes
>   < HTTP/1.1 200 OK
>   < Content-Type: application/json; charset=utf-8
>   < Date: Thu, 12 Aug 2021 01:55:30 GMT
>   < Content-Length: 62
>   <
>   {"data":{"message_id":-1330930483},"retcode":0,"status":"ok"}
> * Connection #0 to host 10.2.145.233 left intact
> * Closing connection 0
> 
> 101个字符就发送失败：
> curl -vvv -H "Content-Type:application/json" -d '{"message_type":"group","group_id":"559152165", "message":"11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111","auto_escape":true}' http://10.2.145.233:5700/send_msg
> 
> * Trying 10.2.145.233...
> * TCP_NODELAY set
> * Connected to 10.2.145.233 (10.2.145.233) port 5700 (#0)
> 
> > POST /send_msg HTTP/1.1
> > Host: 10.2.145.233:5700
> > User-Agent: curl/7.64.1
> > Accept: _/_
> > Content-Type:application/json
> > Content-Length: 181
> 
> * upload completely sent off: 181 out of 181 bytes
> * Empty reply from server
> * Connection #0 to host 10.2.145.233 left intact
>   curl: (52) Empty reply from server
> * Closing connection 0
> 
> log报错：
> 2021/08/12 09:55:15 http: panic serving 10.1.177.73:49378: runtime error: invalid memory address or nil pointer dereference
> goroutine 216 [running]:
> net/http.(*conn).serve.func1(0xc00014dea0)
> net/http/server.go:1824 +0x153
> panic(0xd67ce0, 0x1547be0)
> runtime/panic.go:971 +0x499
> github.com/Mrs4s/MiraiGo/message.(*ServiceElement).Pack(0x0, 0xfad140, 0x0, 0x7f2ae9ae6398)
> github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/message/pack.go:84 +0x37
> github.com/Mrs4s/MiraiGo/message.ToProtoElems(0xc00079cf90, 0x1, 0x1, 0xc0003eb101, 0x47a5bf, 0xd57660, 0xc0007a3c80)
> github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/message/message.go:285 +0x59a
> github.com/Mrs4s/MiraiGo/client.(*QQClient).buildGroupSendingPacket(0xc0002d2480, 0x2153fc25, 0x19eedceb1, 0x0, 0x0, 0xc00079cf90, 0x1, 0x1, 0xc00000e438, 0xedcc98, ...)
> github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/group_msg.go:255 +0x17b
> github.com/Mrs4s/MiraiGo/client.(*QQClient).sendGroupMessage(0xc0002d2480, 0x2153fc25, 0xc0003eb300, 0xc0003eb3d0, 0x0)
> github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/group_msg.go:129 +0x86c
> github.com/Mrs4s/MiraiGo/client.(*QQClient).SendGroupMessage(0xc0002d2480, 0x2153fc25, 0xc0003eb6b8, 0xc00068f45f, 0x1, 0x1, 0xc00068f4c8)
> github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/group_msg.go:53 +0x359
> github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).SendGroupMessage(0xc0001b2300, 0x2153fc25, 0xc00068f6b8, 0x0)
> github.com/Mrs4s/go-cqhttp/coolq/bot.go:292 +0x2d7
> github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSendGroupMessage(0xc0001b2300, 0x2153fc25, 0x3, 0xc0004ba63a, 0x67, 0xc0004ba63b, 0x65, 0x0, 0x3a, 0x1, ...)
> github.com/Mrs4s/go-cqhttp/coolq/api.go:391 +0xa59
> github.com/Mrs4s/go-cqhttp/server.sendMSG(0xc0001b2300, 0xfad360, 0xc0000d8c80, 0x8)
> github.com/Mrs4s/go-cqhttp/server/api.go:63 +0x88e
> github.com/Mrs4s/go-cqhttp/server.(*apiCaller).callAPI(0xc000159100, 0xc0001345d6, 0x8, 0xfad360, 0xc0000d8c80, 0x1)
> github.com/Mrs4s/go-cqhttp/server/api.go:425 +0x409
> github.com/Mrs4s/go-cqhttp/server.(*httpServer).ServeHTTP(0xc0001590e0, 0xfba9c0, 0xc0001d6540, 0xc0001e4300)
> github.com/Mrs4s/go-cqhttp/server/http.go:113 +0x265
> net/http.serverHandler.ServeHTTP(0xc0001fec40, 0xfba9c0, 0xc0001d6540, 0xc0001e4300)
> net/http/server.go:2887 +0xa3
> net/http.(*conn).serve(0xc00014dea0, 0xfbc7f0, 0xc000364d80)
> net/http/server.go:1952 +0x8cd
> created by net/http.(*Server).Serve
> net/http/server.go:3013 +0x39b

#633
