### ISSUE TITLE
QQ临时会话没有收到

### ISSUE THREAD

**Issue by liliangshan** [Mrs4s/go-cqhttp#745]
**环境信息**

go-cqhttp版本: go-cqhttp-v0.9.40-fix4-windows-amd64
运行环境: window2012 R2
连接方式: 事件
使用协议: iPad

**BUG内容**
通过 http://wpa.qq.com/msgrd?v=3&uin=3571028606&site=qq&menu=yes 发起的会话，Bot无法收到
![QQ图片20210320181836](https://user-images.githubusercontent.com/25602657/111866510-f3a32b00-89a8-11eb-83c0-0e9df4297a7b.png)

**Comment by sam01101** [comment]
不好意思, 请问是否可以根据bug模板重新开一次?

**Comment by sam01101** [comment]
你这样我们很难去处理问题

**Comment by sam01101** [comment]
话说`Issuebot`好像bug掉了...

**Comment by liliangshan** [comment]
我去看下模版，第一次提，不好意思

**Comment by sam01101** [comment]
这个还没兼容, 下个版本应该会处理
