### ISSUE TITLE
QQ临时会话没有收到

### ISSUE THREAD

**Issue by liliangshan** [Mrs4s/go-cqhttp#746]
**环境信息**

go-cqhttp版本: 自己编译最新git版本
运行环境:windows2012 R2x64 
连接方式: websocket
使用协议: ipad

**bug内容**
通过 http://wpa.qq.com/msgrd?v=3&uin=3571028606&site=qq&menu=yes 发起的会话，Bot无法收到
![QQ图片20210320181836](https://user-images.githubusercontent.com/25602657/111866634-d3c03700-89a9-11eb-80a3-b35d69208f14.png)

**复现方法**
通过 https://shang.qq.com/v3/widget.html 给Bot的QQ开启临时会话权限，然后用一个未加好友的QQ发送信息，这时Bot无法接收到内容

**Comment by sam01101** [comment]
不好意思, 请问重复开issue
