### ISSUE TITLE
无法解析php接口返回的换行符

### ISSUE THREAD

**Issue by lovezm** [Mrs4s/go-cqhttp#752]
**环境信息**

go-cqhttp版本: 0.9.40
运行环境: windows
连接方式: http
使用协议: golang

**bug内容**

机器人指令触发PHP返回的\ n换行符  替换成了一个空格  要如何使用换行符
如果直接get发送 会直接返回\ n

**复现方法**

**Comment by Ink-33** [comment]
#633

**Comment by sam01101** [comment]
> 使用协议: golang

协议是golang还可以(
