### ISSUE TITLE
Hoshinobot无法正常通过ws反代连接上

### ISSUE THREAD

**Issue by DokiOnjouji** [Mrs4s/go-cqhttp#76]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.17
运行环境: windows_server 2016
连接方式: 反向WS

**bug内容**
在转移hoshinobot从coolq上到mirai上出现无法连接反向ws的错误 bad status 
![image](https://user-images.githubusercontent.com/48285258/89848591-18d0ef00-dbb9-11ea-8cbb-64fc65c1c3eb.png)

这里是config配置，我仔细琢磨了半天，应该没有从cqhttp那边的config文件转换错误
![image](https://user-images.githubusercontent.com/48285258/89848415-c1cb1a00-dbb8-11ea-91b1-41a59df5c808.png)

此为原本cqhttp那边config的设置
![image](https://user-images.githubusercontent.com/48285258/89848381-b972df00-dbb8-11ea-884e-2ae09ba75980.png)

此为hoshinobot那边的设置
![image](https://user-images.githubusercontent.com/48285258/89848658-474eca00-dbb9-11ea-90e2-ccfcb699245e.png)

因为无论在coolq 还是使用编译好的miraiok均可以正常使用ws反代，miraiok上使用的是cqhttpmirai，不太懂为什么到了这里就会疯狂出错，端口设置均无明显问题（如果有的话很抱歉需要指出来，我真看不出来。。。）
**复现方法**
http use 开启
ws 开启
ws 反代开启
HoshinoBot.zip: https://n459.com/file/3192445-456634639
这边是我配置的hoshinobot的文件，解压后应该还要修复一下
1.去到HoshinoBot文件夹，按住shift的同时点右键，选择在此处打开powershell窗口，执行以下命令：
py -3.8 -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
2.再去到HoshinoBot\hoshino\modules\yobot，按住shift的同时点右键，选择在此处打开powershell窗口，执行以下命令：
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r yobot/src/client/requirements.txt

然后分别运行gocqhttp和hoshinobot

**Comment by Mrs4s** [comment]
请把 `reverse_url` 改为空白即可解决

**Comment by DokiOnjouji** [comment]
感谢，测试了可以连结，功能正常使用了。虽然比较好奇为什么是放空就正常了。

**Comment by Ice-Cirno** [comment]
`reverse_url` 少写了 /ws/

**Comment by Mrs4s** [comment]
好像不是我的问题23333

**Comment by DokiOnjouji** [comment]
我的我的，卧槽那居然之前连cqhttpmirai和coolq都能正常用。
