### ISSUE TITLE
戳一戳没有频率限制

### ISSUE THREAD

**Issue by sam01101** [Mrs4s/go-cqhttp#762]
**环境信息**

go-cqhttp版本: go-cqhttp-v1.0.0-alpha1
运行环境: Linux
连接方式: 反向WS
使用协议: MacOS

**bug内容**

![FM(95T2I`{EREH~O3EYLF0N](https://user-images.githubusercontent.com/25792361/112429689-f078b800-8d77-11eb-83bd-208d141448b5.jpg)

**复现方法**

有兴趣可以自己去刷API玩玩, 小心风控

**Comment by Mrs4s** [comment]
服务端行为 早就知道的事情

**Comment by sam01101** [comment]
> 服务端行为 早就知道的事情

gocq不限制一下吗(

**Comment by Mrs4s** [comment]
懒得限制这种不会因为意外影响其他人体验的问题
比如限制字数是因为超长消息会导致其他人的客户端卡顿

**Comment by sam01101** [comment]
懂了
