### ISSUE TITLE
RFC：建议删除回复消息中重复的 [CQ:at]

### ISSUE THREAD

**Issue by Shigma** [Mrs4s/go-cqhttp#764]
目前收到的回复消息中，[CQ:reply] 会自带一个 [CQ:at]。且由于客户端的行为，回复消息会默认带一个 [CQ:at]，这将导致机器人收到的消息中存在两个连续的 [CQ:at]。这一方面非常诡异，另一方面也给机器人的处理逻辑添加负担。

**需要添加的功能内容**

有两种方案：

1. 删除 [CQ:reply] 自己伴随的 [CQ:at]。
2. 检测 [CQ:reply] 之后是否存在连续的 [CQ:at]。如果有则删除之。

方案一的好处是足够干净，且与其他平台逻辑相统一（参考了 discord 等平台的引用逻辑）。坏处是可能对少数机器人存在 breaking change。

方案二基本上不存在兼容性问题，但是逻辑并不足够合理。事实上，后一个 [CQ:at] 的插入位置取决于你点击回复时输入框内的光标位置，因而并不一定是在开头。

不知道大家对上述两种方案有何看法。

**Comment by sam01101** [comment]
> RFC：建议删除回复消息中重复的 [CQ:at]

RFC .. ? 这个是代表什么意思

**Comment by Shigma** [comment]
Request For Comments

**Comment by sam01101** [comment]
> Request For Comments

学会了

**Comment by Mrs4s** [comment]
我认为按方案1处理比较好, 至少能保证机器人收到的和客户端看到的内容现同

**Comment by Shigma** [comment]
所以有打算在 v1 实装吗

**Comment by sam01101** [comment]
> 2\. 检测 [CQ:reply] 之后是否存在连续的 [CQ:at]

如果这个变成 "检测 [CQ:reply] 之后是否存在与reply相同的一个 [CQ:at] 则删除之。" 会不会更好?

**Comment by synodriver** [comment]
一定要做的话，做成可选开关吧，避免向前不兼容

**Comment by sam01101** [comment]
> 一定要做的话，做成可选开关吧，避免向前不兼容

啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊

**Comment by sam01101** [comment]
> 一定要做的话，做成可选开关吧，避免向前不兼容

开关挺多的

**Comment by synodriver** [comment]
> > 一定要做的话，做成可选开关吧，避免向前不兼容
> 
> 开关挺多的

![_5 LU3R%_M~}7S{ R@3AEET](https://user-images.githubusercontent.com/50922489/113596243-98419000-966c-11eb-93da-5bc8b471df0f.jpg)

**Comment by sam01101** [comment]
> > > 一定要做的话，做成可选开关吧，避免向前不兼容
> > 
> > 
> > 开关挺多的
> 
> ![_5 LU3R%_M~}7S{ R@3AEET](https://user-images.githubusercontent.com/50922489/113596243-98419000-966c-11eb-93da-5bc8b471df0f.jpg)
![image](https://user-images.githubusercontent.com/25792361/113596425-dfc81c00-966c-11eb-9fa2-a9b8aa51b42a.png)
我做, 我做就是了

**Comment by sam01101** [comment]
> 所以有打算在 v1 实装吗

之前没有,我刚好写代码就一并加进去了

所以有了(

**Comment by Shigma** [comment]
帮大忙了，感谢采纳
