### ISSUE TITLE
守护进程启动后的日志

### ISSUE THREAD

**Issue by nekolr** [Mrs4s/go-cqhttp#765]
**环境信息**

go-cqhttp版本: go-cqhttp-v1.0.0-alpha1

**需要添加的功能内容**

作为守护进程启动后，日志信息要从哪里查看呢？如果没有能否添加日志？

**Comment by sam01101** [comment]
1. 有的
2. `logs/年-月-日.log`

**Comment by nekolr** [comment]
> 
> 
>     1. 有的
> 
>     2. `logs/年-月-日.log`

thanks!
