### ISSUE TITLE
希望在默认的at sender后自动添加一个换行\n

### ISSUE THREAD

**Issue by Zhongren233** [Mrs4s/go-cqhttp#767]
**环境信息**

go-cqhttp版本: v1.0.0

**需要添加的功能内容**

在默认的at sender后添加一个换行符

**Comment by Ink-33** [comment]
?

**Comment by sam01101** [comment]
「？」

**Comment by Yukari316** [comment]
？

**Comment by sam01101** [comment]
> **环境信息**
> 
> go-cqhttp版本: v1.0.0
> 
> **需要添加的功能内容**
> 
> 在默认的at sender后添加一个换行符

请问是否可以给出一个**充分的理由**来解释为什么要怎样做？

**Comment by Zhongren233** [comment]
我觉得应该补充一下 就是正常我发的信息是这样

昵称:*
id:*
活动点数排名:*
活动点数:*
活动歌曲排名:*
活动歌曲分数:*


如果atsender后，就变成了

@ZhongRen 昵称:*
id:*
活动点数排名:*
活动点数:*
活动歌曲排名:*
活动歌曲分数:*

**Comment by Ink-33** [comment]
> 我觉得应该补充一下 就是正常我发的信息是这样
> 
> 昵称:*
> id:*
> 活动点数排名:*
> 活动点数:*
> 活动歌曲排名:*
> 活动歌曲分数:*
> 
> 
> 如果atsender后，就变成了
> 
> @ZhongRen 昵称:*
> id:*
> 活动点数排名:*
> 活动点数:*
> 活动歌曲排名:*
> 活动歌曲分数:*
> 

这是你自己的问题，请自己添加换行符。

**Comment by Yukari316** [comment]
> 我觉得应该补充一下 就是正常我发的信息是这样
> 
> 昵称:*
> id:*
> 活动点数排名:*
> 活动点数:*
> 活动歌曲排名:*
> 活动歌曲分数:*
> 
> 
> 如果atsender后，就变成了
> 
> @ZhongRen 昵称:*
> id:*
> 活动点数排名:*
> 活动点数:*
> 活动歌曲排名:*
> 活动歌曲分数:*
> 

我寻思这应该自己去构建消息，at只是个cq码而已

**Comment by sam01101** [comment]
> 我觉得应该补充一下 就是正常我发的信息是这样
> 
> 昵称:*
> id:*
> 活动点数排名:*
> 活动点数:*
> 活动歌曲排名:*
> 活动歌曲分数:*
> 
> 如果atsender后，就变成了
> 
> @zhongren 昵称:*
> id:*
> 活动点数排名:*
> 活动点数:*
> 活动歌曲排名:*
> 活动歌曲分数:*

这个你可以在自己的代码中实现
