### ISSUE TITLE
支持手动设置POST上报Timeout阈值

### ISSUE THREAD

**Issue by Morn-zh** [Mrs4s/go-cqhttp#77]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.10
运行环境: windows_amd64
连接方式:http api

**bug内容**
如果本地服务器延迟响应，go-cqhttp会提示超时：context deadline exceeded,从而让后续的操作无法进行

**复现方法**
```
# python，本地服务器
# -*- coding: utf-8 -*-
from cqhttp import CQHttp
import time
bot = CQHttp(api_root='http://127.0.0.1:5700/'

@bot.on_message()
def handle_msg(event):
    time.sleep(30)
    # 以下的发送消息以及print操作都无法执行，提示context deadline exceeded
    print("30s")
    bot.send(event,"已经过去30s")

bot.run(host='127.0.0.1', port=5701)
```
报错截图：
![TIM截图20200811150027](https://user-images.githubusercontent.com/44546842/89867222-71b57d00-dbe3-11ea-8b49-742a60b57e4e.png)

猜测是需要设置个延迟的时间吧

**Comment by Mrs4s** [comment]
应用层问题.

**Comment by Mrs4s** [comment]
将在后续版本加入Timeout手动设置
