### ISSUE TITLE
更新gocq版本至v1.0.0-beta1后，反向ws使用快速回复发送字符串时会自动加全体成员

### ISSUE THREAD

**Issue by zht163** [Mrs4s/go-cqhttp#774]
**环境信息**

go-cqhttp版本: go-cqhttp_linux_amd64
运行环境: centos7
连接方式: 反向ws+aiocqhttp
使用协议: iPad

**bug内容**

govqhttp 从v0.9.38-fix1更新gocq版本至v1.0.0-beta1后，使用反向ws+aiocqhttp快速回复群消息时会自动加上@全体成员，即使没有管理员权限，回复指定消息正常，暂没发现其他异常
测试过低点的版本v0.9.40-fix3、v0.9.40-fix2也是这样
**复现方法**

aiocqhttp代码:
if context.get('message').startswith('/test'):
    return {'reply': "test"}

截图
![image](https://user-images.githubusercontent.com/48507961/113083889-9a8c9000-920f-11eb-87d6-06cad30bbf44.png)

回退版本后则没有自动加上全体成员

![image](https://user-images.githubusercontent.com/48507961/113084056-df182b80-920f-11eb-9c07-13840e3091c5.png)

即使快速回复的内容里有CQ码

![image](https://user-images.githubusercontent.com/48507961/113084666-0de2d180-9211-11eb-8c75-6f87c61dbe4f.png)

![image](https://user-images.githubusercontent.com/48507961/113084709-1f2bde00-9211-11eb-87ab-57734ad58e92.png)

**Comment by sam01101** [comment]
https://github.com/Mrs4s/go-cqhttp/blob/75b531e2dc6869a3f80740fce9aa21cb8bcd7da7/coolq/api.go#L890

`reply`需要`user_id`, 你没添加的话默认是0
当然我觉得可以PR来防止这种情况发生

**Comment by sam01101** [comment]
也有一个原因是因为文档的不清晰导致使用上有问题（别骂了别骂了）

**Comment by sam01101** [comment]
https://github.com/Mrs4s/go-cqhttp/blob/75b531e2dc6869a3f80740fce9aa21cb8bcd7da7/coolq/api.go#L889
至于怎么修，这里检查下
```go
context.Get("sender.user_id")
```
是不是存在就可以了
结果就是
```go
			} else if at && reply.Type == gjson.String && context.Get("sender.user_id") != nil {
```
（没实际测试，凭感觉的）

**Comment by sam01101** [comment]
有谁去测试下然后提个PR？

**Comment by sam01101** [comment]
^^^

**Comment by Yiwen-Chan** [comment]
将会在[fix](https://github.com/Mrs4s/go-cqhttp/pull/775/commits/f495001fac03fdba9550115359542f0b2e4470e7)修复
