### ISSUE TITLE
上传群 文件失败了 : server requires unsupported ftn upload

### ISSUE THREAD

**Issue by hanxiaoxin778** [Mrs4s/go-cqhttp#777]
**环境信息**

go-cqhttp版本: v1.0.0-beta1
运行环境: windows
连接方式: 反向ws
使用协议: iPad

**bug内容**

![QQ截图20210401044607](https://user-images.githubusercontent.com/56909786/113209167-47651c80-92a5-11eb-9373-4828a3c414a1.jpg)

**复现方法**

**Comment by sam01101** [comment]
多好的一个issue号码, 可惜被close了
你可以透过直接Edit来恢复被close状态, 不建议重开

**Comment by sam01101** [comment]
首先, 是否尝试过更换账号?

**Comment by hanxiaoxin778** [comment]
@sam01101 感谢答复，是的已经更换过了，我已经因为频繁加群封掉几个小号了，这个是实在找不到原因了才来提交，第一次在github提交问题.，是IPv4，IPv6没有勾选

**Comment by sam01101** [comment]
> @sam01101 感谢答复，是的已经更换过了，我已经因为频繁加群封掉几个小号了，这个是实在找不到原因了才来提交，第一次在github提交问题.，是IPv4，IPv6没有勾选

请问是否尝试过手动上传文件? 就是打开QQ客户端然后上传一个文件

如果再不行的话我建议你把机器人挂几天等风控过去再尝试

**Comment by hanxiaoxin778** [comment]
本地是可以正常上传的，包括直接post接口也是可以正常上传的。因为cookie会失效所以不太方便使用接口，当然如果go-cqhttp支持的话就太棒了XD。

**Comment by sam01101** [comment]
> 包括直接post接口也是可以正常上传的。

这里是指透过go-cqhttp的API调用可以上传?

**Comment by hanxiaoxin778** [comment]
是通过Fiddler抓包，手动填写参数请求的接口

**Comment by sam01101** [comment]
这个问题我无法独自处理, 要等 @Mrs4s 或其它贡献者过来复现一下

**Comment by sam01101** [comment]
明天再试, 晚安

**Comment by hanxiaoxin778** [comment]
好的晚安~ 果然大佬都是夜猫子。 刚才我刚提交issues就发现你回复了，我以为是机器人自动回复的... 还猜了一下按照#ID号来自定义回复QAQ

**Comment by sam01101** [comment]
草

**Comment by hanxiaoxin778** [comment]
![QQ图片20210401051315](https://user-images.githubusercontent.com/56909786/113212172-ff47f900-92a8-11eb-9fb6-7c78b644dce7.png)
这个是上传文件接口的协议头，ftn应该指的是 地址? 希望这个能有点作用QAQ。  晚安不用答复了快睡觉吧头发掉光了撸

**Comment by sam01101** [comment]
> ![QQ图片20210401051315](https://user-images.githubusercontent.com/56909786/113212172-ff47f900-92a8-11eb-9fb6-7c78b644dce7.png)
> 这个是上传文件接口的协议头，ftn应该指的是 地址? 希望这个能有点作用QAQ。 晚安不用答复了快睡觉吧头发掉光了撸

主要原因是因为没有可用的上传地址才导致这个错误

**Comment by hanxiaoxin778** [comment]
听大佬的！ 快晚安！天马上就要亮了！XD

**Comment by Mrs4s** [comment]
这个是需要支持另一种上传途径、看来还是得做一下

**Comment by hanxiaoxin778** [comment]
@Mrs4s 辛苦啦！！

**Comment by clacknya** [comment]
> 
> 
> https://github.com/Mrs4s/MiraiGo/blob/f3beaae4e4435f499a88245253b703d8a8892df0/client/group_file.go#L193-L195
> 
> 我这边看就是它有可能要你用IPv6来上传, 但目前还没有写有关IPv6的代码
> 如果可以的话这里建议你尝试强制使用IPv4, 如果本身就是IPv4当我没说

后续有计划支持 IPv6 吗？

**Comment by sam01101** [comment]
> > https://github.com/Mrs4s/MiraiGo/blob/f3beaae4e4435f499a88245253b703d8a8892df0/client/group_file.go#L193-L195
> > 我这边看就是它有可能要你用IPv6来上传, 但目前还没有写有关IPv6的代码
> > 如果可以的话这里建议你尝试强制使用IPv4, 如果本身就是IPv4当我没说
> 
> 后续有计划支持 IPv6 吗？

目前1.0不会, 后续版本有可能会增加

**Comment by Mrs4s** [comment]
这不是 `ipv6` 的问题

**Comment by bldq** [comment]
> @sam01101 感谢答复，是的已经更换过了，我已经因为频繁加群封掉几个小号了，这个是实在找不到原因了才来提交，第一次在github提交问题.，是IPv4，IPv6没有勾选

请问现在解决了吗？我也碰见了这个状况，环境和你的一毛一样，前两天还可以发送群文件，今天就不可以了。。

**Comment by Well2333** [comment]
我也碰到这个情况了，而且应该不是ipv6的问题，刚刚还能上传一会之后就不行了

**Comment by xianrui69** [comment]
> 我也碰到这个情况了，而且应该不是ipv6的问题，刚刚还能上传一会之后就不行了

+10086

**Comment by xianrui69** [comment]
我也是碰到这个情况，没有上传成功过

**Comment by xianrui69** [comment]
> 我也是碰到这个情况，没有上传成功过

然后我添加name参数就上传成功了貌似就。。。成功了

**Comment by ModChino** [comment]
> 

我也是添加name参数就成功了

**Comment by ModChino** [comment]
> > 我也遇到过这个情况，没有上传成功
> 
> 然后我加了名字参数就上传成功了就好像。。。成功了

我也是添加了name参数就成功了

**Comment by wheesys** [comment]
> > > 我也遇到过这个情况，没有上传成功
> > 
> > 
> > 然后我加了名字参数就上传成功了就好像。。。成功了
> 
> 我也是添加了name参数就成功了

请问是post还是get?一些别的配置方便说一下吗？我有name参数，post请求，一直提示这个

**Comment by wheesys** [comment]
> 这个是需要支持另一种上传途径、看来还是得做一下

大佬这个问题有后续吗？

**Comment by xianrui69** [comment]
> 
![G`T7A{HK1 P2RRC(19O%Y~G](https://user-images.githubusercontent.com/37205191/156686000-3b095968-c778-4868-acbd-00e11fc84104.png)
post

**Comment by xianrui69** [comment]
> > > > 我也遇到过这种情况，没有上传成功
> > > 
> > > 
> > > 然后我加了名字参数就成功了就好像。。。成功了
> > 
> > 
> > 我也是添加了name参数就成功了
> 
> 是post还是get？一些其他的方便说一下吗？
![K%C1FFKNR E`1 HNT88{Y$Q](https://user-images.githubusercontent.com/37205191/156686081-b0993101-130b-412b-93a5-a1e3bca4d171.png)
post

**Comment by ModChino** [comment]
> > > > > 我也遇到过这种情况，没有上传成功
> > > > 
> > > > 
> > > > 然后我加了名字参数就成功了就好像。。。成功了
> > > 
> > > 
> > > 我也是添加了name参数就成功了
> > 
> > 
> > 是post还是get？一些其他的方便说一下吗？
> > ![K%C1FFKNR E`1 HNT88{Y$Q](https://user-images.githubusercontent.com/37205191/156686081-b0993101-130b-412b-93a5-a1e3bca4d171.png)
> > post

我是写的Hoshino插件。。应该算是反向ws?
![image](https://user-images.githubusercontent.com/44693212/156687531-918af0db-d947-44b8-af64-b24b3476988b.png)

**Comment by wheesys** [comment]
> > > > > 我也遇到过这种情况，没有上传成功
> > > > 
> > > > 
> > > > 然后我加了名字参数就成功了就好像。。。成功了
> > > 
> > > 
> > > 我也是添加了name参数就成功了
> > 
> > 
> > 是post还是get？一些其他的方便说一下吗？
> > ![K%C1FFKNR E`1 HNT88{Y$Q](https://user-images.githubusercontent.com/37205191/156686081-b0993101-130b-412b-93a5-a1e3bca4d171.png)
> > post

嗯，和我的基本差不多，我这就是不行，有name也不行

**Comment by wheesys** [comment]
> > > > > > 我也遇到过这种情况，没有上传成功
> > > > > 
> > > > > 
> > > > > 然后我加了名字参数就成功了就好像。。。成功了
> > > > 
> > > > 
> > > > 我也是添加了name参数就成功了
> > > 
> > > 
> > > 是post还是get？一些其他的方便说一下吗？
> > > ![K%C1FFKNR E`1 HNT88{Y$Q](https://user-images.githubusercontent.com/37205191/156686081-b0993101-130b-412b-93a5-a1e3bca4d171.png)
> > > post
> 
> 我是写的Hoshino插件。。应该算是反向ws? ![image](https://user-images.githubusercontent.com/44693212/156687531-918af0db-d947-44b8-af64-b24b3476988b.png)


> > > > > > 我也遇到过这种情况，没有上传成功
> > > > > 
> > > > > 
> > > > > 然后我加了名字参数就成功了就好像。。。成功了
> > > > 
> > > > 
> > > > 我也是添加了name参数就成功了
> > > 
> > > 
> > > 是post还是get？一些其他的方便说一下吗？
> > > ![K%C1FFKNR E`1 HNT88{Y$Q](https://user-images.githubusercontent.com/37205191/156686081-b0993101-130b-412b-93a5-a1e3bca4d171.png)
> > > post
> 
> 嗯，和我的基本差不多，我这就是不行，有name也不行



> > > > > > 我也遇到过这种情况，没有上传成功
> > > > > 
> > > > > 
> > > > > 然后我加了名字参数就成功了就好像。。。成功了
> > > > 
> > > > 
> > > > 我也是添加了name参数就成功了
> > > 
> > > 
> > > 是post还是get？一些其他的方便说一下吗？
> > > ![K%C1FFKNR E`1 HNT88{Y$Q](https://user-images.githubusercontent.com/37205191/156686081-b0993101-130b-412b-93a5-a1e3bca4d171.png)
> > > post
> 
> 我是写的Hoshino插件。。应该算是反向ws? ![image](https://user-images.githubusercontent.com/44693212/156687531-918af0db-d947-44b8-af64-b24b3476988b.png)

我发正向ws,emm,就是不成功

**Comment by yuyuko233** [comment]
我这也不行

**Comment by copurxia** [comment]
我也遇到了"server requires unsupported ftn upload"

**Comment by xianrui69** [comment]
> > > > > > 我也遇到过这种情况，没有上传成功
> > > > > 
> > > > > 
> > > > > 然后我加了名字参数就成功了就好像。。。成功了
> > > > 
> > > > 
> > > > 我也是添加了name参数就成功了
> > > 
> > > 
> > > 是post还是get？一些其他的方便说一下吗？
> > > ![K%C1FFKNR E`1 HNT88{Y$Q](https://user-images.githubusercontent.com/37205191/156686081-b0993101-130b-412b-93a5-a1e3bca4d171.png)
> > > post
> 
> 我是写的Hoshino插件。。应该算是反向ws? ![image](https://user-images.githubusercontent.com/44693212/156687531-918af0db-d947-44b8-af64-b24b3476988b.png)

ws不知道，我用的http

**Comment by Nikaidou-Shinku** [comment]
天呐，这个还有后文吗…

**Comment by NanakoOfficial** [comment]
草，我也遇到这个报错了，各位大佬们怎么解决的

**Comment by fR0Z863xF** [comment]
同问，我使用的一个插件中有如下代码，可是有些文件能够上传成功，有些则报错如题
![image](https://user-images.githubusercontent.com/83159422/213208089-b5fef5c7-48ec-4cd3-ab7c-3bc22092f70f.png)
希望能有大佬解决

**Comment by Umamusume-Agnes-Digital** [comment]
同样的报错，
windows2012，
gocq1.0.0rc4
因为with tempfile.NamedTemporaryFile()的方法在nonebot2的文档说，windows不适用，所以如下所改，最后得到 server requires unsupported ftn upload的报错
```
async def upload_file(bot: Bot, event: MessageEvent, file_data: memoryview, filename: str):
    """上传临时文件"""
    if systems == "win" or "other":
        file_path = str(Path().joinpath(filename))
        with open(file_path,"wb+") as f:
            f.write(file_data)
        with open(file_path,"rb") as f:
            if isinstance(event, GroupMessageEvent):
                await bot.call_api(
                    "upload_group_file", group_id=event.group_id, file=f.name, name=filename
                )
```

**Comment by sd3970566** [comment]
这个问题解决了吗？我也遇到了啊server requires unsupported ftn upload的报错

**Comment by cuckoo711** [comment]
> 

我今天也遇到了这个问题，我尝试上传了一个没有内容的txt文件，一直报错，于是我尝试手动在qq客户端上传，才被告知不能上传空文件，你可以检查一下你是不是在测试的时候上传了一个空文件。

**Comment by langliverygood** [comment]
我也遇到这个问题了，name字段也填了，还是不行。慢慢测试发现，如果文件名中有时间（比如2025-01-01）字样，必上传失败，去掉文件名中的时间字样，就可以上传成功了

**Comment by langliverygood** [comment]
有的文件上传不成功，还有一种可能，腾讯服务器有文件扫描功能，估计是被识别成木马或者其他高风险文件了
