### ISSUE TITLE
【消息发送失败/go插件开发】发送字符串的机制在win10运行可以触发；而linux系统上不能正常发送

### ISSUE THREAD

**Issue by StrayCamel247** [Mrs4s/go-cqhttp#781]
**环境信息**

go-cqhttp版本: v1.0.0-beta1
运行环境: Linux version 5.4.0-65-generic (buildd@lcy01-amd64-018) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04))
连接方式: 插件代码执行事件监听/非ws
使用协议: ipad

**bug内容**

- 预先写好的指令触发机制-收到预定的指令而发送如下字符串
    - 代码路径[apps\handler.go func:MenuSendEvent](https://github.com/StrayCamel247/BotCamel/blob/69506359de26a49e072560c31fa1e46679c6afe2/apps/handler.go#L48)
    - 仓链接`https://github.com/StrayCamel247/BotCamel`
- 问题：同样的代码window10运行可以触发并发送字符串；而linux系统上不行正常发送字符串
```
======BotCamel基础功能=====
++ [menu 菜单 功能] 功能列表 0x0
======命运2基础功能========
++ [week 周报] 周报信息查询 0x1
++ [day 日报] 日报信息查看 0x2
++ [xiu nine 老九] 老九信息查询 0x3
++ [trial 试炼 train] 试炼最新动态 0x4
++ [dust 光尘] 赛季光尘商店 0x5
++ [random 骰子] 骰子功能 0x6
++ [perk 词条] 查询词条/模组信息 0x7
++ [item 物品] 查询物品信息-提供light-gg信息 0x8
++ [npc] 查询npc信息 0x9
++ [skill] 查询技能等信息 0xa
++ [pve] 查询pve信息 0xb
++ [pvp] 查询pvp信息 0xc
```
- 做过如下尝试
    - 分片开启关闭：都不行
    - 版本回退到0.9：本来就是用的0.9不行，升级到1.0后也不行
    - 字符串的行数减少：减少到一定行数可以；但是我发送更多行数的字符串（纯汉字）居然可以
    - 字符串的符号字符单独拉出来发送：可以发送`: +─├─·`，将其中的特殊字符换成字符`=`发送也是失败
 - 多行数的字符串（纯汉字）
 ```
 一个测试工程师走进一家酒吧，要了一杯啤酒
  一个测试工程师走进一家酒吧，要了一杯咖啡
  一个测试工程师走进一家酒吧，要了0.7杯啤酒
  一个测试工程师走进一家酒吧，要了-1杯啤酒
  一个测试工程师走进一家酒吧，要了232杯啤酒
  一个测试工程师走进一家酒吧，要了一杯洗脚水
  一个测试工程师走进一家酒吧，要了一杯蜥蜴
  一个测试工程师走进一家酒吧，要了一份asdfQwer@24dg!&*(@
  一个测试工程师走进一家酒吧，什么也没要
  一个测试工程师走进一家酒吧，又走出去又从窗户进来又从后门出去从下水道钻进来
  一个测试工程师走进一家酒吧，又走出去又进来又出去又进来又出去，最后在外面把老板打了一顿
  一个测试工程师走进一家酒吧，要了一杯烫烫烫的锟斤拷
  一个测试工程师走进一家酒吧，要了NaN杯Null
  一个测试工程师冲进一家酒吧，要了500T啤酒咖啡洗脚水野猫狼牙棒奶茶
  一个测试工程师把酒吧拆了
  一个测试工程师化装成老板走进一家酒吧，要了500杯啤酒并且不付钱
  一万个测试工程师在酒吧门外呼啸而过
  一个测试工程师走进一家酒吧，要了一杯啤酒';DROP TABLE 酒吧
  测试工程师们满意地离开了酒吧。
  然后一名顾客点了一份炒饭，酒吧炸了。
```
**复现方法**

- window启动并发送`menu`指令
![image](https://user-images.githubusercontent.com/26707191/113385654-242c9100-93bb-11eb-9698-0bb2304da465.png)
![image](https://user-images.githubusercontent.com/26707191/113385699-37d7f780-93bb-11eb-94cc-132c94e62d38.png)
- 而放在linux后启动发送`menu`指令
> 注意我先发送字符串之前打印一下，确保字符串构造没问题
![image](https://user-images.githubusercontent.com/26707191/113385793-65bd3c00-93bb-11eb-87a9-58ab5a70b85f.png)
发送指令后日志如下
![image](https://user-images.githubusercontent.com/26707191/113386412-c8630780-93bc-11eb-8b69-40ecafc4b375.png)

没有报错也没有日志信息，上图为println的结果信息

**Comment by timi137137** [comment]
此情况是由于腾讯风控系统导致，请尝试转为图片发送

**Comment by wdvxdr1123** [comment]
https://github.com/StrayCamel247/BotCamel/blob/69506359de26a49e072560c31fa1e46679c6afe2/apps/handler.go#L63
请尝试使用
```
		c.SendGroupMessage(m.GroupCode, message.NewSendingMessage().Append(message.NewText(res)), true)
```

**Comment by StrayCamel247** [comment]
> .Append

收到-谢谢提醒(ง •_•)ง

**Comment by StrayCamel247** [comment]
风控绕过机制
- 适当减少增加行数和字符串-不实用
- 前后加随机字符串-不可行
- 文字生成图片
    - 实用方便
    - 若没有汉字则直接使用`"image/draw"`包相关操作即可
    - 若涉及到汉字
        - 需要准备一个汉字相关的字体文件`xxx.ttf` 这里是我自己使用的ttf文件[github.com/StrayCamel247/BotCamel --apps/utils/chinese.ttf
 ](https://github.com/StrayCamel247/BotCamel/blob/main/apps/utils/chinese.ttf)  
        - 代码见文件：[`https://github.com/StrayCamel247/BotCamel/blob/main/apps/utils/imgHandler.go`](https://github.com/StrayCamel247/BotCamel/blob/02e369a9027604d3d7bc038eef33f03301983926/apps/utils/imgHandler.go#L85)
  
若有更好的方式 望告知：aboyinsky@outlook.com

**Comment by StrayCamel247** [comment]
TO: 作者

优化建议

考虑做一个发送消息失败的err返回吗

其中包括风控报错

**Comment by StrayCamel247** [comment]
golang 包版本问题

golang import  https://github.com/Mrs4s/go-cqhttp/  并不是1.0版本 而是0.9

我现在是用的 .gitmodules 方式克隆你们最新的代码到本地再用的replace方法加载的1.0版本 `replace github.com/Mrs4s/go-cqhttp => ./go-cqhttp`

若 包更新 望告知 (ง •_•)ง

**Comment by sam01101** [comment]
> TO: 作者
> 
> 优化建议
> 
> 考虑做一个发送消息失败的err返回吗
> 
> 其中包括风控报错

这个不是作者的范围了，这个啊这个
这个要求非常离谱，为什么呢

因为啊因为，我们太懒了

**Comment by sam01101** [comment]
老实说目前的错误其实不完整，而且有些错误还没返回
但，那个工程量是要求把全部代码看一次

可想而知

**Comment by sam01101** [comment]
会哭的

**Comment by Mrs4s** [comment]
> TO: 作者
> 
> 优化建议
> 
> 考虑做一个发送消息失败的err返回吗
> 
> 其中包括风控报错

之前写的时候感觉返回 `error` 的话上层处理会有点麻烦, 所以通过 `Id` 来标识状态了.
而且就算返回 `error` 也很难提供更多信息, 发不出去消息大部分都是服务端直接拦截掉了, 客户端只知道没发出去

**Comment by sam01101** [comment]
好耶

**Comment by sam01101** [comment]
草不是为什么这机器人现在能用了
