### ISSUE TITLE
收到了重复的加群消息

### ISSUE THREAD

**Issue by xiangxiangxiong9** [Mrs4s/go-cqhttp#787]
**环境信息**

go-cqhttp版本: daec9cf12cec5836fdf26e69330b41e5682b7a90 
运行环境: Ubuntu 21.04 arm64
连接方式: 反向WS
使用协议: iPad

**bug内容**

收到了重复的群成员进群事件[且存在于机器人日志当中]
且上报中的time和机器人日志当中出现的所有进群时间均一致 且 出现的QQ号早已加入了群聊 [甚至包括管理员]
**复现方法**

玄学问题...?突然出现一大堆进群事件直接把我这给限制了 [计算了一下，一共出现了45条]

**Comment by sam01101** [comment]
重复的事件是因为腾讯怕客户端收不到发了两次
这个gocq没去重, 如果可以希望目前自己自己处理

**Comment by xiangxiangxiong9** [comment]
> 重复的事件是因为腾讯怕客户端收不到发了两次
> 这个gocq没去重, 如果可以希望目前自己处理

好吧，那我等会创建数据库去了...
Closed
