### ISSUE TITLE
自定义CQ prefix

### ISSUE THREAD

**Issue by sam01101** [Mrs4s/go-cqhttp#788]
**环境信息**

go-cqhttp版本: v1.0 beta

**需要添加的功能内容**
突发奇想, 没啥用的
就是我看好像目前有很多CQ注入的受害者(对有些我害的)
想着, 如果把CQ换掉不就没法注入了吗?
那么, 如果每个人都自定义一个`CQ`就好了

请求: 自定义`CQ` prefix
限制两个大写的英文字, 比如 `QC`, `CC`

默认是`CQ`, 但可更改
![image](https://user-images.githubusercontent.com/25792361/113484090-22f18600-94d9-11eb-930e-c3f0c97e97b6.png)

**Comment by Mrs4s** [comment]
没啥用 暂时不考虑做
