### ISSUE TITLE
解密密码超时相关

### ISSUE THREAD

**Issue by Kyomotoi** [Mrs4s/go-cqhttp#794]
**环境信息**
go-cqhttp版本: v1.0.0-beta1
运行环境: debian10
连接方式: 反向ws
使用协议: macOS

**bug内容**
解密密码超时自动退出时，屏蔽输出现象依存

**复现方法**
设置中打开密码加密，启动，等待时效过期

**Comment by Ink-33** [comment]
windows无法复现，考虑linux专属bug（
