### ISSUE TITLE
添加相关事件缺失的 time 和 self_id 字段

### ISSUE THREAD

**Issue by kanrichan** [Mrs4s/go-cqhttp#796]
**环境信息**

go-cqhttp版本: v1.0.0-beta1

**需要添加的功能内容**

添加相关事件缺失的 time 和 self_id 字段
涉及事件如下：
- [好友戳一戳](https://docs.go-cqhttp.org/event/#%E5%A5%BD%E5%8F%8B%E6%88%B3%E4%B8%80%E6%88%B3)
- [群内戳一戳](https://docs.go-cqhttp.org/event/#%E7%BE%A4%E5%86%85%E6%88%B3%E4%B8%80%E6%88%B3)
- [群红包运气王提示](https://docs.go-cqhttp.org/event/#%E7%BE%A4%E7%BA%A2%E5%8C%85%E8%BF%90%E6%B0%94%E7%8E%8B%E6%8F%90%E7%A4%BA)
- [群成员荣誉变更提示](https://docs.go-cqhttp.org/event/#%E7%BE%A4%E6%88%90%E5%91%98%E8%8D%A3%E8%AA%89%E5%8F%98%E6%9B%B4%E6%8F%90%E7%A4%BA)
- [群成员名片更新](https://docs.go-cqhttp.org/event/#%E7%BE%A4%E6%88%90%E5%91%98%E5%90%8D%E7%89%87%E6%9B%B4%E6%96%B0)
- [接收到离线文件](https://docs.go-cqhttp.org/event/#%E6%8E%A5%E6%94%B6%E5%88%B0%E7%A6%BB%E7%BA%BF%E6%96%87%E4%BB%B6)
- [其他客户端在线状态变更](https://docs.go-cqhttp.org/event/#%E5%85%B6%E4%BB%96%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%9C%A8%E7%BA%BF%E7%8A%B6%E6%80%81%E5%8F%98%E6%9B%B4)
- [精华消息](https://docs.go-cqhttp.org/event/#%E7%B2%BE%E5%8D%8E%E6%B6%88%E6%81%AF)

**Comment by sam01101** [comment]
> **环境信息**
> 
> go-cqhttp版本: v1.0.0-beta1
> 
> **需要添加的功能内容**
> 
> 添加相关事件缺失的 time 和 self_id 字段
> 涉及事件如下：
> 
> * [好友戳一戳](https://docs.go-cqhttp.org/event/#%E5%A5%BD%E5%8F%8B%E6%88%B3%E4%B8%80%E6%88%B3)
> * [群内戳一戳](https://docs.go-cqhttp.org/event/#%E7%BE%A4%E5%86%85%E6%88%B3%E4%B8%80%E6%88%B3)
> * [群红包运气王提示](https://docs.go-cqhttp.org/event/#%E7%BE%A4%E7%BA%A2%E5%8C%85%E8%BF%90%E6%B0%94%E7%8E%8B%E6%8F%90%E7%A4%BA)
> * [群成员荣誉变更提示](https://docs.go-cqhttp.org/event/#%E7%BE%A4%E6%88%90%E5%91%98%E8%8D%A3%E8%AA%89%E5%8F%98%E6%9B%B4%E6%8F%90%E7%A4%BA)
> * [群成员名片更新](https://docs.go-cqhttp.org/event/#%E7%BE%A4%E6%88%90%E5%91%98%E5%90%8D%E7%89%87%E6%9B%B4%E6%96%B0)
> * [接收到离线文件](https://docs.go-cqhttp.org/event/#%E6%8E%A5%E6%94%B6%E5%88%B0%E7%A6%BB%E7%BA%BF%E6%96%87%E4%BB%B6)
> * [其他客户端在线状态变更](https://docs.go-cqhttp.org/event/#%E5%85%B6%E4%BB%96%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%9C%A8%E7%BA%BF%E7%8A%B6%E6%80%81%E5%8F%98%E6%9B%B4)
> * [精华消息](https://docs.go-cqhttp.org/event/#%E7%B2%BE%E5%8D%8E%E6%B6%88%E6%81%AF)

tql, 谢谢整理

**Comment by Mrs4s** [comment]
我看代码似乎是有相关字段的, 请问是文档未完善还是怎么说

**Comment by Yiwen-Chan** [comment]
文档还没补充完，好像都鸽了

**Comment by sam01101** [comment]
> 文档还没补充完，好像都鸽了

是的，鸽了
