### ISSUE TITLE
建议增加支持企业QQ协议.

### ISSUE THREAD

**Issue by wuqiong** [Mrs4s/go-cqhttp#807]
**环境信息**

go-cqhttp版本: 
后续版本
**需要添加的功能内容**

作者有没有计划新增支持企业QQ协议啊.

**Comment by Mrs4s** [comment]
没号

**Comment by sam01101** [comment]
#633 
前面也说过，没号

如果有人愿意提供企业号用于测试的话会添加的

_（我朋友有，但他的企业号是真的企业用的，存在隐私问题_

**Comment by sam01101** [comment]
建议以后有号而且能够提供的时候再开issue

**Comment by wuqiong** [comment]
> 建议以后有号而且能够提供的时候再开issue

我这边可以提供企业号用于测试开发

**Comment by sam01101** [comment]
> > 建议以后有号而且能够提供的时候再开issue
> 
> 我这边可以提供企业号用于测试开发

非常感谢, 请问是否可以进开发群一起详细了解?

**Comment by sam01101** [comment]
开发交流群: `192548878`

**Comment by Mrs4s** [comment]
已支持
