### ISSUE TITLE
后续版本会推出好友赞这个api吗

### ISSUE THREAD

**Issue by suhexia** [Mrs4s/go-cqhttp#809]
**环境信息**

go-cqhttp版本: 

**需要添加的功能内容**
就是点名片赞，我看onebot里面的文档是支持的（公开api的send_like），所以就来问下

**Comment by ishkong** [comment]
该API为预计不实现API
今后的版本预计也不会支持

**Comment by sam01101** [comment]
>该API为预计不实现API
今后的版本预计也不会支持

**Comment by sam01101** [comment]
其实也不必立即否决, 考虑但机会细微
如果要支持肯定排最后才支持, 先吧目前的issue和功能全部解决, 1.0稳定了
再看下
