### ISSUE TITLE
关于CQ码的建议

### ISSUE THREAD

**Issue by chenxuan353** [Mrs4s/go-cqhttp#81]
建议增加替代消息字段，解析失败时，存在替代消息则使用替代消息发送而不是原样发送...
比如增加一个alt=text这样的字段，参数只接受文本

**Comment by Mrs4s** [comment]
目前我们正在统一相关协议，请到 [CQHTTP-Protocol](https://github.com/cqhttp/cqhttp-protocol) PR或者追踪相关进度
