### ISSUE TITLE
断网后重连失败，显示"登陆时发生致命错误"

### ISSUE THREAD

**Issue by Louisover** [Mrs4s/go-cqhttp#811]
**环境信息**

go-cqhttp版本: v1.0.0-beta2
运行环境: 安卓使用linux deploy搭建的archlinux
连接方式: 反向ws
使用协议: ipad

**bug内容**

[WARNING]: Bot已离线: Connection lost.
[WARNING]: 尝试重连...
[FATAL]: 登录时发生致命错误: Packet failed to send: write tcp 局域网ip:端口->ip地址:端口: use of closed network connection

**复现方法**

关闭所有网络然后重连(进电梯的时候经常出现)

**Comment by Ink-33** [comment]
#810
