### ISSUE TITLE
【功能建议】实现onebot标准中的状态码规范

### ISSUE THREAD

**Issue by KUNzfw** [Mrs4s/go-cqhttp#812]
**环境信息**

go-cqhttp版本: 1.0.0-beta2

**需要添加的功能内容**

当前版本的go-cqhttp的http状态码和ws返回数据中的retcode和[onebot v11标准](https://github.com/howmanybots/onebot/tree/master/v11/specs)不一致。

例如：onebot标准中当access token未提供时返回401，不符合时返回403，而go-cqhttp中统一返回了401

**Comment by sam01101** [comment]
> **环境信息**
> 
> go-cqhttp版本: 1.0.0-beta2
> 
> **需要添加的功能内容**
> 
> 当前版本的go-cqhttp的http状态码和ws返回数据中的retcode和[onebot v11标准](https://github.com/howmanybots/onebot/tree/master/v11/specs)不一致。
> 
> 例如：onebot标准中当access token未提供时返回401，不符合时返回403，而go-cqhttp中统一返回了401

这个我可以考虑
