### ISSUE TITLE
管理员通过群私聊群成员 API 返回异常 实际发送成功

### ISSUE THREAD

**Issue by 502647092** [Mrs4s/go-cqhttp#813]
**环境信息**

go-cqhttp版本: master分支
运行环境: linux
连接方式: http
使用协议: ipad

**bug内容**
管理员通过群私聊群成员 API 返回异常 实际发送成功

**复现方法**
管理员通过群私聊群成员

**Comment by Mrs4s** [comment]
能否贴一下API返回了什么异常

**Comment by sam01101** [comment]
> **环境信息**
> 
> go-cqhttp版本: master分支
> 运行环境: linux
> 连接方式: http
> 使用协议: ipad
> 
> **bug内容**
> 管理员通过群私聊群成员 API 返回异常 实际发送成功
> 
> **复现方法**
> 管理员通过群私聊群成员

管理员是谁？群成员又是什么身份？
怎么返回异常？有没有有关的错误信息？
复现方法不清晰

**Comment by 502647092** [comment]
> 能否贴一下API返回了什么异常

```
{
  "data": null,
  "msg": "SEND_MSG_API_ERROR",
  "retcode": 100,
  "status": "failed",
  "wording": "请参考输出"
}
```

但是实际上控制台没有任何输出(已开启DEBUG)

**Comment by sam01101** [comment]
> > 能否贴一下API返回了什么异常
> 
> ```
> {
>   "data": null,
>   "msg": "SEND_MSG_API_ERROR",
>   "retcode": 100,
>   "status": "failed",
>   "wording": "请参考输出"
> }
> ```
> 
> 但是实际上控制台没有任何输出(已开启DEBUG)

> 管理员是谁？群成员又是什么身份？
复现方法不清晰

**Comment by 502647092** [comment]
> > **环境信息**
> > go-cqhttp版本: master分支
> > 运行环境: linux
> > 连接方式: http
> > 使用协议: ipad
> > **bug内容**
> > 管理员通过群私聊群成员 API 返回异常 实际发送成功
> > **复现方法**
> > 管理员通过群私聊群成员
> 
> 管理员是谁？群成员又是什么身份？
> 怎么返回异常？有没有有关的错误信息？
> 复现方法不清晰

复现方法
- 使用 `master分支` 代码 `go build` 二进制文件
- 启动机器人
- 均使用下列HTTP请求代码
```
POST 127.0.0.1:5700/send_msg
Authorization: Bearer 123456
Content-Type: application/json

{
  "user_id": "2059065941",
  "group_id": "908503059",
  "message": "通过群私聊测试"
}
```
- 测试1
  - 机器人和测试用户未在同一个群 不是好友
  - 发送消息失败 控制台输出 不是好友 无法发送
  - 接口返回失败 请参考输出
- 测试2
  - 机器人添加测试用户后
  - 发送消息 成功 测试用户收到消息
  - 接口返回成功
- 测试3
  - 机器人和测试用户添加到同一个群 并且机器人是管理员
  - 发送消息 成功 测试用户收到消息
  - 接口返回成功
- 测试4
  - 机器人和测试用户在同一个群 机器人是管理员 机器人删除测试用户好友
  - 发送消息 成功 测试用户收到消息
  - 接口返回失败 请参考输出

**Comment by sam01101** [comment]
记得取消屏蔽机器人对好友的屏蔽
可以关了

**Comment by sam01101** [comment]
返回 55 错误就是机器人本身屏蔽了好友的错误
腾讯的客户端在删除好友后自动屏蔽

**Comment by 502647092** [comment]
> 返回 55 错误就是机器人本身屏蔽了好友的错误
> 腾讯的客户端在删除好友后自动屏蔽

我知道删除后会自动屏蔽
我手动打开屏蔽的

及时不执行删除操作
新拉一个测试账号2进群
机器人通过群发送给测试账号2
结果也是
发送消息 成功 测试用户收到消息
接口返回失败 请参考输出

**Comment by Mrs4s** [comment]
感谢测试，这个应该是一个特殊情况，我看怎么处理一下

**Comment by sam01101** [comment]
哦我知道问题了, 我忘记加返回`id`了

**Comment by 502647092** [comment]
> 哦我知道问题了, 我忘记加返回`id`了

emmm 能修复一下嘛 我自己编译就好

**Comment by Ink-33** [comment]
> > 哦我知道问题了, 我忘记加返回`id`了
> 
> emmm 能修复一下嘛 我自己编译就好

#818
