### ISSUE TITLE
手Q私聊回复消息异常

### ISSUE THREAD

**Issue by Mmx233** [Mrs4s/go-cqhttp#814]
**环境信息**

go-cqhttp版本: v1.0.0-beta2
运行环境: linux amd64
连接方式: http post
使用协议: http

**bug内容**

+ 在私聊中，手机QQ私聊消息无法正常显示回复（reply），变为类似普通消息，群聊消息正常，pc端正常
+ 回复后在首页中信息简要为空
+ 在三台手机上测试后，两台复现，一台直接接收不到回复
+ 在 https://github.com/Mrs4s/go-cqhttp/issues/253 中提过相似bug并已标记为已修复，此次是在安卓10中再次出现
电脑：
![YN16UUUKT`2L$MOMG}{)JYT](https://user-images.githubusercontent.com/36563672/114276093-c30a5a80-9a57-11eb-878b-30ed58df4f33.png)
手机：
![71D16BB812C777F904EB4CF2E5B87A18](https://user-images.githubusercontent.com/36563672/114275807-838f3e80-9a56-11eb-8d90-fe9fbedeec20.jpg)
手机首页：
![Screenshot_20210410_234426_com tencent mobileqq](https://user-images.githubusercontent.com/36563672/114275947-02847700-9a57-11eb-99e3-78f7e69d6830.png)

**复现方法**

私聊中使用回复[CQ:reply,id=xxx]

**Comment by sam01101** [comment]
临时急救方法：
使用最新版本，打开 `extra-reply-at`
你会发现多了很多数据，现在请把`id`删除，直接发送其它信息
把 `qq, time, text, seq` 全部元素当成普通`reply`发送

你看下这样是否还会有这个问题出现，我这个更新主要就是想紧急解决这个问题的

**Comment by Mmx233** [comment]
> 临时急救方法：
> 使用最新版本，打开 `extra-reply-at`
> 你会发现多了很多数据，现在请把`id`删除，直接发送其它信息
> 把 `qq, time, text, seq` 全部元素当成普通`reply`发送
> 
> 你看下这样是否还会有这个问题出现，我这个更新主要就是想紧急解决这个问题的

仍然异常
+ http post数据
+ get_msg数据
+ 发送的消息

![image](https://user-images.githubusercontent.com/36563672/114290086-85d1b700-9aaf-11eb-9c8d-0568db644519.png)
手机：
![Screenshot_20210411_101029_com tencent mobileqq](https://user-images.githubusercontent.com/36563672/114289928-363ebb80-9aae-11eb-9438-f0aad719b364.png)

**Comment by sam01101** [comment]
> > 临时急救方法：
> > 使用最新版本，打开 `extra-reply-at`
> > 你会发现多了很多数据，现在请把`id`删除，直接发送其它信息
> > 把 `qq, time, text, seq` 全部元素当成普通`reply`发送
> > 你看下这样是否还会有这个问题出现，我这个更新主要就是想紧急解决这个问题的
> 
> 仍然异常
> 
> * http post数据
> * get_msg数据
> * 发送的消息
> 
> ![image](https://user-images.githubusercontent.com/36563672/114290115-b87baf80-9aaf-11eb-9102-8f46cd968c88.png)
> 手机：
> ![Screenshot_20210411_101029_com tencent mobileqq](https://user-images.githubusercontent.com/36563672/114289928-363ebb80-9aae-11eb-9438-f0aad719b364.png)

这个问题是不是在群里就不会出现？

**Comment by Mmx233** [comment]
> > > 临时急救方法：
> > > 使用最新版本，打开 `extra-reply-at`
> > > 你会发现多了很多数据，现在请把`id`删除，直接发送其它信息
> > > 把 `qq, time, text, seq` 全部元素当成普通`reply`发送
> > > 你看下这样是否还会有这个问题出现，我这个更新主要就是想紧急解决这个问题的
> > 
> > 仍然异常
> > 
> > * http post数据
> > * get_msg数据
> > * 发送的消息
> > 
> > ![image](https://user-images.githubusercontent.com/36563672/114290115-b87baf80-9aaf-11eb-9102-8f46cd968c88.png)
> > 手机：
> > ![Screenshot_20210411_101029_com tencent mobileqq](https://user-images.githubusercontent.com/36563672/114289928-363ebb80-9aae-11eb-9438-f0aad719b364.png)
> 
> 这个问题是不是在群里就不会出现？

是的

**Comment by sam01101** [comment]
那就好，这个找天看下

**Comment by wdvxdr1123** [comment]
请尝试使用版本 [54cef1f](https://github.com/Mrs4s/go-cqhttp/actions/runs/1030458299)

**Comment by Mmx233** [comment]
> 请尝试使用版本 [54cef1f](https://github.com/Mrs4s/go-cqhttp/actions/runs/1030458299)

有效，已修复
