### ISSUE TITLE
session.event.comment get empty content, but the user sure himself type the comment

### ISSUE THREAD

**Issue by ChateauXiao** [Mrs4s/go-cqhttp#82]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.17
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
when a stranger try to enter my own qq group and and comment content when commit a request, but the nonebot get empty empty content in session.event.comment. .

**复现方法**
always ocurrs

**Comment by Mrs4s** [comment]
#80
