### ISSUE TITLE
文件上传进度获取、以及上传限速

### ISSUE THREAD

**Issue by Quan666** [Mrs4s/go-cqhttp#828]
**环境信息**

go-cqhttp版本: 
最新
**需要添加的功能内容**

希望实现
1. 通过上传任务id之类的信息实时获取文件上传进度、上传状态
2. 获取当前所有上传任务列表
3. 限制上传的最大速度，解决小水管服务器因为上传文件而把带宽占满导致的网络阻塞问题

**Comment by sam01101** [comment]
建议首先处理 #825 的`async`返回码
然后再返回进程id（类似）

**Comment by Ink-33** [comment]
![下雨了](https://user-images.githubusercontent.com/51873347/114433982-0d750e00-9bf5-11eb-8699-c255e942a005.jpg)

**Comment by sam01101** [comment]
> **环境信息**
> 
> go-cqhttp版本:
> 最新
> **需要添加的功能内容**
> 
> 希望实现
> 
> 1. 通过上传任务id之类的信息实时获取文件上传进度、上传状态
> 2. 获取当前所有上传任务列表
> 3. 限制上传的最大速度，解决小水管服务器因为上传文件而把带宽占满导致的网络阻塞问题

您好，这个需求如果有空可以自己帮忙PR一下吗
~遵循着自己的问题自己解决原则（并没有~

这个提出来真的挺好的，我也想要（

**Comment by Quan666** [comment]
> > **环境信息**
> > 
> > go-cqhttp版本:
> > 最新
> > **需要添加的功能内容**
> > 
> > 希望实现
> > 
> > 1. 通过上传任务id之类的信息实时获取文件上传进度、上传状态
> > 2. 获取当前所有上传任务列表
> > 3. 限制上传的最大速度，解决小水管服务器因为上传文件而把带宽占满导致的网络阻塞问题
> 
> 您好，这个需求如果有空可以自己帮忙PR一下吗
> ~遵循着自己的问题自己解决原则（并没有~
> 
> 这个提出来真的挺好的，我也想要（

等我学会go(

**Comment by sam01101** [comment]
![-250e6e7df241f2ce](https://user-images.githubusercontent.com/25792361/114435583-e4ee1380-9bf6-11eb-8a87-cfb395971444.jpg)

**Comment by Yiwen-Chan** [comment]
![](8a0ef4509e3791701874a636048abd76.image,url=http://gchat.qpic.cn/gchatpic_new/213864964/2182548878-2466587547-8A0EF4509E3791701874A636048ABD76/0?term=3)

**Comment by Mrs4s** [comment]
挺麻烦的, 估计短期不会做emmm

**Comment by LingMuXing** [comment]
这功能没多少人用吧。emmmmmm

**Comment by sam01101** [comment]
前端显示用

在 2021年5月15日週六 下午9:26，林沐馨 ***@***.***> 寫道：

**Comment by NagisaCo** [comment]
mark一下
上传大文件时提示上传进度应该挺有用的
