### ISSUE TITLE
拉机器人进群，收到事件，要返回什么内容，才会确认并自动进群啊

### ISSUE THREAD

**Issue by leoguan88** [Mrs4s/go-cqhttp#83]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.17
运行环境: windows_amd64
连接方式: Http

**bug内容**
请问一下，拉机器人进群，收到事件，要返回什么内容，才会确认并自动进群啊？
以前是在Http请求中，回复："{"approve": true}"; 现在，这样返回，并不会进群。。。。

**复现方法**
请在这里分步骤的描述如何复现这个bug
邀请机器进群，收到邀请进群事件
在事件中，直接返回 "{"approve": true}"，但机器人，并不会进群

**Comment by Mrs4s** [comment]
请使用新版本
