### ISSUE TITLE
v1.0.0-beta3版对CQ码、部分字符消息处理有问题

### ISSUE THREAD

**Issue by BlackcatWatcher** [Mrs4s/go-cqhttp#830]
**环境信息**
go-cqhttp版本: v1.0.0-beta3
运行环境: windows - amd64
连接方式: 正向ws
使用协议: ws
post-format: string

**bug内容**
新版字符处理有问题，导致发送消息错误并后返回“SEND_MSG_API_ERROR”、“请参考消息输出”，使用v0.9.40-fix4版则全部正常发送。使用golang编写，试过将[]&符号转义为&#91;之类，试过直接使用json.Marshal和jsonEncoder.SetEscapeHTML(false)的方式均错误。

**复现方法**
1、发送纯图片消息“[CQ:image,file=file:///C:/image/001.jpg]”会返回错误，但在CQ码前面或后面加个空格或\n都能发送成功。
2、某些摸不着头脑的错误消息，如：
成功发送-"这个武器的紫卡是这样的：\n【空刃双刀(近战)】●●●●●(1.48)\n -这把武器可以合成 觉醒双枪 暗黑分合剑 救赎者,记得保留.\n"
失败发送-"这个武器的紫卡是这样的：\n【席瓦 & 神盾(近战)】●●●●○(1.15)\n"
失败发送-"这个武器的紫卡是这样的：\n【席瓦 \u0026 神盾(近战)】●●●●○(1.15)\n"
失败发送（更换了&符号）-"这个武器的紫卡是这样的：\n【席瓦 ＆ 神盾(近战)】●●●●○(1.15)\n"
失败发送-"这个武器的紫卡是这样的：\n【悦音 PRIME(副武器)】●●○○○(0.75)\n"
成功发送-"已向管理员反馈：\n这个武器的紫卡是这样的： \\n 【席瓦 & 神盾 (近战) 】●●●●○ (1.15)\\n"

**Comment by sam01101** [comment]
fix4 是 LTS（

**Comment by sam01101** [comment]
请问是否尝试过post-format: array?

**Comment by BlackcatWatcher** [comment]
没试过，要改代码挺麻烦的，有空再试

**Comment by sam01101** [comment]
然后，尝试使用官方客户端发送一次
如果还是不行可能是风控

**Comment by BlackcatWatcher** [comment]
啥叫官方客户端，QQ吗..问题是我刚刚试过俩版本，9.40和1.0.0，一个正常发送一个发送失败，都是可复现的，特别是第一条发送图片这个就不可能是风控。

**Comment by BlackcatWatcher** [comment]
而且device信息都是相同的，只是替换了版本。

**Comment by sam01101** [comment]
这个有待复现，你如果可以用beta4就先用吧，这个是TLS

**Comment by Mrs4s** [comment]
删掉 session.token试试

**Comment by BlackcatWatcher** [comment]
gocq是优先支持array的话那我就换过去好了。没看到1.0.0的beta4，可能还没发布？我现在先用9.40。我在换到1.0.0时候是全删只留个exe，重新登陆的，然后发现bug，然后换9.40发现正常。

**Comment by sam01101** [comment]
> gocq是优先支持array的话那我就换过去好了。没看到1.0.0的beta4，可能还没发布？我现在先用9.40。我在换到1.0.0时候是全删只留个exe，重新登陆的，然后发现bug，然后换9.40发现正常。

beta3（
这个稳定性不错
