### ISSUE TITLE
按登录账号创建缓存目录

### ISSUE THREAD

**Issue by icarus-ai** [Mrs4s/go-cqhttp#834]
**环境信息**

go-cqhttp版本: v1.0.0-beta3

**需要添加的功能内容**

按登录账号创建缓存目录

登录QQ 12345
对应的缓存目录
`12345`
`    12345/image`
`    12345/cache`
`    12345/videos`
`    12345/record`
`...`

**Comment by sam01101** [comment]
不太建议分开，因为缓存共用的影响不大，而且还可以加速上传/发送文件图片的速度

**Comment by icarus-ai** [comment]
> 不太建议分开，因为缓存共用的影响不大，而且还可以加速上传/发送文件图片的速度

两个QQ公用数据库消息id不重复? 
能不能把数据库单独出来呢?

**Comment by anye-star** [comment]
应该以"data/QQ号"的格式创建对应账号的缓存目录

**Comment by ishkong** [comment]
个人认为意义不是很大，当前版本，gocqhttp仅支持同时登录一个账号，更换账号可以考虑复制到别的文件夹再运行gocqhttp，这样也能做到缓存独立

**Comment by sam01101** [comment]
> > 不太建议分开，因为缓存共用的影响不大，而且还可以加速上传/发送文件图片的速度
> 
> 两个QQ公用数据库消息id不重复?
> 能不能把数据库单独出来呢?

自定义数据库在干了。。。

**Comment by icarus-ai** [comment]
> 个人认为意义不是很大，当前版本，gocqhttp仅支持同时登录一个账号，更换账号可以考虑复制到别的文件夹再运行gocqhttp，这样也能做到缓存独立

支持指定配置文件路径和复制cqhttp到其他文件夹运行???啊这😞

**Comment by anye-star** [comment]
> > > 不太建议分开，因为缓存共用的影响不大，而且还可以加速上传/发送文件图片的速度
> > 
> > 
> > 两个QQ公用数据库消息id不重复?
> > 能不能把数据库单独出来呢?
> 
> 自定义数据库在干了。。。

那额外问一下能不能把logs文件夹里的输出关掉

**Comment by sam01101** [comment]
> > > > 不太建议分开，因为缓存共用的影响不大，而且还可以加速上传/发送文件图片的速度
> > > 
> > > 
> > > 两个QQ公用数据库消息id不重复?
> > > 能不能把数据库单独出来呢?
> > 
> > 
> > 自定义数据库在干了。。。
> 
> 那额外问一下能不能把logs文件夹里的输出关掉

这个自己实现，定时删除log即可

**Comment by sam01101** [comment]
> > 个人认为意义不是很大，当前版本，gocqhttp仅支持同时登录一个账号，更换账号可以考虑复制到别的文件夹再运行gocqhttp，这样也能做到缓存独立
> 
> 支持指定配置文件路径和复制cqhttp到其他文件夹运行???啊这😞

完全可以自己实现的

**Comment by icarus-ai** [comment]
> > > 不太建议分开，因为缓存共用的影响不大，而且还可以加速上传/发送文件图片的速度
> > 
> > 
> > 两个QQ公用数据库消息id不重复?
> > 能不能把数据库单独出来呢?
> 
> 自定义数据库在干了。。。

好耶

**Comment by Ink-33** [comment]
![868642b7e13a8d1.jpg](https://user-images.githubusercontent.com/51873347/114657520-d9980680-9d22-11eb-8828-75aae2196145.jpg)

**Comment by Yiwen-Chan** [comment]
我觉得没必要增加过多赘余内容影响稳定性能，单独复制一份运行更加好

**Comment by Mrs4s** [comment]
自定义数据库应该会在模块化搞定后加上, 目前主要问题其实是引用太多库导致编译出来的二进制太大.

**Comment by icarus-ai** [comment]
> 我觉得没必要增加过多多余的内容影响稳定性能，单独复制一份运行更加好

按账号命名数据库会影响稳定性???

**Comment by sam01101** [comment]
> > 我觉得没必要增加过多多余的内容影响稳定性能，单独复制一份运行更加好
> 
> 按账号命名数据库会影响稳定性???

是指，没必要添加可以自己实现的功能来浪费空间和性能

**Comment by Mrs4s** [comment]
另外说下目前数据库的情况:

1. 目前数据库是用的 `leveldb`.
2. key 使用的 群号 + 消息序号 来生成的.
3. `image` 等资源文件名是使用的该文件源文件的md5.
4. 所有目录和文件的创建和写入都是以工作目录来的

所以目前混用账号数据其实并没有什么太大的影响

**Comment by icarus-ai** [comment]
> > > 我觉得没必要增加过多多余的内容影响稳定性能，单独复制一份运行更加好
> > 
> > 
> > 按账号命名数据库会影响稳定性???
> 
> 是指，没必要添加可以自己实现的功能来浪费空间和性能

每次更新源码都要再改好几个地方😞

**Comment by icarus-ai** [comment]
> 另外说下目前数据库的情况:
> 
> 1. 目前数据库是用的 `leveldb`.
> 2. key 使用的 群号 + 消息序号 来生成的.
> 3. `image` 等资源文件名是使用的该文件源文件的md5.
> 4. 所有目录和文件的创建和写入都是以工作目录来的
> 
> 所以目前混用账号数据其实并没有什么太大的影响

所以问题回到了这里[#issuecomment-819209757](https://github.com/Mrs4s/go-cqhttp/issues/834#issuecomment-819209757)

两个bot在同一个群收到不同消息或者收到同一个QQ发来的不同私聊，消息序号有没有重复的可能?

**Comment by Mrs4s** [comment]
> > 另外说下目前数据库的情况:
> > 
> > 1. 目前数据库是用的 `leveldb`.
> > 2. key 使用的 群号 + 消息序号 来生成的.
> > 3. `image` 等资源文件名是使用的该文件源文件的md5.
> > 4. 所有目录和文件的创建和写入都是以工作目录来的
> > 
> > 所以目前混用账号数据其实并没有什么太大的影响
> 
> 所以问题回到了这里[#issuecomment-819209757](https://github.com/Mrs4s/go-cqhttp/issues/834#issuecomment-819209757)
> 
> 两个bot在同一个群收到不同消息或者收到同一个QQ发来的不同私聊，消息序号有没有重复的可能?

理论上不会, 我是尽量保证不同bot收到的同一个会话的同一个消息ID一致

**Comment by icarus-ai** [comment]
> > > 另外说下目前数据库的情况:
> > > 
> > > 1. 目前数据库是用的 `leveldb`.
> > > 2. key 使用的 群号 + 消息序号 来生成的.
> > > 3. `image` 等资源文件名是使用的该文件源文件的md5.
> > > 4. 所有目录和文件的创建和写入都是以工作目录来的
> > > 
> > > 所以目前混用账号数据其实并没有什么太大的影响
> > 
> > 
> > 所以问题回到了这里[#issuecomment-819209757](https://github.com/Mrs4s/go-cqhttp/issues/834#issuecomment-819209757)
> > 两个bot在同一个群收到不同消息或者收到同一个QQ发来的不同私聊，消息序号有没有重复的可能?
> 
> 理论上不会, 我是尽量保证不同bot收到的同一个会话的同一个消息ID一致

好的👌

**Comment by icarus-ai** [comment]
那我关这个了

**Comment by sam01101** [comment]
> > 另外说下目前数据库的情况:
> > 
> > 1. 目前数据库是用的 `leveldb`.
> > 2. key 使用的 群号 + 消息序号 来生成的.
> > 3. `image` 等资源文件名是使用的该文件源文件的md5.
> > 4. 所有目录和文件的创建和写入都是以工作目录来的
> > 
> > 所以目前混用账号数据其实并没有什么太大的影响
> 
> 所以问题回到了这里[#issuecomment-819209757](https://github.com/Mrs4s/go-cqhttp/issues/834#issuecomment-819209757)
> 
> 两个bot在同一个群收到不同消息或者收到同一个QQ发来的不同私聊，消息序号有没有重复的可能?
> 就像抄判答案抄蹿行那种

老实说，crc32来hash会重复吗
![55f58a47bf13d396](https://user-images.githubusercontent.com/25792361/114658810-09e0a480-9d25-11eb-9153-b2ebf85cfde8.jpg)

**Comment by icarus-ai** [comment]
> > > 另外说下目前数据库的情况:
> > > 
> > > 1. 目前数据库是用的 `leveldb`.
> > > 2. key 使用的 群号 + 消息序号 来生成的.
> > > 3. `image` 等资源文件名是使用的该文件源文件的md5.
> > > 4. 所有目录和文件的创建和写入都是以工作目录来的
> > > 
> > > 所以目前混用账号数据其实并没有什么太大的影响
> > 
> > 
> > 所以问题回到了这里[#issuecomment-819209757](https://github.com/Mrs4s/go-cqhttp/issues/834#issuecomment-819209757)
> > 两个bot在同一个群收到不同消息或者收到同一个QQ发来的不同私聊，消息序号有没有重复的可能?
> > 就像抄判答案抄蹿行那种
> 
> 老实说，crc32来hash会重复吗
> ![55f58a47bf13d396](https://user-images.githubusercontent.com/25792361/114658810-09e0a480-9d25-11eb-9153-b2ebf85cfde8.jpg)

crc32是群号或者QQ号+消息id得来的，两个bot在同一个群的不同消息id重复了回复和撤回就有可能出问题

**Comment by sam01101** [comment]
> > > > 另外说下目前数据库的情况:
> > > > 
> > > > 1. 目前数据库是用的 `leveldb`.
> > > > 2. key 使用的 群号 + 消息序号 来生成的.
> > > > 3. `image` 等资源文件名是使用的该文件源文件的md5.
> > > > 4. 所有目录和文件的创建和写入都是以工作目录来的
> > > > 
> > > > 所以目前混用账号数据其实并没有什么太大的影响
> > > 
> > > 
> > > 所以问题回到了这里[#issuecomment-819209757](https://github.com/Mrs4s/go-cqhttp/issues/834#issuecomment-819209757)
> > > 两个bot在同一个群收到不同消息或者收到同一个QQ发来的不同私聊，消息序号有没有重复的可能?
> > > 就像抄判答案抄蹿行那种
> > 
> > 
> > 老实说，crc32来hash会重复吗
> > ![55f58a47bf13d396](https://user-images.githubusercontent.com/25792361/114658810-09e0a480-9d25-11eb-9153-b2ebf85cfde8.jpg)
> 
> crc32是群号或者QQ号+消息id得来的，两个bot在同一个群的不同消息id重复了回复和撤回就有可能出问题

其实重复了也没影响，因为你根本不可能同时使用数据库

**Comment by icarus-ai** [comment]
> > > > > 另外说下目前数据库的情况:
> > > > > 
> > > > > 1. 目前数据库是用的 `leveldb`.
> > > > > 2. key 使用的 群号 + 消息序号 来生成的.
> > > > > 3. `image` 等资源文件名是使用的该文件源文件的md5.
> > > > > 4. 所有目录和文件的创建和写入都是以工作目录来的
> > > > > 
> > > > > 所以目前混用账号数据其实并没有什么太大的影响
> > > > 
> > > > 
> > > > 所以问题回到了这里[#issuecomment-819209757](https://github.com/Mrs4s/go-cqhttp/issues/834#issuecomment-819209757)
> > > > 两个bot在同一个群收到不同消息或者收到同一个QQ发来的不同私聊，消息序号有没有重复的可能?
> > > > 就像抄判答案抄蹿行那种
> > > 
> > > 
> > > 老实说，crc32来hash会重复吗
> > > ![55f58a47bf13d396](https://user-images.githubusercontent.com/25792361/114658810-09e0a480-9d25-11eb-9153-b2ebf85cfde8.jpg)
> > 
> > 
> > crc32是群号或者QQ号+消息id得来的，两个bot在同一个群的不同消息id重复了回复和撤回就有可能出问题
> 
> 其实重复了也没影响，因为你根本不可能同时使用数据库

按你说的重复了
bot1群a消息a，id1
bot2群a消息b，id1
crc32 hash值 x
bot1回复消息 id1，回复到x
bot2回复消息 id2，回复到x
这两不在同一个时间发生

**Comment by sam01101** [comment]
？？？不是你在开第二次数据库的时候就已经不可能open了
会自己报错退出

**Comment by Mrs4s** [comment]
> > > > > > 另外说下目前数据库的情况:
> > > > > > 
> > > > > > 1. 目前数据库是用的 `leveldb`.
> > > > > > 2. key 使用的 群号 + 消息序号 来生成的.
> > > > > > 3. `image` 等资源文件名是使用的该文件源文件的md5.
> > > > > > 4. 所有目录和文件的创建和写入都是以工作目录来的
> > > > > > 
> > > > > > 所以目前混用账号数据其实并没有什么太大的影响
> > > > > 
> > > > > 
> > > > > 所以问题回到了这里[#issuecomment-819209757](https://github.com/Mrs4s/go-cqhttp/issues/834#issuecomment-819209757)
> > > > > 两个bot在同一个群收到不同消息或者收到同一个QQ发来的不同私聊，消息序号有没有重复的可能?
> > > > > 就像抄判答案抄蹿行那种
> > > > 
> > > > 
> > > > 老实说，crc32来hash会重复吗
> > > > ![55f58a47bf13d396](https://user-images.githubusercontent.com/25792361/114658810-09e0a480-9d25-11eb-9153-b2ebf85cfde8.jpg)
> > > 
> > > 
> > > crc32是群号或者QQ号+消息id得来的，两个bot在同一个群的不同消息id重复了回复和撤回就有可能出问题
> > 
> > 
> > 其实重复了也没影响，因为你根本不可能同时使用数据库
> 
> 按你说的重复了
> bot1群a消息a，id1
> bot2群a消息b，id1
> crc32 hash值 x
> bot1回复消息 id1，回复到x
> bot2回复消息 id2，回复到x
> 这两不在同一个时间发生


一个群里不可能有重复的id的

**Comment by icarus-ai** [comment]
> ？？？不是你在开第二次数据库的时候就已经不可能open了
> 会自己报错退出

我已经获取到答案并且关闭了这条issue，楼上: 一个群里不可能有重复的id的

**Comment by sam01101** [comment]
草，这就是高ping战士吗（

**Comment by icarus-ai** [comment]
> ？？？不是你在开第二次数据库的时候就已经不可能open了
> 会自己报错退出

可能是我没表述清楚提问的前提:
bot1和bot2在同一个群，因为风控需要换到另一个bot上，混用数据库会不会id错乱或者无效的问题

**Comment by sam01101** [comment]
> > ？？？不是你在开第二次数据库的时候就已经不可能open了
> > 会自己报错退出
> 
> 可能是我没表述清楚提问的前提:
> bot1和bot2在同一个群，因为风控需要换到另一个bot上，混用数据库会不会id错乱或者无效的问题

不会，没了
