### ISSUE TITLE
添加iPad以外的登录协议

### ISSUE THREAD

**Issue by NotoOotori** [Mrs4s/go-cqhttp#843]
**环境信息**

go-cqhttp版本:  v1.0.0-beta3
OS:  Windows 家庭中文版 10.0.19042

**需要添加的功能内容**

目前的"使用协议"中只有iPad, 因为本人只用iPad设备登录QQ, 就会经常导致登录冲突造成不便, 希望能增加iPhone协议的选项. 谢谢!

已经在全部issue中搜索过关键词"iPad"以及"使用协议", 没有很明显相关的内容; 也在go-cqhttp目录中搜索过"iPad", 也没有发现相关的配置.

**Comment by Ink-33** [comment]
#633

**Comment by Ink-33** [comment]
登录协议更换请在`device.json`内，field `protocol`中更改

**Comment by Yiwen-Chan** [comment]
https://docs.go-cqhttp.org/guide/config.html#%E8%AE%BE%E5%A4%87%E4%BF%A1%E6%81%AF

**Comment by NotoOotori** [comment]
感谢!

**Comment by sam01101** [comment]
是时候PR模板了
