### ISSUE TITLE
入群申请偶尔不能及时上报

### ISSUE THREAD

**Issue by LittleTurtle2333** [Mrs4s/go-cqhttp#848]
有时候申请入群事件不会上报，需要等第二个人申请入群，然后第一个人和第二个人一并上报处理。有什么办法可以解决这种问题吗？ 写个定时/get_group_system_msg吗？

**Comment by sam01101** [comment]
> 有时候申请入群事件不会上报，需要等第二个人申请入群，然后第一个人和第二个人一并上报处理。有什么办法可以解决这种问题吗？ 写个定时/get_group_system_msg吗？

是的
