### ISSUE TITLE
iOS端在群聊无法播放TTS语音

### ISSUE THREAD

**Issue by MikeWang000000** [Mrs4s/go-cqhttp#849]
**环境信息**

go-cqhttp版本: v1.0.0-beta3
运行环境: Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-118-generic x86_64)
连接方式: 反向WebSocket
使用协议: iPad

**bug内容**

#390 #460 都有提到过类似的问题，但是 #463 似乎没有彻底解决iOS群聊TTS语音的播放问题。

使用`[CQ:tts,text=语音文字]`发送TTS语音后：

QQ客户端       | 群聊语音 | 私信语音
-------------- | -------- | ----
iOS            | 无法播放 | 正常
iPad           | 无法播放 | 正常
Android        | 正常     | 正常
Windows        | 正常     | 正常
macOS (Intel)  | 正常     | 正常

ffmpeg版本：
```
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Hyper fast Audio and Video encoder
```

**复现方法**

使用`[CQ:tts,text=语音文字]`向iOS QQ用户在QQ群聊内发送TTS语音。iOS用户无法播放。

**Comment by sam01101** [comment]
盲猜`silk`和`aac`的问题

**Comment by MikeWang000000** [comment]
同一段TTS语音，在群聊明显比私信清晰（应该是编码不同），而iOS端没能成功解码...

**Comment by MikeWang000000** [comment]
**部分`silk`音频在iOS端不能被正确解码。**

今天拿Charles抓了一下iOS QQ实际接收到的语音，有了以下发现：

在群聊发送`[CQ:record,file=file:///tmp/test.wav]`和`[CQ:tts,text=下午好]`。
在iOS端收到的**都是**`silk`语音，与`go-cqhttp`发出的数据一致（md5值吻合）。
前者可被iOS客户端播放，而后者不能。

*`[CQ:record,file=file:///tmp/test.wav]`（可播放）：*
![01](https://user-images.githubusercontent.com/11748152/115675429-2615be80-a381-11eb-839c-11d7d2d799e1.png)

*`[CQ:tts,text=下午好]`（播放失败）：*
![02](https://user-images.githubusercontent.com/11748152/115675627-59584d80-a381-11eb-9661-592f68204e2a.png)


这两条`silk`语音，前者是从`go-cqhttp/global/codec.go`编码而来的，后者是`MiraiGo/client/tts.go`直接从服务器上得到的。
（iOS QQ竟不能解码tx自己的音频...）

**而私聊却能播放的原因：**
`go-cqhttp`发出去的是两条`silk`语音，iOS收到的却是`amr`，在服务器上被tx自动转码了。所以私聊语音无问题。

*`[CQ:record,file=file:///tmp/test.wav]`（可播放）：*
![03](https://user-images.githubusercontent.com/11748152/115676340-13e85000-a382-11eb-8221-81d58a4c55ee.png)

*`[CQ:tts,text=下午好]`（可播放）：*
![04](https://user-images.githubusercontent.com/11748152/115676351-18146d80-a382-11eb-8d73-09f63faa22ab.png)

**不是很好的解决方案：**
对TTS API收到的语音重编码（解码成`pcm`，再重新`silk`编码），iOS端就能播放了。

**Comment by sam01101** [comment]
腾讯返回的TTS(官方QQ) 是否可以在iOS上听到?
假如腾讯返回的语言和安卓的没区别, 那么应该就是客户端自己重编码了

**Comment by MikeWang000000** [comment]
谢谢@wdvxdr1123 @sam01101 ，现在播放没有问题了。我刚准备提pr发现冲突了hhhh
![截屏2021-04-22 下午9 30 52](https://user-images.githubusercontent.com/11748152/115723752-dea82600-a3b2-11eb-93bb-f2f41bdfd594.png)

@sam01101 
> 腾讯返回的TTS(官方QQ) 是否可以在iOS上听到?
可以听到。请求除了header里面的客户端信息不一样外没什么区别，不知道为什么在聊天气泡里就播放不出来。
感觉是QQ自己的bug。
¯\_(ツ)_/¯不过这样重新编码一下，确实解决问题了：）

**Comment by wdvxdr1123** [comment]
大概率是ios 客户端解码写死了24k bit rate

**Comment by MikeWang000000** [comment]
真有可能，但它里面的“朗读”却是好好的（同样的silk），这...辣鸡客户端
![](https://user-images.githubusercontent.com/11748152/115726489-5aa36d80-a3b5-11eb-829d-bac251a53afd.png)
