### ISSUE TITLE
在docker中运行程序出现data/images目录权限问题

### ISSUE THREAD

**Issue by zyujs** [Mrs4s/go-cqhttp#85]
**环境信息**
go-cqhttp版本: v0.9.17
运行环境: linux-amd64
连接方式: 反向WS

**bug内容**
在docker容器中运行程序出现奇怪的权限问题
 [2020-08-12 12:20:52] [FATAL]: 创建图片缓存文件夹失败: mkdir data/images: permission denied
go-cqhttp无法在自己创建的data目录中写入内容

**复现方法**
在docker中运行本程序，go-cqhttp所在目录为外部挂载，权限775，目录下只放置go-cqhttp可执行文件。
启动容器后go-cqhttp报错退出。
查看程序目录下自动创建的文件夹发现logs和data权限不一致，logs目录权限为755，data目录权限为655，
手动chmod +x data可以解决问题

**Comment by Mrs4s** [comment]
最新版本已解决此问题
