### ISSUE TITLE
（BUG)拉取群助手消息重复出现

### ISSUE THREAD

**Issue by LittleTurtle2333** [Mrs4s/go-cqhttp#852]
使用get_group_system_msg并处理后，下次执行get_group_system_msg还是有他。（不过这个复现概率太小了，可能无法修复）请问有没有什么办法可以像手机QQ一键清空群通知。

![](https://i.imgur.com/NJ1gBm6.png)
![](https://i.imgur.com/xzn8Kh4.png)
![](https://i.imgur.com/XhRvou0.jpg)

**Comment by sam01101** [comment]
这是一个未加入的`feature`, 请等待加入此功能

**Comment by Mrs4s** [comment]
请检查 `checked` 字段, 理论上操作后这个字段会改为 `true`

**Comment by sam01101** [comment]
https://docs.go-cqhttp.org/api/#%E5%A4%84%E7%90%86%E5%8A%A0%E7%BE%A4%E8%AF%B7%E6%B1%82-%E9%82%80%E8%AF%B7

**Comment by LittleTurtle2333** [comment]
是因为iPadQQ协议的锅吗？？？
![image](https://user-images.githubusercontent.com/32336368/115640163-df0bd700-a348-11eb-98c1-ee5c20356fed.png)
![image](https://user-images.githubusercontent.com/32336368/115640442-8a1c9080-a349-11eb-88d9-ef52bf049596.png)

**Comment by LittleTurtle2333** [comment]
好像和 #621 问题一样，处理没反应

**Comment by LittleTurtle2333** [comment]
> 请检查 `checked` 字段, 理论上操作后这个字段会改为 `true`

是众多人中只有他过不了，因为是风控账号

**Comment by Mrs4s** [comment]
可能需要加入处理返回值的解析

**Comment by LittleTurtle2333** [comment]
@Mrs4s 解析flag吗？普通用户能进，风控用户不行。

**Comment by LittleTurtle2333** [comment]
应该是cq的问题吧，只有风控用户不行，Mac也不行

**Comment by sam01101** [comment]
总而言之这个是一个feature，需要时间添加

**Comment by asjdf** [comment]
雀实是风控账号的原因，显示风控的账号无法正常添加
