### ISSUE TITLE
2个API调用失败:send_group_forward_msg,_get_vip_info

### ISSUE THREAD

**Issue by anye-star** [Mrs4s/go-cqhttp#853]
**环境信息**

go-cqhttp版本: v1.0.0-beta3
运行环境: Windows Server 2016 Datacenter
连接方式: ws/http
使用协议: Android Phone

**bug内容**

send_group_forward_msg：无法通过此接口发送合并转发消息；但是可以复读接收到的合并转发消息“[CQ:forward,id=xxxx]”。
![image](https://user-images.githubusercontent.com/69682578/115689637-da6a1180-a38e-11eb-9ddd-5543f956bc41.png)
_get_vip_info：如图所示；另发现请求超时时长过长或未设置。
![image](https://user-images.githubusercontent.com/69682578/115689791-fec5ee00-a38e-11eb-82d8-202f43db2e58.png)

**复现方法**

连接正向http后，分别访问：
[http.host:port]/send_group_forward_msg?group_id=[gid]&messages=[{"type":"node","data":{"id":"12345"}}]
[http.host:port]/_get_vip_info?user_id=10001

**Comment by sam01101** [comment]
请确认您已以正确的方法调用API

**Comment by sam01101** [comment]
> [http.host:port]/send_group_forward_msg?group_id=[gid]&messages=[{"type":"node","data":{"id":"12345"}}]

请使用 `POST` 方法调用

**Comment by anye-star** [comment]
> > [http.host:port]/send_group_forward_msg?group_id=[gid]&messages=[{"type":"node","data":{"id":"12345"}}]
> 
> 请使用 `POST` 方法调用

![image](https://user-images.githubusercontent.com/69682578/115695115-1489e200-a394-11eb-884c-e5937a4ddba9.png)
无明显变化

**Comment by sam01101** [comment]
妈耶
![image](https://user-images.githubusercontent.com/25792361/115698059-ca563000-a396-11eb-81ba-9d7662f621c4.png)

**Comment by anye-star** [comment]
> 妈耶
> ![image](https://user-images.githubusercontent.com/25792361/115698059-ca563000-a396-11eb-81ba-9d7662f621c4.png)

不能用 urlencoded 表单方式吗

**Comment by sam01101** [comment]
> > 妈耶
> > ![image](https://user-images.githubusercontent.com/25792361/115698059-ca563000-a396-11eb-81ba-9d7662f621c4.png)
> 
> 不能用 urlencoded 表单方式吗

可以, 请从代码参考需要escape的数值

**Comment by anye-star** [comment]
那这个 _get_vip_info 是否有问题

**Comment by sam01101** [comment]
> _get_vip_info

![image](https://user-images.githubusercontent.com/25792361/115700970-db547080-a399-11eb-8420-61412826a49e.png)

**Comment by anye-star** [comment]
> > _get_vip_info
> 
> ![image](https://user-images.githubusercontent.com/25792361/115700970-db547080-a399-11eb-8420-61412826a49e.png)

![image](https://user-images.githubusercontent.com/69682578/115702337-62561880-a39b-11eb-8c03-44c47b8cc321.png)
失败了

**Comment by Mrs4s** [comment]
> > > _get_vip_info
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/25792361/115700970-db547080-a399-11eb-8420-61412826a49e.png)
> 
> ![image](https://user-images.githubusercontent.com/69682578/115702337-62561880-a39b-11eb-8c03-44c47b8cc321.png)
> 失败了

服务器网络问题

**Comment by anye-star** [comment]
好吧，本次issue到此结束

**Comment by sam01101** [comment]
检查服务器IP是否被GFW墙了
