### ISSUE TITLE
qucik reply不会回复机器人自身的指令

### ISSUE THREAD

**Issue by Zhongren233** [Mrs4s/go-cqhttp#856]
**环境信息**

go-cqhttp版本: v1.0.0-beta3
运行环境: Ubuntu20.04
连接方式: http post
使用协议: iPad

**bug内容**

设置是否上报自身消息为true的前提下
在手机上用bot账号输入指令
账号自身指令未正常回复

**复现方法**

必定复现

![image](https://user-images.githubusercontent.com/62706664/115947659-b972ff00-a4fb-11eb-87b5-ea19b30bfa60.png)

![image](https://user-images.githubusercontent.com/62706664/115947705-00f98b00-a4fc-11eb-8f54-ba50540f4b4f.png)

![image](https://user-images.githubusercontent.com/62706664/115947713-0f47a700-a4fc-11eb-9339-564016120276.png)

**Comment by sam01101** [comment]
这是你自身框架的问题, 不是gocq的问题

**Comment by Ink-33** [comment]
我并不认为这是gocq的问题。

**Comment by Zhongren233** [comment]
> 我并不认为这是gocq的问题。

框架中收到了自身的上报信息，但是没有正常回复
gocq中也没有相关的回复信息

**Comment by sam01101** [comment]
> > 我并不认为这是gocq的问题。
> 
> 框架中收到了自身的上报信息，但是没有正常回复
> gocq中也没有相关的回复信息

gocq只有负责上报功能, 对于回复等待高级操作是框架的实现

有问题请去框架的repo开issue

**Comment by Kyomotoi** [comment]
请从你使用的框架中的相关插件寻求帮助

**Comment by Zhongren233** [comment]
这是我自己的bot
回复是使用快速回复操作实现的

**Comment by sam01101** [comment]
> 这是我自己的bot
> 回复是使用快速回复操作实现的
> 
> ![image](https://user-images.githubusercontent.com/62706664/115947833-02778300-a4fd-11eb-93ad-b531aca48578.png)

建议使用 `send_msg`, 快速回复操作不适合

**Comment by sam01101** [comment]
![image](https://user-images.githubusercontent.com/25792361/115947941-9e08f380-a4fd-11eb-8ad2-fd803f2df00b.png)

**Comment by 2938137849** [comment]
![](https://user-images.githubusercontent.com/25792361/115947941-9e08f380-a4fd-11eb-8ad2-fd803f2df00b.png)

**Comment by Zhongren233** [comment]
![](https://user-images.githubusercontent.com/25792361/115947941-9e08f380-a4fd-11eb-8ad2-fd803f2df00b.png)

想了一下自己可能确实有点语死早 抱歉

**Comment by Mrs4s** [comment]
应该是框架问题
