### ISSUE TITLE
websocket发送消息顺序错乱

### ISSUE THREAD

**Issue by Mmx233** [Mrs4s/go-cqhttp#858]
**环境信息**

go-cqhttp版本: 1.0.0 beta2
运行环境: linux amd64
连接方式: ws
使用协议: ws

**bug内容**

ws发送信息存在顺序问题，当短时间发送回复与普通消息时回复总是滞后，当发送回复与xml消息时，也是回复滞后
以前版本使用http调用api似乎没这个问题，有也是网络问题
使用延时是不可行的，我把延时拉到1s1消息后还是无效，而且使用延时是十分不靠谱且效率低的。

**复现方法**

**Comment by sam01101** [comment]
？？？你没有用`seq`吗？

信息发送通常都是异步的，不会有顺序问题

**Comment by Mmx233** [comment]
并没有使用seq，但是使用http到时候顺序就是正常的，可能是因为http发送成功才响应，确保了顺序
上为ws，下为http
我知道了
![Screenshot_20210425_151104_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/36563672/115984225-7c306f00-a5d8-11eb-858c-2c8a294c41da.jpg)
