### ISSUE TITLE
【bug】发送较大的图片提示->消息图片上传失败: upload failed

### ISSUE THREAD

**Issue by YiwanGi** [Mrs4s/go-cqhttp#865]
**环境信息**

go-cqhttp版本: 9.40fix4 | 1.0.0beta3
运行环境: windows
连接方式: 反向ws
使用协议: ipad

**bug内容**

发送较大的图片时无法进行发送（file：4.27Mb）（file：2.31Mb）
go-cqhttp提示【消息图片上传失败: upload failed】
（群聊消息中出现，私聊暂未测试）

**复现方法**

1.使用url发送
2.通过cqhttp下载到缓存目录后 使用文件发送
均提示图片上传失败

**Comment by sam01101** [comment]
這是騰訊的問題，目前沒有很好的辦法解決

**Comment by Ink-33** [comment]
![Screenshot_2021-04-30-00-33-35-005_com.github.android.jpg](https://user-images.githubusercontent.com/51873347/116586143-b8066400-a94b-11eb-9cc0-3144dcbb4e51.jpg)
