### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by zxc7895531** [Mrs4s/go-cqhttp#87]
**环境信息**
go-cqhttp版本: v0.9.18
运行环境: windows_amd64
连接方式: HTTP连接

**bug内容**
上报Event数据失败:context deadline exceeded

**复现方法**
群内发送指令生成图片消息，生成完毕发送时出现此BUG。重启即可正常使用，但过1-3个小时就会再次触发这个BUG。
- [INFO]: 收到群 XXXXXXXX 内 XXXXXXX 的消息: ！recent (XXXXXX)
- [WARNING]: 上报Event数据到 http://127.0.0.1:8888/msg 失败: Post "http://127.0.0.1:8888/msg": context deadline exceeded
- [DEBUG]: 警告: 事件处理耗时超过 5 秒 (5ns秒), 请检查应用是否有堵塞.
（隐私数据已用XXX代替）

经检测排除了我写的应用的问题，而且我的应用发送消息时服务端有回应也有消息ID，但是会报错
![image](https://user-images.githubusercontent.com/38042972/89996251-266f9d00-dcbd-11ea-932a-17e0c7e7476f.png)

**Comment by Mrs4s** [comment]
请通过配置文件调大Timeout阈值，或改用websocket上报（推荐）
