### ISSUE TITLE
更新到最新版本后运行直接报错

### ISSUE THREAD

**Issue by danuonuo** [Mrs4s/go-cqhttp#874]
**环境信息**

go-cqhttp版本: v0.9.40-fix5
运行环境: ubuntu20.04.2LTS
连接方式: null
使用协议: null

**bug内容**

无法启动，直接崩溃，如图
![2F5BE810-E7E0-4CAD-AB45-E57773B01C54](https://user-images.githubusercontent.com/40296672/117018987-97f9ea80-ad27-11eb-98f8-7a3ee1fec6d3.jpeg)

**复现方法**

直接启动go-cqhttp

**Comment by sam01101** [comment]
请手动下载最新版gocq, 已知问题, 待修复

**Comment by danuonuo** [comment]
> 请手动下载最新版gocq, 已知问题, 待修复

以后自动更新不能用了吗

**Comment by sam01101** [comment]
> > 请手动下载最新版gocq, 已知问题, 待修复
> 
> 以后自动更新不能用了吗

待修復

**Comment by wdvxdr1123** [comment]
这是由于老版本自动更新下载连接用的release中的未压缩二进制文件， 在v1.0.0后，未压缩文件不再上传，改用tar.gz / zip文件进行更新
手动升级到1.0后即可使用
注：下个版本自动更新会加入 `checksum` 检验

**Comment by 2938137849** [comment]
这个是因为老版本更新时候自动下载替换的 go-cqhttp 文件下载成了文本文件, 你用vim打开就会发现是个 readme.md 文件
自己手动 wget 一下最新版压缩包就好了
