### ISSUE TITLE
检验失败但能用send massage发消息 也能正常运行 求大佬来看看

### ISSUE THREAD

**Issue by lyy2896679963** [Mrs4s/go-cqhttp#876]
我使用的Windows环境 v0.9.40-fix5这个 然后云服务器能搭建 也能发消息
但是部署了私人酷推 不成功 检验的时候显示检验失败
(https://user-images.githubusercontent.com/81840782/117023647-e01b0c00-ad2b-11eb-9d3c-ea617a7bc62f.png)

dial tcp 121.89.197.5:5700: i/o检验失败 端口5700都开了 防火墙都开了

**Comment by Ink-33** [comment]
这里不是酷推仓库，你在这里问得不到任何解答。

**Comment by sam01101** [comment]
这里不是酷推仓库，你在这里问得不到任何解答。
