### ISSUE TITLE
[Bug] v1.0.0-beta收到了错误的更新提醒

### ISSUE THREAD

**Issue by backrunner** [Mrs4s/go-cqhttp#877]
**环境信息**

go-cqhttp版本: v1.0.0-beta3
运行环境: Linux
连接方式: 
使用协议: 

**bug内容**

检测新版本存在一定问题，v0.9.40-fix5版本发布后，我使用v1.0.0-beta3会收到v0.9.40的更新提醒。
![image](https://user-images.githubusercontent.com/12205593/117041238-5aa05780-ad3d-11eb-892d-cb203cf510a9.png)
希望能在检查更新的时候加入一个大版本号的比对，避免新版本收到错误的更新提示。

**复现方法**

启动程序就能看见

**Comment by sam01101** [comment]
bug+feat，真少见
