### ISSUE TITLE
启动/更新时会将 0.9.40-fix5 视为最新版本

### ISSUE THREAD

**Issue by Jigsaw111** [Mrs4s/go-cqhttp#878]
**环境信息**

go-cqhttp版本:   1.0.0-beta3
运行环境:  Win10 1909  家庭版 64位
连接方式:  无
使用协议:  无

**bug内容**

使用 1.0.0-beta 检测更新时会提示 0.9.40-fix5 为最新版本。
使用 ./go-cqhttp update 更是会使其版本倒退为 0.9.40

**复现方法**

`./go-cqhttp update`

**Comment by wdvxdr1123** [comment]
#877
