### ISSUE TITLE
从v0.9.39升级至v0.9.40后，会自动艾特全体成员

### ISSUE THREAD

**Issue by danyang685** [Mrs4s/go-cqhttp#879]
**环境信息**

go-cqhttp版本: v0.9.40-fix5
运行环境: ubuntu, python aiocqhttp
连接方式: 反向ws
使用协议: MacOS

**bug内容**
自 `v0.9.39` 升级为 `v0.9.40-fix5` 后，发送的reply消息总是带有 `@全体成员` 前缀，当QQ机器人是群内管理员时，还将通知群内全体成员。

`v0.9.39` 版本下，通过反向ws发送消息时的日志：
```
[DEBUG]: WS接收到API调用: .handle_quick_operation 参数: {"self_id": 14175xxxx, "context": {"anonymous": null, "font": 0, "group_id": 6700xxxx, "message_id": -1026930429, "message_seq": 491926, "message_type": "group", "post_type": "message", "self_id": 141757xxxx, "sub_type": "normal", "time": 1620396624, "user_id": 49629xxxx}, "operation": {"reply": "[CQ:reply,id=-1026930429] xxxxxxxxxx"}} 
```
效果：
![9_39行为](https://user-images.githubusercontent.com/29062127/117463361-279ad580-af82-11eb-9685-f60faf8efe8a.png)

`v0.9.40-fix5` 版本下，通过反向ws发送消息时的日志：
```
[DEBUG]: WS接收到API调用: .handle_quick_operation 参数: {"self_id": 14175xxxx, "context": {"anonymous": null, "font": 0, "group_id": 6700xxxx, "message_id": -1484562915, "message_seq": 491881, "message_type": "group", "post_type": "message", "self_id": 14175xxxx, "sub_type": "normal", "time": 1620394022, "user_id": 23021xxxx}, "operation": {"reply": "[CQ:reply,id=-1484562915] xxxxxxxxxx"}}
```
效果：
![9_40行为](https://user-images.githubusercontent.com/29062127/117463432-3ed9c300-af82-11eb-8da4-2ebf0b898267.png)

**复现方法**
使用 `v0.9.40-fix5` 可以稳定复现该问题，随后切换回 `v0.9.39` 版本，问题消失。

**Comment by sam01101** [comment]
https://github.com/Mrs4s/go-cqhttp/blob/d8a373cfa4cc6a99b6f9f5ed5e0bb763c319d07c/coolq/api.go#L893

经对比，发现context没有符合的item
所以变0了
解决方法就是自己建个event之类的意思，表达不好，差不多就是这样

嗯，就是这样。。。

**Comment by wdvxdr1123** [comment]
#774
