### ISSUE TITLE
苹果手机群消息显示多行文本时混乱

### ISSUE THREAD

**Issue by Zzz2333** [Mrs4s/go-cqhttp#884]
**环境信息**

go-cqhttp版本: v0.9.40-fix5
运行环境: win10
连接方式: http
使用协议: ipad

**bug内容**

向群内发送以下纯文本，在安卓机上查看显示正常，在苹果机上查看，格式混乱。显示效果见下图。
发送消息和查看消息的是两个不同的QQ。
不仅仅是多一个空行，有时候会在某一个字符处莫名换行（就是原文本没有换行，但苹果手机上查看显示换行）。
我测试了v0.9.40-fix5版本和v1.0.0-bet3版本，只有前者有问题，后者没有问题。

安卓手机正常：
![Image20210515200848](https://user-images.githubusercontent.com/28297857/118360253-64d21980-b5b9-11eb-8664-37257bace027.jpg)
苹果手机异常：
![71B34028-29F3-498F-AD41-940E176FA778](https://user-images.githubusercontent.com/28297857/118360255-67347380-b5b9-11eb-8bb9-41410da0a0f5.jpg)

以下为原文本：
刘备32100 关羽09651
张飞09000 孔明09000
赵云07755 黄忠05657
刘禅05789 姜维01234
魏延05300 马岱05000
关兴03400 马谡03100
廖化02522 王平02188
马超02122 邓芝01234
周仓00412

**复现方法**

向群里发送以上文本，在苹果手机上查看即可。

**Comment by sam01101** [comment]
应该是QQ客户端的问题，尝试更换协议（应该没用，但值得尝试）

另外，电脑版本的排版你看下时候有这个一样的问题

**Comment by Yiwen-Chan** [comment]
可以尝试关闭分片消息

**Comment by sam01101** [comment]
我突然想起来有个梗图来讽刺自己
![IMG_20210515_204724_637](https://user-images.githubusercontent.com/25792361/118361614-ccd72e80-b5be-11eb-8574-2494176fa95e.jpg)
我找了23分钟

**Comment by Zzz2333** [comment]
多谢两位大佬的回复。关闭分片消息可以解决问题。

**Comment by Zzz2333** [comment]
尝试更换协议不行。
另外，电脑版本的排版是正确的。
