### ISSUE TITLE
闪照无url属性

### ISSUE THREAD

**Issue by frankli0324** [Mrs4s/go-cqhttp#889]
**环境信息**

go-cqhttp版本: 1.0.0-beta3
运行环境: github.com/frank-dockerfiles/docker-go-cqhttp
连接方式: websocket (无关)
使用协议: pad (无关)

**bug内容**

闪照(FlashImgElement)无url参数

https://github.com/Mrs4s/go-cqhttp/blob/beb5c777673d5f312e11695c7be5ac333c03aebc/coolq/cqcode.go#L267-L282

经过简单的xref，发现文件消息段是否有url参数由ToMessage的`isRaw`参数控制，猜测仅在入数据库时isRaw为true，但闪照相关分支没有处理`isRaw = false`

**复现方法**

发闪照

**Comment by wdvxdr1123** [comment]
不是bug，是特性!tx未提供闪照的url

**Comment by sam01101** [comment]
> 不是bug，是特性

不是bug，是特性

**Comment by frankli0324** [comment]
在.image文件中能看到url。。

**Comment by sam01101** [comment]
> 在.image文件中能看到url。。

那个是临时的, 有机会在未来失效

**Comment by frankli0324** [comment]
emmm...这样..
好叭

**Comment by frankli0324** [comment]
为后来者的一个小tip：
gchat的那个url，把后面的md5换掉就可以访问到图片
比如：
文件名为`aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.image`
则访问
`http://gchat.qpic.cn/gchatpic_new/数字/数字-数字-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/0?term=3`
即可

**Comment by sam01101** [comment]
> 为后来者的一个小tip：
> gchat的那个url，把后面的md5换掉就可以访问到包括闪照在内的图片
> 比如：
> 文件名为`aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.image`
> 则访问
> `http://gchat.qpic.cn/gchatpic_new/数字/数字-数字-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/0?term=3`
> 即可

话说 `get_image` 不能用吗?

**Comment by frankli0324** [comment]
可以，但是个人感觉url下载起来方便一些。。。(

**Comment by sam01101** [comment]
> 可以，但是个人感觉url下载起来方便一些。。。(

? `download_file`

**Comment by frankli0324** [comment]
对啊，两行 vs 一行（

**Comment by sam01101** [comment]
@A@ 你喜欢

**Comment by frankli0324** [comment]
莫名其妙地就at上了一个人（（（

**Comment by Mrs4s** [comment]
https://github.com/Mrs4s/go-cqhttp/blob/d8a373cfa4cc6a99b6f9f5ed5e0bb763c319d07c/coolq/event.go#L578-L585
其实闪照在`.image`文件也没有链接

**Comment by frankli0324** [comment]
刚也发现了。。我当时是发了一张普通图片以后发了一张一模一样的闪照
