### ISSUE TITLE
通过群聊申请

### ISSUE THREAD

**Issue by GreenTeodoro839** [Mrs4s/go-cqhttp#895]
https://github.com/LittleTurtle2333/pay_join_group_bot我用的这个项目，但有时看了输出，显示已同意，机器人却是拒绝了。重启nonebot不管用，但是重启cqhttp就管用了。cqhttp也没提示什么错误

**Comment by sam01101** [comment]
对不起，请按照`bug模板`来提交issue，此issue将会忽略并不作处理

**Comment by sam01101** [comment]
而且请注意，您已违反QQ的用户协议
QQ已经下架付费群功能

**您现在提交的issue我们不会处理以免触犯法律**
