### ISSUE TITLE
token过期,导致部分api无效

### ISSUE THREAD

**Issue by sirodeneko** [Mrs4s/go-cqhttp#897]
**环境信息**

go-cqhttp版本: v0.9.40-fix5 
运行环境: linux
连接方式: ws 和 http
使用协议: http

**bug内容**

调用 _send_group_notice 无效
可能原因：token过期，导致请求失败
重启后调用成功

**复现方法**

长时间上线后调用api

希望程序可以自动进行token的更新，而且代码中直接把错误忽略了，不太好，毕竟不是需要立即返回的函数

**Comment by Mrs4s** [comment]
#691
