### ISSUE TITLE
POST 发送消息，程序可能忽略 access_token

### ISSUE THREAD

**Issue by armstrongchen** [Mrs4s/go-cqhttp#899]
**环境信息**

go-cqhttp版本: 1.0.0-beta4  
运行环境: Springdale 8.3  
连接方式: POST URL  
使用协议: HTTP  

**bug内容**

用 POST 方式发送消息，设置了 access_token，并且请求中也包含了 access_token，但报告 401 错误。如改成 GET 方式发送消息则没问题。或者，不启用 access_token 也没问题。

**复现方法**

使用 curl -i -d "access_token=xxxxxxxx" -d "group_id=123456789" -d "message=消息内容" http://127.0.0.1:5701/send_group_msg

**Comment by Ink-33** [comment]
`access_token`仅支持通过`query`和`header`传入，而不是POST BODY。

https://www.github.com/howmanybots/onebot/tree/master/v11%2Fspecs%2Fcommunication%2Fauthorization.md

#633

**Comment by sam01101** [comment]
草，难怪看半天我也看不出哪里出问题了
好家伙，放`body`了

所以
`-H` 是 `Header`
`-d` 是 `Body`
?

**Comment by nidbCN** [comment]
> 草，难怪看半天我也看不出哪里出问题了
> 好家伙，放`body`了
> 
> 所以
> `-H` 是 `Header`
> `-d` 是 `Body`
> ?

事这样的

`-H` `--header` 为header

`-d` `--data` 是和提交表单一样的处理方式，所以是扔body里

https://curl.se/docs/manpage.html

**Comment by armstrongchen** [comment]
对，GET 请求工作正常，我简单的把请求换成 POST 就掉坑了。

问题已解决，谢谢哈。
