### ISSUE TITLE
win10+gocq最新版无法登录,抓包方式显示上网环境异常,扫码方式显示parse incoming packet error: session expired

### ISSUE THREAD

**Issue by RiotGamesU** [Mrs4s/go-cqhttp#900]
**环境信息**

go-cqhttp版本: v1.0.0-beta4
运行环境: win10 latest
连接方式: ws-reverse
使用协议: ws

**bug内容**

无法登录,抓包方式显示上网环境异常,扫码方式显示parse incoming packet error: session expired

**复现方法**

1.下载gocq
2.配置好配置文件
3.运行gocq

**Comment by sam01101** [comment]
1. 网络环境异常, 请尝试使用Android协议登录
2. Session expired: 尝试删除session文件后重新扫码

如果上述方法还是无法解决, 请提供详细log (确保Debug已开启)

**Comment by RiotGamesU** [comment]
> 请尝试删除密码再扫码登录

newbe,可以登录了

**Comment by RiotGamesU** [comment]
> 1. 网络环境异常, 请尝试使用Android协议登录
> 2. Session expired: 尝试删除session文件后重新扫码
> 
> 如果上述方法还是无法解决, 请提供详细log (确保Debug已开启)

关于1,先尝试了上面的方法,成功登陆了,之后添加密码再登录直接成功了,不会出现网络环境异常,所以没法再试了
关于2,未尝试上面的方法之前,不存在session文件
