### ISSUE TITLE
群文件上传事件添加folder_id字段

### ISSUE THREAD

**Issue by shirokurakana** [Mrs4s/go-cqhttp#911]
**环境信息**

go-cqhttp版本: 1.0.0-beta4

**需要添加的功能内容**

文件有可能不是上传至根目录，而是文件夹中，群文件上传事件中如果能体现这一点就好了。
所以我建议在事件中添加`folder_id`字段，也方便调用`get_group_file_url`之类的API
而且我挺好奇根目录的`folder_id`到底是什么情况，因为一些涉及到根目录操作的地方需要用到这个，比如在根目录创建文件夹。
还有，能不能更进一步，将`url`字段也一起添加呢？如果不方便的话当我没说（x

**Comment by Mrs4s** [comment]
下个版本 `delete_group_file` API 不再需要 `folder_id` 参数.
`group_file` 事件无法提供 `folder_id`. QQ并没有给
因为这个事件其实是用于在聊天窗口下载文件用..
`url` 字段已经提供了
