### ISSUE TITLE
私聊无法发送图片信息，提示图片上传失败

### ISSUE THREAD

**Issue by Billdex** [Mrs4s/go-cqhttp#914]
**环境信息**

go-cqhttp版本: 0.9.40-fix4/0.9.40-fix5/1.0.0-beta4均尝试过
运行环境: linux/ubuntu
连接方式: http
使用协议: ipad

**bug内容**

私聊无法正常上传和发送图片，同样的图片在群聊可以正常发送。
消息内容中若同时有图片和文字，则在私聊中可以发送文字部分内容，但图片无法发送，群聊发送消息正常。
![6BF571105B9063C572D05FD5CB7A61A1](https://user-images.githubusercontent.com/23182543/120997008-6efec680-c7b9-11eb-9394-c85f56ff1b07.jpg)
![image](https://user-images.githubusercontent.com/23182543/120997047-7a51f200-c7b9-11eb-82c2-c2a12a821dd0.png)

go-cqhttp日志如下
[2021-06-07 17:31:08] [WARNING]: 警告: 私聊 591404144 消息图片上传失败.
[2021-06-07 17:31:08] [WARNING]: 好友消息发送失败: 消息为空.

使用的CQ码示例如下：
[CQ:image,file=file:////home/billdex/bcjh_bot_aowu/resource/image/recipe/recipe_580.png]
[CQ:image,file=e8d347843b157786d937f8234945ec85.image]

经常出现如下报错，不知是否有相关性：
[2021-06-07 17:31:40] [ERROR]: Protocol -> panic on decoder MessageSvc.PbGetMsg : send on closed channel
goroutine 18283 [running]:
runtime/debug.Stack(0xc003047c30, 0xde7b00, 0x1048b30)
runtime/debug/stack.go:24 +0x9f
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1(0xc0002d4000, 0xc001d0b090)
github.com/Mrs4s/MiraiGo@v0.0.0-20210429065541-8f474db6a37e/client/client.go:1062 +0x76
panic(0xde7b00, 0x1048b30)
runtime/panic.go:965 +0x1b9
github.com/Mrs4s/MiraiGo/client.(*QQClient).sendAndWait.func2(0x0, 0x0, 0x0, 0x0)
github.com/Mrs4s/MiraiGo@v0.0.0-20210429065541-8f474db6a37e/client/client.go:925 +0x76
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0002d4000, 0xc001d0b090, 0xc0014dc000, 0x47d9, 0x7e00)
github.com/Mrs4s/MiraiGo@v0.0.0-20210429065541-8f474db6a37e/client/client.go:1083 +0x20f
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
github.com/Mrs4s/MiraiGo@v0.0.0-20210429065541-8f474db6a37e/client/client.go:1059 +0x425

**复现方法**

通过CQ码发送私聊消息可复现，必要的话可提供机器人帐号与运行环境

**Comment by Watanabe-Asa** [comment]
刚想提这个issue就发现已经有了（）
mark

**Comment by sam01101** [comment]
请依照 #633 的提交bug方法进行搜索
#408 #378

**Comment by Watanabe-Asa** [comment]
感谢指路

**Comment by sam01101** [comment]
Duplicate of #408 #378 #302

**Comment by Billdex** [comment]
> 请依照 #633 的提交bug方法进行搜索
> Duplicate of #408 #378 #302

这3个issue都看过了，感觉应该是新的风控问题，正常用了很长时间了今天突然这样。更新到最新版本也无法解决（0.9.40和1.0.0都试过），大图(500K以上)小图(50K以下)均无法发送。今天群里问了下有几位也是一样的问题。

**Comment by AOALI123** [comment]
大家好 我是408的提问者 我又来了 是的 今天又无法私聊发送图片了 九成九还是风控问题 所以 TXNMSL 期待修复 谢谢 或许可以加上私聊搜图也合并转发搜索结果 可能会管用？

**Comment by sam01101** [comment]
> 大家好 我是408的提问者 我又来了 是的 今天又无法私聊发送图片了 九成九还是风控问题 所以 TXNMSL 期待修复 谢谢 或许可以加上私聊搜图也合并转发搜索结果 可能会管用？

我也加一句, TXNMSL

**Comment by Miuzarte** [comment]
好耶 TXNMSL

**Comment by Watanabe-Asa** [comment]
充svip没用，只好等新的解决方法了（
TXNMSL

**Comment by 2938137849** [comment]
好耶,我也来
TXNMSL

**Comment by auqhjjqdo** [comment]
![image](https://user-images.githubusercontent.com/56216884/121146003-193a2500-c872-11eb-9b1b-f20f197ed3d5.png)
我也遇到了，TXNMSL

**Comment by huiki** [comment]
我也来, TXNMSL

**Comment by LambdaYH** [comment]
今天我也遇到了 TXNMSL

**Comment by desolution025** [comment]
草，现在私聊竟然会风控，TXNMSL

**Comment by 2015WUJI01** [comment]
虽然我的机器人还没有做发图片，但是 TXNMSL

**Comment by wuzhiji37** [comment]
TXNMSL

**Comment by AOALI123** [comment]
说起来上回我408的时候确实是gohttp更新修好的 这回还能修吗

**Comment by sam01101** [comment]
> 说起来上回我408的时候确实是gohttp更新修好的 这回还能修吗

不知道，放到暑假再说

**Comment by wdvxdr1123** [comment]
请尝试使用[fad3bf1](https://github.com/Mrs4s/go-cqhttp/actions/runs/927501177)

**Comment by AOALI123** [comment]
> 请尝试使用[fad3bf1](https://github.com/Mrs4s/go-cqhttp/actions/runs/927501177)

已下载尝试 修好了

**Comment by Dustella** [comment]
unsubscribe



Sent from my Mi phone
Jun 11, 2021 8:42 PM wrote on AOALI123 ***@***.***>:

请尝试使用fad3bf1<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMrs4s%2Fgo-cqhttp%2Factions%2Fruns%2F927501177&data=04%7C01%7C%7C231d5d87a10340b9e72e08d92cd660b6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637590121521942952%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2Bix9umLHqxdnWDSqQCKoqxUuFFbCEbH7EL0gUvi7bkQ%3D&reserved=0>

已下载尝试 修好了

**Comment by AOALI123** [comment]
> unsubscribe
> […](#)
> Sent from my Mi phone Jun 11, 2021 8:42 PM wrote on AOALI123 ***@***.***>: 请尝试使用fad3bf1<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMrs4s%2Fgo-cqhttp%2Factions%2Fruns%2F927501177&data=04%7C01%7C%7C231d5d87a10340b9e72e08d92cd660b6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637590121521942952%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2Bix9umLHqxdnWDSqQCKoqxUuFFbCEbH7EL0gUvi7bkQ%3D&reserved=0> 已下载尝试 修好了 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMrs4s%2Fgo-cqhttp%2Fissues%2F914%23issuecomment-859554265&data=04%7C01%7C%7C231d5d87a10340b9e72e08d92cd660b6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637590121521952909%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Pw9aAW%2FsDBYxSKBXZuEPtneB%2FSC3rG5pl7n8X7Af7p0%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHK62TM7OFTTH7I3JAROLLLTSIADLANCNFSM46HJSM3A&data=04%7C01%7C%7C231d5d87a10340b9e72e08d92cd660b6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637590121521952909%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=I7YcirNG4v4pH0x5ttsI8LOll2DbJQBs11ndssUENAs%3D&reserved=0>.

what is this???这是个什么东西???

**Comment by ppfirework** [comment]
>请尝试使用fad3bf1

私聊可以发图片了
群里面又不能了

**Comment by Ink-33** [comment]
> >请尝试使用fad3bf1
> 
> 私聊可以发图片了
> 群里面又不能了

报错消息能否贴一下

**Comment by master-lzh** [comment]
我是私聊不行，群聊可以

**Comment by ppfirework** [comment]
> > > 请尝试使用fad3bf1
> > 
> > 
> > 私聊可以发图片了
> > 群里面又不能了
> 
> 报错消息能否贴一下

昨天提升账号被风控
今天重启了一下服务器又可以了

**Comment by noahzark** [comment]
![QQ图片20210619175443](https://user-images.githubusercontent.com/4402804/122638597-9b0a3800-d127-11eb-9982-6fb8bcfd3055.png)
惊呆了，v1.0.0-beta4，同一张图，私聊不行群聊就可以？

**Comment by Mrs4s** [comment]
> ![QQ图片20210619175443](https://user-images.githubusercontent.com/4402804/122638597-9b0a3800-d127-11eb-9982-6fb8bcfd3055.png)
> 惊呆了，v1.0.0-beta4，同一张图，私聊不行群聊就可以？

尝试使用最新的测试版

**Comment by noahzark** [comment]
> > ![QQ图片20210619175443](https://user-images.githubusercontent.com/4402804/122638597-9b0a3800-d127-11eb-9982-6fb8bcfd3055.png)
> > 惊呆了，v1.0.0-beta4，同一张图，私聊不行群聊就可以？
> 
> 尝试使用最新的测试版

噢噢，能问一下怎么获取测试版/nightly build嘛？还是要自己compile

**Comment by Ink-33** [comment]
> > > ![QQ图片20210619175443](https://user-images.githubusercontent.com/4402804/122638597-9b0a3800-d127-11eb-9982-6fb8bcfd3055.png)
> > > 惊呆了，v1.0.0-beta4，同一张图，私聊不行群聊就可以？
> > 
> > 尝试使用最新的测试版
> 
> 噢噢，能问一下怎么获取测试版/nightly build嘛？还是要自己compile

从github actions下载

**Comment by TheresaQWQ** [comment]
我这里私聊全都发不出去了，TXNMSL

**Comment by sam01101** [comment]
你好, 有拿mirai进行一个对比实验吗？
如果真的不行可以试一试mirai看看能不能，正常发送

**Comment by kj415j45** [comment]
> > ![QQ图片20210619175443](https://user-images.githubusercontent.com/4402804/122638597-9b0a3800-d127-11eb-9982-6fb8bcfd3055.png)
> > 惊呆了，v1.0.0-beta4，同一张图，私聊不行群聊就可以？
> 
> 尝试使用最新的测试版

使用CI Build fad3bf1后错误信息为：

> 警告: 私聊 [REDACTED] 消息图片上传失败: upload failed: upload failed: 83

**Comment by Giftia** [comment]
已复现，发不了涩图，TXNMSL

**Comment by Miuzarte** [comment]
> 已复现，发不了涩图，TXNMSL

这个单纯的风控...

**Comment by Giftia** [comment]
> > 已复现，发不了涩图，TXNMSL
> 
> 这个单纯的风控...

好吧。。确实是风控。。

**Comment by BestLemoon** [comment]
今天发图片也发现了这个问题，我是一个服务器挂了两个号，一个号刚挂上会被风控，另一个已经挂了很久很久平时也在发消息就可以发送。各位可以尝试先登录挂机7天以上再试试

**Comment by Mrs4s** [comment]
应该是风控
