### ISSUE TITLE
当  CQ:tts 短时间收到过多,就会转码失败

### ISSUE THREAD

**Issue by xiaowine** [Mrs4s/go-cqhttp#916]
**环境信息**

go-cqhttp版本: v1.0.0-beta4
运行环境: windows
连接方式: http
使用协议:  ipad

**bug内容**
当  CQ:tts 短时间收到过多,就会转码失败
![image](https://user-images.githubusercontent.com/68009112/121771998-51f53980-cba5-11eb-93ea-d9a8c6427b8e.png)

**复现方法**

**Comment by sam01101** [comment]
> 我的每秒一次也只是极端测试，谁没事这样做

我每秒发2w条信息也是极端测试
我测试聊天记录最大限制也是极端测试
我撤回大量信息也是极端测试

这些都是我曾经做过的, 我甚至还用QQ薅羊毛无限放文件呢 _(扯远了_
请问腾讯允许我这样做了吗? 没有, 而且没有说

请记住, 这是一个以`客户端协议`实现的机器人, 你的账号是用户账号, 不是机器人账号, 没有任何特权 (除了企业号)
不要以为你正在使用机器人类型的账号, 比用户账号的限制松懈

风控系统是因为机器人以及黑产的出现而诞生的, 本身就对用户无害

即使是马化腾的QQ也会受到这个限制 _(只要他没要求忽略他的账号的风控_

请您以后在创建issue的时候首先查看 #633 的 [《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md), 
![image](https://user-images.githubusercontent.com/25792361/121776327-d0aaa080-cbbe-11eb-8112-eb2d16f1127c.png)
^ 其实非常大了

> - [ ] 我已经仔细阅读上述教程和"提问前需知 [图+文]": https://github.com/Mrs4s/go-cqhttp/issues/633

这里的勾也不是放着的, 是我真的辛辛苦苦制作出633这个Q&A然后哀求他们pin然后放在里面的, 我真的非常非常希望你能给我点面子, 看一下写的东西
