### ISSUE TITLE
当短时间收到过多的 CQ:tts 就会转码失败

### ISSUE THREAD

**Issue by xiaowine** [Mrs4s/go-cqhttp#917]
**环境信息**

go-cqhttp版本: v1.0.0-beta4
运行环境: windows
连接方式: http
使用协议: ipad

**bug内容**

当短时间收到过多的 CQ:tts 就会转码失败
![image](https://user-images.githubusercontent.com/68009112/121772054-aac4d200-cba5-11eb-871f-b3b376efa6c4.png)

**复现方法**

短时间收到过多的 CQ:tts 就会转码失败

**Comment by Kyomotoi** [comment]
这应该是腾讯那边的限制

**Comment by sam01101** [comment]
> **环境信息**
> 
> go-cqhttp版本: v1.0.0-beta4
> 运行环境: windows
> 连接方式: http
> 使用协议: ipad
> 
> **bug内容**
> 
> 当短时间收到过多的 CQ:tts 就会转码失败
> ![image](https://user-images.githubusercontent.com/68009112/121772054-aac4d200-cba5-11eb-871f-b3b376efa6c4.png)
> 
> **复现方法**
> 
> 短时间收到过多的 CQ:tts 就会转码失败

您好, 我想问一下您在短时间内调用的次数为多少?

**Comment by xiaowine** [comment]
大概每秒一次

**Comment by sam01101** [comment]
> 大概每秒一次

如果我是腾讯, 我早把你封了

**Comment by Ink-33** [comment]
> 大概每秒一次

如果我是腾讯, 我早把你封了

**Comment by fkx4-p** [comment]
如果我是腾讯，我早刀了你了

**Comment by xiaowine** [comment]
你们随意

**Comment by Kyomotoi** [comment]
> 你们随意

请问你听说过腾讯风控吗

**Comment by Kyomotoi** [comment]
> 你们随意

在此回复的均属该 repo 活跃的 contributer，如果有解决方法早回复了

**Comment by fkx4-p** [comment]
您需要考虑到以下几点：
1.文字转语音是需要系统资源的，如果不做限制那么腾讯早就被塞爆了。
2.腾讯限制调用频率之后，开发者对此无能为力，除非有能力把腾讯的运维全干翻，然而我们显然没有这种能力。
3.作为用户，我们应当尽量遵守相关规则，否则将面临风控甚至封号。
4.如果有人能够解决您的问题，除非腾讯放开了风控，那么恭喜他，他距离被腾讯以违法侵入计算机系统的罪名被告上法庭不远了。
5.Contributors的所说没错，如果有解决方法一定会拿出来的，所以请不要着急了，这不是简简单单能解决的问题。

**Comment by xiaowine** [comment]
我是没考率到风控，当没人喜欢嘲讽

**Comment by sam01101** [comment]
> 你们随意

我举个例子代表腾讯风控:

你是一名毒贩, 你正在偷偷摸摸的运毒
你在海外到海外的运气很好, 前几次(30-50次)都没被海关抓到
这是你的第52次运毒, 这次你要运到中国
而中国的海关发现了你的异常, 并开始监控着你
有时候有些流程比其他人慢了点, 但你没察觉这个问题, 以为只是慢了点而已

但你的小动作太明显了, 你被海关叫住并开始检查 **(风控开始)**

这里有两个结局, `Good end` 和 `Bad end`

Good End: 经过一段时间后, 因为你的小动作消失了, 所以你幸运的逃脱了 **(风控结束, 恢复正常)**

Bad End: 因为你在被发现后, 因为不停的躲避海关的眼神, 这引起了海关的警惕; 最后, 你的毒品被发现, 于是便被抓起来了 **(冻结 - 封号)**

以故事的形式带出来的话可以解决你说的"嘲讽"了吗?

**Comment by xiaowine** [comment]
> 您需要考虑到以下几点：
> 1.文字转语音是需要系统资源的，如果不做限制那么腾讯早就被塞爆了。
> 2.腾讯限制调用频率之后，开发者对此无能为力，除非有能力把腾讯的运维全干翻，然而我们显然没有这种能力。
> 3.作为用户，我们应当尽量遵守相关规则，否则将面临风控甚至封号。
> 4.如果有人能够解决您的问题，除非腾讯放开了风控，那么恭喜他，他距离被腾讯以违法侵入计算机系统的罪名被告上法庭不远了。
> 5.Contributors的所说没错，如果有解决方法一定会拿出来的，所以请不要着急了，这不是简简单单能解决的问题。

我是没考虑到风控，但没人喜欢嘲讽

**Comment by povsister** [comment]
八点半啦，饮茶先啦。

**Comment by xiaowine** [comment]
> > 你们随意
> 
> 我举个例子代表腾讯风控:
> 
> 你是一名毒贩, 你正在偷偷摸摸的运毒
> 你在海外到海外的运气很好, 前几次(30-50次)都没被海关抓到
> 这是你的第52次运毒, 这次你要运到中国
> 而中国的海关发现了你的异常, 并开始监控着你
> 有时候有些流程比其他人慢了点, 但你没察觉这个问题, 以为只是慢了点而已
> 
> 但你的小动作太明显了, 你被海关叫住并开始检查 **(风控开始)**
> 
> 这里有两个结局, `Good end` 和 `Bad end`
> 
> Good End: 经过一段时间后, 因为你的小动作消失了, 所以你幸运的逃脱了 **(风控结束, 恢复正常)**
> 
> Bad End: 因为你在被发现后, 因为不停的躲避海关的眼神, 这引起了海关的警惕; 最后, 你的毒品被发现, 于是便被抓起来了 **(冻结 - 封号)**
> 
> 以故事的形式带出来的话可以解决你说的"嘲讽"了吗?

我的每秒一次也只是极端测试，谁没事这样做

**Comment by Mrs4s** [comment]
这个来自tx的 api limit. 我们也无能为力.
使用本项目时请尽量不要滥用部分可能会消耗很多资源的api. 不然轻则被限制 重则封号.
