### ISSUE TITLE
合并转发消息未遵守onebot协议

### ISSUE THREAD

**Issue by Joenothing-lst** [Mrs4s/go-cqhttp#923]
**环境信息**

go-cqhttp版本: 1.0.0-beta4
运行环境: linux/centOS7
连接方式: ws
使用协议: pad

**bug内容**

合并转发消息未遵守onebot协议
位于 `node` 消息的 `data` 对象，在[onebot V11](https://github.com/botuniverse/onebot/blob/master/v11/specs/message/segment.md#%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9)标准中，发送者id应该是 `user_id` 而非 `uin` 。

**复现方法**

**Comment by Mrs4s** [comment]
会处理下
