### ISSUE TITLE
更换数据库以解决386构架下数据存取失败的问题

### ISSUE THREAD

**Issue by benx1n** [Mrs4s/go-cqhttp#93]
go-cqhttp版本: v0.9.18
运行环境: windows_386
连接方式: 反向WS

**bug内容**
在开启数据库后 调用reply 仍直接以CQ码文本形式发送
![78T%TYCUCY7 V823H{M_G E](https://user-images.githubusercontent.com/48101337/90090087-b5c88f00-dd55-11ea-8316-d9378de9b0ec.png)
查看目录结构后发现bucket初始化后内存并无增加

**Comment by Mrs4s** [comment]
请问是群聊消息吗, 私聊暂时不支持Reply

**Comment by benx1n** [comment]
是在群聊中 且是必现

**Comment by Mrs4s** [comment]
我这边无法复现，请确保回复的信息是数据库开启之后发送的

**Comment by benx1n** [comment]
数据库是开启了的 这是相关日志
![54MWN{$A~YVT4 JS{PRB6G8](https://user-images.githubusercontent.com/48101337/90119483-3609e700-dd8c-11ea-8f52-a34c4e0ad07f.png)

**Comment by Mrs4s** [comment]
打开debug, 并尝试`get_group_msg` api是否有同样的报错

**Comment by benx1n** [comment]
仍出现报错 日志：
[2020-08-13 18:44:16] [DEBUG]: WS接收到API调用: get_group_msg 参数: {"message_id":1660091210} 
[2020-08-13 18:44:16] [WARNING]: 获取信息时出现错误: key not found in the bucket

**Comment by Mrs4s** [comment]
怀疑是数据库入库的bug, 检查下 `data/db` 文件夹是否正常？

**Comment by benx1n** [comment]
db内bpt为空，meta-bucket内的group-messages.meta修改日期异常，大小为1k

**Comment by mahosho** [comment]
我这边在撤回群内消息的时候也出现了
[WARNING]: 获取信息时出现错误: key not found in the bucket id: 2036145645
版本：0.9.19-windows-386

**Comment by Mrs4s** [comment]
已确认windows-386会复现此问题. 将在后续版本尝试解决. 目前请尝试使用amd64版本
顺便你template的版本可能填错了. 害我研究半天

**Comment by benx1n** [comment]
@Mrs4s 非常抱歉= =看了下模板是win的就忘改了...所用版本确实是win-386，改用amd64后问题已解决
