### ISSUE TITLE
http post添加请求头, 用来描述该bot的监听端口

### ISSUE THREAD

**Issue by xiguasamall** [Mrs4s/go-cqhttp#931]
**环境信息**

go-cqhttp版本: 1.0.0-beta4

**需要添加的功能内容**

在http post 添加一个请求头, 用来描述该bot的监听的http端口

优点, 在程序中, 无需关心和维护该bot的监听端口, 用请求头携带过来的端口拼接成一个url
尤其在一个程序连接多个bot时, 优点特别明显, 再也不用手动建立bot和端口的映射关系了

**Comment by sam01101** [comment]
我想问下这个“服务器监听端口”是什么
还有请提供例子，就这么点信息没法得知实际需求

**Comment by Ink-33** [comment]
用处不大，应该不会做

**Comment by sam01101** [comment]
如果是QQ服务端的port，这个可以在log里面找到

**Comment by xiguasamall** [comment]
> 我想问下这个“服务器监听端口”是什么
> 还有请提供例子，就这么点信息没法得知实际需求

配置文件中的servers中http.port 的属性. 比如5701

**Comment by Yiwen-Chan** [comment]
既然都能 POST 了，那为什么不继续用原本的端口呢

**Comment by sam01101** [comment]
> > 我想问下这个“服务器监听端口”是什么
> > 还有请提供例子，就这么点信息没法得知实际需求
> 
> 配置文件中的servers中http.port 的属性. 比如5701

这就没必要了，读配置文件就可以了

**Comment by Yiwen-Chan** [comment]
建议使用websocket

**Comment by xiguasamall** [comment]
> > > 我想问下这个“服务器监听端口”是什么
> > > 还有请提供例子，就这么点信息没法得知实际需求
> > 
> > 
> > 配置文件中的servers中http.port 的属性. 比如5701
> 
> 这就没必要了，读配置文件就可以了

咦?配置文件中没有描述web_ui的端口了, 管理Api还能继续使用吗?

**Comment by sam01101** [comment]
> > > > 我想问下这个“服务器监听端口”是什么
> > > > 还有请提供例子，就这么点信息没法得知实际需求
> > > 
> > > 
> > > 配置文件中的servers中http.port 的属性. 比如5701
> > 
> > 
> > 这就没必要了，读配置文件就可以了
> 
> 咦?配置文件中没有描述web_ui的端口了, 管理Api还能继续使用吗?

啊？怎么没有
理论上代码就是完整的config转成json的

**Comment by Yiwen-Chan** [comment]
> > > > 我想问下这个“服务器监听端口”是什么
> > > > 还有请提供例子，就这么点信息没法得知实际需求
> > > 
> > > 
> > > 配置文件中的servers中http.port 的属性. 比如5701
> > 
> > 
> > 这就没必要了，读配置文件就可以了
> 
> 咦?配置文件中没有描述web_ui的端口了, 管理Api还能继续使用吗?

web_ui 是远古的东西了，很早就没了

**Comment by xiguasamall** [comment]
> 建议使用websocket

其实我想, 如果bot配置发生改变的话, 机器人的功能程序不用修改bot的http 监听端口了

**Comment by Ink-33** [comment]
> > 建议使用websocket
> 
> 其实我想, 如果bot配置发生改变的话, 机器人的功能程序不用修改bot的http 监听端口了

欢迎使用Websocket

**Comment by Mrs4s** [comment]
可以考虑新增一个获取配置文件的接口

**Comment by xiguasamall** [comment]
> > > 建议使用websocket
> > 
> > 
> > 其实我想, 如果bot配置发生改变的话, 机器人的功能程序不用修改bot的http 监听端口了
> 
> 欢迎使用Websocket

谢谢, 那我研究一下

**Comment by xiguasamall** [comment]
> > > > > 我想问下这个“服务器监听端口”是什么
> > > > > 还有请提供例子，就这么点信息没法得知实际需求
> > > > 
> > > > 
> > > > 配置文件中的servers中http.port 的属性. 比如5701
> > > 
> > > 
> > > 这就没必要了，读配置文件就可以了
> > 
> > 
> > 咦?配置文件中没有描述web_ui的端口了, 管理Api还能继续使用吗?
> 
> 啊？怎么没有
> 理论上代码就是完整的config转成json的

哇哦? 管理Api相关的接口还能继续使用??!

**Comment by Mrs4s** [comment]
> > > > > > 我想问下这个“服务器监听端口”是什么
> 
> > > > > > 还有请提供例子，就这么点信息没法得知实际需求
> 
> > > > > 
> 
> > > > > 
> 
> > > > > 配置文件中的servers中http.port 的属性. 比如5701
> 
> > > > 
> 
> > > > 
> 
> > > > 这就没必要了，读配置文件就可以了
> 
> > > 
> 
> > > 
> 
> > > 咦?配置文件中没有描述web_ui的端口了, 管理Api还能继续使用吗?
> 
> > 
> 
> > 啊？怎么没有
> 
> > 理论上代码就是完整的config转成json的
> 
> 
> 
> 哇哦? 管理Api相关的接口还能继续使用??!

别听他的 不能用了

**Comment by sam01101** [comment]
> > > > > > 我想问下这个“服务器监听端口”是什么
> > > > > > 还有请提供例子，就这么点信息没法得知实际需求
> > > > > 
> > > > > 
> > > > > 配置文件中的servers中http.port 的属性. 比如5701
> > > > 
> > > > 
> > > > 这就没必要了，读配置文件就可以了
> > > 
> > > 
> > > 咦?配置文件中没有描述web_ui的端口了, 管理Api还能继续使用吗?
> > 
> > 
> > 啊？怎么没有
> > 理论上代码就是完整的config转成json的
> 
> 哇哦? 管理Api相关的接口还能继续使用??!

我不知道代码有没有更新，如果没更新的话用不了正常

**Comment by Mrs4s** [comment]
> > > > > > > 我想问下这个“服务器监听端口”是什么
> 
> > > > > > > 还有请提供例子，就这么点信息没法得知实际需求
> 
> > > > > > 
> 
> > > > > > 
> 
> > > > > > 配置文件中的servers中http.port 的属性. 比如5701
> 
> > > > > 
> 
> > > > > 
> 
> > > > > 这就没必要了，读配置文件就可以了
> 
> > > > 
> 
> > > > 
> 
> > > > 咦?配置文件中没有描述web_ui的端口了, 管理Api还能继续使用吗?
> 
> > > 
> 
> > > 
> 
> > > 啊？怎么没有
> 
> > > 理论上代码就是完整的config转成json的
> 
> > 
> 
> > 哇哦? 管理Api相关的接口还能继续使用??!
> 
> 
> 
> 我不知道代码有没有更新，如果没更新的话用不了正常

是更新了后用不了 web ui老早就砍掉了

**Comment by xiguasamall** [comment]
> > > > > > > 我想问下这个“服务器监听端口”是什么
> > > > > > > 还有请提供例子，就这么点信息没法得知实际需求
> > > > > > 
> > > > > > 
> > > > > > 配置文件中的servers中http.port 的属性. 比如5701
> > > > > 
> > > > > 
> > > > > 这就没必要了，读配置文件就可以了
> > > > 
> > > > 
> > > > 咦?配置文件中没有描述web_ui的端口了, 管理Api还能继续使用吗?
> > > 
> > > 
> > > 啊？怎么没有
> > > 理论上代码就是完整的config转成json的
> > 
> > 
> > 哇哦? 管理Api相关的接口还能继续使用??!
> 
> 我不知道代码有没有更新，如果没更新的话用不了正常

其实我的机器人功能程序, 因为每天发送消息量很太, 所以一个程序连接了多个机器人
现在是在机器人功能程序启动时, 手动键入每个Bot对应http监听的端口, 如果后期bot需要维护的话, 可能在程序中,我还需要手动修改对应的http监听端口,
如果请求的时候携带了监听端口, 这样我直接拼接了url, 特别方便

我现在思索一下lnk-33 的ws方案试试

**Comment by xiguasamall** [comment]
> > > > > > > > 我想问下这个“服务器监听端口”是什么
> > 
> > 
> > > > > > > > 还有请提供例子，就这么点信息没法得知实际需求
> > 
> > 
> > > > > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > > > > > 配置文件中的servers中http.port 的属性. 比如5701
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > 这就没必要了，读配置文件就可以了
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > 咦?配置文件中没有描述web_ui的端口了, 管理Api还能继续使用吗?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 啊？怎么没有
> > 
> > 
> > > > 理论上代码就是完整的config转成json的
> > 
> > 
> > > 
> > 
> > 
> > > 哇哦? 管理Api相关的接口还能继续使用??!
> > 
> > 
> > 我不知道代码有没有更新，如果没更新的话用不了正常
> 
> 是更新了后用不了 web ui老早就砍掉了

合着, 我程序内部维护这一个Map<QQ, http监听端口>
现在是手动维护这个Map, 如果有获取配置文件的话, 也是半手动维护

**Comment by Yiwen-Chan** [comment]
立刻使用反向websocket

**Comment by xiguasamall** [comment]
> > > > > > > 我想问下这个“服务器监听端口”是什么
> > 
> > 
> > > > > > > 还有请提供例子，就这么点信息没法得知实际需求
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > 配置文件中的servers中http.port 的属性. 比如5701
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > 这就没必要了，读配置文件就可以了
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 咦?配置文件中没有描述web_ui的端口了, 管理Api还能继续使用吗?
> > 
> > 
> > > 
> > 
> > 
> > > 啊？怎么没有
> > 
> > 
> > > 理论上代码就是完整的config转成json的
> > 
> > 
> > 哇哦? 管理Api相关的接口还能继续使用??!
> 
> 别听他的 不能用了

哈哈哈哈, 我还以为是我笨了

**Comment by xiguasamall** [comment]
> 立刻使用反向websocket

好的谢谢, 我先了解一下, 我的需求和使用中问题已经描述好了,
现在我就去了解一下反向ws, 如何解决我的问题

**Comment by xiguasamall** [comment]
> 立刻使用反向websocket

请问一下, 如何使用反向ws, 让bot发送消息, 实在是没找到相关文档

**Comment by Mrs4s** [comment]
单论这个功能的话其实可以有的, 事件带上 `http api` 的监听端口, 方便回调
