### ISSUE TITLE
建议修改ocr报错

### ISSUE THREAD

**Issue by Mmx233** [Mrs4s/go-cqhttp#934]
**环境信息**

go-cqhttp版本: 1.0.0-beta1

**需要添加的功能内容**

建议把ocr的报错修改一下。没识别出文字的图片也是报错”服务忙,请稍后重试“，容易造成误导

**Comment by sam01101** [comment]
我建议你发bug反馈

**Comment by Mmx233** [comment]
可是我觉得从统一报错到别的应该算feature

**Comment by sam01101** [comment]
听我的，bug > feature request
