### ISSUE TITLE
建议修改ocr报错

### ISSUE THREAD

**Issue by Mmx233** [Mrs4s/go-cqhttp#935]
**环境信息**

go-cqhttp版本: 1.0.0-beta1
运行环境: Linux amd64
连接方式: websocket
使用协议: websocket + http

**bug内容**

建议把ocr的报错修改一下。没识别出文字的图片也是报错”服务忙,请稍后重试“，容易造成误导。

**复现方法**

使用ocr接口解析不带文字的图片

**Comment by sam01101** [comment]
? 卧槽 issue bot真nb

**Comment by Mmx233** [comment]
> ? 卧槽 issue bot真nb

是这样的，我甚至忍不住去翻了下代码

**Comment by Mrs4s** [comment]
没考虑到这种情况, 下个版本应该会处理
