### ISSUE TITLE
kick some one that not longer in group makes a nil pointer [signal SIGSEGV: segmentation

### ISSUE THREAD

**Issue by ChateauXiao** [Mrs4s/go-cqhttp#94]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.18
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x85fc69]

goroutine 10734 [running]:
github.com/Mrs4s/MiraiGo/client.(*GroupMemberInfo).Kick(0xc000f4efc0, 0x0, 0x0)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200812011522-ee1117893fad/client/entities.go:246 +0x29
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSetGroupKick(0xc00023e9c0, 0x1919dd70, 0x7a8be99f, 0x0, 0x0, 0x0)
        /github/workspace/coolq/api.go:274 +0x1e7
github.com/Mrs4s/go-cqhttp/server.glob..func17(0xc00023e9c0, 0x5, 0xc00037e107, 0x30, 0x0, 0x0, 0x0, 0x27, 0x6)
        /github/workspace/server/websocket.go:385 +0x201
github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenApi(0xc000093900, 0xc0001701b0, 0xc000544001)
        /github/workspace/server/websocket.go:170 +0x544
created by github.com/Mrs4s/go-cqhttp/server.(*websocketClient).connectUniversal
        /github/workspace/server/websocket.go:154 +0x54c

**复现方法**
[2020-08-13 07:19:50] [DEBUG]: 反向WS接收到API调用: set_group_kick 参数: {"group_id": xxxxxx, "user_id": "yyyyyyy"}

where user_id is no longer in that group ..

**Comment by Mrs4s** [comment]
#88
