### ISSUE TITLE
请求网络资源时自定义headers

### ISSUE THREAD

**Issue by RiotGamesU** [Mrs4s/go-cqhttp#940]
**环境信息**
os:win10 latest
go-cqhttp版本: latest

**需要添加的功能内容**

请求网络资源时自定义headers
网络资源:比如图片,音乐等
自定义headers:比如请求pixiv的图片时需要添加Referer

**Comment by Mrs4s** [comment]
请使用 `download_file` API. 支持自定义请求头和代理.

**Comment by RiotGamesU** [comment]
> `download_file`

好的谢谢
