### ISSUE TITLE
群聊消息没有撤回成功

### ISSUE THREAD

**Issue by lunzima** [Mrs4s/go-cqhttp#945]
**环境信息**

go-cqhttp版本: 1.0.0-beta4
运行环境: Ubuntu 20.04
连接方式: ws-reverse
使用协议: via nonebot2-adapter-cqhttp

**bug内容**

似乎已经正确执行了delete_msg，但是匹配关键字的群聊消息并没有撤回

**复现方法**

使用如下代码（dfafilter实现略）：

> def chat_rule() -> Rule:
>     async def _chat_rule(bot: "Bot", event: "Event", state: T_State) -> bool:
>         if str(event.user_id) == str(bot.self_id):
>             return False
>         if event.__getattribute__('message_type') == 'private':
>             group_id = None
>         else:
>             group_id = event.group_id
>         return True
>     return Rule(_chat_rule)
> 
> withdraw_bot = on_message(rule=chat_rule(), permission=None, priority=1, block=False)
> 
> @withdraw_bot.handle()
> async def handle_first_receive(bot: Bot, event: Event, state: T_State):
>     session = str(event.user_id)
>     args = str(event.get_message()).strip()
>     if dfafilter.has_profanities(args):
>         logger.info('Profanities censored!')
>         bot.delete_msg(message_id=event.message_id)
> 
> 

触发撤回条件时会得到Profanities censored!日志。

**Comment by sam01101** [comment]
```python3
# 我看到你的代码差点想骂人

def chat_rule() -> Rule:
  async def _chat_rule(bot: "Bot", event: "Event", state: T_State) -> bool:
    return event.message_type != "private" and str(event.user_id) != str(bot.self_id)

  return Rule(_chat_rule)

withdraw_bot = on_message(rule=chat_rule(), permission=None, priority=1, block=False)

@withdraw_bot.handle()
async def handle_first_receive(bot: Bot, event: Event, state: T_State):
  session = str(event.user_id)
  args = str(event.get_message()).strip()
  if dfafilter.has_profanities(args):
      logger.info('Profanities censored!')
      bot.delete_msg(message_id=event.message_id)
```
别撤回太快，太快会失败的

**Comment by lunzima** [comment]
加了10秒延时，没有效果

**Comment by sam01101** [comment]
> 加了10秒延时，没有效果

不妨做一个 `pool`，把需要撤回的 `message_id` 丢进去，然后起一个 `Queue` 来慢慢撤回
单个群的撤回速度有限制，但也只是单个群

**Comment by sam01101** [comment]
此外，这个问题不应该来问 `gocq`，我建议去 `nonebot2` 的 repo 开一个 issue，那边的开发者的答案应该会比我的答案更好

**Comment by lunzima** [comment]
尝试每隔一段时间就撤回一次，但是没有效果
delete_msg没有返回值也不是很方便判断消息到底有没有撤回

**Comment by sam01101** [comment]
> 尝试每隔一段时间就撤回一次，但是没有效果
> delete_msg没有返回值也不是很方便判断消息到底有没有撤回

换个账号撤回

**Comment by lunzima** [comment]
换了本人QQ大号也没有效果。

**Comment by sam01101** [comment]
> 换了本人QQ大号也没有效果。

尝试使用`HTTP`手动撤回

**Comment by lunzima** [comment]
异步函数没加await，锅了
