### ISSUE TITLE
调用 /send_group_forward_msg 失败

### ISSUE THREAD

**Issue by Anillc** [Mrs4s/go-cqhttp#946]
**环境信息**

go-cqhttp版本: v1.0.0-beta4 / v0.9.40-fix5
运行环境:  linux (CentOS 7)
连接方式:  websocket / http
使用协议:  iPad

**bug内容**

经过多次测试无法发送合并转发。  

表现：  
- 使用 v0.9.40-fix5 版本、koishi 框架、websocket 连接方式时调用 sendGroupForwardMsg 出现 `警告: 非法 Forward node 将跳过`  
- 更新至 v1.0.0-beta4 版本、koishi 框架、websocket 连接方式，调用该接口时不再报之前的错误，但是返回码为 `100` ，发送失败  
- 使用 v1.0.0-beta4 版本，http 请求方式，先后尝试 Get (浏览器中 fetch、Everest、Hoppscotch)、Post (Everest、Hoppscotch) 方法均返回 `100`  
- 尝试使用 mirai 进行自定义消息合并转发，成功发送  
- 粗略地看了一下代码，发现在 `CQSendGroupForwardMessage` 中有两个位置可能返回 `100` 但是由于对项目结构及 go 语言不熟悉，所以没有看出什么，建议可以优化一下报错提示  

**复现方法**

![image](https://user-images.githubusercontent.com/23411248/124347606-23083b80-dc18-11eb-9420-a3d7457053c3.png)
![image](https://user-images.githubusercontent.com/23411248/124347611-2996b300-dc18-11eb-9618-ec4fdf7eb112.png)

**Comment by Mrs4s** [comment]
能否贴一下 `go-cqhttp` 端的控制台输出

**Comment by Anillc** [comment]
抱歉，可能之前没有看清楚，在 `v1.0.0-beta4` 版本中仍然有 `警告: 非法 Forward node 将跳过` 的报错  

![image](https://user-images.githubusercontent.com/23411248/124348018-34eade00-dc1a-11eb-8010-338bdd385b30.png)

**Comment by Mrs4s** [comment]
https://github.com/Mrs4s/go-cqhttp/actions/runs/995933797 尝试使用这个版本, 我加了更多的日志

**Comment by Anillc** [comment]
使用该版本发送成功

**Comment by Mrs4s** [comment]
我应该只是改了点日志...

**Comment by Anillc** [comment]
但是他确实就发送成功了，api 调试器那边我没有改任何参数。不过换用这个版本之后无法建立 websocket 连接，配置文件我也没有动过，鉴权策略更改了吗  
![image](https://user-images.githubusercontent.com/23411248/124348491-c2c7c880-dc1c-11eb-83a3-f41daddbce98.png)

**Comment by Mrs4s** [comment]
看了下记录 老版本的 `uin` 参数应该只接收 `string` 类型. 鉴权应该没怎么动过才对, 我看看

**Comment by Mrs4s** [comment]
能不能提供一些 WS 连接鉴权相关代码

**Comment by Anillc** [comment]
啊，原来是只收 string 啊，我跟着文档写的数字  
![image](https://user-images.githubusercontent.com/23411248/124348601-5e593900-dc1d-11eb-8685-4d7ef6f5cc8c.png)
ws 我还在调试，之前从来没用过鉴权，都是留空的

**Comment by Mrs4s** [comment]
这个是文档typo 新版本已经和文档行为一致了.
如果调不通的话可以贴下代码

**Comment by Anillc** [comment]
好了，加上 token 就成功连上了
