### ISSUE TITLE
添加post上报地址后不断出错

### ISSUE THREAD

**Issue by Norm7X2** [Mrs4s/go-cqhttp#947]
**环境信息**

go-cqhttp版本: v1.0.0-beta4
运行环境: win10
连接方式: http
使用协议: 0

**bug内容**

![2](https://user-images.githubusercontent.com/86873105/124349313-002e5500-dc21-11eb-85bb-a181367f346f.jpg)
在config里面添加上报地址就会报错 如果加上#不上报就不出错 麻烦问一下怎么解决这个问题

**复现方法**

cmd打开正常运行就会出现

**Comment by Norm7X2** [comment]
啊啊啊麻烦管理员删除一下 我解决了 是我电脑的问题 麻烦了

**Comment by Ink-33** [comment]
建议自己close
