### ISSUE TITLE
多次调用返回 message_id 相同，消息实际未发出去

### ISSUE THREAD

**Issue by Arnie97** [Mrs4s/go-cqhttp#95]
**环境信息**
go-cqhttp版本: v0.9.18
运行环境: linux_amd64
连接方式: HTTP

**bug内容**
在群中发送不同消息后，返回的 message_id 相同，实际上全都未发出去。
重启 go-cqhttp 后一段时间发送正常。
接收消息始终正常。

**复现方法**
特定账号稳定复现，不是新挂机的账号。如果需要我可以改代码加日志打点。

**Comment by Mrs4s** [comment]
初步怀疑还是风控因素，message-id一样多半是因为seq返回的-1, 发送超时后seq会返回-1...

**Comment by Arnie97** [comment]
应该和 #38 重复了，也是发两个字节可以发送出去。
