### ISSUE TITLE
iPhone通知栏信息显示异常

### ISSUE THREAD

**Issue by ShootDeath** [Mrs4s/go-cqhttp#952]
**环境信息**

go-cqhttp版本: v1.0.0-beta4
运行环境: centos 7.6
连接方式: 反向ws
使用协议: iPad
bug复现手机系统: ios 14, ios 13, ios 10(其余系统未测试)
**bug内容**

通知栏信息显示异常，文字仅显示一行，且中文部分出现乱码，若发送纯数字显示又正常，使用utf-8编码方式，但是打开此条信息，qq内显示正常，调用api也显示成功发送{message_id:xxx}
![IMG_5161](https://user-images.githubusercontent.com/13230678/124853051-d33ec100-dfd7-11eb-9d82-a95f0dc62dbb.PNG)

**复现方法**

调用 bot.send_group_msg(group_id=xxx,message=Message(xxx)) 时出现此bug

**Comment by Mrs4s** [comment]
`iOS`由于是走的 Apple 的推送服务, 可能是QQ服务端处理消息的问题. 
有机会可以进一步测试一下 `Android` 是否有同样的问题

**Comment by ShootDeath** [comment]
目前手上没安卓机..等周末回家后 我再测测

**Comment by ShootDeath** [comment]
> `iOS`由于是走的 Apple 的推送服务, 可能是QQ服务端处理消息的问题.
> 有机会可以进一步测试一下 `Android` 是否有同样的问题

我这个华为手机本身就只显示了一行...测试了几条没看到乱码、但是只显示了一行
![2E6D6044DFB21CE55249A178C9B0BD32](https://user-images.githubusercontent.com/13230678/125106400-2e74ce80-e112-11eb-9289-a4367c3c9227.jpg)
![2440BD1C7FFCAB98DAD0F6445ADB9BDA](https://user-images.githubusercontent.com/13230678/125106442-36cd0980-e112-11eb-9722-ef494dd736de.jpg)

**Comment by ShootDeath** [comment]
可能真的跟苹果的推送机制有关系，只是不知道有没有办法避免这种问题
https://www.jianshu.com/p/b4196e097465
