### ISSUE TITLE
WS地址只支持同服务器地址吗？

### ISSUE THREAD

**Issue by 9raxdev** [Mrs4s/go-cqhttp#954]
**环境信息**
go-cqhttp版本: windows_amd64 v1.0.0-beta4
运行环境: windows
连接方式: 反向 ws
使用协议:ipad 

**bug内容**
当我业务在windows 本机跑的时候是正常的，但使用服务器地址就会连不上，提示错误

 [WARNING]: 连接到反向WebSocket Universal服务器 ws://47.115.10.102:8282/C86m5ae7 时出现错误: dial tcp 127.0.0.1:4780: connectex: N
o connection could be made because the target machine actively refused it.

![image](https://user-images.githubusercontent.com/11805413/125042881-f0a18700-e0cc-11eb-8cbb-cfbdc5fb7df9.png)

我很确定本机和服务器端口都是开放的，用浏览器测试ws地址也是可以连上去

**Comment by Mrs4s** [comment]
地址末尾加上 `/`

**Comment by 9raxdev** [comment]
> 地址末尾加上 `/`

![image](https://user-images.githubusercontent.com/11805413/125044755-dd8fb680-e0ce-11eb-8c5b-a000641a9029.png)
不对哦，我加了/也是这样，原理说不过去阿，如果我本地跑起ws的话地址是可以用的  比如ws://127.0.0.1:8282/C86m5ae7,同服务器就可以

**Comment by 9raxdev** [comment]
> 地址末尾加上 `/`

![image](https://user-images.githubusercontent.com/11805413/125045085-31020480-e0cf-11eb-814b-a4d5fa58740b.png)

**Comment by Ink-33** [comment]
你请求连接的是47.115.10.102:8282，但是被127.0.0.1:4700拒绝了连接

请确认

**Comment by Ink-33** [comment]
（说实话我还没有见过这种错误
![1625818510729.png](https://user-images.githubusercontent.com/51873347/125046692-d79ad500-e0d0-11eb-93e0-e2e1c412cf26.png)

**Comment by 9raxdev** [comment]
我可能大概知道了，这个端口是代理端口，不过奇葩的是我关了代理，或者改了代理端口，貌似有些程序还会走代理记录，我在navicat软件上也碰到过这种情况，可能是windows的bug


![image](https://user-images.githubusercontent.com/11805413/125047651-c3a3a300-e0d1-11eb-8a49-4a64454722c3.png)

4780是旧的代理端口  4888是临时改的  并且关了代理，跑起来还是那个代理阻止，应该是我使用电脑的问题，我本地win11这个问题也让我郁闷过，现在可能明白一些了
