### ISSUE TITLE
群多的时候,取的群列表信息返回的JSON有问题

### ISSUE THREAD

**Issue by qwe0099001** [Mrs4s/go-cqhttp#955]
**环境信息**

go-cqhttp版本: 1.0.0.beta4
运行环境: WIN10
连接方式: 反向WS
使用协议: IPAD

**bug内容**
群多的时候,取的群列表信息返回的JSON有问题

**复现方法**

{
    "data": [{
        "group_create_time": 0,
        "group_id": 79261617,
        "group_level": 0,
        "group_memo": "管理员不要让发广告的人进来，现在进群的差不多都是发广告的，请注意点！",
        "group_name": "交友互赞群.",
        "max_member_count": 2000,
        "member_count": 406
    }, {
        "group_create_time": 0,
        "group_id": 100400800,
        "group_level": 0,
        "group_memo": "",
        "group_name": "100400800",
        "max_member_count": 500,
        "member_count": 14
    }, {
        "group_create_time": 0,
        "group_id": 117498742,
        "group_level": 0,
        "group_memo": "",
        "group_name": "。",
        "max_member_count": 500,
        "member_count": 376
    }, {
        "group_create_time": 0,
        "group_id": 141609405,
        "group_level": 0,
        "group_memo": "",
        "group_name": "抖音热搜影视圈60",
        "max_member_count": 2000,
        "member_count": 1129
    }, {
        "group_create_time": 0,
        "group_id": 171897727,
        "group_level": 0,
        "group_memo": "勿骂人",
        "group_name": "聊天群",
        "max_member_count": 200,
        "member_count": 8
    }, {
        "group_create_time": 0,
        "group_id": 172986165,
        "group_level": 0,
        "group_memo": "单身yyds.",
        "group_name": "yyds",
        "max_member_count": 200,
        "member_count": 131
    }, {
        "group_create_time": 0,
        "group_id": 200191893,
        "group_level": 0,
        "group_memo": "不要刷屏，不要发广告。要头衔私聊群主，谢谢。简单明了。不要宣群，不要发乱七八糟的东西，文明聊天，不然",
        "group_name": "扩列唠嗑处cp",
        "max_member_count": 2000,
        "member_count": 1650
    }, {
        "group_create_time": 0,
        "group_id": 201133505,
        "group_level": 0,
        "group_memo": "发广告宣传其他群。一律踢。请自觉遵守群规，谢谢！！！发广告宣传其他群。一律踢。请自觉遵守群规，谢谢",
        "group_name": "互赞/扩列群",
        "max_member_count": 2000,
        "member_count": 1934
    }, {
        "group_create_time": 0,
        "group_id": 202010030,
        "group_level": 0,
        "group_memo": "用了一下群恢复，如有打扰请见谅，请配合工作，谢谢！",
        "group_name": "扩列/交友/暖说说",
        "max_member_count": 3000,
        "member_count": 1155
    }, {
        "group_create_time": 0,
        "group_id": 207570947,
        "group_level": 0,
        "group_memo": "",
        "group_name": "ASMR秋名山之旅",
        "max_member_count": 500,
        "member_count": 473
    }, {
        "group_create_time": 0,
        "group_id": 225235116,
        "group_level": 0,
        "group_memo": "-",
        "group_name": "优质扩列恋爱",
        "max_member_count": 2000,
        "member_count": 1550
    }, {
        "group_create_time": 0,
        "group_id": 225764164,
        "group_level": 0,
        "group_memo": "",
        "group_name": "QQ空间名片互赞群扩列",
        "max_member_count": 2000,
        "member_count": 1101
    }, {
        "group_create_time": 0,
        "group_id": 229771102,
        "group_level": 0,
        "group_memo": "-",
        "group_name": "1515",
        "max_member_count": 2000,
        "member_count": 523
    }, {
        "group_create_time": 0,
        "group_id": 237854330,
        "group_level": 0,
        "group_memo": "",
        "group_name": "挥不去的记忆青春H192",
        "max_member_count": 2000,
        "member_count": 1930
    }, {
        "group_create_time": 0,
        "group_id": 276360418,
        "group_level": 0,
        "group_memo": "",
        "group_name": "1",
        "max_member_count": 2000,
        "member_count": 890
    }, {
        "group_create_time": 0,
        "group_id": 290856557,
        "group_level": 0,
        "group_memo": "质量保证，价格便宜，谢谢大家前去支持，浏览器打开：http://20001013.tzdsb.com/",
        "group_name": "扩列 nss cqy",
        "max_member_count": 500,
        "member_count": 470
    }, {
        "group_create_time": 0,
        "group_id": 297307872,
        "group_level": 0,
        "group_memo": "别宣群 别打广告 别刷图 别眼瞎",
        "group_name": "【全网唱歌扩列处关系群】",
        "max_member_count": 500,
        "member_count": 490
    }, {
        "group_create_time": 0,
        "group_id": 310680243,
        "group_level": 0,
        "group_memo": "这个暑假你想要更有趣吗？\r\r那就来听老师的课吧\r针对数理化专项练习\r戳链接加入哦\rhttps://c.ei72.com/xyd3",
        "group_name": "【数理化生】核心考点内部资料21群",
        "max_member_count": 2000,
        "member_count": 676
    }, {
        "group_create_time": 0,
        "group_id": 331514191,
        "group_level": 0,
        "group_memo": "",
        "group_name": "QQ能领红包的进",
        "max_member_count": 500,
        "member_count": 384
    }, {
        "group_create_time": 0,
        "group_id": 336340074,
        "group_level": 0,
        "group_memo": "",
        "group_name": "魚龍混雜",
        "max_member_count": 200,
        "member_count": 7
    }, {
        "group_create_time": 0,
        "group_id": 338759812,
        "group_level": 0,
        "group_memo": "本群新开业，进群的小伙伴们帮忙扩展人数",
        "group_name": "长期互赞群",
        "max_member_count": 500,
        "member_count": 489
    }, {
        "group_create_time": 0,
        "group_id": 338788767,
        "group_level": 0,
        "group_memo": "",
        "group_name": "扩列处cp养草养火花",
        "max_member_count": 2000,
        "member_count": 1208
    }, {
        "group_create_time": 0,
        "group_id": 378620804,
        "group_level": 0,
        "group_memo": "禁止搞w，刷屏，斗图，骂人，图过三踢，别整天整这些有的没的。",
        "group_name": "优质扩列聊天圈",
        "max_member_count": 2000,
        "member_count": 1078
    }, {
        "group_create_time": 0,
        "group_id": 397112060,
        "group_level": 0,
        "group_memo": "",
        "group_name": "小罗软件库A17",
        "max_member_count": 2000,
        "member_count": 1045
    }, {
        "group_create_time": 0,
        "group_id": 434184058,
        "group_level": 0,
        "group_memo": "",
        "group_name": "水瓶座颂贊",
        "max_member_count": 2000,
        "member_count": 1941
    }, {
        "group_create_time": 0,
        "group_id": 459372618,
        "group_level": 0,
        "group_memo": "",
        "group_name": "想给你写封情书",
        "max_member_count": 2000,
        "member_count": 1892
    }, {
        "group_create_time": 0,
        "group_id": 479241858,
        "group_level": 0,
        "group_memo": "还在为没有靠谱的打字商家烦恼吗？还在担心违约金太高吗？还在担心没有客户担心吗？还在担心商家跑路？端午",
        "group_name": "十三-广告群\u003c5b\u003e上人卡管",
        "max_member_count": 500,
        "member_count": 353
    }, {
        "group_create_time": 0,
        "group_id": 482663050,
        "group_level": 0,
        "group_memo": "点击链接加入群聊【免费高佣金打字团】：https://jq.qq.com/?_wv=1027\u0026k=wTCCJtt6",
        "group_name": "暮然窝",
        "max_member_count": 1000,
        "member_count": 915
    }, {
        "group_create_time": 0,
        "group_id": 499428951,
        "group_level": 0,
        "group_memo": "@所有人进群不能说脏话不许骂人",
        "group_name": "月夏家",
        "max_member_count": 200,
        "member_count": 19
    }, {
        "group_create_time": 0,
        "group_id": 519282825,
        "group_level": 0,
        "group_memo": "",
        "group_name": "〈季梦〉赚钱窝",
        "max_member_count": 2000,
        "member_count": 367
    }, {
        "group_create_time": 0,
        "group_id": 527633049,
        "group_level": 0,
        "group_memo": "",
        "group_name": "挥不去的记忆青春H205",
        "max_member_count": 2000,
        "member_count": 1951
    }, {
        "group_create_time": 0,
        "group_id": 554854760,
        "group_level": 0,
        "group_memo": "",
        "group_name": "00后的乐园",
        "max_member_count": 500,
        "member_count": 200
    }, {
        "group_create_time": 0,
        "group_id": 554863949,
        "group_level": 0,
        "group_memo": "橙子插件5.4.1【就是群里的那个机器人】界面细节优化完善授权版完善运行流畅修复bug",
        "group_name": "扩列互赞交友聊天处关系",
        "max_member_count": 2000,
        "member_count": 850
    }, {
        "group_create_time": 0,
        "group_id": 557814134,
        "group_level": 0,
        "group_memo": "有事找管理有事找管理有事找管理！我设这么多管理是干嘛的，没点数吗?",
        "group_name": "宝贝互赞不②",
        "max_member_count": 500,
        "member_count": 491
    }, {
        "group_create_time": 0,
        "group_id": 567156782,
        "group_level": 0,
        "group_memo": "请不要在发扩列了，发扩列直接踢",
        "group_name": "休闲聊天扩列群",
        "max_member_count": 2000,
        "member_count": 1172
    }, {
        "group_create_time": 0,
        "group_id": 577480207,
        "group_level": 0,
        "group_memo": "现在想当管理员的踊跃报名哟，名额有限。注意以下几点：1，不能是小号，QQ必须有一颗太阳2，要经常在线，",
        "group_name": "互赞/聊天/扩列/暖说说",
        "max_member_count": 500,
        "member_count": 466
    }, {
        "group_create_time": 0,
        "group_id": 598797911,
        "group_level": 0,
        "group_memo": "",
        "group_name": "悦悦不禁言广告群④",
        "max_member_count": 200,
        "member_count": 189
    }, {
        "group_create_time": 0,
        "group_id": 600720253,
        "group_level": 0,
        "group_memo": "",
        "group_name": "",
        "max_member_count": 2000,
        "member_count": 709
    }, {
        "group_create_time": 0,
        "group_id": 605053508,
        "group_level": 0,
        "group_memo": "请文明用语别骂人和平相处谢谢配合！谢谢",
        "group_name": "扩列聊天处cp",
        "max_member_count": 500,
        "member_count": 331
    }, {
        "group_create_time": 0,
        "group_id": 609271435,
        "group_level": 0,
        "group_memo": "",
        "group_name": "聊天群",
        "max_member_count": 500,
        "member_count": 50
    }, {
        "group_create_time": 0,
        "group_id": 620243589,
        "group_level": 0,
        "group_memo": "",
        "group_name": "挥不去的记忆青春H183",
        "max_member_count": 2000,
        "member_count": 1933
    }, {
        "group_create_time": 0,
        "group_id": 627384435,
        "group_level": 0,
        "group_memo": "群里的朋友们都和谐相处有什么大无语事件找管理处理",
        "group_name": "江苏扩列.",
        "max_member_count": 1000,
        "member_count": 773
    }, {
        "group_create_time": 0,
        "group_id": 638481955,
        "group_level": 0,
        "group_memo": "",
        "group_name": "",
        "max_member_count": 2000,
        "member_count": 623
    }, {
        "group_create_time": 0,
        "group_id": 641195668,
        "group_level": 0,
        "group_memo": "",
        "group_name": "王者荣耀",
        "max_member_count": 200,
        "member_count": 161
    }, {
        "group_create_time": 0,
        "group_id": 645742528,
        "group_level": 0,
        "group_memo": "-",
        "group_name": "1515",
        "max_member_count": 2000,
        "member_count": 591
    }, {
        "group_create_time": 0,
        "group_id": 666768103,
        "group_level": 0,
        "group_memo": "",
        "group_name": "勇敢牛牛不怕困难",
        "max_member_count": 200,
        "member_count": 87
    }, {
        "group_create_time": 0,
        "group_id": 673112453,
        "group_level": 0,
        "group_memo": "末秀恩爱千万别秀",
        "group_name": "潍坊特产辣嘎哒交流群",
        "max_member_count": 2000,
        "member_count": 717
    }, {
        "group_create_time": 0,
        "group_id": 673144727,
        "group_level": 0,
        "group_memo": "",
        "group_name": "聊天群",
        "max_member_count": 200,
        "member_count": 17
    }, {
        "group_create_time": 0,
        "group_id": 675135536,
        "group_level": 0,
        "group_memo": "",
        "group_name": "",
        "max_member_count": 2000,
        "member_count": 1112
    }, {
        "group_create_time": 0,
        "group_id": 676873663,
        "group_level": 0,
        "group_memo": "你没有排面，全看我心情！你没有排面，全看我心情！你没有排面，全看我心情！你没有排面，全看我心情！",
        "group_name": "圈子",
        "max_member_count": 2000,
        "member_count": 1124
    }, {
        "group_create_time": 0,
        "group_id": 693365701,
        "group_level": 0,
        "group_memo": "",
        "group_name": "",
        "max_member_count": 2000,
        "member_count": 863
    }, {
        "group_create_time": 0,
        "group_id": 696099266,
        "group_level": 0,
        "group_memo": "要管理加我",
        "group_name": "互赞扩列聊天群①",
        "max_member_count": 2000,
        "member_count": 1903
    }, {
        "group_create_time": 0,
        "group_id": 698038664,
        "group_level": 0,
        "group_memo": "①每拉一人送300名片赞，10-30分钟到账领取人数较多，没有及时唰到，请耐心等待。\r②禁止拉机器人，小号，死",
        "group_name": "cp扩列互赞交友群22",
        "max_member_count": 2000,
        "member_count": 1911
    }, {
        "group_create_time": 0,
        "group_id": 700305735,
        "group_level": 0,
        "group_memo": "",
        "group_name": "扩列交友群",
        "max_member_count": 200,
        "member_count": 1946
    }, {
        "group_create_time": 0,
        "group_id": 703452745,
        "group_level": 0,
        "group_memo": "",
        "group_name": "名片说说互赞扩列群",
        "max_member_count": 2000,
        "member_count": 1777
    }, {
        "group_create_time": 0,
        "group_id": 709510313,
        "group_level": 0,
        "group_memo": "",
        "group_name": "情侣多了.单身才养眼",
        "max_member_count": 200,
        "member_count": 9
    }, {
        "group_create_time": 0,
        "group_id": 709772634,
        "group_level": 0,
        "group_memo": "",
        "group_name": "扩列 养草 养火花  任何",
        "max_member_count": 2000,
        "member_count": 844
    }, {
        "group_create_time": 0,
        "group_id": 710970197,
        "group_level": 0,
        "group_memo": "",
        "group_name": "大赦天下",
        "max_member_count": 200,
        "member_count": 16
    }, {
        "group_create_time": 0,
        "group_id": 714941870,
        "group_level": 0,
        "group_memo": "-",
        "group_name": "",
        "max_member_count": 2000,
        "member_count": 590
    }, {
        "group_create_time": 0,
        "group_id": 724982832,
        "group_level": 0,
        "group_memo": "",
        "group_name": "唠嗑游戏交友群",
        "max_member_count": 2000,
        "member_count": 294
    }, {
        "group_create_time": 0,
        "group_id": 737819501,
        "group_level": 0,
        "group_memo": "本群已安装小霸王游戏机请尽情体验http://fc.my71.top/",
        "group_name": "全网交友互赞扩列群\u003c$"
        yA\u0011\u0010\u003e ","
        max_member_count ":1000,"
        member_count ":902},{"
        group_create_time ":0,"
        group_id ":740266543,"
        group_level ":0,"
        group_memo ":"
        ","
        group_name ":"
        1515 ","
        max_member_count ":2000,"
        member_count ":936},{"
        group_create_time ":0,"
        group_id ":755023941,"
        group_level ":0,"
        group_memo ":"
        ","
        group_name ":"
        QQ名片空间送赞群","
        max_member_count ":200,"
        member_count ":1053},{"
        group_create_time ":0,"
        group_id ":757153204,"
        group_level ":0,"
        group_memo ":"
        ","
        group_name ":"
        qq空间名片互赞","
        max_member_count ":2000,"
        member_count ":1378},{"
        group_create_time ":0,"
        group_id ":760102116,"
        group_level ":0,"
        group_memo ":"没啥要求多拉人唠会嗑啥的就行拉8卡管拉3找群主要头衔","
        group_name ":"扩列聊天互赞","
        max_member_count ":500,"
        member_count ":97},{"
        group_create_time ":0,"
        group_id ":775356763,"
        group_level ":0,"
        group_memo ":"
        ","
        group_name ":"
        1赞转1 ","
        max_member_count ":200,"
        member_count ":5},{"
        group_create_time ":0,"
        group_id ":777372580,"
        group_level ":0,"
        group_memo ":"拉人卡管理","
        group_name ":"阿城扩列交友聊天总群","
        max_member_count ":2000,"
        member_count ":1225},{"
        group_create_time ":0,"
        group_id ":778980228,"
        group_level ":0,"
        group_memo ":"群规: （我来说明一下) 1.本群不允许发任何广告及宣群2.禁止骂人、呵呵，刷图其他的等……3.本群不允许开车，","
    group_name ":"
    CP扩列交友聊天","
    max_member_count ":2000,"
    member_count ":1934},{"
    group_create_time ":0,"
    group_id ":781061724,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"啦人送名片赞D8 ","
    max_member_count ":2000,"
    member_count ":1813},{"
    group_create_time ":0,"
    group_id ":795425800,"
    group_level ":0,"
    group_memo ":"群里玩光遇的ios区的可以私我备注 + 链接跟我解锁击掌以后可以带进办公室","
    group_name ":"聊天 / 扩列 / 吃鸡 / 王者 / 声控 / nss + /cp","max_member_count":1000,"member_count":823},{"group_create_time":0,"group_id":796989847,"group_level":0,"group_memo":"","group_name":"刷点赞群","max_member_count":500,"member_count":145},{"group_create_time":0,"group_id":797874214,"group_level":0,"group_memo":"","group_name":"名片空间说说互赞(14)群","max_member_count":2000,"member_count":1019},{"group_create_time":0,"group_id":807321348,"group_level":0,"group_memo":"","group_name":"挥不去的记忆青春H140","max_member_count":2000,"member_count":1935},{"group_create_time":0,"group_id":810643342,"group_level":0,"group_memo":"发现一个好玩的微信群！你不来吗？\r\r\r微信群老师长期伴学送资料\r还定期送各类读物图书\r老师发各类发福利","group_name":"初中寒假预习资料22群","max_member_count":2000,"member_count":599},{"group_create_time":0,"group_id":813859249,"group_level":0,"group_memo":"","group_name":"挥不去的记忆青春H166","max_member_count":2000,"member_count":1948},{"group_create_time":0,"group_id":815622783,"group_level":0,"group_memo":"恭喜获得管理群里的黑丝妹妹们速度冲冲冲上去干翻他 让他从此厌倦黑丝美腿管理限时28.88头衔9.99永久 管理","group_name":"扩列聊天恋爱","max_member_count":2000,"member_count":1462},{"group_create_time":0,"group_id":825354028,"group_level":0,"group_memo":"由于人数增多设置一些规则方便管理本群1.不得在本群分享其他群聊，发现者直接踢2.不得在群里开车（什么意","group_name":"扩列互赞cpdd","max_member_count":500,"member_count":422},{"group_create_time":0,"group_id":831846087,"group_level":0,"group_memo":"24小时自助下单网站：kehu.fafalaozs.cn客服在线：9：30-23：59","group_name":"抖音快手网红扩列交友","max_member_count":2000,"member_count":1022},{"group_create_time":0,"group_id":835260624,"group_level":0,"group_memo":"各位兄弟姐妹们我班同学问我要管理，我给他了，没想他他把人都移了，能邀回来的在邀回来，谢谢","group_name":"花果山 ","max_member_count":500,"member_count":373},{"group_create_time":0,"group_id":836752461,"group_level":0,"group_memo":"本群仪容仪表要求男性应穿好西装并佩戴领结，头发最好控制在3-7厘米左右，刘海不能遮挡住眉毛，侧部头发不","group_name":"连麦处cp交友群","max_member_count":2000,"member_count":1263},{"group_create_time":0,"group_id":839768483,"group_level":0,"group_memo":"三太55 皇冠128 皇冠还剩一个代刷各种赞联系群主","group_name":"QQ账号交易群","max_member_count":500,"member_count":213},{"group_create_time":0,"group_id":851292843,"group_level":0,"group_memo":"为了防止群里机器人，纤儿打算明天早上踢人，请各位家人们是真人就在群聊名称前面加xs 比如我的名字，谢谢家","group_name":"优质扩列聊天交友群","max_member_count":500,"member_count":485},{"group_create_time":0,"group_id":851868227,"group_level":0,"group_memo":"","group_name":"霸霸","max_member_count":200,"member_count":12},{"group_create_time":0,"group_id":861791232,"group_level":0,"group_memo":"","group_name":"扩列交友群","max_member_count":2000,"member_count":1996},{"group_create_time":0,"group_id":870643129,"group_level":0,"group_memo":"小号自行退","group_name":"cp/连麦 / cdx / 扩列 / 小可爱","
    max_member_count ":500,"
    member_count ":351},{"
    group_create_time ":0,"
    group_id ":870775330,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"扩列.","
    max_member_count ":200,"
    member_count ":134},{"
    group_create_time ":0,"
    group_id ":892104923,"
    group_level ":0,"
    group_memo ":"我们进群就是一家人，希望大家可以别退群，也别没有给你管理员就退群，希望大家可以好好配合，谢谢","
    group_name ":"德云社大班（禁止退群）","
    max_member_count ":200,"
    member_count ":45},{"
    group_create_time ":0,"
    group_id ":909624775,"
    group_level ":0,"
    group_memo ":" - ","
    group_name ":"
    ","
    max_member_count ":2000,"
    member_count ":1551},{"
    group_create_time ":0,"
    group_id ":915698364,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"
    qq名片空间点赞互赞群","
    max_member_count ":2000,"
    member_count ":1027},{"
    group_create_time ":0,"
    group_id ":916410844,"
    group_level ":0,"
    group_memo ":"邀请1人奖励1000赞\r邀请10人进群直接奖励3万名片赞 + 1年SVIP\r不允许拉机器人进群一旦发现取消奖励资格","
    group_name ":"拉人进群年费领取1000个赞C ","
    max_member_count ":2000,"
    member_count ":1814},{"
    group_create_time ":0,"
    group_id ":932627398,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"
    QQ聊天扩列群","
    max_member_count ":500,"
    member_count ":369},{"
    group_create_time ":0,"
    group_id ":932780533,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"天猫吃货不禁言群","
    max_member_count ":2000,"
    member_count ":962},{"
    group_create_time ":0,"
    group_id ":936564863,"
    group_level ":0,"
    group_memo ":"所有人改群昵称：马甲格式：楠家军—XXX !! !! 每个人都得改，7：00之前不改的全退出群。","
    group_name ":"
    Chaney林秋楠粉丝总部②","
    max_member_count ":1000,"
    member_count ":517},{"
    group_create_time ":0,"
    group_id ":939680830,"
    group_level ":0,"
    group_memo ":"不可以骂人口哦！可以拉其他人进群","
    group_name ":"聊天群 (小仙女们的群)","
    max_member_count ":200,"
    member_count ":15},{"
    group_create_time ":0,"
    group_id ":948946094,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"扩列互赞空间暖说说","
    max_member_count ":2000,"
    member_count ":1731},{"
    group_create_time ":0,"
    group_id ":956584626,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"唠嗑游戏交友群","
    max_member_count ":2000,"
    member_count ":1064},{"
    group_create_time ":0,"
    group_id ":957861031,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"
    ","
    max_member_count ":2000,"
    member_count ":1896},{"
    group_create_time ":0,"
    group_id ":958121624,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"互赞扩列暖说说赞空间","
    max_member_count ":200,"
    member_count ":191},{"
    group_create_time ":0,"
    group_id ":966680148,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"抖音作品双击互赞","
    max_member_count ":200,"
    member_count ":133},{"
    group_create_time ":0,"
    group_id ":967567051,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"挥不去的记忆青春H112 ","
    max_member_count ":2000,"
    member_count ":1943},{"
    group_create_time ":0,"
    group_id ":971123609,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"互赞扩列暖说说赞空间","
    max_member_count ":2000,"
    member_count ":958},{"
    group_create_time ":0,"
    group_id ":971206020,"
    group_level ":0,"
    group_memo ":"从现在开始，本群禁止外来家族招人，外来家族如果想招人的话请进互进组织群，别在这儿招，这里是聊天群，不","
    group_name ":"我们的青春","
    max_member_count ":200,"
    member_count ":167},{"
    group_create_time ":0,"
    group_id ":977867665,"
    group_level ":0,"
    group_memo ":"群规（群员必看）1.本群群主最大，都不许欺负群主和管理员！！！2.禁止骂人（违反者管理员踢）3.禁止刷屏，","
    group_name ":"声优群","
    max_member_count ":200,"
    member_count ":40},{"
    group_create_time ":0,"
    group_id ":992679271,"
    group_level ":0,"
    group_memo ":"群主已退圈，不会在进行任何交易，如果有一定是代码！！！！！","
    group_name ":"小圈子","
    max_member_count ":200,"
    member_count ":957},{"
    group_create_time ":0,"
    group_id ":996818294,"
    group_level ":0,"
    group_memo ":"优质扩列群956053839 ","
    group_name ":"扩列交友暖说说⑤","
    max_member_count ":2000,"
    member_count ":1278},{"
    group_create_time ":0,"
    group_id ":1014662006,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"
    QQ空间名片互赞群扩列","
    max_member_count ":2000,"
    member_count ":1719},{"
    group_create_time ":0,"
    group_id ":1018293082,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"杭州90后扩列交友","
    max_member_count ":200,"
    member_count ":1562},{"
    group_create_time ":0,"
    group_id ":1032169696,"
    group_level ":0,"
    group_memo ":"
    3an.top卡网","
    group_name ":"
    iOS / 安卓高端游戏科技","
    max_member_count ":2000,"
    member_count ":1729},{"
    group_create_time ":0,"
    group_id ":1034953898,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"沙雕幼儿园［欢迎你］","
    max_member_count ":200,"
    member_count ":130},{"
    group_create_time ":0,"
    group_id ":1036079311,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"快手白院长粉丝群","
    max_member_count ":2000,"
    member_count ":516},{"
    group_create_time ":0,"
    group_id ":1038017840,"
    group_level ":0,"
    group_memo ":"本群禁止发起现金交易，发现立即踢出，不给解释","
    group_name ":"长城之畔","
    max_member_count ":200,"
    member_count ":151},{"
    group_create_time ":0,"
    group_id ":1038889171,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"唠嗑游戏交友群","
    max_member_count ":2000,"
    member_count ":1303},{"
    group_create_time ":0,"
    group_id ":1043273987,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"魔法士颂攒","
    max_member_count ":2000,"
    member_count ":1944},{"
    group_create_time ":0,"
    group_id ":1044224521,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"聊天","
    max_member_count ":200,"
    member_count ":9},{"
    group_create_time ":0,"
    group_id ":1044817333,"
    group_level ":0,"
    group_memo ":"嗝，新人们，看看公告，扩列啥的改马甲，别再群里叭叭，OK？","
    group_name ":"￡优质扩列交友群","
    max_member_count ":2000,"
    member_count ":990},{"
    group_create_time ":0,"
    group_id ":1051825110,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"沙雕交友声控群","
    max_member_count ":2000,"
    member_count ":504},{"
    group_create_time ":0,"
    group_id ":1053014353,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"
    cp扩列互赞交友群179 ","
    max_member_count ":2000,"
    member_count ":1830},{"
    group_create_time ":0,"
    group_id ":1053875394,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"挥不去的记忆的青春48 ","
    max_member_count ":2000,"
    member_count ":1886},{"
    group_create_time ":0,"
    group_id ":1059943326,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"广告群不禁言","
    max_member_count ":2000,"
    member_count ":2000},{"
    group_create_time ":0,"
    group_id ":1060185719,"
    group_level ":0,"
    group_memo ":"最近这段时间，qq微信头像昵称都改不了了，视频软件弹幕也来不了，微博会员也带不了图评论，头像昵称都改不","
    group_name ":"优质声优扩列群","
    max_member_count ":2000,"
    member_count ":745},{"
    group_create_time ":0,"
    group_id ":1065620595,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"沙雕交友声控群","
    max_member_count ":2000,"
    member_count ":271},{"
    group_create_time ":0,"
    group_id ":1079518299,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"懵懂的我们 - 18 ","
    max_member_count ":2000,"
    member_count ":1703},{"
    group_create_time ":0,"
    group_id ":1080695998,"
    group_level ":0,"
    group_memo ":"别发广告","
    group_name ":"网恋处cp游戏群","
    max_member_count ":200,"
    member_count ":196},{"
    group_create_time ":0,"
    group_id ":1081797734,"
    group_level ":0,"
    group_memo ":"拉十人找我那Max云防周卡","
    group_name ":"
    MAX交流群，不禁言","
    max_member_count ":2000,"
    member_count ":117},{"
    group_create_time ":0,"
    group_id ":1085989025,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"传奇宣传不禁言①","
    max_member_count ":500,"
    member_count ":464},{"
    group_create_time ":0,"
    group_id ":1090317300,"
    group_level ":0,"
    group_memo ":"欢迎来到此群群规1.不许乱改群名2.不许在此群CPdd，不许扩列3.不许向群主要管理，除非群主自给4.不许刷屏5.","
    group_name ":"真心话大冒险","
    max_member_count ":200,"
    member_count ":67},{"
    group_create_time ":0,"
    group_id ":1102711212,"
    group_level ":0,"
    group_memo ":"多拉甜筒1.拒绝辱骂、挑事2.拒绝发广告3.本群禁止骂人，如果骂人自觉退出群聊，否则群主和管理员移出群聊4 ","
    group_name ":"晓彤粉丝群","
    max_member_count ":200,"
    member_count ":51},{"
    group_create_time ":0,"
    group_id ":1104078236,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"全网00后扩列处cp群","
    max_member_count ":2000,"
    member_count ":966},{"
    group_create_time ":0,"
    group_id ":1104950259,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"
    ","
    max_member_count ":2000,"
    member_count ":775},{"
    group_create_time ":0,"
    group_id ":1124408627,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"水瓶座松攒","
    max_member_count ":2000,"
    member_count ":1946},{"
    group_create_time ":0,"
    group_id ":1128065520,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"魔法士宋攒","
    max_member_count ":2000,"
    member_count ":1950},{"
    group_create_time ":0,"
    group_id ":1142610438,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"水瓶座颂贊","
    max_member_count ":2000,"
    member_count ":1976},{"
    group_create_time ":0,"
    group_id ":1142911349,"
    group_level ":0,"
    group_memo ":"管理员矛盾由高级管理@敢敢调解管理员级别普通管理——资深固定管理——高级固定管理——副群主","
    group_name ":"中原无敌共和国","
    max_member_count ":1000,"
    member_count ":737},{"
    group_create_time ":0,"
    group_id ":1149678856,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"快手涨粉免费群（官方）","
    max_member_count ":200,"
    member_count ":199},{"
    group_create_time ":0,"
    group_id ":1158964948,"
    group_level ":0,"
    group_memo ":"
    ","
    group_name ":"对方正在输入中……","
    max_member_count ":200,"
    member_count ":11}],"
    retcode ":0,"
    status ":"
    ok "}

**Comment by Ink-33** [comment]
有什么问题吗？我怀疑你在打广告
