### ISSUE TITLE
群消息发送失败: 账号可能被风控

### ISSUE THREAD

**Issue by huangdongqin** [Mrs4s/go-cqhttp#958]
* 环境信息

go-cqhttp版本: devel(master编译)
运行环境: docker
连接方式: ws
使用协议: http

* bug内容
ws发送send_group_msg, 试了几个qq都直接报 群消息发送失败: 账号可能被风控

* 复现方法
1.直接发送文本消息abcd到qq群

**Comment by Mrs4s** [comment]
账号可能被风控

**Comment by huangdongqin** [comment]
> 账号可能被风控

不太可能，我用mirai的都可以发送，两个都是老号

**Comment by liyk123** [comment]
我这里也遇到了这个问题，部分消息被风控，目前yobot的大部分消息都被风控了，除了日历信息，hoshinobot的大部分消息都还是可以的，但是像rss插件的rss list被风控了，日历图片也被风控了，同样的内容手动发是可以的。现在force-fragment 启用之前基本上什么都发不出来，昨天还是一切正常的。

**Comment by saucer-man** [comment]
> 我这里也遇到了这个问题，部分消息被风控，目前yobot的大部分消息都被风控了，除了日历信息，hoshinobot的大部分消息都还是可以的，但是像rss插件的rss list被风控了，日历图片也被风控了，同样的内容手动发是可以的。现在force-fragment 启用之前基本上什么都发不出来，昨天还是一切正常的。今天刚申请的新号也是有问题的。

所以现在还有什么好用的吗，我也遇到了风控的问题

**Comment by nymanyim** [comment]
群消息风控，私聊正常解决方法：添加设备锁，验证登陆后正常接收消息

**Comment by liyk123** [comment]
我是挂了三天自动解除了，刚才用手机登陆加了设备锁，又被风控了。。。大概因为我登陆的IP是香港的？被判定异地登陆？

**Comment by liyk123** [comment]
刚才实验的方法,如果发现被风控,在启用设备锁的前提下,可按以下步骤解除,:

1. 停止gocqhttp
2. 删除gocqhttp_data下的device.json
3. 在手机上登陆qq删除mirai设备登陆信息 
4. 确保配置文件中qq密码为空
5. 启动gocqhttp,进行扫码登陆验证

**Comment by nymanyim** [comment]
风控解除最终版：开启设备锁，删除session.token，切换安卓协议，填写密码登陆。正常！！

**Comment by liyk123** [comment]
今天最近又出现风控。。。改协议换设备还是不行，账号还被冻结了一次

**Comment by HOLLYwyh** [comment]
我这边在手机上给Bot的QQ添加了设备锁就好了

**Comment by allofee** [comment]
> 风控解除最终版：开启设备锁，删除session.token，切换安卓协议，填写密码登陆。正常！！

有效！

**Comment by Minephliss** [comment]
> 风控解除最终版：开启设备锁，删除session.token，切换安卓协议，填写密码登陆。正常！！

有效有效，感谢

**Comment by 66Leo66** [comment]
> 风控解除最终版：开启设备锁，删除session.token，切换安卓协议，填写密码登陆。正常！！

有效有效，感谢！

**Comment by Ice-cream1024** [comment]
> 风控解除最终版：开启设备锁，删除session.token，切换安卓协议，填写密码登陆。正常！！

解决了！感谢！

**Comment by huang122124** [comment]
> 风控解除最终版：开启设备锁，删除session.token，切换安卓协议，填写密码登陆。正常！！

牛逼！解决了!

**Comment by Am2333** [comment]
> > 风控解除最终版：开启设备锁，删除session.token，切换安卓协议，填写密码登陆。正常！！
> 
> 有效！

怎么切换安卓协议的？

**Comment by ChinaBuleSky** [comment]
> 

device.json文件里把protocol改成1

**Comment by PoweredSnow** [comment]
另一个解决办法：自己在手机QQ上登陆机器人账号并像群内发送消息，会提示账号因……而被风控，后面有个蓝链可以点进去，然后按照提示输入验证码，就可以正常发送群消息了。

**Comment by milknights** [comment]
> 我们在您的 Issue 中发现了如下问题：
> * 没有在问题描述中找到对应复现方法。清晰明了的复现方法有助于快速定位问题。请尝试复现并补全复现方法。
> 
> 请参照 [相关教程](https://github.com/Mrs4s/go-cqhttp/issues/633) 按照上述要求对 Issue 进行修改。

这个相关教程有链接吗？我打开来404呀，我看都说要开启设备锁+安卓协议+配置里填密码，不太懂要怎么操作

**Comment by liyk123** [comment]
> 

已经过期了，最新的解决方案看最新的release

**Comment by liyk123** [comment]
> > 我们在您的 Issue 中发现了如下问题：
> > 
> > * 没有在问题描述中找到对应复现方法。清晰明了的复现方法有助于快速定位问题。请尝试复现并补全复现方法。
> > 
> > 请参照 [相关教程](https://github.com/Mrs4s/go-cqhttp/issues/633) 按照上述要求对 Issue 进行修改。
> 
> 这个相关教程有链接吗？我打开来404呀，我看都说要开启设备锁+安卓协议+配置里填密码，不太懂要怎么操作

已经过期了，最新的解决方案看最新的release

**Comment by milknights** [comment]
> 3\. mirai

你好可以问问release在哪里呀，我把https://github.com/lss233/chatgpt-mirai-qq-bot/releases 翻了个底朝天也没有看到，感谢您能回答

**Comment by liyk123** [comment]
> > 3. mirai
> 
> 你好可以问问release在哪里呀，我把https://github.com/lss233/chatgpt-mirai-qq-bot/releases 翻了个底朝天也没有看到，感谢您能回答

https://github.com/Mrs4s/go-cqhttp/releases
