### ISSUE TITLE
CQ码发送图片异常

### ISSUE THREAD

**Issue by lliioollcn** [Mrs4s/go-cqhttp#961]
**环境信息**

go-cqhttp版本: v1.0.0-beta4
运行环境: win10 x64
连接方式: 反向websocket
使用协议: iPad
**bug内容**

在ws调用私聊消息发送时,cq码会报错
调用内容:
`{"action":"send_private_msg","params":{"user_id":3483706632,"auto_escape":false,"message":["[CQ:image,file=https://scpic2.chinaz.net/Files/pic/pic9/202107/apic33885_s.jpg,type=show,id=40000]"]},"echo":"npy85YiBijK99T6d3Jtq"}`
提示内容: 
`[2021-07-15 11:23:45] [DEBUG]: WS接收到API调用: send_private_msg 参数: {"user_id":3483706632,"auto_escape":false,"message":["[CQ:image,file=https://scpic2.chinaz.net/Files/pic/pic9/202107/apic33885_s.jpg,type=show,id=40000]"]}
[2021-07-15 11:23:45] [WARNING]: 转换CQ码 ("[CQ:image,file=https://scpic2.chinaz.net/Files/pic/pic9/202107/apic33885_s.jpg,type=show,id=40000]") 到MiraiGo Element时出现错误: unsupported cq code:  将忽略本段CQ码.
[2021-07-15 11:23:45] [WARNING]: 好友消息发送失败: 消息为空.`
**复现方法**

向go-http发送调用内容(反向websocket)

**Comment by Yiwen-Chan** [comment]
使用CQ码时请不要用json数组

**Comment by lliioollcn** [comment]
> 
> 
> 使用CQ码时请不要用json数组

请问下，当使用{"data":{"file":"https://img2.baidu.com/it/u=2102736929,2417598652&fm=26&fmt=auto&gp=0.jpg","type":"show","url":"https://img2.baidu.com/it/u=2102736929,2417598652&fm=26&fmt=auto&gp=0.jpg","cache":1,"id":40000,"c":1},"type":"image"}作为数组内容时，他会当做cqcode解析

**Comment by Yiwen-Chan** [comment]
> 请问下，当使用{"data":{"file":"[https://img2.baidu.com/it/u=2102736929,2417598652&fm=26&fmt=auto&gp=0.jpg","type":"show","url":"https://img2.baidu.com/it/u=2102736929,2417598652&fm=26&fmt=auto&gp=0.jpg","cache":1,"id":40000,"c":1},"type":"image"}作为数组内容时，他会当做cqcode解析](https://img2.baidu.com/it/u=2102736929,2417598652&fm=26&fmt=auto&gp=0.jpg%22,%22type%22:%22show%22,%22url%22:%22https://img2.baidu.com/it/u=2102736929,2417598652&fm=26&fmt=auto&gp=0.jpg%22,%22cache%22:1,%22id%22:40000,%22c%22:1%7D,%22type%22:%22image%22%7D%E4%BD%9C%E4%B8%BA%E6%95%B0%E7%BB%84%E5%86%85%E5%AE%B9%E6%97%B6%EF%BC%8C%E4%BB%96%E4%BC%9A%E5%BD%93%E5%81%9Acqcode%E8%A7%A3%E6%9E%90)

字段错误，请仔细阅读 OneBot 文档

**Comment by lliioollcn** [comment]
> 
> 
> > 请问下，当使用{"data":{"file":"[https://img2.baidu.com/it/u=2102736929,2417598652&fm=26&fmt=auto&gp=0.jpg","type":"show","url":"https://img2.baidu.com/it/u=2102736929,2417598652&fm=26&fmt=auto&gp=0.jpg","cache":1,"id":40000,"c":1},"type":"image"}作为数组内容时，他会当做cqcode解析](https://img2.baidu.com/it/u=2102736929,2417598652&fm=26&fmt=auto&gp=0.jpg%22,%22type%22:%22show%22,%22url%22:%22https://img2.baidu.com/it/u=2102736929,2417598652&fm=26&fmt=auto&gp=0.jpg%22,%22cache%22:1,%22id%22:40000,%22c%22:1%7D,%22type%22:%22image%22%7D%E4%BD%9C%E4%B8%BA%E6%95%B0%E7%BB%84%E5%86%85%E5%AE%B9%E6%97%B6%EF%BC%8C%E4%BB%96%E4%BC%9A%E5%BD%93%E5%81%9Acqcode%E8%A7%A3%E6%9E%90)
> 
> 字段错误，请仔细阅读 OneBot 文档

好的，感谢

**Comment by lliioollcn** [comment]
> 
> 
> > 请问下，当使用{"data":{"file":"[https://img2.baidu.com/it/u=2102736929,2417598652&fm=26&fmt=auto&gp=0.jpg","type":"show","url":"https://img2.baidu.com/it/u=2102736929,2417598652&fm=26&fmt=auto&gp=0.jpg","cache":1,"id":40000,"c":1},"type":"image"}作为数组内容时，他会当做cqcode解析](https://img2.baidu.com/it/u=2102736929,2417598652&fm=26&fmt=auto&gp=0.jpg%22,%22type%22:%22show%22,%22url%22:%22https://img2.baidu.com/it/u=2102736929,2417598652&fm=26&fmt=auto&gp=0.jpg%22,%22cache%22:1,%22id%22:40000,%22c%22:1%7D,%22type%22:%22image%22%7D%E4%BD%9C%E4%B8%BA%E6%95%B0%E7%BB%84%E5%86%85%E5%AE%B9%E6%97%B6%EF%BC%8C%E4%BB%96%E4%BC%9A%E5%BD%93%E5%81%9Acqcode%E8%A7%A3%E6%9E%90)
> 
> 字段错误，请仔细阅读 OneBot 文档

字段正确后仍然显示发送失败...
![图片](https://user-images.githubusercontent.com/44719954/125725638-419aabf0-b5cb-4f01-91af-f4ca5650c996.png)

**Comment by Yiwen-Chan** [comment]
> 字段正确后仍然显示发送失败...
> ![图片](https://user-images.githubusercontent.com/44719954/125725638-419aabf0-b5cb-4f01-91af-f4ca5650c996.png)

https://github.com/Mrs4s/go-cqhttp/issues/914

**Comment by lliioollcn** [comment]
> 
> 
> > 字段正确后仍然显示发送失败...
> > ![图片](https://user-images.githubusercontent.com/44719954/125725638-419aabf0-b5cb-4f01-91af-f4ca5650c996.png)
> 
> #914

好的，感谢
