### ISSUE TITLE
conf.Message.markAsRead配置无效

### ISSUE THREAD

**Issue by langren1353** [Mrs4s/go-cqhttp#965]
**环境信息**

go-cqhttp版本: v1.0.0-beta4
运行环境: Linux x64
连接方式: bin
使用协议: iPad

**bug内容**
在yaml中配置conf.Message.mark-as-read参数无效
经查代码：go-cqhttp/coolq/bot.go:53 有使用conf.Message.MarkAsRead
但是对应的Message类没有这个配置：go-cqhttp/global/config/config.go:47
导致该参数配置无效，同时未在default文档以及其他文档中看到该配置的使用，建议更新一下具体内容

**复现方法**
持续复现

**Comment by Ink-33** [comment]
你查的是#903都代码吧，还没合呢...

**Comment by langren1353** [comment]
是#902和#903的
目前release  v1.0.0-beta4 上默认消息全部已读了，我主账号消息全被自动mark了，不得已退回了beta3

**Comment by Mrs4s** [comment]
考虑吧 `markAsRead` 做成一个 `api` 而不是一个被动功能.
