### ISSUE TITLE
无法发送语音

### ISSUE THREAD

**Issue by qbldx** [Mrs4s/go-cqhttp#972]
**环境信息**

go-cqhttp版本: dev 最新（截止目前）
运行环境: Windows amd64
连接方式: 反向ws
使用协议: iPad

**bug内容**
无法发送语音，CQ码填写正确，执行发送请求后收到的为纯文本信息
![图片](https://user-images.githubusercontent.com/53810658/127761580-87782d24-2921-42e0-b6ab-47a6de771223.png)

**复现方法**
 执行get请求http://127.0.0.1:5700/send_msg?group_id=xxx&message=[CQ:record,file=http://xxx.com/1.mp3]关键部分已打码

**Comment by Ink-33** [comment]
请提供gocq日志
我盲猜你没装ffmpeg

**Comment by qbldx** [comment]
[2021-08-01.log](https://github.com/Mrs4s/go-cqhttp/files/6912235/2021-08-01.log)
确实没装
