### ISSUE TITLE
无法发送语音

### ISSUE THREAD

**Issue by qbldx** [Mrs4s/go-cqhttp#973]
**环境信息**

环境信息

go-cqhttp版本: dev 最新（截止目前）
运行环境: Windows amd64
连接方式: 反向ws
使用协议: iPad

bug内容
无法发送语音，CQ码填写正确，执行发送请求后收到的为纯文本信息
已经安装ffmpeg，出现‘’转换CQ码 ({"type":"record","data":{"file":"https:\/\/dl.tareotas.com\/aw.mp3"}}) 到MiraiGo Element时出现错误: encode silk failed: convert pcm file error: exec: "ffmpeg": executable file not found in %PATH% 将忽略本段CQ码.‘’
log
[2021-08-01.log](https://github.com/Mrs4s/go-cqhttp/files/6912242/2021-08-01.log)

![图片](https://user-images.githubusercontent.com/53810658/127761887-35cbb768-5903-4c7a-b078-b23d9f8af8db.png)

复现方法
执行get请求http://127.0.0.1:5700/send_msg?group_id=xxx&message=[CQ:record,file=http://xxx.com/1.mp3]关键部分已打码

**Comment by wdvxdr1123** [comment]
请安装ffmpeg

**Comment by qbldx** [comment]
> 
> 
> 请安装ffmpeg

安装过了

**Comment by qbldx** [comment]
> 
> 
> 请安装ffmpeg

还是发不了

**Comment by sam01101** [comment]
> > 请安装ffmpeg
> 
> 还是发不了

打开 `cmd` 输入 `ffmpeg` 是否会获得以下画面?
![image](https://user-images.githubusercontent.com/25792361/127766764-a05d35b3-a478-4b18-90ec-fdc51d27b462.png)

**Comment by qbldx** [comment]
> 
> 
> > > 请安装ffmpeg
> > 
> > 
> > 还是发不了
> 
> 打开 `cmd` 输入 `ffmpeg` 是否会获得以下画面?
> ![image](https://user-images.githubusercontent.com/25792361/127766764-a05d35b3-a478-4b18-90ec-fdc51d27b462.png)

已经好了，安装ffmpeg后仍需要重启电脑，感谢解答
