### ISSUE TITLE
arm版无法发送语音

### ISSUE THREAD

**Issue by ldeus** [Mrs4s/go-cqhttp#974]
**环境信息**

go-cqhttp版本: dev action arm64
运行环境: Linux version 5.0.2-aml-s905 (root@vbox) (gcc version 7.3.1 20180425 [linaro-7.3-2018.05 revision d29120a424ecfbc167ef90065c0eeb7f91977701] (Linaro GCC 7.3-2018.05)) #5.77 SMP PREEMPT Mon Apr 1 17:23:16 MSK 2019
连接方式: ws-reverse
使用协议: ipad

**bug内容**

ffmpeg确认已安装：root@aml:~# ffmpeg -version
ffmpeg version N-58069-gc253b180cb-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 8 (Debian 8.3.0-6)
无法发送语音('[CQ:record,file=https://xx.com/aw.mp3]')
debug信息
[2021-07-10 19:27:22] [DEBUG]: Protocol -> rev pkt: PbMessageSvc.PbMsgReadedReport seq: 14519
[2021-07-10 19:27:22] [DEBUG]: WSAPCQ ({"type": "record", "data": {"file": "https://xx.com/aw.mp3"}}) MiraiGo Element误: encode silk failed: convert pcm file error: exit status 1 忽段CQ.
[2021-07-10 19:27:22] [WARNING]: 好失败: 为空
**复现方法**

在action构建的arm版本中使用ffmpeg官方提供的Linux Static Builds
32-bit and 64-bit for kernel 3.2.0 and above发送语音会失败

**Comment by ldeus** [comment]
大概知道原因了，linux上跑着cqhttp，并且安装了ffmpeg；但是ws的对端是在win上的nonebot。应该在win上安装ffmpeg？？？

**Comment by Yiwen-Chan** [comment]
在linux上装没错

**Comment by sam01101** [comment]
> 大概知道原因了，linux上跑着cqhttp，并且安装了ffmpeg；但是ws的对端是在win上的nonebot。应该在win上安装ffmpeg？？？

你MP3能不能读取

**Comment by ldeus** [comment]
> > 大概知道原因了，linux上跑着cqhttp，并且安装了ffmpeg；但是ws的对端是在win上的nonebot。应该在win上安装ffmpeg？？？
> 
> 你MP3能不能读取

可以啊，难不成是代理的原因？

**Comment by sam01101** [comment]
> > > 大概知道原因了，linux上跑着cqhttp，并且安装了ffmpeg；但是ws的对端是在win上的nonebot。应该在win上安装ffmpeg？？？
> > 
> > 
> > 你MP3能不能读取
> 
> 可以啊，难不成是代理的原因？

`encode silk failed: convert pcm file error: exit status 1`

ffmpeg 转换失败, 我建议你试一试手动转一下 mp3 文件试一试

指令: `ffmpeg -i <mp3文件> -f s16le -c:a pcm_s16le -ar 48000 -ac 2 out.raw`

试一试

**Comment by ldeus** [comment]
> > > > 大概知道原因了，linux上跑着cqhttp，并且安装了ffmpeg；但是ws的对端是在win上的nonebot。应该在win上安装ffmpeg？？？
> > > 
> > > 
> > > 你MP3能不能读取
> > 
> > 
> > 可以啊，难不成是代理的原因？
> 
> `encode silk failed: convert pcm file error: exit status 1`
> 
> ffmpeg 转换失败, 我建议你试一试手动转一下 mp3 文件测试
> 
> 指令: `ffmpeg -i <mp3文件> -f s16le -c:a pcm_s16le -ar 48000 -ac 2 out.raw`
> 
> 试一试

![image](https://user-images.githubusercontent.com/48109470/127773754-9a85d5a9-8f38-4379-ab6d-05d00f48b042.png)

**Comment by sam01101** [comment]
> > > > > 大概知道原因了，linux上跑着cqhttp，并且安装了ffmpeg；但是ws的对端是在win上的nonebot。应该在win上安装ffmpeg？？？
> > > > 
> > > > 
> > > > 你MP3能不能读取
> > > 
> > > 
> > > 可以啊，难不成是代理的原因？
> > 
> > 
> > `encode silk failed: convert pcm file error: exit status 1`
> > ffmpeg 转换失败, 我建议你试一试手动转一下 mp3 文件测试
> > 指令: `ffmpeg -i <mp3文件> -f s16le -c:a pcm_s16le -ar 48000 -ac 2 out.raw`
> > 试一试
> 
> ![image](https://user-images.githubusercontent.com/48109470/127773754-9a85d5a9-8f38-4379-ab6d-05d00f48b042.png)

奇怪, 那么你的 mp3 音频可以在 Linux 系统上面获取到吗?

**Comment by ldeus** [comment]
![image](https://user-images.githubusercontent.com/48109470/127774384-03b094ac-fb9c-42f3-a184-12df3731aa3d.png)
这样？
![image](https://user-images.githubusercontent.com/48109470/127774436-9984bfd8-77e0-4a1f-abab-4dc1a0b647ff.png)

**Comment by sam01101** [comment]
这个问题我也不清楚, 可能要求救其他人了

/cc @Yiwen-Chan @wfjsw

**Comment by ldeus** [comment]
删除数据文件重新打开好了，可以正常发送语音了。谢谢了！
