### ISSUE TITLE
send_group_forward_msg api无法使用？

### ISSUE THREAD

**Issue by l1nfp** [Mrs4s/go-cqhttp#977]
**环境信息**

go-cqhttp版本: v1.0.0-beta5
运行环境: windows 10
连接方式: http post
使用协议: ipad

**bug内容**

我参考了以下文档内容
![image](https://user-images.githubusercontent.com/55312093/127855248-66a06e60-2c11-4008-bc8c-950974de298c.png)
![image](https://user-images.githubusercontent.com/55312093/127855292-057c2e78-f9c4-4358-bd39-5d2fe9a82a46.png)
调用api方式如下（group_id等信息已经被我修改为虚构）
![image](https://user-images.githubusercontent.com/55312093/127855451-9da610d8-6f9a-40a7-bc80-9bccd2c07858.png)
调用结果一直是fail，并且go-cqhttp也没有给出任何异常信息。
![image](https://user-images.githubusercontent.com/55312093/127855528-96db33f3-5bfd-4eb8-98fa-6d66b8fe386d.png)
我认为可能是我调用方式出了问题或是api无法使用，期待能得到解答。

**复现方法**

持续复现

**Comment by wdvxdr1123** [comment]
请参考:
https://github.com/Mrs4s/go-cqhttp/blob/master/docs/cqhttp.md#%E5%8F%91%E9%80%81%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91%E7%BE%A4

https://github.com/Mrs4s/go-cqhttp/blob/master/docs/cqhttp.md#%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91%E6%B6%88%E6%81%AF%E8%8A%82%E7%82%B9

**Comment by sam01101** [comment]
用错方法，用 POST 进行请求
而且使用 body， 以 json 格式进行发送
具体参考 CQ码的例子

**Comment by l1nfp** [comment]
> 用错方法，用 POST 进行请求
> 而且使用 body， 以 json 格式进行发送
> 具体参考 CQ码的例子

感谢回复，使用post传递参数后可以使用了。
我想知道就用get传递参数可以吗？（因为发现别的api基本都可以使用get传递参数）

**Comment by sam01101** [comment]
> > 用错方法，用 POST 进行请求
> > 而且使用 body， 以 json 格式进行发送
> > 具体参考 CQ码的例子
> 
> @sam01101 感谢回复，使用post传递参数后可以使用了。
> 我想知道就用get传递参数可以吗？（因为发现别的api基本都可以使用get传递参数）

其实是字符没escape导致的
