### ISSUE TITLE
私聊不支持合并消息吗?CQ码说已经实现,然后私聊不支持 

### ISSUE THREAD

**Issue by qwe0099001** [Mrs4s/go-cqhttp#979]
**环境信息**

go-cqhttp版本: v1.0.0-beta5
运行环境: windows 10
连接方式: http post
使用协议: ipad

**bug内容**

私聊发送合并消息,提示unsupported cq code: node 将忽略.
但但文档是已经实现[CQ:node]的
**复现方法**

私聊发送[CQ:node,user_id=10001000,nickname=某人,content=[CQ:face,id=123]哈喽～]

**Comment by qwe0099001** [comment]
另外大佬有计划提供私聊发送合并消息的API不

**Comment by sam01101** [comment]
对，私聊就是现在不支持合并消息

你如果要解决方法也很简单，开一个空的群，发送合并消息
然后把返回的信息转发到私聊就可以了

**Comment by qwe0099001** [comment]
> 对，私聊就是现在不支持合并消息
> 
> 你如果要解决方法也很简单，开一个空的群，发送合并消息
> 然后把返回的信息转发到私聊就可以了

有想过这种办法,曲线救国,感觉有点蛋疼= =
谢谢大佬解答

**Comment by sam01101** [comment]
> > 对，私聊就是现在不支持合并消息
> > 你如果要解决方法也很简单，开一个空的群，发送合并消息
> > 然后把返回的信息转发到私聊就可以了
> 
> 有想过这种办法,曲线救国,感觉有点蛋疼= =
> 谢谢大佬解答

还有另外一种鬼畜的方法解决，这里要改程序就不说了

**Comment by qwe0099001** [comment]
> > > 对，私聊就是现在不支持合并消息
> > > 你如果要解决方法也很简单，开一个空的群，发送合并消息
> > > 然后把返回的信息转发到私聊就可以了
> > 
> > 
> > 有想过这种办法,曲线救国,感觉有点蛋疼= =
> > 谢谢大佬解答
> 
> 还有另外一种鬼畜的方法解决，这里要改程序就不说了

太高端了,说了也学不会
仰望大佬

**Comment by xsjk** [comment]
> > 对，私聊就是现在不支持合并消息
> > 你如果要解决方法也很简单，开一个空的群，发送合并消息
> > 然后把返回的信息转发到私聊就可以了
> 
> 有想过这种办法,曲线救国,感觉有点蛋疼= = 谢谢大佬解答

请问这里所说的"把返回的信息转发到私聊"是给私聊发这种消息吗
我这样试了，先把合并聊天记录发到一个群，获取得到[CQ:forward,id=xxxx]，然后把这个原封不动地发给私聊，然而私聊收到的合并聊天记录里面的图片加载不出来。
但是神奇的是，如果私聊把这段收到合并聊天记录整个转发回给bot，那里面的图片旧能加载出来了，想请教一下原因。

go-cqhttp版本: v1.0.0-rc1
运行环境: windows 10
连接方式: 反向WS
使用协议: ipad
