### ISSUE TITLE
无法接收单向好友（陌生人）消息

### ISSUE THREAD

**Issue by Tsuk1ko** [Mrs4s/go-cqhttp#98]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.18
运行环境: windows_amd64
连接方式: any

**bug内容**
无法接收单向好友（陌生人）消息

**复现方法**
1. 机器人QQ设置允许任何人添加好友
2. 把机器人加为好友，此时机器人在我的好友里，而我在机器人的陌生人里
3. 向机器人发送消息，go-cqhttp 日志没有显示收到消息

**Comment by Tsuk1ko** [comment]
是不会支持么 #26

**Comment by Mrs4s** [comment]
是bug，在后续版本会处理的

**Comment by Tsuk1ko** [comment]
😂好的，差点以为打扰了

**Comment by wordgao** [comment]
反馈的很多问题都得不到解决，我现在都不反馈了，还是去用java的扩展包去了。

**Comment by Mrs4s** [comment]
> 反馈的很多问题都得不到解决，我现在都不反馈了，还是去用java的扩展包去了。

> 请注意, 开发者并没有义务回复您的问题. 您应该具备基本的提问技巧。
您提出了多个不规范的问题，并不能帮助开发者定位BUG，所以我Close了
这并不是商业项目，开发者都是在业余的时间维护，如果需要技术支持请使用商业项目

**Comment by wordgao** [comment]
感谢您的反馈。

**Comment by LR1093141031** [comment]
遇到了所有好友发消息都无法在控制台里看到的情况
