### ISSUE TITLE
收到群消息时事件上报的message_type为private

### ISSUE THREAD

**Issue by imyMuyang** [Mrs4s/go-cqhttp#980]
**环境信息**

go-cqhttp版本: windows386 v1.0.0-beta5
运行环境: windows10 x64 1903
连接方式: ws
使用协议: iPad

**bug内容**
收到的事件内容：
{
  anonymous: null,
  font: 0,
  group_id: 58打码31, // 这里有群号
  message: '？',
  message_id: 439522901,
  message_seq: 170672,
  message_type: 'private', // 这里为什么是private？
  post_type: 'message',
  raw_message: '？',
  self_id: 19打码67,
  sender: { // 这里有群消息里专有的sender字段
    age: 0,
    area: '',
    card: '老八',
    level: '',
    nickname: '老八',
    role: 'admin',
    sex: 'unknown',
    title: '',
    user_id: 21打码39
  },
  sub_type: 'normal',
  time: 1627976161,
  user_id: 21打码39
}

**复现方法**
启动程序然后在群内发送信息

**Comment by wdvxdr1123** [comment]
无法复现，需要更多信息
