### ISSUE TITLE
推送event时发生 i/o timeout 

### ISSUE THREAD

**Issue by lclbm** [Mrs4s/go-cqhttp#982]
**环境信息**

go-cqhttp版本: v1.0.0-beta5
运行环境: windows 10 64
连接方式: 反向ws
使用协议: ipad

**bug内容**
在bot发送图片后，小概率会出现下面的WARNING，之后bot又会快速重连。
```
[WARNING]: 向WS服务器 127.0.0.1:5800 推送Event时出现错误: write tcp 127.0.0.1:54020->127.0.0.1:5800: i/o timeout 
[WARNING]: 监听反向WS API时出现错误: read tcp 127.0.0.1:54020->127.0.0.1:5800: use of closed network connection
```
nonebot2也会报错
`
RuntimeError: Unexpected ASGI message 'websocket.send', after sending 'websocket.close'.
`

**复现方法**
使用gocq向群内发送图片。
图片的大小在500KB~2MB之间。

**Comment by Mrs4s** [comment]
这个是与应用的连接问题, 服务端暂时没办法处理
