### ISSUE TITLE
在部分网络环境下无法上传媒体资源

### ISSUE THREAD

**Issue by YiwanGi** [Mrs4s/go-cqhttp#983]
**环境信息**

go-cqhttp版本: v1.0.0-beta4
运行环境: windows 2012
连接方式: 反向ws
使用协议: ipad

**bug内容**
北京的机子 部分机器人正常 该情况出现在部分机器人上
![image](https://user-images.githubusercontent.com/69124377/128135453-40f00d7f-212b-4152-9d9d-90ac6262be19.png)
![image](https://user-images.githubusercontent.com/69124377/128135492-092cac10-7b34-4730-85c8-2662345501d5.png)

**复现方法**
持续出现

**Comment by YiwanGi** [comment]
目前换区域登录后正常发送 
出问题区域：阿里云·华北2（北京）

**Comment by xzsk2** [comment]
同样的问题，阿里云北京机子，无法发送图片，日志出现过`175.27.12.205`及`182.254.58.220`两个ip，手动ping了一下丢包率90%，延迟10ms以下。本地部署无问题，可能是阿里云北京到qq图片服务器的连接出现了问题？

```
[2021-08-04 10:50:58] [WARNING]: 警告: 私聊 ***** 消息图片上传失败: upload failed: write conn error: write tcp ***:45500->182.254.58.220:443: write: connection reset by peer 
[2021-08-04 10:50:58] [WARNING]: 好友消息发送失败: 消息为空.
```

**Comment by SK-415** [comment]
我群里也收到两位群友反馈了相同问题，经确认均为北京阿里云。

经过测试，使用 URL 和本地文件的方式发送图片正常，只有在 base64 的时候会出现这个情况。

**Comment by howrain** [comment]
同样的问题，华北2（北京）阿里云，只有在使用base64发送时会出现。丢包率超过90%
[2021-08-05 16:52:16] [WARNING]: 警告: 群 **** 消息图片上传失败: upload failed: connect error: dial tcp 182.254.63.105:80: i/o timeout

**Comment by ReiKohaku** [comment]
我也遇到了相同的问题。
版本：1.0.0-beta5/0.9.40-fix5
环境：阿里云 北京 轻量应用服务器 1C2G
报错与上方issue所述相同，即长消息无法发送且图片无法上传超时。
目前我已经通过**把软件迁移到其它地域服务器**的方式解决了该问题。

**Comment by Mas0ra** [comment]
同样的问题，图片和语音都上传失败，目前只有阿里云北京的机子，不知道有什么解决办法

**Comment by Mrs4s** [comment]
得等我找到一个会丢包的服务器测试一下到底怎么回事再看看

**Comment by corvo007** [comment]
我的服务器也是阿里云华北2（北京），也遇到了一模一样的问题

**Comment by corvo007** [comment]
昨天我阿里云上发了工单，就关于访问这几个ip超时的问题，那边的工程师是这么说的：
![image](https://user-images.githubusercontent.com/67192165/128624849-eab68d48-e25f-433b-8a9d-30963af55abc.png)
访问其中一个ip的traceroute是这样的：
![image](https://user-images.githubusercontent.com/67192165/128624887-8fb2147a-3c81-4463-ac4f-d0ed93587fba.png)
然后还提到连接时被reset，希望能有帮助。

**Comment by Mrs4s** [comment]
> 昨天我阿里云上发了工单，就关于访问这几个ip超时的问题，那边的工程师是这么说的：
> ![image](https://user-images.githubusercontent.com/67192165/128624849-eab68d48-e25f-433b-8a9d-30963af55abc.png)
> 访问其中一个ip的traceroute是这样的：
> ![image](https://user-images.githubusercontent.com/67192165/128624887-8fb2147a-3c81-4463-ac4f-d0ed93587fba.png)
> 然后还提到连接时被reset，希望能有帮助。

请问使用的产品是轻量云还是ECS 我这边需要自己开个环境测试下

**Comment by corvo007** [comment]
> > 昨天我阿里云上发了工单，就关于访问这几个ip超时的问题，那边的工程师是这么说的：
> > ![image](https://user-images.githubusercontent.com/67192165/128624849-eab68d48-e25f-433b-8a9d-30963af55abc.png)
> > 访问其中一个ip的traceroute是这样的：
> > ![image](https://user-images.githubusercontent.com/67192165/128624887-8fb2147a-3c81-4463-ac4f-d0ed93587fba.png)
> > 然后还提到连接时被reset，希望能有帮助。
> 
> 请问使用的产品是轻量云还是ECS 我这边需要自己开个环境测试下

ECS

**Comment by xzsk2** [comment]
> > 昨天我阿里云上发了工单，就关于访问这几个ip超时的问题，那边的工程师是这么说的：
> > ![image](https://user-images.githubusercontent.com/67192165/128624849-eab68d48-e25f-433b-8a9d-30963af55abc.png)
> > 访问其中一个ip的traceroute是这样的：
> > ![image](https://user-images.githubusercontent.com/67192165/128624887-8fb2147a-3c81-4463-ac4f-d0ed93587fba.png)
> > 然后还提到连接时被reset，希望能有帮助。
> 
> 请问使用的产品是轻量云还是ECS 我这边需要自己开个环境测试下

我这里是轻量云北京

**Comment by Mrs4s** [comment]
> > > 昨天我阿里云上发了工单，就关于访问这几个ip超时的问题，那边的工程师是这么说的：
> > > ![image](https://user-images.githubusercontent.com/67192165/128624849-eab68d48-e25f-433b-8a9d-30963af55abc.png)
> > > 访问其中一个ip的traceroute是这样的：
> > > ![image](https://user-images.githubusercontent.com/67192165/128624887-8fb2147a-3c81-4463-ac4f-d0ed93587fba.png)
> > > 然后还提到连接时被reset，希望能有帮助。
> > 
> > 
> > 请问使用的产品是轻量云还是ECS 我这边需要自己开个环境测试下
> 
> ECS

我这边试了下ECS北京可用区H 没发现丢包的情况, 请问你这边是使用哪个可用区的

**Comment by ssz66666** [comment]
> > > > 昨天我阿里云上发了工单，就关于访问这几个ip超时的问题，那边的工程师是这么说的：
> > > > ![image](https://user-images.githubusercontent.com/67192165/128624849-eab68d48-e25f-433b-8a9d-30963af55abc.png)
> > > > 访问其中一个ip的traceroute是这样的：
> > > > ![image](https://user-images.githubusercontent.com/67192165/128624887-8fb2147a-3c81-4463-ac4f-d0ed93587fba.png)
> > > > 然后还提到连接时被reset，希望能有帮助。
> > > 
> > > 
> > > 请问使用的产品是轻量云还是ECS 我这边需要自己开个环境测试下
> > 
> > 
> > ECS
> 
> 我这边试了下ECS北京可用区H 没发现丢包的情况, 请问你这边是使用哪个可用区的

华北2（北京）ECS 可用区H，同发现有严重丢包。

**Comment by Mrs4s** [comment]
我这边没开到有问题的机器, 如果谁方便的话希望能私聊一个机器给我测试...

**Comment by YiwanGi** [comment]
> 我这个还没开到有问题的机器，如果谁有空的话希望可以私聊一个机器给我测试...

刚测试 图片语音上传问题均已恢复正常

**Comment by ssz66666** [comment]
北京ECS恢复正常+1

**Comment by corvo007** [comment]
> > > > 昨天我阿里云上发了工单，就关于访问这几个ip超时的问题，那边的工程师是这么说的：
> > > > ![image](https://user-images.githubusercontent.com/67192165/128624849-eab68d48-e25f-433b-8a9d-30963af55abc.png)
> > > > 访问其中一个ip的traceroute是这样的：
> > > > ![image](https://user-images.githubusercontent.com/67192165/128624887-8fb2147a-3c81-4463-ac4f-d0ed93587fba.png)
> > > > 然后还提到连接时被reset，希望能有帮助。
> > > 
> > > 
> > > 请问使用的产品是轻量云还是ECS 我这边需要自己开个环境测试下
> > 
> > 
> > ECS
> 
> 我这边试了下ECS北京可用区H 没发现丢包的情况, 请问你这边是使用哪个可用区的

也许是个别服务器的问题？我服务器同样位于可用区H，丢包的情况目前没有改善。
![image](https://user-images.githubusercontent.com/67192165/128637454-2b1bbf7d-b9a5-4350-a441-91c000ba3ba8.png)

**Comment by Mrs4s** [comment]
> > > > > 昨天我阿里云上发了工单，就关于访问这几个ip超时的问题，那边的工程师是这么说的：
> > > > > ![image](https://user-images.githubusercontent.com/67192165/128624849-eab68d48-e25f-433b-8a9d-30963af55abc.png)
> > > > > 访问其中一个ip的traceroute是这样的：
> > > > > ![image](https://user-images.githubusercontent.com/67192165/128624887-8fb2147a-3c81-4463-ac4f-d0ed93587fba.png)
> > > > > 然后还提到连接时被reset，希望能有帮助。
> > > > 
> > > > 
> > > > 请问使用的产品是轻量云还是ECS 我这边需要自己开个环境测试下
> > > 
> > > 
> > > ECS
> > 
> > 
> > 我这边试了下ECS北京可用区H 没发现丢包的情况, 请问你这边是使用哪个可用区的
> 
> 也许是个别服务器的问题？我服务器同样位于可用区H，丢包的情况目前没有改善。
> ![image](https://user-images.githubusercontent.com/67192165/128637454-2b1bbf7d-b9a5-4350-a441-91c000ba3ba8.png)

测试一下图片能不能正常上传, 有可能tx会更新下发的资源服务器地址

**Comment by Ink-33** [comment]
也许Tx正在旁观此issue(x

**Comment by corvo007** [comment]
> > > > > > 昨天我阿里云上发了工单，就关于访问这几个ip超时的问题，那边的工程师是这么说的：
> > > > > > ![image](https://user-images.githubusercontent.com/67192165/128624849-eab68d48-e25f-433b-8a9d-30963af55abc.png)
> > > > > > 访问其中一个ip的traceroute是这样的：
> > > > > > ![image](https://user-images.githubusercontent.com/67192165/128624887-8fb2147a-3c81-4463-ac4f-d0ed93587fba.png)
> > > > > > 然后还提到连接时被reset，希望能有帮助。
> > > > > 
> > > > > 
> > > > > 请问使用的产品是轻量云还是ECS 我这边需要自己开个环境测试下
> > > > 
> > > > 
> > > > ECS
> > > 
> > > 
> > > 我这边试了下ECS北京可用区H 没发现丢包的情况, 请问你这边是使用哪个可用区的
> > 
> > 也许是个别服务器的问题？我服务器同样位于可用区H，丢包的情况目前没有改善。
> > ![image](https://user-images.githubusercontent.com/67192165/128637454-2b1bbf7d-b9a5-4350-a441-91c000ba3ba8.png)
> 
> 测试一下图片能不能正常上传, 有可能tx会更新下发的资源服务器地址

目前也是不能的，还是提示io timeout，broken pipe，connect reset之类的错误

**Comment by Mas0ra** [comment]
阿里云轻量（北京）在刚才重启gocq v0.9.40 fix5后已恢复正常，未重启状态仍为上传time out

**Comment by Mrs4s** [comment]
比较麻烦 回头我在试一下能不能开一个丢包的环境

**Comment by xzsk2** [comment]
`175.27.12.205`及`182.254.58.220`依然丢包，但是能正常发送图片了，可能tx确实更新了下发的服务器ip

**Comment by corvo007** [comment]
今早重启后测试，发现已经可以正常发送图片
