### ISSUE TITLE
发送语音时出现[WARNING]: 转换CQ码 ({"type":"record","data":{"file":"http s:\/\/xxx.com\/xx.mp3"}}) 到MiraiGo Element时出现错误: encode silk fa iled: convert pcm file error: exit status 1 将忽略本段CQ码.

### ISSUE THREAD

**Issue by wrnxr233** [Mrs4s/go-cqhttp#988]
**环境信息**

go-cqhttp版本: 
运行环境: 
连接方式: 
使用协议: 

**bug内容**
发送语音时出现[WARNING]: 转换CQ码 ({"type":"record","data":{"file":"http s:\/\/xxx.com\/sblbw.mp3"}}) 到MiraiGo Element时出现错误: encode silk fa iled: convert pcm file error: exit status 1 将忽略本段CQ码.
已经尝试手动转换，结果为成功
已经确保系统能获取到mp3文件
![图片](https://user-images.githubusercontent.com/53810658/128284615-537279cf-1652-4544-9312-f631367e9368.png)

系统环境：
OS:Windows7SP1旗舰版 64位
CPU:Intel Atom D2550
RAM:2GB
GOCQ版本：beta5

**复现方法**
1.写插件（已确认插件编写无误）
2.放入插件文件夹
3.重启gocq以及nonebot
4.尝试发送语音

**Comment by qbldx** [comment]
忘了个py版本Python3.8.9

**Comment by wdvxdr1123** [comment]
能否提供一下对应的音频文件

**Comment by qbldx** [comment]
可以，dl.tareotas.com/sblbw.mp3

**Comment by qbldx** [comment]
换了Windowsserver2012R2 ，Python3.9.8也是这样

**Comment by qbldx** [comment]
发现问题之后我又在自己电脑测试 发现在自己电脑没问题 ，在另外一台机器就不行
电脑运行环境：
Windows11 22000.100
python3.9.8

**Comment by wdvxdr1123** [comment]
请使用版本  https://github.com/Mrs4s/go-cqhttp/actions/runs/1107177268
并开启Debug，可以查看ffmpeg的输出

我这边无法复现，可能和ffmpeg的版本有关

**Comment by qbldx** [comment]
试了一下，现在又好了，真奇怪，以后再复现时候再说吧，FFmpeg用的是文档里给的

**Comment by SlightDust** [comment]
是这样，我刚刚也遇到了同样的问题，后来发现是我不熟悉screen软件导致的。系统centos7.6，ffmpeg4.1，gocq1.0.0-beta6。我的gocq运行在screen里，在screen外装好ffmpeg并配置生效，测试没问题后进入screen重启gocq，发现还是报错。结束运行gocq后在screen内执行`ffmpeg -version`提示找不到，后来在screen内重新`source /etc/profile`应用配置后再运行gocq，没有报错，语音可以正常发送。

或许楼主也是ffmpeg配置没生效？

**Comment by wrnxr233** [comment]
> 是这样，我刚刚也遇到了同样的问题，后来发现是我不熟悉screen软件导致的。系统centos7.6，ffmpeg4.1，gocq1.0.0-beta6。我的gocq运行在screen里，在screen外装好ffmpeg并配置生效，测试没问题后进入screen重启gocq，发现还是报错。结束运行gocq后在screen内执行`ffmpeg -version`提示找不到，后来在screen内重新`source /etc/profile`应用配置后再运行gocq，没有报错，语音可以正常发送。
> 
> 或许楼主也是ffmpeg配置没生效？

emm，也许是，但我是在实体机挂的没用screen

**Comment by romanticfire** [comment]
我也遇到了类似的问题,是发送图片出问题,ffmpeg在screen里面可以,后来看log发现时区不对,把时区改过来貌似就没问题了(

**Comment by Warrior-li** [comment]
> 我也遇到了类似的问题,是发送图片出问题,ffmpeg在screen里面可以,后来看log发现时区不对,把时区改过来貌似就没问题了(

请问是在哪里看，我原来就是中国北京的时间

**Comment by qjksxy** [comment]
就是ffmpeg的问题。我重启了一下服务器，就解决了
