### ISSUE TITLE
运行更新后无法启动

### ISSUE THREAD

**Issue by LIERTTTTTT** [Mrs4s/go-cqhttp#989]
root@TEST:~/go-cqhttp# ./go-cqhttp
./go-cqhttp:行7: 未预期的符号“newline”附近有语法错误
./go-cqhttp:行7: `<DOCTYPE html>'

**Comment by LIERTTTTTT** [comment]
root@TEST:~/go-cqhttp# ./go-cqhttp
./go-cqhttp:行1: 未预期的符号“newline”附近有语法错误
./go-cqhttp:行1: `<DOCTYPE html>'

**Comment by wdvxdr1123** [comment]
#874
