### ISSUE TITLE
Session Expired

### ISSUE THREAD

**Issue by xxyy3130** [Mrs4s/go-cqhttp#992]
**环境信息**

go-cqhttp版本: v1.0.0-beta5
运行环境: windows_amd64
连接方式: ws
使用协议: Android Phone

**bug内容**

运行过程中出现
[2021-08-05 15:06:57] [ERROR]: Protocol -> parse incoming packet error: packet dropped 
[2021-08-05 15:06:59] [WARNING]: Bot已离线: session expired 

**复现方法**

不同服务器的几个Bot同一时间出现，删除session后正常启动

**Comment by sam01101** [comment]
#633 真当633不存在了？
![Screenshot_20210805-151846](https://user-images.githubusercontent.com/25792361/128308285-cef9c922-53c4-4704-ad92-9707e4d1264f.png)

**Comment by xxyy3130** [comment]
> #633 真当633不存在了？
> ![Screenshot_20210805-151846](https://user-images.githubusercontent.com/25792361/128308285-cef9c922-53c4-4704-ad92-9707e4d1264f.png)

额，他们不是登陆出错吗，运行中出现这个也是一样么...

**Comment by sam01101** [comment]
> > #633 真当633不存在了？
> > ![Screenshot_20210805-151846](https://user-images.githubusercontent.com/25792361/128308285-cef9c922-53c4-4704-ad92-9707e4d1264f.png)
> 
> 额，他们不是登陆出错吗，运行中出现这个也是一样么...

你是因为突然掉线而重连才出现的吧，这
但session也过期了
和他们是一样的（结果），他们也是过期了

**Comment by xxyy3130** [comment]
> > > #633 真当633不存在了？
> > > ![Screenshot_20210805-151846](https://user-images.githubusercontent.com/25792361/128308285-cef9c922-53c4-4704-ad92-9707e4d1264f.png)
> > 
> > 
> > 额，他们不是登陆出错吗，运行中出现这个也是一样么...
> 
> 你是因为突然掉线而重连才出现的吧，这
> 但session也过期了
> 和他们是一样的（结果），他们也是过期了

好的，我删除了再观察观察
