### ISSUE TITLE
语音发送失败，上传语音失败

### ISSUE THREAD

**Issue by ujmyvq1582** [Mrs4s/go-cqhttp#993]
**环境信息**

go-cqhttp版本: 1.0beta5
运行环境: linux
连接方式: http
使用协议: ipad

**bug内容**

当用cq发送语音的时候，会弹出以下信息。
[2021-08-05 22:35:57] [WARNING]: 警告: 群 xxxxxxxxx 消息语音上传失败: connect error: dial tcp 182.254.57.123:80: connect
: connection timed out
**复现方法**

1.用http直接请求发送语音的CQ码，例如：
curl http://127.0.0.1:5700/send_msg?group_id=xxxxxxxx&message=[CQ,record,file=file:///data/1.mp3]
2.会直接返回错误信息。
去看日志就是上面的示例。

**Comment by wdvxdr1123** [comment]
似乎和 #983 是一个问题

**Comment by Mrs4s** [comment]
#983
