### ISSUE TITLE
可以选择收到消息后不标记已读吗，或者可以配置不接收指定群或只接收指定群的消息吗

### ISSUE THREAD

**Issue by LHXnois** [Mrs4s/go-cqhttp#997]
**环境信息**

go-cqhttp版本: v1.0.0-beta5

**需要添加的功能内容**

~~（人机合一的时候发现没有未读消息了））~~
现在的gocq在收到消息后会标记已读，同时登录的其他客户端上就看不到未读消息了，可以选择不标记已读吗，更进一步的，可以只对指定的群消息标记已读吗，或者可以配置不接收指定群或只接收指定群的消息吗
我看到有个事件过滤器，但是好像只是用来配置接收到消息后是否上报的

**Comment by Ink-33** [comment]
https://github.com/Mrs4s/go-cqhttp/issues/965#issuecomment-886053244

#902

供参考

**Comment by LHXnois** [comment]
了解了，感谢
期待新版本

**Comment by zzm88** [comment]
我也需要这个功能：只把群消息自动标记为已读，私信不进行已读标记。

**Comment by LHXnois** [comment]
> 我也需要这个功能：只把群消息自动标记为已读，私信不进行已读标记。

beta6已经有api了，你看更新说明
只不过文档好像还没更新
